/**
 *   @file  aoaprochwa.h
 *
 *   @brief
 *      Implements Data path processing functionality.
 *
 *  \par
 *  NOTE:
 *      (C) Copyright 2018 Texas Instruments, Inc.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**************************************************************************
 *************************** Include Files ********************************
 **************************************************************************/
#ifndef AOAPROC_HWA_H
#define AOAPROC_HWA_H

/* Standard Include Files. */
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

/* mmWave SDK Driver/Common Include Files */
#include <ti/drivers/osal/SemaphoreP.h>
#include <ti/drivers/hwa/hwa.h>

/* Datapath files */
#include <ti/datapath/dpif/dpif_radarcube.h>
#include <ti/datapath/dpif/dpif_pointcloud.h>
#include <ti/datapath/dpedma/dpedma.h>
#include <ti/datapath/dpif/dp_error.h>
#include <ti/datapath/dpc/dpu/aoaproc/aoaproc_common.h>

/** @defgroup DPU_AOAPROC_EXTERNAL       aoaProcHWA DPU External
 */
/**
@defgroup DPU_AOAPROC_EXTERNAL_FUNCTION            aoaProcHWA DPU External Functions
@ingroup DPU_AOAPROC_EXTERNAL
@brief
*   The section has a list of all the exported API which the user need to
*   invoke in order to use the aoaProc DPU
*/
/**
@defgroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE      aoaProcHWA DPU External Data Structures
@ingroup DPU_AOAPROC_EXTERNAL
@brief
*   The section has a list of all the data structures which are exposed to the user
*/
/**
@defgroup DPU_AOAPROC_EXTERNAL_DEFINITIONS      aoaProcHWA DPU External Definitions
@ingroup DPU_AOAPROC_EXTERNAL
@brief
*   The section has a list of all the definitions which are exposed to the user
*/
/**
@defgroup DPU_AOAPROC_ERROR_CODE                   aoaProcHWA DPU Error Codes
@ingroup DPU_AOAPROC_EXTERNAL
@brief
*   The section has a list of all the error codes which are generated by the sampleProc DPU
*/

/** @addtogroup DPU_AOAPROC_EXTERNAL_DEFINITIONS
 *
 @{ */

/*! @brief Number of HWA parameter sets */
#define DPU_AOAPROCHWA_NUM_HWA_PARAM_SETS  3U

/*! @brief Alignment for memory allocation purpose. There is CPU access of this buffer
 *         in the implementation.
 */
#define DPU_AOAPROCHWA_CFAR_DET_LIST_BYTE_ALIGNMENT          DPIF_CFAR_DET_LIST_CPU_BYTE_ALIGNMENT

/*! @brief Alignment for memory allocation purpose. There is CPU access of this buffer
 *         in the implementation.
 */
#define DPU_AOAPROCHWA_POINT_CLOUD_CARTESIAN_BYTE_ALIGNMENT  DPIF_POINT_CLOUD_CARTESIAN_CPU_BYTE_ALIGNMENT

/*! @brief Alignment for memory allocation purpose. There is CPU access of this buffer
 *         in the implementation.
 */
#define DPU_AOAPROCHWA_POINT_CLOUD_SIDE_INFO_BYTE_ALIGNMENT  DPIF_POINT_CLOUD_SIDE_INFO_CPU_BYTE_ALIGNMENT

/*! @brief Alignment for memory allocation purpose. There is CPU access of this buffer
 *         in the implementation.
 */
#define DPU_AOAPROCHWA_AZIMUTH_STATIC_HEAT_MAP_BYTE_ALIGNMENT (sizeof(int16_t))

/*! @brief Alignment for memory allocation purpose. There is CPU access of this buffer
 *         in the implementation.
 */
#define DPU_AOAPROCHWA_DET_OBJ_ELEVATION_ANGLE_BYTE_ALIGNMENT (sizeof(float))

/*! @brief   Size of azimuth FFT */
#define DPU_AOAPROCHWA_NUM_ANGLE_BINS 64

/*! When elevation is enabled, FFT buffers can hold a maximum of 64 objects.
   A: Hwa memory size (M3) = 16KB
   B: Azimuth FFT size = 64
   C: Complex sample size = 4 bytes
   Maximum number of objects = A / (B*C) = 64*/
#define DPU_AOAPROCHWA_MAX_OBJ_WITH_3_TX_ANT 64

/*! With elevation disabled, FFT buffers can hold a maximum of 256 objects.
   A: Hwa memory size (M2+M3) = 32KB
   B: Azimuth FFT size = 64
   C: log magnitude sample size = 2 bytes
   Maximum number of objects = A / (B*C) = 256 */
#define DPU_AOAPROCHWA_MAX_OBJ_WITH_2_TX_ANT 256

/**
@}
*/

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup DPU_AOAPROC_ERROR_CODE
 *  Base error code for the aoaProc DPU is defined in the
 *  \include ti/datapath/dpif/dp_error.h
 @{ */

/**
 * @brief   Error Code: Invalid argument (general e.g NULL pointers)
 */
#define DPU_AOAPROCHWA_EINVAL                  (DP_ERRNO_AOA_PROC_BASE-1)

/**
 * @brief   Error Code: Invalid argument - radar cube format
 */
#define DPU_AOAPROCHWA_EINVAL__RADARCUBE_DATAFORMAT  (DP_ERRNO_AOA_PROC_BASE-2)

/**
 * @brief   Error Code: Out of memory when allocating using MemoryP_osal
 */
#define DPU_AOAPROCHWA_ENOMEM                               (DP_ERRNO_AOA_PROC_BASE-20)

/**
 * @brief   Error Code: Memory not aligned for @ref DPU_AoAProcHWA_HW_Resources::cfarRngDopSnrList
 */
#define DPU_AOAPROCHWA_ENOMEMALIGN_CFAR_DET_LIST            (DP_ERRNO_AOA_PROC_BASE-21)

/**
 * @brief   Error Code: Memory not aligned for @ref DPU_AoAProcHWA_HW_Resources::detObjOut
 */
#define DPU_AOAPROCHWA_ENOMEMALIGN_POINT_CLOUD_CARTESIAN    (DP_ERRNO_AOA_PROC_BASE-22)

/**
 * @brief   Error Code: Memory not aligned for @ref DPU_AoAProcHWA_HW_Resources::detObjOutSideInfo
 */
#define DPU_AOAPROCHWA_ENOMEMALIGN_POINT_CLOUD_SIDE_INFO    (DP_ERRNO_AOA_PROC_BASE-23)

/**
 * @brief   Error Code: Insufficient memory allocated for azimuth static heat map
 */
#define DPU_AOAPROCHWA_ENOMEM__AZIMUTH_STATIC_HEAT_MAP      (DP_ERRNO_AOA_PROC_BASE-24)

/**
 * @brief   Error Code: Memory not aligned for @ref DPU_AoAProcHWA_HW_Resources::azimuthStaticHeatMap
 */
#define DPU_AOAPROCHWA_ENOMEMALIGN_AZIMUTH_STATIC_HEAT_MAP  (DP_ERRNO_AOA_PROC_BASE-25)

/**
 * @brief   Error Code: Memory not aligned for @ref DPU_AoAProcHWA_HW_Resources::detObjElevationAngle
 */
#define DPU_AOAPROCHWA_ENOMEMALIGN_DET_OBJ_ELEVATION_ANGLE  (DP_ERRNO_AOA_PROC_BASE-26)

/**
 * @brief   Error Code: azimuth heat-map flag enabled and single virtual antenna not valid combination
 */
#define DPU_AOAPROCHWA_EINVALID_NUM_VIRT_ANT_AND_AZIMUTH_STATIC_HEAT_MAP (DP_ERRNO_AOA_PROC_BASE-27)

/**
 * @brief   Error Code: Configure parameters exceed HWA memory bank size
 */
#define DPU_AOAPROCHWA_EEXCEEDHWAMEM (DP_ERRNO_AOA_PROC_BASE-28)

/**
 * @brief   Error Code: Internal error
 */
#define DPU_AOAPROCHWA_EINTERNAL               (DP_ERRNO_AOA_PROC_BASE-30)

/**
 * @brief   Error Code: Not implemented
 */
#define DPU_AOAPROCHWA_ENOTIMPL                (DP_ERRNO_AOA_PROC_BASE-40)

/**
 * @brief   Error Code: Semaphore error
 */
#define DPU_AOAPROCHWA_ESEMA                   (DP_ERRNO_AOA_PROC_BASE-50)

/**
@}
*/


/**
* @brief
*  AoAProcHWA DPU control command
*
* @details
*  The enum defines the AoAProcHWA supported run time command
*
*  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
*/
typedef enum DPU_AoAProcHWA_Cmd_e
{
 /*! @brief     Command to update field of view configuration, azimuth and elevation selected range*/
 DPU_AoAProcHWA_Cmd_FovAoACfg,
 /*! @brief     Command to update multiobject beam forming configuration */
 DPU_AoAProcHWA_Cmd_MultiObjBeamFormingCfg,
 /*! @brief     Command to update rx channel phase compensation */
 DPU_AoAProcHWA_Cmd_CompRxChannelBiasCfg,
 /*! @brief     Command to update Azimuth heat-map configuration */
 DPU_AoAProcHWA_Cmd_PrepareRangeAzimuthHeatMap
} DPU_AoAProcHWA_Cmd;

/**
 * @brief
 *  AoAProcHWA DPU configuration
 *
 * @details
 *  The structure is used to hold the HWA configuration needed for AOA
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_AoAProcHWA_hwaAoAConfig_t
{
    /** @brief     HWA paramset Start index */
    uint8_t    paramSetStartIdx;

    /** @brief     number of HWA paramset, must be @ref DPU_AOAPROCHWA_NUM_HWA_PARAM_SETS */
    uint8_t    numParamSet;

    /*! @brief     Flag to indicate if HWA windowing is symmetric
                    see HWA_WINDOW_SYMM definitions in HWA driver's doxygen documentation
     */
    uint8_t   winSym;

    /*! @brief Doppler FFT window size in bytes.
         This is the number of coefficients to be programmed in the HWA for the windowing
         functionality. The size is a function of @ref DPU_AoAProcHWA_StaticConfig::numDopplerChirps as follows:\n
         If non-symmetric window is selected: windowSize = numDopplerChirps * sizeof(int32_t) \n
         If symmetric window is selected and numDopplerChirps is even:
         windowSize = numDopplerChirps * sizeof(int32_t) / 2 \n
         If symmetric window is selected and numDopplerChirps is odd:
         windowSize = (numDopplerChirps + 1) * sizeof(int32_t) / 2
    */
    uint32_t    windowSize;

    /*! @brief Pointer to doppler FFT window coefficients. */
    int32_t     *window;

    /*! @brief   Offset in HWA window RAM for singleBin doppler FFT
     *            in number of samples */
    uint32_t     winRamOffset;
}DPU_AoAProcHWA_hwaAoAConfig;

/**
 * @brief
 *  AoAProcHWA DPU initial configuration parameters
 *
 * @details
 *  The structure is used to hold the DPU initial configurations parameters.
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_AoAProcHWA_InitParams_t
{
    /*! @brief HWA Handle */
    HWA_Handle  hwaHandle;
}DPU_AoAProcHWA_InitParams;

/**
 * @brief
 *  AoAProcHWA DPU Hardware resources
 *
 * @details
 *  AoAProcHWA DPU Hardware resources
 *
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef struct DPU_AoAProcHWA_Resources_t
{
    /*! @brief     EDMA Handle */
    EDMA_Handle         edmaHandle;

    /*! @brief     EDMA configuration for AOA data In */
    DPEDMA_ChanCfg       edmaHwaIn;

    /*! @brief     EDMA configuration for AOA data In signaure */
    DPEDMA_ChanCfg       edmaHwaInSignature;

    /*! @brief     EDMA configuration for AOA data Out */
    DPEDMA_ChanCfg       edmaHwaOut;

    /*! @brief     HWA Configuration */
    DPU_AoAProcHWA_hwaAoAConfig    hwaCfg;

    /*! @brief     Radar Cube structure */
    DPIF_RadarCube      radarCube;

    /*! @brief      List of CFAR detected objects of @ref cfarRngDopSnrListSize elements,
     *              must be aligned to @ref DPU_AOAPROCHWA_CFAR_DET_LIST_BYTE_ALIGNMENT */
    DPIF_CFARDetList *cfarRngDopSnrList;

    /*! @brief      CFAR detected objects list size */
    uint16_t        cfarRngDopSnrListSize;

    /*! @brief      Detected objects output list sized to @ref detObjOutMaxSize elements,
     *              must be aligned to @ref DPU_AOAPROCHWA_POINT_CLOUD_CARTESIAN_BYTE_ALIGNMENT  */
    DPIF_PointCloudCartesian *detObjOut;

    /*! @brief      Detected objects side information (snr + noise) output list,
     *              sized to @ref detObjOutMaxSize elements,
     *              must be aligned to @ref DPU_AOAPROCHWA_POINT_CLOUD_SIDE_INFO_BYTE_ALIGNMENT */
    DPIF_PointCloudSideInfo *detObjOutSideInfo;

    /*! @brief      This field dimensions several other fields in this structure as
     *              referred in their descriptions. It is determined by the dpc/application based
     *              on balancing between maximum number of objects expected to be
     *              detected in the scene (this can depend on configuration like cfar thresholds,
     *              static clutter removal etc) and memory and MIPS limitations. */
    uint32_t        detObjOutMaxSize;

    /*! @brief      Pointer to range-azimuth static heat map, this is a 2D FFT
     *              array in range direction (x[numRangeBins][numVirtualAntAzim]),
     *              at doppler index 0, sized to @ref azimuthStaticHeatMapSize elements of
     *              type cplx16ImRe_t.
     *              Alignment should be @ref DPU_AOAPROCHWA_AZIMUTH_STATIC_HEAT_MAP_BYTE_ALIGNMENT */
    cmplx16ImRe_t   *azimuthStaticHeatMap;

    /*! @brief      Number of elements of azimuthStaticHeatMap, this should be
     *              numVirtualAntAzim * numRangeBins */
    uint32_t        azimuthStaticHeatMapSize;

    /*! @brief      Detected objects azimuth index for debugging,
     *              sized to @ref detObjOutMaxSize elements */
    uint8_t         *detObj2dAzimIdx;

    /*! @brief      Detected object elevation angle for debugging,
     *              sized to @ref detObjOutMaxSize elements, must be aligned to
     *              @ref DPU_AOAPROCHWA_DET_OBJ_ELEVATION_ANGLE_BYTE_ALIGNMENT */
    float           *detObjElevationAngle;

} DPU_AoAProcHWA_HW_Resources;

/**
 * @brief
 *  AoAProcHWA DPU static configuration parameters
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 *
 * @details
 * The following conditions must be satisfied:
 *    @verbatim
      numTxAntennas * numRxAntennas * numDopplerChirps * sizeof(cmplx16ImRe_t) <= 16 KB (one HWA memory bank)
      numTxAntennas * numRxAntennas * numDopplerBins * sizeof(cmplx16ImRe_t) <= 32 KB (two HWA memory banks)
      @endverbatim
 *
 */
typedef struct DPU_AoAProcHWA_StaticConfig_t
{
    /*! @brief  Number of transmit antennas */
    uint8_t     numTxAntennas;

    /*! @brief  Number of receive antennas */
    uint8_t     numRxAntennas;

    /*! @brief  Number of virtual azimuth antennas */
    uint8_t     numVirtualAntAzim;

    /*! @brief  Number of virtual elevation antennas */
    uint8_t     numVirtualAntElev;

    /*! @brief  Number of range bins */
    uint16_t    numRangeBins;

    /*! @brief Number of chirps for Doppler computation purposes.
               For example, in TDM/BPM-MIMO scheme, this is the physical chirps
               in a frame per transmit antenna
               i.e numDopplerChirps = numChirpsPerFrame / numTxAntennas */
    uint16_t    numDopplerChirps;

    /*! @brief  Number of doppler bins */
    uint16_t    numDopplerBins;

    /*! @brief  Range conversion factor for range FFT index to meters */
    float       rangeStep;

    /*! @brief  Doppler conversion factor for Doppler FFT index to m/s */
    float       dopplerStep;
} DPU_AoAProcHWA_StaticConfig;

/**
 * @brief
 *  AoAProcHWA DPU configuration
 *
 * @details
 *  The structure is used to hold the AoAProcHWA configuration
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_AoAProcHWA_Config_t
{
    /*! @brief     Data path common parameters */
    DPU_AoAProcHWA_StaticConfig   staticCfg;

    /*! @brief     Hardware resources */
    DPU_AoAProcHWA_HW_Resources res;

    /*! @brief     Dynamic configuration */
    DPU_AoAProc_DynamicConfig dynCfg;

}DPU_AoAProcHWA_Config;

/**
 * @brief
 *  Output parameters populated during Processing time
 *
 * @details
 *  The structure is used to hold the output parameters
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_AoAProcHWA_OutParams_t
{

    /*! @brief     AoAProcHWA stats */
    DPU_AoAProc_Stats       stats;

    /*! @brief      Number of AoA DPU detected points*/
    uint32_t numAoADetectedPoints;

}DPU_AoAProcHWA_OutParams;

/**
 * @brief
 *  AoAProcHWA DPU Handle
 *
 *
 *  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef void* DPU_AoAProcHWA_Handle ;

/**
 *  @b Description
 *  @n
 *      The function is AoAProcHWA DPU initialization function. It allocates memory to store
 *  its internal data object and returns a handle if it executes successfully.
 *
 *  @param[in]  initParams              Pointer to initialization parameters
 *
 *  @param[in]  errCode                 Pointer to errCode generates from the API
 *
 *  \ingroup    DPU_AOAPROC_EXTERNAL_FUNCTION
 *
 *  @retval
 *      Success     - valid AoAProcHWA handle
 *  @retval
 *      Error       - NULL
 */
DPU_AoAProcHWA_Handle DPU_AoAProcHWA_init
(
    DPU_AoAProcHWA_InitParams *initParams,
    int32_t*            errCode
);

/**
 *  @b Description
 *  @n
 *      The function is AoAProcHWA DPU configuration function. It saves buffer pointer and configurations
 *  including system resources and configures EDMA for runtime range processing.
 *
 *  @pre    DPU_AoAProcHWA_init() has been called
 *
 *  @param[in]  handle                  AoAProcHWA DPU handle
 *  @param[in]  aoaHwaCfg              Pointer to AoAProcHWA configuration data structure
 *
 *  \ingroup    DPU_AOAPROC_EXTERNAL_FUNCTION
 *
 *  @retval
 *      Success     - 0
 *  @retval
 *      Error       - <0
 */
int32_t DPU_AoAProcHWA_config
(
    DPU_AoAProcHWA_Handle    handle,
    DPU_AoAProcHWA_Config    *aoaHwaCfg
);

/**
 *  @b Description
 *  @n
 *      The function is AoAProcHWA DPU process function. It performs CFAR detection using HWA
 *
 *  @pre    DPU_AoAProcHWA_init() has been called
 *
 *  @param[in]  handle                  AoAProcHWA DPU handle
 *
 *  @param[in]  numObjsIn               Number of detected objects by CFAR DPU
 *
 *  @param[in]  outParams               DPU output parameters
 *
 *  \ingroup    DPU_AOAPROC_EXTERNAL_FUNCTION
 *
 *  @retval
 *      Success = 0
 *  @retval
 *      Error  != 0
 */
uint32_t DPU_AoAProcHWA_process
(
    DPU_AoAProcHWA_Handle    handle,
    uint32_t        numObjsIn,
    DPU_AoAProcHWA_OutParams  *outParams
);

/**
 *  @b Description
 *  @n
 *      The function is AoAProcHWA DPU control function.
 *
 *  @pre     DPU_AoAProcHWA_init() has been called
 *
 *  @param[in]  handle           AoAProcHWA DPU handle
 *  @param[in]  cmd              AoAProcHWA DPU control command
 *  @param[in]  arg              AoAProcHWA DPU control argument pointer
 *  @param[in]  argSize          AoAProcHWA DPU control argument size
 *
 *  \ingroup    DPU_AOAPROC_EXTERNAL_FUNCTION
 *
 *  @retval
 *      Success     - 0
 *  @retval
 *      Error       - <0
 */
int32_t DPU_AoAProcHWA_control
(
   DPU_AoAProcHWA_Handle handle,
   DPU_AoAProcHWA_Cmd cmd,
   void *arg,
   uint32_t argSize
);

/**
 *  @b Description
 *  @n
 *      The function is AoAProcHWA DPU deinitialization function. It frees up the
 *   resources allocated during initialization.
 *
 *  @pre    DPU_AoAProcHWA_init() has been called
 *
 *  @param[in]  handle           AoAProcHWA DPU handle
 *
 *  \ingroup    DPU_AOAPROC_EXTERNAL_FUNCTION
 *
 *  @retval
 *      Success     - 0
 *  @retval
 *      Error       - <0
 */
int32_t DPU_AoAProcHWA_deinit
(
    DPU_AoAProcHWA_Handle handle
);

#ifdef __cplusplus
}
#endif

#endif
