RF Parser External Functions
RF Parser External Functions
Mmwdemo RFparser External
The section has a list of all the exported API which the applications need to invoke in order to use the RF Parser.
Functions
int32_t MmwDemo_RFParser_parseConfig (MmwDemo_RFParserOutParams *outParams, uint8_t subFrameIdx, MMWave_OpenCfg *openCfg, MMWave_CtrlCfg *ctrlCfg, MmwDemo_ADCBufCfg *adcBufCfg, float rfFreqScaleFactor)
Detailed Description
The section has a list of all the exported API which the applications need to invoke in order to use the RF Parser.
Function Documentation
int32_t MmwDemo_RFParser_parseConfig (MmwDemo_RFParserOutParams * outParams, uint8_t subFrameIdx, MMWave_OpenCfg * openCfg, MMWave_CtrlCfg * ctrlCfg, MmwDemo_ADCBufCfg * adcBufCfg, float rfFreqScaleFactor)
Description
The function is used to parse chirp/profile configurations and save configuration and derived parameter in datapath parameter structure.
Parameters
[out] outParams Pointer to parameters generated after parsing configuration
[in] subFrameIdx Sub-frame index
[in] openCfg Pointer to the MMWave Open configuration
[in] ctrlCfg Pointer to the MMWave Control configuration
[in] adcBufCfg Pointer to ADCBuf configuration
[in] rfFreqScaleFactor RF frequency scale factor, see SOC_getDeviceRFFreqScaleFactor API
Return values
Success - = 0
Error - < 0, one of RF Parser Error Codes
Definition at line 790 of file mmwdemo_rfparser.c.
References MMWDEMO_RFPARSER_EINVAL__NUM_SUBFRAMES, MmwDemo_RFParser_parseADCBufCfg(), and MmwDemo_RFParser_parseCtrlConfig().
Referenced by MmwDemo_dataPathConfig(), and MmwDemo_RFParser_parseADCBufCfg().
Copyright 2018, Texas Instruments Incorporated