xwr18xx/mmw/mss/mss_main.c File Reference
mss_main.c File Reference
This is the main file which implements the millimeter wave Demo.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/drivers/pinmux/pinmux.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/control/dpm/dpm.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/uart/UART.h>
#include <ti/utils/cli/cli.h>
#include <ti/utils/mathutils/mathutils.h>
#include <ti/demo/xwr18xx/mmw/include/mmw_config.h>
#include <ti/demo/utils/mmwdemo_rfparser.h>
#include <ti/demo/utils/mmwdemo_adcconfig.h>
#include <ti/demo/xwr18xx/mmw/include/mmw_output.h>
#include <ti/demo/xwr18xx/mmw/mss/mmw_mss.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
Macros
#define MMWDEMO_CLI_TASK_PRIORITY 3
Task Priority settings: Mmwave task is at higher priority because of potential async messages from BSS that need quick action in real-time.
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 4
#define MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY 5
#define DPC_OBJDET_INSTANCEID (0xFEEDFEED)
Functions
void MmwDemo_CLIInit (uint8_t taskPriority)
static void MmwDemo_dataPathOpen (void)
static int32_t MmwDemo_dataPathConfig (void)
static void MmwDemo_dataPathStart (void)
static void MmwDemo_dataPathStop (void)
static void MmwDemo_handleObjectDetResult (DPM_Buffer *ptrResult)
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1)
static void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, DPC_ObjectDetection_ExecuteResult *result, MmwDemo_output_message_stats *timingInfo)
Transmits detection data over UART.
static void MmwDemo_measurementResultOutput (DPU_AoAProc_compRxChannelBiasCfg *compRxChanCfg)
static int32_t MmwDemo_DPM_ioctl_blocking (DPM_Handle handle, uint32_t cmd, void *arg, uint32_t argLen)
static int32_t MmwDemo_processPendingDynamicCfgCommands (uint8_t subFrameIndx)
static void MmwDemo_initTask (UArg arg0, UArg arg1)
static void MmwDemo_platformInit (MmwDemo_platformCfg *config)
static void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
static int32_t MmwDemo_mmWaveCtrlStop (void)
static int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t *payload)
void MmwDemo_sleep (void)
void _MmwDemo_debugAssert (int32_t expression, const char *file, int32_t line)
static void MmwDemo_setSubFramePendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg, uint32_t offset)
static uint8_t MmwDemo_isObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static uint8_t MmwDemo_isObjDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
static uint8_t MmwDemo_isObjDetCommonCfgInNonPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static uint8_t MmwDemo_isObjDynCfgInNonPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
static void MmwDemo_resetObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static void MmwDemo_resetObjDetDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
uint8_t MmwDemo_isAllCfgInPendingState (void)
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
void MmwDemo_CfgUpdate (void *srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
static uint8_t MmwDemo_getNextSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames)
static uint8_t MmwDemo_getPrevSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames)
static void mmwDemo_mssDPMTask (UArg arg0, UArg arg1)
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
int32_t MmwDemo_configSensor (void)
int32_t MmwDemo_startSensor (void)
static void MmwDemo_sensorStopEpilog (void)
void MmwDemo_stopSensor (void)
int main (void)
Variables
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
MmwDemo_HSRAM gHSRAM
Global Variable for HSRAM buffer used to share results to remote.
Detailed Description
This is the main file which implements the millimeter wave Demo.
NOTE: (C) Copyright 2018 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file mss_main.c.
Macro Definition Documentation
#define DPC_OBJDET_INSTANCEID (0xFEEDFEED)
Definition at line 467 of file mss_main.c.
Referenced by MmwDemo_DPC_ObjectDetection_reportFxn(), and MmwDemo_initTask().
#define MMWDEMO_CLI_TASK_PRIORITY 3
Task Priority settings: Mmwave task is at higher priority because of potential async messages from BSS that need quick action in real-time.
CLI task must be at a lower priority than object detection dpm task priority because the dynamic CLI command handling in the objection detection dpm task assumes CLI task is held back during this processing. The alternative is to use a semaphore between the two tasks.
Definition at line 459 of file mss_main.c.
Referenced by MmwDemo_initTask().
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 4
Definition at line 460 of file mss_main.c.
Referenced by MmwDemo_initTask().
#define MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY 5
Definition at line 461 of file mss_main.c.
Referenced by MmwDemo_initTask().
Function Documentation
void _MmwDemo_debugAssert (int32_t expression, const char * file, int32_t line)
Description
Send assert information through CLI.
Definition at line 549 of file mss_main.c.
References CLI_write().
int main (void)
Description
Entry point into the Millimeter Wave Demo
Return values
Not Applicable.
Definition at line 2708 of file mss_main.c.
References MmwDemo_TaskHandles_t::initTask, MmwDemo_debugAssert, MmwDemo_initTask(), MmwDemo_MSS_MCB_t::socHandle, and MmwDemo_MSS_MCB_t::taskHandles.
void MmwDemo_CfgUpdate (void * srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
Description
Utility function to apply configuration to specified sub-frame
Parameters
[in] srcPtr Pointer to configuration
[in] offset Offset of configuration within the parent structure
[in] size Size of configuration
[in] subFrameNum Sub-frame Number (0 based) to apply to, broadcast to all sub-frames if special code MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG
Return values
Success - 0
Error - <0
Definition at line 802 of file mss_main.c.
References MmwDemo_setSubFramePendingState(), MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG, MmwDemo_SubFrameCfg_t::objDetDynCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIGuiMonSel(), and MmwDemo_CLIMultiObjBeamForming().
void MmwDemo_CLIInit (uint8_t taskPriority)
HSRAM for processing results
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 821 of file mmw_cli.c.
References CLI_open(), CLI_Cfg_t::cliBanner, CLI_Cfg_t::cliPrompt, CLI_Cfg_t::cliUartHandle, CLI_CmdTableEntry_t::cmd, CLI_CmdTableEntry_t::cmdHandlerFxn, MmwDemo_MSS_MCB_t::commandUartHandle, MmwDemo_MSS_MCB_t::ctrlHandle, CLI_Cfg_t::enableMMWaveExtension, CLI_CmdTableEntry_t::helpString, CLI_Cfg_t::mmWaveHandle, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), CLI_Cfg_t::socHandle, MmwDemo_MSS_MCB_t::socHandle, CLI_Cfg_t::tableEntry, CLI_Cfg_t::taskPriority, and CLI_Cfg_t::usePolledMode.
Referenced by MmwDemo_initTask().
int32_t MmwDemo_configSensor (void)
Description
MMW demo helper Function to configure sensor. User need to fill gMmwMssMCB.cfg.ctrlCfg and add profiles/chirp to mmWave before calling this function
Return values
Success - 0
Error - <0
Definition at line 2275 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_config(), MMWave_decodeError(), and MmwDemo_dataPathConfig().
Referenced by MmwDemo_CLISensorStart().
static int32_t MmwDemo_dataPathConfig (void) static
Description
The function is used to configure the data path based on the chirp profile. After this function is executed, the data path processing will ready to go when the ADC buffer starts receiving samples corresponding to the chirps.
Return values
Success - 0
Error - <0
Definition at line 1261 of file mss_main.c.
References DPIF_ADCBufProperty_t::adcBits, MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_SubFrameCfg_t::adcBufChanDataSize, MmwDemo_RFParserOutParams_t::adcBufChanDataSize, DPC_ObjectDetection_StaticCfg_t::ADCBufData, MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_ADCBufCfg_t::adcFmt, MMWave_CtrlCfg_t::advancedFrameCfg, MmwDemo_MSS_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_Cfg_t::ctrlCfg, DPIF_ADCBufData_t::data, DPIF_ADCBufProperty_t::dataFmt, DPIF_ADCBufData_t::dataProperty, DPIF_ADCBufData_t::dataSize, MMWave_CtrlCfg_t::dfeDataOutputMode, DPC_ObjectDetection_StaticCfg_t::dopplerStep, MmwDemo_RFParserOutParams_t::dopplerStep, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPIF_DATAFORMAT_COMPLEX16_IMRE, DPIF_DATAFORMAT_COMPLEX16_REIM, DPIF_RXCHAN_INTERLEAVE_MODE, DPIF_RXCHAN_NON_INTERLEAVE_MODE, DPC_ObjectDetection_PreStartCfg_t::dynCfg, MmwDemo_DPC_ObjDet_DynCfg_t::dynCfg, MMWave_AdvancedFrameCfg_t::frameCfg, MmwDemo_SubFrameCfg_t::guiMonSel, DPIF_ADCBufProperty_t::interleave, MmwDemo_ADCBufCfg_t::iqSwapSel, DPC_ObjectDetection_StaticCfg_t::isValidProfileHasOneTxPerChirp, MMWave_DFEDataOutputMode_ADVANCED_FRAME, MmwDemo_ADCBufConfig(), MmwDemo_debugAssert, MmwDemo_DPM_ioctl_blocking(), MmwDemo_resetObjDetCommonCfgPendingState(), MmwDemo_resetObjDetDynCfgPendingState(), MmwDemo_RFParser_parseConfig(), DPIF_ADCBufProperty_t::numAdcSamples, MmwDemo_RFParserOutParams_t::numAdcSamples, DPIF_ADCBufProperty_t::numChirpsPerChirpEvent, MmwDemo_RFParserOutParams_t::numChirpsPerChirpEvent, MmwDemo_SubFrameCfg_t::numChirpsPerChirpEvent, DPC_ObjectDetection_StaticCfg_t::numChirpsPerFrame, MmwDemo_RFParserOutParams_t::numChirpsPerFrame, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, MmwDemo_SubFrameCfg_t::numDopplerBins, MmwDemo_RFParserOutParams_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, MmwDemo_RFParserOutParams_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numRangeBins, MmwDemo_SubFrameCfg_t::numRangeBins, MmwDemo_RFParserOutParams_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, MmwDemo_RFParserOutParams_t::numRxAntennas, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, MmwDemo_RFParserOutParams_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntAzim, MmwDemo_RFParserOutParams_t::numVirtualAntAzim, DPC_ObjectDetection_StaticCfg_t::numVirtualAntElev, MmwDemo_RFParserOutParams_t::numVirtualAntElev, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, MmwDemo_RFParserOutParams_t::numVirtualAntennas, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_Cfg_t::openCfg, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, DPC_ObjectDetection_StaticCfg_t::rangeStep, MmwDemo_RFParserOutParams_t::rangeStep, MmwDemo_MSS_MCB_t::rfFreqScaleFactor, DPC_ObjectDetection_StaticCfg_t::rxAntOrder, MmwDemo_RFParserOutParams_t::rxAntOrder, DPIF_ADCBufProperty_t::rxChanOffset, SOC_XWR18XX_MSS_ADCBUF_BASE_ADDRESS, MmwDemo_MSS_MCB_t::socHandle, DPC_ObjectDetection_PreStartCfg_t::staticCfg, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_PreStartCfg_t::subFrameNum, DPC_ObjectDetection_StaticCfg_t::txAntOrder, MmwDemo_RFParserOutParams_t::txAntOrder, and MmwDemo_RFParserOutParams_t::validProfileHasOneTxPerChirp.
Referenced by MmwDemo_configSensor().
static void MmwDemo_dataPathOpen (void) static
Description
Perform Data path driver open
Return values
Not Applicable.
Definition at line 1240 of file mss_main.c.
References MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_ADCBufOpen(), and MmwDemo_debugAssert.
Referenced by MmwDemo_openSensor().
static void MmwDemo_dataPathStart (void) static
Description
The function is used to Start data path to handle chirps from front end.
Return values
Not Applicable.
Definition at line 1467 of file mss_main.c.
References DPM_start(), MmwDemo_MSS_MCB_t::DPMstartSemHandle, MmwDemo_debugAssert, and MmwDemo_MSS_MCB_t::objDetDpmHandle.
Referenced by MmwDemo_startSensor().
static void MmwDemo_dataPathStop (void) static
Description
The function is used to stop data path.
Return values
Not Applicable.
Definition at line 1495 of file mss_main.c.
References DPM_stop(), MmwDemo_debugAssert, and MmwDemo_MSS_MCB_t::objDetDpmHandle.
Referenced by MmwDemo_eventCallbackFxn().
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1) static
Description
DPM Registered Report Handler. The DPM Module uses this registered function to notify the application about DPM reports.
Parameters
[in] reportType Report Type
[in] instanceId Instance Identifier which generated the report
[in] errCode Error code if any.
[in] arg0 Argument 0 interpreted with the report type
[in] arg1 Argument 1 interpreted with the report type
Return values
Not Applicable.
Definition at line 1628 of file mss_main.c.
References CLI_write(), DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreLocalRamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreLocalRamUsage, DPC_OBJDET_INSTANCEID, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPM_Report_DPC_ASSERT, DPM_Report_DPC_INFO, DPM_Report_DPC_STARTED, DPM_Report_DPC_STOPPED, DPM_Report_IOCTL, DPM_Report_NOTIFY_DPC_RESULT, DPM_Report_NOTIFY_DPC_RESULT_ACKED, MmwDemo_MSS_MCB_t::DPMioctlSemHandle, MmwDemo_MSS_MCB_t::DPMstartSemHandle, MmwDemo_MSS_MCB_t::DPMstopSemHandle, DPM_DPCAssert_t::fileName, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamUsage, DPM_DPCAssert_t::lineNum, DPC_ObjectDetection_PreStartCfg_t::memUsage, MmwDemo_handleObjectDetResult(), DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapDPCUsed, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapTotal, and DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapUsed.
Referenced by MmwDemo_eventCallbackFxn(), and MmwDemo_initTask().
static int32_t MmwDemo_DPM_ioctl_blocking (DPM_Handle handle, uint32_t cmd, void * arg, uint32_t argLen) static
Description
Help function to make DPM_ioctl blocking until response is reported
Return values
Success -0 Failed <0
Definition at line 1209 of file mss_main.c.
References DPM_ioctl(), and MmwDemo_MSS_MCB_t::DPMioctlSemHandle.
Referenced by MmwDemo_dataPathConfig(), and MmwDemo_mmWaveCtrlTask().
static int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t * payload) static
Description
Registered event function to mmwave which is invoked when an event from the BSS is received.
Parameters
[in] msgId Message Identifier
[in] sbId Subblock identifier
[in] sbLen Length of the subblock
[in] payload Pointer to the payload buffer
Return values
Always return 0
Definition at line 1527 of file mss_main.c.
References MmwDemo_MSS_Stats_t::calibrationReports, CLI_write(), MmwDemo_MSS_Stats_t::failedTimingReports, MmwDemo_MSS_Stats_t::frameTriggerReady, MmwDemo_dataPathStop(), MmwDemo_debugAssert, MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_MSS_Stats_t::sensorStopped, and MmwDemo_MSS_MCB_t::stats.
Referenced by MmwDemo_initTask().
static uint8_t MmwDemo_getNextSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames) static
Description
Utility function to get next sub-frame index
Parameters
[in] currentIndx Current sub-frame index
[in] numSubFrames Number of sub-frames
Return values
Index of next sub-frame.
Definition at line 1776 of file mss_main.c.
Referenced by MmwDemo_handleObjectDetResult().
static uint8_t MmwDemo_getPrevSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames) static
Description
Utility function to get previous sub-frame index
Parameters
[in] currentIndx Current sub-frame index
[in] numSubFrames Number of sub-frames
Return values
Index of previous sub-frame
Definition at line 1802 of file mss_main.c.
Referenced by MmwDemo_handleObjectDetResult().
static void MmwDemo_handleObjectDetResult (DPM_Buffer * ptrResult) static
Description
Function to handle frame processing results from DPC
Return values
Not Applicable.
Definition at line 2026 of file mss_main.c.
References MmwDemo_output_message_stats_t::activeFrameCPULoad, MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_SubFrameCfg_t::adcBufChanDataSize, MmwDemo_MSS_MCB_t::adcBufHandle, MmwDemo_MSS_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, DPC_ObjectDetection_ExecuteResult_t::compRxChanBiasMeasurement, DPC_OBJDET_IOCTL__DYNAMIC_EXECUTE_RESULT_EXPORTED, DPM_ioctl(), DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, MmwDemo_output_message_stats_t::interChirpProcessingMargin, MmwDemo_output_message_stats_t::interFrameCPULoad, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_output_message_stats_t::interFrameProcessingTime, MmwDemo_MSS_MCB_t::loggingUartHandle, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, MmwDemo_ADCBufConfig(), MmwDemo_debugAssert, MmwDemo_getNextSubFrameIndx(), MmwDemo_getPrevSubFrameIndx(), MmwDemo_measurementResultOutput(), MmwDemo_processPendingDynamicCfgCommands(), MmwDemo_transmitProcessedOutput(), MmwDemo_SubFrameCfg_t::numChirpsPerChirpEvent, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_Cfg_t::openCfg, MmwDemo_SubFrameStats_t::outputStats, MmwDemo_SubFrameStats_t::pendingConfigProcTime, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPM_Buffer_t::ptrBuffer, R4F_CLOCK_MHZ, DPM_Buffer_t::size, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_ExecuteResultExportedInfo_t::subFrameIdx, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, MmwDemo_SubFrameStats_t::subFramePreparationTime, MmwDemo_MSS_MCB_t::subFrameStats, SYS_COMMON_NUM_RX_CHANNEL, and MmwDemo_output_message_stats_t::transmitOutputTime.
Referenced by MmwDemo_DPC_ObjectDetection_reportFxn(), and MmwDemo_processPendingDynamicCfgCommands().
static void MmwDemo_initTask (UArg arg0, UArg arg1) static
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 2496 of file mss_main.c.
References DPM_InitCfg_t::arg, DPM_InitCfg_t::argSize, MmwDemo_MSS_MCB_t::cfg, MMWave_InitCfg_t::cfgMode, MmwDemo_platformCfg_t::commandBaudRate, MmwDemo_MSS_MCB_t::commandUartHandle, MMWave_LinkCRCCfg_t::crcChannel, MmwDemo_MSS_MCB_t::ctrlHandle, DPM_InitCfg_t::domain, MMWave_InitCfg_t::domain, DPC_OBJDET_INSTANCEID, DPM_Domain_REMOTE, DPM_init(), DPM_synch(), MmwDemo_MSS_MCB_t::DPMioctlSemHandle, MmwDemo_MSS_MCB_t::DPMstartSemHandle, MmwDemo_MSS_MCB_t::DPMstopSemHandle, MMWave_InitCfg_t::eventFxn, DPM_InitCfg_t::instanceId, MMWave_InitCfg_t::linkCRCCfg, MmwDemo_platformCfg_t::loggingBaudRate, MmwDemo_MSS_MCB_t::loggingUartHandle, MMWave_ConfigurationMode_FULL, MMWave_Domain_MSS, MMWave_ExecutionMode_ISOLATION, MMWave_init(), MMWave_sync(), MmwDemo_TaskHandles_t::mmwaveCtrl, MMWDEMO_CLI_TASK_PRIORITY, MmwDemo_CLIInit(), MmwDemo_debugAssert, MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY, MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_eventCallbackFxn(), MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY, MmwDemo_mmWaveCtrlTask(), mmwDemo_mssDPMTask(), MmwDemo_platformInit(), MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_TaskHandles_t::objDetDpmTask, MmwDemo_Cfg_t::platformCfg, DPM_InitCfg_t::ptrProcChainCfg, DPM_InitCfg_t::reportFxn, MMWave_InitCfg_t::socHandle, DPM_InitCfg_t::socHandle, MmwDemo_MSS_MCB_t::socHandle, MmwDemo_platformCfg_t::sysClockFrequency, MmwDemo_MSS_MCB_t::taskHandles, and MMWave_LinkCRCCfg_t::useCRCDriver.
Referenced by main().
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in non-pending (cleared) state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in non-pending state, else return 0
Definition at line 774 of file mss_main.c.
References MmwDemo_isObjDetCommonCfgInNonPendingState(), MmwDemo_isObjDynCfgInNonPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
uint8_t MmwDemo_isAllCfgInPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in pending state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in pending state, else return 0
Definition at line 753 of file mss_main.c.
References MmwDemo_isObjDetCommonCfgPendingState(), MmwDemo_isObjDynCfgPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MSS_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
static uint8_t MmwDemo_isObjDetCommonCfgInNonPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Utility function to find out if all common configuration is in non-pending (cleared) state.
Parameters
[in] cfg Pointer to common specific configuration
Return values
1 if all common configuration is in non-pending state, else return 0
Definition at line 665 of file mss_main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_isAllCfgInNonPendingState().
static uint8_t MmwDemo_isObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Utility function to find out if all common configuration is pending
Parameters
[in] cfg Pointer to Common configuration
Return values
1 if all common configuration is pending, else return 0.
Definition at line 617 of file mss_main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_isAllCfgInPendingState().
static uint8_t MmwDemo_isObjDynCfgInNonPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Utility function to find out if all sub-frame specific dynamic configuration is in non-pending (cleared) state.
Parameters
[in] cfg Pointer to common specific configuration
Return values
1 if all sub-frame specific dynamic configuration is in non-pending state, else return 0
Definition at line 686 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_isAllCfgInNonPendingState().
static uint8_t MmwDemo_isObjDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Utility function to find out if all sub-frame specific dynamic configuration is pending
Parameters
[in] cfg Pointer to sub-frame specific configuration
Return values
1 if all sub-frame specific dynamic configuration is pending, else return 0
Definition at line 638 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_isAllCfgInPendingState().
static void MmwDemo_measurementResultOutput (DPU_AoAProc_compRxChannelBiasCfg * compRxChanCfg) static
Definition at line 826 of file mss_main.c.
References CLI_write(), cmplx16ImRe_t_::imag, MmwDemo_transmitProcessedOutput(), DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, cmplx16ImRe_t_::real, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, SYS_COMMON_NUM_RX_CHANNEL, and SYS_COMMON_NUM_TX_ANTENNAS.
Referenced by MmwDemo_handleObjectDetResult().
static int32_t MmwDemo_mmWaveCtrlStop (void) static
Description
The function is used to trigger the Front end to stop generating chirps.
Return values
Not Applicable.
Definition at line 1136 of file mss_main.c.
References MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_decodeError(), MMWave_ErrorLevel_ERROR, MMWave_stop(), and MmwDemo_debugAssert.
Referenced by MmwDemo_stopSensor().
static void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1) static
Description
The task is used to provide an execution context for the mmWave control task
Return values
Not Applicable.
Definition at line 1180 of file mss_main.c.
References MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_execute(), MmwDemo_debugAssert, and MmwDemo_DPM_ioctl_blocking().
Referenced by MmwDemo_initTask().
static void mmwDemo_mssDPMTask (UArg arg0, UArg arg1) static
Description
DPM Execution Task which executes the DPM Instance which manages the HL Profiles executing on the MSS.
Return values
Not Applicable.
Definition at line 2191 of file mss_main.c.
References DPM_execute(), and MmwDemo_MSS_MCB_t::objDetDpmHandle.
Referenced by MmwDemo_initTask().
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
Description
mmw demo helper Function to do one time sensor initialization. User need to fill gMmwMssMCB.cfg.openCfg before calling this function
Parameters
[in] isFirstTimeOpen If true then issues MMwave_open
Return values
Success - 0
Error - <0
Definition at line 2224 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_OpenCfg_t::customCalibrationEnableMask, MMWave_OpenCfg_t::disableFrameStartAsyncEvent, MMWave_OpenCfg_t::disableFrameStopAsyncEvent, MMWave_OpenCfg_t::freqLimitHigh, MMWave_OpenCfg_t::freqLimitLow, MMWave_decodeError(), MMWave_open(), MmwDemo_dataPathOpen(), MmwDemo_Cfg_t::openCfg, and MMWave_OpenCfg_t::useCustomCalibration.
Referenced by MmwDemo_CLISensorStart().
static void MmwDemo_platformInit (MmwDemo_platformCfg * config) static
Description
Platform specific hardware initialization.
Parameters
[in] config Platform initialization configuraiton
Return values
Not Applicable.
Definition at line 2451 of file mss_main.c.
References MmwDemo_platformCfg_t::commandBaudRate, MmwDemo_platformCfg_t::loggingBaudRate, MSS_SYS_VCLK, MmwDemo_platformCfg_t::SensorStatusGPIO, SOC_XWR18XX_GPIO_2, and MmwDemo_platformCfg_t::sysClockFrequency.
Referenced by MmwDemo_initTask().
static int32_t MmwDemo_processPendingDynamicCfgCommands (uint8_t subFrameIndx) static
Description
Processes any pending dynamic configuration commands for the specified sub-frame by fanning out to the respective DPUs using IOCTL interface, and resets (clears) the pending state after processing.
Parameters
[in] subFrameIndx Sub-frame index of desired sub-frame to process
Return values
Success - 0
Error - <0
Definition at line 1831 of file mss_main.c.
References DPC_ObjectDetection_DynCfg_t::calibDcRangeSigCfg, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, DPC_ObjectDetection_fovRangeCfg_t::cfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::cfg, DPC_ObjectDetection_CalibDcRangeSigCfg_t::cfg, DPC_ObjectDetection_CfarCfg_t::cfg, DPC_ObjectDetection_StaticClutterRemovalCfg_t::cfg, DPC_ObjectDetection_fovAoaCfg_t::cfg, DPC_ObjectDetection_fovDopplerCfg_t::cfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, DPC_OBJDET_IOCTL__DYNAMIC_CALIB_DC_RANGE_SIG_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_DOPPLER_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_RANGE_CFG, DPC_OBJDET_IOCTL__DYNAMIC_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_FOV_AOA, DPC_OBJDET_IOCTL__DYNAMIC_FOV_DOPPLER, DPC_OBJDET_IOCTL__DYNAMIC_FOV_RANGE, DPC_OBJDET_IOCTL__DYNAMIC_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_MULTI_OBJ_BEAM_FORM_CFG, DPC_OBJDET_IOCTL__DYNAMIC_RANGE_AZIMUTH_HEAT_MAP, DPC_OBJDET_IOCTL__DYNAMIC_STATICCLUTTER_REMOVAL_CFG, DPM_ioctl(), MmwDemo_DPC_ObjDet_DynCfg_t::dynCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovRange, MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, MmwDemo_handleObjectDetResult(), DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, MmwDemo_MSS_MCB_t::objDetCommonCfg, MmwDemo_MSS_MCB_t::objDetDpmHandle, MmwDemo_SubFrameCfg_t::objDetDynCfg, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_fovAoaCfg_t::subFrameNum, DPC_ObjectDetection_fovRangeCfg_t::subFrameNum, DPC_ObjectDetection_CfarCfg_t::subFrameNum, DPC_ObjectDetection_fovDopplerCfg_t::subFrameNum, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::subFrameNum, DPC_ObjectDetection_CalibDcRangeSigCfg_t::subFrameNum, DPC_ObjectDetection_StaticClutterRemovalCfg_t::subFrameNum, and DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::subFrameNum.
Referenced by MmwDemo_handleObjectDetResult().
static void MmwDemo_resetObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Resets (clears) all pending common configuration of Object Detection DPC
Parameters
[in] cfg Object Detection DPC common configuration
Return values
Not Applicable.
Definition at line 713 of file mss_main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_dataPathConfig().
static void MmwDemo_resetObjDetDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Resets (clears) all pending sub-frame specific dynamic configuration of Object Detection DPC
Parameters
[in] cfg Object Detection DPC sub-frame dynamic configuration
Return values
Not Applicable.
Definition at line 730 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_dataPathConfig().
static void MmwDemo_sensorStopEpilog (void) static
Description
Epilog processing after sensor has stopped
Return values
None
Definition at line 2363 of file mss_main.c.
References MmwDemo_TaskHandles_t::initTask, MmwDemo_TaskHandles_t::mmwaveCtrl, MmwDemo_debugAssert, MmwDemo_TaskHandles_t::objDetDpmTask, and MmwDemo_MSS_MCB_t::taskHandles.
Referenced by MmwDemo_stopSensor().
static void MmwDemo_setSubFramePendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg, uint32_t offset) static
Description
Utility function to set the pending state of configuration.
Parameters
[in] cfg Sub-frame specific dynamic configuration
[in] offset Configuration structure offset that uniquely identifies the configuration to set to the pending state.
Return values
None
Definition at line 567 of file mss_main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending, MMWDEMO_ADCBUFCFG_OFFSET, MMWDEMO_CALIBDCRANGESIG_OFFSET, MMWDEMO_CFARCFGDOPPLER_OFFSET, MMWDEMO_CFARCFGRANGE_OFFSET, MmwDemo_debugAssert, MMWDEMO_FOVAOA_OFFSET, MMWDEMO_FOVDOPPLER_OFFSET, MMWDEMO_FOVRANGE_OFFSET, MMWDEMO_GUIMONSEL_OFFSET, MMWDEMO_MULTIOBJBEAMFORMING_OFFSET, and MMWDEMO_STATICCLUTTERREMOFVAL_OFFSET.
Referenced by MmwDemo_CfgUpdate().
void MmwDemo_sleep (void)
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 2694 of file mss_main.c.
int32_t MmwDemo_startSensor (void)
Description
mmw demo helper Function to start sensor.
Return values
Success - 0
Error - <0
Definition at line 2309 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MMWave_CalibrationCfg_t::chirpCalibrationCfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MSS_MCB_t::ctrlHandle, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CalibrationCfg_t::dfeDataOutputMode, MMWave_ChirpCalibrationCfg_t::enableCalibration, MMWave_ChirpCalibrationCfg_t::enablePeriodicity, MMWave_decodeError(), MMWave_start(), MmwDemo_dataPathStart(), MMWave_ChirpCalibrationCfg_t::periodicTimeInFrames, MmwDemo_Cfg_t::platformCfg, MmwDemo_MSS_MCB_t::sensorStartCount, and MmwDemo_platformCfg_t::SensorStatusGPIO.
Referenced by MmwDemo_CLISensorStart().
void MmwDemo_stopSensor (void)
Description
Stops the RF and datapath for the sensor. Blocks until both operation are completed. Prints epilog at the end.
Return values
None
Definition at line 2416 of file mss_main.c.
References MmwDemo_MSS_MCB_t::cfg, MmwDemo_MSS_MCB_t::DPMstopSemHandle, MmwDemo_mmWaveCtrlStop(), MmwDemo_sensorStopEpilog(), MmwDemo_Cfg_t::platformCfg, MmwDemo_MSS_MCB_t::sensorStartCount, MmwDemo_platformCfg_t::SensorStatusGPIO, and MmwDemo_MSS_MCB_t::sensorStopCount.
Referenced by MmwDemo_CLISensorStop().
static void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, DPC_ObjectDetection_ExecuteResult * result, MmwDemo_output_message_stats * timingInfo) static
Transmits detection data over UART.
The following data is transmitted:
Header (size = 32bytes), including "Magic word", (size = 8 bytes) and including the number of TLV items TLV Items:
If detectedObjects flag is 1 or 2, DPIF_PointCloudCartesian structure containing X,Y,Z location and velocity for detected objects, size = sizeof(DPIF_PointCloudCartesian) * number of detected objects
If detectedObjects flag is 1, DPIF_PointCloudSideInfo structure containing SNR and noise for detected objects, size = sizeof(DPIF_PointCloudCartesian) * number of detected objects
If logMagRange flag is set, rangeProfile, size = number of range bins * sizeof(uint16_t)
If noiseProfile flag is set, noiseProfile, size = number of range bins * sizeof(uint16_t)
If rangeAzimuthHeatMap flag is set, the zero Doppler column of the range cubed matrix, size = number of Rx Azimuth virtual antennas * number of chirps per frame * sizeof(uint32_t)
If rangeDopplerHeatMap flag is set, the log magnitude range-Doppler matrix, size = number of range bins * number of Doppler bins * sizeof(uint16_t)
If statsInfo flag is set, the stats information
Parameters
[in] uartHandle UART driver handle
[in] result Pointer to result from object detection DPC processing
[in] timingInfo Pointer to timing information provided from core that runs data path
Definition at line 867 of file mss_main.c.
References DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMap, DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMapSize, DPIF_DetMatrix_t::data, DPIF_RadarCube_t::data, MmwDemo_GuiMonSel_t::detectedObjects, DPC_ObjectDetection_ExecuteResult_t::detMatrix, MmwDemo_output_message_header_t::frameNumber, MmwDemo_SubFrameCfg_t::guiMonSel, MmwDemo_output_message_tl_t::length, MmwDemo_GuiMonSel_t::logMagRange, MmwDemo_output_message_header_t::magicWord, MMWDEMO_OUTPUT_MSG_AZIMUT_STATIC_HEAT_MAP, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS_SIDE_INFO, MMWDEMO_OUTPUT_MSG_MAX, MMWDEMO_OUTPUT_MSG_NOISE_PROFILE, MMWDEMO_OUTPUT_MSG_RANGE_DOPPLER_HEAT_MAP, MMWDEMO_OUTPUT_MSG_RANGE_PROFILE, MMWDEMO_OUTPUT_MSG_SEGMENT_LEN, MMWDEMO_OUTPUT_MSG_STATS, MmwDemo_GuiMonSel_t::noiseProfile, MmwDemo_output_message_header_t::numDetectedObj, MmwDemo_SubFrameCfg_t::numDopplerBins, DPC_ObjectDetection_ExecuteResult_t::numObjOut, MmwDemo_SubFrameCfg_t::numRangeBins, MmwDemo_output_message_header_t::numTLVs, DPC_ObjectDetection_ExecuteResult_t::objOut, DPC_ObjectDetection_ExecuteResult_t::objOutSideInfo, MmwDemo_output_message_header_t::platform, DPC_ObjectDetection_ExecuteResult_t::radarCube, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, MmwDemo_GuiMonSel_t::rangeDopplerHeatMap, DPC_ObjectDetection_ExecuteResult_t::stats, MmwDemo_GuiMonSel_t::statsInfo, MmwDemo_MSS_MCB_t::subFrameCfg, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, MmwDemo_output_message_header_t::subFrameNumber, MmwDemo_output_message_header_t::timeCpuCycles, MmwDemo_output_message_header_t::totalPacketLen, MmwDemo_output_message_tl_t::type, and MmwDemo_output_message_header_t::version.
Referenced by MmwDemo_handleObjectDetResult(), and MmwDemo_measurementResultOutput().
Variable Documentation
MmwDemo_HSRAM gHSRAM
Global Variable for HSRAM buffer used to share results to remote.
Definition at line 484 of file mss_main.c.
MmwDemo_MSS_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 478 of file mss_main.c.
Copyright 2018, Texas Instruments Incorporated