# Setting Travis CI for Continuous Integration Setting

sudo: required

services:
  - docker

before_install:
  - docker pull roomz/ccs-ci
  
install:
  - docker build -t ccs_test .

script:
  - docker run -ti -v C:\workspace\roomzscreen:/workdir ccs_test /bin/bash

