# Setting Travis CI for Continuous Integration Setting

sudo: required

services:
  - docker

#before_install:
#  - docker pull roomz/ccs-ci
  
install:
  #- docker build -t Dockerfile.ccs.mmwave .
  - docker build --target ccs-mmwave --tag ccs-mmwave:latest --file Dockerfile.ccs.mmwave.ubuntu18 .

script:
  #- docker run -ti -v ccs_test /bin/bash
  - sudo docker run --net=host  --cap-add=NET_ADMIN --device /dev/net/tun:/dev/net/tun -it ccs-mmwave
