xwr68xx/mmw/data_path.h File Reference
data_path.h File Reference
This is the data path processing header.
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_error.h>
#include <ti/drivers/adcbuf/ADCBuf.h>
#include <ti/drivers/edma/edma.h>
#include <ti/drivers/hwa/hwa.h>
#include <ti/demo/xwr68xx/mmw/mmw_config.h>
#include <ti/demo/utils/mmwdemo_adcconfig.h>
#include <ti/datapath/dpc/objectdetection/objdethwa/objectdetection.h>
#include <ti/demo/xwr68xx/mmw/mmw_output.h>
Data Structures
struct MmwDemo_DPC_ObjDet_DynCfg_t
struct MmwDemo_DPC_ObjDet_CommonCfg_t
Same functionality as MmwDemo_DPC_ObjDet_DynCfg but for common configuration.
struct MmwDemo_DataPathObj_t
Data path Object information.
Typedefs
typedef struct MmwDemo_DPC_ObjDet_DynCfg_t MmwDemo_DPC_ObjDet_DynCfg
typedef struct MmwDemo_DPC_ObjDet_CommonCfg_t MmwDemo_DPC_ObjDet_CommonCfg
Same functionality as MmwDemo_DPC_ObjDet_DynCfg but for common configuration.
typedef struct MmwDemo_DataPathObj_t MmwDemo_DataPathObj
Data path Object information.
Functions
void MmwDemo_hwaInit (MmwDemo_DataPathObj *obj)
void MmwDemo_edmaInit (MmwDemo_DataPathObj *obj)
void MmwDemo_hwaOpen (MmwDemo_DataPathObj *obj, SOC_Handle socHandle)
void MmwDemo_edmaOpen (MmwDemo_DataPathObj *obj)
void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t *errorInfo)
void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t *errorInfo)
void MmwDemo_dataPathObjInit (MmwDemo_DataPathObj *obj)
void MmwDemo_edmaClose (MmwDemo_DataPathObj *obj)
void MmwDemo_hwaClose (MmwDemo_DataPathObj *obj)
Detailed Description
This is the data path processing header.
NOTE: (C) Copyright 2018 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file data_path.h.
Typedef Documentation
typedef struct MmwDemo_DataPathObj_t MmwDemo_DataPathObj
Data path Object information.
typedef struct MmwDemo_DPC_ObjDet_CommonCfg_t MmwDemo_DPC_ObjDet_CommonCfg
Same functionality as MmwDemo_DPC_ObjDet_DynCfg but for common configuration.
typedef struct MmwDemo_DPC_ObjDet_DynCfg_t MmwDemo_DPC_ObjDet_DynCfg
Function Documentation
void MmwDemo_dataPathObjInit (MmwDemo_DataPathObj * obj)
Description
Initializes data path object.
Definition at line 221 of file data_path.c.
Referenced by MmwDemo_dataPathInit().
void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t * errorInfo)
Description
Call back function for EDMA CC (Channel controller) error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 105 of file data_path.c.
References MmwDemo_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_errorInfo, gMmwMCB, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t * errorInfo)
Description
Call back function for EDMA transfer controller error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 118 of file data_path.c.
References MmwDemo_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, gMmwMCB, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
void MmwDemo_edmaClose (MmwDemo_DataPathObj * obj)
Description
Close EDMA.
Definition at line 210 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle.
void MmwDemo_edmaInit (MmwDemo_DataPathObj * obj)
Description
Init EDMA.
Definition at line 76 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_errorInfo, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathInit().
void MmwDemo_edmaOpen (MmwDemo_DataPathObj * obj)
Description
Open EDMA.
Definition at line 170 of file data_path.c.
References EDMA_NUM_CC, MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_debugAssert, MmwDemo_EDMA_errorCallbackFxn(), and MmwDemo_EDMA_transferControllerErrorCallbackFxn().
Referenced by MmwDemo_dataPathOpen().
void MmwDemo_hwaClose (MmwDemo_DataPathObj * obj)
Description
Close HWA instance.
Definition at line 150 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
void MmwDemo_hwaInit (MmwDemo_DataPathObj * obj)
Description
Init HWA.
Definition at line 65 of file data_path.c.
Referenced by MmwDemo_dataPathInit().
void MmwDemo_hwaOpen (MmwDemo_DataPathObj * obj, SOC_Handle socHandle)
Description
Open HWA instance.
Definition at line 130 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathOpen().
Copyright 2018, Texas Instruments Incorporated