ADC Config External Functions
ADC Config External Functions
Mmwdemo ADC Config External
The section has a list of all internal API which are not exposed to the external applications.
Functions
ADCBuf_Handle MmwDemo_ADCBufOpen (void)
int32_t MmwDemo_ADCBufConfig (ADCBuf_Handle adcBufHandle, uint16_t rxChannelEn, uint8_t chirpThreshold, uint32_t chanDataSize, MmwDemo_ADCBufCfg *adcBufCfg, uint16_t *rxChanOffset)
Detailed Description
The section has a list of all internal API which are not exposed to the external applications.
Function Documentation
int32_t MmwDemo_ADCBufConfig (ADCBuf_Handle adcBufHandle, uint16_t rxChannelEn, uint8_t chirpThreshold, uint32_t chanDataSize, MmwDemo_ADCBufCfg * adcBufCfg, uint16_t * rxChanOffset)
Description
Function configures ADCBuf driver with data path parameters parsed from configurations
Parameters
[in] adcBufHandle ADCBuf driver handle
[in] rxChannelEn rx channel enable bit mask as described in rlChanCfg_t in rl_sensor.h
[in] chirpThreshold Chirp threshold
[in] chanDataSize Data size of the ADC channel
[in] adcBufCfg pointer to ADCBuf configuration
[out] rxChanOffset pointer to rx channel offset in the ADC buffer, for each of enabled rx antenna
Return values
Success - 0 Fail < 0, one of ADCBuf driver error codes
Definition at line 114 of file mmwdemo_adcconfig.c.
References MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_ADCBufCfg_t::iqSwapSel, and SYS_COMMON_NUM_RX_CHANNEL.
Referenced by MmwDemo_ADCBufOpen(), MmwDemo_dataPathConfig(), and MmwDemo_DPC_ObjectDetection_dpmTask().
ADCBuf_Handle MmwDemo_ADCBufOpen (void)
Description
Function initializes and opens ADCBuf driver
Return values
Success - ADCBuf driver handle Fail NULL
Definition at line 71 of file mmwdemo_adcconfig.c.
References MmwDemo_ADCBufConfig().
Referenced by MmwDemo_dataPathOpen().
Copyright 2018, Texas Instruments Incorporated