xwr68xx/mmw/main.c File Reference
main.c File Reference
This is the main file which implements the millimeter wave Demo.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/pinmux/pinmux.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/control/dpm/dpm.h>
#include <ti/datapath/dpc/objectdetection/objdethwa/objectdetection.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/uart/UART.h>
#include <ti/utils/cli/cli.h>
#include <ti/utils/mathutils/mathutils.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
#include <ti/demo/utils/mmwdemo_rfparser.h>
#include <ti/demo/xwr68xx/mmw/mmw_output.h>
#include <ti/demo/xwr68xx/mmw/mmw.h>
#include <ti/demo/xwr68xx/mmw/data_path.h>
#include <ti/demo/xwr68xx/mmw/mmw_config.h>
Macros
#define MMWDEMO_CLI_TASK_PRIORITY 3
Task Priority settings: Mmwave task is at higher priority because of potential async messages from BSS that need quick action in real-time.
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 4
#define MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY 5
#define MMWDEMO_OBJDET_TCM_SIZE (49U * 1024U)
Functions
void MmwDemo_CLIInit (uint8_t taskPriority)
void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
void MmwDemo_dataPathInit (MmwDemo_DataPathObj *obj)
int32_t MmwDemo_dataPathConfig (void)
void MmwDemo_dataPathOpen (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathStart (void)
void MmwDemo_dataPathStop (MmwDemo_DataPathObj *obj)
void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, DPC_ObjectDetection_ExecuteResult *result, MmwDemo_output_message_stats *timingInfo)
Transmits detection data over UART.
void MmwDemo_initTask (UArg arg0, UArg arg1)
void MmwDemo_dataPathTask (UArg arg0, UArg arg1)
int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t *payload)
void MmwDemo_sleep (void)
void _MmwDemo_debugAssert (int32_t expression, const char *file, int32_t line)
static void MmwDemo_setSubFramePendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg, uint32_t offset)
static uint8_t MmwDemo_isObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static uint8_t MmwDemo_isObjDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
static uint8_t MmwDemo_isObjDetCommonCfgInNonPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static uint8_t MmwDemo_isObjDynCfgInNonPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
static void MmwDemo_resetObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg *cfg)
static void MmwDemo_resetObjDetDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg *cfg)
uint8_t MmwDemo_isAllCfgInPendingState (void)
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
void MmwDemo_CfgUpdate (void *srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
void MmwDemo_MMWave_stop (void)
void MmwDemo_sensorStopEpilog (void)
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
int32_t MmwDemo_configSensor (void)
int32_t MmwDemo_startSensor (void)
void MmwDemo_stopSensor ()
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1)
void MmwDemo_measurementResultOutput (DPU_AoAProc_compRxChannelBiasCfg *compRxChanCfg)
static uint8_t MmwDemo_getNextSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames)
static uint8_t MmwDemo_getPrevSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames)
static int32_t MmwDemo_processPendingDynamicCfgCommands (uint8_t subFrameIndx)
static void MmwDemo_DPC_ObjectDetection_dpmTask (UArg arg0, UArg arg1)
void MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn (uint8_t subFrameIndx)
void MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn (uint8_t subFrameIndx)
void MmwDemo_platformInit (MmwDemo_platformCfg *config)
int main (void)
Variables
uint8_t gMmwL3 [SOC_L3RAM_SIZE]
uint8_t gDPC_ObjDetTCM [MMWDEMO_OBJDET_TCM_SIZE]
MmwDemo_MCB gMmwMCB
Global Variable for tracking information required by the mmw Demo.
Detailed Description
This is the main file which implements the millimeter wave Demo.
NOTE: (C) Copyright 2018 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file main.c.
Macro Definition Documentation
#define MMWDEMO_CLI_TASK_PRIORITY 3
Task Priority settings: Mmwave task is at higher priority because of potential async messages from BSS that need quick action in real-time.
CLI task must be at a lower priority than object detection dpm task priority because the dynamic CLI command handling in the objection detection dpm task assumes CLI task is held back during this processing. The alternative is to use a semaphore between the two tasks.
Definition at line 419 of file main.c.
Referenced by MmwDemo_initTask().
#define MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY 4
Definition at line 420 of file main.c.
Referenced by MmwDemo_initTask().
#define MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY 5
Definition at line 421 of file main.c.
Referenced by MmwDemo_initTask().
#define MMWDEMO_OBJDET_TCM_SIZE (49U * 1024U)
TCM RAM buffer for object detection DPC
Definition at line 432 of file main.c.
Function Documentation
void _MmwDemo_debugAssert (int32_t expression, const char * file, int32_t line)
Description
Send assert information through CLI.
Definition at line 481 of file main.c.
References CLI_write().
int main (void)
Description
Entry point into the Millimeter Wave Demo
Return values
Not Applicable.
Definition at line 2529 of file main.c.
References MmwDemo_TaskHandles_t::initTask, MmwDemo_debugAssert, MmwDemo_initTask(), MmwDemo_MCB_t::socHandle, and MmwDemo_MCB_t::taskHandles.
void MmwDemo_CfgUpdate (void * srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
Description
Utility function to apply configuration to specified sub-frame
Parameters
[in] srcPtr Pointer to configuration
[in] offset Offset of configuration within the parent structure
[in] size Size of configuration
[in] subFrameNum Sub-frame Number (0 based) to apply to, broadcast to all sub-frames if special code MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG
Return values
Success - 0
Error - <0
Definition at line 731 of file main.c.
References MmwDemo_setSubFramePendingState(), MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG, MmwDemo_SubFrameCfg_t::objDetDynCfg, and MmwDemo_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIGuiMonSel(), and MmwDemo_CLIMultiObjBeamForming().
void MmwDemo_CLIInit (uint8_t taskPriority)
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 813 of file mmw_cli.c.
References CLI_open(), CLI_Cfg_t::cliBanner, CLI_Cfg_t::cliPrompt, CLI_Cfg_t::cliUartHandle, CLI_CmdTableEntry_t::cmd, CLI_CmdTableEntry_t::cmdHandlerFxn, MmwDemo_MCB_t::commandUartHandle, MmwDemo_MCB_t::ctrlHandle, CLI_Cfg_t::enableMMWaveExtension, CLI_CmdTableEntry_t::helpString, CLI_Cfg_t::mmWaveHandle, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAoAFovCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLICfarFovCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), CLI_Cfg_t::socHandle, MmwDemo_MCB_t::socHandle, CLI_Cfg_t::tableEntry, CLI_Cfg_t::taskPriority, and CLI_Cfg_t::usePolledMode.
Referenced by MmwDemo_initTask().
int32_t MmwDemo_configSensor (void)
Description
mmw demo helper Function to configure sensor. User need to fill gMmwMCB.cfg.ctrlCfg and add profiles/chirp to mmWave before calling this function
Return values
0 if no error, error code otherwise
Definition at line 895 of file main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MCB_t::ctrlHandle, MMWave_config(), MMWave_decodeError(), and MmwDemo_dataPathConfig().
Referenced by MmwDemo_CLISensorStart().
int32_t MmwDemo_dataPathConfig (void)
Description
The function is used to configure the data path based on the chirp profile. After this function is executed, the data path processing will ready to go when the ADC buffer starts receiving samples corresponding to the chirps.
Return values
0 if no error, error code otherwise.
Definition at line 1048 of file main.c.
References DPIF_ADCBufProperty_t::adcBits, MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_SubFrameCfg_t::adcBufChanDataSize, MmwDemo_RFParserOutParams_t::adcBufChanDataSize, DPC_ObjectDetection_StaticCfg_t::ADCBufData, MmwDemo_DataPathObj_t::adcbufHandle, MmwDemo_ADCBufCfg_t::adcFmt, MMWave_CtrlCfg_t::advancedFrameCfg, MmwDemo_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_Cfg_t::ctrlCfg, DPIF_ADCBufData_t::data, DPIF_ADCBufProperty_t::dataFmt, MmwDemo_MCB_t::dataPathObj, DPIF_ADCBufData_t::dataProperty, DPIF_ADCBufData_t::dataSize, MMWave_CtrlCfg_t::dfeDataOutputMode, DPC_ObjectDetection_StaticCfg_t::dopplerStep, MmwDemo_RFParserOutParams_t::dopplerStep, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPIF_DATAFORMAT_COMPLEX16_IMRE, DPIF_DATAFORMAT_COMPLEX16_REIM, DPIF_RXCHAN_INTERLEAVE_MODE, DPIF_RXCHAN_NON_INTERLEAVE_MODE, DPM_ioctl(), DPC_ObjectDetection_PreStartCfg_t::dynCfg, MmwDemo_DPC_ObjDet_DynCfg_t::dynCfg, MMWave_AdvancedFrameCfg_t::frameCfg, MmwDemo_SubFrameCfg_t::guiMonSel, DPIF_ADCBufProperty_t::interleave, MmwDemo_ADCBufCfg_t::iqSwapSel, DPC_ObjectDetection_StaticCfg_t::isValidProfileHasOneTxPerChirp, MMWave_DFEDataOutputMode_ADVANCED_FRAME, MmwDemo_ADCBufConfig(), MmwDemo_debugAssert, MmwDemo_resetObjDetCommonCfgPendingState(), MmwDemo_resetObjDetDynCfgPendingState(), MmwDemo_RFParser_parseConfig(), DPIF_ADCBufProperty_t::numAdcSamples, MmwDemo_RFParserOutParams_t::numAdcSamples, DPIF_ADCBufProperty_t::numChirpsPerChirpEvent, MmwDemo_SubFrameCfg_t::numChirpsPerChirpEvent, MmwDemo_RFParserOutParams_t::numChirpsPerChirpEvent, DPC_ObjectDetection_StaticCfg_t::numChirpsPerFrame, MmwDemo_RFParserOutParams_t::numChirpsPerFrame, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, MmwDemo_SubFrameCfg_t::numDopplerBins, MmwDemo_RFParserOutParams_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, MmwDemo_RFParserOutParams_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numRangeBins, MmwDemo_SubFrameCfg_t::numRangeBins, MmwDemo_RFParserOutParams_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, MmwDemo_RFParserOutParams_t::numRxAntennas, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, MmwDemo_RFParserOutParams_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntAzim, MmwDemo_RFParserOutParams_t::numVirtualAntAzim, DPC_ObjectDetection_StaticCfg_t::numVirtualAntElev, MmwDemo_RFParserOutParams_t::numVirtualAntElev, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, MmwDemo_RFParserOutParams_t::numVirtualAntennas, MmwDemo_DataPathObj_t::objDetCommonCfg, MmwDemo_DataPathObj_t::objDetDpmHandle, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_Cfg_t::openCfg, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, DPC_ObjectDetection_StaticCfg_t::rangeStep, MmwDemo_RFParserOutParams_t::rangeStep, MmwDemo_MCB_t::rfFreqScaleFactor, DPC_ObjectDetection_StaticCfg_t::rxAntOrder, MmwDemo_RFParserOutParams_t::rxAntOrder, DPIF_ADCBufProperty_t::rxChanOffset, SOC_XWR68XX_MSS_ADCBUF_BASE_ADDRESS, MmwDemo_MCB_t::socHandle, DPC_ObjectDetection_PreStartCfg_t::staticCfg, MmwDemo_MCB_t::subFrameCfg, DPC_ObjectDetection_PreStartCfg_t::subFrameNum, DPC_ObjectDetection_StaticCfg_t::txAntOrder, MmwDemo_RFParserOutParams_t::txAntOrder, and MmwDemo_RFParserOutParams_t::validProfileHasOneTxPerChirp.
Referenced by MmwDemo_configSensor().
void MmwDemo_dataPathInit (MmwDemo_DataPathObj * obj)
Description
This function is called at the init time from MmwDemo_initTask. It initializes drivers: ADCBUF, HWA, EDMA, and semaphores used by MmwDemo_dataPathTask
Return values
Not Applicable.
Definition at line 1010 of file main.c.
References MmwDemo_dataPathObjInit(), MmwDemo_edmaInit(), and MmwDemo_hwaInit().
Referenced by MmwDemo_initTask().
void MmwDemo_dataPathOpen (MmwDemo_DataPathObj * obj)
Description
Opens HWA, EDMA and ADCBUF drivers
Parameters
[in] obj pointer to data path object
Return values
Not Applicable.
Definition at line 1031 of file main.c.
References MmwDemo_DataPathObj_t::adcbufHandle, MmwDemo_ADCBufOpen(), MmwDemo_edmaOpen(), MmwDemo_hwaOpen(), and MmwDemo_MCB_t::socHandle.
Referenced by MmwDemo_initTask().
void MmwDemo_dataPathStart (void)
Description
The function is used to start the data path manager and underlying processing chain. It will wait for the processing chain to ack
Return values
Not Applicable.
Definition at line 1248 of file main.c.
References MmwDemo_MCB_t::dataPathObj, DPM_start(), MmwDemo_MCB_t::DPMstartSemHandle, MmwDemo_debugAssert, and MmwDemo_DataPathObj_t::objDetDpmHandle.
Referenced by MmwDemo_startSensor().
void MmwDemo_dataPathStop (MmwDemo_DataPathObj * obj)
Description
The function is used to Stop data path.
Return values
Not Applicable.
Definition at line 1278 of file main.c.
References DPM_stop(), MmwDemo_debugAssert, and MmwDemo_DataPathObj_t::objDetDpmHandle.
Referenced by MmwDemo_eventCallbackFxn().
void MmwDemo_dataPathTask (UArg arg0, UArg arg1)
static void MmwDemo_DPC_ObjectDetection_dpmTask (UArg arg0, UArg arg1) static
Description
DPM Execution Task. DPM execute results are processed here: a) Transmits results through UART port. b) Updates book-keeping code for timing info. c) Notifies DPC that results have been exported (using DPC IOCTL command)
Return values
Not Applicable.
Definition at line 2069 of file main.c.
References MmwDemo_SubFrameCfg_t::adcBufCfg, MmwDemo_SubFrameCfg_t::adcBufChanDataSize, MmwDemo_DataPathObj_t::adcbufHandle, MmwDemo_MCB_t::cfg, MMWave_OpenCfg_t::chCfg, DPC_ObjectDetection_ExecuteResult_t::compRxChanBiasMeasurement, MmwDemo_MCB_t::dataPathObj, DPC_OBJDET_IOCTL__DYNAMIC_EXECUTE_RESULT_EXPORTED, DPM_execute(), DPM_ioctl(), DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, DPC_ObjectDetection_Stats_t::frameStartTimeStamp, MmwDemo_SubFrameStats_t::interFrameProcessingEndTime, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_output_message_stats_t::interFrameProcessingTime, DPC_ObjectDetection_Stats_t::interFrameStartTimeStamp, MmwDemo_MCB_t::loggingUartHandle, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, MmwDemo_ADCBufConfig(), MmwDemo_debugAssert, MmwDemo_getNextSubFrameIndx(), MmwDemo_getPrevSubFrameIndx(), MmwDemo_measurementResultOutput(), MmwDemo_processPendingDynamicCfgCommands(), MmwDemo_transmitProcessedOutput(), MmwDemo_SubFrameCfg_t::numChirpsPerChirpEvent, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_DataPathObj_t::objDetCommonCfg, MmwDemo_DataPathObj_t::objDetDpmHandle, MmwDemo_SubFrameStats_t::objDetSubFramePreparationTime, MmwDemo_Cfg_t::openCfg, MmwDemo_SubFrameStats_t::outputStats, MmwDemo_SubFrameStats_t::pendingConfigProcTime, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPM_Buffer_t::ptrBuffer, R4F_CLOCK_MHZ, DPM_Buffer_t::size, DPC_ObjectDetection_ExecuteResult_t::stats, MmwDemo_MCB_t::subFrameCfg, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, DPC_ObjectDetection_ExecuteResultExportedInfo_t::subFrameIdx, DPC_ObjectDetection_Stats_t::subFramePreparationCycles, MmwDemo_SubFrameStats_t::subFramePreparationTime, MmwDemo_MCB_t::subFrameStats, SYS_COMMON_NUM_RX_CHANNEL, and MmwDemo_output_message_stats_t::transmitOutputTime.
Referenced by MmwDemo_initTask().
void MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn (uint8_t subFrameIndx)
Description
Call back function that was registered during config time and is going to be called in DPC processing at the beginning of frame/sub-frame processing, we use this to issue BIOS calls for computing CPU load during inter-frame
Parameters
[in] subFrameIndx Sub-frame index of the sub-frame during which processing this function was called.
Return values
None
Definition at line 2226 of file main.c.
References MmwDemo_output_message_stats_t::interFrameCPULoad, MmwDemo_SubFrameStats_t::outputStats, and MmwDemo_MCB_t::subFrameStats.
Referenced by MmwDemo_initTask().
void MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn (uint8_t subFrameIndx)
Description
Call back function that was registered during config time and is going to be called in DPC processing at the beginning of inter-frame/inter-sub-frame processing, we use this to issue BIOS calls for computing CPU load during active frame (chirping)
Parameters
[in] subFrameIndx Sub-frame index of the sub-frame during which processing this function was called.
Return values
None
Definition at line 2250 of file main.c.
References MmwDemo_output_message_stats_t::activeFrameCPULoad, MmwDemo_SubFrameStats_t::outputStats, and MmwDemo_MCB_t::subFrameStats.
Referenced by MmwDemo_initTask().
static void MmwDemo_DPC_ObjectDetection_reportFxn (DPM_Report reportType, uint32_t instanceId, int32_t errCode, uint32_t arg0, uint32_t arg1) static
Description
DPM Registered Report Handler. The DPM Module uses this registered function to notify the application about DPM reports.
Parameters
[in] reportType Report Type
[in] instanceId Instance Identifier which generated the report
[in] errCode Error code if any.
[in] arg0 Argument 0 interpreted with the report type
[in] arg1 Argument 1 interpreted with the report type
Return values
Not Applicable.
Definition at line 1436 of file main.c.
References CLI_write(), DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreLocalRamUsage, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPM_Report_DPC_ASSERT, DPM_Report_DPC_INFO, DPM_Report_DPC_STARTED, DPM_Report_DPC_STOPPED, DPM_Report_IOCTL, DPM_Report_NOTIFY_DPC_RESULT, MmwDemo_MCB_t::DPMstartSemHandle, MmwDemo_MCB_t::DPMstopSemHandle, DPM_DPCAssert_t::fileName, gDPC_ObjDetTCM, gMmwL3, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamUsage, DPM_DPCAssert_t::lineNum, DPC_ObjectDetection_PreStartCfg_t::memUsage, MmwDemo_debugAssert, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapDPCUsed, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapTotal, and DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapUsed.
Referenced by MmwDemo_eventCallbackFxn(), and MmwDemo_initTask().
int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t * payload)
Description
Registered event function to mmwave which is invoked when an event from the BSS is received.
Parameters
[in] msgId Message Identifier
[in] sbId Subblock identifier
[in] sbLen Length of the subblock
[in] payload Pointer to the payload buffer
Return values
Always return 0
Definition at line 1334 of file main.c.
References MmwDemo_Stats_t::calibrationReports, CLI_write(), MmwDemo_MCB_t::dataPathObj, MmwDemo_Stats_t::failedTimingReports, MmwDemo_Stats_t::frameTriggerReady, MmwDemo_dataPathStop(), MmwDemo_debugAssert, MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_Stats_t::sensorStopped, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_initTask().
static uint8_t MmwDemo_getNextSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames) static
Description
Utility function to get next sub-frame index
Parameters
[in] currentIndx Current sub-frame index
[in] numSubFrames Number of sub-frames
Return values
Index of next sub-frame.
Definition at line 1818 of file main.c.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
static uint8_t MmwDemo_getPrevSubFrameIndx (uint8_t currentIndx, uint8_t numSubFrames) static
Description
Utility function to get previous sub-frame index
Parameters
[in] currentIndx Current sub-frame index
[in] numSubFrames Number of sub-frames
Return values
Index of previous sub-frame
Definition at line 1844 of file main.c.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
void MmwDemo_initTask (UArg arg0, UArg arg1)
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 2314 of file main.c.
References DPC_ObjectDetection_MemCfg_t::addr, DPM_InitCfg_t::arg, DPM_InitCfg_t::argSize, MmwDemo_MCB_t::cfg, MMWave_InitCfg_t::cfgMode, MmwDemo_platformCfg_t::commandBaudRate, MmwDemo_MCB_t::commandUartHandle, DPC_ObjectDetection_InitParams_t::CoreLocalRamCfg, MMWave_LinkCRCCfg_t::crcChannel, MmwDemo_MCB_t::ctrlHandle, MmwDemo_MCB_t::dataPathObj, DPM_InitCfg_t::domain, MMWave_InitCfg_t::domain, DPM_Domain_LOCALIZED, DPM_init(), MmwDemo_MCB_t::DPMstartSemHandle, MmwDemo_MCB_t::DPMstopSemHandle, EDMA_NUM_CC, DPC_ObjectDetection_InitParams_t::edmaHandle, MmwDemo_DataPathObj_t::edmaHandle, MMWave_InitCfg_t::eventFxn, gDPC_ObjDetTCM, gDPC_ObjectDetectionCfg, gMmwL3, DPC_ObjectDetection_InitParams_t::hwaHandle, MmwDemo_DataPathObj_t::hwaHandle, DPM_InitCfg_t::instanceId, DPC_ObjectDetection_InitParams_t::L3ramCfg, MMWave_InitCfg_t::linkCRCCfg, MmwDemo_platformCfg_t::loggingBaudRate, MmwDemo_MCB_t::loggingUartHandle, MMWave_ConfigurationMode_FULL, MMWave_Domain_MSS, MMWave_ExecutionMode_ISOLATION, MMWave_init(), MMWave_sync(), MmwDemo_TaskHandles_t::mmwaveCtrl, MMWDEMO_CLI_TASK_PRIORITY, MmwDemo_CLIInit(), MmwDemo_dataPathInit(), MmwDemo_dataPathOpen(), MmwDemo_debugAssert, MMWDEMO_DPC_OBJDET_DPM_TASK_PRIORITY, MmwDemo_DPC_ObjectDetection_dpmTask(), MmwDemo_DPC_ObjectDetection_processFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_processInterFrameBeginCallBackFxn(), MmwDemo_DPC_ObjectDetection_reportFxn(), MmwDemo_eventCallbackFxn(), MMWDEMO_MMWAVE_CTRL_TASK_PRIORITY, MmwDemo_mmWaveCtrlTask(), MmwDemo_platformInit(), MmwDemo_DataPathObj_t::objDetDpmHandle, MmwDemo_TaskHandles_t::objDetDpmTask, MmwDemo_Cfg_t::platformCfg, DPC_ObjectDetection_InitParams_t::processCallBackCfg, DPC_ObjectDetection_ProcessCallBackCfg_t::processFrameBeginCallBackFxn, DPC_ObjectDetection_ProcessCallBackCfg_t::processInterFrameBeginCallBackFxn, DPM_InitCfg_t::ptrProcChainCfg, DPM_InitCfg_t::reportFxn, DPC_ObjectDetection_MemCfg_t::size, MMWave_InitCfg_t::socHandle, DPM_InitCfg_t::socHandle, MmwDemo_MCB_t::socHandle, MmwDemo_platformCfg_t::sysClockFrequency, MmwDemo_MCB_t::taskHandles, and MMWave_LinkCRCCfg_t::useCRCDriver.
Referenced by main().
uint8_t MmwDemo_isAllCfgInNonPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in non-pending (cleared) state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in non-pending state, else return 0
Definition at line 703 of file main.c.
References MmwDemo_MCB_t::dataPathObj, MmwDemo_isObjDetCommonCfgInNonPendingState(), MmwDemo_isObjDynCfgInNonPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_DataPathObj_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
uint8_t MmwDemo_isAllCfgInPendingState (void)
Description
Utility function to find out if all configuration (common and sub-frame specific dynamic config) is in pending state.
Return values
1 if all configuration (common and sub-frame specific dynamic config) is in pending state, else return 0
Definition at line 682 of file main.c.
References MmwDemo_MCB_t::dataPathObj, MmwDemo_isObjDetCommonCfgPendingState(), MmwDemo_isObjDynCfgPendingState(), DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, MmwDemo_DataPathObj_t::objDetCommonCfg, MmwDemo_SubFrameCfg_t::objDetDynCfg, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, and MmwDemo_MCB_t::subFrameCfg.
Referenced by MmwDemo_CLISensorStart().
static uint8_t MmwDemo_isObjDetCommonCfgInNonPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Utility function to find out if all common configuration is in non-pending (cleared) state.
Parameters
[in] cfg Pointer to common specific configuration
Return values
1 if all common configuration is in non-pending state, else return 0
Definition at line 595 of file main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_isAllCfgInNonPendingState().
static uint8_t MmwDemo_isObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Utility function to find out if all common configuration is pending
Parameters
[in] cfg Pointer to Common configuration
Return values
1 if all common configuration is pending, else return 0.
Definition at line 548 of file main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_isAllCfgInPendingState().
static uint8_t MmwDemo_isObjDynCfgInNonPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Utility function to find out if all sub-frame specific dynamic configuration is in non-pending (cleared) state.
Parameters
[in] cfg Pointer to common specific configuration
Return values
1 if all sub-frame specific dynamic configuration is in non-pending state, else return 0
Definition at line 616 of file main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_isAllCfgInNonPendingState().
static uint8_t MmwDemo_isObjDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Utility function to find out if all sub-frame specific dynamic configuration is pending
Parameters
[in] cfg Pointer to sub-frame specific configuration
Return values
1 if all sub-frame specific dynamic configuration is pending, else return 0
Definition at line 568 of file main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_isAllCfgInPendingState().
void MmwDemo_measurementResultOutput (DPU_AoAProc_compRxChannelBiasCfg * compRxChanCfg)
Definition at line 1556 of file main.c.
References CLI_write(), cmplx16ImRe_t_::imag, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, cmplx16ImRe_t_::real, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, SYS_COMMON_NUM_RX_CHANNEL, and SYS_COMMON_NUM_TX_ANTENNAS.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
void MmwDemo_MMWave_stop (void)
Description
mmw demo helper Function to issue MMWave_stop. The DPM_stop will be called in the BSS frame done call back case.
Return values
None
Definition at line 762 of file main.c.
References MmwDemo_MCB_t::ctrlHandle, MMWave_decodeError(), MMWave_ErrorLevel_ERROR, MMWave_stop(), and MmwDemo_debugAssert.
Referenced by MmwDemo_stopSensor().
void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
Description
The task is used to provide an execution context for the mmWave control task
Return values
Not Applicable.
Definition at line 1301 of file main.c.
References MmwDemo_MCB_t::ctrlHandle, MMWave_execute(), and MmwDemo_debugAssert.
Referenced by MmwDemo_initTask().
int32_t MmwDemo_openSensor (bool isFirstTimeOpen)
Description
mmw demo helper Function to do one time sensor initialization. User need to fill gMmwMCB.cfg.openCfg before calling this function
Parameters
[in] isFirstTimeOpen if true then issues MMwave_open
Return values
0 if no error, -1 if error
Definition at line 854 of file main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_MCB_t::ctrlHandle, MMWave_OpenCfg_t::customCalibrationEnableMask, MMWave_OpenCfg_t::disableFrameStartAsyncEvent, MMWave_OpenCfg_t::disableFrameStopAsyncEvent, MMWave_OpenCfg_t::freqLimitHigh, MMWave_OpenCfg_t::freqLimitLow, MMWave_open(), MmwDemo_Cfg_t::openCfg, and MMWave_OpenCfg_t::useCustomCalibration.
Referenced by MmwDemo_CLISensorStart().
void MmwDemo_platformInit (MmwDemo_platformCfg * config)
Description
Platform specific hardware initialization.
Return values
Not Applicable.
Definition at line 2269 of file main.c.
References MmwDemo_platformCfg_t::commandBaudRate, MmwDemo_platformCfg_t::loggingBaudRate, MSS_SYS_VCLK, MmwDemo_platformCfg_t::SensorStatusGPIO, SOC_XWR68XX_GPIO_2, and MmwDemo_platformCfg_t::sysClockFrequency.
Referenced by MmwDemo_initTask().
static int32_t MmwDemo_processPendingDynamicCfgCommands (uint8_t subFrameIndx) static
Description
Processes any pending dynamic configuration commands for the specified sub-frame by fanning out to the respective DPUs using IOCTL interface, and resets (clears) the pending state after processing.
Parameters
[in] subFrameIndx Sub-frame index of desired sub-frame to process
Return values
Success - 0
Error - <0
Definition at line 1873 of file main.c.
References DPC_ObjectDetection_DynCfg_t::calibDcRangeSigCfg, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, DPC_ObjectDetection_fovRangeCfg_t::cfg, DPC_ObjectDetection_CalibDcRangeSigCfg_t::cfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::cfg, DPC_ObjectDetection_CfarCfg_t::cfg, DPC_ObjectDetection_StaticClutterRemovalCfg_t::cfg, DPC_ObjectDetection_fovAoaCfg_t::cfg, DPC_ObjectDetection_fovDopplerCfg_t::cfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, MmwDemo_MCB_t::dataPathObj, DPC_OBJDET_IOCTL__DYNAMIC_CALIB_DC_RANGE_SIG_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_DOPPLER_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_RANGE_CFG, DPC_OBJDET_IOCTL__DYNAMIC_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_FOV_AOA, DPC_OBJDET_IOCTL__DYNAMIC_FOV_DOPPLER, DPC_OBJDET_IOCTL__DYNAMIC_FOV_RANGE, DPC_OBJDET_IOCTL__DYNAMIC_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_MULTI_OBJ_BEAM_FORM_CFG, DPC_OBJDET_IOCTL__DYNAMIC_RANGE_AZIMUTH_HEAT_MAP, DPC_OBJDET_IOCTL__DYNAMIC_STATICCLUTTER_REMOVAL_CFG, DPM_ioctl(), MmwDemo_DPC_ObjDet_DynCfg_t::dynCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovRange, MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, MmwDemo_DataPathObj_t::objDetCommonCfg, MmwDemo_DataPathObj_t::objDetDpmHandle, MmwDemo_SubFrameCfg_t::objDetDynCfg, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::prepareRangeAzimuthHeatMap, MmwDemo_DPC_ObjDet_CommonCfg_t::preStartCommonCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, MmwDemo_MCB_t::subFrameCfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::subFrameNum, DPC_ObjectDetection_CfarCfg_t::subFrameNum, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::subFrameNum, DPC_ObjectDetection_CalibDcRangeSigCfg_t::subFrameNum, DPC_ObjectDetection_fovDopplerCfg_t::subFrameNum, DPC_ObjectDetection_fovAoaCfg_t::subFrameNum, DPC_ObjectDetection_fovRangeCfg_t::subFrameNum, and DPC_ObjectDetection_StaticClutterRemovalCfg_t::subFrameNum.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
static void MmwDemo_resetObjDetCommonCfgPendingState (MmwDemo_DPC_ObjDet_CommonCfg * cfg) static
Description
Resets (clears) all pending common configuration of Object Detection DPC
Parameters
[in] cfg Object Detection DPC common configuration
Return values
Not Applicable.
Definition at line 643 of file main.c.
References MmwDemo_DPC_ObjDet_CommonCfg_t::isCompRxChannelBiasCfgPending, and MmwDemo_DPC_ObjDet_CommonCfg_t::isMeasureRxChannelBiasCfgPending.
Referenced by MmwDemo_dataPathConfig().
static void MmwDemo_resetObjDetDynCfgPendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg) static
Description
Resets (clears) all pending sub-frame specific dynamic configuration of Object Detection DPC
Parameters
[in] cfg Object Detection DPC sub-frame dynamic configuration
Return values
Not Applicable.
Definition at line 660 of file main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, and MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending.
Referenced by MmwDemo_dataPathConfig().
void MmwDemo_sensorStopEpilog (void)
Description
Epilog processing after sensor has stopped
Return values
None
Definition at line 802 of file main.c.
References MmwDemo_TaskHandles_t::initTask, MmwDemo_TaskHandles_t::mmwaveCtrl, MmwDemo_debugAssert, MmwDemo_TaskHandles_t::objDetDpmTask, and MmwDemo_MCB_t::taskHandles.
Referenced by MmwDemo_stopSensor().
static void MmwDemo_setSubFramePendingState (MmwDemo_DPC_ObjDet_DynCfg * cfg, uint32_t offset) static
Description
Utility function to set the pending state of configuration.
Parameters
[in] cfg Sub-frame specific dynamic configuration
[in] offset Configuration structure offset that uniquely identifies the configuration to set to the pending state.
Return values
None
Definition at line 499 of file main.c.
References MmwDemo_DPC_ObjDet_DynCfg_t::isCalibDcRangeSigCfg, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isCfarCfgRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovAoaCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovDopplerPending, MmwDemo_DPC_ObjDet_DynCfg_t::isFovRangePending, MmwDemo_DPC_ObjDet_DynCfg_t::isMultiObjBeamFormingCfgPending, MmwDemo_DPC_ObjDet_DynCfg_t::isPrepareRangeAzimuthHeatMapPending, MmwDemo_DPC_ObjDet_DynCfg_t::isStaticClutterRemovalCfgPending, MMWDEMO_ADCBUFCFG_OFFSET, MMWDEMO_CALIBDCRANGESIG_OFFSET, MMWDEMO_CFARCFGDOPPLER_OFFSET, MMWDEMO_CFARCFGRANGE_OFFSET, MmwDemo_debugAssert, MMWDEMO_FOVAOA_OFFSET, MMWDEMO_FOVDOPPLER_OFFSET, MMWDEMO_FOVRANGE_OFFSET, MMWDEMO_GUIMONSEL_OFFSET, MMWDEMO_MULTIOBJBEAMFORMING_OFFSET, and MMWDEMO_STATICCLUTTERREMOFVAL_OFFSET.
Referenced by MmwDemo_CfgUpdate().
void MmwDemo_sleep (void)
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 2515 of file main.c.
int32_t MmwDemo_startSensor (void)
Description
mmw demo helper Function to start sensor.
Return values
0 if no error, -1 if error
Definition at line 929 of file main.c.
References MmwDemo_MCB_t::cfg, MMWave_CalibrationCfg_t::chirpCalibrationCfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MCB_t::ctrlHandle, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CalibrationCfg_t::dfeDataOutputMode, MMWave_ChirpCalibrationCfg_t::enableCalibration, MMWave_ChirpCalibrationCfg_t::enablePeriodicity, MMWave_start(), MmwDemo_dataPathStart(), MMWave_ChirpCalibrationCfg_t::periodicTimeInFrames, MmwDemo_Cfg_t::platformCfg, MmwDemo_MCB_t::sensorStartCount, and MmwDemo_platformCfg_t::SensorStatusGPIO.
Referenced by MmwDemo_CLISensorStart().
void MmwDemo_stopSensor ()
Description
Stops the RF and datapath for the sensor. Blocks until both operation are not complete Prints epilog at the end
Return values
None
Definition at line 980 of file main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_MCB_t::DPMstopSemHandle, MmwDemo_MMWave_stop(), MmwDemo_sensorStopEpilog(), MmwDemo_Cfg_t::platformCfg, MmwDemo_MCB_t::sensorStartCount, MmwDemo_platformCfg_t::SensorStatusGPIO, and MmwDemo_MCB_t::sensorStopCount.
Referenced by MmwDemo_CLISensorStop().
void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, DPC_ObjectDetection_ExecuteResult * result, MmwDemo_output_message_stats * timingInfo)
Transmits detection data over UART.
The following data is transmitted:
Header (size = 32bytes), including "Magic word", (size = 8 bytes) and including the number of TLV items TLV Items:
If detectedObjects flag is 1 or 2, DPIF_PointCloudCartesian structure containing X,Y,Z location and velocity for detected objects, size = sizeof(DPIF_PointCloudCartesian) * number of detected objects
If detectedObjects flag is 1, DPIF_PointCloudSideInfo structure containing SNR and noise for detected objects, size = sizeof(DPIF_PointCloudCartesian) * number of detected objects
If logMagRange flag is set, rangeProfile, size = number of range bins * sizeof(uint16_t)
If noiseProfile flag is set, noiseProfile, size = number of range bins * sizeof(uint16_t)
If rangeAzimuthHeatMap flag is set, the zero Doppler column of the range cubed matrix, size = number of Rx Azimuth virtual antennas * number of chirps per frame * sizeof(uint32_t)
If rangeDopplerHeatMap flag is set, the log magnitude range-Doppler matrix, size = number of range bins * number of Doppler bins * sizeof(uint16_t)
If statsInfo flag is set, the stats information
Parameters
[in] uartHandle UART driver handle
[in] result Pointer to result from object detection DPC processing
[in] timingInfo Pointer to sub-frame object stats that contains timing info
Definition at line 1595 of file main.c.
References DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMap, DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMapSize, DPIF_DetMatrix_t::data, MmwDemo_GuiMonSel_t::detectedObjects, DPC_ObjectDetection_ExecuteResult_t::detMatrix, MmwDemo_output_message_header_t::frameNumber, DPC_ObjectDetection_Stats_t::frameStartIntCounter, MmwDemo_SubFrameCfg_t::guiMonSel, MmwDemo_GuiMonSel_t::logMagRange, MmwDemo_output_message_header_t::magicWord, MMWDEMO_OUTPUT_MSG_AZIMUT_STATIC_HEAT_MAP, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS_SIDE_INFO, MMWDEMO_OUTPUT_MSG_MAX, MMWDEMO_OUTPUT_MSG_NOISE_PROFILE, MMWDEMO_OUTPUT_MSG_RANGE_DOPPLER_HEAT_MAP, MMWDEMO_OUTPUT_MSG_RANGE_PROFILE, MMWDEMO_OUTPUT_MSG_SEGMENT_LEN, MMWDEMO_OUTPUT_MSG_STATS, MmwDemo_GuiMonSel_t::noiseProfile, MmwDemo_output_message_header_t::numDetectedObj, MmwDemo_SubFrameCfg_t::numDopplerBins, DPC_ObjectDetection_ExecuteResult_t::numObjOut, MmwDemo_SubFrameCfg_t::numRangeBins, MmwDemo_output_message_header_t::numTLVs, DPC_ObjectDetection_ExecuteResult_t::objOut, DPC_ObjectDetection_ExecuteResult_t::objOutSideInfo, MmwDemo_output_message_header_t::platform, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, MmwDemo_GuiMonSel_t::rangeDopplerHeatMap, DPC_ObjectDetection_ExecuteResult_t::stats, MmwDemo_GuiMonSel_t::statsInfo, MmwDemo_MCB_t::subFrameCfg, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, MmwDemo_output_message_header_t::subFrameNumber, MmwDemo_output_message_header_t::timeCpuCycles, MmwDemo_output_message_header_t::totalPacketLen, and MmwDemo_output_message_header_t::version.
Referenced by MmwDemo_DPC_ObjectDetection_dpmTask().
Variable Documentation
uint8_t gDPC_ObjDetTCM[MMWDEMO_OBJDET_TCM_SIZE]
Definition at line 433 of file main.c.
Referenced by MmwDemo_DPC_ObjectDetection_reportFxn(), and MmwDemo_initTask().
uint8_t gMmwL3[SOC_L3RAM_SIZE]
L3 RAM buffer for object detection DPC
Definition at line 428 of file main.c.
Referenced by MmwDemo_DPC_ObjectDetection_reportFxn(), and MmwDemo_initTask().
MmwDemo_MCB gMmwMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 444 of file main.c.
Referenced by MmwDemo_EDMA_errorCallbackFxn(), and MmwDemo_EDMA_transferControllerErrorCallbackFxn().
Copyright 2018, Texas Instruments Incorporated