/**
 *  @file    reg_dss_xwr16xx.h
 *
 *  @brief
 *    This file gives register definitions of DSS_REG module.
 *
 *  This file is auto-generated on 3/27/2017.
 *
 */

 /*
 *   (C) Copyright 2016, Texas Instruments Incorporated. - TI web address www.ti.com
 *---------------------------------------------------------------------------------------
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *    Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT  OWNER OR CONTRIBUTORS
 *  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *  CONTRACT,  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef REG_DSS_H
#define REG_DSS_H

/****************************************************************************************
 * INCLUDE FILES
 ****************************************************************************************/
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Definition for field EVT0 in Register RTIEVENTCAPTURESEL */
#define RTIEVENTCAPTURESEL_EVT0_BIT_START                   0U
#define RTIEVENTCAPTURESEL_EVT0_BIT_END                     6U

/* Definition for field EVT1 in Register RTIEVENTCAPTURESEL */
#define RTIEVENTCAPTURESEL_EVT1_BIT_START                   16U
#define RTIEVENTCAPTURESEL_EVT1_BIT_END                     22U

/* Definition for field CQDATAWIDTH in Register CQCFG1 */
#define CQCFG1_CQDATAWIDTH_BIT_START                        0U
#define CQCFG1_CQDATAWIDTH_BIT_END                          1U

/* Definition for field CQ96BITPACKEN in Register CQCFG1 */
#define CQCFG1_CQ96BITPACKEN_BIT_START                      3U
#define CQCFG1_CQ96BITPACKEN_BIT_END                        3U

/* Definition for field CQ0BASEADDR in Register CQCFG1 */
#define CQCFG1_CQ0BASEADDR_BIT_START                        4U
#define CQCFG1_CQ0BASEADDR_BIT_END                          12U

/* Definition for field CQ1BASEADDR in Register CQCFG1 */
#define CQCFG1_CQ1BASEADDR_BIT_START                        13U
#define CQCFG1_CQ1BASEADDR_BIT_END                          21U

/* Definition for field CQ2BASEADDR in Register CQCFG1 */
#define CQCFG1_CQ2BASEADDR_BIT_START                        22U
#define CQCFG1_CQ2BASEADDR_BIT_END                          30U

/* Definition for field TPCCPARITYSTAT in Register TPCCPARSTATCFG */
#define TPCCPARSTATCFG_TPCCPARITYSTAT_BIT_START             0U
#define TPCCPARSTATCFG_TPCCPARITYSTAT_BIT_END               7U

/* Definition for field TPCCPARITYCLR in Register TPCCPARSTATCFG */
#define TPCCPARSTATCFG_TPCCPARITYCLR_BIT_START              8U
#define TPCCPARSTATCFG_TPCCPARITYCLR_BIT_END                8U

/* Definition for field TPCCPARITYEN in Register TPCCPARSTATCFG */
#define TPCCPARSTATCFG_TPCCPARITYEN_BIT_START               9U
#define TPCCPARSTATCFG_TPCCPARITYEN_BIT_END                 9U

/* Definition for field TPCCPARITYTSTEN in Register TPCCPARSTATCFG */
#define TPCCPARSTATCFG_TPCCPARITYTSTEN_BIT_START            10U
#define TPCCPARSTATCFG_TPCCPARITYTSTEN_BIT_END              10U

/* Definition for field CSI2TXPARITYSTAT in Register CSI2TXPARSTATCFG */
#define CSI2TXPARSTATCFG_CSI2TXPARITYSTAT_BIT_START         0U
#define CSI2TXPARSTATCFG_CSI2TXPARITYSTAT_BIT_END           6U

/* Definition for field CSI2TXPARITYCLR in Register CSI2TXPARSTATCFG */
#define CSI2TXPARSTATCFG_CSI2TXPARITYCLR_BIT_START          8U
#define CSI2TXPARSTATCFG_CSI2TXPARITYCLR_BIT_END            8U

/* Definition for field CSI2TXPARITYEN in Register CSI2TXPARSTATCFG */
#define CSI2TXPARSTATCFG_CSI2TXPARITYEN_BIT_START           9U
#define CSI2TXPARSTATCFG_CSI2TXPARITYEN_BIT_END             9U

/* Definition for field CSI2TXPARITYTSTEN in Register CSI2TXPARSTATCFG */
#define CSI2TXPARSTATCFG_CSI2TXPARITYTSTEN_BIT_START        10U
#define CSI2TXPARSTATCFG_CSI2TXPARITYTSTEN_BIT_END          10U

/* Definition for field CSIMIDLEREQ in Register CSICFG1 */
#define CSICFG1_CSIMIDLEREQ_BIT_START                       9U
#define CSICFG1_CSIMIDLEREQ_BIT_END                         9U

/* Definition for field CSILANEENABLE in Register CSICFG1 */
#define CSICFG1_CSILANEENABLE_BIT_START                     12U
#define CSICFG1_CSILANEENABLE_BIT_END                       16U

/* Definition for field CSISIDLEACK in Register CSICFG1 */
#define CSICFG1_CSISIDLEACK_BIT_START                       17U
#define CSICFG1_CSISIDLEACK_BIT_END                         17U

/* Definition for field CSIPIPD0 in Register CSICFG1 */
#define CSICFG1_CSIPIPD0_BIT_START                          19U
#define CSICFG1_CSIPIPD0_BIT_END                            19U

/* Definition for field CSIPIPD1 in Register CSICFG1 */
#define CSICFG1_CSIPIPD1_BIT_START                          20U
#define CSICFG1_CSIPIPD1_BIT_END                            20U

/* Definition for field CSIPIPD2 in Register CSICFG1 */
#define CSICFG1_CSIPIPD2_BIT_START                          21U
#define CSICFG1_CSIPIPD2_BIT_END                            21U

/* Definition for field CSIPIPD3 in Register CSICFG1 */
#define CSICFG1_CSIPIPD3_BIT_START                          22U
#define CSICFG1_CSIPIPD3_BIT_END                            22U

/* Definition for field CSIPIPD4 in Register CSICFG1 */
#define CSICFG1_CSIPIPD4_BIT_START                          23U
#define CSICFG1_CSIPIPD4_BIT_END                            23U

/* Definition for field TPTC0WRMPUSTADD0 in Register TPTC0WRMPUSTADD0 */
#define TPTC0WRMPUSTADD0_TPTC0WRMPUSTADD0_BIT_START         0U
#define TPTC0WRMPUSTADD0_TPTC0WRMPUSTADD0_BIT_END           31U

/* Definition for field TPTC0WRMPUSTADD1 in Register TPTC0WRMPUSTADD1 */
#define TPTC0WRMPUSTADD1_TPTC0WRMPUSTADD1_BIT_START         0U
#define TPTC0WRMPUSTADD1_TPTC0WRMPUSTADD1_BIT_END           31U

/* Definition for field TPTC0WRMPUSTADD2 in Register TPTC0WRMPUSTADD2 */
#define TPTC0WRMPUSTADD2_TPTC0WRMPUSTADD2_BIT_START         0U
#define TPTC0WRMPUSTADD2_TPTC0WRMPUSTADD2_BIT_END           31U

/* Definition for field TPTC0WRMPUSTADD3 in Register TPTC0WRMPUSTADD3 */
#define TPTC0WRMPUSTADD3_TPTC0WRMPUSTADD3_BIT_START         0U
#define TPTC0WRMPUSTADD3_TPTC0WRMPUSTADD3_BIT_END           31U

/* Definition for field TPTC0WRMPUSTADD4 in Register TPTC0WRMPUSTADD4 */
#define TPTC0WRMPUSTADD4_TPTC0WRMPUSTADD4_BIT_START         0U
#define TPTC0WRMPUSTADD4_TPTC0WRMPUSTADD4_BIT_END           31U

/* Definition for field TPTC0WRMPUSTADD5 in Register TPTC0WRMPUSTADD5 */
#define TPTC0WRMPUSTADD5_TPTC0WRMPUSTADD5_BIT_START         0U
#define TPTC0WRMPUSTADD5_TPTC0WRMPUSTADD5_BIT_END           31U

/* Definition for field TPTC0WRMPUENDADD0 in Register TPTC0WRMPUENDADD0 */
#define TPTC0WRMPUENDADD0_TPTC0WRMPUENDADD0_BIT_START       0U
#define TPTC0WRMPUENDADD0_TPTC0WRMPUENDADD0_BIT_END         31U

/* Definition for field TPTC0WRMPUENDADD1 in Register TPTC0WRMPUENDADD1 */
#define TPTC0WRMPUENDADD1_TPTC0WRMPUENDADD1_BIT_START       0U
#define TPTC0WRMPUENDADD1_TPTC0WRMPUENDADD1_BIT_END         31U

/* Definition for field TPTC0WRMPUENDADD2 in Register TPTC0WRMPUENDADD2 */
#define TPTC0WRMPUENDADD2_TPTC0WRMPUENDADD2_BIT_START       0U
#define TPTC0WRMPUENDADD2_TPTC0WRMPUENDADD2_BIT_END         31U

/* Definition for field TPTC0WRMPUENDADD3 in Register TPTC0WRMPUENDADD3 */
#define TPTC0WRMPUENDADD3_TPTC0WRMPUENDADD3_BIT_START       0U
#define TPTC0WRMPUENDADD3_TPTC0WRMPUENDADD3_BIT_END         31U

/* Definition for field TPTC0WRMPUENDADD4 in Register TPTC0WRMPUENDADD4 */
#define TPTC0WRMPUENDADD4_TPTC0WRMPUENDADD4_BIT_START       0U
#define TPTC0WRMPUENDADD4_TPTC0WRMPUENDADD4_BIT_END         31U

/* Definition for field TPTC0WRMPUENDADD5 in Register TPTC0WRMPUENDADD5 */
#define TPTC0WRMPUENDADD5_TPTC0WRMPUENDADD5_BIT_START       0U
#define TPTC0WRMPUENDADD5_TPTC0WRMPUENDADD5_BIT_END         31U

/* Definition for field TPTC0WRMPUERRADD in Register TPTC0WRMPUERRADD */
#define TPTC0WRMPUERRADD_TPTC0WRMPUERRADD_BIT_START         0U
#define TPTC0WRMPUERRADD_TPTC0WRMPUERRADD_BIT_END           31U

/* Definition for field TPTC0RDMPUSTADD0 in Register TPTC0RDMPUSTADD0 */
#define TPTC0RDMPUSTADD0_TPTC0RDMPUSTADD0_BIT_START         0U
#define TPTC0RDMPUSTADD0_TPTC0RDMPUSTADD0_BIT_END           31U

/* Definition for field TPTC0RDMPUSTADD1 in Register TPTC0RDMPUSTADD1 */
#define TPTC0RDMPUSTADD1_TPTC0RDMPUSTADD1_BIT_START         0U
#define TPTC0RDMPUSTADD1_TPTC0RDMPUSTADD1_BIT_END           31U

/* Definition for field TPTC0RDMPUSTADD2 in Register TPTC0RDMPUSTADD2 */
#define TPTC0RDMPUSTADD2_TPTC0RDMPUSTADD2_BIT_START         0U
#define TPTC0RDMPUSTADD2_TPTC0RDMPUSTADD2_BIT_END           31U

/* Definition for field TPTC0RDMPUSTADD3 in Register TPTC0RDMPUSTADD3 */
#define TPTC0RDMPUSTADD3_TPTC0RDMPUSTADD3_BIT_START         0U
#define TPTC0RDMPUSTADD3_TPTC0RDMPUSTADD3_BIT_END           31U

/* Definition for field TPTC0RDMPUSTADD4 in Register TPTC0RDMPUSTADD4 */
#define TPTC0RDMPUSTADD4_TPTC0RDMPUSTADD4_BIT_START         0U
#define TPTC0RDMPUSTADD4_TPTC0RDMPUSTADD4_BIT_END           31U

/* Definition for field TPTC0RDMPUSTADD5 in Register TPTC0RDMPUSTADD5 */
#define TPTC0RDMPUSTADD5_TPTC0RDMPUSTADD5_BIT_START         0U
#define TPTC0RDMPUSTADD5_TPTC0RDMPUSTADD5_BIT_END           31U

/* Definition for field TPTC0RDMPUENDADD0 in Register TPTC0RDMPUENDADD0 */
#define TPTC0RDMPUENDADD0_TPTC0RDMPUENDADD0_BIT_START       0U
#define TPTC0RDMPUENDADD0_TPTC0RDMPUENDADD0_BIT_END         31U

/* Definition for field TPTC0RDMPUENDADD1 in Register TPTC0RDMPUENDADD1 */
#define TPTC0RDMPUENDADD1_TPTC0RDMPUENDADD1_BIT_START       0U
#define TPTC0RDMPUENDADD1_TPTC0RDMPUENDADD1_BIT_END         31U

/* Definition for field TPTC0RDMPUENDADD2 in Register TPTC0RDMPUENDADD2 */
#define TPTC0RDMPUENDADD2_TPTC0RDMPUENDADD2_BIT_START       0U
#define TPTC0RDMPUENDADD2_TPTC0RDMPUENDADD2_BIT_END         31U

/* Definition for field TPTC0RDMPUENDADD3 in Register TPTC0RDMPUENDADD3 */
#define TPTC0RDMPUENDADD3_TPTC0RDMPUENDADD3_BIT_START       0U
#define TPTC0RDMPUENDADD3_TPTC0RDMPUENDADD3_BIT_END         31U

/* Definition for field TPTC0RDMPUENDADD4 in Register TPTC0RDMPUENDADD4 */
#define TPTC0RDMPUENDADD4_TPTC0RDMPUENDADD4_BIT_START       0U
#define TPTC0RDMPUENDADD4_TPTC0RDMPUENDADD4_BIT_END         31U

/* Definition for field TPTC0RDMPUENDADD5 in Register TPTC0RDMPUENDADD5 */
#define TPTC0RDMPUENDADD5_TPTC0RDMPUENDADD5_BIT_START       0U
#define TPTC0RDMPUENDADD5_TPTC0RDMPUENDADD5_BIT_END         31U

/* Definition for field TPTC0RDMPUERRADD in Register TPTC0RDMPUERRADD */
#define TPTC0RDMPUERRADD_TPTC0RDMPUERRADD_BIT_START         0U
#define TPTC0RDMPUERRADD_TPTC0RDMPUERRADD_BIT_END           31U

/* Definition for field TPTC1WRMPUSTADD0 in Register TPTC1WRMPUSTADD0 */
#define TPTC1WRMPUSTADD0_TPTC1WRMPUSTADD0_BIT_START         0U
#define TPTC1WRMPUSTADD0_TPTC1WRMPUSTADD0_BIT_END           31U

/* Definition for field TPTC1WRMPUSTADD1 in Register TPTC1WRMPUSTADD1 */
#define TPTC1WRMPUSTADD1_TPTC1WRMPUSTADD1_BIT_START         0U
#define TPTC1WRMPUSTADD1_TPTC1WRMPUSTADD1_BIT_END           31U

/* Definition for field TPTC1WRMPUSTADD2 in Register TPTC1WRMPUSTADD2 */
#define TPTC1WRMPUSTADD2_TPTC1WRMPUSTADD2_BIT_START         0U
#define TPTC1WRMPUSTADD2_TPTC1WRMPUSTADD2_BIT_END           31U

/* Definition for field TPTC1WRMPUSTADD3 in Register TPTC1WRMPUSTADD3 */
#define TPTC1WRMPUSTADD3_TPTC1WRMPUSTADD3_BIT_START         0U
#define TPTC1WRMPUSTADD3_TPTC1WRMPUSTADD3_BIT_END           31U

/* Definition for field TPTC1WRMPUSTADD4 in Register TPTC1WRMPUSTADD4 */
#define TPTC1WRMPUSTADD4_TPTC1WRMPUSTADD4_BIT_START         0U
#define TPTC1WRMPUSTADD4_TPTC1WRMPUSTADD4_BIT_END           31U

/* Definition for field TPTC1WRMPUSTADD5 in Register TPTC1WRMPUSTADD5 */
#define TPTC1WRMPUSTADD5_TPTC1WRMPUSTADD5_BIT_START         0U
#define TPTC1WRMPUSTADD5_TPTC1WRMPUSTADD5_BIT_END           31U

/* Definition for field TPTC1WRMPUENDADD0 in Register TPTC1WRMPUENDADD0 */
#define TPTC1WRMPUENDADD0_TPTC1WRMPUENDADD0_BIT_START       0U
#define TPTC1WRMPUENDADD0_TPTC1WRMPUENDADD0_BIT_END         31U

/* Definition for field TPTC1WRMPUENDADD1 in Register TPTC1WRMPUENDADD1 */
#define TPTC1WRMPUENDADD1_TPTC1WRMPUENDADD1_BIT_START       0U
#define TPTC1WRMPUENDADD1_TPTC1WRMPUENDADD1_BIT_END         31U

/* Definition for field TPTC1WRMPUENDADD2 in Register TPTC1WRMPUENDADD2 */
#define TPTC1WRMPUENDADD2_TPTC1WRMPUENDADD2_BIT_START       0U
#define TPTC1WRMPUENDADD2_TPTC1WRMPUENDADD2_BIT_END         31U

/* Definition for field TPTC1WRMPUENDADD3 in Register TPTC1WRMPUENDADD3 */
#define TPTC1WRMPUENDADD3_TPTC1WRMPUENDADD3_BIT_START       0U
#define TPTC1WRMPUENDADD3_TPTC1WRMPUENDADD3_BIT_END         31U

/* Definition for field TPTC1WRMPUENDADD4 in Register TPTC1WRMPUENDADD4 */
#define TPTC1WRMPUENDADD4_TPTC1WRMPUENDADD4_BIT_START       0U
#define TPTC1WRMPUENDADD4_TPTC1WRMPUENDADD4_BIT_END         31U

/* Definition for field TPTC1WRMPUENDADD5 in Register TPTC1WRMPUENDADD5 */
#define TPTC1WRMPUENDADD5_TPTC1WRMPUENDADD5_BIT_START       0U
#define TPTC1WRMPUENDADD5_TPTC1WRMPUENDADD5_BIT_END         31U

/* Definition for field TPTC1WRMPUERRADD in Register TPTC1WRMPUERRADD */
#define TPTC1WRMPUERRADD_TPTC1WRMPUERRADD_BIT_START         0U
#define TPTC1WRMPUERRADD_TPTC1WRMPUERRADD_BIT_END           31U

/* Definition for field TPTC1RDMPUSTADD0 in Register TPTC1RDMPUSTADD0 */
#define TPTC1RDMPUSTADD0_TPTC1RDMPUSTADD0_BIT_START         0U
#define TPTC1RDMPUSTADD0_TPTC1RDMPUSTADD0_BIT_END           31U

/* Definition for field TPTC1RDMPUSTADD1 in Register TPTC1RDMPUSTADD1 */
#define TPTC1RDMPUSTADD1_TPTC1RDMPUSTADD1_BIT_START         0U
#define TPTC1RDMPUSTADD1_TPTC1RDMPUSTADD1_BIT_END           31U

/* Definition for field TPTC1RDMPUSTADD2 in Register TPTC1RDMPUSTADD2 */
#define TPTC1RDMPUSTADD2_TPTC1RDMPUSTADD2_BIT_START         0U
#define TPTC1RDMPUSTADD2_TPTC1RDMPUSTADD2_BIT_END           31U

/* Definition for field TPTC1RDMPUSTADD3 in Register TPTC1RDMPUSTADD3 */
#define TPTC1RDMPUSTADD3_TPTC1RDMPUSTADD3_BIT_START         0U
#define TPTC1RDMPUSTADD3_TPTC1RDMPUSTADD3_BIT_END           31U

/* Definition for field TPTC1RDMPUSTADD4 in Register TPTC1RDMPUSTADD4 */
#define TPTC1RDMPUSTADD4_TPTC1RDMPUSTADD4_BIT_START         0U
#define TPTC1RDMPUSTADD4_TPTC1RDMPUSTADD4_BIT_END           31U

/* Definition for field TPTC1RDMPUSTADD5 in Register TPTC1RDMPUSTADD5 */
#define TPTC1RDMPUSTADD5_TPTC1RDMPUSTADD5_BIT_START         0U
#define TPTC1RDMPUSTADD5_TPTC1RDMPUSTADD5_BIT_END           31U

/* Definition for field TPTC1RDMPUENDADD0 in Register TPTC1RDMPUENDADD0 */
#define TPTC1RDMPUENDADD0_TPTC1RDMPUENDADD0_BIT_START       0U
#define TPTC1RDMPUENDADD0_TPTC1RDMPUENDADD0_BIT_END         31U

/* Definition for field TPTC1RDMPUENDADD1 in Register TPTC1RDMPUENDADD1 */
#define TPTC1RDMPUENDADD1_TPTC1RDMPUENDADD1_BIT_START       0U
#define TPTC1RDMPUENDADD1_TPTC1RDMPUENDADD1_BIT_END         31U

/* Definition for field TPTC1RDMPUENDADD2 in Register TPTC1RDMPUENDADD2 */
#define TPTC1RDMPUENDADD2_TPTC1RDMPUENDADD2_BIT_START       0U
#define TPTC1RDMPUENDADD2_TPTC1RDMPUENDADD2_BIT_END         31U

/* Definition for field TPTC1RDMPUENDADD3 in Register TPTC1RDMPUENDADD3 */
#define TPTC1RDMPUENDADD3_TPTC1RDMPUENDADD3_BIT_START       0U
#define TPTC1RDMPUENDADD3_TPTC1RDMPUENDADD3_BIT_END         31U

/* Definition for field TPTC1RDMPUENDADD4 in Register TPTC1RDMPUENDADD4 */
#define TPTC1RDMPUENDADD4_TPTC1RDMPUENDADD4_BIT_START       0U
#define TPTC1RDMPUENDADD4_TPTC1RDMPUENDADD4_BIT_END         31U

/* Definition for field TPTC1RDMPUENDADD5 in Register TPTC1RDMPUENDADD5 */
#define TPTC1RDMPUENDADD5_TPTC1RDMPUENDADD5_BIT_START       0U
#define TPTC1RDMPUENDADD5_TPTC1RDMPUENDADD5_BIT_END         31U

/* Definition for field TPTC1RDMPUERRADD in Register TPTC1RDMPUERRADD */
#define TPTC1RDMPUERRADD_TPTC1RDMPUERRADD_BIT_START         0U
#define TPTC1RDMPUERRADD_TPTC1RDMPUERRADD_BIT_END           31U

/* Definition for field TPTC0WRMPURNGVLD in Register TPTCMPUVALIDCFG */
#define TPTCMPUVALIDCFG_TPTC0WRMPURNGVLD_BIT_START          0U
#define TPTCMPUVALIDCFG_TPTC0WRMPURNGVLD_BIT_END            7U

/* Definition for field TPTC0RDMPURNGVLD in Register TPTCMPUVALIDCFG */
#define TPTCMPUVALIDCFG_TPTC0RDMPURNGVLD_BIT_START          8U
#define TPTCMPUVALIDCFG_TPTC0RDMPURNGVLD_BIT_END            15U

/* Definition for field TPTC1WRMPURNGVLD in Register TPTCMPUVALIDCFG */
#define TPTCMPUVALIDCFG_TPTC1WRMPURNGVLD_BIT_START          16U
#define TPTCMPUVALIDCFG_TPTC1WRMPURNGVLD_BIT_END            23U

/* Definition for field TPTC1RDMPURNGVLD in Register TPTCMPUVALIDCFG */
#define TPTCMPUVALIDCFG_TPTC1RDMPURNGVLD_BIT_START          24U
#define TPTCMPUVALIDCFG_TPTC1RDMPURNGVLD_BIT_END            31U

/* Definition for field TPTC0WRMPUEN in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC0WRMPUEN_BIT_START                 0U
#define TPTCMPUENCFG_TPTC0WRMPUEN_BIT_END                   0U

/* Definition for field TPTC0RDMPUEN in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC0RDMPUEN_BIT_START                 1U
#define TPTCMPUENCFG_TPTC0RDMPUEN_BIT_END                   1U

/* Definition for field TPTC1WRMPUEN in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC1WRMPUEN_BIT_START                 2U
#define TPTCMPUENCFG_TPTC1WRMPUEN_BIT_END                   2U

/* Definition for field TPTC1RDMPUEN in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC1RDMPUEN_BIT_START                 3U
#define TPTCMPUENCFG_TPTC1RDMPUEN_BIT_END                   3U

/* Definition for field TPTC0WRMPUERRCLR in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC0WRMPUERRCLR_BIT_START             4U
#define TPTCMPUENCFG_TPTC0WRMPUERRCLR_BIT_END               4U

/* Definition for field TPTC0RDMPUERRCLR in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC0RDMPUERRCLR_BIT_START             5U
#define TPTCMPUENCFG_TPTC0RDMPUERRCLR_BIT_END               5U

/* Definition for field TPTC1WRMPUERRCLR in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC1WRMPUERRCLR_BIT_START             6U
#define TPTCMPUENCFG_TPTC1WRMPUERRCLR_BIT_END               6U

/* Definition for field TPTC1RDMPUERRCLR in Register TPTCMPUENCFG */
#define TPTCMPUENCFG_TPTC1RDMPUERRCLR_BIT_START             7U
#define TPTCMPUENCFG_TPTC1RDMPUERRCLR_BIT_END               7U

/* Definition for field TSTPATRX1IOFFSET in Register TESTPATTERNRX1ICFG */
#define TESTPATTERNRX1ICFG_TSTPATRX1IOFFSET_BIT_START       0U
#define TESTPATTERNRX1ICFG_TSTPATRX1IOFFSET_BIT_END         15U

/* Definition for field TSTPATRX1IINCR in Register TESTPATTERNRX1ICFG */
#define TESTPATTERNRX1ICFG_TSTPATRX1IINCR_BIT_START         16U
#define TESTPATTERNRX1ICFG_TSTPATRX1IINCR_BIT_END           31U

/* Definition for field TSTPATRX2IOFFSET in Register TESTPATTERNRX2ICFG */
#define TESTPATTERNRX2ICFG_TSTPATRX2IOFFSET_BIT_START       0U
#define TESTPATTERNRX2ICFG_TSTPATRX2IOFFSET_BIT_END         15U

/* Definition for field TSTPATRX2IINCR in Register TESTPATTERNRX2ICFG */
#define TESTPATTERNRX2ICFG_TSTPATRX2IINCR_BIT_START         16U
#define TESTPATTERNRX2ICFG_TSTPATRX2IINCR_BIT_END           31U

/* Definition for field TSTPATRX3IOFFSET in Register TESTPATTERNRX3ICFG */
#define TESTPATTERNRX3ICFG_TSTPATRX3IOFFSET_BIT_START       0U
#define TESTPATTERNRX3ICFG_TSTPATRX3IOFFSET_BIT_END         15U

/* Definition for field TSTPATRX3IINCR in Register TESTPATTERNRX3ICFG */
#define TESTPATTERNRX3ICFG_TSTPATRX3IINCR_BIT_START         16U
#define TESTPATTERNRX3ICFG_TSTPATRX3IINCR_BIT_END           31U

/* Definition for field TSTPATRX4IOFFSET in Register TESTPATTERNRX4ICFG */
#define TESTPATTERNRX4ICFG_TSTPATRX4IOFFSET_BIT_START       0U
#define TESTPATTERNRX4ICFG_TSTPATRX4IOFFSET_BIT_END         15U

/* Definition for field TSTPATRX4IINCR in Register TESTPATTERNRX4ICFG */
#define TESTPATTERNRX4ICFG_TSTPATRX4IINCR_BIT_START         16U
#define TESTPATTERNRX4ICFG_TSTPATRX4IINCR_BIT_END           31U

/* Definition for field TSTPATRX1QOFFSET in Register TESTPATTERNRX1QCFG */
#define TESTPATTERNRX1QCFG_TSTPATRX1QOFFSET_BIT_START       0U
#define TESTPATTERNRX1QCFG_TSTPATRX1QOFFSET_BIT_END         15U

/* Definition for field TSTPATRX1QINCR in Register TESTPATTERNRX1QCFG */
#define TESTPATTERNRX1QCFG_TSTPATRX1QINCR_BIT_START         16U
#define TESTPATTERNRX1QCFG_TSTPATRX1QINCR_BIT_END           31U

/* Definition for field TSTPATRX2QOFFSET in Register TESTPATTERNRX2QCFG */
#define TESTPATTERNRX2QCFG_TSTPATRX2QOFFSET_BIT_START       0U
#define TESTPATTERNRX2QCFG_TSTPATRX2QOFFSET_BIT_END         15U

/* Definition for field TSTPATRX2QINCR in Register TESTPATTERNRX2QCFG */
#define TESTPATTERNRX2QCFG_TSTPATRX2QINCR_BIT_START         16U
#define TESTPATTERNRX2QCFG_TSTPATRX2QINCR_BIT_END           31U

/* Definition for field TSTPATRX3QOFFSET in Register TESTPATTERNRX3QCFG */
#define TESTPATTERNRX3QCFG_TSTPATRX3QOFFSET_BIT_START       0U
#define TESTPATTERNRX3QCFG_TSTPATRX3QOFFSET_BIT_END         15U

/* Definition for field TSTPATRX3QINCR in Register TESTPATTERNRX3QCFG */
#define TESTPATTERNRX3QCFG_TSTPATRX3QINCR_BIT_START         16U
#define TESTPATTERNRX3QCFG_TSTPATRX3QINCR_BIT_END           31U

/* Definition for field TSTPATRX4QOFFSET in Register TESTPATTERNRX4QCFG */
#define TESTPATTERNRX4QCFG_TSTPATRX4QOFFSET_BIT_START       0U
#define TESTPATTERNRX4QCFG_TSTPATRX4QOFFSET_BIT_END         15U

/* Definition for field TSTPATRX4QINCR in Register TESTPATTERNRX4QCFG */
#define TESTPATTERNRX4QCFG_TSTPATRX4QINCR_BIT_START         16U
#define TESTPATTERNRX4QCFG_TSTPATRX4QINCR_BIT_END           31U

/* Definition for field TSTPATVLDCNT in Register TESTPATTERNVLDCFG */
#define TESTPATTERNVLDCFG_TSTPATVLDCNT_BIT_START            0U
#define TESTPATTERNVLDCFG_TSTPATVLDCNT_BIT_END              7U

/* Definition for field TSTPATGENEN in Register TESTPATTERNVLDCFG */
#define TESTPATTERNVLDCFG_TSTPATGENEN_BIT_START             8U
#define TESTPATTERNVLDCFG_TSTPATGENEN_BIT_END               10U

/* Definition for field FFTACCSLVEN in Register DSSMISC */
#define DSSMISC_FFTACCSLVEN_BIT_START                       6U
#define DSSMISC_FFTACCSLVEN_BIT_END                         8U

/* Definition for field TPCC1PARITYSTAT in Register TPCC1PARSTATCFG */
#define TPCC1PARSTATCFG_TPCC1PARITYSTAT_BIT_START           0U
#define TPCC1PARSTATCFG_TPCC1PARITYSTAT_BIT_END             8U

/* Definition for field TPCC1PARITYCLR in Register TPCC1PARSTATCFG */
#define TPCC1PARSTATCFG_TPCC1PARITYCLR_BIT_START            9U
#define TPCC1PARSTATCFG_TPCC1PARITYCLR_BIT_END              9U

/* Definition for field TPCC1PARITYEN in Register TPCC1PARSTATCFG */
#define TPCC1PARSTATCFG_TPCC1PARITYEN_BIT_START             10U
#define TPCC1PARSTATCFG_TPCC1PARITYEN_BIT_END               10U

/* Definition for field TPCC1PARITYTSTEN in Register TPCC1PARSTATCFG */
#define TPCC1PARSTATCFG_TPCC1PARITYTSTEN_BIT_START          11U
#define TPCC1PARSTATCFG_TPCC1PARITYTSTEN_BIT_END            11U

/* Definition for field DMMADCBUFPINPONSEL in Register DMMSWINT1 */
#define DMMSWINT1_DMMADCBUFPINPONSEL_BIT_START              16U
#define DMMSWINT1_DMMADCBUFPINPONSEL_BIT_END                16U

/* Definition for field DMMADCBUFWREN in Register DMMSWINT1 */
#define DMMSWINT1_DMMADCBUFWREN_BIT_START                   17U
#define DMMSWINT1_DMMADCBUFWREN_BIT_END                     17U

/* Definition for field DMMCPBPMPINPONSEL in Register DMMSWINT1 */
#define DMMSWINT1_DMMCPBPMPINPONSEL_BIT_START               18U
#define DMMSWINT1_DMMCPBPMPINPONSEL_BIT_END                 18U

/* Definition for field DMMCPBPMWREN in Register DMMSWINT1 */
#define DMMSWINT1_DMMCPBPMWREN_BIT_START                    19U
#define DMMSWINT1_DMMCPBPMWREN_BIT_END                      19U

/* Definition for field DMMCPBPMMEMSEL in Register DMMSWINT1 */
#define DMMSWINT1_DMMCPBPMMEMSEL_BIT_START                  20U
#define DMMSWINT1_DMMCPBPMMEMSEL_BIT_END                    20U

/* Definition for field DMMCQPINPONSEL in Register DMMSWINT1 */
#define DMMSWINT1_DMMCQPINPONSEL_BIT_START                  21U
#define DMMSWINT1_DMMCQPINPONSEL_BIT_END                    21U

/* Definition for field DMMCQWREN in Register DMMSWINT1 */
#define DMMSWINT1_DMMCQWREN_BIT_START                       22U
#define DMMSWINT1_DMMCQWREN_BIT_END                         22U

/* Definition for field FRAMESTRTINTMUXSEL in Register DSSINTRCFG */
#define DSSINTRCFG_FRAMESTRTINTMUXSEL_BIT_START             0U
#define DSSINTRCFG_FRAMESTRTINTMUXSEL_BIT_END               1U

/* Definition for field CHIRPAVLINTMUXSEL in Register DSSINTRCFG */
#define DSSINTRCFG_CHIRPAVLINTMUXSEL_BIT_START              2U
#define DSSINTRCFG_CHIRPAVLINTMUXSEL_BIT_END                3U

/* Definition for field PINPONINTMUXSEL in Register DSSINTRCFG */
#define DSSINTRCFG_PINPONINTMUXSEL_BIT_START                4U
#define DSSINTRCFG_PINPONINTMUXSEL_BIT_END                  5U

/* Definition for field LGFRAMESTRTINTMUXSEL in Register DSSINTRCFG */
#define DSSINTRCFG_LGFRAMESTRTINTMUXSEL_BIT_START           6U
#define DSSINTRCFG_LGFRAMESTRTINTMUXSEL_BIT_END             7U

/* Definition for field MPUMSTID0 in Register MPUMSTIDCFG1 */
#define MPUMSTIDCFG1_MPUMSTID0_BIT_START                    0U
#define MPUMSTIDCFG1_MPUMSTID0_BIT_END                      7U

/* Definition for field MPUMSTID1 in Register MPUMSTIDCFG1 */
#define MPUMSTIDCFG1_MPUMSTID1_BIT_START                    8U
#define MPUMSTIDCFG1_MPUMSTID1_BIT_END                      15U

/* Definition for field MPUMSTID2 in Register MPUMSTIDCFG1 */
#define MPUMSTIDCFG1_MPUMSTID2_BIT_START                    16U
#define MPUMSTIDCFG1_MPUMSTID2_BIT_END                      23U

/* Definition for field MPUMSTID3 in Register MPUMSTIDCFG1 */
#define MPUMSTIDCFG1_MPUMSTID3_BIT_START                    24U
#define MPUMSTIDCFG1_MPUMSTID3_BIT_END                      31U

/* Definition for field MPUMSTID4 in Register MPUMSTIDCFG2 */
#define MPUMSTIDCFG2_MPUMSTID4_BIT_START                    0U
#define MPUMSTIDCFG2_MPUMSTID4_BIT_END                      7U

/* Definition for field MPUMSTID5 in Register MPUMSTIDCFG2 */
#define MPUMSTIDCFG2_MPUMSTID5_BIT_START                    8U
#define MPUMSTIDCFG2_MPUMSTID5_BIT_END                      15U

/* Definition for field MPUMSTID6 in Register MPUMSTIDCFG2 */
#define MPUMSTIDCFG2_MPUMSTID6_BIT_START                    16U
#define MPUMSTIDCFG2_MPUMSTID6_BIT_END                      23U

/* Definition for field MPUMSTID7 in Register MPUMSTIDCFG2 */
#define MPUMSTIDCFG2_MPUMSTID7_BIT_START                    24U
#define MPUMSTIDCFG2_MPUMSTID7_BIT_END                      31U

/* Definition for field MPUMSTIDVLD in Register MPUMSTIDCFG3 */
#define MPUMSTIDCFG3_MPUMSTIDVLD_BIT_START                  0U
#define MPUMSTIDCFG3_MPUMSTIDVLD_BIT_END                    7U

/* Definition for field MPUERRMSTID in Register MPUMSTIDCFG3 */
#define MPUMSTIDCFG3_MPUERRMSTID_BIT_START                  8U
#define MPUMSTIDCFG3_MPUERRMSTID_BIT_END                    15U

/* Definition for field MPUERRCLR in Register MPUMSTIDCFG3 */
#define MPUMSTIDCFG3_MPUERRCLR_BIT_START                    17U
#define MPUMSTIDCFG3_MPUERRCLR_BIT_END                      17U

/* Definition for field MPUMSTIDEN in Register MPUMSTIDCFG3 */
#define MPUMSTIDCFG3_MPUMSTIDEN_BIT_START                   19U
#define MPUMSTIDCFG3_MPUMSTIDEN_BIT_END                     19U

/* Definition for field HSRAM1ECCINIT in Register HSRAM1ECCCFG */
#define HSRAM1ECCCFG_HSRAM1ECCINIT_BIT_START                0U
#define HSRAM1ECCCFG_HSRAM1ECCINIT_BIT_END                  0U

/* Definition for field HSRAM1ECCINITDONE in Register HSRAM1ECCCFG */
#define HSRAM1ECCCFG_HSRAM1ECCINITDONE_BIT_START            1U
#define HSRAM1ECCCFG_HSRAM1ECCINITDONE_BIT_END              1U

/* Definition for field HSRAM1ECCEN in Register HSRAM1ECCCFG */
#define HSRAM1ECCCFG_HSRAM1ECCEN_BIT_START                  2U
#define HSRAM1ECCCFG_HSRAM1ECCEN_BIT_END                    2U

/* Definition for field HSRAM1ECCERRCLR in Register HSRAM1ECCCFG */
#define HSRAM1ECCCFG_HSRAM1ECCERRCLR_BIT_START              3U
#define HSRAM1ECCCFG_HSRAM1ECCERRCLR_BIT_END                3U

/* Definition for field HSRAM1ECCFAULTADDRESS in Register HSRAM1ECCCFG */
#define HSRAM1ECCCFG_HSRAM1ECCFAULTADDRESS_BIT_START        4U
#define HSRAM1ECCCFG_HSRAM1ECCFAULTADDRESS_BIT_END          14U

/* Definition for field HSRAM1ECCREPAIREDBIT in Register HSRAM1ECCCFG */
#define HSRAM1ECCCFG_HSRAM1ECCREPAIREDBIT_BIT_START         15U
#define HSRAM1ECCCFG_HSRAM1ECCREPAIREDBIT_BIT_END           22U

/* Definition for field DATATRRAMECCINIT in Register DATATRRAMECCCFG */
#define DATATRRAMECCCFG_DATATRRAMECCINIT_BIT_START          0U
#define DATATRRAMECCCFG_DATATRRAMECCINIT_BIT_END            0U

/* Definition for field DATATRRAMECCINITDONE in Register DATATRRAMECCCFG */
#define DATATRRAMECCCFG_DATATRRAMECCINITDONE_BIT_START      1U
#define DATATRRAMECCCFG_DATATRRAMECCINITDONE_BIT_END        1U

/* Definition for field DATATRRAMECCEN in Register DATATRRAMECCCFG */
#define DATATRRAMECCCFG_DATATRRAMECCEN_BIT_START            2U
#define DATATRRAMECCCFG_DATATRRAMECCEN_BIT_END              2U

/* Definition for field DATATRRAMECCERRCLR in Register DATATRRAMECCCFG */
#define DATATRRAMECCCFG_DATATRRAMECCERRCLR_BIT_START        3U
#define DATATRRAMECCCFG_DATATRRAMECCERRCLR_BIT_END          3U

/* Definition for field DATATRRAMECCFAULTADDRESS in Register DATATRRAMECCCFG */
#define DATATRRAMECCCFG_DATATRRAMECCFAULTADDRESS_BIT_START  4U
#define DATATRRAMECCCFG_DATATRRAMECCFAULTADDRESS_BIT_END    12U

/* Definition for field DATATRRAMECCREPAIREDBIT in Register DATATRRAMECCCFG */
#define DATATRRAMECCCFG_DATATRRAMECCREPAIREDBIT_BIT_START   13U
#define DATATRRAMECCCFG_DATATRRAMECCREPAIREDBIT_BIT_END     20U

/* Definition for field ADCBUFPINGECCINIT in Register ADCBUFPINGECCCFG */
#define ADCBUFPINGECCCFG_ADCBUFPINGECCINIT_BIT_START        0U
#define ADCBUFPINGECCCFG_ADCBUFPINGECCINIT_BIT_END          0U

/* Definition for field ADCBUFPINGECCINITDONE in Register ADCBUFPINGECCCFG */
#define ADCBUFPINGECCCFG_ADCBUFPINGECCINITDONE_BIT_START    1U
#define ADCBUFPINGECCCFG_ADCBUFPINGECCINITDONE_BIT_END      1U

/* Definition for field ADCBUFPINGECCEN in Register ADCBUFPINGECCCFG */
#define ADCBUFPINGECCCFG_ADCBUFPINGECCEN_BIT_START          2U
#define ADCBUFPINGECCCFG_ADCBUFPINGECCEN_BIT_END            2U

/* Definition for field ADCBUFPINGECCERRCLR in Register ADCBUFPINGECCCFG */
#define ADCBUFPINGECCCFG_ADCBUFPINGECCERRCLR_BIT_START      3U
#define ADCBUFPINGECCCFG_ADCBUFPINGECCERRCLR_BIT_END        3U

/* Definition for field ADCBUFPINGECCFAULTADDRESS in Register ADCBUFPINGECCCFG */
#define ADCBUFPINGECCCFG_ADCBUFPINGECCFAULTADDRESS_BIT_START 4U
#define ADCBUFPINGECCCFG_ADCBUFPINGECCFAULTADDRESS_BIT_END  14U

/* Definition for field ADCBUFPINGECCREPAIREDBIT in Register ADCBUFPINGECCCFG */
#define ADCBUFPINGECCCFG_ADCBUFPINGECCREPAIREDBIT_BIT_START 15U
#define ADCBUFPINGECCCFG_ADCBUFPINGECCREPAIREDBIT_BIT_END   22U

/* Definition for field ADCBUFPONGECCINIT in Register ADCBUFPONGECCCFG */
#define ADCBUFPONGECCCFG_ADCBUFPONGECCINIT_BIT_START        0U
#define ADCBUFPONGECCCFG_ADCBUFPONGECCINIT_BIT_END          0U

/* Definition for field ADCBUFPONGECCINITDONE in Register ADCBUFPONGECCCFG */
#define ADCBUFPONGECCCFG_ADCBUFPONGECCINITDONE_BIT_START    1U
#define ADCBUFPONGECCCFG_ADCBUFPONGECCINITDONE_BIT_END      1U

/* Definition for field ADCBUFPONGECCEN in Register ADCBUFPONGECCCFG */
#define ADCBUFPONGECCCFG_ADCBUFPONGECCEN_BIT_START          2U
#define ADCBUFPONGECCCFG_ADCBUFPONGECCEN_BIT_END            2U

/* Definition for field ADCBUFPONGECCERRCLR in Register ADCBUFPONGECCCFG */
#define ADCBUFPONGECCCFG_ADCBUFPONGECCERRCLR_BIT_START      3U
#define ADCBUFPONGECCCFG_ADCBUFPONGECCERRCLR_BIT_END        3U

/* Definition for field ADCBUFPONGECCFAULTADDRESS in Register ADCBUFPONGECCCFG */
#define ADCBUFPONGECCCFG_ADCBUFPONGECCFAULTADDRESS_BIT_START 4U
#define ADCBUFPONGECCCFG_ADCBUFPONGECCFAULTADDRESS_BIT_END  14U

/* Definition for field ADCBUFPONGECCREPAIREDBIT in Register ADCBUFPONGECCCFG */
#define ADCBUFPONGECCCFG_ADCBUFPONGECCREPAIREDBIT_BIT_START 15U
#define ADCBUFPONGECCCFG_ADCBUFPONGECCREPAIREDBIT_BIT_END   22U

/* Definition for field UMAP0PAREN in Register UMAP0PARITYCFG1 */
#define UMAP0PARITYCFG1_UMAP0PAREN_BIT_START                0U
#define UMAP0PARITYCFG1_UMAP0PAREN_BIT_END                  0U

/* Definition for field UMAP0PARERRCLR in Register UMAP0PARITYCFG1 */
#define UMAP0PARITYCFG1_UMAP0PARERRCLR_BIT_START            1U
#define UMAP0PARITYCFG1_UMAP0PARERRCLR_BIT_END              1U

/* Definition for field UMAP0BANK01ERROUT in Register UMAP0PARITYCFG1 */
#define UMAP0PARITYCFG1_UMAP0BANK01ERROUT_BIT_START         2U
#define UMAP0PARITYCFG1_UMAP0BANK01ERROUT_BIT_END           2U

/* Definition for field UMAP0BANK23ERROUT in Register UMAP0PARITYCFG1 */
#define UMAP0PARITYCFG1_UMAP0BANK23ERROUT_BIT_START         3U
#define UMAP0PARITYCFG1_UMAP0BANK23ERROUT_BIT_END           3U

/* Definition for field UMAP0BANK01ADDOUT in Register UMAP0PARITYCFG1 */
#define UMAP0PARITYCFG1_UMAP0BANK01ADDOUT_BIT_START         4U
#define UMAP0PARITYCFG1_UMAP0BANK01ADDOUT_BIT_END           14U

/* Definition for field UMAP0BANK23ADDOUT in Register UMAP0PARITYCFG1 */
#define UMAP0PARITYCFG1_UMAP0BANK23ADDOUT_BIT_START         15U
#define UMAP0PARITYCFG1_UMAP0BANK23ADDOUT_BIT_END           25U

/* Definition for field UMAP0BANK0BITOUT in Register UMAP0PARITYCFG2 */
#define UMAP0PARITYCFG2_UMAP0BANK0BITOUT_BIT_START          0U
#define UMAP0PARITYCFG2_UMAP0BANK0BITOUT_BIT_END            15U

/* Definition for field UMAP0BANK1BITOUT in Register UMAP0PARITYCFG2 */
#define UMAP0PARITYCFG2_UMAP0BANK1BITOUT_BIT_START          16U
#define UMAP0PARITYCFG2_UMAP0BANK1BITOUT_BIT_END            31U

/* Definition for field UMAP0BANK2BITOUT in Register UMAP0PARITYCFG3 */
#define UMAP0PARITYCFG3_UMAP0BANK2BITOUT_BIT_START          0U
#define UMAP0PARITYCFG3_UMAP0BANK2BITOUT_BIT_END            15U

/* Definition for field UMAP0BANK3BITOUT in Register UMAP0PARITYCFG3 */
#define UMAP0PARITYCFG3_UMAP0BANK3BITOUT_BIT_START          16U
#define UMAP0PARITYCFG3_UMAP0BANK3BITOUT_BIT_END            31U

/* Definition for field UMAP1PAREN in Register UMAP1PARITYCFG1 */
#define UMAP1PARITYCFG1_UMAP1PAREN_BIT_START                0U
#define UMAP1PARITYCFG1_UMAP1PAREN_BIT_END                  0U

/* Definition for field UMAP1PARERRCLR in Register UMAP1PARITYCFG1 */
#define UMAP1PARITYCFG1_UMAP1PARERRCLR_BIT_START            1U
#define UMAP1PARITYCFG1_UMAP1PARERRCLR_BIT_END              1U

/* Definition for field UMAP1BANK01ERROUT in Register UMAP1PARITYCFG1 */
#define UMAP1PARITYCFG1_UMAP1BANK01ERROUT_BIT_START         2U
#define UMAP1PARITYCFG1_UMAP1BANK01ERROUT_BIT_END           2U

/* Definition for field UMAP1BANK23ERROUT in Register UMAP1PARITYCFG1 */
#define UMAP1PARITYCFG1_UMAP1BANK23ERROUT_BIT_START         3U
#define UMAP1PARITYCFG1_UMAP1BANK23ERROUT_BIT_END           3U

/* Definition for field UMAP1BANK01ADDOUT in Register UMAP1PARITYCFG1 */
#define UMAP1PARITYCFG1_UMAP1BANK01ADDOUT_BIT_START         4U
#define UMAP1PARITYCFG1_UMAP1BANK01ADDOUT_BIT_END           14U

/* Definition for field UMAP1BANK23ADDOUT in Register UMAP1PARITYCFG1 */
#define UMAP1PARITYCFG1_UMAP1BANK23ADDOUT_BIT_START         15U
#define UMAP1PARITYCFG1_UMAP1BANK23ADDOUT_BIT_END           25U

/* Definition for field UMAP1BANK0BITOUT in Register UMAP1PARITYCFG2 */
#define UMAP1PARITYCFG2_UMAP1BANK0BITOUT_BIT_START          0U
#define UMAP1PARITYCFG2_UMAP1BANK0BITOUT_BIT_END            15U

/* Definition for field UMAP1BANK1BITOUT in Register UMAP1PARITYCFG2 */
#define UMAP1PARITYCFG2_UMAP1BANK1BITOUT_BIT_START          16U
#define UMAP1PARITYCFG2_UMAP1BANK1BITOUT_BIT_END            31U

/* Definition for field UMAP1BANK2BITOUT in Register UMAP1PARITYCFG3 */
#define UMAP1PARITYCFG3_UMAP1BANK2BITOUT_BIT_START          0U
#define UMAP1PARITYCFG3_UMAP1BANK2BITOUT_BIT_END            15U

/* Definition for field UMAP1BANK3BITOUT in Register UMAP1PARITYCFG3 */
#define UMAP1PARITYCFG3_UMAP1BANK3BITOUT_BIT_START          16U
#define UMAP1PARITYCFG3_UMAP1BANK3BITOUT_BIT_END            31U

/* Definition for field ESMGRP2MASK in Register ESMGRP2MASKCFG */
#define ESMGRP2MASKCFG_ESMGRP2MASK_BIT_START                0U
#define ESMGRP2MASKCFG_ESMGRP2MASK_BIT_END                  31U

/* Definition for field UMAP0BANK0DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK0DATAINIT_BIT_START          0U
#define L2MEMINITCFG1_UMAP0BANK0DATAINIT_BIT_END            0U

/* Definition for field UMAP0BANK1DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK1DATAINIT_BIT_START          1U
#define L2MEMINITCFG1_UMAP0BANK1DATAINIT_BIT_END            1U

/* Definition for field UMAP0BANK2DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK2DATAINIT_BIT_START          2U
#define L2MEMINITCFG1_UMAP0BANK2DATAINIT_BIT_END            2U

/* Definition for field UMAP0BANK3DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK3DATAINIT_BIT_START          3U
#define L2MEMINITCFG1_UMAP0BANK3DATAINIT_BIT_END            3U

/* Definition for field UMAP1BANK0DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK0DATAINIT_BIT_START          4U
#define L2MEMINITCFG1_UMAP1BANK0DATAINIT_BIT_END            4U

/* Definition for field UMAP1BANK1DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK1DATAINIT_BIT_START          5U
#define L2MEMINITCFG1_UMAP1BANK1DATAINIT_BIT_END            5U

/* Definition for field UMAP1BANK2DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK2DATAINIT_BIT_START          6U
#define L2MEMINITCFG1_UMAP1BANK2DATAINIT_BIT_END            6U

/* Definition for field UMAP1BANK3DATAINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK3DATAINIT_BIT_START          7U
#define L2MEMINITCFG1_UMAP1BANK3DATAINIT_BIT_END            7U

/* Definition for field UMAP0BANK0PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK0PARINIT_BIT_START           8U
#define L2MEMINITCFG1_UMAP0BANK0PARINIT_BIT_END             8U

/* Definition for field UMAP0BANK1PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK1PARINIT_BIT_START           9U
#define L2MEMINITCFG1_UMAP0BANK1PARINIT_BIT_END             9U

/* Definition for field UMAP0BANK2PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK2PARINIT_BIT_START           10U
#define L2MEMINITCFG1_UMAP0BANK2PARINIT_BIT_END             10U

/* Definition for field UMAP0BANK3PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK3PARINIT_BIT_START           11U
#define L2MEMINITCFG1_UMAP0BANK3PARINIT_BIT_END             11U

/* Definition for field UMAP1BANK0PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK0PARINIT_BIT_START           12U
#define L2MEMINITCFG1_UMAP1BANK0PARINIT_BIT_END             12U

/* Definition for field UMAP1BANK1PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK1PARINIT_BIT_START           13U
#define L2MEMINITCFG1_UMAP1BANK1PARINIT_BIT_END             13U

/* Definition for field UMAP1BANK2PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK2PARINIT_BIT_START           14U
#define L2MEMINITCFG1_UMAP1BANK2PARINIT_BIT_END             14U

/* Definition for field UMAP1BANK3PARINIT in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK3PARINIT_BIT_START           15U
#define L2MEMINITCFG1_UMAP1BANK3PARINIT_BIT_END             15U

/* Definition for field UMAP0BANK0DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK0DATAINITDONE_BIT_START      16U
#define L2MEMINITCFG1_UMAP0BANK0DATAINITDONE_BIT_END        16U

/* Definition for field UMAP0BANK1DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK1DATAINITDONE_BIT_START      17U
#define L2MEMINITCFG1_UMAP0BANK1DATAINITDONE_BIT_END        17U

/* Definition for field UMAP0BANK2DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK2DATAINITDONE_BIT_START      18U
#define L2MEMINITCFG1_UMAP0BANK2DATAINITDONE_BIT_END        18U

/* Definition for field UMAP0BANK3DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK3DATAINITDONE_BIT_START      19U
#define L2MEMINITCFG1_UMAP0BANK3DATAINITDONE_BIT_END        19U

/* Definition for field UMAP1BANK0DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK0DATAINITDONE_BIT_START      20U
#define L2MEMINITCFG1_UMAP1BANK0DATAINITDONE_BIT_END        20U

/* Definition for field UMAP1BANK1DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK1DATAINITDONE_BIT_START      21U
#define L2MEMINITCFG1_UMAP1BANK1DATAINITDONE_BIT_END        21U

/* Definition for field UMAP1BANK2DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK2DATAINITDONE_BIT_START      22U
#define L2MEMINITCFG1_UMAP1BANK2DATAINITDONE_BIT_END        22U

/* Definition for field UMAP1BANK3DATAINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK3DATAINITDONE_BIT_START      23U
#define L2MEMINITCFG1_UMAP1BANK3DATAINITDONE_BIT_END        23U

/* Definition for field UMAP0BANK0PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK0PARINITDONE_BIT_START       24U
#define L2MEMINITCFG1_UMAP0BANK0PARINITDONE_BIT_END         24U

/* Definition for field UMAP0BANK1PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK1PARINITDONE_BIT_START       25U
#define L2MEMINITCFG1_UMAP0BANK1PARINITDONE_BIT_END         25U

/* Definition for field UMAP0BANK2PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK2PARINITDONE_BIT_START       26U
#define L2MEMINITCFG1_UMAP0BANK2PARINITDONE_BIT_END         26U

/* Definition for field UMAP0BANK3PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP0BANK3PARINITDONE_BIT_START       27U
#define L2MEMINITCFG1_UMAP0BANK3PARINITDONE_BIT_END         27U

/* Definition for field UMAP1BANK0PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK0PARINITDONE_BIT_START       28U
#define L2MEMINITCFG1_UMAP1BANK0PARINITDONE_BIT_END         28U

/* Definition for field UMAP1BANK1PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK1PARINITDONE_BIT_START       29U
#define L2MEMINITCFG1_UMAP1BANK1PARINITDONE_BIT_END         29U

/* Definition for field UMAP1BANK2PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK2PARINITDONE_BIT_START       30U
#define L2MEMINITCFG1_UMAP1BANK2PARINITDONE_BIT_END         30U

/* Definition for field UMAP1BANK3PARINITDONE in Register L2MEMINITCFG1 */
#define L2MEMINITCFG1_UMAP1BANK3PARINITDONE_BIT_START       31U
#define L2MEMINITCFG1_UMAP1BANK3PARINITDONE_BIT_END         31U

/* Definition for field UMAP0BANK0PRAMINIT in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP0BANK0PRAMINIT_BIT_START          0U
#define L2MEMINITCFG2_UMAP0BANK0PRAMINIT_BIT_END            0U

/* Definition for field UMAP0BANK1PRAMINIT in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP0BANK1PRAMINIT_BIT_START          1U
#define L2MEMINITCFG2_UMAP0BANK1PRAMINIT_BIT_END            1U

/* Definition for field UMAP1BANK0PRAMINIT in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP1BANK0PRAMINIT_BIT_START          2U
#define L2MEMINITCFG2_UMAP1BANK0PRAMINIT_BIT_END            2U

/* Definition for field UMAP1BANK1PRAMINIT in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP1BANK1PRAMINIT_BIT_START          3U
#define L2MEMINITCFG2_UMAP1BANK1PRAMINIT_BIT_END            3U

/* Definition for field UMAP0BANK0PRAMINITDONE in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP0BANK0PRAMINITDONE_BIT_START      4U
#define L2MEMINITCFG2_UMAP0BANK0PRAMINITDONE_BIT_END        4U

/* Definition for field UMAP0BANK1PRAMINITDONE in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP0BANK1PRAMINITDONE_BIT_START      5U
#define L2MEMINITCFG2_UMAP0BANK1PRAMINITDONE_BIT_END        5U

/* Definition for field UMAP1BANK0PRAMINITDONE in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP1BANK0PRAMINITDONE_BIT_START      6U
#define L2MEMINITCFG2_UMAP1BANK0PRAMINITDONE_BIT_END        6U

/* Definition for field UMAP1BANK1PRAMINITDONE in Register L2MEMINITCFG2 */
#define L2MEMINITCFG2_UMAP1BANK1PRAMINITDONE_BIT_START      7U
#define L2MEMINITCFG2_UMAP1BANK1PRAMINITDONE_BIT_END        7U

/* Definition for field GEMLRSTCAUSE in Register GEMRSTCAUSE */
#define GEMRSTCAUSE_GEMLRSTCAUSE_BIT_START                  0U
#define GEMRSTCAUSE_GEMLRSTCAUSE_BIT_END                    7U

/* Definition for field GEMGRSTCAUSE in Register GEMRSTCAUSE */
#define GEMRSTCAUSE_GEMGRSTCAUSE_BIT_START                  8U
#define GEMRSTCAUSE_GEMGRSTCAUSE_BIT_END                    15U

/* Definition for field GEMPORCAUSE in Register GEMRSTCAUSE */
#define GEMRSTCAUSE_GEMPORCAUSE_BIT_START                   16U
#define GEMRSTCAUSE_GEMPORCAUSE_BIT_END                     23U

/* Definition for field GEMRSTCAUSECLR in Register GEMRSTCAUSE */
#define GEMRSTCAUSE_GEMRSTCAUSECLR_BIT_START                24U
#define GEMRSTCAUSE_GEMRSTCAUSECLR_BIT_END                  24U

/* Definition for field PWRSMMODESTATUS in Register GEMPWRSMCFG3 */
#define GEMPWRSMCFG3_PWRSMMODESTATUS_BIT_START              18U
#define GEMPWRSMCFG3_PWRSMMODESTATUS_BIT_END                19U

/* Definition for field PWRSMSLEEPTRIG in Register GEMPWRSMCFG4 */
#define GEMPWRSMCFG4_PWRSMSLEEPTRIG_BIT_START               16U
#define GEMPWRSMCFG4_PWRSMSLEEPTRIG_BIT_END                 16U

/* Definition for field PWRSMLRSTHALT in Register GEMPWRSMCFG4 */
#define GEMPWRSMCFG4_PWRSMLRSTHALT_BIT_START                17U
#define GEMPWRSMCFG4_PWRSMLRSTHALT_BIT_END                  17U

/* Definition for field GEMEVENTMASK in Register GEMPWRSMCFG4 */
#define GEMPWRSMCFG4_GEMEVENTMASK_BIT_START                 18U
#define GEMPWRSMCFG4_GEMEVENTMASK_BIT_END                   18U

/* Definition for field PWRSMWAKEMASK0 in Register PWRSMWAKEMASK0 */
#define PWRSMWAKEMASK0_PWRSMWAKEMASK0_BIT_START             0U
#define PWRSMWAKEMASK0_PWRSMWAKEMASK0_BIT_END               31U

/* Definition for field PWRSMWAKEMASK1 in Register PWRSMWAKEMASK1 */
#define PWRSMWAKEMASK1_PWRSMWAKEMASK1_BIT_START             0U
#define PWRSMWAKEMASK1_PWRSMWAKEMASK1_BIT_END               31U

/* Definition for field PWRSMWAKEMASK2 in Register PWRSMWAKEMASK2 */
#define PWRSMWAKEMASK2_PWRSMWAKEMASK2_BIT_START             0U
#define PWRSMWAKEMASK2_PWRSMWAKEMASK2_BIT_END               31U

/* Definition for field PWRSMMISEVTMASK0 in Register PWRSMMISEVTMASK0 */
#define PWRSMMISEVTMASK0_PWRSMMISEVTMASK0_BIT_START         0U
#define PWRSMMISEVTMASK0_PWRSMMISEVTMASK0_BIT_END           31U

/* Definition for field PWRSMMISEVTMASK1 in Register PWRSMMISEVTMASK1 */
#define PWRSMMISEVTMASK1_PWRSMMISEVTMASK1_BIT_START         0U
#define PWRSMMISEVTMASK1_PWRSMMISEVTMASK1_BIT_END           31U

/* Definition for field PWRSMMISEVTMASK2 in Register PWRSMMISEVTMASK2 */
#define PWRSMMISEVTMASK2_PWRSMMISEVTMASK2_BIT_START         0U
#define PWRSMMISEVTMASK2_PWRSMMISEVTMASK2_BIT_END           31U

/* Definition for field PWRSMWAKESRCSTAT0 in Register PWRSMWAKESRCSTAT0 */
#define PWRSMWAKESRCSTAT0_PWRSMWAKESRCSTAT0_BIT_START       0U
#define PWRSMWAKESRCSTAT0_PWRSMWAKESRCSTAT0_BIT_END         31U

/* Definition for field PWRSMWAKESRCSTAT1 in Register PWRSMWAKESRCSTAT1 */
#define PWRSMWAKESRCSTAT1_PWRSMWAKESRCSTAT1_BIT_START       0U
#define PWRSMWAKESRCSTAT1_PWRSMWAKESRCSTAT1_BIT_END         31U

/* Definition for field PWRSMWAKESRCSTAT2 in Register PWRSMWAKESRCSTAT2 */
#define PWRSMWAKESRCSTAT2_PWRSMWAKESRCSTAT2_BIT_START       0U
#define PWRSMWAKESRCSTAT2_PWRSMWAKESRCSTAT2_BIT_END         31U

/* Definition for field PWRSMEVNTMONSTAT0 in Register PWRSMEVNTMONSTAT0 */
#define PWRSMEVNTMONSTAT0_PWRSMEVNTMONSTAT0_BIT_START       0U
#define PWRSMEVNTMONSTAT0_PWRSMEVNTMONSTAT0_BIT_END         31U

/* Definition for field PWRSMEVNTMONSTAT1 in Register PWRSMEVNTMONSTAT1 */
#define PWRSMEVNTMONSTAT1_PWRSMEVNTMONSTAT1_BIT_START       0U
#define PWRSMEVNTMONSTAT1_PWRSMEVNTMONSTAT1_BIT_END         31U

/* Definition for field PWRSMEVNTMONSTAT2 in Register PWRSMEVNTMONSTAT2 */
#define PWRSMEVNTMONSTAT2_PWRSMEVNTMONSTAT2_BIT_START       0U
#define PWRSMEVNTMONSTAT2_PWRSMEVNTMONSTAT2_BIT_END         31U

/* Definition for field PWRSMWAKESRCSTATCLR0 in Register PWRSMWAKESRCSTATCLR0 */
#define PWRSMWAKESRCSTATCLR0_PWRSMWAKESRCSTATCLR0_BIT_START 0U
#define PWRSMWAKESRCSTATCLR0_PWRSMWAKESRCSTATCLR0_BIT_END   31U

/* Definition for field PWRSMWAKESRCSTATCLR1 in Register PWRSMWAKESRCSTATCLR1 */
#define PWRSMWAKESRCSTATCLR1_PWRSMWAKESRCSTATCLR1_BIT_START 0U
#define PWRSMWAKESRCSTATCLR1_PWRSMWAKESRCSTATCLR1_BIT_END   31U

/* Definition for field PWRSMWAKESRCSTATCLR2 in Register PWRSMWAKESRCSTATCLR2 */
#define PWRSMWAKESRCSTATCLR2_PWRSMWAKESRCSTATCLR2_BIT_START 0U
#define PWRSMWAKESRCSTATCLR2_PWRSMWAKESRCSTATCLR2_BIT_END   31U

/* Definition for field ADCBUFREALONLYMODE in Register ADCBUFCFG1 */
#define ADCBUFCFG1_ADCBUFREALONLYMODE_BIT_START             2U
#define ADCBUFCFG1_ADCBUFREALONLYMODE_BIT_END               2U

/* Definition for field ADCBUFIQSWAP in Register ADCBUFCFG1 */
#define ADCBUFCFG1_ADCBUFIQSWAP_BIT_START                   5U
#define ADCBUFCFG1_ADCBUFIQSWAP_BIT_END                     5U

/* Definition for field RX0EN in Register ADCBUFCFG1 */
#define ADCBUFCFG1_RX0EN_BIT_START                          6U
#define ADCBUFCFG1_RX0EN_BIT_END                            6U

/* Definition for field RX1EN in Register ADCBUFCFG1 */
#define ADCBUFCFG1_RX1EN_BIT_START                          7U
#define ADCBUFCFG1_RX1EN_BIT_END                            7U

/* Definition for field RX2EN in Register ADCBUFCFG1 */
#define ADCBUFCFG1_RX2EN_BIT_START                          8U
#define ADCBUFCFG1_RX2EN_BIT_END                            8U

/* Definition for field RX3EN in Register ADCBUFCFG1 */
#define ADCBUFCFG1_RX3EN_BIT_START                          9U
#define ADCBUFCFG1_RX3EN_BIT_END                            9U

/* Definition for field ADCBUFWRITEMODE in Register ADCBUFCFG1 */
#define ADCBUFCFG1_ADCBUFWRITEMODE_BIT_START                12U
#define ADCBUFCFG1_ADCBUFWRITEMODE_BIT_END                  12U

/* Definition for field ADCBUFCONTMODEEN in Register ADCBUFCFG1 */
#define ADCBUFCFG1_ADCBUFCONTMODEEN_BIT_START               13U
#define ADCBUFCFG1_ADCBUFCONTMODEEN_BIT_END                 13U

/* Definition for field ADCBUFCONTSTRTPL in Register ADCBUFCFG1 */
#define ADCBUFCFG1_ADCBUFCONTSTRTPL_BIT_START               14U
#define ADCBUFCFG1_ADCBUFCONTSTRTPL_BIT_END                 14U

/* Definition for field ADCBUFCONTSTOPPL in Register ADCBUFCFG1 */
#define ADCBUFCFG1_ADCBUFCONTSTOPPL_BIT_START               15U
#define ADCBUFCFG1_ADCBUFCONTSTOPPL_BIT_END                 15U

/* Definition for field ADCBUFADDRX0 in Register ADCBUFCFG2 */
#define ADCBUFCFG2_ADCBUFADDRX0_BIT_START                   0U
#define ADCBUFCFG2_ADCBUFADDRX0_BIT_END                     10U

/* Definition for field ADCBUFADDRX1 in Register ADCBUFCFG2 */
#define ADCBUFCFG2_ADCBUFADDRX1_BIT_START                   16U
#define ADCBUFCFG2_ADCBUFADDRX1_BIT_END                     26U

/* Definition for field ADCBUFADDRX2 in Register ADCBUFCFG3 */
#define ADCBUFCFG3_ADCBUFADDRX2_BIT_START                   0U
#define ADCBUFCFG3_ADCBUFADDRX2_BIT_END                     10U

/* Definition for field ADCBUFADDRX3 in Register ADCBUFCFG3 */
#define ADCBUFCFG3_ADCBUFADDRX3_BIT_START                   16U
#define ADCBUFCFG3_ADCBUFADDRX3_BIT_END                     26U

/* Definition for field ADCBUFSAMPCNT in Register ADCBUFCFG4 */
#define ADCBUFCFG4_ADCBUFSAMPCNT_BIT_START                  0U
#define ADCBUFCFG4_ADCBUFSAMPCNT_BIT_END                    15U

/* Definition for field ADCBUFNUMCHRPPING in Register ADCBUFCFG4 */
#define ADCBUFCFG4_ADCBUFNUMCHRPPING_BIT_START              16U
#define ADCBUFCFG4_ADCBUFNUMCHRPPING_BIT_END                20U

/* Definition for field ADCBUFNUMCHRPPONG in Register ADCBUFCFG4 */
#define ADCBUFCFG4_ADCBUFNUMCHRPPONG_BIT_START              21U
#define ADCBUFCFG4_ADCBUFNUMCHRPPONG_BIT_END                25U

/* Definition for field STCPBISTLRSTDASRTHALT in Register STCPBISTSMCFG1 */
#define STCPBISTSMCFG1_STCPBISTLRSTDASRTHALT_BIT_START      3U
#define STCPBISTSMCFG1_STCPBISTLRSTDASRTHALT_BIT_END        3U

/* Definition for field RTI2EVT0 in Register RTI2EVENTCAPTURESEL */
#define RTI2EVENTCAPTURESEL_RTI2EVT0_BIT_START              0U
#define RTI2EVENTCAPTURESEL_RTI2EVT0_BIT_END                6U

/* Definition for field RTI2EVT1 in Register RTI2EVENTCAPTURESEL */
#define RTI2EVENTCAPTURESEL_RTI2EVT1_BIT_START              16U
#define RTI2EVENTCAPTURESEL_RTI2EVT1_BIT_END                22U

/* Definition for field CQPIPOSELCNT in Register DSSMISC5 */
#define DSSMISC5_CQPIPOSELCNT_BIT_START                     0U
#define DSSMISC5_CQPIPOSELCNT_BIT_END                       0U

/* Definition for field CQPIPOSELVAL in Register DSSMISC5 */
#define DSSMISC5_CQPIPOSELVAL_BIT_START                     1U
#define DSSMISC5_CQPIPOSELVAL_BIT_END                       1U

/* Definition for field CPBPMPIPOSELCNT in Register DSSMISC5 */
#define DSSMISC5_CPBPMPIPOSELCNT_BIT_START                  2U
#define DSSMISC5_CPBPMPIPOSELCNT_BIT_END                    2U

/* Definition for field CPBPMPIPOSELVAL in Register DSSMISC5 */
#define DSSMISC5_CPBPMPIPOSELVAL_BIT_START                  3U
#define DSSMISC5_CPBPMPIPOSELVAL_BIT_END                    3U

/* Definition for field TPCC0PARMEMINIT in Register DSSMISC5 */
#define DSSMISC5_TPCC0PARMEMINIT_BIT_START                  4U
#define DSSMISC5_TPCC0PARMEMINIT_BIT_END                    4U

/* Definition for field TPCC1PARMEMINIT in Register DSSMISC5 */
#define DSSMISC5_TPCC1PARMEMINIT_BIT_START                  5U
#define DSSMISC5_TPCC1PARMEMINIT_BIT_END                    5U

/* Definition for field TPCC0PARMEMINITDONE in Register DSSMISC5 */
#define DSSMISC5_TPCC0PARMEMINITDONE_BIT_START              6U
#define DSSMISC5_TPCC0PARMEMINITDONE_BIT_END                6U

/* Definition for field TPCC1PARMEMINITDONE in Register DSSMISC5 */
#define DSSMISC5_TPCC1PARMEMINITDONE_BIT_START              7U
#define DSSMISC5_TPCC1PARMEMINITDONE_BIT_END                7U



/**
 * @struct DSSRegs_t
 * @brief
 *   Module DSS_REG Register Definition
 * @details
 *   This structure is used to access the DSS_REG module registers.
 */
/**
 * @typedef DSSRegs
 * @brief
 *   Module DSS_REG Register Frame type Definition
 * @details
 *   This type is used to access the DSS_REG module registers.
 */
typedef volatile struct DSSRegs_t
{
    uint32_t    DSSGPREG0                          ;        /* Offset = 0x000 */
    uint32_t    RESTRICTED1[19]                    ;        /* Offset = 0x004 */
    uint32_t    RTIEVENTCAPTURESEL                 ;        /* Offset = 0x050 */
    uint32_t    RESTRICTED2[6]                     ;        /* Offset = 0x054 */
    uint32_t    CQCFG1                             ;        /* Offset = 0x06C */
    uint32_t    RESTRICTED3[4]                     ;        /* Offset = 0x070 */
    uint32_t    TPCCPARSTATCFG                     ;        /* Offset = 0x080 */
    uint32_t    CSI2TXPARSTATCFG                   ;        /* Offset = 0x084 */
    uint32_t    RESTRICTED4[6]                     ;        /* Offset = 0x088 */
    uint32_t    CSICFG1                            ;        /* Offset = 0x0A0 */
    uint32_t    RESTRICTED5[24]                    ;        /* Offset = 0x0A4 */
    uint32_t    TPTC0WRMPUSTADD0                   ;        /* Offset = 0x104 */
    uint32_t    TPTC0WRMPUSTADD1                   ;        /* Offset = 0x108 */
    uint32_t    TPTC0WRMPUSTADD2                   ;        /* Offset = 0x10C */
    uint32_t    TPTC0WRMPUSTADD3                   ;        /* Offset = 0x110 */
    uint32_t    TPTC0WRMPUSTADD4                   ;        /* Offset = 0x114 */
    uint32_t    TPTC0WRMPUSTADD5                   ;        /* Offset = 0x118 */
    uint32_t    RESTRICTED6[2]                     ;        /* Offset = 0x11C */
    uint32_t    TPTC0WRMPUENDADD0                  ;        /* Offset = 0x124 */
    uint32_t    TPTC0WRMPUENDADD1                  ;        /* Offset = 0x128 */
    uint32_t    TPTC0WRMPUENDADD2                  ;        /* Offset = 0x12C */
    uint32_t    TPTC0WRMPUENDADD3                  ;        /* Offset = 0x130 */
    uint32_t    TPTC0WRMPUENDADD4                  ;        /* Offset = 0x134 */
    uint32_t    TPTC0WRMPUENDADD5                  ;        /* Offset = 0x138 */
    uint32_t    RESTRICTED7[2]                     ;        /* Offset = 0x13C */
    uint32_t    TPTC0WRMPUERRADD                   ;        /* Offset = 0x144 */
    uint32_t    TPTC0RDMPUSTADD0                   ;        /* Offset = 0x148 */
    uint32_t    TPTC0RDMPUSTADD1                   ;        /* Offset = 0x14C */
    uint32_t    TPTC0RDMPUSTADD2                   ;        /* Offset = 0x150 */
    uint32_t    TPTC0RDMPUSTADD3                   ;        /* Offset = 0x154 */
    uint32_t    TPTC0RDMPUSTADD4                   ;        /* Offset = 0x158 */
    uint32_t    TPTC0RDMPUSTADD5                   ;        /* Offset = 0x15C */
    uint32_t    RESTRICTED8[2]                     ;        /* Offset = 0x160 */
    uint32_t    TPTC0RDMPUENDADD0                  ;        /* Offset = 0x168 */
    uint32_t    TPTC0RDMPUENDADD1                  ;        /* Offset = 0x16C */
    uint32_t    TPTC0RDMPUENDADD2                  ;        /* Offset = 0x170 */
    uint32_t    TPTC0RDMPUENDADD3                  ;        /* Offset = 0x174 */
    uint32_t    TPTC0RDMPUENDADD4                  ;        /* Offset = 0x178 */
    uint32_t    TPTC0RDMPUENDADD5                  ;        /* Offset = 0x17C */
    uint32_t    RESTRICTED9[2]                     ;        /* Offset = 0x180 */
    uint32_t    TPTC0RDMPUERRADD                   ;        /* Offset = 0x188 */
    uint32_t    TPTC1WRMPUSTADD0                   ;        /* Offset = 0x18C */
    uint32_t    TPTC1WRMPUSTADD1                   ;        /* Offset = 0x190 */
    uint32_t    TPTC1WRMPUSTADD2                   ;        /* Offset = 0x194 */
    uint32_t    TPTC1WRMPUSTADD3                   ;        /* Offset = 0x198 */
    uint32_t    TPTC1WRMPUSTADD4                   ;        /* Offset = 0x19C */
    uint32_t    TPTC1WRMPUSTADD5                   ;        /* Offset = 0x1A0 */
    uint32_t    RESTRICTED10[2]                    ;        /* Offset = 0x1A4 */
    uint32_t    TPTC1WRMPUENDADD0                  ;        /* Offset = 0x1AC */
    uint32_t    TPTC1WRMPUENDADD1                  ;        /* Offset = 0x1B0 */
    uint32_t    TPTC1WRMPUENDADD2                  ;        /* Offset = 0x1B4 */
    uint32_t    TPTC1WRMPUENDADD3                  ;        /* Offset = 0x1B8 */
    uint32_t    TPTC1WRMPUENDADD4                  ;        /* Offset = 0x1BC */
    uint32_t    TPTC1WRMPUENDADD5                  ;        /* Offset = 0x1C0 */
    uint32_t    RESTRICTED11[2]                    ;        /* Offset = 0x1C4 */
    uint32_t    TPTC1WRMPUERRADD                   ;        /* Offset = 0x1CC */
    uint32_t    TPTC1RDMPUSTADD0                   ;        /* Offset = 0x1D0 */
    uint32_t    TPTC1RDMPUSTADD1                   ;        /* Offset = 0x1D4 */
    uint32_t    TPTC1RDMPUSTADD2                   ;        /* Offset = 0x1D8 */
    uint32_t    TPTC1RDMPUSTADD3                   ;        /* Offset = 0x1DC */
    uint32_t    TPTC1RDMPUSTADD4                   ;        /* Offset = 0x1E0 */
    uint32_t    TPTC1RDMPUSTADD5                   ;        /* Offset = 0x1E4 */
    uint32_t    RESTRICTED12[2]                    ;        /* Offset = 0x1E8 */
    uint32_t    TPTC1RDMPUENDADD0                  ;        /* Offset = 0x1F0 */
    uint32_t    TPTC1RDMPUENDADD1                  ;        /* Offset = 0x1F4 */
    uint32_t    TPTC1RDMPUENDADD2                  ;        /* Offset = 0x1F8 */
    uint32_t    TPTC1RDMPUENDADD3                  ;        /* Offset = 0x1FC */
    uint32_t    TPTC1RDMPUENDADD4                  ;        /* Offset = 0x200 */
    uint32_t    TPTC1RDMPUENDADD5                  ;        /* Offset = 0x204 */
    uint32_t    RESTRICTED13[2]                    ;        /* Offset = 0x208 */
    uint32_t    TPTC1RDMPUERRADD                   ;        /* Offset = 0x210 */
    uint32_t    TPTCMPUVALIDCFG                    ;        /* Offset = 0x214 */
    uint32_t    TPTCMPUENCFG                       ;        /* Offset = 0x218 */
    uint32_t    TESTPATTERNRX1ICFG                 ;        /* Offset = 0x21C */
    uint32_t    TESTPATTERNRX2ICFG                 ;        /* Offset = 0x220 */
    uint32_t    TESTPATTERNRX3ICFG                 ;        /* Offset = 0x224 */
    uint32_t    TESTPATTERNRX4ICFG                 ;        /* Offset = 0x228 */
    uint32_t    TESTPATTERNRX1QCFG                 ;        /* Offset = 0x22C */
    uint32_t    TESTPATTERNRX2QCFG                 ;        /* Offset = 0x230 */
    uint32_t    TESTPATTERNRX3QCFG                 ;        /* Offset = 0x234 */
    uint32_t    TESTPATTERNRX4QCFG                 ;        /* Offset = 0x238 */
    uint32_t    TESTPATTERNVLDCFG                  ;        /* Offset = 0x23C */
    uint32_t    DSSMISC                            ;        /* Offset = 0x240 */
    uint32_t    RESTRICTED14[5]                    ;        /* Offset = 0x244 */
    uint32_t    TPCC1PARSTATCFG                    ;        /* Offset = 0x258 */
    uint32_t    RESTRICTED15                       ;        /* Offset = 0x25C */
    uint32_t    DMMSWINT1                          ;        /* Offset = 0x260 */
    uint32_t    RESTRICTED16[3]                    ;        /* Offset = 0x264 */
    uint32_t    DSSINTRCFG                         ;        /* Offset = 0x270 */
    uint32_t    MPUMSTIDCFG1                       ;        /* Offset = 0x274 */
    uint32_t    MPUMSTIDCFG2                       ;        /* Offset = 0x278 */
    uint32_t    MPUMSTIDCFG3                       ;        /* Offset = 0x27C */
    uint32_t    HSRAM1ECCCFG                       ;        /* Offset = 0x280 */
    uint32_t    RESTRICTED17                       ;        /* Offset = 0x284 */
    uint32_t    DATATRRAMECCCFG                    ;        /* Offset = 0x288 */
    uint32_t    ADCBUFPINGECCCFG                   ;        /* Offset = 0x28C */
    uint32_t    ADCBUFPONGECCCFG                   ;        /* Offset = 0x290 */
    uint32_t    RESTRICTED18[2]                    ;        /* Offset = 0x294 */
    uint32_t    UMAP0PARITYCFG1                    ;        /* Offset = 0x29C */
    uint32_t    UMAP0PARITYCFG2                    ;        /* Offset = 0x2A0 */
    uint32_t    UMAP0PARITYCFG3                    ;        /* Offset = 0x2A4 */
    uint32_t    UMAP1PARITYCFG1                    ;        /* Offset = 0x2A8 */
    uint32_t    UMAP1PARITYCFG2                    ;        /* Offset = 0x2AC */
    uint32_t    UMAP1PARITYCFG3                    ;        /* Offset = 0x2B0 */
    uint32_t    ESMGRP2MASKCFG                     ;        /* Offset = 0x2B4 */
    uint32_t    L2MEMINITCFG1                      ;        /* Offset = 0x2B8 */
    uint32_t    L2MEMINITCFG2                      ;        /* Offset = 0x2BC */
    uint32_t    GEMRSTCAUSE                        ;        /* Offset = 0x2C0 */
    uint32_t    RESTRICTED19                       ;        /* Offset = 0x2C4 */
    uint32_t    GEMPWRSMCFG3                       ;        /* Offset = 0x2C8 */
    uint32_t    GEMPWRSMCFG4                       ;        /* Offset = 0x2CC */
    uint32_t    RESTRICTED20                       ;        /* Offset = 0x2D0 */
    uint32_t    PWRSMWAKEMASK0                     ;        /* Offset = 0x2D4 */
    uint32_t    PWRSMWAKEMASK1                     ;        /* Offset = 0x2D8 */
    uint32_t    PWRSMWAKEMASK2                     ;        /* Offset = 0x2DC */
    uint32_t    PWRSMMISEVTMASK0                   ;        /* Offset = 0x2E0 */
    uint32_t    PWRSMMISEVTMASK1                   ;        /* Offset = 0x2E4 */
    uint32_t    PWRSMMISEVTMASK2                   ;        /* Offset = 0x2E8 */
    uint32_t    PWRSMWAKESRCSTAT0                  ;        /* Offset = 0x2EC */
    uint32_t    PWRSMWAKESRCSTAT1                  ;        /* Offset = 0x2F0 */
    uint32_t    RESTRICTED21[11]                   ;        /* Offset = 0x2F4 */
    uint32_t    PWRSMWAKESRCSTAT2                  ;        /* Offset = 0x320 */
    uint32_t    PWRSMEVNTMONSTAT0                  ;        /* Offset = 0x324 */
    uint32_t    PWRSMEVNTMONSTAT1                  ;        /* Offset = 0x328 */
    uint32_t    PWRSMEVNTMONSTAT2                  ;        /* Offset = 0x32C */
    uint32_t    PWRSMWAKESRCSTATCLR0               ;        /* Offset = 0x330 */
    uint32_t    PWRSMWAKESRCSTATCLR1               ;        /* Offset = 0x334 */
    uint32_t    PWRSMWAKESRCSTATCLR2               ;        /* Offset = 0x338 */
    uint32_t    ADCBUFCFG1                         ;        /* Offset = 0x33C */
    uint32_t    ADCBUFCFG2                         ;        /* Offset = 0x340 */
    uint32_t    ADCBUFCFG3                         ;        /* Offset = 0x344 */
    uint32_t    ADCBUFCFG4                         ;        /* Offset = 0x348 */
    uint32_t    STCPBISTSMCFG1                     ;        /* Offset = 0x34C */
    uint32_t    RESTRICTED22[2]                    ;        /* Offset = 0x350 */
    uint32_t    RTI2EVENTCAPTURESEL                ;        /* Offset = 0x358 */
    uint32_t    DSSMISC5                           ;        /* Offset = 0x35C */
} DSSRegs;

#ifdef __cplusplus
}
#endif

#endif /* REG_DSS_H */
/* END OF REG_DSS_H */

