TI-radar: common/cfg.c File Reference
cfg.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <xdc/runtime/System.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/uart/UART.h>
#include <ti/control/mmwavelink/mmwavelink.h>
#include <ti/utils/cli/cli.h>
#include "mrr_config_consts.h"
Functions
void Cfg_AdvFrameCfgInitParams (rlAdvFrameCfg_t *ptrAdvFrameCfg)
void Cfg_FrameCfgInitParams (rlFrameCfg_t *ptrFrameCfg)
void Cfg_ProfileCfgInitParams (uint8_t profileNum, rlProfileCfg_t *ptrProfileCfg)
void Cfg_ChirpCfgInitParams (uint8_t chirpNum, rlChirpCfg_t *ptrChirpCfg)
void Cfg_LowPowerModeInitParams (rlLowPowerModeCfg_t *ptrLowPowerMode)
void Cfg_ChannelCfgInitParams (rlChanCfg_t *ptrChannelCfg)
void Cfg_ADCOutCfgInitParams (rlAdcOutCfg_t *ptrADCOutCfg)
Function Documentation
Cfg_ADCOutCfgInitParams()
void Cfg_ADCOutCfgInitParams (rlAdcOutCfg_t * ptrADCOutCfg)
Description
The function initializes the ADCOut configuration with the default parameters.
Parameters
[out] ptrADCOutCfg Pointer to the ADCOutput configuration
Return values
Not applicable
Definition at line 367 of file cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_AdvFrameCfgInitParams()
void Cfg_AdvFrameCfgInitParams (rlAdvFrameCfg_t * ptrAdvFrameCfg)
Description
The function initializes the frame configuration with the default parameters.
Parameters
[out] ptrAdvFrameCfg Pointer to the adavance frame configuration
Return values
Not applicable
Definition at line 45 of file cfg.c.
Cfg_ChannelCfgInitParams()
void Cfg_ChannelCfgInitParams (rlChanCfg_t * ptrChannelCfg)
Description
The function initializes the channel configuration with the default parameters.
Parameters
[out] ptrChannelCfg Pointer to the channel configuration
Return values
Not applicable
Definition at line 342 of file cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_ChirpCfgInitParams()
void Cfg_ChirpCfgInitParams (uint8_t chirpNum, rlChirpCfg_t * ptrChirpCfg)
Description
The function initializes the chirp configuration with the default parameters.
Parameters
[out] chirpNum Chirp Number to be configured
[out] ptrChirpCfg Pointer to the chirp configuration
Return values
Not applicable
Definition at line 231 of file cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_FrameCfgInitParams()
void Cfg_FrameCfgInitParams (rlFrameCfg_t * ptrFrameCfg)
Description
The function initializes the frame configuration with the default parameters.
Parameters
[out] ptrFrameCfg Pointer to the frame configuration
Return values
Not applicable
Definition at line 142 of file cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_LowPowerModeInitParams()
void Cfg_LowPowerModeInitParams (rlLowPowerModeCfg_t * ptrLowPowerMode)
Description
The function initializes the low power configuration with the default parameters.
Parameters
[out] ptrLowPowerMode Pointer to the low power mode configuration
Return values
Not applicable
Definition at line 320 of file cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_ProfileCfgInitParams()
void Cfg_ProfileCfgInitParams (uint8_t profileNum, rlProfileCfg_t * ptrProfileCfg)
Description
The function initializes the profile configuration with the default parameters.
Parameters
[in] profileNum Profile number to be initialized
[out] ptrProfileCfg Pointer to the profile configuration
Return values
Not applicable
Definition at line 173 of file cfg.c.
Referenced by MSS_CLIBasicCfg().