TI-radar AWR1843 ARM-Cortex R4F core: common/mmWave_XSS.h File Reference
mmWave_XSS.h File Reference
#include <ti/common/mmwave_error.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/uart/UART.h>
#include <ti/drivers/pinmux/pinmux.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/drivers/cbuff/cbuff.h>
#include <ti/drivers/adcbuf/ADCBuf.h>
#include <ti/drivers/edma/edma.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Event.h>
#include <common/app_cfg.h>
Data Structures
struct mmW_MSS_STATS_t
The structure is used to hold the statistics information for the Millimeter Wave Application.
struct MCB_t
DSP-Subsystem (DSS) Master control block (MCB) The structure is used to hold handling information, flags and stats relative to the radar design.
Macros
#define MSS
#define DSS_START_COMPLETED_EVT Event_Id_07
sensor start CLI event SYS/BIOS events are a means of communication between Tasks and threads SYS/BIOS objects include semaphores, mailboxes, message queues, etc. Only tasks can WAIT for events; whereas tasks, Hwis, Swis, or SYS/BIOS objects can POST them. -ref http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/sysbios/6_41_02_41/exports/bios_6_41_02_41/docs/cdoc/ti/sysbios/knl/Event.html
#define MMWDEMO_CLI_EVENTS
#define MMWDEMO_BSS_FAULT_EVENTS
Typedefs
typedef struct mmW_MSS_STATS_t mmW_MSS_STATS
The structure is used to hold the statistics information for the Millimeter Wave Application.
typedef struct MCB_t MCB
DSP-Subsystem (DSS) Master control block (MCB) The structure is used to hold handling information, flags and stats relative to the radar design.
Functions
void MSS_CLIInit (void)
This is the CLI Execution Task.
void Cfg_AdvFrameCfgInitParams (rlAdvFrameCfg_t *ptrAdvFrameCfg)
The function initializes the frame configuration with the default parameters.
void Cfg_FrameCfgInitParams (rlFrameCfg_t *ptrFrameCfg)
The function initializes the frame configuration with the default parameters.
void Cfg_ProfileCfgInitParams (uint8_t profileNum, rlProfileCfg_t *ptrProfileCfg)
The function initializes the profile configuration with the default parameters.
void Cfg_ChirpCfgInitParams (uint8_t chirpNum, rlChirpCfg_t *ptrChirpCfg)
The function initializes the chirp configuration with the default parameters.
void Cfg_LowPowerModeInitParams (rlLowPowerModeCfg_t *ptrLowPowerMode)
The function initializes the low power configuration with the default parameters.
void Cfg_ChannelCfgInitParams (rlChanCfg_t *ptrChannelCfg)
The function initializes the channel configuration with the default parameters.
void Cfg_ADCOutCfgInitParams (rlAdcOutCfg_t *ptrADCOutCfg)
The function initializes the ADCOut configuration with the default parameters.
Variables
MCB gMCB
gMCB structure contains the tracking information required by the design is aligned using DATA_ALIGN paragma to increase the performance of MSS core by aligning the structure gMCB (Master Control Block) to be divisable by 16.
Macro Definition Documentation
DSS_START_COMPLETED_EVT
#define DSS_START_COMPLETED_EVT Event_Id_07
sensor start CLI event SYS/BIOS events are a means of communication between Tasks and threads SYS/BIOS objects include semaphores, mailboxes, message queues, etc. Only tasks can WAIT for events; whereas tasks, Hwis, Swis, or SYS/BIOS objects can POST them. -ref http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/sysbios/6_41_02_41/exports/bios_6_41_02_41/docs/cdoc/ti/sysbios/knl/Event.html
Definition at line 80 of file mmWave_XSS.h.
MMWDEMO_BSS_FAULT_EVENTS
#define MMWDEMO_BSS_FAULT_EVENTS
Value:
(MMWDEMO_BSS_CPUFAULT_EVT | \
                                                         MMWDEMO_BSS_ESMFAULT_EVT )
Definition at line 90 of file mmWave_XSS.h.
MMWDEMO_CLI_EVENTS
#define MMWDEMO_CLI_EVENTS
Value:
(MMWDEMO_CLI_SENSORSTART_EVT    | \
                                                         MMWDEMO_CLI_SENSORSTOP_EVT     | \
                                                         MMWDEMO_CLI_FRAMESTART_EVT)
Definition at line 84 of file mmWave_XSS.h.
MSS
#define MSS
Definition at line 13 of file mmWave_XSS.h.
Typedef Documentation
MCB
typedef struct MCB_t MCB
DSP-Subsystem (DSS) Master control block (MCB) The structure is used to hold handling information, flags and stats relative to the radar design.
mmW_MSS_STATS
typedef struct mmW_MSS_STATS_t mmW_MSS_STATS
The structure is used to hold the statistics information for the Millimeter Wave Application.
Design
Function Documentation
Cfg_ADCOutCfgInitParams()
void Cfg_ADCOutCfgInitParams (rlAdcOutCfg_t * ptrADCOutCfg)
The function initializes the ADCOut configuration with the default parameters.
Parameters
[out] ptrADCOutCfg Pointer to the ADCOutput configuration
Return values
N/A
Definition at line 309 of file frame_cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_AdvFrameCfgInitParams()
void Cfg_AdvFrameCfgInitParams (rlAdvFrameCfg_t * ptrAdvFrameCfg)
The function initializes the frame configuration with the default parameters.
Parameters
[out] ptrAdvFrameCfg Pointer to the adavance frame configuration
Return values
N/A
Definition at line 43 of file frame_cfg.c.
Cfg_ChannelCfgInitParams()
void Cfg_ChannelCfgInitParams (rlChanCfg_t * ptrChannelCfg)
The function initializes the channel configuration with the default parameters.
Parameters
[out] ptrChannelCfg Pointer to the channel configuration
Return values
N/A
Definition at line 286 of file frame_cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_ChirpCfgInitParams()
void Cfg_ChirpCfgInitParams (uint8_t chirpNum, rlChirpCfg_t * ptrChirpCfg)
The function initializes the chirp configuration with the default parameters.
Parameters
[out] chirpNum Chirp Number to be configured
[out] ptrChirpCfg Pointer to the chirp configuration
Return values
N/A
Definition at line 205 of file frame_cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_FrameCfgInitParams()
void Cfg_FrameCfgInitParams (rlFrameCfg_t * ptrFrameCfg)
The function initializes the frame configuration with the default parameters.
Parameters
[out] ptrFrameCfg Pointer to the frame configuration
Return values
N/A
Definition at line 139 of file frame_cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_LowPowerModeInitParams()
void Cfg_LowPowerModeInitParams (rlLowPowerModeCfg_t * ptrLowPowerMode)
The function initializes the low power configuration with the default parameters.
Parameters
[out] ptrLowPowerMode Pointer to the low power mode configuration
Return values
N/A
Definition at line 265 of file frame_cfg.c.
Referenced by MSS_CLIBasicCfg().
Cfg_ProfileCfgInitParams()
void Cfg_ProfileCfgInitParams (uint8_t profileNum, rlProfileCfg_t * ptrProfileCfg)
The function initializes the profile configuration with the default parameters.
Parameters
[in] profileNum Profile number to be initialized
[out] ptrProfileCfg Pointer to the profile configuration
Return values
N/A
Definition at line 168 of file frame_cfg.c.
Referenced by MSS_CLIBasicCfg().
MSS_CLIInit()
void MSS_CLIInit (void)
This is the CLI Execution Task.
Return values
N/A
Definition at line 311 of file mss_cli.c.
Referenced by MSS_mmWaveInitTASK().
Variable Documentation
gMCB
MCB gMCB
gMCB structure contains the tracking information required by the design is aligned using DATA_ALIGN paragma to increase the performance of MSS core by aligning the structure gMCB (Master Control Block) to be divisable by 16.
TI-reference: spnu151j.pdf section #5.10.6
Definition at line 163 of file mss_main.c.
Referenced by main(), mboxCallbackFxn_MSS_ch0(), mboxIn_uartOut_TASK(), MSS_chirpIntCallback(), MSS_CLIBasicCfg(), MSS_CLISensorStart(), MSS_CLISensorStop(), MSS_frameStartIntCallback(), MSS_mboxWrite(), MSS_mmWaveCtrlTask(), MSS_mmWaveInitTASK(), MSS_mmWaveStartCallbackFxn(), and MSS_mmWaveStopCallbackFxn().