TI-radar: Debug/configPkg/package/cfg/mss_mrr_per4f.c File Reference
mss_mrr_per4f.c File Reference
#include <xdc/std.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/family/arm/IntrinsicsSupport.h>
#include <ti/sysbios/family/arm/TaskSupport.h>
#include <ti/sysbios/family/arm/exc/Exception.h>
#include <ti/sysbios/family/arm/v7r/tms570/Core.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/sysbios/gates/GateHwi.h>
#include <ti/sysbios/gates/GateMutex.h>
#include <ti/sysbios/hal/Cache.h>
#include <ti/sysbios/hal/CacheNull.h>
#include <ti/sysbios/hal/Core.h>
#include <ti/sysbios/hal/Hwi.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Idle.h>
#include <ti/sysbios/knl/Intrinsics.h>
#include <ti/sysbios/knl/Queue.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Swi.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/timers/rti/Timer.h>
#include <xdc/runtime/Assert.h>
#include <xdc/runtime/Core.h>
#include <xdc/runtime/Defaults.h>
#include <xdc/runtime/Diags.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Gate.h>
#include <xdc/runtime/Log.h>
#include <xdc/runtime/Main.h>
#include <xdc/runtime/Memory.h>
#include <xdc/runtime/Registry.h>
#include <xdc/runtime/Startup.h>
#include <xdc/runtime/SysStd.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Text.h>
#include <limits.h>
#include <xdc/runtime/Types.h>
#include <xdc/runtime/System__internal.h>
#include <_lock.h>
#include <string.h>
Data Structures
struct ti_sysbios_BIOS_RtsGateProxy_Module__
struct ti_sysbios_knl_Queue_Object__
struct ti_sysbios_knl_Queue_Object2__
struct ti_sysbios_knl_Semaphore_Object__
struct ti_sysbios_knl_Semaphore_Object2__
struct ti_sysbios_gates_GateMutex_Object__
struct ti_sysbios_gates_GateMutex_Object2__
struct ti_sysbios_BIOS_RtsGateProxy_Object2__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Module__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Object__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Object2__
struct ti_sysbios_gates_GateHwi_Module__
struct ti_sysbios_gates_GateHwi_Object__
struct ti_sysbios_gates_GateHwi_Object2__
struct ti_sysbios_gates_GateMutex_Module__
struct ti_sysbios_hal_Hwi_Module__
struct ti_sysbios_hal_Hwi_Object__
struct ti_sysbios_hal_Hwi_Object2__
struct ti_sysbios_hal_Hwi_HwiProxy_Module__
struct ti_sysbios_hal_Hwi_HwiProxy_Object2__
struct ti_sysbios_heaps_HeapBuf_Module__
struct ti_sysbios_heaps_HeapBuf_Object__
struct ti_sysbios_heaps_HeapBuf_Object2__
struct ti_sysbios_heaps_HeapMem_Module__
struct ti_sysbios_heaps_HeapMem_Object__
struct ti_sysbios_heaps_HeapMem_Object2__
struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Object2__
struct ti_sysbios_knl_Clock_Module__
struct ti_sysbios_knl_Clock_Object__
struct ti_sysbios_knl_Clock_Object2__
struct ti_sysbios_knl_Clock_TimerProxy_Module__
struct ti_sysbios_timers_rti_Timer_Object__
struct ti_sysbios_timers_rti_Timer_Object2__
struct ti_sysbios_knl_Clock_TimerProxy_Object2__
struct ti_sysbios_knl_Event_Module__
struct ti_sysbios_knl_Event_Object__
struct ti_sysbios_knl_Event_Object2__
struct ti_sysbios_knl_Queue_Module__
struct ti_sysbios_knl_Semaphore_Module__
struct ti_sysbios_knl_Swi_Module__
struct ti_sysbios_knl_Swi_Object__
struct ti_sysbios_knl_Swi_Object2__
struct ti_sysbios_knl_Task_Module__
struct ti_sysbios_knl_Task_Object__
struct ti_sysbios_knl_Task_Object2__
struct ti_sysbios_timers_rti_Timer_Module__
struct xdc_runtime_Main_Module_GateProxy_Module__
struct xdc_runtime_Main_Module_GateProxy_Object2__
struct xdc_runtime_Memory_HeapProxy_Module__
struct xdc_runtime_Memory_HeapProxy_Object2__
struct xdc_runtime_System_Module_GateProxy_Module__
struct xdc_runtime_System_Module_GateProxy_Object2__
struct ti_sysbios_BIOS_Module_State__
struct ti_sysbios_family_arm_exc_Exception_Module_State__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
struct ti_sysbios_heaps_HeapBuf_Module_State__
struct ti_sysbios_knl_Clock_Module_State__
struct ti_sysbios_knl_Swi_Module_State__
struct ti_sysbios_knl_Task_Module_State__
struct ti_sysbios_timers_rti_Timer_Module_State__
struct xdc_runtime_Error_Module_State__
struct xdc_runtime_Memory_Module_State__
struct xdc_runtime_Registry_Module_State__
struct xdc_runtime_Startup_Module_State__
struct xdc_runtime_System_Module_State__
struct xdc_runtime_Text_Module_State__
union Header
struct ti_sysbios_family_arm_v7r_vim_Hwi___S1
struct ti_sysbios_gates_GateHwi___S1
struct ti_sysbios_gates_GateMutex___S1
struct ti_sysbios_hal_Hwi___S1
struct ti_sysbios_heaps_HeapBuf___S1
struct ti_sysbios_heaps_HeapMem___S1
struct ti_sysbios_knl_Clock___S1
struct ti_sysbios_knl_Event___S1
struct ti_sysbios_knl_Queue___S1
struct ti_sysbios_knl_Semaphore___S1
struct ti_sysbios_knl_Swi___S1
struct ti_sysbios_knl_Task___S1
struct ti_sysbios_timers_rti_Timer___S1
Macros
#define __nested__
#define __config__
#define ATTRIBUTE __attribute__ ((used))
#define IMM_FLAG_REG 0xFFF7AC18
#define IMM_WORD1_REG 0xFFF7AC84
#define IMM_REG_RW32(X) (*(volatile UInt32*)(X))
#define Module__MID ti_sysbios_BIOS_RtsGateProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_BIOS_RtsGateProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_BIOS_RtsGateProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_BIOS_RtsGateProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_BIOS_RtsGateProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_BIOS_RtsGateProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_BIOS_RtsGateProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_BIOS_RtsGateProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C
#define Module__DGSINCL ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_query
#define Module__MID ti_sysbios_gates_GateHwi_Module__id__C
#define Module__DGSINCL ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_gates_GateHwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_gates_GateHwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_gates_GateHwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_gates_GateHwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_gates_GateHwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_gates_GateHwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_gates_GateHwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_gates_GateHwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_gates_GateHwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_gates_GateHwi_Module_GateProxy_query
#define Module__MID ti_sysbios_gates_GateMutex_Module__id__C
#define Module__DGSINCL ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_gates_GateMutex_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_gates_GateMutex_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_gates_GateMutex_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_gates_GateMutex_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_gates_GateMutex_Module__gatePrms__C
#define Module__GP_create ti_sysbios_gates_GateMutex_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_gates_GateMutex_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_gates_GateMutex_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_gates_GateMutex_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_gates_GateMutex_Module_GateProxy_query
#define Module__MID ti_sysbios_hal_Hwi_Module__id__C
#define Module__DGSINCL ti_sysbios_hal_Hwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_hal_Hwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_hal_Hwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_hal_Hwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_hal_Hwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_hal_Hwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_hal_Hwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_hal_Hwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_hal_Hwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_hal_Hwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_hal_Hwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_hal_Hwi_Module_GateProxy_query
#define Module__MID ti_sysbios_hal_Hwi_HwiProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_hal_Hwi_HwiProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_hal_Hwi_HwiProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_hal_Hwi_HwiProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_hal_Hwi_HwiProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_hal_Hwi_HwiProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_hal_Hwi_HwiProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_hal_Hwi_HwiProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapBuf_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapBuf_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapBuf_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapBuf_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapBuf_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapBuf_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapBuf_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapBuf_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapBuf_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapBuf_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapMem_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Clock_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Clock_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Clock_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Clock_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Clock_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Clock_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Clock_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Clock_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Clock_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Clock_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Clock_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Clock_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Clock_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Clock_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Clock_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Clock_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Clock_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Clock_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Clock_TimerProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Clock_TimerProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Clock_TimerProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Clock_TimerProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Clock_TimerProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Clock_TimerProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Clock_TimerProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Clock_TimerProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Event_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Event_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Event_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Event_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Event_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Event_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Event_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Event_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Event_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Event_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Event_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Event_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Event_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Event_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Event_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Event_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Event_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Event_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Queue_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Queue_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Queue_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Queue_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Queue_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Queue_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Queue_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Queue_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Queue_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Queue_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Queue_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Queue_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Queue_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Queue_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Queue_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Queue_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Queue_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Queue_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Semaphore_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Semaphore_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Semaphore_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Semaphore_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Semaphore_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Semaphore_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Semaphore_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Semaphore_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Semaphore_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Semaphore_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Semaphore_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Swi_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Swi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Swi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Swi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Swi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Swi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Swi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Swi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Swi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Swi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Swi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Swi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Swi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Swi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Swi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Swi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Swi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Swi_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Task_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Task_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Task_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Task_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Task_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Task_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Task_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Task_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Task_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Task_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Task_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Task_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Task_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Task_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Task_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Task_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Task_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Task_Module_GateProxy_query
#define Module__MID ti_sysbios_timers_rti_Timer_Module__id__C
#define Module__DGSINCL ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_timers_rti_Timer_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_timers_rti_Timer_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_timers_rti_Timer_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_timers_rti_Timer_Module__gatePrms__C
#define Module__GP_create ti_sysbios_timers_rti_Timer_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_timers_rti_Timer_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_timers_rti_Timer_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_timers_rti_Timer_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_timers_rti_Timer_Module_GateProxy_query
#define Module__MID xdc_runtime_Main_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_Main_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_Main_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_Main_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_Main_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_Main_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_Main_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_Main_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_Main_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_Main_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_Main_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_Main_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_Main_Module_GateProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_Memory_HeapProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_Memory_HeapProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_Memory_HeapProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_Memory_HeapProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_Memory_HeapProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_Memory_HeapProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_Memory_HeapProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_Memory_HeapProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_Memory_HeapProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_Memory_HeapProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_Memory_HeapProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_Memory_HeapProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_Memory_HeapProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_Memory_HeapProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_Memory_HeapProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_Memory_HeapProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_Memory_HeapProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_Memory_HeapProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_System_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_System_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_System_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_System_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_System_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_System_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_System_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_System_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_System_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_System_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_System_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_System_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_System_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_System_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_System_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_System_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_System_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_System_Module_GateProxy_Module_GateProxy_query
Typedefs
typedef struct ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__
typedef struct ti_sysbios_knl_Queue_Object__ ti_sysbios_knl_Queue_Object__
typedef struct ti_sysbios_knl_Semaphore_Object__ ti_sysbios_knl_Semaphore_Object__
typedef struct ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_BIOS_RtsGateProxy_Object__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__
typedef struct ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__
typedef struct ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__
typedef struct ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__
typedef struct ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__
typedef struct ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__
typedef struct ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__
typedef ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_hal_Hwi_HwiProxy_Object__
typedef struct ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__
typedef struct ti_sysbios_heaps_HeapBuf_Object__ ti_sysbios_heaps_HeapBuf_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__
typedef struct ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
typedef struct ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__
typedef struct ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__
typedef struct ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__
typedef struct ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__
typedef ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_knl_Clock_TimerProxy_Object__
typedef struct ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__
typedef struct ti_sysbios_knl_Event_Object__ ti_sysbios_knl_Event_Object__
typedef struct ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__
typedef struct ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__
typedef struct ti_sysbios_knl_Swi_Module__ ti_sysbios_knl_Swi_Module__
typedef struct ti_sysbios_knl_Swi_Object__ ti_sysbios_knl_Swi_Object__
typedef struct ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__
typedef struct ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__
typedef struct ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__
typedef struct xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_Main_Module_GateProxy_Object__
typedef struct xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__
typedef ti_sysbios_heaps_HeapMem_Object__ xdc_runtime_Memory_HeapProxy_Object__
typedef struct xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_System_Module_GateProxy_Object__
typedef struct ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module_State__
typedef struct ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module_State__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
typedef struct ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module_State__
typedef struct ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module_State__
typedef struct ti_sysbios_knl_Swi_Module_State__ ti_sysbios_knl_Swi_Module_State__
typedef struct ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module_State__
typedef struct ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module_State__
typedef struct xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module_State__
typedef struct xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module_State__
typedef struct xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module_State__
typedef struct xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module_State__
typedef struct xdc_runtime_System_Module_State__ xdc_runtime_System_Module_State__
typedef struct xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module_State__
typedef union Header Header
Functions
xdc_Void ti_sysbios_BIOS_startFunc (xdc_Void)
xdc_Void ti_sysbios_BIOS_exitFunc (xdc_Int)
xdc_UInt ti_sysbios_knl_Swi_disable__E (xdc_Void)
xdc_Void ti_sysbios_knl_Swi_restoreHwi__E (xdc_UInt)
xdc_UInt ti_sysbios_knl_Task_disable__E (xdc_Void)
xdc_Void ti_sysbios_knl_Task_restoreHwi__E (xdc_UInt)
xdc_Void ti_sysbios_knl_Clock_doTick__I (xdc_UArg)
xdc_Void ti_sysbios_hal_Hwi_checkStack (xdc_Void)
xdc_Void ti_sysbios_knl_Task_restore__E (xdc_UInt)
xdc_Void ti_sysbios_hal_Hwi_initStack (xdc_Void)
xdc_Int xdc_runtime_System_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Clock_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Swi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Task_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_heaps_HeapBuf_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_exc_Exception_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_hal_Hwi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_timers_rti_Timer_Module_startup__E (xdc_Int)
xdc_Int xdc_runtime_System_printfExtend__I (xdc_Char **, xdc_CString *, xdc_VaList *, xdc_runtime_System_ParseData *)
xdc__META (__ASM__, "@(#)__ASM__ = C:/Users/astro/workspace_v9_2/mrr_18xx_mss/Debug/configPkg/package/cfg/mss_mrr_per4f")
xdc__META (__ISA__, "@(#)__ISA__ = v7R")
xdc__META (__PLAT__, "@(#)__PLAT__ = ti.platforms.cortexR")
xdc__META (__TARG__, "@(#)__TARG__ = ti.targets.arm.elf.R4F")
xdc__META (__TRDR__, "@(#)__TRDR__ = ti.targets.omf.elf.Elf32")
xdc_Bool xdc_runtime_System_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Swi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__F (void)
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__F (void)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F (void)
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__F (void)
xdc_Void xdc_runtime_Startup_exec__I (void)
xdc_Void xdc_runtime_Startup_reset__I (void)
void xdc_runtime_Text_visitRope__I (xdc_runtime_Text_RopeId rope, xdc_Fxn visFxn, xdc_Ptr visState)
Void ti_sysbios_BIOS_atExitFunc__I (Int)
Void ti_sysbios_BIOS_registerRTSLock ()
Void ti_sysbios_timers_rti_Timer_startup__E ()
Void ti_sysbios_BIOS_startFunc__I ()
Void ti_sysbios_BIOS_rtsLock ()
Void ti_sysbios_BIOS_rtsUnlock ()
Void ti_sysbios_BIOS_nullFunc__I ()
Void ti_sysbios_BIOS_registerRTSLock (Void)
Void ti_sysbios_BIOS_removeRTSLock (Void)
Void ti_sysbios_BIOS_exitFunc (Int stat)
Void ti_sysbios_BIOS_errorRaiseHook (xdc_runtime_Error_Block *eb)
Void ti_sysbios_knl_Clock_doTick__I (UArg arg)
Void _c_int00 ()
Void ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I ()
Void ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I ()
Void ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I ()
static Void * ti_sysbios_rts_MemAlloc_alloc (SizeT size)
Void ATTRIBUTE * malloc (SizeT size)
Void ATTRIBUTE * memalign (SizeT alignment, SizeT size)
Void ATTRIBUTE * calloc (SizeT nmemb, SizeT size)
Void ATTRIBUTE free (Void *ptr)
Void ATTRIBUTE * realloc (Void *ptr, SizeT size)
Void ti_sysbios_family_arm_v7r_tms570_Core_resetC__I ()
xdc_Int xdc_runtime_System_printf_va__E (xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_printf__E (xdc_CString fmt,...)
xdc_Int xdc_runtime_System_aprintf_va__E (xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_aprintf__E (xdc_CString fmt,...)
xdc_Int xdc_runtime_System_sprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_sprintf__E (xdc_Char buf[], xdc_CString fmt,...)
xdc_Int xdc_runtime_System_asprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_asprintf__E (xdc_Char buf[], xdc_CString fmt,...)
xdc_Int xdc_runtime_System_snprintf_va__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_snprintf__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt,...)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S (void)
ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_RtsGateProxy_create (const ti_sysbios_BIOS_RtsGateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_BIOS_RtsGateProxy_delete (ti_sysbios_BIOS_RtsGateProxy_Handle *instp)
void ti_sysbios_BIOS_RtsGateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_BIOS_RtsGateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_query__E (xdc_Int qual)
xdc_IArg ti_sysbios_BIOS_RtsGateProxy_enter__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst)
xdc_Void ti_sysbios_BIOS_RtsGateProxy_leave__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst, xdc_IArg key)
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S (void)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_enable__E (xdc_Bits16 type)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_disable__E (xdc_Bits16 type)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_inv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wb__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbAll__E (void)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInvAll__E (void)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wait__E (void)
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S (void)
xdc_UInt ti_sysbios_hal_Core_CoreProxy_getId__E (void)
xdc_Void ti_sysbios_hal_Core_CoreProxy_interruptCore__E (xdc_UInt coreId)
xdc_IArg ti_sysbios_hal_Core_CoreProxy_lock__E (void)
xdc_Void ti_sysbios_hal_Core_CoreProxy_unlock__E (void)
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiDisable__E (void)
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiEnable__E (void)
xdc_Void ti_sysbios_hal_Core_CoreProxy_hwiRestore__E (xdc_UInt key)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S (void)
ti_sysbios_hal_Hwi_HwiProxy_Handle ti_sysbios_hal_Hwi_HwiProxy_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_HwiProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_HwiProxy_delete (ti_sysbios_hal_Hwi_HwiProxy_Handle *instp)
void ti_sysbios_hal_Hwi_HwiProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo *stkInfo, xdc_Bool computeStackDepth)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo *stkInfo, xdc_Bool computeStackDepth, xdc_UInt coreId)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_startup__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disable__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enable__E (void)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restore__E (xdc_UInt key)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E (void)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_post__E (xdc_UInt intNum)
xdc_Char * ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E (xdc_UInt intNum)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E (xdc_UInt intNum)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E (xdc_UInt intNum, xdc_UInt key)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E (xdc_UInt intNum)
ti_sysbios_interfaces_IHwi_FuncPtr ti_sysbios_hal_Hwi_HwiProxy_getFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_UArg *arg)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, ti_sysbios_interfaces_IHwi_FuncPtr fxn, xdc_UArg arg)
xdc_Ptr ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id, xdc_Ptr hookContext)
ti_sysbios_interfaces_IHwi_Irp ti_sysbios_hal_Hwi_HwiProxy_getIrp__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S (void)
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle ti_sysbios_heaps_HeapMem_Module_GateProxy_create (const ti_sysbios_heaps_HeapMem_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapMem_Module_GateProxy_delete (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle *instp)
void ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst)
xdc_Void ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S (void)
ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_TimerProxy_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_knl_Clock_TimerProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Clock_TimerProxy_delete (ti_sysbios_knl_Clock_TimerProxy_Handle *instp)
void ti_sysbios_knl_Clock_TimerProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_knl_Clock_TimerProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_UInt ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E (void)
ti_sysbios_interfaces_ITimer_Status ti_sysbios_knl_Clock_TimerProxy_getStatus__E (xdc_UInt id)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_startup__E (void)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setNextTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 ticks)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_start__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_stop__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 period)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 microsecs)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCount__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_getFreq__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_runtime_Types_FreqHz *freq)
ti_sysbios_interfaces_ITimer_FuncPtr ti_sysbios_knl_Clock_TimerProxy_getFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UArg *arg)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, ti_sysbios_interfaces_ITimer_FuncPtr fxn, xdc_UArg arg)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_trigger__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 cycles)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 tickPeriod)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_Bool save)
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S (void)
xdc_UInt ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E (xdc_UInt bits)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S (void)
xdc_Ptr ti_sysbios_knl_Task_SupportProxy_start__E (xdc_Ptr curTask, ti_sysbios_interfaces_ITaskSupport_FuncPtr enterFxn, ti_sysbios_interfaces_ITaskSupport_FuncPtr exitFxn, xdc_runtime_Error_Block *eb)
xdc_Void ti_sysbios_knl_Task_SupportProxy_swap__E (xdc_Ptr *oldtskContext, xdc_Ptr *newtskContext)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_checkStack__E (xdc_Char *stack, xdc_SizeT size)
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_stackUsed__E (xdc_Char *stack, xdc_SizeT size)
xdc_UInt ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E (void)
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E (void)
xdc_Bool xdc_runtime_Main_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_Main_Module_GateProxy_Handle xdc_runtime_Main_Module_GateProxy_create (const xdc_runtime_Main_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_Main_Module_GateProxy_delete (xdc_runtime_Main_Module_GateProxy_Handle *instp)
void xdc_runtime_Main_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_Main_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_Main_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_Main_Module_GateProxy_enter__E (xdc_runtime_Main_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_Main_Module_GateProxy_leave__E (xdc_runtime_Main_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_Memory_HeapProxy_Module__startupDone__S (void)
xdc_runtime_Memory_HeapProxy_Handle xdc_runtime_Memory_HeapProxy_create (const xdc_runtime_Memory_HeapProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_Memory_HeapProxy_delete (xdc_runtime_Memory_HeapProxy_Handle *instp)
void xdc_runtime_Memory_HeapProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_Memory_HeapProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Ptr xdc_runtime_Memory_HeapProxy_alloc__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_SizeT size, xdc_SizeT align, xdc_runtime_Error_Block *eb)
xdc_Void xdc_runtime_Memory_HeapProxy_free__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_Ptr block, xdc_SizeT size)
xdc_Bool xdc_runtime_Memory_HeapProxy_isBlocking__E (xdc_runtime_Memory_HeapProxy_Handle __inst)
xdc_Void xdc_runtime_Memory_HeapProxy_getStats__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_runtime_Memory_Stats *stats)
xdc_Bool xdc_runtime_System_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_System_Module_GateProxy_Handle xdc_runtime_System_Module_GateProxy_create (const xdc_runtime_System_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_System_Module_GateProxy_delete (xdc_runtime_System_Module_GateProxy_Handle *instp)
void xdc_runtime_System_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_System_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_System_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_System_Module_GateProxy_enter__E (xdc_runtime_System_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_System_Module_GateProxy_leave__E (xdc_runtime_System_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_System_SupportProxy_Module__startupDone__S (void)
xdc_Void xdc_runtime_System_SupportProxy_abort__E (xdc_CString str)
xdc_Void xdc_runtime_System_SupportProxy_exit__E (xdc_Int stat)
xdc_Void xdc_runtime_System_SupportProxy_flush__E (void)
xdc_Void xdc_runtime_System_SupportProxy_putch__E (xdc_Char ch)
xdc_Bool xdc_runtime_System_SupportProxy_ready__E (void)
xdc_runtime_IHeap_Handle xdc_runtime_IHeap_create (xdc_runtime_IHeap_Module mod, const xdc_runtime_IHeap_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IHeap_delete (xdc_runtime_IHeap_Handle *instp)
xdc_runtime_IGateProvider_Handle xdc_runtime_IGateProvider_create (xdc_runtime_IGateProvider_Module mod, const xdc_runtime_IGateProvider_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IGateProvider_delete (xdc_runtime_IGateProvider_Handle *instp)
xdc_Bool ti_sysbios_BIOS_Module__startupDone__S (void)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_TaskSupport_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__first__S (void)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_family_arm_v7r_vim_Hwi_Handle ti_sysbios_family_arm_v7r_vim_Hwi_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_family_arm_v7r_vim_Hwi_construct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct *__obj, xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_family_arm_v7r_vim_Hwi_destruct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct *obj)
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_family_arm_v7r_vim_Hwi_delete (ti_sysbios_family_arm_v7r_vim_Hwi_Handle *instp)
xdc_Bool ti_sysbios_gates_GateHwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_gates_GateHwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_gates_GateHwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__first__S (void)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_gates_GateHwi_Handle ti_sysbios_gates_GateHwi_create (const ti_sysbios_gates_GateHwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_gates_GateHwi_construct (ti_sysbios_gates_GateHwi_Struct *__obj, const ti_sysbios_gates_GateHwi_Params *__paramsPtr)
void ti_sysbios_gates_GateHwi_destruct (ti_sysbios_gates_GateHwi_Struct *obj)
xdc_Void ti_sysbios_gates_GateHwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_gates_GateHwi_delete (ti_sysbios_gates_GateHwi_Handle *instp)
xdc_Bool ti_sysbios_gates_GateMutex_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_gates_GateMutex_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_gates_GateMutex_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__first__S (void)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_gates_GateMutex_Handle ti_sysbios_gates_GateMutex_create (const ti_sysbios_gates_GateMutex_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_gates_GateMutex_construct (ti_sysbios_gates_GateMutex_Struct *__obj, const ti_sysbios_gates_GateMutex_Params *__paramsPtr)
void ti_sysbios_gates_GateMutex_destruct (ti_sysbios_gates_GateMutex_Struct *obj)
xdc_Void ti_sysbios_gates_GateMutex_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_gates_GateMutex_delete (ti_sysbios_gates_GateMutex_Handle *instp)
xdc_Bool ti_sysbios_hal_Cache_Module__startupDone__S (void)
xdc_Bool ti_sysbios_hal_CacheNull_Module__startupDone__S (void)
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_hal_Core_Module__startupDone__S (void)
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Core_CoreProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_hal_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_hal_Hwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_hal_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_hal_Hwi_Object__first__S (void)
xdc_Ptr ti_sysbios_hal_Hwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_hal_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_hal_Hwi_Handle ti_sysbios_hal_Hwi_create (xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_construct (ti_sysbios_hal_Hwi_Struct *__obj, xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_destruct (ti_sysbios_hal_Hwi_Struct *obj)
xdc_Void ti_sysbios_hal_Hwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_hal_Hwi_delete (ti_sysbios_hal_Hwi_Handle *instp)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapBuf_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_heaps_HeapBuf_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__first__S (void)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_heaps_HeapBuf_Handle ti_sysbios_heaps_HeapBuf_create (const ti_sysbios_heaps_HeapBuf_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapBuf_construct (ti_sysbios_heaps_HeapBuf_Struct *__obj, const ti_sysbios_heaps_HeapBuf_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapBuf_destruct (ti_sysbios_heaps_HeapBuf_Struct *obj)
xdc_Void ti_sysbios_heaps_HeapBuf_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_heaps_HeapBuf_delete (ti_sysbios_heaps_HeapBuf_Handle *instp)
xdc_Bool ti_sysbios_heaps_HeapMem_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapMem_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_heaps_HeapMem_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__first__S (void)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_heaps_HeapMem_Handle ti_sysbios_heaps_HeapMem_create (const ti_sysbios_heaps_HeapMem_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapMem_construct (ti_sysbios_heaps_HeapMem_Struct *__obj, const ti_sysbios_heaps_HeapMem_Params *__paramsPtr)
void ti_sysbios_heaps_HeapMem_destruct (ti_sysbios_heaps_HeapMem_Struct *obj)
xdc_Void ti_sysbios_heaps_HeapMem_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_heaps_HeapMem_delete (ti_sysbios_heaps_HeapMem_Handle *instp)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Clock_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Clock_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Clock_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Clock_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Clock_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Clock_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Clock_Handle ti_sysbios_knl_Clock_create (ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Clock_construct (ti_sysbios_knl_Clock_Struct *__obj, ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params *__paramsPtr)
void ti_sysbios_knl_Clock_destruct (ti_sysbios_knl_Clock_Struct *obj)
xdc_Void ti_sysbios_knl_Clock_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Clock_delete (ti_sysbios_knl_Clock_Handle *instp)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Event_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Event_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Event_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Event_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Event_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Event_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Event_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Event_Handle ti_sysbios_knl_Event_create (const ti_sysbios_knl_Event_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Event_construct (ti_sysbios_knl_Event_Struct *__obj, const ti_sysbios_knl_Event_Params *__paramsPtr)
void ti_sysbios_knl_Event_destruct (ti_sysbios_knl_Event_Struct *obj)
xdc_Void ti_sysbios_knl_Event_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Event_delete (ti_sysbios_knl_Event_Handle *instp)
xdc_Bool ti_sysbios_knl_Idle_Module__startupDone__S (void)
xdc_Bool ti_sysbios_knl_Intrinsics_Module__startupDone__S (void)
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Queue_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Queue_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Queue_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Queue_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Queue_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Queue_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Queue_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Queue_create (const ti_sysbios_knl_Queue_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Queue_construct (ti_sysbios_knl_Queue_Struct *__obj, const ti_sysbios_knl_Queue_Params *__paramsPtr)
void ti_sysbios_knl_Queue_destruct (ti_sysbios_knl_Queue_Struct *obj)
xdc_Void ti_sysbios_knl_Queue_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Queue_delete (ti_sysbios_knl_Queue_Handle *instp)
xdc_Bool ti_sysbios_knl_Semaphore_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Semaphore_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Semaphore_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Semaphore_Handle ti_sysbios_knl_Semaphore_create (xdc_Int count, const ti_sysbios_knl_Semaphore_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Semaphore_construct (ti_sysbios_knl_Semaphore_Struct *__obj, xdc_Int count, const ti_sysbios_knl_Semaphore_Params *__paramsPtr)
void ti_sysbios_knl_Semaphore_destruct (ti_sysbios_knl_Semaphore_Struct *obj)
xdc_Void ti_sysbios_knl_Semaphore_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Semaphore_delete (ti_sysbios_knl_Semaphore_Handle *instp)
xdc_Bool ti_sysbios_knl_Swi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Swi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Swi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Swi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Swi_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Swi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Swi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Swi_Handle ti_sysbios_knl_Swi_create (ti_sysbios_knl_Swi_FuncPtr swiFxn, const ti_sysbios_knl_Swi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Swi_construct (ti_sysbios_knl_Swi_Struct *__obj, ti_sysbios_knl_Swi_FuncPtr swiFxn, const ti_sysbios_knl_Swi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Swi_destruct (ti_sysbios_knl_Swi_Struct *obj)
xdc_Void ti_sysbios_knl_Swi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Swi_delete (ti_sysbios_knl_Swi_Handle *instp)
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Task_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Task_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Task_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Task_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Task_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Task_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Task_Handle ti_sysbios_knl_Task_create (ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Task_construct (ti_sysbios_knl_Task_Struct *__obj, ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Task_destruct (ti_sysbios_knl_Task_Struct *obj)
xdc_Void ti_sysbios_knl_Task_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Task_delete (ti_sysbios_knl_Task_Handle *instp)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_timers_rti_Timer_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_timers_rti_Timer_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__first__S (void)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_timers_rti_Timer_Handle ti_sysbios_timers_rti_Timer_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_timers_rti_Timer_construct (ti_sysbios_timers_rti_Timer_Struct *__obj, xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_timers_rti_Timer_destruct (ti_sysbios_timers_rti_Timer_Struct *obj)
xdc_Void ti_sysbios_timers_rti_Timer_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_timers_rti_Timer_delete (ti_sysbios_timers_rti_Timer_Handle *instp)
xdc_Bool xdc_runtime_Assert_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Core_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Defaults_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Diags_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Error_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Gate_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Log_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Main_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Memory_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Memory_HeapProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Memory_HeapProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Registry_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Startup_Module__startupDone__S (void)
xdc_Bool xdc_runtime_SysStd_Module__startupDone__S (void)
xdc_Bool xdc_runtime_System_Module__startupDone__S (void)
xdc_Bool xdc_runtime_System_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_System_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_System_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_System_SupportProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Text_Module__startupDone__S (void)
int __xdc__init (void)
Variables
ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V
ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__root__V
ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__root__V
ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__root__V
ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__root__V
ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__root__V
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__root__V
ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__root__V
ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__root__V
ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__root__V
ti_sysbios_knl_Swi_Module__ ti_sysbios_knl_Swi_Module__root__V
ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__root__V
ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__root__V
xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__root__V
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IHeap_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base ti_sysbios_interfaces_ICache_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ISystemSupport_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IGateProvider_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IModule_Interface__BASE__C = {0}
const ti_sysbios_gates_GateHwi_Fxns__ ti_sysbios_gates_GateHwi_Module__FXNS__C
const ti_sysbios_gates_GateMutex_Fxns__ ti_sysbios_gates_GateMutex_Module__FXNS__C
const ti_sysbios_hal_CacheNull_Fxns__ ti_sysbios_hal_CacheNull_Module__FXNS__C
const ti_sysbios_heaps_HeapBuf_Fxns__ ti_sysbios_heaps_HeapBuf_Module__FXNS__C
const ti_sysbios_heaps_HeapMem_Fxns__ ti_sysbios_heaps_HeapMem_Module__FXNS__C
const xdc_runtime_SysStd_Fxns__ xdc_runtime_SysStd_Module__FXNS__C
ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module__state__V
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excActive ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A [1]
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excContext ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A [1]
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStackBuffers ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A [1]
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A [4096]
__T2_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A [1]
ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module__state__V
const __T1_ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__A [1]
ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V [1]
void * __TI_STACK_BASE
void * __TI_STACK_SIZE
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A [2048]
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__dispatchTable ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A [128]
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__state__V
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A [128]
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A [4]
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A [4]
ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__table__V [1]
ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__table__V [2]
ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__table__V [1]
ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module__state__V
__T1_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A [32768]
ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__table__V [1]
ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module__state__V
const __T1_ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__A [1]
const __T1_ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__A [1]
ti_sysbios_knl_Swi_Object__ ti_sysbios_knl_Swi_Object__table__V [1]
__T1_ti_sysbios_knl_Swi_Module_State__readyQ ti_sysbios_knl_Swi_Module_State_0_readyQ__A [16]
ti_sysbios_knl_Swi_Module_State__ ti_sysbios_knl_Swi_Module__state__V
__T1_ti_sysbios_knl_Task_Instance_State__stack ti_sysbios_knl_Task_Instance_State_0_stack__A [2048]
ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__table__V [1]
__T1_ti_sysbios_knl_Task_Module_State__readyQ ti_sysbios_knl_Task_Module_State_0_readyQ__A [16]
__T1_ti_sysbios_knl_Task_Module_State__idleTask ti_sysbios_knl_Task_Module_State_0_idleTask__A [1]
ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module__state__V
ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__table__V [1]
__T1_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State_0_device__A [2]
__T1_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A [2]
__T1_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State_0_handles__A [2]
ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module__state__V
xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module__state__V
xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module__state__V
xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module__state__V
xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module__state__V
const __T1_xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__A [2]
const __T1_xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__A [10]
const __T1_xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__A [10]
__T1_xdc_runtime_System_Module_State__atexitHandlers xdc_runtime_System_Module_State_0_atexitHandlers__A [8]
xdc_runtime_System_Module_State__ xdc_runtime_System_Module__state__V
xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module__state__V
const __T1_xdc_runtime_Text_charTab xdc_runtime_Text_charTab__A [6894]
const __T1_xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__A [52]
const __FAR__ xdc_SizeT ti_sysbios_gates_GateMutex_Instance_State_sem__O = offsetof(ti_sysbios_gates_GateMutex_Object__,Object_field_sem)
const __FAR__ xdc_SizeT ti_sysbios_heaps_HeapBuf_Instance_State_freeList__O = offsetof(ti_sysbios_heaps_HeapBuf_Object__,Object_field_freeList)
const __FAR__ xdc_SizeT ti_sysbios_knl_Clock_Module_State_clockQ__O = offsetof(ti_sysbios_knl_Clock_Module_State__,Object_field_clockQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Event_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Event_Object__,Object_field_pendQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Semaphore_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Semaphore_Object__,Object_field_pendQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_inactiveQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_inactiveQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_terminatedQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_terminatedQ)
xdc_runtime_Error_Block xdc_runtime_Error_IgnoreBlock
const UInt32 ti_sysbios_family_arm_v7r_vim_Hwi_vectors []
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsEnabled ti_sysbios_BIOS_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsIncluded ti_sysbios_BIOS_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsMask ti_sysbios_BIOS_Module__diagsMask__C = ((CT__ti_sysbios_BIOS_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__gateObj ti_sysbios_BIOS_Module__gateObj__C = ((CT__ti_sysbios_BIOS_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__gatePrms ti_sysbios_BIOS_Module__gatePrms__C = ((CT__ti_sysbios_BIOS_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__id ti_sysbios_BIOS_Module__id__C = (xdc_Bits16)0x8015
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerDefined ti_sysbios_BIOS_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerObj ti_sysbios_BIOS_Module__loggerObj__C = ((CT__ti_sysbios_BIOS_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn0 ti_sysbios_BIOS_Module__loggerFxn0__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn1 ti_sysbios_BIOS_Module__loggerFxn1__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn2 ti_sysbios_BIOS_Module__loggerFxn2__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn4 ti_sysbios_BIOS_Module__loggerFxn4__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn8 ti_sysbios_BIOS_Module__loggerFxn8__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_BIOS_Object__count ti_sysbios_BIOS_Object__count__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Object__heap ti_sysbios_BIOS_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Object__sizeof ti_sysbios_BIOS_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Object__table ti_sysbios_BIOS_Object__table__C = 0
const __FAR__ CT__ti_sysbios_BIOS_smpEnabled ti_sysbios_BIOS_smpEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_mpeEnabled ti_sysbios_BIOS_mpeEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_cpuFreq ti_sysbios_BIOS_cpuFreq__C
const __FAR__ CT__ti_sysbios_BIOS_runtimeCreatesEnabled ti_sysbios_BIOS_runtimeCreatesEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_taskEnabled ti_sysbios_BIOS_taskEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_swiEnabled ti_sysbios_BIOS_swiEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_clockEnabled ti_sysbios_BIOS_clockEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_defaultKernelHeapInstance ti_sysbios_BIOS_defaultKernelHeapInstance__C = 0
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSize ti_sysbios_BIOS_kernelHeapSize__C = (xdc_SizeT)0x1000
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSection ti_sysbios_BIOS_kernelHeapSection__C = ".kernel_heap"
const __FAR__ CT__ti_sysbios_BIOS_heapSize ti_sysbios_BIOS_heapSize__C = (xdc_SizeT)0x1000
const __FAR__ CT__ti_sysbios_BIOS_heapSection ti_sysbios_BIOS_heapSection__C = 0
const __FAR__ CT__ti_sysbios_BIOS_heapTrackEnabled ti_sysbios_BIOS_heapTrackEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_setupSecureContext ti_sysbios_BIOS_setupSecureContext__C = 0
const __FAR__ CT__ti_sysbios_BIOS_useSK ti_sysbios_BIOS_useSK__C = 0
const __FAR__ CT__ti_sysbios_BIOS_installedErrorHook ti_sysbios_BIOS_installedErrorHook__C = ((CT__ti_sysbios_BIOS_installedErrorHook)((xdc_Fxn)xdc_runtime_Error_print__E))
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__id ti_sysbios_family_arm_IntrinsicsSupport_Module__id__C = (xdc_Bits16)0x8013
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__count ti_sysbios_family_arm_IntrinsicsSupport_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__heap ti_sysbios_family_arm_IntrinsicsSupport_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__table ti_sysbios_family_arm_IntrinsicsSupport_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask ti_sysbios_family_arm_TaskSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj ti_sysbios_family_arm_TaskSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms ti_sysbios_family_arm_TaskSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__id ti_sysbios_family_arm_TaskSupport_Module__id__C = (xdc_Bits16)0x8014
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerDefined ti_sysbios_family_arm_TaskSupport_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj ti_sysbios_family_arm_TaskSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__count ti_sysbios_family_arm_TaskSupport_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__heap ti_sysbios_family_arm_TaskSupport_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__sizeof ti_sysbios_family_arm_TaskSupport_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__table ti_sysbios_family_arm_TaskSupport_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_defaultStackSize ti_sysbios_family_arm_TaskSupport_defaultStackSize__C = (xdc_SizeT)0x800
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_stackAlignment ti_sysbios_family_arm_TaskSupport_stackAlignment__C = (xdc_UInt)0x8
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask ti_sysbios_family_arm_exc_Exception_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj ti_sysbios_family_arm_exc_Exception_Module__gateObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms ti_sysbios_family_arm_exc_Exception_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__id ti_sysbios_family_arm_exc_Exception_Module__id__C = (xdc_Bits16)0x8026
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerDefined ti_sysbios_family_arm_exc_Exception_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj ti_sysbios_family_arm_exc_Exception_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__count ti_sysbios_family_arm_exc_Exception_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__heap ti_sysbios_family_arm_exc_Exception_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__sizeof ti_sysbios_family_arm_exc_Exception_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__table ti_sysbios_family_arm_exc_Exception_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_swi ti_sysbios_family_arm_exc_Exception_E_swi__C = (((xdc_runtime_Error_Id)4814) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_prefetchAbort ti_sysbios_family_arm_exc_Exception_E_prefetchAbort__C = (((xdc_runtime_Error_Id)4847) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_dataAbort ti_sysbios_family_arm_exc_Exception_E_dataAbort__C = (((xdc_runtime_Error_Id)4890) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction__C = (((xdc_runtime_Error_Id)4929) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_enableDecode ti_sysbios_family_arm_exc_Exception_enableDecode__C = 1
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_excHookFunc ti_sysbios_family_arm_exc_Exception_excHookFunc__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFunc)0)
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs)ti_sysbios_family_arm_exc_Exception_excHookFuncs__A)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__id ti_sysbios_family_arm_v7r_tms570_Core_Module__id__C = (xdc_Bits16)0x8030
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__count ti_sysbios_family_arm_v7r_tms570_Core_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__heap ti_sysbios_family_arm_v7r_tms570_Core_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__table ti_sysbios_family_arm_v7r_tms570_Core_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_numCores ti_sysbios_family_arm_v7r_tms570_Core_numCores__C = (xdc_UInt)0x1
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds__C = (((xdc_runtime_Error_Id)5058) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_id ti_sysbios_family_arm_v7r_tms570_Core_id__C = (xdc_UInt)0x0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C
const __FAR__ ti_sysbios_family_arm_v7r_vim_Hwi_Params ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__id ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C = (xdc_Bits16)0x8024
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__count ti_sysbios_family_arm_v7r_vim_Hwi_Object__count__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof__C = sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object__)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__table ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__C = ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS__C = (xdc_UInt)0x80
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress)(0x0))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress)(0x0))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc)((xdc_Fxn)ti_sysbios_family_arm_v7r_vim_Hwi_phantomIntHandler__I))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack)0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM__C = 1
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId__C = (((xdc_runtime_Assert_Id)2825) << 16 | 16)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined__C = (((xdc_runtime_Error_Id)4570) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum__C = (((xdc_runtime_Error_Id)4618) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined__C = (((xdc_runtime_Error_Id)4658) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption__C = (((xdc_runtime_Error_Id)4697) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt__C = (((xdc_runtime_Error_Id)4760) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin__C = (((xdc_runtime_Log_Event)6429) << 16 | 768)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_LD_end ti_sysbios_family_arm_v7r_vim_Hwi_LD_end__C = (((xdc_runtime_Log_Event)6499) << 16 | 512)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap)ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A)
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable)((xdc_Fxn)ti_sysbios_knl_Swi_disable__E))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Swi_restoreHwi__E))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Task_restoreHwi__E))
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_hooks ti_sysbios_family_arm_v7r_vim_Hwi_hooks__C = {0, 0}
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateHwi_Object__DESC__C
const __FAR__ ti_sysbios_gates_GateHwi_Params ti_sysbios_gates_GateHwi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsEnabled ti_sysbios_gates_GateHwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsIncluded ti_sysbios_gates_GateHwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsMask ti_sysbios_gates_GateHwi_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateHwi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gateObj ti_sysbios_gates_GateHwi_Module__gateObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gatePrms ti_sysbios_gates_GateHwi_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateHwi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__id ti_sysbios_gates_GateHwi_Module__id__C = (xdc_Bits16)0x8028
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerDefined ti_sysbios_gates_GateHwi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerObj ti_sysbios_gates_GateHwi_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__count ti_sysbios_gates_GateHwi_Object__count__C = 1
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__heap ti_sysbios_gates_GateHwi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__sizeof ti_sysbios_gates_GateHwi_Object__sizeof__C = sizeof(ti_sysbios_gates_GateHwi_Object__)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__table ti_sysbios_gates_GateHwi_Object__table__C = ti_sysbios_gates_GateHwi_Object__table__V
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateMutex_Object__DESC__C
const __FAR__ ti_sysbios_gates_GateMutex_Params ti_sysbios_gates_GateMutex_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsEnabled ti_sysbios_gates_GateMutex_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsIncluded ti_sysbios_gates_GateMutex_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsMask ti_sysbios_gates_GateMutex_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateMutex_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gateObj ti_sysbios_gates_GateMutex_Module__gateObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gatePrms ti_sysbios_gates_GateMutex_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateMutex_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__id ti_sysbios_gates_GateMutex_Module__id__C = (xdc_Bits16)0x8029
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerDefined ti_sysbios_gates_GateMutex_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerObj ti_sysbios_gates_GateMutex_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__count ti_sysbios_gates_GateMutex_Object__count__C = 2
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__heap ti_sysbios_gates_GateMutex_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__sizeof ti_sysbios_gates_GateMutex_Object__sizeof__C = sizeof(ti_sysbios_gates_GateMutex_Object__)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__table ti_sysbios_gates_GateMutex_Object__table__C = ti_sysbios_gates_GateMutex_Object__table__V
const __FAR__ CT__ti_sysbios_gates_GateMutex_A_badContext ti_sysbios_gates_GateMutex_A_badContext__C = (((xdc_runtime_Assert_Id)3349) << 16 | 16)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__diagsEnabled ti_sysbios_hal_Cache_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Cache_Module__diagsIncluded ti_sysbios_hal_Cache_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Cache_Module__diagsMask ti_sysbios_hal_Cache_Module__diagsMask__C = ((CT__ti_sysbios_hal_Cache_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__gateObj ti_sysbios_hal_Cache_Module__gateObj__C = ((CT__ti_sysbios_hal_Cache_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__gatePrms ti_sysbios_hal_Cache_Module__gatePrms__C = ((CT__ti_sysbios_hal_Cache_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__id ti_sysbios_hal_Cache_Module__id__C = (xdc_Bits16)0x802b
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerDefined ti_sysbios_hal_Cache_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerObj ti_sysbios_hal_Cache_Module__loggerObj__C = ((CT__ti_sysbios_hal_Cache_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn0 ti_sysbios_hal_Cache_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn1 ti_sysbios_hal_Cache_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn2 ti_sysbios_hal_Cache_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn4 ti_sysbios_hal_Cache_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn8 ti_sysbios_hal_Cache_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_hal_Cache_Object__count ti_sysbios_hal_Cache_Object__count__C = 0
const __FAR__ CT__ti_sysbios_hal_Cache_Object__heap ti_sysbios_hal_Cache_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_hal_Cache_Object__sizeof ti_sysbios_hal_Cache_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_hal_Cache_Object__table ti_sysbios_hal_Cache_Object__table__C = 0
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__diagsEnabled ti_sysbios_hal_CacheNull_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__diagsIncluded ti_sysbios_hal_CacheNull_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__diagsMask ti_sysbios_hal_CacheNull_Module__diagsMask__C = ((CT__ti_sysbios_hal_CacheNull_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__gateObj ti_sysbios_hal_CacheNull_Module__gateObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__gatePrms ti_sysbios_hal_CacheNull_Module__gatePrms__C = ((CT__ti_sysbios_hal_CacheNull_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__id ti_sysbios_hal_CacheNull_Module__id__C = (xdc_Bits16)0x802c
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerDefined ti_sysbios_hal_CacheNull_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerObj ti_sysbios_hal_CacheNull_Module__loggerObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0 ti_sysbios_hal_CacheNull_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1 ti_sysbios_hal_CacheNull_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2 ti_sysbios_hal_CacheNull_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4 ti_sysbios_hal_CacheNull_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8 ti_sysbios_hal_CacheNull_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__count ti_sysbios_hal_CacheNull_Object__count__C = 0
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__heap ti_sysbios_hal_CacheNull_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__sizeof ti_sysbios_hal_CacheNull_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__table ti_sysbios_hal_CacheNull_Object__table__C = 0
const __FAR__ CT__ti_sysbios_hal_Core_Module__diagsEnabled ti_sysbios_hal_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Core_Module__diagsIncluded ti_sysbios_hal_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Core_Module__diagsMask ti_sysbios_hal_Core_Module__diagsMask__C = ((CT__ti_sysbios_hal_Core_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__gateObj ti_sysbios_hal_Core_Module__gateObj__C = ((CT__ti_sysbios_hal_Core_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__gatePrms ti_sysbios_hal_Core_Module__gatePrms__C = ((CT__ti_sysbios_hal_Core_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__id ti_sysbios_hal_Core_Module__id__C = (xdc_Bits16)0x802d
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerDefined ti_sysbios_hal_Core_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerObj ti_sysbios_hal_Core_Module__loggerObj__C = ((CT__ti_sysbios_hal_Core_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn0 ti_sysbios_hal_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn1 ti_sysbios_hal_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn2 ti_sysbios_hal_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn4 ti_sysbios_hal_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn8 ti_sysbios_hal_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_hal_Core_Object__count ti_sysbios_hal_Core_Object__count__C = 0
const __FAR__ CT__ti_sysbios_hal_Core_Object__heap ti_sysbios_hal_Core_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_hal_Core_Object__sizeof ti_sysbios_hal_Core_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_hal_Core_Object__table ti_sysbios_hal_Core_Object__table__C = 0
const __FAR__ CT__ti_sysbios_hal_Core_numCores ti_sysbios_hal_Core_numCores__C = (xdc_UInt)0x1
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_hal_Hwi_Object__DESC__C
const __FAR__ ti_sysbios_hal_Hwi_Params ti_sysbios_hal_Hwi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsEnabled ti_sysbios_hal_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsIncluded ti_sysbios_hal_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsMask ti_sysbios_hal_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_hal_Hwi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gateObj ti_sysbios_hal_Hwi_Module__gateObj__C = ((CT__ti_sysbios_hal_Hwi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gatePrms ti_sysbios_hal_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_hal_Hwi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__id ti_sysbios_hal_Hwi_Module__id__C = (xdc_Bits16)0x802e
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerDefined ti_sysbios_hal_Hwi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerObj ti_sysbios_hal_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__count ti_sysbios_hal_Hwi_Object__count__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__heap ti_sysbios_hal_Hwi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__sizeof ti_sysbios_hal_Hwi_Object__sizeof__C = sizeof(ti_sysbios_hal_Hwi_Object__)
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__table ti_sysbios_hal_Hwi_Object__table__C = ti_sysbios_hal_Hwi_Object__table__V
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherSwiSupport ti_sysbios_hal_Hwi_dispatcherSwiSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherTaskSupport ti_sysbios_hal_Hwi_dispatcherTaskSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_E_stackOverflow ti_sysbios_hal_Hwi_E_stackOverflow__C = (((xdc_runtime_Error_Id)5021) << 16 | 0)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapBuf_Object__DESC__C
const __FAR__ ti_sysbios_heaps_HeapBuf_Params ti_sysbios_heaps_HeapBuf_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__diagsEnabled ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__diagsIncluded ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask ti_sysbios_heaps_HeapBuf_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__gateObj ti_sysbios_heaps_HeapBuf_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms ti_sysbios_heaps_HeapBuf_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__id ti_sysbios_heaps_HeapBuf_Module__id__C = (xdc_Bits16)0x8020
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerDefined ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj ti_sysbios_heaps_HeapBuf_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__count ti_sysbios_heaps_HeapBuf_Object__count__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__heap ti_sysbios_heaps_HeapBuf_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__sizeof ti_sysbios_heaps_HeapBuf_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapBuf_Object__)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__table ti_sysbios_heaps_HeapBuf_Object__table__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_nullBuf ti_sysbios_heaps_HeapBuf_A_nullBuf__C = (((xdc_runtime_Assert_Id)1995) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_bufAlign ti_sysbios_heaps_HeapBuf_A_bufAlign__C = (((xdc_runtime_Assert_Id)2024) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidAlign ti_sysbios_heaps_HeapBuf_A_invalidAlign__C = (((xdc_runtime_Assert_Id)2049) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign__C = (((xdc_runtime_Assert_Id)2139) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidBlockSize ti_sysbios_heaps_HeapBuf_A_invalidBlockSize__C = (((xdc_runtime_Assert_Id)2228) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_zeroBlocks ti_sysbios_heaps_HeapBuf_A_zeroBlocks__C = (((xdc_runtime_Assert_Id)2288) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_zeroBufSize ti_sysbios_heaps_HeapBuf_A_zeroBufSize__C = (((xdc_runtime_Assert_Id)2313) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidBufSize ti_sysbios_heaps_HeapBuf_A_invalidBufSize__C = (((xdc_runtime_Assert_Id)2336) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_noBlocksToFree ti_sysbios_heaps_HeapBuf_A_noBlocksToFree__C = (((xdc_runtime_Assert_Id)2394) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidFree ti_sysbios_heaps_HeapBuf_A_invalidFree__C = (((xdc_runtime_Assert_Id)2454) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_E_size ti_sysbios_heaps_HeapBuf_E_size__C = (((xdc_runtime_Error_Id)4486) << 16 | 0)
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_trackMaxAllocs ti_sysbios_heaps_HeapBuf_trackMaxAllocs__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_numConstructedHeaps ti_sysbios_heaps_HeapBuf_numConstructedHeaps__C = (xdc_UInt)0x0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapMem_Object__DESC__C
const __FAR__ ti_sysbios_heaps_HeapMem_Params ti_sysbios_heaps_HeapMem_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsEnabled ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsIncluded ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsMask ti_sysbios_heaps_HeapMem_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapMem_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gateObj ti_sysbios_heaps_HeapMem_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[0]))
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gatePrms ti_sysbios_heaps_HeapMem_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__id ti_sysbios_heaps_HeapMem_Module__id__C = (xdc_Bits16)0x8021
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerDefined ti_sysbios_heaps_HeapMem_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerObj ti_sysbios_heaps_HeapMem_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__count ti_sysbios_heaps_HeapMem_Object__count__C = 1
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__heap ti_sysbios_heaps_HeapMem_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__sizeof ti_sysbios_heaps_HeapMem_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapMem_Object__)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__table ti_sysbios_heaps_HeapMem_Object__table__C = ti_sysbios_heaps_HeapMem_Object__table__V
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_zeroBlock ti_sysbios_heaps_HeapMem_A_zeroBlock__C = (((xdc_runtime_Assert_Id)2482) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_heapSize ti_sysbios_heaps_HeapMem_A_heapSize__C = (((xdc_runtime_Assert_Id)2518) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_align ti_sysbios_heaps_HeapMem_A_align__C = (((xdc_runtime_Assert_Id)2563) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_E_memory ti_sysbios_heaps_HeapMem_E_memory__C = (((xdc_runtime_Error_Id)4534) << 16 | 0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_invalidFree ti_sysbios_heaps_HeapMem_A_invalidFree__C = (((xdc_runtime_Assert_Id)2454) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_reqAlign ti_sysbios_heaps_HeapMem_reqAlign__C = (xdc_SizeT)0x8
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Clock_Object__DESC__C
const __FAR__ ti_sysbios_knl_Clock_Params ti_sysbios_knl_Clock_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsEnabled ti_sysbios_knl_Clock_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsIncluded ti_sysbios_knl_Clock_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsMask ti_sysbios_knl_Clock_Module__diagsMask__C = ((CT__ti_sysbios_knl_Clock_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gateObj ti_sysbios_knl_Clock_Module__gateObj__C = ((CT__ti_sysbios_knl_Clock_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gatePrms ti_sysbios_knl_Clock_Module__gatePrms__C = ((CT__ti_sysbios_knl_Clock_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__id ti_sysbios_knl_Clock_Module__id__C = (xdc_Bits16)0x8017
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerDefined ti_sysbios_knl_Clock_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerObj ti_sysbios_knl_Clock_Module__loggerObj__C = ((CT__ti_sysbios_knl_Clock_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn0 ti_sysbios_knl_Clock_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn1 ti_sysbios_knl_Clock_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn2 ti_sysbios_knl_Clock_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn4 ti_sysbios_knl_Clock_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn8 ti_sysbios_knl_Clock_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Object__count ti_sysbios_knl_Clock_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_Object__heap ti_sysbios_knl_Clock_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_Object__sizeof ti_sysbios_knl_Clock_Object__sizeof__C = sizeof(ti_sysbios_knl_Clock_Object__)
const __FAR__ CT__ti_sysbios_knl_Clock_Object__table ti_sysbios_knl_Clock_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_LW_delayed ti_sysbios_knl_Clock_LW_delayed__C = (((xdc_runtime_Log_Event)5484) << 16 | 1024)
const __FAR__ CT__ti_sysbios_knl_Clock_LM_tick ti_sysbios_knl_Clock_LM_tick__C = (((xdc_runtime_Log_Event)5506) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Clock_LM_begin ti_sysbios_knl_Clock_LM_begin__C = (((xdc_runtime_Log_Event)5524) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Clock_A_clockDisabled ti_sysbios_knl_Clock_A_clockDisabled__C = (((xdc_runtime_Assert_Id)615) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Clock_A_badThreadType ti_sysbios_knl_Clock_A_badThreadType__C = (((xdc_runtime_Assert_Id)696) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Clock_serviceMargin ti_sysbios_knl_Clock_serviceMargin__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_knl_Clock_tickSource ti_sysbios_knl_Clock_tickSource__C = ti_sysbios_knl_Clock_TickSource_TIMER
const __FAR__ CT__ti_sysbios_knl_Clock_tickMode ti_sysbios_knl_Clock_tickMode__C = ti_sysbios_knl_Clock_TickMode_PERIODIC
const __FAR__ CT__ti_sysbios_knl_Clock_timerId ti_sysbios_knl_Clock_timerId__C = (xdc_UInt)(-0x0 - 1)
const __FAR__ CT__ti_sysbios_knl_Clock_tickPeriod ti_sysbios_knl_Clock_tickPeriod__C = (xdc_UInt32)0x3e8
const __FAR__ CT__ti_sysbios_knl_Clock_doTickFunc ti_sysbios_knl_Clock_doTickFunc__C = ((CT__ti_sysbios_knl_Clock_doTickFunc)((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I))
const __FAR__ CT__ti_sysbios_knl_Clock_triggerClock ti_sysbios_knl_Clock_triggerClock__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Event_Object__DESC__C
const __FAR__ ti_sysbios_knl_Event_Params ti_sysbios_knl_Event_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsEnabled ti_sysbios_knl_Event_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsIncluded ti_sysbios_knl_Event_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsMask ti_sysbios_knl_Event_Module__diagsMask__C = ((CT__ti_sysbios_knl_Event_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__gateObj ti_sysbios_knl_Event_Module__gateObj__C = ((CT__ti_sysbios_knl_Event_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__gatePrms ti_sysbios_knl_Event_Module__gatePrms__C = ((CT__ti_sysbios_knl_Event_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__id ti_sysbios_knl_Event_Module__id__C = (xdc_Bits16)0x801a
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerDefined ti_sysbios_knl_Event_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerObj ti_sysbios_knl_Event_Module__loggerObj__C = ((CT__ti_sysbios_knl_Event_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn0 ti_sysbios_knl_Event_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn1 ti_sysbios_knl_Event_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn2 ti_sysbios_knl_Event_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn4 ti_sysbios_knl_Event_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn8 ti_sysbios_knl_Event_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Event_Object__count ti_sysbios_knl_Event_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_Object__heap ti_sysbios_knl_Event_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_Object__sizeof ti_sysbios_knl_Event_Object__sizeof__C = sizeof(ti_sysbios_knl_Event_Object__)
const __FAR__ CT__ti_sysbios_knl_Event_Object__table ti_sysbios_knl_Event_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_LM_post ti_sysbios_knl_Event_LM_post__C = (((xdc_runtime_Log_Event)5556) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Event_LM_pend ti_sysbios_knl_Event_LM_pend__C = (((xdc_runtime_Log_Event)5610) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventMasks ti_sysbios_knl_Event_A_nullEventMasks__C = (((xdc_runtime_Assert_Id)766) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventId ti_sysbios_knl_Event_A_nullEventId__C = (((xdc_runtime_Assert_Id)813) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_eventInUse ti_sysbios_knl_Event_A_eventInUse__C = (((xdc_runtime_Assert_Id)852) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_badContext ti_sysbios_knl_Event_A_badContext__C = (((xdc_runtime_Assert_Id)895) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_pendTaskDisabled ti_sysbios_knl_Event_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)958) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsEnabled ti_sysbios_knl_Idle_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsIncluded ti_sysbios_knl_Idle_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsMask ti_sysbios_knl_Idle_Module__diagsMask__C = ((CT__ti_sysbios_knl_Idle_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gateObj ti_sysbios_knl_Idle_Module__gateObj__C = ((CT__ti_sysbios_knl_Idle_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gatePrms ti_sysbios_knl_Idle_Module__gatePrms__C = ((CT__ti_sysbios_knl_Idle_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__id ti_sysbios_knl_Idle_Module__id__C = (xdc_Bits16)0x8018
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerDefined ti_sysbios_knl_Idle_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerObj ti_sysbios_knl_Idle_Module__loggerObj__C = ((CT__ti_sysbios_knl_Idle_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn0 ti_sysbios_knl_Idle_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn1 ti_sysbios_knl_Idle_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn2 ti_sysbios_knl_Idle_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn4 ti_sysbios_knl_Idle_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn8 ti_sysbios_knl_Idle_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Object__count ti_sysbios_knl_Idle_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Object__heap ti_sysbios_knl_Idle_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Object__sizeof ti_sysbios_knl_Idle_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Object__table ti_sysbios_knl_Idle_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__C = {1, ((__T1_ti_sysbios_knl_Idle_funcList *)ti_sysbios_knl_Idle_funcList__A)}
const __FAR__ CT__ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__C = {1, ((__T1_ti_sysbios_knl_Idle_coreList *)ti_sysbios_knl_Idle_coreList__A)}
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsEnabled ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsIncluded ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsMask ti_sysbios_knl_Intrinsics_Module__diagsMask__C = ((CT__ti_sysbios_knl_Intrinsics_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gateObj ti_sysbios_knl_Intrinsics_Module__gateObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gatePrms ti_sysbios_knl_Intrinsics_Module__gatePrms__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__id ti_sysbios_knl_Intrinsics_Module__id__C = (xdc_Bits16)0x8019
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerDefined ti_sysbios_knl_Intrinsics_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerObj ti_sysbios_knl_Intrinsics_Module__loggerObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0 ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1 ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2 ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4 ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8 ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__count ti_sysbios_knl_Intrinsics_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__heap ti_sysbios_knl_Intrinsics_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__sizeof ti_sysbios_knl_Intrinsics_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__table ti_sysbios_knl_Intrinsics_Object__table__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Queue_Object__DESC__C
const __FAR__ ti_sysbios_knl_Queue_Params ti_sysbios_knl_Queue_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsEnabled ti_sysbios_knl_Queue_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsIncluded ti_sysbios_knl_Queue_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsMask ti_sysbios_knl_Queue_Module__diagsMask__C = ((CT__ti_sysbios_knl_Queue_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gateObj ti_sysbios_knl_Queue_Module__gateObj__C = ((CT__ti_sysbios_knl_Queue_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gatePrms ti_sysbios_knl_Queue_Module__gatePrms__C = ((CT__ti_sysbios_knl_Queue_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__id ti_sysbios_knl_Queue_Module__id__C = (xdc_Bits16)0x801b
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerDefined ti_sysbios_knl_Queue_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerObj ti_sysbios_knl_Queue_Module__loggerObj__C = ((CT__ti_sysbios_knl_Queue_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn0 ti_sysbios_knl_Queue_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn1 ti_sysbios_knl_Queue_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn2 ti_sysbios_knl_Queue_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn4 ti_sysbios_knl_Queue_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn8 ti_sysbios_knl_Queue_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Object__count ti_sysbios_knl_Queue_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Queue_Object__heap ti_sysbios_knl_Queue_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Queue_Object__sizeof ti_sysbios_knl_Queue_Object__sizeof__C = sizeof(ti_sysbios_knl_Queue_Object__)
const __FAR__ CT__ti_sysbios_knl_Queue_Object__table ti_sysbios_knl_Queue_Object__table__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Semaphore_Object__DESC__C
const __FAR__ ti_sysbios_knl_Semaphore_Params ti_sysbios_knl_Semaphore_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsEnabled ti_sysbios_knl_Semaphore_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsIncluded ti_sysbios_knl_Semaphore_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsMask ti_sysbios_knl_Semaphore_Module__diagsMask__C = ((CT__ti_sysbios_knl_Semaphore_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gateObj ti_sysbios_knl_Semaphore_Module__gateObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gatePrms ti_sysbios_knl_Semaphore_Module__gatePrms__C = ((CT__ti_sysbios_knl_Semaphore_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__id ti_sysbios_knl_Semaphore_Module__id__C = (xdc_Bits16)0x801c
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerDefined ti_sysbios_knl_Semaphore_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerObj ti_sysbios_knl_Semaphore_Module__loggerObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__count ti_sysbios_knl_Semaphore_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__heap ti_sysbios_knl_Semaphore_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__sizeof ti_sysbios_knl_Semaphore_Object__sizeof__C = sizeof(ti_sysbios_knl_Semaphore_Object__)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__table ti_sysbios_knl_Semaphore_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_post ti_sysbios_knl_Semaphore_LM_post__C = (((xdc_runtime_Log_Event)5691) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_pend ti_sysbios_knl_Semaphore_LM_pend__C = (((xdc_runtime_Log_Event)5721) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_noEvents ti_sysbios_knl_Semaphore_A_noEvents__C = (((xdc_runtime_Assert_Id)1106) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_invTimeout ti_sysbios_knl_Semaphore_A_invTimeout__C = (((xdc_runtime_Assert_Id)1161) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_badContext ti_sysbios_knl_Semaphore_A_badContext__C = (((xdc_runtime_Assert_Id)895) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_overflow ti_sysbios_knl_Semaphore_A_overflow__C = (((xdc_runtime_Assert_Id)1226) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_pendTaskDisabled ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)1280) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)4068) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsEvents ti_sysbios_knl_Semaphore_supportsEvents__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsPriority ti_sysbios_knl_Semaphore_supportsPriority__C = 1
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventPost ti_sysbios_knl_Semaphore_eventPost__C = ((CT__ti_sysbios_knl_Semaphore_eventPost)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventSync ti_sysbios_knl_Semaphore_eventSync__C = ((CT__ti_sysbios_knl_Semaphore_eventSync)0)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Swi_Object__DESC__C
const __FAR__ ti_sysbios_knl_Swi_Params ti_sysbios_knl_Swi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__diagsEnabled ti_sysbios_knl_Swi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Swi_Module__diagsIncluded ti_sysbios_knl_Swi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Swi_Module__diagsMask ti_sysbios_knl_Swi_Module__diagsMask__C = ((CT__ti_sysbios_knl_Swi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__gateObj ti_sysbios_knl_Swi_Module__gateObj__C = ((CT__ti_sysbios_knl_Swi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__gatePrms ti_sysbios_knl_Swi_Module__gatePrms__C = ((CT__ti_sysbios_knl_Swi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__id ti_sysbios_knl_Swi_Module__id__C = (xdc_Bits16)0x801d
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerDefined ti_sysbios_knl_Swi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerObj ti_sysbios_knl_Swi_Module__loggerObj__C = ((CT__ti_sysbios_knl_Swi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn0 ti_sysbios_knl_Swi_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn1 ti_sysbios_knl_Swi_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn2 ti_sysbios_knl_Swi_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn4 ti_sysbios_knl_Swi_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn8 ti_sysbios_knl_Swi_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Swi_Object__count ti_sysbios_knl_Swi_Object__count__C = 1
const __FAR__ CT__ti_sysbios_knl_Swi_Object__heap ti_sysbios_knl_Swi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Swi_Object__sizeof ti_sysbios_knl_Swi_Object__sizeof__C = sizeof(ti_sysbios_knl_Swi_Object__)
const __FAR__ CT__ti_sysbios_knl_Swi_Object__table ti_sysbios_knl_Swi_Object__table__C = ti_sysbios_knl_Swi_Object__table__V
const __FAR__ CT__ti_sysbios_knl_Swi_LM_begin ti_sysbios_knl_Swi_LM_begin__C = (((xdc_runtime_Log_Event)5764) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Swi_LD_end ti_sysbios_knl_Swi_LD_end__C = (((xdc_runtime_Log_Event)5811) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Swi_LM_post ti_sysbios_knl_Swi_LM_post__C = (((xdc_runtime_Log_Event)5829) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Swi_A_swiDisabled ti_sysbios_knl_Swi_A_swiDisabled__C = (((xdc_runtime_Assert_Id)1374) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Swi_A_badPriority ti_sysbios_knl_Swi_A_badPriority__C = (((xdc_runtime_Assert_Id)1431) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Swi_numPriorities ti_sysbios_knl_Swi_numPriorities__C = (xdc_UInt)0x10
const __FAR__ CT__ti_sysbios_knl_Swi_hooks ti_sysbios_knl_Swi_hooks__C = {0, 0}
const __FAR__ CT__ti_sysbios_knl_Swi_taskDisable ti_sysbios_knl_Swi_taskDisable__C = ((CT__ti_sysbios_knl_Swi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
const __FAR__ CT__ti_sysbios_knl_Swi_taskRestore ti_sysbios_knl_Swi_taskRestore__C = ((CT__ti_sysbios_knl_Swi_taskRestore)((xdc_Fxn)ti_sysbios_knl_Task_restore__E))
const __FAR__ CT__ti_sysbios_knl_Swi_numConstructedSwis ti_sysbios_knl_Swi_numConstructedSwis__C = (xdc_UInt)0x0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Task_Object__DESC__C
const __FAR__ ti_sysbios_knl_Task_Params ti_sysbios_knl_Task_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsEnabled ti_sysbios_knl_Task_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsIncluded ti_sysbios_knl_Task_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsMask ti_sysbios_knl_Task_Module__diagsMask__C = ((CT__ti_sysbios_knl_Task_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__gateObj ti_sysbios_knl_Task_Module__gateObj__C = ((CT__ti_sysbios_knl_Task_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__gatePrms ti_sysbios_knl_Task_Module__gatePrms__C = ((CT__ti_sysbios_knl_Task_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__id ti_sysbios_knl_Task_Module__id__C = (xdc_Bits16)0x801e
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerDefined ti_sysbios_knl_Task_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerObj ti_sysbios_knl_Task_Module__loggerObj__C = ((CT__ti_sysbios_knl_Task_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn0 ti_sysbios_knl_Task_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn1 ti_sysbios_knl_Task_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn2 ti_sysbios_knl_Task_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn4 ti_sysbios_knl_Task_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn8 ti_sysbios_knl_Task_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Task_Object__count ti_sysbios_knl_Task_Object__count__C = 1
const __FAR__ CT__ti_sysbios_knl_Task_Object__heap ti_sysbios_knl_Task_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_Object__sizeof ti_sysbios_knl_Task_Object__sizeof__C = sizeof(ti_sysbios_knl_Task_Object__)
const __FAR__ CT__ti_sysbios_knl_Task_Object__table ti_sysbios_knl_Task_Object__table__C = ti_sysbios_knl_Task_Object__table__V
const __FAR__ CT__ti_sysbios_knl_Task_LM_switch ti_sysbios_knl_Task_LM_switch__C = (((xdc_runtime_Log_Event)5869) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LM_sleep ti_sysbios_knl_Task_LM_sleep__C = (((xdc_runtime_Log_Event)5937) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LD_ready ti_sysbios_knl_Task_LD_ready__C = (((xdc_runtime_Log_Event)5982) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Task_LD_block ti_sysbios_knl_Task_LD_block__C = (((xdc_runtime_Log_Event)6023) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Task_LM_yield ti_sysbios_knl_Task_LM_yield__C = (((xdc_runtime_Log_Event)6055) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LM_setPri ti_sysbios_knl_Task_LM_setPri__C = (((xdc_runtime_Log_Event)6103) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LD_exit ti_sysbios_knl_Task_LD_exit__C = (((xdc_runtime_Log_Event)6159) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Task_LM_setAffinity ti_sysbios_knl_Task_LM_setAffinity__C = (((xdc_runtime_Log_Event)6190) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LM_schedule ti_sysbios_knl_Task_LM_schedule__C = (((xdc_runtime_Log_Event)6273) << 16 | 1024)
const __FAR__ CT__ti_sysbios_knl_Task_LM_noWork ti_sysbios_knl_Task_LM_noWork__C = (((xdc_runtime_Log_Event)6359) << 16 | 1024)
const __FAR__ CT__ti_sysbios_knl_Task_E_stackOverflow ti_sysbios_knl_Task_E_stackOverflow__C = (((xdc_runtime_Error_Id)4147) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_spOutOfBounds ti_sysbios_knl_Task_E_spOutOfBounds__C = (((xdc_runtime_Error_Id)4190) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_deleteNotAllowed ti_sysbios_knl_Task_E_deleteNotAllowed__C = (((xdc_runtime_Error_Id)4241) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_moduleStateCheckFailed ti_sysbios_knl_Task_E_moduleStateCheckFailed__C = (((xdc_runtime_Error_Id)4272) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_objectCheckFailed ti_sysbios_knl_Task_E_objectCheckFailed__C = (((xdc_runtime_Error_Id)4345) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_objectNotInKernelSpace ti_sysbios_knl_Task_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)4412) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_A_badThreadType ti_sysbios_knl_Task_A_badThreadType__C = (((xdc_runtime_Assert_Id)1480) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badTaskState ti_sysbios_knl_Task_A_badTaskState__C = (((xdc_runtime_Assert_Id)1549) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_noPendElem ti_sysbios_knl_Task_A_noPendElem__C = (((xdc_runtime_Assert_Id)1603) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_taskDisabled ti_sysbios_knl_Task_A_taskDisabled__C = (((xdc_runtime_Assert_Id)1657) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badPriority ti_sysbios_knl_Task_A_badPriority__C = (((xdc_runtime_Assert_Id)1720) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badTimeout ti_sysbios_knl_Task_A_badTimeout__C = (((xdc_runtime_Assert_Id)1770) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badAffinity ti_sysbios_knl_Task_A_badAffinity__C = (((xdc_runtime_Assert_Id)1805) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_sleepTaskDisabled ti_sysbios_knl_Task_A_sleepTaskDisabled__C = (((xdc_runtime_Assert_Id)1838) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_invalidCoreId ti_sysbios_knl_Task_A_invalidCoreId__C = (((xdc_runtime_Assert_Id)1922) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_numPriorities ti_sysbios_knl_Task_numPriorities__C = (xdc_UInt)0x10
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackSize ti_sysbios_knl_Task_defaultStackSize__C = (xdc_SizeT)0x800
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackHeap ti_sysbios_knl_Task_defaultStackHeap__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_allBlockedFunc ti_sysbios_knl_Task_allBlockedFunc__C = ((CT__ti_sysbios_knl_Task_allBlockedFunc)0)
const __FAR__ CT__ti_sysbios_knl_Task_initStackFlag ti_sysbios_knl_Task_initStackFlag__C = 1
const __FAR__ CT__ti_sysbios_knl_Task_checkStackFlag ti_sysbios_knl_Task_checkStackFlag__C = 1
const __FAR__ CT__ti_sysbios_knl_Task_deleteTerminatedTasks ti_sysbios_knl_Task_deleteTerminatedTasks__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__C = {0, 0}
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFxn ti_sysbios_knl_Task_moduleStateCheckFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_moduleStateCheck__I))
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn ti_sysbios_knl_Task_moduleStateCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getModuleStateCheckValue__I))
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFlag ti_sysbios_knl_Task_moduleStateCheckFlag__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFxn ti_sysbios_knl_Task_objectCheckFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_objectCheck__I))
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckValueFxn ti_sysbios_knl_Task_objectCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getObjectCheckValue__I))
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFlag ti_sysbios_knl_Task_objectCheckFlag__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_numConstructedTasks ti_sysbios_knl_Task_numConstructedTasks__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_knl_Task_startupHookFunc ti_sysbios_knl_Task_startupHookFunc__C = ((CT__ti_sysbios_knl_Task_startupHookFunc)0)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_timers_rti_Timer_Object__DESC__C
const __FAR__ ti_sysbios_timers_rti_Timer_Params ti_sysbios_timers_rti_Timer_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsEnabled ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsIncluded ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsMask ti_sysbios_timers_rti_Timer_Module__diagsMask__C = ((CT__ti_sysbios_timers_rti_Timer_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gateObj ti_sysbios_timers_rti_Timer_Module__gateObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gatePrms ti_sysbios_timers_rti_Timer_Module__gatePrms__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__id ti_sysbios_timers_rti_Timer_Module__id__C = (xdc_Bits16)0x8033
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerDefined ti_sysbios_timers_rti_Timer_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerObj ti_sysbios_timers_rti_Timer_Module__loggerObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__count ti_sysbios_timers_rti_Timer_Object__count__C = 1
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__heap ti_sysbios_timers_rti_Timer_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__sizeof ti_sysbios_timers_rti_Timer_Object__sizeof__C = sizeof(ti_sysbios_timers_rti_Timer_Object__)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__table ti_sysbios_timers_rti_Timer_Object__table__C = ti_sysbios_timers_rti_Timer_Object__table__V
const __FAR__ CT__ti_sysbios_timers_rti_Timer_A_invalidTimer ti_sysbios_timers_rti_Timer_A_invalidTimer__C = (((xdc_runtime_Assert_Id)3548) << 16 | 16)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidTimer ti_sysbios_timers_rti_Timer_E_invalidTimer__C = (((xdc_runtime_Error_Id)5123) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_notAvailable ti_sysbios_timers_rti_Timer_E_notAvailable__C = (((xdc_runtime_Error_Id)5159) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidHwiMask ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C = (((xdc_runtime_Error_Id)5198) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_cannotSupport ti_sysbios_timers_rti_Timer_E_cannotSupport__C = (((xdc_runtime_Error_Id)5250) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_anyMask ti_sysbios_timers_rti_Timer_anyMask__C = (xdc_UInt)0x3
const __FAR__ CT__ti_sysbios_timers_rti_Timer_continueOnSuspend ti_sysbios_timers_rti_Timer_continueOnSuspend__C = 0
const __FAR__ CT__ti_sysbios_timers_rti_Timer_startupNeeded ti_sysbios_timers_rti_Timer_startupNeeded__C = (xdc_UInt)0x1
const __FAR__ CT__ti_sysbios_timers_rti_Timer_numTimerDevices ti_sysbios_timers_rti_Timer_numTimerDevices__C = (xdc_Int)0x2
const __FAR__ CT__xdc_runtime_Assert_Module__diagsEnabled xdc_runtime_Assert_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Assert_Module__diagsIncluded xdc_runtime_Assert_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Assert_Module__diagsMask xdc_runtime_Assert_Module__diagsMask__C = ((CT__xdc_runtime_Assert_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Assert_Module__gateObj xdc_runtime_Assert_Module__gateObj__C = ((CT__xdc_runtime_Assert_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Assert_Module__gatePrms xdc_runtime_Assert_Module__gatePrms__C = ((CT__xdc_runtime_Assert_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Assert_Module__id xdc_runtime_Assert_Module__id__C = (xdc_Bits16)0x8002
const __FAR__ CT__xdc_runtime_Assert_Module__loggerDefined xdc_runtime_Assert_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Assert_Module__loggerObj xdc_runtime_Assert_Module__loggerObj__C = ((CT__xdc_runtime_Assert_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn0 xdc_runtime_Assert_Module__loggerFxn0__C = ((CT__xdc_runtime_Assert_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn1 xdc_runtime_Assert_Module__loggerFxn1__C = ((CT__xdc_runtime_Assert_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn2 xdc_runtime_Assert_Module__loggerFxn2__C = ((CT__xdc_runtime_Assert_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn4 xdc_runtime_Assert_Module__loggerFxn4__C = ((CT__xdc_runtime_Assert_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn8 xdc_runtime_Assert_Module__loggerFxn8__C = ((CT__xdc_runtime_Assert_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Assert_Object__count xdc_runtime_Assert_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Assert_Object__heap xdc_runtime_Assert_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Assert_Object__sizeof xdc_runtime_Assert_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Assert_Object__table xdc_runtime_Assert_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Assert_E_assertFailed xdc_runtime_Assert_E_assertFailed__C = (((xdc_runtime_Error_Id)3828) << 16 | 0)
const __FAR__ CT__xdc_runtime_Core_Module__diagsEnabled xdc_runtime_Core_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Core_Module__diagsIncluded xdc_runtime_Core_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Core_Module__diagsMask xdc_runtime_Core_Module__diagsMask__C = ((CT__xdc_runtime_Core_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Core_Module__gateObj xdc_runtime_Core_Module__gateObj__C = ((CT__xdc_runtime_Core_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Core_Module__gatePrms xdc_runtime_Core_Module__gatePrms__C = ((CT__xdc_runtime_Core_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Core_Module__id xdc_runtime_Core_Module__id__C = (xdc_Bits16)0x8003
const __FAR__ CT__xdc_runtime_Core_Module__loggerDefined xdc_runtime_Core_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Core_Module__loggerObj xdc_runtime_Core_Module__loggerObj__C = ((CT__xdc_runtime_Core_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn0 xdc_runtime_Core_Module__loggerFxn0__C = ((CT__xdc_runtime_Core_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn1 xdc_runtime_Core_Module__loggerFxn1__C = ((CT__xdc_runtime_Core_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn2 xdc_runtime_Core_Module__loggerFxn2__C = ((CT__xdc_runtime_Core_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn4 xdc_runtime_Core_Module__loggerFxn4__C = ((CT__xdc_runtime_Core_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn8 xdc_runtime_Core_Module__loggerFxn8__C = ((CT__xdc_runtime_Core_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Core_Object__count xdc_runtime_Core_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Core_Object__heap xdc_runtime_Core_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Core_Object__sizeof xdc_runtime_Core_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Core_Object__table xdc_runtime_Core_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Core_A_initializedParams xdc_runtime_Core_A_initializedParams__C = (((xdc_runtime_Assert_Id)1) << 16 | 16)
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsEnabled xdc_runtime_Defaults_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsIncluded xdc_runtime_Defaults_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsMask xdc_runtime_Defaults_Module__diagsMask__C = ((CT__xdc_runtime_Defaults_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__gateObj xdc_runtime_Defaults_Module__gateObj__C = ((CT__xdc_runtime_Defaults_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__gatePrms xdc_runtime_Defaults_Module__gatePrms__C = ((CT__xdc_runtime_Defaults_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__id xdc_runtime_Defaults_Module__id__C = (xdc_Bits16)0x8004
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerDefined xdc_runtime_Defaults_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerObj xdc_runtime_Defaults_Module__loggerObj__C = ((CT__xdc_runtime_Defaults_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn0 xdc_runtime_Defaults_Module__loggerFxn0__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn1 xdc_runtime_Defaults_Module__loggerFxn1__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn2 xdc_runtime_Defaults_Module__loggerFxn2__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn4 xdc_runtime_Defaults_Module__loggerFxn4__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn8 xdc_runtime_Defaults_Module__loggerFxn8__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Defaults_Object__count xdc_runtime_Defaults_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Object__heap xdc_runtime_Defaults_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Object__sizeof xdc_runtime_Defaults_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Object__table xdc_runtime_Defaults_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Diags_Module__diagsEnabled xdc_runtime_Diags_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Diags_Module__diagsIncluded xdc_runtime_Diags_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Diags_Module__diagsMask xdc_runtime_Diags_Module__diagsMask__C = ((CT__xdc_runtime_Diags_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Diags_Module__gateObj xdc_runtime_Diags_Module__gateObj__C = ((CT__xdc_runtime_Diags_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Diags_Module__gatePrms xdc_runtime_Diags_Module__gatePrms__C = ((CT__xdc_runtime_Diags_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Diags_Module__id xdc_runtime_Diags_Module__id__C = (xdc_Bits16)0x8005
const __FAR__ CT__xdc_runtime_Diags_Module__loggerDefined xdc_runtime_Diags_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Diags_Module__loggerObj xdc_runtime_Diags_Module__loggerObj__C = ((CT__xdc_runtime_Diags_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn0 xdc_runtime_Diags_Module__loggerFxn0__C = ((CT__xdc_runtime_Diags_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn1 xdc_runtime_Diags_Module__loggerFxn1__C = ((CT__xdc_runtime_Diags_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn2 xdc_runtime_Diags_Module__loggerFxn2__C = ((CT__xdc_runtime_Diags_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn4 xdc_runtime_Diags_Module__loggerFxn4__C = ((CT__xdc_runtime_Diags_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn8 xdc_runtime_Diags_Module__loggerFxn8__C = ((CT__xdc_runtime_Diags_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Diags_Object__count xdc_runtime_Diags_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Diags_Object__heap xdc_runtime_Diags_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Diags_Object__sizeof xdc_runtime_Diags_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Diags_Object__table xdc_runtime_Diags_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Diags_setMaskEnabled xdc_runtime_Diags_setMaskEnabled__C = 0
const __FAR__ CT__xdc_runtime_Diags_dictBase xdc_runtime_Diags_dictBase__C = ((CT__xdc_runtime_Diags_dictBase)0)
const __FAR__ CT__xdc_runtime_Error_Module__diagsEnabled xdc_runtime_Error_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Error_Module__diagsIncluded xdc_runtime_Error_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Error_Module__diagsMask xdc_runtime_Error_Module__diagsMask__C = ((CT__xdc_runtime_Error_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Error_Module__gateObj xdc_runtime_Error_Module__gateObj__C = ((CT__xdc_runtime_Error_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Error_Module__gatePrms xdc_runtime_Error_Module__gatePrms__C = ((CT__xdc_runtime_Error_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Error_Module__id xdc_runtime_Error_Module__id__C = (xdc_Bits16)0x8006
const __FAR__ CT__xdc_runtime_Error_Module__loggerDefined xdc_runtime_Error_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Error_Module__loggerObj xdc_runtime_Error_Module__loggerObj__C = ((CT__xdc_runtime_Error_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn0 xdc_runtime_Error_Module__loggerFxn0__C = ((CT__xdc_runtime_Error_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn1 xdc_runtime_Error_Module__loggerFxn1__C = ((CT__xdc_runtime_Error_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn2 xdc_runtime_Error_Module__loggerFxn2__C = ((CT__xdc_runtime_Error_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn4 xdc_runtime_Error_Module__loggerFxn4__C = ((CT__xdc_runtime_Error_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn8 xdc_runtime_Error_Module__loggerFxn8__C = ((CT__xdc_runtime_Error_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Error_Object__count xdc_runtime_Error_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Error_Object__heap xdc_runtime_Error_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Error_Object__sizeof xdc_runtime_Error_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Error_Object__table xdc_runtime_Error_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Error_policyFxn xdc_runtime_Error_policyFxn__C = ((CT__xdc_runtime_Error_policyFxn)((xdc_Fxn)xdc_runtime_Error_policyDefault__E))
const __FAR__ CT__xdc_runtime_Error_E_generic xdc_runtime_Error_E_generic__C = (((xdc_runtime_Error_Id)3850) << 16 | 0)
const __FAR__ CT__xdc_runtime_Error_E_memory xdc_runtime_Error_E_memory__C = (((xdc_runtime_Error_Id)3854) << 16 | 0)
const __FAR__ CT__xdc_runtime_Error_E_msgCode xdc_runtime_Error_E_msgCode__C = (((xdc_runtime_Error_Id)3888) << 16 | 0)
const __FAR__ CT__xdc_runtime_Error_policy xdc_runtime_Error_policy__C = xdc_runtime_Error_UNWIND
const __FAR__ CT__xdc_runtime_Error_raiseHook xdc_runtime_Error_raiseHook__C = ((CT__xdc_runtime_Error_raiseHook)((xdc_Fxn)ti_sysbios_BIOS_errorRaiseHook__I))
const __FAR__ CT__xdc_runtime_Error_maxDepth xdc_runtime_Error_maxDepth__C = (xdc_UInt16)0x10
const __FAR__ CT__xdc_runtime_Gate_Module__diagsEnabled xdc_runtime_Gate_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Gate_Module__diagsIncluded xdc_runtime_Gate_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Gate_Module__diagsMask xdc_runtime_Gate_Module__diagsMask__C = ((CT__xdc_runtime_Gate_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Gate_Module__gateObj xdc_runtime_Gate_Module__gateObj__C = ((CT__xdc_runtime_Gate_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Gate_Module__gatePrms xdc_runtime_Gate_Module__gatePrms__C = ((CT__xdc_runtime_Gate_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Gate_Module__id xdc_runtime_Gate_Module__id__C = (xdc_Bits16)0x8007
const __FAR__ CT__xdc_runtime_Gate_Module__loggerDefined xdc_runtime_Gate_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Gate_Module__loggerObj xdc_runtime_Gate_Module__loggerObj__C = ((CT__xdc_runtime_Gate_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn0 xdc_runtime_Gate_Module__loggerFxn0__C = ((CT__xdc_runtime_Gate_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn1 xdc_runtime_Gate_Module__loggerFxn1__C = ((CT__xdc_runtime_Gate_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn2 xdc_runtime_Gate_Module__loggerFxn2__C = ((CT__xdc_runtime_Gate_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn4 xdc_runtime_Gate_Module__loggerFxn4__C = ((CT__xdc_runtime_Gate_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn8 xdc_runtime_Gate_Module__loggerFxn8__C = ((CT__xdc_runtime_Gate_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Gate_Object__count xdc_runtime_Gate_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Gate_Object__heap xdc_runtime_Gate_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Gate_Object__sizeof xdc_runtime_Gate_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Gate_Object__table xdc_runtime_Gate_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Log_Module__diagsEnabled xdc_runtime_Log_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Log_Module__diagsIncluded xdc_runtime_Log_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Log_Module__diagsMask xdc_runtime_Log_Module__diagsMask__C = ((CT__xdc_runtime_Log_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Log_Module__gateObj xdc_runtime_Log_Module__gateObj__C = ((CT__xdc_runtime_Log_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Log_Module__gatePrms xdc_runtime_Log_Module__gatePrms__C = ((CT__xdc_runtime_Log_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Log_Module__id xdc_runtime_Log_Module__id__C = (xdc_Bits16)0x8008
const __FAR__ CT__xdc_runtime_Log_Module__loggerDefined xdc_runtime_Log_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Log_Module__loggerObj xdc_runtime_Log_Module__loggerObj__C = ((CT__xdc_runtime_Log_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn0 xdc_runtime_Log_Module__loggerFxn0__C = ((CT__xdc_runtime_Log_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn1 xdc_runtime_Log_Module__loggerFxn1__C = ((CT__xdc_runtime_Log_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn2 xdc_runtime_Log_Module__loggerFxn2__C = ((CT__xdc_runtime_Log_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn4 xdc_runtime_Log_Module__loggerFxn4__C = ((CT__xdc_runtime_Log_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn8 xdc_runtime_Log_Module__loggerFxn8__C = ((CT__xdc_runtime_Log_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Log_Object__count xdc_runtime_Log_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Log_Object__heap xdc_runtime_Log_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Log_Object__sizeof xdc_runtime_Log_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Log_Object__table xdc_runtime_Log_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Log_L_construct xdc_runtime_Log_L_construct__C = (((xdc_runtime_Log_Event)5308) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_create xdc_runtime_Log_L_create__C = (((xdc_runtime_Log_Event)5332) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_destruct xdc_runtime_Log_L_destruct__C = (((xdc_runtime_Log_Event)5353) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_delete xdc_runtime_Log_L_delete__C = (((xdc_runtime_Log_Event)5372) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_error xdc_runtime_Log_L_error__C = (((xdc_runtime_Log_Event)5389) << 16 | 192)
const __FAR__ CT__xdc_runtime_Log_L_warning xdc_runtime_Log_L_warning__C = (((xdc_runtime_Log_Event)5403) << 16 | 224)
const __FAR__ CT__xdc_runtime_Log_L_info xdc_runtime_Log_L_info__C = (((xdc_runtime_Log_Event)5419) << 16 | 16384)
const __FAR__ CT__xdc_runtime_Log_L_start xdc_runtime_Log_L_start__C = (((xdc_runtime_Log_Event)5426) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Log_L_stop xdc_runtime_Log_L_stop__C = (((xdc_runtime_Log_Event)5437) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Log_L_startInstance xdc_runtime_Log_L_startInstance__C = (((xdc_runtime_Log_Event)5447) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Log_L_stopInstance xdc_runtime_Log_L_stopInstance__C = (((xdc_runtime_Log_Event)5466) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Main_Module__diagsEnabled xdc_runtime_Main_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Main_Module__diagsIncluded xdc_runtime_Main_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Main_Module__diagsMask xdc_runtime_Main_Module__diagsMask__C = ((CT__xdc_runtime_Main_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Main_Module__gateObj xdc_runtime_Main_Module__gateObj__C = ((CT__xdc_runtime_Main_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
const __FAR__ CT__xdc_runtime_Main_Module__gatePrms xdc_runtime_Main_Module__gatePrms__C = ((CT__xdc_runtime_Main_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Main_Module__id xdc_runtime_Main_Module__id__C = (xdc_Bits16)0x8009
const __FAR__ CT__xdc_runtime_Main_Module__loggerDefined xdc_runtime_Main_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Main_Module__loggerObj xdc_runtime_Main_Module__loggerObj__C = ((CT__xdc_runtime_Main_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn0 xdc_runtime_Main_Module__loggerFxn0__C = ((CT__xdc_runtime_Main_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn1 xdc_runtime_Main_Module__loggerFxn1__C = ((CT__xdc_runtime_Main_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn2 xdc_runtime_Main_Module__loggerFxn2__C = ((CT__xdc_runtime_Main_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn4 xdc_runtime_Main_Module__loggerFxn4__C = ((CT__xdc_runtime_Main_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn8 xdc_runtime_Main_Module__loggerFxn8__C = ((CT__xdc_runtime_Main_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Main_Object__count xdc_runtime_Main_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Main_Object__heap xdc_runtime_Main_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Main_Object__sizeof xdc_runtime_Main_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Main_Object__table xdc_runtime_Main_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Memory_Module__diagsEnabled xdc_runtime_Memory_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Memory_Module__diagsIncluded xdc_runtime_Memory_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Memory_Module__diagsMask xdc_runtime_Memory_Module__diagsMask__C = ((CT__xdc_runtime_Memory_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Memory_Module__gateObj xdc_runtime_Memory_Module__gateObj__C = ((CT__xdc_runtime_Memory_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Memory_Module__gatePrms xdc_runtime_Memory_Module__gatePrms__C = ((CT__xdc_runtime_Memory_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Memory_Module__id xdc_runtime_Memory_Module__id__C = (xdc_Bits16)0x800a
const __FAR__ CT__xdc_runtime_Memory_Module__loggerDefined xdc_runtime_Memory_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Memory_Module__loggerObj xdc_runtime_Memory_Module__loggerObj__C = ((CT__xdc_runtime_Memory_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn0 xdc_runtime_Memory_Module__loggerFxn0__C = ((CT__xdc_runtime_Memory_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn1 xdc_runtime_Memory_Module__loggerFxn1__C = ((CT__xdc_runtime_Memory_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn2 xdc_runtime_Memory_Module__loggerFxn2__C = ((CT__xdc_runtime_Memory_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn4 xdc_runtime_Memory_Module__loggerFxn4__C = ((CT__xdc_runtime_Memory_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn8 xdc_runtime_Memory_Module__loggerFxn8__C = ((CT__xdc_runtime_Memory_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Memory_Object__count xdc_runtime_Memory_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Memory_Object__heap xdc_runtime_Memory_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Memory_Object__sizeof xdc_runtime_Memory_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Memory_Object__table xdc_runtime_Memory_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Memory_defaultHeapInstance xdc_runtime_Memory_defaultHeapInstance__C = (xdc_runtime_IHeap_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0]
const __FAR__ CT__xdc_runtime_Registry_Module__diagsEnabled xdc_runtime_Registry_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Registry_Module__diagsIncluded xdc_runtime_Registry_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Registry_Module__diagsMask xdc_runtime_Registry_Module__diagsMask__C = ((CT__xdc_runtime_Registry_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Registry_Module__gateObj xdc_runtime_Registry_Module__gateObj__C = ((CT__xdc_runtime_Registry_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Registry_Module__gatePrms xdc_runtime_Registry_Module__gatePrms__C = ((CT__xdc_runtime_Registry_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Registry_Module__id xdc_runtime_Registry_Module__id__C = (xdc_Bits16)0x800b
const __FAR__ CT__xdc_runtime_Registry_Module__loggerDefined xdc_runtime_Registry_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Registry_Module__loggerObj xdc_runtime_Registry_Module__loggerObj__C = ((CT__xdc_runtime_Registry_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn0 xdc_runtime_Registry_Module__loggerFxn0__C = ((CT__xdc_runtime_Registry_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn1 xdc_runtime_Registry_Module__loggerFxn1__C = ((CT__xdc_runtime_Registry_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn2 xdc_runtime_Registry_Module__loggerFxn2__C = ((CT__xdc_runtime_Registry_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn4 xdc_runtime_Registry_Module__loggerFxn4__C = ((CT__xdc_runtime_Registry_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn8 xdc_runtime_Registry_Module__loggerFxn8__C = ((CT__xdc_runtime_Registry_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Registry_Object__count xdc_runtime_Registry_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Registry_Object__heap xdc_runtime_Registry_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Registry_Object__sizeof xdc_runtime_Registry_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Registry_Object__table xdc_runtime_Registry_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Startup_Module__diagsEnabled xdc_runtime_Startup_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Startup_Module__diagsIncluded xdc_runtime_Startup_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Startup_Module__diagsMask xdc_runtime_Startup_Module__diagsMask__C = ((CT__xdc_runtime_Startup_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Startup_Module__gateObj xdc_runtime_Startup_Module__gateObj__C = ((CT__xdc_runtime_Startup_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Startup_Module__gatePrms xdc_runtime_Startup_Module__gatePrms__C = ((CT__xdc_runtime_Startup_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Startup_Module__id xdc_runtime_Startup_Module__id__C = (xdc_Bits16)0x800c
const __FAR__ CT__xdc_runtime_Startup_Module__loggerDefined xdc_runtime_Startup_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Startup_Module__loggerObj xdc_runtime_Startup_Module__loggerObj__C = ((CT__xdc_runtime_Startup_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn0 xdc_runtime_Startup_Module__loggerFxn0__C = ((CT__xdc_runtime_Startup_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn1 xdc_runtime_Startup_Module__loggerFxn1__C = ((CT__xdc_runtime_Startup_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn2 xdc_runtime_Startup_Module__loggerFxn2__C = ((CT__xdc_runtime_Startup_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn4 xdc_runtime_Startup_Module__loggerFxn4__C = ((CT__xdc_runtime_Startup_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn8 xdc_runtime_Startup_Module__loggerFxn8__C = ((CT__xdc_runtime_Startup_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Startup_Object__count xdc_runtime_Startup_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Startup_Object__heap xdc_runtime_Startup_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Startup_Object__sizeof xdc_runtime_Startup_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Startup_Object__table xdc_runtime_Startup_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Startup_maxPasses xdc_runtime_Startup_maxPasses__C = (xdc_Int)0x20
const __FAR__ CT__xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__C = {2, ((__T1_xdc_runtime_Startup_firstFxns *)xdc_runtime_Startup_firstFxns__A)}
const __FAR__ CT__xdc_runtime_Startup_lastFxns xdc_runtime_Startup_lastFxns__C = {0, 0}
const __FAR__ CT__xdc_runtime_Startup_startModsFxn xdc_runtime_Startup_startModsFxn__C = ((CT__xdc_runtime_Startup_startModsFxn)((xdc_Fxn)xdc_runtime_Startup_startMods__I))
const __FAR__ CT__xdc_runtime_Startup_execImpl xdc_runtime_Startup_execImpl__C = ((CT__xdc_runtime_Startup_execImpl)((xdc_Fxn)xdc_runtime_Startup_exec__I))
const __FAR__ CT__xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__C = ((CT__xdc_runtime_Startup_sfxnTab)xdc_runtime_Startup_sfxnTab__A)
const __FAR__ CT__xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__C = ((CT__xdc_runtime_Startup_sfxnRts)xdc_runtime_Startup_sfxnRts__A)
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsEnabled xdc_runtime_SysStd_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsIncluded xdc_runtime_SysStd_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsMask xdc_runtime_SysStd_Module__diagsMask__C = ((CT__xdc_runtime_SysStd_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__gateObj xdc_runtime_SysStd_Module__gateObj__C = ((CT__xdc_runtime_SysStd_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__gatePrms xdc_runtime_SysStd_Module__gatePrms__C = ((CT__xdc_runtime_SysStd_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__id xdc_runtime_SysStd_Module__id__C = (xdc_Bits16)0x800e
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerDefined xdc_runtime_SysStd_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerObj xdc_runtime_SysStd_Module__loggerObj__C = ((CT__xdc_runtime_SysStd_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn0 xdc_runtime_SysStd_Module__loggerFxn0__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn1 xdc_runtime_SysStd_Module__loggerFxn1__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn2 xdc_runtime_SysStd_Module__loggerFxn2__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn4 xdc_runtime_SysStd_Module__loggerFxn4__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn8 xdc_runtime_SysStd_Module__loggerFxn8__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_SysStd_Object__count xdc_runtime_SysStd_Object__count__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Object__heap xdc_runtime_SysStd_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Object__sizeof xdc_runtime_SysStd_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Object__table xdc_runtime_SysStd_Object__table__C = 0
const __FAR__ CT__xdc_runtime_System_Module__diagsEnabled xdc_runtime_System_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_System_Module__diagsIncluded xdc_runtime_System_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_System_Module__diagsMask xdc_runtime_System_Module__diagsMask__C = ((CT__xdc_runtime_System_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_System_Module__gateObj xdc_runtime_System_Module__gateObj__C = ((CT__xdc_runtime_System_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
const __FAR__ CT__xdc_runtime_System_Module__gatePrms xdc_runtime_System_Module__gatePrms__C = ((CT__xdc_runtime_System_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_System_Module__id xdc_runtime_System_Module__id__C = (xdc_Bits16)0x800d
const __FAR__ CT__xdc_runtime_System_Module__loggerDefined xdc_runtime_System_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_System_Module__loggerObj xdc_runtime_System_Module__loggerObj__C = ((CT__xdc_runtime_System_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn0 xdc_runtime_System_Module__loggerFxn0__C = ((CT__xdc_runtime_System_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn1 xdc_runtime_System_Module__loggerFxn1__C = ((CT__xdc_runtime_System_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn2 xdc_runtime_System_Module__loggerFxn2__C = ((CT__xdc_runtime_System_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn4 xdc_runtime_System_Module__loggerFxn4__C = ((CT__xdc_runtime_System_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn8 xdc_runtime_System_Module__loggerFxn8__C = ((CT__xdc_runtime_System_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_System_Object__count xdc_runtime_System_Object__count__C = 0
const __FAR__ CT__xdc_runtime_System_Object__heap xdc_runtime_System_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_System_Object__sizeof xdc_runtime_System_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_System_Object__table xdc_runtime_System_Object__table__C = 0
const __FAR__ CT__xdc_runtime_System_A_cannotFitIntoArg xdc_runtime_System_A_cannotFitIntoArg__C = (((xdc_runtime_Assert_Id)352) << 16 | 16)
const __FAR__ CT__xdc_runtime_System_maxAtexitHandlers xdc_runtime_System_maxAtexitHandlers__C = (xdc_Int)0x8
const __FAR__ CT__xdc_runtime_System_abortFxn xdc_runtime_System_abortFxn__C = ((CT__xdc_runtime_System_abortFxn)((xdc_Fxn)xdc_runtime_System_abortStd__E))
const __FAR__ CT__xdc_runtime_System_exitFxn xdc_runtime_System_exitFxn__C = ((CT__xdc_runtime_System_exitFxn)((xdc_Fxn)xdc_runtime_System_exitStd__E))
const __FAR__ CT__xdc_runtime_System_extendFxn xdc_runtime_System_extendFxn__C = ((CT__xdc_runtime_System_extendFxn)((xdc_Fxn)xdc_runtime_System_printfExtend__I))
const __FAR__ CT__xdc_runtime_Text_Module__diagsEnabled xdc_runtime_Text_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Text_Module__diagsIncluded xdc_runtime_Text_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Text_Module__diagsMask xdc_runtime_Text_Module__diagsMask__C = ((CT__xdc_runtime_Text_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Text_Module__gateObj xdc_runtime_Text_Module__gateObj__C = ((CT__xdc_runtime_Text_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Text_Module__gatePrms xdc_runtime_Text_Module__gatePrms__C = ((CT__xdc_runtime_Text_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Text_Module__id xdc_runtime_Text_Module__id__C = (xdc_Bits16)0x800f
const __FAR__ CT__xdc_runtime_Text_Module__loggerDefined xdc_runtime_Text_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Text_Module__loggerObj xdc_runtime_Text_Module__loggerObj__C = ((CT__xdc_runtime_Text_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn0 xdc_runtime_Text_Module__loggerFxn0__C = ((CT__xdc_runtime_Text_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn1 xdc_runtime_Text_Module__loggerFxn1__C = ((CT__xdc_runtime_Text_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn2 xdc_runtime_Text_Module__loggerFxn2__C = ((CT__xdc_runtime_Text_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn4 xdc_runtime_Text_Module__loggerFxn4__C = ((CT__xdc_runtime_Text_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn8 xdc_runtime_Text_Module__loggerFxn8__C = ((CT__xdc_runtime_Text_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Text_Object__count xdc_runtime_Text_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Text_Object__heap xdc_runtime_Text_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Text_Object__sizeof xdc_runtime_Text_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Text_Object__table xdc_runtime_Text_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Text_nameUnknown xdc_runtime_Text_nameUnknown__C = "{unknown-instance-name}"
const __FAR__ CT__xdc_runtime_Text_nameEmpty xdc_runtime_Text_nameEmpty__C = "{empty-instance-name}"
const __FAR__ CT__xdc_runtime_Text_nameStatic xdc_runtime_Text_nameStatic__C = "{static-instance-name}"
const __FAR__ CT__xdc_runtime_Text_isLoaded xdc_runtime_Text_isLoaded__C = 1
const __FAR__ CT__xdc_runtime_Text_charTab xdc_runtime_Text_charTab__C = ((CT__xdc_runtime_Text_charTab)xdc_runtime_Text_charTab__A)
const __FAR__ CT__xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__C = ((CT__xdc_runtime_Text_nodeTab)xdc_runtime_Text_nodeTab__A)
const __FAR__ CT__xdc_runtime_Text_charCnt xdc_runtime_Text_charCnt__C = (xdc_Int16)0x1aee
const __FAR__ CT__xdc_runtime_Text_nodeCnt xdc_runtime_Text_nodeCnt__C = (xdc_Int16)0x34
const __FAR__ CT__xdc_runtime_Text_unnamedModsLastId xdc_runtime_Text_unnamedModsLastId__C = (xdc_UInt16)0x4000
const __FAR__ CT__xdc_runtime_Text_registryModsLastId xdc_runtime_Text_registryModsLastId__C = (xdc_UInt16)0x7fff
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn xdc_runtime_Text_visitRopeFxn__C = ((CT__xdc_runtime_Text_visitRopeFxn)((xdc_Fxn)xdc_runtime_Text_visitRope__I))
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn2 xdc_runtime_Text_visitRopeFxn2__C = ((CT__xdc_runtime_Text_visitRopeFxn2)((xdc_Fxn)xdc_runtime_Text_visitRope2__I))
__FAR__ int(*volatile __xdc__init__addr)(void) = &__xdc__init
const ti_sysbios_heaps_HeapMem_Handle heap0 = (ti_sysbios_heaps_HeapMem_Handle)((ti_sysbios_heaps_HeapMem_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0])
Macro Definition Documentation
__config__
#define __config__
Definition at line 9 of file mss_mrr_per4f.c.
__nested__
#define __nested__
Definition at line 8 of file mss_mrr_per4f.c.
ATTRIBUTE
#define ATTRIBUTE __attribute__ ((used))
Definition at line 2271 of file mss_mrr_per4f.c.
IMM_FLAG_REG
#define IMM_FLAG_REG 0xFFF7AC18
Definition at line 2492 of file mss_mrr_per4f.c.
IMM_REG_RW32
#define IMM_REG_RW32 (X) (*(volatile UInt32*)(X))
Definition at line 2494 of file mss_mrr_per4f.c.
IMM_WORD1_REG
#define IMM_WORD1_REG 0xFFF7AC84
Definition at line 2493 of file mss_mrr_per4f.c.
Module__DGSENAB [1/20]
#define Module__DGSENAB ti_sysbios_BIOS_RtsGateProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [2/20]
#define Module__DGSENAB ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [3/20]
#define Module__DGSENAB ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [4/20]
#define Module__DGSENAB ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [5/20]
#define Module__DGSENAB ti_sysbios_hal_Hwi_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [6/20]
#define Module__DGSENAB ti_sysbios_hal_Hwi_HwiProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [7/20]
#define Module__DGSENAB ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [8/20]
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [9/20]
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [10/20]
#define Module__DGSENAB ti_sysbios_knl_Clock_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [11/20]
#define Module__DGSENAB ti_sysbios_knl_Clock_TimerProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [12/20]
#define Module__DGSENAB ti_sysbios_knl_Event_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [13/20]
#define Module__DGSENAB ti_sysbios_knl_Queue_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [14/20]
#define Module__DGSENAB ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [15/20]
#define Module__DGSENAB ti_sysbios_knl_Swi_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [16/20]
#define Module__DGSENAB ti_sysbios_knl_Task_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [17/20]
#define Module__DGSENAB ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [18/20]
#define Module__DGSENAB xdc_runtime_Main_Module_GateProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [19/20]
#define Module__DGSENAB xdc_runtime_Memory_HeapProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSENAB [20/20]
#define Module__DGSENAB xdc_runtime_System_Module_GateProxy_Module__diagsEnabled__C
Definition at line 20141 of file mss_mrr_per4f.c.
Module__DGSINCL [1/20]
#define Module__DGSINCL ti_sysbios_BIOS_RtsGateProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [2/20]
#define Module__DGSINCL ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [3/20]
#define Module__DGSINCL ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [4/20]
#define Module__DGSINCL ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [5/20]
#define Module__DGSINCL ti_sysbios_hal_Hwi_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [6/20]
#define Module__DGSINCL ti_sysbios_hal_Hwi_HwiProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [7/20]
#define Module__DGSINCL ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [8/20]
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [9/20]
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [10/20]
#define Module__DGSINCL ti_sysbios_knl_Clock_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [11/20]
#define Module__DGSINCL ti_sysbios_knl_Clock_TimerProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [12/20]
#define Module__DGSINCL ti_sysbios_knl_Event_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [13/20]
#define Module__DGSINCL ti_sysbios_knl_Queue_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [14/20]
#define Module__DGSINCL ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [15/20]
#define Module__DGSINCL ti_sysbios_knl_Swi_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [16/20]
#define Module__DGSINCL ti_sysbios_knl_Task_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [17/20]
#define Module__DGSINCL ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [18/20]
#define Module__DGSINCL xdc_runtime_Main_Module_GateProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [19/20]
#define Module__DGSINCL xdc_runtime_Memory_HeapProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSINCL [20/20]
#define Module__DGSINCL xdc_runtime_System_Module_GateProxy_Module__diagsIncluded__C
Definition at line 20134 of file mss_mrr_per4f.c.
Module__DGSMASK [1/20]
#define Module__DGSMASK ti_sysbios_BIOS_RtsGateProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [2/20]
#define Module__DGSMASK ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [3/20]
#define Module__DGSMASK ti_sysbios_gates_GateHwi_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [4/20]
#define Module__DGSMASK ti_sysbios_gates_GateMutex_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [5/20]
#define Module__DGSMASK ti_sysbios_hal_Hwi_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [6/20]
#define Module__DGSMASK ti_sysbios_hal_Hwi_HwiProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [7/20]
#define Module__DGSMASK ti_sysbios_heaps_HeapBuf_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [8/20]
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [9/20]
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [10/20]
#define Module__DGSMASK ti_sysbios_knl_Clock_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [11/20]
#define Module__DGSMASK ti_sysbios_knl_Clock_TimerProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [12/20]
#define Module__DGSMASK ti_sysbios_knl_Event_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [13/20]
#define Module__DGSMASK ti_sysbios_knl_Queue_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [14/20]
#define Module__DGSMASK ti_sysbios_knl_Semaphore_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [15/20]
#define Module__DGSMASK ti_sysbios_knl_Swi_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [16/20]
#define Module__DGSMASK ti_sysbios_knl_Task_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [17/20]
#define Module__DGSMASK ti_sysbios_timers_rti_Timer_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [18/20]
#define Module__DGSMASK xdc_runtime_Main_Module_GateProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [19/20]
#define Module__DGSMASK xdc_runtime_Memory_HeapProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__DGSMASK [20/20]
#define Module__DGSMASK xdc_runtime_System_Module_GateProxy_Module__diagsMask__C
Definition at line 20148 of file mss_mrr_per4f.c.
Module__G_OBJ [1/20]
#define Module__G_OBJ ti_sysbios_BIOS_RtsGateProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [2/20]
#define Module__G_OBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [3/20]
#define Module__G_OBJ ti_sysbios_gates_GateHwi_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [4/20]
#define Module__G_OBJ ti_sysbios_gates_GateMutex_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [5/20]
#define Module__G_OBJ ti_sysbios_hal_Hwi_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [6/20]
#define Module__G_OBJ ti_sysbios_hal_Hwi_HwiProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [7/20]
#define Module__G_OBJ ti_sysbios_heaps_HeapBuf_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [8/20]
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [9/20]
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [10/20]
#define Module__G_OBJ ti_sysbios_knl_Clock_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [11/20]
#define Module__G_OBJ ti_sysbios_knl_Clock_TimerProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [12/20]
#define Module__G_OBJ ti_sysbios_knl_Event_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [13/20]
#define Module__G_OBJ ti_sysbios_knl_Queue_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [14/20]
#define Module__G_OBJ ti_sysbios_knl_Semaphore_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [15/20]
#define Module__G_OBJ ti_sysbios_knl_Swi_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [16/20]
#define Module__G_OBJ ti_sysbios_knl_Task_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [17/20]
#define Module__G_OBJ ti_sysbios_timers_rti_Timer_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [18/20]
#define Module__G_OBJ xdc_runtime_Main_Module_GateProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [19/20]
#define Module__G_OBJ xdc_runtime_Memory_HeapProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_OBJ [20/20]
#define Module__G_OBJ xdc_runtime_System_Module_GateProxy_Module__gateObj__C
Definition at line 20205 of file mss_mrr_per4f.c.
Module__G_PRMS [1/20]
#define Module__G_PRMS ti_sysbios_BIOS_RtsGateProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [2/20]
#define Module__G_PRMS ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [3/20]
#define Module__G_PRMS ti_sysbios_gates_GateHwi_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [4/20]
#define Module__G_PRMS ti_sysbios_gates_GateMutex_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [5/20]
#define Module__G_PRMS ti_sysbios_hal_Hwi_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [6/20]
#define Module__G_PRMS ti_sysbios_hal_Hwi_HwiProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [7/20]
#define Module__G_PRMS ti_sysbios_heaps_HeapBuf_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [8/20]
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [9/20]
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [10/20]
#define Module__G_PRMS ti_sysbios_knl_Clock_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [11/20]
#define Module__G_PRMS ti_sysbios_knl_Clock_TimerProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [12/20]
#define Module__G_PRMS ti_sysbios_knl_Event_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [13/20]
#define Module__G_PRMS ti_sysbios_knl_Queue_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [14/20]
#define Module__G_PRMS ti_sysbios_knl_Semaphore_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [15/20]
#define Module__G_PRMS ti_sysbios_knl_Swi_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [16/20]
#define Module__G_PRMS ti_sysbios_knl_Task_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [17/20]
#define Module__G_PRMS ti_sysbios_timers_rti_Timer_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [18/20]
#define Module__G_PRMS xdc_runtime_Main_Module_GateProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [19/20]
#define Module__G_PRMS xdc_runtime_Memory_HeapProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__G_PRMS [20/20]
#define Module__G_PRMS xdc_runtime_System_Module_GateProxy_Module__gatePrms__C
Definition at line 20212 of file mss_mrr_per4f.c.
Module__GP_create [1/20]
#define Module__GP_create ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [2/20]
#define Module__GP_create ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [3/20]
#define Module__GP_create ti_sysbios_gates_GateHwi_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [4/20]
#define Module__GP_create ti_sysbios_gates_GateMutex_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [5/20]
#define Module__GP_create ti_sysbios_hal_Hwi_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [6/20]
#define Module__GP_create ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [7/20]
#define Module__GP_create ti_sysbios_heaps_HeapBuf_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [8/20]
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [9/20]
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [10/20]
#define Module__GP_create ti_sysbios_knl_Clock_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [11/20]
#define Module__GP_create ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [12/20]
#define Module__GP_create ti_sysbios_knl_Event_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [13/20]
#define Module__GP_create ti_sysbios_knl_Queue_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [14/20]
#define Module__GP_create ti_sysbios_knl_Semaphore_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [15/20]
#define Module__GP_create ti_sysbios_knl_Swi_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [16/20]
#define Module__GP_create ti_sysbios_knl_Task_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [17/20]
#define Module__GP_create ti_sysbios_timers_rti_Timer_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [18/20]
#define Module__GP_create xdc_runtime_Main_Module_GateProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [19/20]
#define Module__GP_create xdc_runtime_Memory_HeapProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_create [20/20]
#define Module__GP_create xdc_runtime_System_Module_GateProxy_Module_GateProxy_create
Definition at line 20216 of file mss_mrr_per4f.c.
Module__GP_delete [1/20]
#define Module__GP_delete ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [2/20]
#define Module__GP_delete ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [3/20]
#define Module__GP_delete ti_sysbios_gates_GateHwi_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [4/20]
#define Module__GP_delete ti_sysbios_gates_GateMutex_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [5/20]
#define Module__GP_delete ti_sysbios_hal_Hwi_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [6/20]
#define Module__GP_delete ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [7/20]
#define Module__GP_delete ti_sysbios_heaps_HeapBuf_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [8/20]
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [9/20]
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [10/20]
#define Module__GP_delete ti_sysbios_knl_Clock_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [11/20]
#define Module__GP_delete ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [12/20]
#define Module__GP_delete ti_sysbios_knl_Event_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [13/20]
#define Module__GP_delete ti_sysbios_knl_Queue_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [14/20]
#define Module__GP_delete ti_sysbios_knl_Semaphore_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [15/20]
#define Module__GP_delete ti_sysbios_knl_Swi_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [16/20]
#define Module__GP_delete ti_sysbios_knl_Task_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [17/20]
#define Module__GP_delete ti_sysbios_timers_rti_Timer_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [18/20]
#define Module__GP_delete xdc_runtime_Main_Module_GateProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [19/20]
#define Module__GP_delete xdc_runtime_Memory_HeapProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_delete [20/20]
#define Module__GP_delete xdc_runtime_System_Module_GateProxy_Module_GateProxy_delete
Definition at line 20218 of file mss_mrr_per4f.c.
Module__GP_enter [1/20]
#define Module__GP_enter ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [2/20]
#define Module__GP_enter ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [3/20]
#define Module__GP_enter ti_sysbios_gates_GateHwi_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [4/20]
#define Module__GP_enter ti_sysbios_gates_GateMutex_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [5/20]
#define Module__GP_enter ti_sysbios_hal_Hwi_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [6/20]
#define Module__GP_enter ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [7/20]
#define Module__GP_enter ti_sysbios_heaps_HeapBuf_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [8/20]
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [9/20]
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [10/20]
#define Module__GP_enter ti_sysbios_knl_Clock_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [11/20]
#define Module__GP_enter ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [12/20]
#define Module__GP_enter ti_sysbios_knl_Event_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [13/20]
#define Module__GP_enter ti_sysbios_knl_Queue_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [14/20]
#define Module__GP_enter ti_sysbios_knl_Semaphore_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [15/20]
#define Module__GP_enter ti_sysbios_knl_Swi_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [16/20]
#define Module__GP_enter ti_sysbios_knl_Task_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [17/20]
#define Module__GP_enter ti_sysbios_timers_rti_Timer_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [18/20]
#define Module__GP_enter xdc_runtime_Main_Module_GateProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [19/20]
#define Module__GP_enter xdc_runtime_Memory_HeapProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_enter [20/20]
#define Module__GP_enter xdc_runtime_System_Module_GateProxy_Module_GateProxy_enter
Definition at line 20220 of file mss_mrr_per4f.c.
Module__GP_leave [1/20]
#define Module__GP_leave ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [2/20]
#define Module__GP_leave ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [3/20]
#define Module__GP_leave ti_sysbios_gates_GateHwi_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [4/20]
#define Module__GP_leave ti_sysbios_gates_GateMutex_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [5/20]
#define Module__GP_leave ti_sysbios_hal_Hwi_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [6/20]
#define Module__GP_leave ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [7/20]
#define Module__GP_leave ti_sysbios_heaps_HeapBuf_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [8/20]
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [9/20]
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [10/20]
#define Module__GP_leave ti_sysbios_knl_Clock_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [11/20]
#define Module__GP_leave ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [12/20]
#define Module__GP_leave ti_sysbios_knl_Event_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [13/20]
#define Module__GP_leave ti_sysbios_knl_Queue_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [14/20]
#define Module__GP_leave ti_sysbios_knl_Semaphore_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [15/20]
#define Module__GP_leave ti_sysbios_knl_Swi_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [16/20]
#define Module__GP_leave ti_sysbios_knl_Task_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [17/20]
#define Module__GP_leave ti_sysbios_timers_rti_Timer_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [18/20]
#define Module__GP_leave xdc_runtime_Main_Module_GateProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [19/20]
#define Module__GP_leave xdc_runtime_Memory_HeapProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_leave [20/20]
#define Module__GP_leave xdc_runtime_System_Module_GateProxy_Module_GateProxy_leave
Definition at line 20222 of file mss_mrr_per4f.c.
Module__GP_query [1/20]
#define Module__GP_query ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [2/20]
#define Module__GP_query ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [3/20]
#define Module__GP_query ti_sysbios_gates_GateHwi_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [4/20]
#define Module__GP_query ti_sysbios_gates_GateMutex_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [5/20]
#define Module__GP_query ti_sysbios_hal_Hwi_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [6/20]
#define Module__GP_query ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [7/20]
#define Module__GP_query ti_sysbios_heaps_HeapBuf_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [8/20]
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [9/20]
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [10/20]
#define Module__GP_query ti_sysbios_knl_Clock_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [11/20]
#define Module__GP_query ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [12/20]
#define Module__GP_query ti_sysbios_knl_Event_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [13/20]
#define Module__GP_query ti_sysbios_knl_Queue_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [14/20]
#define Module__GP_query ti_sysbios_knl_Semaphore_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [15/20]
#define Module__GP_query ti_sysbios_knl_Swi_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [16/20]
#define Module__GP_query ti_sysbios_knl_Task_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [17/20]
#define Module__GP_query ti_sysbios_timers_rti_Timer_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [18/20]
#define Module__GP_query xdc_runtime_Main_Module_GateProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [19/20]
#define Module__GP_query xdc_runtime_Memory_HeapProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__GP_query [20/20]
#define Module__GP_query xdc_runtime_System_Module_GateProxy_Module_GateProxy_query
Definition at line 20224 of file mss_mrr_per4f.c.
Module__LOGDEF [1/20]
#define Module__LOGDEF ti_sysbios_BIOS_RtsGateProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [2/20]
#define Module__LOGDEF ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [3/20]
#define Module__LOGDEF ti_sysbios_gates_GateHwi_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [4/20]
#define Module__LOGDEF ti_sysbios_gates_GateMutex_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [5/20]
#define Module__LOGDEF ti_sysbios_hal_Hwi_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [6/20]
#define Module__LOGDEF ti_sysbios_hal_Hwi_HwiProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [7/20]
#define Module__LOGDEF ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [8/20]
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [9/20]
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [10/20]
#define Module__LOGDEF ti_sysbios_knl_Clock_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [11/20]
#define Module__LOGDEF ti_sysbios_knl_Clock_TimerProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [12/20]
#define Module__LOGDEF ti_sysbios_knl_Event_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [13/20]
#define Module__LOGDEF ti_sysbios_knl_Queue_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [14/20]
#define Module__LOGDEF ti_sysbios_knl_Semaphore_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [15/20]
#define Module__LOGDEF ti_sysbios_knl_Swi_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [16/20]
#define Module__LOGDEF ti_sysbios_knl_Task_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [17/20]
#define Module__LOGDEF ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [18/20]
#define Module__LOGDEF xdc_runtime_Main_Module_GateProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [19/20]
#define Module__LOGDEF xdc_runtime_Memory_HeapProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGDEF [20/20]
#define Module__LOGDEF xdc_runtime_System_Module_GateProxy_Module__loggerDefined__C
Definition at line 20155 of file mss_mrr_per4f.c.
Module__LOGFXN0 [1/20]
#define Module__LOGFXN0 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [2/20]
#define Module__LOGFXN0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [3/20]
#define Module__LOGFXN0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [4/20]
#define Module__LOGFXN0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [5/20]
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [6/20]
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [7/20]
#define Module__LOGFXN0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [8/20]
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [9/20]
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [10/20]
#define Module__LOGFXN0 ti_sysbios_knl_Clock_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [11/20]
#define Module__LOGFXN0 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [12/20]
#define Module__LOGFXN0 ti_sysbios_knl_Event_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [13/20]
#define Module__LOGFXN0 ti_sysbios_knl_Queue_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [14/20]
#define Module__LOGFXN0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [15/20]
#define Module__LOGFXN0 ti_sysbios_knl_Swi_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [16/20]
#define Module__LOGFXN0 ti_sysbios_knl_Task_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [17/20]
#define Module__LOGFXN0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [18/20]
#define Module__LOGFXN0 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [19/20]
#define Module__LOGFXN0 xdc_runtime_Memory_HeapProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN0 [20/20]
#define Module__LOGFXN0 xdc_runtime_System_Module_GateProxy_Module__loggerFxn0__C
Definition at line 20170 of file mss_mrr_per4f.c.
Module__LOGFXN1 [1/20]
#define Module__LOGFXN1 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [2/20]
#define Module__LOGFXN1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [3/20]
#define Module__LOGFXN1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [4/20]
#define Module__LOGFXN1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [5/20]
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [6/20]
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [7/20]
#define Module__LOGFXN1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [8/20]
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [9/20]
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [10/20]
#define Module__LOGFXN1 ti_sysbios_knl_Clock_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [11/20]
#define Module__LOGFXN1 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [12/20]
#define Module__LOGFXN1 ti_sysbios_knl_Event_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [13/20]
#define Module__LOGFXN1 ti_sysbios_knl_Queue_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [14/20]
#define Module__LOGFXN1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [15/20]
#define Module__LOGFXN1 ti_sysbios_knl_Swi_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [16/20]
#define Module__LOGFXN1 ti_sysbios_knl_Task_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [17/20]
#define Module__LOGFXN1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [18/20]
#define Module__LOGFXN1 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [19/20]
#define Module__LOGFXN1 xdc_runtime_Memory_HeapProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN1 [20/20]
#define Module__LOGFXN1 xdc_runtime_System_Module_GateProxy_Module__loggerFxn1__C
Definition at line 20177 of file mss_mrr_per4f.c.
Module__LOGFXN2 [1/20]
#define Module__LOGFXN2 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [2/20]
#define Module__LOGFXN2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [3/20]
#define Module__LOGFXN2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [4/20]
#define Module__LOGFXN2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [5/20]
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [6/20]
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [7/20]
#define Module__LOGFXN2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [8/20]
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [9/20]
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [10/20]
#define Module__LOGFXN2 ti_sysbios_knl_Clock_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [11/20]
#define Module__LOGFXN2 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [12/20]
#define Module__LOGFXN2 ti_sysbios_knl_Event_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [13/20]
#define Module__LOGFXN2 ti_sysbios_knl_Queue_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [14/20]
#define Module__LOGFXN2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [15/20]
#define Module__LOGFXN2 ti_sysbios_knl_Swi_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [16/20]
#define Module__LOGFXN2 ti_sysbios_knl_Task_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [17/20]
#define Module__LOGFXN2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [18/20]
#define Module__LOGFXN2 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [19/20]
#define Module__LOGFXN2 xdc_runtime_Memory_HeapProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN2 [20/20]
#define Module__LOGFXN2 xdc_runtime_System_Module_GateProxy_Module__loggerFxn2__C
Definition at line 20184 of file mss_mrr_per4f.c.
Module__LOGFXN4 [1/20]
#define Module__LOGFXN4 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [2/20]
#define Module__LOGFXN4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [3/20]
#define Module__LOGFXN4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [4/20]
#define Module__LOGFXN4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [5/20]
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [6/20]
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [7/20]
#define Module__LOGFXN4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [8/20]
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [9/20]
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [10/20]
#define Module__LOGFXN4 ti_sysbios_knl_Clock_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [11/20]
#define Module__LOGFXN4 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [12/20]
#define Module__LOGFXN4 ti_sysbios_knl_Event_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [13/20]
#define Module__LOGFXN4 ti_sysbios_knl_Queue_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [14/20]
#define Module__LOGFXN4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [15/20]
#define Module__LOGFXN4 ti_sysbios_knl_Swi_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [16/20]
#define Module__LOGFXN4 ti_sysbios_knl_Task_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [17/20]
#define Module__LOGFXN4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [18/20]
#define Module__LOGFXN4 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [19/20]
#define Module__LOGFXN4 xdc_runtime_Memory_HeapProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN4 [20/20]
#define Module__LOGFXN4 xdc_runtime_System_Module_GateProxy_Module__loggerFxn4__C
Definition at line 20191 of file mss_mrr_per4f.c.
Module__LOGFXN8 [1/20]
#define Module__LOGFXN8 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [2/20]
#define Module__LOGFXN8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [3/20]
#define Module__LOGFXN8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [4/20]
#define Module__LOGFXN8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [5/20]
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [6/20]
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [7/20]
#define Module__LOGFXN8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [8/20]
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [9/20]
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [10/20]
#define Module__LOGFXN8 ti_sysbios_knl_Clock_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [11/20]
#define Module__LOGFXN8 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [12/20]
#define Module__LOGFXN8 ti_sysbios_knl_Event_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [13/20]
#define Module__LOGFXN8 ti_sysbios_knl_Queue_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [14/20]
#define Module__LOGFXN8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [15/20]
#define Module__LOGFXN8 ti_sysbios_knl_Swi_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [16/20]
#define Module__LOGFXN8 ti_sysbios_knl_Task_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [17/20]
#define Module__LOGFXN8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [18/20]
#define Module__LOGFXN8 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [19/20]
#define Module__LOGFXN8 xdc_runtime_Memory_HeapProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGFXN8 [20/20]
#define Module__LOGFXN8 xdc_runtime_System_Module_GateProxy_Module__loggerFxn8__C
Definition at line 20198 of file mss_mrr_per4f.c.
Module__LOGOBJ [1/20]
#define Module__LOGOBJ ti_sysbios_BIOS_RtsGateProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [2/20]
#define Module__LOGOBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [3/20]
#define Module__LOGOBJ ti_sysbios_gates_GateHwi_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [4/20]
#define Module__LOGOBJ ti_sysbios_gates_GateMutex_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [5/20]
#define Module__LOGOBJ ti_sysbios_hal_Hwi_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [6/20]
#define Module__LOGOBJ ti_sysbios_hal_Hwi_HwiProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [7/20]
#define Module__LOGOBJ ti_sysbios_heaps_HeapBuf_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [8/20]
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [9/20]
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [10/20]
#define Module__LOGOBJ ti_sysbios_knl_Clock_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [11/20]
#define Module__LOGOBJ ti_sysbios_knl_Clock_TimerProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [12/20]
#define Module__LOGOBJ ti_sysbios_knl_Event_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [13/20]
#define Module__LOGOBJ ti_sysbios_knl_Queue_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [14/20]
#define Module__LOGOBJ ti_sysbios_knl_Semaphore_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [15/20]
#define Module__LOGOBJ ti_sysbios_knl_Swi_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [16/20]
#define Module__LOGOBJ ti_sysbios_knl_Task_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [17/20]
#define Module__LOGOBJ ti_sysbios_timers_rti_Timer_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [18/20]
#define Module__LOGOBJ xdc_runtime_Main_Module_GateProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [19/20]
#define Module__LOGOBJ xdc_runtime_Memory_HeapProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__LOGOBJ [20/20]
#define Module__LOGOBJ xdc_runtime_System_Module_GateProxy_Module__loggerObj__C
Definition at line 20163 of file mss_mrr_per4f.c.
Module__MID [1/20]
#define Module__MID ti_sysbios_BIOS_RtsGateProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [2/20]
#define Module__MID ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [3/20]
#define Module__MID ti_sysbios_gates_GateHwi_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [4/20]
#define Module__MID ti_sysbios_gates_GateMutex_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [5/20]
#define Module__MID ti_sysbios_hal_Hwi_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [6/20]
#define Module__MID ti_sysbios_hal_Hwi_HwiProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [7/20]
#define Module__MID ti_sysbios_heaps_HeapBuf_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [8/20]
#define Module__MID ti_sysbios_heaps_HeapMem_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [9/20]
#define Module__MID ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [10/20]
#define Module__MID ti_sysbios_knl_Clock_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [11/20]
#define Module__MID ti_sysbios_knl_Clock_TimerProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [12/20]
#define Module__MID ti_sysbios_knl_Event_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [13/20]
#define Module__MID ti_sysbios_knl_Queue_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [14/20]
#define Module__MID ti_sysbios_knl_Semaphore_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [15/20]
#define Module__MID ti_sysbios_knl_Swi_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [16/20]
#define Module__MID ti_sysbios_knl_Task_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [17/20]
#define Module__MID ti_sysbios_timers_rti_Timer_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [18/20]
#define Module__MID xdc_runtime_Main_Module_GateProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [19/20]
#define Module__MID xdc_runtime_Memory_HeapProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Module__MID [20/20]
#define Module__MID xdc_runtime_System_Module_GateProxy_Module__id__C
Definition at line 20127 of file mss_mrr_per4f.c.
Typedef Documentation
Header
typedef union Header Header
ti_sysbios_BIOS_Module_State__
typedef struct ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module_State__
ti_sysbios_BIOS_RtsGateProxy_Module__
typedef struct ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__
ti_sysbios_BIOS_RtsGateProxy_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_BIOS_RtsGateProxy_Object__
Definition at line 146 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module_State__
typedef struct ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module_State__
ti_sysbios_family_arm_v7r_vim_Hwi_Module__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
ti_sysbios_family_arm_v7r_vim_Hwi_Object__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__
ti_sysbios_gates_GateHwi_Module__
typedef struct ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__
ti_sysbios_gates_GateHwi_Object__
typedef struct ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__
ti_sysbios_gates_GateMutex_Module__
typedef struct ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__
ti_sysbios_gates_GateMutex_Object__
typedef struct ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__
ti_sysbios_hal_Hwi_HwiProxy_Module__
typedef struct ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__
ti_sysbios_hal_Hwi_HwiProxy_Object__
typedef ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_hal_Hwi_HwiProxy_Object__
Definition at line 310 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__
typedef struct ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__
ti_sysbios_hal_Hwi_Object__
typedef struct ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__
ti_sysbios_heaps_HeapBuf_Module__
typedef struct ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__
ti_sysbios_heaps_HeapBuf_Module_State__
typedef struct ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module_State__
ti_sysbios_heaps_HeapBuf_Object__
typedef struct ti_sysbios_heaps_HeapBuf_Object__ ti_sysbios_heaps_HeapBuf_Object__
ti_sysbios_heaps_HeapMem_Module__
typedef struct ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
typedef struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
Definition at line 396 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Object__
typedef struct ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__
ti_sysbios_knl_Clock_Module__
typedef struct ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__
ti_sysbios_knl_Clock_Module_State__
typedef struct ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module_State__
ti_sysbios_knl_Clock_Object__
typedef struct ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__
ti_sysbios_knl_Clock_TimerProxy_Module__
typedef struct ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__
ti_sysbios_knl_Clock_TimerProxy_Object__
typedef ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_knl_Clock_TimerProxy_Object__
Definition at line 474 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__
typedef struct ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__
ti_sysbios_knl_Event_Object__
typedef struct ti_sysbios_knl_Event_Object__ ti_sysbios_knl_Event_Object__
ti_sysbios_knl_Queue_Module__
typedef struct ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__
ti_sysbios_knl_Queue_Object__
typedef struct ti_sysbios_knl_Queue_Object__ ti_sysbios_knl_Queue_Object__
ti_sysbios_knl_Semaphore_Module__
typedef struct ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__
ti_sysbios_knl_Semaphore_Object__
typedef struct ti_sysbios_knl_Semaphore_Object__ ti_sysbios_knl_Semaphore_Object__
ti_sysbios_knl_Swi_Module__
typedef struct ti_sysbios_knl_Swi_Module__ ti_sysbios_knl_Swi_Module__
ti_sysbios_knl_Swi_Module_State__
typedef struct ti_sysbios_knl_Swi_Module_State__ ti_sysbios_knl_Swi_Module_State__
ti_sysbios_knl_Swi_Object__
typedef struct ti_sysbios_knl_Swi_Object__ ti_sysbios_knl_Swi_Object__
ti_sysbios_knl_Task_Module__
typedef struct ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__
ti_sysbios_knl_Task_Module_State__
typedef struct ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module_State__
ti_sysbios_knl_Task_Object__
typedef struct ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__
ti_sysbios_timers_rti_Timer_Module__
typedef struct ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__
ti_sysbios_timers_rti_Timer_Module_State__
typedef struct ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module_State__
ti_sysbios_timers_rti_Timer_Object__
typedef struct ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__
xdc_runtime_Error_Module_State__
typedef struct xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module_State__
xdc_runtime_Main_Module_GateProxy_Module__
typedef struct xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__
xdc_runtime_Main_Module_GateProxy_Object__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_Main_Module_GateProxy_Object__
Definition at line 711 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_Module__
typedef struct xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__
xdc_runtime_Memory_HeapProxy_Object__
typedef ti_sysbios_heaps_HeapMem_Object__ xdc_runtime_Memory_HeapProxy_Object__
Definition at line 740 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module_State__
typedef struct xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module_State__
xdc_runtime_Registry_Module_State__
typedef struct xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module_State__
xdc_runtime_Startup_Module_State__
typedef struct xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module_State__
xdc_runtime_System_Module_GateProxy_Module__
typedef struct xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__
xdc_runtime_System_Module_GateProxy_Object__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_System_Module_GateProxy_Object__
Definition at line 784 of file mss_mrr_per4f.c.
xdc_runtime_System_Module_State__
typedef struct xdc_runtime_System_Module_State__ xdc_runtime_System_Module_State__
xdc_runtime_Text_Module_State__
typedef struct xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module_State__
Function Documentation
__xdc__init()
int __xdc__init (void)
_c_int00()
Void _c_int00 ()
calloc()
Void ATTRIBUTE* calloc (SizeT nmemb, SizeT size)
Definition at line 2385 of file mss_mrr_per4f.c.
References ti_sysbios_rts_MemAlloc_alloc().
free()
Void ATTRIBUTE free (Void * ptr)
Definition at line 2408 of file mss_mrr_per4f.c.
References Header::actualBuf, Header::header, and Header::size.
Referenced by realloc().
malloc()
Void ATTRIBUTE* malloc (SizeT size)
Definition at line 2336 of file mss_mrr_per4f.c.
References ti_sysbios_rts_MemAlloc_alloc().
Referenced by realloc().
memalign()
Void ATTRIBUTE* memalign (SizeT alignment, SizeT size)
Definition at line 2345 of file mss_mrr_per4f.c.
References Header::actualBuf, Header::header, and Header::size.
realloc()
Void ATTRIBUTE* realloc (Void * ptr, SizeT size)
Definition at line 2424 of file mss_mrr_per4f.c.
References free(), Header::header, malloc(), and Header::size.
ti_sysbios_BIOS_atExitFunc__I()
Void ti_sysbios_BIOS_atExitFunc__I (Int notused)
Definition at line 2076 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_startFunc__I().
ti_sysbios_BIOS_errorRaiseHook()
Void ti_sysbios_BIOS_errorRaiseHook (xdc_runtime_Error_Block * eb)
Definition at line 2166 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_removeRTSLock().
ti_sysbios_BIOS_exitFunc() [1/2]
Void ti_sysbios_BIOS_exitFunc (Int stat)
Definition at line 2152 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_removeRTSLock().
ti_sysbios_BIOS_exitFunc() [2/2]
xdc_Void ti_sysbios_BIOS_exitFunc (xdc_Int)
ti_sysbios_BIOS_Module__startupDone__S()
xdc_Bool ti_sysbios_BIOS_Module__startupDone__S (void)
Definition at line 15857 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_nullFunc__I()
Void ti_sysbios_BIOS_nullFunc__I ()
Definition at line 2123 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_registerRTSLock() [1/2]
Void ti_sysbios_BIOS_registerRTSLock ()
Referenced by ti_sysbios_BIOS_startFunc__I().
ti_sysbios_BIOS_registerRTSLock() [2/2]
Void ti_sysbios_BIOS_registerRTSLock (Void)
Definition at line 2130 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_Module__state__V, ti_sysbios_BIOS_rtsLock(), and ti_sysbios_BIOS_rtsUnlock().
ti_sysbios_BIOS_removeRTSLock()
Void ti_sysbios_BIOS_removeRTSLock (Void)
Definition at line 2141 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_errorRaiseHook(), and ti_sysbios_BIOS_exitFunc().
ti_sysbios_BIOS_RtsGateProxy_create()
ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_RtsGateProxy_create (const ti_sysbios_BIOS_RtsGateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 14786 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_create().
ti_sysbios_BIOS_RtsGateProxy_delete()
void ti_sysbios_BIOS_RtsGateProxy_delete (ti_sysbios_BIOS_RtsGateProxy_Handle * instp)
Definition at line 14792 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_BIOS_RtsGateProxy_enter__E()
xdc_IArg ti_sysbios_BIOS_RtsGateProxy_enter__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst)
Definition at line 14816 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_RtsGateProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_BIOS_RtsGateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 14804 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Handle__label__S().
ti_sysbios_BIOS_RtsGateProxy_leave__E()
xdc_Void ti_sysbios_BIOS_RtsGateProxy_leave__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst, xdc_IArg key)
Definition at line 14822 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S (void)
Definition at line 14780 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Module__startupDone__S().
ti_sysbios_BIOS_RtsGateProxy_Params__init__S()
void ti_sysbios_BIOS_RtsGateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 14798 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Params__init__S().
ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S (void)
Definition at line 15972 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S (void)
Definition at line 15976 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Module__FXNS__C.
ti_sysbios_BIOS_RtsGateProxy_query__E()
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_query__E (xdc_Int qual)
Definition at line 14810 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_rtsLock()
Void ti_sysbios_BIOS_rtsLock ()
Definition at line 2093 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_registerRTSLock().
ti_sysbios_BIOS_rtsUnlock()
Void ti_sysbios_BIOS_rtsUnlock ()
Definition at line 2109 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_registerRTSLock().
ti_sysbios_BIOS_startFunc()
xdc_Void ti_sysbios_BIOS_startFunc (xdc_Void)
ti_sysbios_BIOS_startFunc__I()
Void ti_sysbios_BIOS_startFunc__I ()
Definition at line 2054 of file mss_mrr_per4f.c.
References ti_sysbios_BIOS_atExitFunc__I(), ti_sysbios_BIOS_registerRTSLock(), and ti_sysbios_timers_rti_Timer_startup__E().
ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I()
Void ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I ()
ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I()
Void ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I ()
ti_sysbios_family_arm_exc_Exception_Module__startupDone__F()
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__F (void)
Definition at line 1769 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_exc_Exception_Module__startupDone__S().
ti_sysbios_family_arm_exc_Exception_Module__startupDone__S()
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__S (void)
Definition at line 16012 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_exc_Exception_Module__startupDone__F().
ti_sysbios_family_arm_exc_Exception_Module_startup__E()
xdc_Int ti_sysbios_family_arm_exc_Exception_Module_startup__E (xdc_Int)
ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S()
xdc_Bool ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S (void)
Definition at line 15988 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S().
ti_sysbios_family_arm_TaskSupport_Module__startupDone__S()
xdc_Bool ti_sysbios_family_arm_TaskSupport_Module__startupDone__S (void)
Definition at line 16000 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S().
ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F()
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F (void)
Definition at line 1777 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S().
ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S()
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S (void)
Definition at line 16024 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F().
Referenced by ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S().
ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E()
xdc_Int ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E (xdc_Int)
ti_sysbios_family_arm_v7r_tms570_Core_resetC__I()
Void ti_sysbios_family_arm_v7r_tms570_Core_resetC__I ()
Definition at line 2499 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_construct()
void ti_sysbios_family_arm_v7r_vim_Hwi_construct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct * __obj, xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 16252 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C.
ti_sysbios_family_arm_v7r_vim_Hwi_create()
ti_sysbios_family_arm_v7r_vim_Hwi_Handle ti_sysbios_family_arm_v7r_vim_Hwi_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 16228 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_create().
ti_sysbios_family_arm_v7r_vim_Hwi_delete()
void ti_sysbios_family_arm_v7r_vim_Hwi_delete (ti_sysbios_family_arm_v7r_vim_Hwi_Handle * instp)
Definition at line 16282 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S().
ti_sysbios_family_arm_v7r_vim_Hwi_destruct()
void ti_sysbios_family_arm_v7r_vim_Hwi_destruct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct * obj)
Definition at line 16269 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C.
ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I()
Void ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I ()
ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 16146 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F()
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F (void)
Definition at line 1765 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S()
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S (void)
Definition at line 16140 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F().
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E()
xdc_Int ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E (xdc_Int)
ti_sysbios_family_arm_v7r_vim_Hwi_Object__create__S()
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 16199 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S()
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S (xdc_Ptr instp)
Definition at line 16275 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_delete(), and ti_sysbios_hal_Hwi_HwiProxy_delete().
ti_sysbios_family_arm_v7r_vim_Hwi_Object__first__S()
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__first__S (void)
Definition at line 16173 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__::link, and ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__get__S()
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 16162 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__C.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__next__S()
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__next__S (xdc_Ptr obj)
Definition at line 16186 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__::link, and ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.
ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S()
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 16156 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Params__init__S().
ti_sysbios_gates_GateHwi_construct()
void ti_sysbios_gates_GateHwi_construct (ti_sysbios_gates_GateHwi_Struct * __obj, const ti_sysbios_gates_GateHwi_Params * __paramsPtr)
Definition at line 16496 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
ti_sysbios_gates_GateHwi_create()
ti_sysbios_gates_GateHwi_Handle ti_sysbios_gates_GateHwi_create (const ti_sysbios_gates_GateHwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 16478 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
Referenced by xdc_runtime_Main_Module_GateProxy_create(), and xdc_runtime_System_Module_GateProxy_create().
ti_sysbios_gates_GateHwi_delete()
void ti_sysbios_gates_GateHwi_delete (ti_sysbios_gates_GateHwi_Handle * instp)
Definition at line 16521 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
ti_sysbios_gates_GateHwi_destruct()
void ti_sysbios_gates_GateHwi_destruct (ti_sysbios_gates_GateHwi_Struct * obj)
Definition at line 16508 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
ti_sysbios_gates_GateHwi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_gates_GateHwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 16403 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Main_Module_GateProxy_Handle__label__S(), and xdc_runtime_System_Module_GateProxy_Handle__label__S().
ti_sysbios_gates_GateHwi_Module__startupDone__S()
xdc_Bool ti_sysbios_gates_GateHwi_Module__startupDone__S (void)
Definition at line 16397 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Main_Module_GateProxy_Module__startupDone__S(), and xdc_runtime_System_Module_GateProxy_Module__startupDone__S().
ti_sysbios_gates_GateHwi_Object__create__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 16456 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
ti_sysbios_gates_GateHwi_Object__delete__S()
xdc_Void ti_sysbios_gates_GateHwi_Object__delete__S (xdc_Ptr instp)
Definition at line 16514 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
Referenced by ti_sysbios_gates_GateHwi_delete(), xdc_runtime_Main_Module_GateProxy_delete(), and xdc_runtime_System_Module_GateProxy_delete().
ti_sysbios_gates_GateHwi_Object__first__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__first__S (void)
Definition at line 16430 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Module__::link, and ti_sysbios_gates_GateHwi_Module__root__V.
ti_sysbios_gates_GateHwi_Object__get__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 16419 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__table__C.
ti_sysbios_gates_GateHwi_Object__next__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__next__S (xdc_Ptr obj)
Definition at line 16443 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Module__::link, and ti_sysbios_gates_GateHwi_Module__root__V.
ti_sysbios_gates_GateHwi_Params__init__S()
xdc_Void ti_sysbios_gates_GateHwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 16413 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__PARAMS__C.
Referenced by xdc_runtime_Main_Module_GateProxy_Params__init__S(), and xdc_runtime_System_Module_GateProxy_Params__init__S().
ti_sysbios_gates_GateMutex_construct()
void ti_sysbios_gates_GateMutex_construct (ti_sysbios_gates_GateMutex_Struct * __obj, const ti_sysbios_gates_GateMutex_Params * __paramsPtr)
Definition at line 16735 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
ti_sysbios_gates_GateMutex_create()
ti_sysbios_gates_GateMutex_Handle ti_sysbios_gates_GateMutex_create (const ti_sysbios_gates_GateMutex_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 16717 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
Referenced by ti_sysbios_BIOS_RtsGateProxy_create(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_create().
ti_sysbios_gates_GateMutex_delete()
void ti_sysbios_gates_GateMutex_delete (ti_sysbios_gates_GateMutex_Handle * instp)
Definition at line 16760 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_gates_GateMutex_destruct()
void ti_sysbios_gates_GateMutex_destruct (ti_sysbios_gates_GateMutex_Struct * obj)
Definition at line 16747 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
ti_sysbios_gates_GateMutex_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_gates_GateMutex_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 16642 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Handle__label__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S().
ti_sysbios_gates_GateMutex_Module__startupDone__S()
xdc_Bool ti_sysbios_gates_GateMutex_Module__startupDone__S (void)
Definition at line 16636 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S().
ti_sysbios_gates_GateMutex_Object__create__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 16695 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
ti_sysbios_gates_GateMutex_Object__delete__S()
xdc_Void ti_sysbios_gates_GateMutex_Object__delete__S (xdc_Ptr instp)
Definition at line 16753 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
Referenced by ti_sysbios_BIOS_RtsGateProxy_delete(), ti_sysbios_gates_GateMutex_delete(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_delete().
ti_sysbios_gates_GateMutex_Object__first__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__first__S (void)
Definition at line 16669 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Module__::link, and ti_sysbios_gates_GateMutex_Module__root__V.
ti_sysbios_gates_GateMutex_Object__get__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 16658 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__table__C.
ti_sysbios_gates_GateMutex_Object__next__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__next__S (xdc_Ptr obj)
Definition at line 16682 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Module__::link, and ti_sysbios_gates_GateMutex_Module__root__V.
ti_sysbios_gates_GateMutex_Params__init__S()
xdc_Void ti_sysbios_gates_GateMutex_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 16652 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__PARAMS__C.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Params__init__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S().
ti_sysbios_hal_Cache_CacheProxy_disable__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_disable__E (xdc_Bits16 type)
Definition at line 14847 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_enable__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_enable__E (xdc_Bits16 type)
Definition at line 14841 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_inv__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_inv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
Definition at line 14853 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S (void)
Definition at line 14835 of file mss_mrr_per4f.c.
References ti_sysbios_hal_CacheNull_Module__startupDone__S().
ti_sysbios_hal_Cache_CacheProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Proxy__abstract__S (void)
Definition at line 16795 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S (void)
Definition at line 16799 of file mss_mrr_per4f.c.
References ti_sysbios_hal_CacheNull_Module__FXNS__C.
ti_sysbios_hal_Cache_CacheProxy_wait__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wait__E (void)
Definition at line 14883 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_wb__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wb__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
Definition at line 14859 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_wbAll__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbAll__E (void)
Definition at line 14871 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_wbInv__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
Definition at line 14865 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_CacheProxy_wbInvAll__E()
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInvAll__E (void)
Definition at line 14877 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Cache_Module__startupDone__S (void)
Definition at line 16771 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_CacheNull_Module__startupDone__S (void)
Definition at line 16783 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S().
ti_sysbios_hal_Core_CoreProxy_getId__E()
xdc_UInt ti_sysbios_hal_Core_CoreProxy_getId__E (void)
Definition at line 14902 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_hwiDisable__E()
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiDisable__E (void)
Definition at line 14926 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_hwiEnable__E()
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiEnable__E (void)
Definition at line 14932 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_hwiRestore__E()
xdc_Void ti_sysbios_hal_Core_CoreProxy_hwiRestore__E (xdc_UInt key)
Definition at line 14938 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_interruptCore__E()
xdc_Void ti_sysbios_hal_Core_CoreProxy_interruptCore__E (xdc_UInt coreId)
Definition at line 14908 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_lock__E()
xdc_IArg ti_sysbios_hal_Core_CoreProxy_lock__E (void)
Definition at line 14914 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S (void)
Definition at line 14896 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S().
ti_sysbios_hal_Core_CoreProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Proxy__abstract__S (void)
Definition at line 16822 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_hal_Core_CoreProxy_Proxy__delegate__S (void)
Definition at line 16826 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_CoreProxy_unlock__E()
xdc_Void ti_sysbios_hal_Core_CoreProxy_unlock__E (void)
Definition at line 14920 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Core_Module__startupDone__S (void)
Definition at line 16810 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_checkStack()
xdc_Void ti_sysbios_hal_Hwi_checkStack (xdc_Void)
ti_sysbios_hal_Hwi_construct()
void ti_sysbios_hal_Hwi_construct (ti_sysbios_hal_Hwi_Struct * __obj, xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 17053 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_create()
ti_sysbios_hal_Hwi_Handle ti_sysbios_hal_Hwi_create (xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 17029 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_delete()
void ti_sysbios_hal_Hwi_delete (ti_sysbios_hal_Hwi_Handle * instp)
Definition at line 17083 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__delete__S().
ti_sysbios_hal_Hwi_destruct()
void ti_sysbios_hal_Hwi_destruct (ti_sysbios_hal_Hwi_Struct * obj)
Definition at line 17070 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_hal_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 16947 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E (xdc_UInt intNum)
Definition at line 15053 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_create()
ti_sysbios_hal_Hwi_HwiProxy_Handle ti_sysbios_hal_Hwi_HwiProxy_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_HwiProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 14957 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_create().
ti_sysbios_hal_Hwi_HwiProxy_delete()
void ti_sysbios_hal_Hwi_HwiProxy_delete (ti_sysbios_hal_Hwi_HwiProxy_Handle * instp)
Definition at line 14963 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S().
ti_sysbios_hal_Hwi_HwiProxy_disable__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disable__E (void)
Definition at line 14999 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E (xdc_UInt intNum)
Definition at line 15035 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_enable__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enable__E (void)
Definition at line 15005 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E (xdc_UInt intNum)
Definition at line 15041 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo * stkInfo, xdc_Bool computeStackDepth, xdc_UInt coreId)
Definition at line 14987 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_getFunc__E()
ti_sysbios_interfaces_IHwi_FuncPtr ti_sysbios_hal_Hwi_HwiProxy_getFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_UArg * arg)
Definition at line 15059 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E()
xdc_Ptr ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id)
Definition at line 15071 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_getIrp__E()
ti_sysbios_interfaces_IHwi_Irp ti_sysbios_hal_Hwi_HwiProxy_getIrp__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst)
Definition at line 15083 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo * stkInfo, xdc_Bool computeStackDepth)
Definition at line 14981 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E()
xdc_Char* ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E (void)
Definition at line 15029 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 14975 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S().
ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S (void)
Definition at line 14951 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S().
ti_sysbios_hal_Hwi_HwiProxy_Params__init__S()
void ti_sysbios_hal_Hwi_HwiProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 14969 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S().
ti_sysbios_hal_Hwi_HwiProxy_post__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_post__E (xdc_UInt intNum)
Definition at line 15023 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S (void)
Definition at line 17197 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S (void)
Definition at line 17201 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_restore__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restore__E (xdc_UInt key)
Definition at line 15011 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E (xdc_UInt intNum, xdc_UInt key)
Definition at line 15047 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_setFunc__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, ti_sysbios_interfaces_IHwi_FuncPtr fxn, xdc_UArg arg)
Definition at line 15065 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id, xdc_Ptr hookContext)
Definition at line 15077 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_startup__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_startup__E (void)
Definition at line 14993 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E (void)
Definition at line 15017 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_initStack()
xdc_Void ti_sysbios_hal_Hwi_initStack (xdc_Void)
ti_sysbios_hal_Hwi_Module__startupDone__F()
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__F (void)
Definition at line 1773 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_hal_Hwi_Module__startupDone__S().
ti_sysbios_hal_Hwi_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__S (void)
Definition at line 16941 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Module__startupDone__F().
ti_sysbios_hal_Hwi_Module_startup__E()
xdc_Int ti_sysbios_hal_Hwi_Module_startup__E (xdc_Int)
ti_sysbios_hal_Hwi_Object__create__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 17000 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_Object__delete__S()
xdc_Void ti_sysbios_hal_Hwi_Object__delete__S (xdc_Ptr instp)
Definition at line 17076 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
Referenced by ti_sysbios_hal_Hwi_delete().
ti_sysbios_hal_Hwi_Object__first__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__first__S (void)
Definition at line 16974 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Module__::link, and ti_sysbios_hal_Hwi_Module__root__V.
ti_sysbios_hal_Hwi_Object__get__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 16963 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__table__C.
ti_sysbios_hal_Hwi_Object__next__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__next__S (xdc_Ptr obj)
Definition at line 16987 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Module__::link, and ti_sysbios_hal_Hwi_Module__root__V.
ti_sysbios_hal_Hwi_Params__init__S()
xdc_Void ti_sysbios_hal_Hwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 16957 of file mss_mrr_per4f.c.
References ti_sysbios_hal_Hwi_Object__PARAMS__C.
ti_sysbios_heaps_HeapBuf_construct()
void ti_sysbios_heaps_HeapBuf_construct (ti_sysbios_heaps_HeapBuf_Struct * __obj, const ti_sysbios_heaps_HeapBuf_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 17428 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__DESC__C.
ti_sysbios_heaps_HeapBuf_create()
ti_sysbios_heaps_HeapBuf_Handle ti_sysbios_heaps_HeapBuf_create (const ti_sysbios_heaps_HeapBuf_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 17404 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__DESC__C.
ti_sysbios_heaps_HeapBuf_delete()
void ti_sysbios_heaps_HeapBuf_delete (ti_sysbios_heaps_HeapBuf_Handle * instp)
Definition at line 17458 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__delete__S().
ti_sysbios_heaps_HeapBuf_destruct()
void ti_sysbios_heaps_HeapBuf_destruct (ti_sysbios_heaps_HeapBuf_Struct * obj)
Definition at line 17445 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__DESC__C.
ti_sysbios_heaps_HeapBuf_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapBuf_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 17323 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__startupDone__F()
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__F (void)
Definition at line 1761 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_heaps_HeapBuf_Module__startupDone__S().
ti_sysbios_heaps_HeapBuf_Module__startupDone__S()
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__S (void)
Definition at line 17317 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Module__startupDone__F().
ti_sysbios_heaps_HeapBuf_Module_startup__E()
xdc_Int ti_sysbios_heaps_HeapBuf_Module_startup__E (xdc_Int)
ti_sysbios_heaps_HeapBuf_Object__create__S()
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 17376 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__DESC__C.
ti_sysbios_heaps_HeapBuf_Object__delete__S()
xdc_Void ti_sysbios_heaps_HeapBuf_Object__delete__S (xdc_Ptr instp)
Definition at line 17451 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__DESC__C.
Referenced by ti_sysbios_heaps_HeapBuf_delete().
ti_sysbios_heaps_HeapBuf_Object__first__S()
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__first__S (void)
Definition at line 17350 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Module__::link, and ti_sysbios_heaps_HeapBuf_Module__root__V.
ti_sysbios_heaps_HeapBuf_Object__get__S()
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 17339 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Object__next__S()
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__next__S (xdc_Ptr obj)
Definition at line 17363 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Module__::link, and ti_sysbios_heaps_HeapBuf_Module__root__V.
ti_sysbios_heaps_HeapBuf_Params__init__S()
xdc_Void ti_sysbios_heaps_HeapBuf_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 17333 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapBuf_Object__PARAMS__C.
ti_sysbios_heaps_HeapMem_construct()
void ti_sysbios_heaps_HeapMem_construct (ti_sysbios_heaps_HeapMem_Struct * __obj, const ti_sysbios_heaps_HeapMem_Params * __paramsPtr)
Definition at line 17672 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
ti_sysbios_heaps_HeapMem_create()
ti_sysbios_heaps_HeapMem_Handle ti_sysbios_heaps_HeapMem_create (const ti_sysbios_heaps_HeapMem_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 17654 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
Referenced by xdc_runtime_Memory_HeapProxy_create().
ti_sysbios_heaps_HeapMem_delete()
void ti_sysbios_heaps_HeapMem_delete (ti_sysbios_heaps_HeapMem_Handle * instp)
Definition at line 17697 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__delete__S().
ti_sysbios_heaps_HeapMem_destruct()
void ti_sysbios_heaps_HeapMem_destruct (ti_sysbios_heaps_HeapMem_Struct * obj)
Definition at line 17684 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
ti_sysbios_heaps_HeapMem_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapMem_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 17579 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Memory_HeapProxy_Handle__label__S().
ti_sysbios_heaps_HeapMem_Module__startupDone__S()
xdc_Bool ti_sysbios_heaps_HeapMem_Module__startupDone__S (void)
Definition at line 17573 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Memory_HeapProxy_Module__startupDone__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_create()
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle ti_sysbios_heaps_HeapMem_Module_GateProxy_create (const ti_sysbios_heaps_HeapMem_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15102 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_create().
ti_sysbios_heaps_HeapMem_Module_GateProxy_delete()
void ti_sysbios_heaps_HeapMem_Module_GateProxy_delete (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle * instp)
Definition at line 15108 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E()
xdc_IArg ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst)
Definition at line 15132 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 15120 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Handle__label__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E()
xdc_Void ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 15138 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S (void)
Definition at line 15096 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Module__startupDone__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S()
void ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 15114 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Params__init__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 17811 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 17815 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateMutex_Module__FXNS__C.
ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E()
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 15126 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Object__create__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 17632 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
ti_sysbios_heaps_HeapMem_Object__delete__S()
xdc_Void ti_sysbios_heaps_HeapMem_Object__delete__S (xdc_Ptr instp)
Definition at line 17690 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
Referenced by ti_sysbios_heaps_HeapMem_delete(), and xdc_runtime_Memory_HeapProxy_delete().
ti_sysbios_heaps_HeapMem_Object__first__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__first__S (void)
Definition at line 17606 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Module__::link, and ti_sysbios_heaps_HeapMem_Module__root__V.
ti_sysbios_heaps_HeapMem_Object__get__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 17595 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__table__C.
ti_sysbios_heaps_HeapMem_Object__next__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__next__S (xdc_Ptr obj)
Definition at line 17619 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Module__::link, and ti_sysbios_heaps_HeapMem_Module__root__V.
ti_sysbios_heaps_HeapMem_Params__init__S()
xdc_Void ti_sysbios_heaps_HeapMem_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 17589 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__PARAMS__C.
Referenced by xdc_runtime_Memory_HeapProxy_Params__init__S().
ti_sysbios_knl_Clock_construct()
void ti_sysbios_knl_Clock_construct (ti_sysbios_knl_Clock_Struct * __obj, ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params * __paramsPtr)
Definition at line 18031 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_create()
ti_sysbios_knl_Clock_Handle ti_sysbios_knl_Clock_create (ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 18013 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_delete()
void ti_sysbios_knl_Clock_delete (ti_sysbios_knl_Clock_Handle * instp)
Definition at line 18056 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__delete__S().
ti_sysbios_knl_Clock_destruct()
void ti_sysbios_knl_Clock_destruct (ti_sysbios_knl_Clock_Struct * obj)
Definition at line 18043 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_doTick__I() [1/2]
Void ti_sysbios_knl_Clock_doTick__I (UArg arg)
Definition at line 2191 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Module__state__V.
ti_sysbios_knl_Clock_doTick__I() [2/2]
xdc_Void ti_sysbios_knl_Clock_doTick__I (xdc_UArg)
ti_sysbios_knl_Clock_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Clock_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 17937 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__startupDone__F()
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__F (void)
Definition at line 1749 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Clock_Module__startupDone__S().
ti_sysbios_knl_Clock_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__S (void)
Definition at line 17931 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Module__startupDone__F().
ti_sysbios_knl_Clock_Module_startup__E()
xdc_Int ti_sysbios_knl_Clock_Module_startup__E (xdc_Int)
ti_sysbios_knl_Clock_Object__create__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 17990 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_Object__delete__S()
xdc_Void ti_sysbios_knl_Clock_Object__delete__S (xdc_Ptr instp)
Definition at line 18049 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
Referenced by ti_sysbios_knl_Clock_delete().
ti_sysbios_knl_Clock_Object__first__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__first__S (void)
Definition at line 17964 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Module__::link, and ti_sysbios_knl_Clock_Module__root__V.
ti_sysbios_knl_Clock_Object__get__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 17953 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Object__next__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__next__S (xdc_Ptr obj)
Definition at line 17977 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Module__::link, and ti_sysbios_knl_Clock_Module__root__V.
ti_sysbios_knl_Clock_Params__init__S()
xdc_Void ti_sysbios_knl_Clock_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 17947 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Clock_Object__PARAMS__C.
ti_sysbios_knl_Clock_TimerProxy_create()
ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_TimerProxy_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_knl_Clock_TimerProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15157 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_create().
ti_sysbios_knl_Clock_TimerProxy_delete()
void ti_sysbios_knl_Clock_TimerProxy_delete (ti_sysbios_knl_Clock_TimerProxy_Handle * instp)
Definition at line 15163 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__delete__S().
ti_sysbios_knl_Clock_TimerProxy_getCount__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCount__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 15241 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_Bool save)
Definition at line 15283 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 15271 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 tickPeriod)
Definition at line 15277 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getFreq__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_getFreq__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_runtime_Types_FreqHz * freq)
Definition at line 15247 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getFunc__E()
ti_sysbios_interfaces_ITimer_FuncPtr ti_sysbios_knl_Clock_TimerProxy_getFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UArg * arg)
Definition at line 15253 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 15199 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E()
xdc_UInt ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E (void)
Definition at line 15181 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getPeriod__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 15235 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_getStatus__E()
ti_sysbios_interfaces_ITimer_Status ti_sysbios_knl_Clock_TimerProxy_getStatus__E (xdc_UInt id)
Definition at line 15187 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Clock_TimerProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 15175 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Handle__label__S().
ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S (void)
Definition at line 15151 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__S().
ti_sysbios_knl_Clock_TimerProxy_Params__init__S()
void ti_sysbios_knl_Clock_TimerProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 15169 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Params__init__S().
ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S (void)
Definition at line 18170 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S (void)
Definition at line 18174 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_setFunc__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, ti_sysbios_interfaces_ITimer_FuncPtr fxn, xdc_UArg arg)
Definition at line 15259 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_setNextTick__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setNextTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 ticks)
Definition at line 15205 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_setPeriod__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 period)
Definition at line 15223 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E()
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 microsecs)
Definition at line 15229 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_start__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_start__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 15211 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_startup__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_startup__E (void)
Definition at line 15193 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_stop__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_stop__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 15217 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_trigger__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_trigger__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 cycles)
Definition at line 15265 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_construct()
void ti_sysbios_knl_Event_construct (ti_sysbios_knl_Event_Struct * __obj, const ti_sysbios_knl_Event_Params * __paramsPtr)
Definition at line 18389 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_create()
ti_sysbios_knl_Event_Handle ti_sysbios_knl_Event_create (const ti_sysbios_knl_Event_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 18371 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_delete()
void ti_sysbios_knl_Event_delete (ti_sysbios_knl_Event_Handle * instp)
Definition at line 18414 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__delete__S().
ti_sysbios_knl_Event_destruct()
void ti_sysbios_knl_Event_destruct (ti_sysbios_knl_Event_Struct * obj)
Definition at line 18401 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Event_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 18296 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Event_Module__startupDone__S (void)
Definition at line 18290 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Object__create__S()
xdc_Ptr ti_sysbios_knl_Event_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 18349 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_Object__delete__S()
xdc_Void ti_sysbios_knl_Event_Object__delete__S (xdc_Ptr instp)
Definition at line 18407 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__DESC__C.
Referenced by ti_sysbios_knl_Event_delete().
ti_sysbios_knl_Event_Object__first__S()
xdc_Ptr ti_sysbios_knl_Event_Object__first__S (void)
Definition at line 18323 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Module__::link, and ti_sysbios_knl_Event_Module__root__V.
ti_sysbios_knl_Event_Object__get__S()
xdc_Ptr ti_sysbios_knl_Event_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 18312 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Object__next__S()
xdc_Ptr ti_sysbios_knl_Event_Object__next__S (xdc_Ptr obj)
Definition at line 18336 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Module__::link, and ti_sysbios_knl_Event_Module__root__V.
ti_sysbios_knl_Event_Params__init__S()
xdc_Void ti_sysbios_knl_Event_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 18306 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Event_Object__PARAMS__C.
ti_sysbios_knl_Idle_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Idle_Module__startupDone__S (void)
Definition at line 18425 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Intrinsics_Module__startupDone__S (void)
Definition at line 18437 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E()
xdc_UInt ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E (xdc_UInt bits)
Definition at line 15302 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S (void)
Definition at line 15296 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S().
ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S (void)
Definition at line 18449 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S (void)
Definition at line 18453 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_construct()
void ti_sysbios_knl_Queue_construct (ti_sysbios_knl_Queue_Struct * __obj, const ti_sysbios_knl_Queue_Params * __paramsPtr)
Definition at line 18667 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_create()
ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Queue_create (const ti_sysbios_knl_Queue_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 18649 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_delete()
void ti_sysbios_knl_Queue_delete (ti_sysbios_knl_Queue_Handle * instp)
Definition at line 18692 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__delete__S().
ti_sysbios_knl_Queue_destruct()
void ti_sysbios_knl_Queue_destruct (ti_sysbios_knl_Queue_Struct * obj)
Definition at line 18679 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Queue_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 18574 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Queue_Module__startupDone__S (void)
Definition at line 18568 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Object__create__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 18627 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_Object__delete__S()
xdc_Void ti_sysbios_knl_Queue_Object__delete__S (xdc_Ptr instp)
Definition at line 18685 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
Referenced by ti_sysbios_knl_Queue_delete().
ti_sysbios_knl_Queue_Object__first__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__first__S (void)
Definition at line 18601 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Module__::link, and ti_sysbios_knl_Queue_Module__root__V.
ti_sysbios_knl_Queue_Object__get__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 18590 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Object__next__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__next__S (xdc_Ptr obj)
Definition at line 18614 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Module__::link, and ti_sysbios_knl_Queue_Module__root__V.
ti_sysbios_knl_Queue_Params__init__S()
xdc_Void ti_sysbios_knl_Queue_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 18584 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Queue_Object__PARAMS__C.
ti_sysbios_knl_Semaphore_construct()
void ti_sysbios_knl_Semaphore_construct (ti_sysbios_knl_Semaphore_Struct * __obj, xdc_Int count, const ti_sysbios_knl_Semaphore_Params * __paramsPtr)
Definition at line 18907 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_create()
ti_sysbios_knl_Semaphore_Handle ti_sysbios_knl_Semaphore_create (xdc_Int count, const ti_sysbios_knl_Semaphore_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 18889 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_delete()
void ti_sysbios_knl_Semaphore_delete (ti_sysbios_knl_Semaphore_Handle * instp)
Definition at line 18932 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__delete__S().
ti_sysbios_knl_Semaphore_destruct()
void ti_sysbios_knl_Semaphore_destruct (ti_sysbios_knl_Semaphore_Struct * obj)
Definition at line 18919 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Semaphore_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 18813 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Semaphore_Module__startupDone__S (void)
Definition at line 18807 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Object__create__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 18866 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_Object__delete__S()
xdc_Void ti_sysbios_knl_Semaphore_Object__delete__S (xdc_Ptr instp)
Definition at line 18925 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
Referenced by ti_sysbios_knl_Semaphore_delete().
ti_sysbios_knl_Semaphore_Object__first__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__first__S (void)
Definition at line 18840 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Module__::link, and ti_sysbios_knl_Semaphore_Module__root__V.
ti_sysbios_knl_Semaphore_Object__get__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 18829 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Object__next__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__next__S (xdc_Ptr obj)
Definition at line 18853 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Module__::link, and ti_sysbios_knl_Semaphore_Module__root__V.
ti_sysbios_knl_Semaphore_Params__init__S()
xdc_Void ti_sysbios_knl_Semaphore_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 18823 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Semaphore_Object__PARAMS__C.
ti_sysbios_knl_Swi_construct()
void ti_sysbios_knl_Swi_construct (ti_sysbios_knl_Swi_Struct * __obj, ti_sysbios_knl_Swi_FuncPtr swiFxn, const ti_sysbios_knl_Swi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 19159 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__DESC__C.
ti_sysbios_knl_Swi_create()
ti_sysbios_knl_Swi_Handle ti_sysbios_knl_Swi_create (ti_sysbios_knl_Swi_FuncPtr swiFxn, const ti_sysbios_knl_Swi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 19135 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__DESC__C.
ti_sysbios_knl_Swi_delete()
void ti_sysbios_knl_Swi_delete (ti_sysbios_knl_Swi_Handle * instp)
Definition at line 19189 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__delete__S().
ti_sysbios_knl_Swi_destruct()
void ti_sysbios_knl_Swi_destruct (ti_sysbios_knl_Swi_Struct * obj)
Definition at line 19176 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__DESC__C.
ti_sysbios_knl_Swi_disable__E()
xdc_UInt ti_sysbios_knl_Swi_disable__E (xdc_Void)
ti_sysbios_knl_Swi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Swi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 19053 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__startupDone__F()
xdc_Bool ti_sysbios_knl_Swi_Module__startupDone__F (void)
Definition at line 1753 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Swi_Module__startupDone__S().
ti_sysbios_knl_Swi_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Swi_Module__startupDone__S (void)
Definition at line 19047 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Module__startupDone__F().
ti_sysbios_knl_Swi_Module_startup__E()
xdc_Int ti_sysbios_knl_Swi_Module_startup__E (xdc_Int)
ti_sysbios_knl_Swi_Object__create__S()
xdc_Ptr ti_sysbios_knl_Swi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 19106 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__DESC__C.
ti_sysbios_knl_Swi_Object__delete__S()
xdc_Void ti_sysbios_knl_Swi_Object__delete__S (xdc_Ptr instp)
Definition at line 19182 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__DESC__C.
Referenced by ti_sysbios_knl_Swi_delete().
ti_sysbios_knl_Swi_Object__first__S()
xdc_Ptr ti_sysbios_knl_Swi_Object__first__S (void)
Definition at line 19080 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Module__::link, and ti_sysbios_knl_Swi_Module__root__V.
ti_sysbios_knl_Swi_Object__get__S()
xdc_Ptr ti_sysbios_knl_Swi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 19069 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__table__C.
ti_sysbios_knl_Swi_Object__next__S()
xdc_Ptr ti_sysbios_knl_Swi_Object__next__S (xdc_Ptr obj)
Definition at line 19093 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Module__::link, and ti_sysbios_knl_Swi_Module__root__V.
ti_sysbios_knl_Swi_Params__init__S()
xdc_Void ti_sysbios_knl_Swi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 19063 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Swi_Object__PARAMS__C.
ti_sysbios_knl_Swi_restoreHwi__E()
xdc_Void ti_sysbios_knl_Swi_restoreHwi__E (xdc_UInt)
ti_sysbios_knl_Task_construct()
void ti_sysbios_knl_Task_construct (ti_sysbios_knl_Task_Struct * __obj, ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 19416 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_create()
ti_sysbios_knl_Task_Handle ti_sysbios_knl_Task_create (ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 19392 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_delete()
void ti_sysbios_knl_Task_delete (ti_sysbios_knl_Task_Handle * instp)
Definition at line 19446 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__delete__S().
ti_sysbios_knl_Task_destruct()
void ti_sysbios_knl_Task_destruct (ti_sysbios_knl_Task_Struct * obj)
Definition at line 19433 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_disable__E()
xdc_UInt ti_sysbios_knl_Task_disable__E (xdc_Void)
ti_sysbios_knl_Task_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Task_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 19310 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__startupDone__F()
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__F (void)
Definition at line 1757 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Task_Module__startupDone__S().
ti_sysbios_knl_Task_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__S (void)
Definition at line 19304 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Module__startupDone__F().
ti_sysbios_knl_Task_Module_startup__E()
xdc_Int ti_sysbios_knl_Task_Module_startup__E (xdc_Int)
ti_sysbios_knl_Task_Object__create__S()
xdc_Ptr ti_sysbios_knl_Task_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 19363 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_Object__delete__S()
xdc_Void ti_sysbios_knl_Task_Object__delete__S (xdc_Ptr instp)
Definition at line 19439 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__DESC__C.
Referenced by ti_sysbios_knl_Task_delete().
ti_sysbios_knl_Task_Object__first__S()
xdc_Ptr ti_sysbios_knl_Task_Object__first__S (void)
Definition at line 19337 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Module__::link, and ti_sysbios_knl_Task_Module__root__V.
ti_sysbios_knl_Task_Object__get__S()
xdc_Ptr ti_sysbios_knl_Task_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 19326 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__table__C.
ti_sysbios_knl_Task_Object__next__S()
xdc_Ptr ti_sysbios_knl_Task_Object__next__S (xdc_Ptr obj)
Definition at line 19350 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Module__::link, and ti_sysbios_knl_Task_Module__root__V.
ti_sysbios_knl_Task_Params__init__S()
xdc_Void ti_sysbios_knl_Task_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 19320 of file mss_mrr_per4f.c.
References ti_sysbios_knl_Task_Object__PARAMS__C.
ti_sysbios_knl_Task_restore__E()
xdc_Void ti_sysbios_knl_Task_restore__E (xdc_UInt)
ti_sysbios_knl_Task_restoreHwi__E()
xdc_Void ti_sysbios_knl_Task_restoreHwi__E (xdc_UInt)
ti_sysbios_knl_Task_SupportProxy_checkStack__E()
xdc_Bool ti_sysbios_knl_Task_SupportProxy_checkStack__E (xdc_Char * stack, xdc_SizeT size)
Definition at line 15333 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E()
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E (void)
Definition at line 15351 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E()
xdc_UInt ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E (void)
Definition at line 15345 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S (void)
Definition at line 15315 of file mss_mrr_per4f.c.
References ti_sysbios_family_arm_TaskSupport_Module__startupDone__S().
ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S (void)
Definition at line 19457 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S (void)
Definition at line 19461 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_stackUsed__E()
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_stackUsed__E (xdc_Char * stack, xdc_SizeT size)
Definition at line 15339 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_start__E()
xdc_Ptr ti_sysbios_knl_Task_SupportProxy_start__E (xdc_Ptr curTask, ti_sysbios_interfaces_ITaskSupport_FuncPtr enterFxn, ti_sysbios_interfaces_ITaskSupport_FuncPtr exitFxn, xdc_runtime_Error_Block * eb)
Definition at line 15321 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_SupportProxy_swap__E()
xdc_Void ti_sysbios_knl_Task_SupportProxy_swap__E (xdc_Ptr * oldtskContext, xdc_Ptr * newtskContext)
Definition at line 15327 of file mss_mrr_per4f.c.
ti_sysbios_rts_MemAlloc_alloc()
static Void* ti_sysbios_rts_MemAlloc_alloc (SizeT size) static
Definition at line 2309 of file mss_mrr_per4f.c.
References Header::actualBuf, Header::header, and Header::size.
Referenced by calloc(), and malloc().
ti_sysbios_timers_rti_Timer_construct()
void ti_sysbios_timers_rti_Timer_construct (ti_sysbios_timers_rti_Timer_Struct * __obj, xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 19688 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
ti_sysbios_timers_rti_Timer_create()
ti_sysbios_timers_rti_Timer_Handle ti_sysbios_timers_rti_Timer_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 19664 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
Referenced by ti_sysbios_knl_Clock_TimerProxy_create().
ti_sysbios_timers_rti_Timer_delete()
void ti_sysbios_timers_rti_Timer_delete (ti_sysbios_timers_rti_Timer_Handle * instp)
Definition at line 19718 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__delete__S().
ti_sysbios_timers_rti_Timer_destruct()
void ti_sysbios_timers_rti_Timer_destruct (ti_sysbios_timers_rti_Timer_Struct * obj)
Definition at line 19705 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
ti_sysbios_timers_rti_Timer_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_timers_rti_Timer_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 19582 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Clock_TimerProxy_Handle__label__S().
ti_sysbios_timers_rti_Timer_Module__startupDone__F()
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__F (void)
Definition at line 1781 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_timers_rti_Timer_Module__startupDone__S().
ti_sysbios_timers_rti_Timer_Module__startupDone__S()
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__S (void)
Definition at line 19576 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__F().
Referenced by ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S().
ti_sysbios_timers_rti_Timer_Module_startup__E()
xdc_Int ti_sysbios_timers_rti_Timer_Module_startup__E (xdc_Int)
ti_sysbios_timers_rti_Timer_Object__create__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 19635 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
ti_sysbios_timers_rti_Timer_Object__delete__S()
xdc_Void ti_sysbios_timers_rti_Timer_Object__delete__S (xdc_Ptr instp)
Definition at line 19711 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
Referenced by ti_sysbios_knl_Clock_TimerProxy_delete(), and ti_sysbios_timers_rti_Timer_delete().
ti_sysbios_timers_rti_Timer_Object__first__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__first__S (void)
Definition at line 19609 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Module__::link, and ti_sysbios_timers_rti_Timer_Module__root__V.
ti_sysbios_timers_rti_Timer_Object__get__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 19598 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__table__C.
ti_sysbios_timers_rti_Timer_Object__next__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__next__S (xdc_Ptr obj)
Definition at line 19622 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Module__::link, and ti_sysbios_timers_rti_Timer_Module__root__V.
ti_sysbios_timers_rti_Timer_Params__init__S()
xdc_Void ti_sysbios_timers_rti_Timer_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 19592 of file mss_mrr_per4f.c.
References ti_sysbios_timers_rti_Timer_Object__PARAMS__C.
Referenced by ti_sysbios_knl_Clock_TimerProxy_Params__init__S().
ti_sysbios_timers_rti_Timer_startup__E()
Void ti_sysbios_timers_rti_Timer_startup__E ()
Referenced by ti_sysbios_BIOS_startFunc__I().
xdc__META() [1/5]
xdc__META (__ASM__)
xdc__META() [2/5]
xdc__META (__ISA__)
xdc__META() [3/5]
xdc__META (__PLAT__)
xdc__META() [4/5]
xdc__META (__TARG__)
xdc__META() [5/5]
xdc__META (__TRDR__)
xdc_runtime_Assert_Module__startupDone__S()
xdc_Bool xdc_runtime_Assert_Module__startupDone__S (void)
Definition at line 19729 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__startupDone__S()
xdc_Bool xdc_runtime_Core_Module__startupDone__S (void)
Definition at line 19741 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__startupDone__S()
xdc_Bool xdc_runtime_Defaults_Module__startupDone__S (void)
Definition at line 19753 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__startupDone__S()
xdc_Bool xdc_runtime_Diags_Module__startupDone__S (void)
Definition at line 19765 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__startupDone__S()
xdc_Bool xdc_runtime_Error_Module__startupDone__S (void)
Definition at line 19777 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__startupDone__S()
xdc_Bool xdc_runtime_Gate_Module__startupDone__S (void)
Definition at line 19789 of file mss_mrr_per4f.c.
xdc_runtime_IGateProvider_create()
xdc_runtime_IGateProvider_Handle xdc_runtime_IGateProvider_create (xdc_runtime_IGateProvider_Module mod, const xdc_runtime_IGateProvider_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15840 of file mss_mrr_per4f.c.
xdc_runtime_IGateProvider_delete()
void xdc_runtime_IGateProvider_delete (xdc_runtime_IGateProvider_Handle * instp)
Definition at line 15846 of file mss_mrr_per4f.c.
xdc_runtime_IHeap_create()
xdc_runtime_IHeap_Handle xdc_runtime_IHeap_create (xdc_runtime_IHeap_Module mod, const xdc_runtime_IHeap_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15823 of file mss_mrr_per4f.c.
xdc_runtime_IHeap_delete()
void xdc_runtime_IHeap_delete (xdc_runtime_IHeap_Handle * instp)
Definition at line 15829 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__startupDone__S()
xdc_Bool xdc_runtime_Log_Module__startupDone__S (void)
Definition at line 19801 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__startupDone__S()
xdc_Bool xdc_runtime_Main_Module__startupDone__S (void)
Definition at line 19813 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module_GateProxy_create()
xdc_runtime_Main_Module_GateProxy_Handle xdc_runtime_Main_Module_GateProxy_create (const xdc_runtime_Main_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15370 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_create().
xdc_runtime_Main_Module_GateProxy_delete()
void xdc_runtime_Main_Module_GateProxy_delete (xdc_runtime_Main_Module_GateProxy_Handle * instp)
Definition at line 15376 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_runtime_Main_Module_GateProxy_enter__E()
xdc_IArg xdc_runtime_Main_Module_GateProxy_enter__E (xdc_runtime_Main_Module_GateProxy_Handle __inst)
Definition at line 15400 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module_GateProxy_Handle__label__S()
xdc_runtime_Types_Label* xdc_runtime_Main_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 15388 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_runtime_Main_Module_GateProxy_leave__E()
xdc_Void xdc_runtime_Main_Module_GateProxy_leave__E (xdc_runtime_Main_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 15406 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module_GateProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_Main_Module_GateProxy_Module__startupDone__S (void)
Definition at line 15364 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
xdc_runtime_Main_Module_GateProxy_Params__init__S()
void xdc_runtime_Main_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 15382 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 19928 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 19932 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_runtime_Main_Module_GateProxy_query__E()
xdc_Bool xdc_runtime_Main_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 15394 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_alloc__E()
xdc_Ptr xdc_runtime_Memory_HeapProxy_alloc__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_SizeT size, xdc_SizeT align, xdc_runtime_Error_Block * eb)
Definition at line 15449 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_create()
xdc_runtime_Memory_HeapProxy_Handle xdc_runtime_Memory_HeapProxy_create (const xdc_runtime_Memory_HeapProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15425 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_create().
xdc_runtime_Memory_HeapProxy_delete()
void xdc_runtime_Memory_HeapProxy_delete (xdc_runtime_Memory_HeapProxy_Handle * instp)
Definition at line 15431 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Object__delete__S().
xdc_runtime_Memory_HeapProxy_free__E()
xdc_Void xdc_runtime_Memory_HeapProxy_free__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_Ptr block, xdc_SizeT size)
Definition at line 15455 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_getStats__E()
xdc_Void xdc_runtime_Memory_HeapProxy_getStats__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_runtime_Memory_Stats * stats)
Definition at line 15467 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_Handle__label__S()
xdc_runtime_Types_Label* xdc_runtime_Memory_HeapProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 15443 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Handle__label__S().
xdc_runtime_Memory_HeapProxy_isBlocking__E()
xdc_Bool xdc_runtime_Memory_HeapProxy_isBlocking__E (xdc_runtime_Memory_HeapProxy_Handle __inst)
Definition at line 15461 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_Memory_HeapProxy_Module__startupDone__S (void)
Definition at line 15419 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Module__startupDone__S().
xdc_runtime_Memory_HeapProxy_Params__init__S()
void xdc_runtime_Memory_HeapProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 15437 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Params__init__S().
xdc_runtime_Memory_HeapProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_Memory_HeapProxy_Proxy__abstract__S (void)
Definition at line 20059 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_Memory_HeapProxy_Proxy__delegate__S (void)
Definition at line 20063 of file mss_mrr_per4f.c.
References ti_sysbios_heaps_HeapMem_Module__FXNS__C.
xdc_runtime_Memory_Module__startupDone__S()
xdc_Bool xdc_runtime_Memory_Module__startupDone__S (void)
Definition at line 19944 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__startupDone__S()
xdc_Bool xdc_runtime_Registry_Module__startupDone__S (void)
Definition at line 20075 of file mss_mrr_per4f.c.
xdc_runtime_Startup_exec__I()
xdc_Void xdc_runtime_Startup_exec__I (void)
Definition at line 1810 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_startModsFxn__C.
xdc_runtime_Startup_Module__startupDone__S()
xdc_Bool xdc_runtime_Startup_Module__startupDone__S (void)
Definition at line 20087 of file mss_mrr_per4f.c.
xdc_runtime_Startup_reset__I()
xdc_Void xdc_runtime_Startup_reset__I (void)
Definition at line 1847 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__startupDone__S()
xdc_Bool xdc_runtime_SysStd_Module__startupDone__S (void)
Definition at line 20099 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_System_SupportProxy_Module__startupDone__S().
xdc_runtime_System_aprintf__E()
xdc_Int xdc_runtime_System_aprintf__E (xdc_CString fmt, ...)
Definition at line 14707 of file mss_mrr_per4f.c.
xdc_runtime_System_aprintf_va__E()
xdc_Int xdc_runtime_System_aprintf_va__E (xdc_CString fmt, va_list __va)
Definition at line 14701 of file mss_mrr_per4f.c.
xdc_runtime_System_asprintf__E()
xdc_Int xdc_runtime_System_asprintf__E (xdc_Char buf[], xdc_CString fmt, ...)
Definition at line 14743 of file mss_mrr_per4f.c.
xdc_runtime_System_asprintf_va__E()
xdc_Int xdc_runtime_System_asprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
Definition at line 14737 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__startupDone__F()
xdc_Bool xdc_runtime_System_Module__startupDone__F (void)
Definition at line 1745 of file mss_mrr_per4f.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by xdc_runtime_System_Module__startupDone__S().
xdc_runtime_System_Module__startupDone__S()
xdc_Bool xdc_runtime_System_Module__startupDone__S (void)
Definition at line 20111 of file mss_mrr_per4f.c.
References xdc_runtime_System_Module__startupDone__F().
xdc_runtime_System_Module_GateProxy_create()
xdc_runtime_System_Module_GateProxy_Handle xdc_runtime_System_Module_GateProxy_create (const xdc_runtime_System_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 15486 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_create().
xdc_runtime_System_Module_GateProxy_delete()
void xdc_runtime_System_Module_GateProxy_delete (xdc_runtime_System_Module_GateProxy_Handle * instp)
Definition at line 15492 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_runtime_System_Module_GateProxy_enter__E()
xdc_IArg xdc_runtime_System_Module_GateProxy_enter__E (xdc_runtime_System_Module_GateProxy_Handle __inst)
Definition at line 15516 of file mss_mrr_per4f.c.
xdc_runtime_System_Module_GateProxy_Handle__label__S()
xdc_runtime_Types_Label* xdc_runtime_System_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 15504 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_runtime_System_Module_GateProxy_leave__E()
xdc_Void xdc_runtime_System_Module_GateProxy_leave__E (xdc_runtime_System_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 15522 of file mss_mrr_per4f.c.
xdc_runtime_System_Module_GateProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_System_Module_GateProxy_Module__startupDone__S (void)
Definition at line 15480 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
xdc_runtime_System_Module_GateProxy_Params__init__S()
void xdc_runtime_System_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 15498 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_runtime_System_Module_GateProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_System_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 20226 of file mss_mrr_per4f.c.
xdc_runtime_System_Module_GateProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_System_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 20230 of file mss_mrr_per4f.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_runtime_System_Module_GateProxy_query__E()
xdc_Bool xdc_runtime_System_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 15510 of file mss_mrr_per4f.c.
xdc_runtime_System_Module_startup__E()
xdc_Int xdc_runtime_System_Module_startup__E (xdc_Int)
xdc_runtime_System_printf__E()
xdc_Int xdc_runtime_System_printf__E (xdc_CString fmt, ...)
Definition at line 14689 of file mss_mrr_per4f.c.
xdc_runtime_System_printf_va__E()
xdc_Int xdc_runtime_System_printf_va__E (xdc_CString fmt, va_list __va)
Definition at line 14683 of file mss_mrr_per4f.c.
xdc_runtime_System_printfExtend__I()
xdc_Int xdc_runtime_System_printfExtend__I (xdc_Char ** pbuf, xdc_CString * pfmt, xdc_VaList * pva, xdc_runtime_System_ParseData * parse)
Definition at line 1876 of file mss_mrr_per4f.c.
xdc_runtime_System_snprintf__E()
xdc_Int xdc_runtime_System_snprintf__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, ...)
Definition at line 14761 of file mss_mrr_per4f.c.
xdc_runtime_System_snprintf_va__E()
xdc_Int xdc_runtime_System_snprintf_va__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, va_list __va)
Definition at line 14755 of file mss_mrr_per4f.c.
xdc_runtime_System_sprintf__E()
xdc_Int xdc_runtime_System_sprintf__E (xdc_Char buf[], xdc_CString fmt, ...)
Definition at line 14725 of file mss_mrr_per4f.c.
xdc_runtime_System_sprintf_va__E()
xdc_Int xdc_runtime_System_sprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
Definition at line 14719 of file mss_mrr_per4f.c.
xdc_runtime_System_SupportProxy_abort__E()
xdc_Void xdc_runtime_System_SupportProxy_abort__E (xdc_CString str)
Definition at line 15541 of file mss_mrr_per4f.c.
xdc_runtime_System_SupportProxy_exit__E()
xdc_Void xdc_runtime_System_SupportProxy_exit__E (xdc_Int stat)
Definition at line 15547 of file mss_mrr_per4f.c.
xdc_runtime_System_SupportProxy_flush__E()
xdc_Void xdc_runtime_System_SupportProxy_flush__E (void)
Definition at line 15553 of file mss_mrr_per4f.c.
xdc_runtime_System_SupportProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_System_SupportProxy_Module__startupDone__S (void)
Definition at line 15535 of file mss_mrr_per4f.c.
References xdc_runtime_SysStd_Module__startupDone__S().
xdc_runtime_System_SupportProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_System_SupportProxy_Proxy__abstract__S (void)
Definition at line 20242 of file mss_mrr_per4f.c.
xdc_runtime_System_SupportProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_System_SupportProxy_Proxy__delegate__S (void)
Definition at line 20246 of file mss_mrr_per4f.c.
References xdc_runtime_SysStd_Module__FXNS__C.
xdc_runtime_System_SupportProxy_putch__E()
xdc_Void xdc_runtime_System_SupportProxy_putch__E (xdc_Char ch)
Definition at line 15559 of file mss_mrr_per4f.c.
xdc_runtime_System_SupportProxy_ready__E()
xdc_Bool xdc_runtime_System_SupportProxy_ready__E (void)
Definition at line 15565 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__startupDone__S()
xdc_Bool xdc_runtime_Text_Module__startupDone__S (void)
Definition at line 20257 of file mss_mrr_per4f.c.
xdc_runtime_Text_visitRope__I()
void xdc_runtime_Text_visitRope__I (xdc_runtime_Text_RopeId rope, xdc_Fxn visFxn, xdc_Ptr visState)
Definition at line 2036 of file mss_mrr_per4f.c.
Variable Documentation
__TI_STACK_BASE
void* __TI_STACK_BASE
__TI_STACK_SIZE
void* __TI_STACK_SIZE
__xdc__init__addr
__FAR__ int(* volatile __xdc__init__addr) (void) = &__xdc__init
Definition at line 20278 of file mss_mrr_per4f.c.
heap0
const ti_sysbios_heaps_HeapMem_Handle heap0 = (ti_sysbios_heaps_HeapMem_Handle)((ti_sysbios_heaps_HeapMem_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0])
Definition at line 20294 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_clockEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_clockEnabled ti_sysbios_BIOS_clockEnabled__C = 1
Definition at line 2629 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_cpuFreq__C
const __FAR__ CT__ti_sysbios_BIOS_cpuFreq ti_sysbios_BIOS_cpuFreq__C
Initial value:
= {
    (xdc_Bits32)0x0,
    (xdc_Bits32)0xbebc200,
}
Definition at line 2610 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_defaultKernelHeapInstance__C
const __FAR__ CT__ti_sysbios_BIOS_defaultKernelHeapInstance ti_sysbios_BIOS_defaultKernelHeapInstance__C = 0
Definition at line 2633 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_heapSection__C
const __FAR__ CT__ti_sysbios_BIOS_heapSection ti_sysbios_BIOS_heapSection__C = 0
Definition at line 2649 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_heapSize__C
const __FAR__ CT__ti_sysbios_BIOS_heapSize ti_sysbios_BIOS_heapSize__C = (xdc_SizeT)0x1000
Definition at line 2645 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_heapTrackEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_heapTrackEnabled ti_sysbios_BIOS_heapTrackEnabled__C = 0
Definition at line 2653 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_installedErrorHook__C
const __FAR__ CT__ti_sysbios_BIOS_installedErrorHook ti_sysbios_BIOS_installedErrorHook__C = ((CT__ti_sysbios_BIOS_installedErrorHook)((xdc_Fxn)xdc_runtime_Error_print__E))
Definition at line 2665 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_kernelHeapSection__C
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSection ti_sysbios_BIOS_kernelHeapSection__C = ".kernel_heap"
Definition at line 2641 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_kernelHeapSize__C
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSize ti_sysbios_BIOS_kernelHeapSize__C = (xdc_SizeT)0x1000
Definition at line 2637 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsEnabled ti_sysbios_BIOS_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2534 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsIncluded ti_sysbios_BIOS_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2538 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsMask ti_sysbios_BIOS_Module__diagsMask__C = ((CT__ti_sysbios_BIOS_Module__diagsMask)0)
Definition at line 2542 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__gateObj__C
const __FAR__ CT__ti_sysbios_BIOS_Module__gateObj ti_sysbios_BIOS_Module__gateObj__C = ((CT__ti_sysbios_BIOS_Module__gateObj)0)
Definition at line 2546 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_BIOS_Module__gatePrms ti_sysbios_BIOS_Module__gatePrms__C = ((CT__ti_sysbios_BIOS_Module__gatePrms)0)
Definition at line 2550 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__id__C
const __FAR__ CT__ti_sysbios_BIOS_Module__id ti_sysbios_BIOS_Module__id__C = (xdc_Bits16)0x8015
Definition at line 2554 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerDefined ti_sysbios_BIOS_Module__loggerDefined__C = 0
Definition at line 2558 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn0 ti_sysbios_BIOS_Module__loggerFxn0__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn0)0)
Definition at line 2566 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn1 ti_sysbios_BIOS_Module__loggerFxn1__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn1)0)
Definition at line 2570 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn2 ti_sysbios_BIOS_Module__loggerFxn2__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn2)0)
Definition at line 2574 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn4 ti_sysbios_BIOS_Module__loggerFxn4__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn4)0)
Definition at line 2578 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn8 ti_sysbios_BIOS_Module__loggerFxn8__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn8)0)
Definition at line 2582 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerObj ti_sysbios_BIOS_Module__loggerObj__C = ((CT__ti_sysbios_BIOS_Module__loggerObj)0)
Definition at line 2562 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Module__state__V
ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module__state__V
Initial value:
= {
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
    (xdc_UInt)0x0,
    ((xdc_IArg)(0x0)),
    (ti_sysbios_BIOS_RtsGateProxy_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[1],
    ti_sysbios_BIOS_ThreadType_Main,
    ((void*)0),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_BIOS_startFunc)),
    ((xdc_Void(*)(xdc_Int))((xdc_Fxn)ti_sysbios_BIOS_exitFunc)),
}
Definition at line 981 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_BIOS_atExitFunc__I(), ti_sysbios_BIOS_registerRTSLock(), ti_sysbios_BIOS_removeRTSLock(), ti_sysbios_BIOS_rtsLock(), and ti_sysbios_BIOS_rtsUnlock().
ti_sysbios_BIOS_mpeEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_mpeEnabled ti_sysbios_BIOS_mpeEnabled__C = 0
Definition at line 2606 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Object__count__C
const __FAR__ CT__ti_sysbios_BIOS_Object__count ti_sysbios_BIOS_Object__count__C = 0
Definition at line 2586 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Object__heap__C
const __FAR__ CT__ti_sysbios_BIOS_Object__heap ti_sysbios_BIOS_Object__heap__C = 0
Definition at line 2590 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Object__sizeof__C
const __FAR__ CT__ti_sysbios_BIOS_Object__sizeof ti_sysbios_BIOS_Object__sizeof__C = 0
Definition at line 2594 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_Object__table__C
const __FAR__ CT__ti_sysbios_BIOS_Object__table ti_sysbios_BIOS_Object__table__C = 0
Definition at line 2598 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_BIOS_runtimeCreatesEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_runtimeCreatesEnabled ti_sysbios_BIOS_runtimeCreatesEnabled__C = 1
Definition at line 2617 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_setupSecureContext__C
const __FAR__ CT__ti_sysbios_BIOS_setupSecureContext ti_sysbios_BIOS_setupSecureContext__C = 0
Definition at line 2657 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_smpEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_smpEnabled ti_sysbios_BIOS_smpEnabled__C = 0
Definition at line 2602 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_swiEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_swiEnabled ti_sysbios_BIOS_swiEnabled__C = 1
Definition at line 2625 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_taskEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_taskEnabled ti_sysbios_BIOS_taskEnabled__C = 1
Definition at line 2621 of file mss_mrr_per4f.c.
ti_sysbios_BIOS_useSK__C
const __FAR__ CT__ti_sysbios_BIOS_useSK ti_sysbios_BIOS_useSK__C = 0
Definition at line 2661 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_E_dataAbort__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_dataAbort ti_sysbios_family_arm_exc_Exception_E_dataAbort__C = (((xdc_runtime_Error_Id)4890) << 16 | 0)
Definition at line 2957 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_E_prefetchAbort__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_prefetchAbort ti_sysbios_family_arm_exc_Exception_E_prefetchAbort__C = (((xdc_runtime_Error_Id)4847) << 16 | 0)
Definition at line 2953 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_E_swi__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_swi ti_sysbios_family_arm_exc_Exception_E_swi__C = (((xdc_runtime_Error_Id)4814) << 16 | 0)
Definition at line 2949 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction__C = (((xdc_runtime_Error_Id)4929) << 16 | 0)
Definition at line 2961 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_enableDecode__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_enableDecode ti_sysbios_family_arm_exc_Exception_enableDecode__C = 1
Definition at line 2965 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_excHookFunc__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_excHookFunc ti_sysbios_family_arm_exc_Exception_excHookFunc__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFunc)0)
Definition at line 2969 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_excHookFuncs__A
const __T1_ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__A
Initial value:
= {
    ((xdc_Void(*)(ti_sysbios_family_arm_exc_Exception_ExcContext*))0),
}
Definition at line 1042 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_excHookFuncs__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs)ti_sysbios_family_arm_exc_Exception_excHookFuncs__A)
Definition at line 2973 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2881 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2885 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask ti_sysbios_family_arm_exc_Exception_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask)0)
Definition at line 2889 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj ti_sysbios_family_arm_exc_Exception_Module__gateObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj)0)
Definition at line 2893 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms ti_sysbios_family_arm_exc_Exception_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms)0)
Definition at line 2897 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__id__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__id ti_sysbios_family_arm_exc_Exception_Module__id__C = (xdc_Bits16)0x8026
Definition at line 2901 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerDefined ti_sysbios_family_arm_exc_Exception_Module__loggerDefined__C = 0
Definition at line 2905 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0)0)
Definition at line 2913 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1)0)
Definition at line 2917 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2)0)
Definition at line 2921 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4)0)
Definition at line 2925 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8)0)
Definition at line 2929 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj ti_sysbios_family_arm_exc_Exception_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj)0)
Definition at line 2909 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module__state__V
ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module__state__V
Initial value:
= {
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A),
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A),
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A),
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A),
    (xdc_SizeT)0x1000,
}
Definition at line 1039 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excActive ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A
Initial value:
= {
    0,
}
Definition at line 1013 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excContext ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A
Initial value:
= {
    ((ti_sysbios_family_arm_exc_Exception_ExcContext*)0),
}
Definition at line 1016 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A
Definition at line 1025 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A
__T2_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A
Initial value:
= {
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A),
}
Definition at line 1036 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStackBuffers ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A
Initial value:
= {
    ((xdc_Ptr)0),
}
Definition at line 1019 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Object__count__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__count ti_sysbios_family_arm_exc_Exception_Object__count__C = 0
Definition at line 2933 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Object__heap__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__heap ti_sysbios_family_arm_exc_Exception_Object__heap__C = 0
Definition at line 2937 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__sizeof ti_sysbios_family_arm_exc_Exception_Object__sizeof__C = 0
Definition at line 2941 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_exc_Exception_Object__table__C
const __FAR__ CT__ti_sysbios_family_arm_exc_Exception_Object__table ti_sysbios_family_arm_exc_Exception_Object__table__C = 0
Definition at line 2945 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2679 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2683 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask)0)
Definition at line 2687 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj)0)
Definition at line 2691 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms)0)
Definition at line 2695 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__id__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__id ti_sysbios_family_arm_IntrinsicsSupport_Module__id__C = (xdc_Bits16)0x8013
Definition at line 2699 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined__C = 0
Definition at line 2703 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0)0)
Definition at line 2711 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1)0)
Definition at line 2715 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2)0)
Definition at line 2719 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4)0)
Definition at line 2723 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8)0)
Definition at line 2727 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj)0)
Definition at line 2707 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Object__count__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__count ti_sysbios_family_arm_IntrinsicsSupport_Object__count__C = 0
Definition at line 2731 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Object__heap__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__heap ti_sysbios_family_arm_IntrinsicsSupport_Object__heap__C = 0
Definition at line 2735 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof__C = 0
Definition at line 2739 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_IntrinsicsSupport_Object__table__C
const __FAR__ CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__table ti_sysbios_family_arm_IntrinsicsSupport_Object__table__C = 0
Definition at line 2743 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_defaultStackSize__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_defaultStackSize ti_sysbios_family_arm_TaskSupport_defaultStackSize__C = (xdc_SizeT)0x800
Definition at line 2820 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2752 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2756 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask ti_sysbios_family_arm_TaskSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask)0)
Definition at line 2760 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj ti_sysbios_family_arm_TaskSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj)0)
Definition at line 2764 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms ti_sysbios_family_arm_TaskSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms)0)
Definition at line 2768 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__id__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__id ti_sysbios_family_arm_TaskSupport_Module__id__C = (xdc_Bits16)0x8014
Definition at line 2772 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerDefined ti_sysbios_family_arm_TaskSupport_Module__loggerDefined__C = 0
Definition at line 2776 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0)0)
Definition at line 2784 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1)0)
Definition at line 2788 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2)0)
Definition at line 2792 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4)0)
Definition at line 2796 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8)0)
Definition at line 2800 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj ti_sysbios_family_arm_TaskSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj)0)
Definition at line 2780 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Object__count__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__count ti_sysbios_family_arm_TaskSupport_Object__count__C = 0
Definition at line 2804 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Object__heap__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__heap ti_sysbios_family_arm_TaskSupport_Object__heap__C = 0
Definition at line 2808 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__sizeof ti_sysbios_family_arm_TaskSupport_Object__sizeof__C = 0
Definition at line 2812 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_Object__table__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_Object__table ti_sysbios_family_arm_TaskSupport_Object__table__C = 0
Definition at line 2816 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_TaskSupport_stackAlignment__C
const __FAR__ CT__ti_sysbios_family_arm_TaskSupport_stackAlignment ti_sysbios_family_arm_TaskSupport_stackAlignment__C = (xdc_UInt)0x8
Definition at line 2824 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds__C = (((xdc_runtime_Error_Id)5058) << 16 | 0)
Definition at line 3054 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_id__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_id ti_sysbios_family_arm_v7r_tms570_Core_id__C = (xdc_UInt)0x0
Definition at line 3058 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2982 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2986 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask)0)
Definition at line 2990 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj)0)
Definition at line 2994 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms)0)
Definition at line 2998 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__id__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__id ti_sysbios_family_arm_v7r_tms570_Core_Module__id__C = (xdc_Bits16)0x8030
Definition at line 3002 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined__C = 0
Definition at line 3006 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0)0)
Definition at line 3014 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1)0)
Definition at line 3018 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2)0)
Definition at line 3022 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4)0)
Definition at line 3026 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8)0)
Definition at line 3030 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj)0)
Definition at line 3010 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_numCores__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_numCores ti_sysbios_family_arm_v7r_tms570_Core_numCores__C = (xdc_UInt)0x1
Definition at line 3050 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Object__count__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__count ti_sysbios_family_arm_v7r_tms570_Core_Object__count__C = 0
Definition at line 3034 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Object__heap__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__heap ti_sysbios_family_arm_v7r_tms570_Core_Object__heap__C = 0
Definition at line 3038 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof__C = 0
Definition at line 3042 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_tms570_Core_Object__table__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__table ti_sysbios_family_arm_v7r_tms570_Core_Object__table__C = 0
Definition at line 3046 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId__C = (((xdc_runtime_Assert_Id)2825) << 16 | 16)
Definition at line 3541 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A
Definition at line 1106 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap)ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A)
Definition at line 3573 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress)(0x0))
Definition at line 3517 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress)(0x0))
Definition at line 3521 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport__C = 1
Definition at line 3497 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport__C = 1
Definition at line 3509 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport__C = 1
Definition at line 3501 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport__C = 1
Definition at line 3505 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined__C = (((xdc_runtime_Error_Id)4570) << 16 | 0)
Definition at line 3545 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum__C = (((xdc_runtime_Error_Id)4618) << 16 | 0)
Definition at line 3549 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt__C = (((xdc_runtime_Error_Id)4760) << 16 | 0)
Definition at line 3561 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined__C = (((xdc_runtime_Error_Id)4658) << 16 | 0)
Definition at line 3553 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption__C = (((xdc_runtime_Error_Id)4697) << 16 | 0)
Definition at line 3557 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm__C = 1
Definition at line 3533 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack)0)
Definition at line 3529 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_hooks__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_hooks ti_sysbios_family_arm_v7r_vim_Hwi_hooks__C = {0, 0}
Definition at line 3601 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A
Initial value:
= {
    (xdc_UInt32)0x4,
    (xdc_UInt32)0x0,
    (xdc_UInt32)0x0,
    (xdc_UInt32)0x0,
}
Definition at line 1109 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A)
Definition at line 3577 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_LD_end__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_LD_end ti_sysbios_family_arm_v7r_vim_Hwi_LD_end__C = (((xdc_runtime_Log_Event)6499) << 16 | 512)
Definition at line 3569 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin__C = (((xdc_runtime_Log_Event)6429) << 16 | 768)
Definition at line 3565 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3429 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3433 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask)0)
Definition at line 3437 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj)0)
Definition at line 3441 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms)0)
Definition at line 3445 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__id ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C = (xdc_Bits16)0x8024
Definition at line 3449 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C = 0
Definition at line 3453 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0)0)
Definition at line 3461 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1)0)
Definition at line 3465 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2)0)
Definition at line 3469 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4)0)
Definition at line 3473 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8)0)
Definition at line 3477 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj)0)
Definition at line 3457 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V
ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.link,
    &ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.link},
}
Definition at line 3088 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_Object__first__S(), and ti_sysbios_family_arm_v7r_vim_Hwi_Object__next__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Module__state__V
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__state__V
Initial value:
= {
    ((xdc_Char*)0),
    ((xdc_Char*)0),
    ((xdc_Ptr)((void*)&__TI_STACK_BASE)),
    ((xdc_Ptr)((void*)&__TI_STACK_SIZE)),
    ((void*)ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A),
    (xdc_SizeT)0x800,
    ((xdc_UInt*)(0xfff82000)),
    ((void*)ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A),
    {
        (xdc_UInt)0xffffffff,
        (xdc_UInt)0xffffffff,
        (xdc_UInt)0xffffffff,
        (xdc_UInt)0xffffffff,
    },
    (xdc_UInt)0x0,
}
Definition at line 1103 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__dispatchTable ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A
Definition at line 1100 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A
Definition at line 1081 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS__C = (xdc_UInt)0x80
Definition at line 3513 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__count__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__count ti_sysbios_family_arm_v7r_vim_Hwi_Object__count__C = 1
Definition at line 3481 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.link,
    sizeof(ti_sysbios_family_arm_v7r_vim_Hwi___S1) - sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object2__),
    (xdc_CPtr)&ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C,
    sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Params),
}
Definition at line 3066 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_construct(), ti_sysbios_family_arm_v7r_vim_Hwi_create(), ti_sysbios_family_arm_v7r_vim_Hwi_destruct(), ti_sysbios_family_arm_v7r_vim_Hwi_Object__create__S(), and ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap__C = 0
Definition at line 3485 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C
const __FAR__ ti_sysbios_family_arm_v7r_vim_Hwi_Params ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_family_arm_v7r_vim_Hwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_IHwi_MaskingOption_LOWER,
    ((xdc_UArg)(0x0)),
    1,
    (xdc_Int)(-0x0 - 1),
    (xdc_Int)(-0x0 - 1),
    ti_sysbios_family_arm_v7r_vim_Hwi_Type_IRQ,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 3070 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof__C = sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object__)
Definition at line 3489 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__table ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__C = ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
Definition at line 3493 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_Object__get__S().
ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
Initial value:
= {
    {
        0,
        ti_sysbios_family_arm_v7r_vim_Hwi_Type_IRQ,
        ((xdc_UArg)((void*)(ti_sysbios_timers_rti_Timer_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0])),
        ((xdc_Void(*)(xdc_UArg))((xdc_Fxn)ti_sysbios_timers_rti_Timer_periodicStub__E)),
        (xdc_Int)0x2,
        ((xdc_UArg)0),
        ((void*)0),
        {
            (xdc_UInt)0x4,
            (xdc_UInt)0x0,
            (xdc_UInt)0x0,
            (xdc_UInt)0x0,
        },
    },
}
Definition at line 1055 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc)((xdc_Fxn)ti_sysbios_family_arm_v7r_vim_Hwi_phantomIntHandler__I))
Definition at line 3525 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM__C = 1
Definition at line 3537 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable)((xdc_Fxn)ti_sysbios_knl_Swi_disable__E))
Definition at line 3585 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Swi_restoreHwi__E))
Definition at line 3589 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
Definition at line 3593 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Task_restoreHwi__E))
Definition at line 3597 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_vectors
const UInt32 ti_sysbios_family_arm_v7r_vim_Hwi_vectors[]
Initial value:
= {
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE51FF1B0),
    (UInt32)(&_c_int00),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I)
}
Definition at line 2231 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A
Initial value:
= {
    (xdc_UInt32)0xffffffff,
    (xdc_UInt32)0xffffffff,
    (xdc_UInt32)0xffffffff,
    (xdc_UInt32)0xffffffff,
}
Definition at line 1112 of file mss_mrr_per4f.c.
ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__C
const __FAR__ CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A)
Definition at line 3581 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsEnabled ti_sysbios_gates_GateHwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3639 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsIncluded ti_sysbios_gates_GateHwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3643 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsMask ti_sysbios_gates_GateHwi_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateHwi_Module__diagsMask)0)
Definition at line 3647 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__FXNS__C
const ti_sysbios_gates_GateHwi_Fxns__ ti_sysbios_gates_GateHwi_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IGateProvider_Interface__BASE__C,
    &ti_sysbios_gates_GateHwi_Module__FXNS__C.__sfxns,
    ti_sysbios_gates_GateHwi_query__E,
    ti_sysbios_gates_GateHwi_enter__E,
    ti_sysbios_gates_GateHwi_leave__E,
    {
        ti_sysbios_gates_GateHwi_Object__create__S,
        ti_sysbios_gates_GateHwi_Object__delete__S,
        ti_sysbios_gates_GateHwi_Handle__label__S,
        0x8028,
    }
}
Definition at line 829 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S(), and xdc_runtime_System_Module_GateProxy_Proxy__delegate__S().
ti_sysbios_gates_GateHwi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gateObj ti_sysbios_gates_GateHwi_Module__gateObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__gateObj)0)
Definition at line 3651 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gatePrms ti_sysbios_gates_GateHwi_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateHwi_Module__gatePrms)0)
Definition at line 3655 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__id__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__id ti_sysbios_gates_GateHwi_Module__id__C = (xdc_Bits16)0x8028
Definition at line 3659 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerDefined ti_sysbios_gates_GateHwi_Module__loggerDefined__C = 0
Definition at line 3663 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0)0)
Definition at line 3671 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1)0)
Definition at line 3675 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2)0)
Definition at line 3679 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4)0)
Definition at line 3683 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8)0)
Definition at line 3687 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerObj ti_sysbios_gates_GateHwi_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerObj)0)
Definition at line 3667 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Module__root__V
ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_gates_GateHwi_Module__root__V.link,
    &ti_sysbios_gates_GateHwi_Module__root__V.link},
}
Definition at line 3625 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateHwi_Object__first__S(), and ti_sysbios_gates_GateHwi_Object__next__S().
ti_sysbios_gates_GateHwi_Object__count__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__count ti_sysbios_gates_GateHwi_Object__count__C = 1
Definition at line 3691 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateHwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_gates_GateHwi_Module__FXNS__C,
    &ti_sysbios_gates_GateHwi_Module__root__V.link,
    sizeof(ti_sysbios_gates_GateHwi___S1) - sizeof(ti_sysbios_gates_GateHwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_gates_GateHwi_Object2__),
    (xdc_CPtr)&ti_sysbios_gates_GateHwi_Object__PARAMS__C,
    sizeof(ti_sysbios_gates_GateHwi_Params),
}
Definition at line 3609 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateHwi_construct(), ti_sysbios_gates_GateHwi_create(), ti_sysbios_gates_GateHwi_destruct(), ti_sysbios_gates_GateHwi_Object__create__S(), and ti_sysbios_gates_GateHwi_Object__delete__S().
ti_sysbios_gates_GateHwi_Object__heap__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__heap ti_sysbios_gates_GateHwi_Object__heap__C = 0
Definition at line 3695 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Object__PARAMS__C
const __FAR__ ti_sysbios_gates_GateHwi_Params ti_sysbios_gates_GateHwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_gates_GateHwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_gates_GateHwi_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 3613 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateHwi_Params__init__S().
ti_sysbios_gates_GateHwi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__sizeof ti_sysbios_gates_GateHwi_Object__sizeof__C = sizeof(ti_sysbios_gates_GateHwi_Object__)
Definition at line 3699 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateHwi_Object__table__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__table ti_sysbios_gates_GateHwi_Object__table__C = ti_sysbios_gates_GateHwi_Object__table__V
Definition at line 3703 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateHwi_Object__get__S().
ti_sysbios_gates_GateHwi_Object__table__V
ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__table__V
Initial value:
= {
    {
        &ti_sysbios_gates_GateHwi_Module__FXNS__C,
    },
}
Definition at line 1132 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_A_badContext__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_A_badContext ti_sysbios_gates_GateMutex_A_badContext__C = (((xdc_runtime_Assert_Id)3349) << 16 | 16)
Definition at line 3838 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Instance_State_sem__O
const __FAR__ xdc_SizeT ti_sysbios_gates_GateMutex_Instance_State_sem__O = offsetof(ti_sysbios_gates_GateMutex_Object__,Object_field_sem)
Definition at line 1624 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsEnabled ti_sysbios_gates_GateMutex_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3770 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsIncluded ti_sysbios_gates_GateMutex_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3774 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsMask ti_sysbios_gates_GateMutex_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateMutex_Module__diagsMask)0)
Definition at line 3778 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__FXNS__C
const ti_sysbios_gates_GateMutex_Fxns__ ti_sysbios_gates_GateMutex_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IGateProvider_Interface__BASE__C,
    &ti_sysbios_gates_GateMutex_Module__FXNS__C.__sfxns,
    ti_sysbios_gates_GateMutex_query__E,
    ti_sysbios_gates_GateMutex_enter__E,
    ti_sysbios_gates_GateMutex_leave__E,
    {
        ti_sysbios_gates_GateMutex_Object__create__S,
        ti_sysbios_gates_GateMutex_Object__delete__S,
        ti_sysbios_gates_GateMutex_Handle__label__S,
        0x8029,
    }
}
Definition at line 850 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S().
ti_sysbios_gates_GateMutex_Module__gateObj__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gateObj ti_sysbios_gates_GateMutex_Module__gateObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__gateObj)0)
Definition at line 3782 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gatePrms ti_sysbios_gates_GateMutex_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateMutex_Module__gatePrms)0)
Definition at line 3786 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__id__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__id ti_sysbios_gates_GateMutex_Module__id__C = (xdc_Bits16)0x8029
Definition at line 3790 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerDefined ti_sysbios_gates_GateMutex_Module__loggerDefined__C = 0
Definition at line 3794 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0)0)
Definition at line 3802 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1)0)
Definition at line 3806 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2)0)
Definition at line 3810 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4)0)
Definition at line 3814 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8)0)
Definition at line 3818 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerObj ti_sysbios_gates_GateMutex_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerObj)0)
Definition at line 3798 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Module__root__V
ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__root__V
Initial value:
= {
    {&ti_sysbios_gates_GateMutex_Module__root__V.link,
    &ti_sysbios_gates_GateMutex_Module__root__V.link},
}
Definition at line 3727 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateMutex_Object__first__S(), and ti_sysbios_gates_GateMutex_Object__next__S().
ti_sysbios_gates_GateMutex_Object__count__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__count ti_sysbios_gates_GateMutex_Object__count__C = 2
Definition at line 3822 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateMutex_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_gates_GateMutex_Module__FXNS__C,
    &ti_sysbios_gates_GateMutex_Module__root__V.link,
    sizeof(ti_sysbios_gates_GateMutex___S1) - sizeof(ti_sysbios_gates_GateMutex_Object2__),
    0,
    0,
    sizeof(ti_sysbios_gates_GateMutex_Object2__),
    (xdc_CPtr)&ti_sysbios_gates_GateMutex_Object__PARAMS__C,
    sizeof(ti_sysbios_gates_GateMutex_Params),
}
Definition at line 3711 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateMutex_construct(), ti_sysbios_gates_GateMutex_create(), ti_sysbios_gates_GateMutex_destruct(), ti_sysbios_gates_GateMutex_Object__create__S(), and ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_gates_GateMutex_Object__heap__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__heap ti_sysbios_gates_GateMutex_Object__heap__C = 0
Definition at line 3826 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Object__PARAMS__C
const __FAR__ ti_sysbios_gates_GateMutex_Params ti_sysbios_gates_GateMutex_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_gates_GateMutex_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_gates_GateMutex_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 3715 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateMutex_Params__init__S().
ti_sysbios_gates_GateMutex_Object__sizeof__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__sizeof ti_sysbios_gates_GateMutex_Object__sizeof__C = sizeof(ti_sysbios_gates_GateMutex_Object__)
Definition at line 3830 of file mss_mrr_per4f.c.
ti_sysbios_gates_GateMutex_Object__table__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__table ti_sysbios_gates_GateMutex_Object__table__C = ti_sysbios_gates_GateMutex_Object__table__V
Definition at line 3834 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_gates_GateMutex_Object__get__S().
ti_sysbios_gates_GateMutex_Object__table__V
ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__table__V
Definition at line 1140 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__diagsEnabled ti_sysbios_hal_Cache_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3847 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__diagsIncluded ti_sysbios_hal_Cache_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3851 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__diagsMask ti_sysbios_hal_Cache_Module__diagsMask__C = ((CT__ti_sysbios_hal_Cache_Module__diagsMask)0)
Definition at line 3855 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__gateObj__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__gateObj ti_sysbios_hal_Cache_Module__gateObj__C = ((CT__ti_sysbios_hal_Cache_Module__gateObj)0)
Definition at line 3859 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__gatePrms ti_sysbios_hal_Cache_Module__gatePrms__C = ((CT__ti_sysbios_hal_Cache_Module__gatePrms)0)
Definition at line 3863 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__id__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__id ti_sysbios_hal_Cache_Module__id__C = (xdc_Bits16)0x802b
Definition at line 3867 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerDefined ti_sysbios_hal_Cache_Module__loggerDefined__C = 0
Definition at line 3871 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn0 ti_sysbios_hal_Cache_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn0)0)
Definition at line 3879 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn1 ti_sysbios_hal_Cache_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn1)0)
Definition at line 3883 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn2 ti_sysbios_hal_Cache_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn2)0)
Definition at line 3887 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn4 ti_sysbios_hal_Cache_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn4)0)
Definition at line 3891 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerFxn8 ti_sysbios_hal_Cache_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn8)0)
Definition at line 3895 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_hal_Cache_Module__loggerObj ti_sysbios_hal_Cache_Module__loggerObj__C = ((CT__ti_sysbios_hal_Cache_Module__loggerObj)0)
Definition at line 3875 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Object__count__C
const __FAR__ CT__ti_sysbios_hal_Cache_Object__count ti_sysbios_hal_Cache_Object__count__C = 0
Definition at line 3899 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Object__heap__C
const __FAR__ CT__ti_sysbios_hal_Cache_Object__heap ti_sysbios_hal_Cache_Object__heap__C = 0
Definition at line 3903 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Object__sizeof__C
const __FAR__ CT__ti_sysbios_hal_Cache_Object__sizeof ti_sysbios_hal_Cache_Object__sizeof__C = 0
Definition at line 3907 of file mss_mrr_per4f.c.
ti_sysbios_hal_Cache_Object__table__C
const __FAR__ CT__ti_sysbios_hal_Cache_Object__table ti_sysbios_hal_Cache_Object__table__C = 0
Definition at line 3911 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__diagsEnabled ti_sysbios_hal_CacheNull_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3920 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__diagsIncluded ti_sysbios_hal_CacheNull_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3924 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__diagsMask ti_sysbios_hal_CacheNull_Module__diagsMask__C = ((CT__ti_sysbios_hal_CacheNull_Module__diagsMask)0)
Definition at line 3928 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__FXNS__C
const ti_sysbios_hal_CacheNull_Fxns__ ti_sysbios_hal_CacheNull_Module__FXNS__C
Initial value:
= {
    &ti_sysbios_interfaces_ICache_Interface__BASE__C,
    &ti_sysbios_hal_CacheNull_Module__FXNS__C.__sfxns,
    ti_sysbios_hal_CacheNull_enable__E,
    ti_sysbios_hal_CacheNull_disable__E,
    ti_sysbios_hal_CacheNull_inv__E,
    ti_sysbios_hal_CacheNull_wb__E,
    ti_sysbios_hal_CacheNull_wbInv__E,
    ti_sysbios_hal_CacheNull_wbAll__E,
    ti_sysbios_hal_CacheNull_wbInvAll__E,
    ti_sysbios_hal_CacheNull_wait__E,
    {
        NULL,
        NULL,
        NULL,
        0x802c,
    }
}
Definition at line 871 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S().
ti_sysbios_hal_CacheNull_Module__gateObj__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__gateObj ti_sysbios_hal_CacheNull_Module__gateObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__gateObj)0)
Definition at line 3932 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__gatePrms ti_sysbios_hal_CacheNull_Module__gatePrms__C = ((CT__ti_sysbios_hal_CacheNull_Module__gatePrms)0)
Definition at line 3936 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__id__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__id ti_sysbios_hal_CacheNull_Module__id__C = (xdc_Bits16)0x802c
Definition at line 3940 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerDefined ti_sysbios_hal_CacheNull_Module__loggerDefined__C = 0
Definition at line 3944 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0 ti_sysbios_hal_CacheNull_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0)0)
Definition at line 3952 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1 ti_sysbios_hal_CacheNull_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1)0)
Definition at line 3956 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2 ti_sysbios_hal_CacheNull_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2)0)
Definition at line 3960 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4 ti_sysbios_hal_CacheNull_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4)0)
Definition at line 3964 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8 ti_sysbios_hal_CacheNull_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8)0)
Definition at line 3968 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Module__loggerObj ti_sysbios_hal_CacheNull_Module__loggerObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerObj)0)
Definition at line 3948 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Object__count__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__count ti_sysbios_hal_CacheNull_Object__count__C = 0
Definition at line 3972 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Object__heap__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__heap ti_sysbios_hal_CacheNull_Object__heap__C = 0
Definition at line 3976 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Object__sizeof__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__sizeof ti_sysbios_hal_CacheNull_Object__sizeof__C = 0
Definition at line 3980 of file mss_mrr_per4f.c.
ti_sysbios_hal_CacheNull_Object__table__C
const __FAR__ CT__ti_sysbios_hal_CacheNull_Object__table ti_sysbios_hal_CacheNull_Object__table__C = 0
Definition at line 3984 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__diagsEnabled ti_sysbios_hal_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3998 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__diagsIncluded ti_sysbios_hal_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4002 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__diagsMask ti_sysbios_hal_Core_Module__diagsMask__C = ((CT__ti_sysbios_hal_Core_Module__diagsMask)0)
Definition at line 4006 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__gateObj__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__gateObj ti_sysbios_hal_Core_Module__gateObj__C = ((CT__ti_sysbios_hal_Core_Module__gateObj)0)
Definition at line 4010 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__gatePrms ti_sysbios_hal_Core_Module__gatePrms__C = ((CT__ti_sysbios_hal_Core_Module__gatePrms)0)
Definition at line 4014 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__id__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__id ti_sysbios_hal_Core_Module__id__C = (xdc_Bits16)0x802d
Definition at line 4018 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerDefined ti_sysbios_hal_Core_Module__loggerDefined__C = 0
Definition at line 4022 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn0 ti_sysbios_hal_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn0)0)
Definition at line 4030 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn1 ti_sysbios_hal_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn1)0)
Definition at line 4034 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn2 ti_sysbios_hal_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn2)0)
Definition at line 4038 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn4 ti_sysbios_hal_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn4)0)
Definition at line 4042 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerFxn8 ti_sysbios_hal_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn8)0)
Definition at line 4046 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_hal_Core_Module__loggerObj ti_sysbios_hal_Core_Module__loggerObj__C = ((CT__ti_sysbios_hal_Core_Module__loggerObj)0)
Definition at line 4026 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_numCores__C
const __FAR__ CT__ti_sysbios_hal_Core_numCores ti_sysbios_hal_Core_numCores__C = (xdc_UInt)0x1
Definition at line 4066 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Object__count__C
const __FAR__ CT__ti_sysbios_hal_Core_Object__count ti_sysbios_hal_Core_Object__count__C = 0
Definition at line 4050 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Object__heap__C
const __FAR__ CT__ti_sysbios_hal_Core_Object__heap ti_sysbios_hal_Core_Object__heap__C = 0
Definition at line 4054 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Object__sizeof__C
const __FAR__ CT__ti_sysbios_hal_Core_Object__sizeof ti_sysbios_hal_Core_Object__sizeof__C = 0
Definition at line 4058 of file mss_mrr_per4f.c.
ti_sysbios_hal_Core_Object__table__C
const __FAR__ CT__ti_sysbios_hal_Core_Object__table ti_sysbios_hal_Core_Object__table__C = 0
Definition at line 4062 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C = 1
Definition at line 4183 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C = 1
Definition at line 4195 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_dispatcherSwiSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherSwiSupport ti_sysbios_hal_Hwi_dispatcherSwiSupport__C = 1
Definition at line 4187 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_dispatcherTaskSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherTaskSupport ti_sysbios_hal_Hwi_dispatcherTaskSupport__C = 1
Definition at line 4191 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_E_stackOverflow__C
const __FAR__ CT__ti_sysbios_hal_Hwi_E_stackOverflow ti_sysbios_hal_Hwi_E_stackOverflow__C = (((xdc_runtime_Error_Id)5021) << 16 | 0)
Definition at line 4199 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_hal_Hwi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsEnabled ti_sysbios_hal_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4115 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsIncluded ti_sysbios_hal_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4119 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsMask ti_sysbios_hal_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_hal_Hwi_Module__diagsMask)0)
Definition at line 4123 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gateObj ti_sysbios_hal_Hwi_Module__gateObj__C = ((CT__ti_sysbios_hal_Hwi_Module__gateObj)0)
Definition at line 4127 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gatePrms ti_sysbios_hal_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_hal_Hwi_Module__gatePrms)0)
Definition at line 4131 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__id__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__id ti_sysbios_hal_Hwi_Module__id__C = (xdc_Bits16)0x802e
Definition at line 4135 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerDefined ti_sysbios_hal_Hwi_Module__loggerDefined__C = 0
Definition at line 4139 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn0)0)
Definition at line 4147 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn1)0)
Definition at line 4151 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn2)0)
Definition at line 4155 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn4)0)
Definition at line 4159 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn8)0)
Definition at line 4163 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerObj ti_sysbios_hal_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerObj)0)
Definition at line 4143 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Module__root__V
ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_hal_Hwi_Module__root__V.link,
    &ti_sysbios_hal_Hwi_Module__root__V.link},
}
Definition at line 4100 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Hwi_Object__first__S(), and ti_sysbios_hal_Hwi_Object__next__S().
ti_sysbios_hal_Hwi_Object__count__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__count ti_sysbios_hal_Hwi_Object__count__C = 1
Definition at line 4167 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_hal_Hwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_hal_Hwi_Module__root__V.link,
    sizeof(ti_sysbios_hal_Hwi___S1) - sizeof(ti_sysbios_hal_Hwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_hal_Hwi_Object2__),
    (xdc_CPtr)&ti_sysbios_hal_Hwi_Object__PARAMS__C,
    sizeof(ti_sysbios_hal_Hwi_Params),
}
Definition at line 4079 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Hwi_construct(), ti_sysbios_hal_Hwi_create(), ti_sysbios_hal_Hwi_destruct(), ti_sysbios_hal_Hwi_Object__create__S(), and ti_sysbios_hal_Hwi_Object__delete__S().
ti_sysbios_hal_Hwi_Object__heap__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__heap ti_sysbios_hal_Hwi_Object__heap__C = 0
Definition at line 4171 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Object__PARAMS__C
const __FAR__ ti_sysbios_hal_Hwi_Params ti_sysbios_hal_Hwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_hal_Hwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_hal_Hwi_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_IHwi_MaskingOption_LOWER,
    ((xdc_UArg)(0x0)),
    1,
    (xdc_Int)(-0x0 - 1),
    (xdc_Int)(-0x0 - 1),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4083 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Hwi_Params__init__S().
ti_sysbios_hal_Hwi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__sizeof ti_sysbios_hal_Hwi_Object__sizeof__C = sizeof(ti_sysbios_hal_Hwi_Object__)
Definition at line 4175 of file mss_mrr_per4f.c.
ti_sysbios_hal_Hwi_Object__table__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__table ti_sysbios_hal_Hwi_Object__table__C = ti_sysbios_hal_Hwi_Object__table__V
Definition at line 4179 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_hal_Hwi_Object__get__S().
ti_sysbios_hal_Hwi_Object__table__V
ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__table__V
Initial value:
= {
    {
        0,
        (ti_sysbios_hal_Hwi_HwiProxy_Handle)&ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V[0],
    },
}
Definition at line 1173 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_bufAlign__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_bufAlign ti_sysbios_heaps_HeapBuf_A_bufAlign__C = (((xdc_runtime_Assert_Id)2024) << 16 | 16)
Definition at line 4327 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_invalidAlign__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidAlign ti_sysbios_heaps_HeapBuf_A_invalidAlign__C = (((xdc_runtime_Assert_Id)2049) << 16 | 16)
Definition at line 4331 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_invalidBlockSize__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidBlockSize ti_sysbios_heaps_HeapBuf_A_invalidBlockSize__C = (((xdc_runtime_Assert_Id)2228) << 16 | 16)
Definition at line 4339 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_invalidBufSize__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidBufSize ti_sysbios_heaps_HeapBuf_A_invalidBufSize__C = (((xdc_runtime_Assert_Id)2336) << 16 | 16)
Definition at line 4351 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_invalidFree__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidFree ti_sysbios_heaps_HeapBuf_A_invalidFree__C = (((xdc_runtime_Assert_Id)2454) << 16 | 16)
Definition at line 4359 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign__C = (((xdc_runtime_Assert_Id)2139) << 16 | 16)
Definition at line 4335 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_noBlocksToFree__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_noBlocksToFree ti_sysbios_heaps_HeapBuf_A_noBlocksToFree__C = (((xdc_runtime_Assert_Id)2394) << 16 | 16)
Definition at line 4355 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_nullBuf__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_nullBuf ti_sysbios_heaps_HeapBuf_A_nullBuf__C = (((xdc_runtime_Assert_Id)1995) << 16 | 16)
Definition at line 4323 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_zeroBlocks__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_zeroBlocks ti_sysbios_heaps_HeapBuf_A_zeroBlocks__C = (((xdc_runtime_Assert_Id)2288) << 16 | 16)
Definition at line 4343 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_A_zeroBufSize__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_A_zeroBufSize ti_sysbios_heaps_HeapBuf_A_zeroBufSize__C = (((xdc_runtime_Assert_Id)2313) << 16 | 16)
Definition at line 4347 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_E_size__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_E_size ti_sysbios_heaps_HeapBuf_E_size__C = (((xdc_runtime_Error_Id)4486) << 16 | 0)
Definition at line 4363 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Instance_State_freeList__O
const __FAR__ xdc_SizeT ti_sysbios_heaps_HeapBuf_Instance_State_freeList__O = offsetof(ti_sysbios_heaps_HeapBuf_Object__,Object_field_freeList)
Definition at line 1632 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__diagsEnabled ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4255 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__diagsIncluded ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4259 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask ti_sysbios_heaps_HeapBuf_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask)0)
Definition at line 4263 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__FXNS__C
const ti_sysbios_heaps_HeapBuf_Fxns__ ti_sysbios_heaps_HeapBuf_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IHeap_Interface__BASE__C,
    &ti_sysbios_heaps_HeapBuf_Module__FXNS__C.__sfxns,
    ti_sysbios_heaps_HeapBuf_alloc__E,
    ti_sysbios_heaps_HeapBuf_free__E,
    ti_sysbios_heaps_HeapBuf_isBlocking__E,
    ti_sysbios_heaps_HeapBuf_getStats__E,
    {
        ti_sysbios_heaps_HeapBuf_Object__create__S,
        ti_sysbios_heaps_HeapBuf_Object__delete__S,
        ti_sysbios_heaps_HeapBuf_Handle__label__S,
        0x8020,
    }
}
Definition at line 897 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__gateObj__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__gateObj ti_sysbios_heaps_HeapBuf_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gateObj)0)
Definition at line 4267 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms ti_sysbios_heaps_HeapBuf_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms)0)
Definition at line 4271 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__id__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__id ti_sysbios_heaps_HeapBuf_Module__id__C = (xdc_Bits16)0x8020
Definition at line 4275 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerDefined ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C = 0
Definition at line 4279 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0)0)
Definition at line 4287 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1)0)
Definition at line 4291 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2)0)
Definition at line 4295 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4)0)
Definition at line 4299 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8)0)
Definition at line 4303 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj ti_sysbios_heaps_HeapBuf_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj)0)
Definition at line 4283 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Module__root__V
ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__root__V
Initial value:
= {
    {&ti_sysbios_heaps_HeapBuf_Module__root__V.link,
    &ti_sysbios_heaps_HeapBuf_Module__root__V.link},
}
Definition at line 4233 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapBuf_Object__first__S(), and ti_sysbios_heaps_HeapBuf_Object__next__S().
ti_sysbios_heaps_HeapBuf_Module__state__V
ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module__state__V
Initial value:
= {
    ((void*)0),
}
Definition at line 1191 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_numConstructedHeaps__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_numConstructedHeaps ti_sysbios_heaps_HeapBuf_numConstructedHeaps__C = (xdc_UInt)0x0
Definition at line 4371 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Object__count__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__count ti_sysbios_heaps_HeapBuf_Object__count__C = 0
Definition at line 4307 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapBuf_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_heaps_HeapBuf_Module__FXNS__C,
    &ti_sysbios_heaps_HeapBuf_Module__root__V.link,
    sizeof(ti_sysbios_heaps_HeapBuf___S1) - sizeof(ti_sysbios_heaps_HeapBuf_Object2__),
    0,
    0,
    sizeof(ti_sysbios_heaps_HeapBuf_Object2__),
    (xdc_CPtr)&ti_sysbios_heaps_HeapBuf_Object__PARAMS__C,
    sizeof(ti_sysbios_heaps_HeapBuf_Params),
}
Definition at line 4212 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapBuf_construct(), ti_sysbios_heaps_HeapBuf_create(), ti_sysbios_heaps_HeapBuf_destruct(), ti_sysbios_heaps_HeapBuf_Object__create__S(), and ti_sysbios_heaps_HeapBuf_Object__delete__S().
ti_sysbios_heaps_HeapBuf_Object__heap__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__heap ti_sysbios_heaps_HeapBuf_Object__heap__C = 0
Definition at line 4311 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Object__PARAMS__C
const __FAR__ ti_sysbios_heaps_HeapBuf_Params ti_sysbios_heaps_HeapBuf_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_heaps_HeapBuf_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_heaps_HeapBuf_Object__PARAMS__C.__iprms,
    (xdc_SizeT)0x0,
    (xdc_UInt)0x0,
    (xdc_SizeT)0x0,
    ((xdc_UArg)(0x0)),
    ((xdc_Ptr)(0x0)),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4216 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapBuf_Params__init__S().
ti_sysbios_heaps_HeapBuf_Object__sizeof__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__sizeof ti_sysbios_heaps_HeapBuf_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapBuf_Object__)
Definition at line 4315 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_Object__table__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_Object__table ti_sysbios_heaps_HeapBuf_Object__table__C = 0
Definition at line 4319 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapBuf_trackMaxAllocs__C
const __FAR__ CT__ti_sysbios_heaps_HeapBuf_trackMaxAllocs ti_sysbios_heaps_HeapBuf_trackMaxAllocs__C = 0
Definition at line 4367 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_A_align__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_align ti_sysbios_heaps_HeapMem_A_align__C = (((xdc_runtime_Assert_Id)2563) << 16 | 16)
Definition at line 4498 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_A_heapSize__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_heapSize ti_sysbios_heaps_HeapMem_A_heapSize__C = (((xdc_runtime_Assert_Id)2518) << 16 | 16)
Definition at line 4494 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_A_invalidFree__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_invalidFree ti_sysbios_heaps_HeapMem_A_invalidFree__C = (((xdc_runtime_Assert_Id)2454) << 16 | 16)
Definition at line 4506 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_A_zeroBlock__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_zeroBlock ti_sysbios_heaps_HeapMem_A_zeroBlock__C = (((xdc_runtime_Assert_Id)2482) << 16 | 16)
Definition at line 4490 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_E_memory__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_E_memory ti_sysbios_heaps_HeapMem_E_memory__C = (((xdc_runtime_Error_Id)4534) << 16 | 0)
Definition at line 4502 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A
__T1_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A
Definition at line 1202 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsEnabled ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4422 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsIncluded ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4426 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsMask ti_sysbios_heaps_HeapMem_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapMem_Module__diagsMask)0)
Definition at line 4430 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__FXNS__C
const ti_sysbios_heaps_HeapMem_Fxns__ ti_sysbios_heaps_HeapMem_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IHeap_Interface__BASE__C,
    &ti_sysbios_heaps_HeapMem_Module__FXNS__C.__sfxns,
    ti_sysbios_heaps_HeapMem_alloc__E,
    ti_sysbios_heaps_HeapMem_free__E,
    ti_sysbios_heaps_HeapMem_isBlocking__E,
    ti_sysbios_heaps_HeapMem_getStats__E,
    {
        ti_sysbios_heaps_HeapMem_Object__create__S,
        ti_sysbios_heaps_HeapMem_Object__delete__S,
        ti_sysbios_heaps_HeapMem_Handle__label__S,
        0x8021,
    }
}
Definition at line 919 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Memory_HeapProxy_Proxy__delegate__S().
ti_sysbios_heaps_HeapMem_Module__gateObj__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gateObj ti_sysbios_heaps_HeapMem_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[0]))
Definition at line 4434 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gatePrms ti_sysbios_heaps_HeapMem_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gatePrms)0)
Definition at line 4438 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__id__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__id ti_sysbios_heaps_HeapMem_Module__id__C = (xdc_Bits16)0x8021
Definition at line 4442 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerDefined ti_sysbios_heaps_HeapMem_Module__loggerDefined__C = 0
Definition at line 4446 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0)0)
Definition at line 4454 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1)0)
Definition at line 4458 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2)0)
Definition at line 4462 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4)0)
Definition at line 4466 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8)0)
Definition at line 4470 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerObj ti_sysbios_heaps_HeapMem_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerObj)0)
Definition at line 4450 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Module__root__V
ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__root__V
Initial value:
= {
    {&ti_sysbios_heaps_HeapMem_Module__root__V.link,
    &ti_sysbios_heaps_HeapMem_Module__root__V.link},
}
Definition at line 4401 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapMem_Object__first__S(), and ti_sysbios_heaps_HeapMem_Object__next__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_heaps_HeapMem_Object__count__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__count ti_sysbios_heaps_HeapMem_Object__count__C = 1
Definition at line 4474 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapMem_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_heaps_HeapMem_Module__FXNS__C,
    &ti_sysbios_heaps_HeapMem_Module__root__V.link,
    sizeof(ti_sysbios_heaps_HeapMem___S1) - sizeof(ti_sysbios_heaps_HeapMem_Object2__),
    0,
    0,
    sizeof(ti_sysbios_heaps_HeapMem_Object2__),
    (xdc_CPtr)&ti_sysbios_heaps_HeapMem_Object__PARAMS__C,
    sizeof(ti_sysbios_heaps_HeapMem_Params),
}
Definition at line 4379 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapMem_construct(), ti_sysbios_heaps_HeapMem_create(), ti_sysbios_heaps_HeapMem_destruct(), ti_sysbios_heaps_HeapMem_Object__create__S(), and ti_sysbios_heaps_HeapMem_Object__delete__S().
ti_sysbios_heaps_HeapMem_Object__heap__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__heap ti_sysbios_heaps_HeapMem_Object__heap__C = 0
Definition at line 4478 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Object__PARAMS__C
const __FAR__ ti_sysbios_heaps_HeapMem_Params ti_sysbios_heaps_HeapMem_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_heaps_HeapMem_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_heaps_HeapMem_Object__PARAMS__C.__iprms,
    (xdc_SizeT)0x0,
    ((xdc_Ptr)(0x0)),
    ((xdc_UArg)(0x0)),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4383 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapMem_Params__init__S().
ti_sysbios_heaps_HeapMem_Object__sizeof__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__sizeof ti_sysbios_heaps_HeapMem_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapMem_Object__)
Definition at line 4482 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_Object__table__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__table ti_sysbios_heaps_HeapMem_Object__table__C = ti_sysbios_heaps_HeapMem_Object__table__V
Definition at line 4486 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_heaps_HeapMem_Object__get__S().
ti_sysbios_heaps_HeapMem_Object__table__V
ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__table__V
Initial value:
= {
    {
        &ti_sysbios_heaps_HeapMem_Module__FXNS__C,
        ((xdc_UArg)(0x8)),
        ((void*)ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A),
        {
            ((ti_sysbios_heaps_HeapMem_Header*)0),
            ((xdc_UArg)(0x8000)),
        },
        (xdc_SizeT)0x8,
    },
}
Definition at line 1221 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr)0)
Definition at line 4510 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr)0)
Definition at line 4514 of file mss_mrr_per4f.c.
ti_sysbios_heaps_HeapMem_reqAlign__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_reqAlign ti_sysbios_heaps_HeapMem_reqAlign__C = (xdc_SizeT)0x8
Definition at line 4518 of file mss_mrr_per4f.c.
ti_sysbios_interfaces_ICache_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base ti_sysbios_interfaces_ICache_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 811 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_A_badThreadType__C
const __FAR__ CT__ti_sysbios_knl_Clock_A_badThreadType ti_sysbios_knl_Clock_A_badThreadType__C = (((xdc_runtime_Assert_Id)696) << 16 | 16)
Definition at line 4671 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_A_clockDisabled__C
const __FAR__ CT__ti_sysbios_knl_Clock_A_clockDisabled ti_sysbios_knl_Clock_A_clockDisabled__C = (((xdc_runtime_Assert_Id)615) << 16 | 16)
Definition at line 4667 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_doTickFunc__C
const __FAR__ CT__ti_sysbios_knl_Clock_doTickFunc ti_sysbios_knl_Clock_doTickFunc__C = ((CT__ti_sysbios_knl_Clock_doTickFunc)((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I))
Definition at line 4695 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_LM_begin__C
const __FAR__ CT__ti_sysbios_knl_Clock_LM_begin ti_sysbios_knl_Clock_LM_begin__C = (((xdc_runtime_Log_Event)5524) << 16 | 768)
Definition at line 4663 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_LM_tick__C
const __FAR__ CT__ti_sysbios_knl_Clock_LM_tick ti_sysbios_knl_Clock_LM_tick__C = (((xdc_runtime_Log_Event)5506) << 16 | 768)
Definition at line 4659 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_LW_delayed__C
const __FAR__ CT__ti_sysbios_knl_Clock_LW_delayed ti_sysbios_knl_Clock_LW_delayed__C = (((xdc_runtime_Log_Event)5484) << 16 | 1024)
Definition at line 4655 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsEnabled ti_sysbios_knl_Clock_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4587 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsIncluded ti_sysbios_knl_Clock_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4591 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsMask ti_sysbios_knl_Clock_Module__diagsMask__C = ((CT__ti_sysbios_knl_Clock_Module__diagsMask)0)
Definition at line 4595 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gateObj ti_sysbios_knl_Clock_Module__gateObj__C = ((CT__ti_sysbios_knl_Clock_Module__gateObj)0)
Definition at line 4599 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gatePrms ti_sysbios_knl_Clock_Module__gatePrms__C = ((CT__ti_sysbios_knl_Clock_Module__gatePrms)0)
Definition at line 4603 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__id ti_sysbios_knl_Clock_Module__id__C = (xdc_Bits16)0x8017
Definition at line 4607 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerDefined ti_sysbios_knl_Clock_Module__loggerDefined__C = 0
Definition at line 4611 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn0 ti_sysbios_knl_Clock_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn0)0)
Definition at line 4619 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn1 ti_sysbios_knl_Clock_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn1)0)
Definition at line 4623 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn2 ti_sysbios_knl_Clock_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn2)0)
Definition at line 4627 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn4 ti_sysbios_knl_Clock_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn4)0)
Definition at line 4631 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn8 ti_sysbios_knl_Clock_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn8)0)
Definition at line 4635 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerObj ti_sysbios_knl_Clock_Module__loggerObj__C = ((CT__ti_sysbios_knl_Clock_Module__loggerObj)0)
Definition at line 4615 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Module__root__V
ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Clock_Module__root__V.link,
    &ti_sysbios_knl_Clock_Module__root__V.link},
}
Definition at line 4550 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Clock_Object__first__S(), and ti_sysbios_knl_Clock_Object__next__S().
ti_sysbios_knl_Clock_Module__state__V
ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module__state__V
Initial value:
= {
    (xdc_UInt32)0x0,
    (xdc_UInt)0x0,
    (ti_sysbios_knl_Clock_TimerProxy_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0],
    (ti_sysbios_knl_Swi_Handle)&ti_sysbios_knl_Swi_Object__table__V[0],
    (xdc_UInt)0x1,
    (xdc_UInt32)0x1,
    (xdc_UInt32)0x0,
    0,
    0,
    0,
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Module__state__V.Object_field_clockQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Module__state__V.Object_field_clockQ.elem)),
        },
    },
}
Definition at line 1249 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Clock_doTick__I().
ti_sysbios_knl_Clock_Module_State_clockQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Clock_Module_State_clockQ__O = offsetof(ti_sysbios_knl_Clock_Module_State__,Object_field_clockQ)
Definition at line 1640 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__count ti_sysbios_knl_Clock_Object__count__C = 0
Definition at line 4639 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Clock_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Clock_Module__root__V.link,
    sizeof(ti_sysbios_knl_Clock___S1) - sizeof(ti_sysbios_knl_Clock_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Clock_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Clock_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Clock_Params),
}
Definition at line 4531 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Clock_construct(), ti_sysbios_knl_Clock_create(), ti_sysbios_knl_Clock_destruct(), ti_sysbios_knl_Clock_Object__create__S(), and ti_sysbios_knl_Clock_Object__delete__S().
ti_sysbios_knl_Clock_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__heap ti_sysbios_knl_Clock_Object__heap__C = 0
Definition at line 4643 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Clock_Params ti_sysbios_knl_Clock_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Clock_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Clock_Object__PARAMS__C.__iprms,
    0,
    (xdc_UInt32)0x0,
    ((xdc_UArg)0),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4535 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Clock_Params__init__S().
ti_sysbios_knl_Clock_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__sizeof ti_sysbios_knl_Clock_Object__sizeof__C = sizeof(ti_sysbios_knl_Clock_Object__)
Definition at line 4647 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__table ti_sysbios_knl_Clock_Object__table__C = 0
Definition at line 4651 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_serviceMargin__C
const __FAR__ CT__ti_sysbios_knl_Clock_serviceMargin ti_sysbios_knl_Clock_serviceMargin__C = (xdc_UInt32)0x0
Definition at line 4675 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_tickMode__C
const __FAR__ CT__ti_sysbios_knl_Clock_tickMode ti_sysbios_knl_Clock_tickMode__C = ti_sysbios_knl_Clock_TickMode_PERIODIC
Definition at line 4683 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_tickPeriod__C
const __FAR__ CT__ti_sysbios_knl_Clock_tickPeriod ti_sysbios_knl_Clock_tickPeriod__C = (xdc_UInt32)0x3e8
Definition at line 4691 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_tickSource__C
const __FAR__ CT__ti_sysbios_knl_Clock_tickSource ti_sysbios_knl_Clock_tickSource__C = ti_sysbios_knl_Clock_TickSource_TIMER
Definition at line 4679 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_timerId__C
const __FAR__ CT__ti_sysbios_knl_Clock_timerId ti_sysbios_knl_Clock_timerId__C = (xdc_UInt)(-0x0 - 1)
Definition at line 4687 of file mss_mrr_per4f.c.
ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Clock_triggerClock__C
const __FAR__ CT__ti_sysbios_knl_Clock_triggerClock ti_sysbios_knl_Clock_triggerClock__C = 0
Definition at line 4699 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_A_badContext__C
const __FAR__ CT__ti_sysbios_knl_Event_A_badContext ti_sysbios_knl_Event_A_badContext__C = (((xdc_runtime_Assert_Id)895) << 16 | 16)
Definition at line 4823 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_A_eventInUse__C
const __FAR__ CT__ti_sysbios_knl_Event_A_eventInUse ti_sysbios_knl_Event_A_eventInUse__C = (((xdc_runtime_Assert_Id)852) << 16 | 16)
Definition at line 4819 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_A_nullEventId__C
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventId ti_sysbios_knl_Event_A_nullEventId__C = (((xdc_runtime_Assert_Id)813) << 16 | 16)
Definition at line 4815 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_A_nullEventMasks__C
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventMasks ti_sysbios_knl_Event_A_nullEventMasks__C = (((xdc_runtime_Assert_Id)766) << 16 | 16)
Definition at line 4811 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_A_pendTaskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Event_A_pendTaskDisabled ti_sysbios_knl_Event_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)958) << 16 | 16)
Definition at line 4827 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Instance_State_pendQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Event_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Event_Object__,Object_field_pendQ)
Definition at line 1648 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_LM_pend__C
const __FAR__ CT__ti_sysbios_knl_Event_LM_pend ti_sysbios_knl_Event_LM_pend__C = (((xdc_runtime_Log_Event)5610) << 16 | 768)
Definition at line 4807 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_LM_post__C
const __FAR__ CT__ti_sysbios_knl_Event_LM_post ti_sysbios_knl_Event_LM_post__C = (((xdc_runtime_Log_Event)5556) << 16 | 768)
Definition at line 4803 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsEnabled ti_sysbios_knl_Event_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4735 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsIncluded ti_sysbios_knl_Event_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4739 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsMask ti_sysbios_knl_Event_Module__diagsMask__C = ((CT__ti_sysbios_knl_Event_Module__diagsMask)0)
Definition at line 4743 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__gateObj ti_sysbios_knl_Event_Module__gateObj__C = ((CT__ti_sysbios_knl_Event_Module__gateObj)0)
Definition at line 4747 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__gatePrms ti_sysbios_knl_Event_Module__gatePrms__C = ((CT__ti_sysbios_knl_Event_Module__gatePrms)0)
Definition at line 4751 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__id ti_sysbios_knl_Event_Module__id__C = (xdc_Bits16)0x801a
Definition at line 4755 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerDefined ti_sysbios_knl_Event_Module__loggerDefined__C = 0
Definition at line 4759 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn0 ti_sysbios_knl_Event_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn0)0)
Definition at line 4767 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn1 ti_sysbios_knl_Event_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn1)0)
Definition at line 4771 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn2 ti_sysbios_knl_Event_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn2)0)
Definition at line 4775 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn4 ti_sysbios_knl_Event_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn4)0)
Definition at line 4779 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn8 ti_sysbios_knl_Event_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn8)0)
Definition at line 4783 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerObj ti_sysbios_knl_Event_Module__loggerObj__C = ((CT__ti_sysbios_knl_Event_Module__loggerObj)0)
Definition at line 4763 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Module__root__V
ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Event_Module__root__V.link,
    &ti_sysbios_knl_Event_Module__root__V.link},
}
Definition at line 4728 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Event_Object__first__S(), and ti_sysbios_knl_Event_Object__next__S().
ti_sysbios_knl_Event_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__count ti_sysbios_knl_Event_Object__count__C = 0
Definition at line 4787 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Event_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Event_Module__root__V.link,
    sizeof(ti_sysbios_knl_Event___S1) - sizeof(ti_sysbios_knl_Event_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Event_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Event_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Event_Params),
}
Definition at line 4712 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Event_construct(), ti_sysbios_knl_Event_create(), ti_sysbios_knl_Event_destruct(), ti_sysbios_knl_Event_Object__create__S(), and ti_sysbios_knl_Event_Object__delete__S().
ti_sysbios_knl_Event_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__heap ti_sysbios_knl_Event_Object__heap__C = 0
Definition at line 4791 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Event_Params ti_sysbios_knl_Event_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Event_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Event_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4716 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Event_Params__init__S().
ti_sysbios_knl_Event_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__sizeof ti_sysbios_knl_Event_Object__sizeof__C = sizeof(ti_sysbios_knl_Event_Object__)
Definition at line 4795 of file mss_mrr_per4f.c.
ti_sysbios_knl_Event_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__table ti_sysbios_knl_Event_Object__table__C = 0
Definition at line 4799 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_coreList__A
const __T1_ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__A
Initial value:
= {
    (xdc_UInt)0x0,
}
Definition at line 1276 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_coreList__C
const __FAR__ CT__ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__C = {1, ((__T1_ti_sysbios_knl_Idle_coreList *)ti_sysbios_knl_Idle_coreList__A)}
Definition at line 4920 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_funcList__A
const __T1_ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_hal_Hwi_checkStack)),
}
Definition at line 1273 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_funcList__C
const __FAR__ CT__ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__C = {1, ((__T1_ti_sysbios_knl_Idle_funcList *)ti_sysbios_knl_Idle_funcList__A)}
Definition at line 4916 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsEnabled ti_sysbios_knl_Idle_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4848 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsIncluded ti_sysbios_knl_Idle_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4852 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsMask ti_sysbios_knl_Idle_Module__diagsMask__C = ((CT__ti_sysbios_knl_Idle_Module__diagsMask)0)
Definition at line 4856 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gateObj ti_sysbios_knl_Idle_Module__gateObj__C = ((CT__ti_sysbios_knl_Idle_Module__gateObj)0)
Definition at line 4860 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gatePrms ti_sysbios_knl_Idle_Module__gatePrms__C = ((CT__ti_sysbios_knl_Idle_Module__gatePrms)0)
Definition at line 4864 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__id ti_sysbios_knl_Idle_Module__id__C = (xdc_Bits16)0x8018
Definition at line 4868 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerDefined ti_sysbios_knl_Idle_Module__loggerDefined__C = 0
Definition at line 4872 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn0 ti_sysbios_knl_Idle_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn0)0)
Definition at line 4880 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn1 ti_sysbios_knl_Idle_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn1)0)
Definition at line 4884 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn2 ti_sysbios_knl_Idle_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn2)0)
Definition at line 4888 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn4 ti_sysbios_knl_Idle_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn4)0)
Definition at line 4892 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn8 ti_sysbios_knl_Idle_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn8)0)
Definition at line 4896 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerObj ti_sysbios_knl_Idle_Module__loggerObj__C = ((CT__ti_sysbios_knl_Idle_Module__loggerObj)0)
Definition at line 4876 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__count ti_sysbios_knl_Idle_Object__count__C = 0
Definition at line 4900 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__heap ti_sysbios_knl_Idle_Object__heap__C = 0
Definition at line 4904 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__sizeof ti_sysbios_knl_Idle_Object__sizeof__C = 0
Definition at line 4908 of file mss_mrr_per4f.c.
ti_sysbios_knl_Idle_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__table ti_sysbios_knl_Idle_Object__table__C = 0
Definition at line 4912 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsEnabled ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4929 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsIncluded ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4933 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsMask ti_sysbios_knl_Intrinsics_Module__diagsMask__C = ((CT__ti_sysbios_knl_Intrinsics_Module__diagsMask)0)
Definition at line 4937 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gateObj ti_sysbios_knl_Intrinsics_Module__gateObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gateObj)0)
Definition at line 4941 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gatePrms ti_sysbios_knl_Intrinsics_Module__gatePrms__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gatePrms)0)
Definition at line 4945 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__id ti_sysbios_knl_Intrinsics_Module__id__C = (xdc_Bits16)0x8019
Definition at line 4949 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerDefined ti_sysbios_knl_Intrinsics_Module__loggerDefined__C = 0
Definition at line 4953 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0 ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0)0)
Definition at line 4961 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1 ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1)0)
Definition at line 4965 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2 ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2)0)
Definition at line 4969 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4 ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4)0)
Definition at line 4973 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8 ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8)0)
Definition at line 4977 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerObj ti_sysbios_knl_Intrinsics_Module__loggerObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerObj)0)
Definition at line 4957 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__count ti_sysbios_knl_Intrinsics_Object__count__C = 0
Definition at line 4981 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__heap ti_sysbios_knl_Intrinsics_Object__heap__C = 0
Definition at line 4985 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__sizeof ti_sysbios_knl_Intrinsics_Object__sizeof__C = 0
Definition at line 4989 of file mss_mrr_per4f.c.
ti_sysbios_knl_Intrinsics_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__table ti_sysbios_knl_Intrinsics_Object__table__C = 0
Definition at line 4993 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsEnabled ti_sysbios_knl_Queue_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5029 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsIncluded ti_sysbios_knl_Queue_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5033 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsMask ti_sysbios_knl_Queue_Module__diagsMask__C = ((CT__ti_sysbios_knl_Queue_Module__diagsMask)0)
Definition at line 5037 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gateObj ti_sysbios_knl_Queue_Module__gateObj__C = ((CT__ti_sysbios_knl_Queue_Module__gateObj)0)
Definition at line 5041 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gatePrms ti_sysbios_knl_Queue_Module__gatePrms__C = ((CT__ti_sysbios_knl_Queue_Module__gatePrms)0)
Definition at line 5045 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__id ti_sysbios_knl_Queue_Module__id__C = (xdc_Bits16)0x801b
Definition at line 5049 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerDefined ti_sysbios_knl_Queue_Module__loggerDefined__C = 0
Definition at line 5053 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn0 ti_sysbios_knl_Queue_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn0)0)
Definition at line 5061 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn1 ti_sysbios_knl_Queue_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn1)0)
Definition at line 5065 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn2 ti_sysbios_knl_Queue_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn2)0)
Definition at line 5069 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn4 ti_sysbios_knl_Queue_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn4)0)
Definition at line 5073 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn8 ti_sysbios_knl_Queue_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn8)0)
Definition at line 5077 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerObj ti_sysbios_knl_Queue_Module__loggerObj__C = ((CT__ti_sysbios_knl_Queue_Module__loggerObj)0)
Definition at line 5057 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Module__root__V
ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Queue_Module__root__V.link,
    &ti_sysbios_knl_Queue_Module__root__V.link},
}
Definition at line 5022 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Queue_Object__first__S(), and ti_sysbios_knl_Queue_Object__next__S().
ti_sysbios_knl_Queue_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__count ti_sysbios_knl_Queue_Object__count__C = 0
Definition at line 5081 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Queue_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Queue_Module__root__V.link,
    sizeof(ti_sysbios_knl_Queue___S1) - sizeof(ti_sysbios_knl_Queue_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Queue_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Queue_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Queue_Params),
}
Definition at line 5006 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Queue_construct(), ti_sysbios_knl_Queue_create(), ti_sysbios_knl_Queue_destruct(), ti_sysbios_knl_Queue_Object__create__S(), and ti_sysbios_knl_Queue_Object__delete__S().
ti_sysbios_knl_Queue_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__heap ti_sysbios_knl_Queue_Object__heap__C = 0
Definition at line 5085 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Queue_Params ti_sysbios_knl_Queue_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Queue_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Queue_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5010 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Queue_Params__init__S().
ti_sysbios_knl_Queue_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__sizeof ti_sysbios_knl_Queue_Object__sizeof__C = sizeof(ti_sysbios_knl_Queue_Object__)
Definition at line 5089 of file mss_mrr_per4f.c.
ti_sysbios_knl_Queue_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__table ti_sysbios_knl_Queue_Object__table__C = 0
Definition at line 5093 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_A_badContext__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_badContext ti_sysbios_knl_Semaphore_A_badContext__C = (((xdc_runtime_Assert_Id)895) << 16 | 16)
Definition at line 5211 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_A_invTimeout__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_invTimeout ti_sysbios_knl_Semaphore_A_invTimeout__C = (((xdc_runtime_Assert_Id)1161) << 16 | 16)
Definition at line 5207 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_A_noEvents__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_noEvents ti_sysbios_knl_Semaphore_A_noEvents__C = (((xdc_runtime_Assert_Id)1106) << 16 | 16)
Definition at line 5203 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_A_overflow__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_overflow ti_sysbios_knl_Semaphore_A_overflow__C = (((xdc_runtime_Assert_Id)1226) << 16 | 16)
Definition at line 5215 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_pendTaskDisabled ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)1280) << 16 | 16)
Definition at line 5219 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)4068) << 16 | 0)
Definition at line 5223 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_eventPost__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventPost ti_sysbios_knl_Semaphore_eventPost__C = ((CT__ti_sysbios_knl_Semaphore_eventPost)0)
Definition at line 5235 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_eventSync__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventSync ti_sysbios_knl_Semaphore_eventSync__C = ((CT__ti_sysbios_knl_Semaphore_eventSync)0)
Definition at line 5239 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Instance_State_pendQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Semaphore_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Semaphore_Object__,Object_field_pendQ)
Definition at line 1656 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_LM_pend__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_pend ti_sysbios_knl_Semaphore_LM_pend__C = (((xdc_runtime_Log_Event)5721) << 16 | 768)
Definition at line 5199 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_LM_post__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_post ti_sysbios_knl_Semaphore_LM_post__C = (((xdc_runtime_Log_Event)5691) << 16 | 768)
Definition at line 5195 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsEnabled ti_sysbios_knl_Semaphore_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5127 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsIncluded ti_sysbios_knl_Semaphore_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5131 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsMask ti_sysbios_knl_Semaphore_Module__diagsMask__C = ((CT__ti_sysbios_knl_Semaphore_Module__diagsMask)0)
Definition at line 5135 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gateObj ti_sysbios_knl_Semaphore_Module__gateObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__gateObj)0)
Definition at line 5139 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gatePrms ti_sysbios_knl_Semaphore_Module__gatePrms__C = ((CT__ti_sysbios_knl_Semaphore_Module__gatePrms)0)
Definition at line 5143 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__id ti_sysbios_knl_Semaphore_Module__id__C = (xdc_Bits16)0x801c
Definition at line 5147 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerDefined ti_sysbios_knl_Semaphore_Module__loggerDefined__C = 0
Definition at line 5151 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0)0)
Definition at line 5159 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1)0)
Definition at line 5163 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2)0)
Definition at line 5167 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4)0)
Definition at line 5171 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8)0)
Definition at line 5175 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerObj ti_sysbios_knl_Semaphore_Module__loggerObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerObj)0)
Definition at line 5155 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Module__root__V
ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Semaphore_Module__root__V.link,
    &ti_sysbios_knl_Semaphore_Module__root__V.link},
}
Definition at line 5120 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Semaphore_Object__first__S(), and ti_sysbios_knl_Semaphore_Object__next__S().
ti_sysbios_knl_Semaphore_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__count ti_sysbios_knl_Semaphore_Object__count__C = 0
Definition at line 5179 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Semaphore_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Semaphore_Module__root__V.link,
    sizeof(ti_sysbios_knl_Semaphore___S1) - sizeof(ti_sysbios_knl_Semaphore_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Semaphore_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Semaphore_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Semaphore_Params),
}
Definition at line 5101 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Semaphore_construct(), ti_sysbios_knl_Semaphore_create(), ti_sysbios_knl_Semaphore_destruct(), ti_sysbios_knl_Semaphore_Object__create__S(), and ti_sysbios_knl_Semaphore_Object__delete__S().
ti_sysbios_knl_Semaphore_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__heap ti_sysbios_knl_Semaphore_Object__heap__C = 0
Definition at line 5183 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Semaphore_Params ti_sysbios_knl_Semaphore_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Semaphore_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Semaphore_Object__PARAMS__C.__iprms,
    0,
    (xdc_UInt)0x1,
    ti_sysbios_knl_Semaphore_Mode_COUNTING,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5105 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Semaphore_Params__init__S().
ti_sysbios_knl_Semaphore_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__sizeof ti_sysbios_knl_Semaphore_Object__sizeof__C = sizeof(ti_sysbios_knl_Semaphore_Object__)
Definition at line 5187 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__table ti_sysbios_knl_Semaphore_Object__table__C = 0
Definition at line 5191 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_supportsEvents__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsEvents ti_sysbios_knl_Semaphore_supportsEvents__C = 0
Definition at line 5227 of file mss_mrr_per4f.c.
ti_sysbios_knl_Semaphore_supportsPriority__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsPriority ti_sysbios_knl_Semaphore_supportsPriority__C = 1
Definition at line 5231 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_A_badPriority__C
const __FAR__ CT__ti_sysbios_knl_Swi_A_badPriority ti_sysbios_knl_Swi_A_badPriority__C = (((xdc_runtime_Assert_Id)1431) << 16 | 16)
Definition at line 5499 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_A_swiDisabled__C
const __FAR__ CT__ti_sysbios_knl_Swi_A_swiDisabled ti_sysbios_knl_Swi_A_swiDisabled__C = (((xdc_runtime_Assert_Id)1374) << 16 | 16)
Definition at line 5495 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_hooks__C
const __FAR__ CT__ti_sysbios_knl_Swi_hooks ti_sysbios_knl_Swi_hooks__C = {0, 0}
Definition at line 5507 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_LD_end__C
const __FAR__ CT__ti_sysbios_knl_Swi_LD_end ti_sysbios_knl_Swi_LD_end__C = (((xdc_runtime_Log_Event)5811) << 16 | 512)
Definition at line 5487 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_LM_begin__C
const __FAR__ CT__ti_sysbios_knl_Swi_LM_begin ti_sysbios_knl_Swi_LM_begin__C = (((xdc_runtime_Log_Event)5764) << 16 | 768)
Definition at line 5483 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_LM_post__C
const __FAR__ CT__ti_sysbios_knl_Swi_LM_post ti_sysbios_knl_Swi_LM_post__C = (((xdc_runtime_Log_Event)5829) << 16 | 768)
Definition at line 5491 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__diagsEnabled ti_sysbios_knl_Swi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5415 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__diagsIncluded ti_sysbios_knl_Swi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5419 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__diagsMask ti_sysbios_knl_Swi_Module__diagsMask__C = ((CT__ti_sysbios_knl_Swi_Module__diagsMask)0)
Definition at line 5423 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__gateObj ti_sysbios_knl_Swi_Module__gateObj__C = ((CT__ti_sysbios_knl_Swi_Module__gateObj)0)
Definition at line 5427 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__gatePrms ti_sysbios_knl_Swi_Module__gatePrms__C = ((CT__ti_sysbios_knl_Swi_Module__gatePrms)0)
Definition at line 5431 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__id ti_sysbios_knl_Swi_Module__id__C = (xdc_Bits16)0x801d
Definition at line 5435 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerDefined ti_sysbios_knl_Swi_Module__loggerDefined__C = 0
Definition at line 5439 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn0 ti_sysbios_knl_Swi_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn0)0)
Definition at line 5447 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn1 ti_sysbios_knl_Swi_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn1)0)
Definition at line 5451 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn2 ti_sysbios_knl_Swi_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn2)0)
Definition at line 5455 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn4 ti_sysbios_knl_Swi_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn4)0)
Definition at line 5459 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerFxn8 ti_sysbios_knl_Swi_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Swi_Module__loggerFxn8)0)
Definition at line 5463 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Swi_Module__loggerObj ti_sysbios_knl_Swi_Module__loggerObj__C = ((CT__ti_sysbios_knl_Swi_Module__loggerObj)0)
Definition at line 5443 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module__root__V
ti_sysbios_knl_Swi_Module__ ti_sysbios_knl_Swi_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Swi_Module__root__V.link,
    &ti_sysbios_knl_Swi_Module__root__V.link},
}
Definition at line 5267 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Swi_Object__first__S(), and ti_sysbios_knl_Swi_Object__next__S().
ti_sysbios_knl_Swi_Module__state__V
ti_sysbios_knl_Swi_Module_State__ ti_sysbios_knl_Swi_Module__state__V
Initial value:
= {
    1,
    (xdc_UInt)0x0,
    (xdc_UInt)0x0,
    0,
    0,
    ((void*)ti_sysbios_knl_Swi_Module_State_0_readyQ__A),
    ((void*)0),
}
Definition at line 1321 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Module_State_0_readyQ__A
__T1_ti_sysbios_knl_Swi_Module_State__readyQ ti_sysbios_knl_Swi_Module_State_0_readyQ__A
Definition at line 1318 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_numConstructedSwis__C
const __FAR__ CT__ti_sysbios_knl_Swi_numConstructedSwis ti_sysbios_knl_Swi_numConstructedSwis__C = (xdc_UInt)0x0
Definition at line 5519 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_numPriorities__C
const __FAR__ CT__ti_sysbios_knl_Swi_numPriorities ti_sysbios_knl_Swi_numPriorities__C = (xdc_UInt)0x10
Definition at line 5503 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Swi_Object__count ti_sysbios_knl_Swi_Object__count__C = 1
Definition at line 5467 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Swi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Swi_Module__root__V.link,
    sizeof(ti_sysbios_knl_Swi___S1) - sizeof(ti_sysbios_knl_Swi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Swi_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Swi_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Swi_Params),
}
Definition at line 5247 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Swi_construct(), ti_sysbios_knl_Swi_create(), ti_sysbios_knl_Swi_destruct(), ti_sysbios_knl_Swi_Object__create__S(), and ti_sysbios_knl_Swi_Object__delete__S().
ti_sysbios_knl_Swi_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Swi_Object__heap ti_sysbios_knl_Swi_Object__heap__C = 0
Definition at line 5471 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Swi_Params ti_sysbios_knl_Swi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Swi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Swi_Object__PARAMS__C.__iprms,
    ((xdc_UArg)(0x0)),
    ((xdc_UArg)(0x0)),
    (xdc_UInt)(-0x0 - 1),
    (xdc_UInt)0x0,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5251 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Swi_Params__init__S().
ti_sysbios_knl_Swi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Swi_Object__sizeof ti_sysbios_knl_Swi_Object__sizeof__C = sizeof(ti_sysbios_knl_Swi_Object__)
Definition at line 5475 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Swi_Object__table ti_sysbios_knl_Swi_Object__table__C = ti_sysbios_knl_Swi_Object__table__V
Definition at line 5479 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Swi_Object__get__S().
ti_sysbios_knl_Swi_Object__table__V
ti_sysbios_knl_Swi_Object__ ti_sysbios_knl_Swi_Object__table__V
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Swi_Object__table__V[0].qElem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Swi_Object__table__V[0].qElem)),
        },
        ((xdc_Void(*)(xdc_UArg,xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Clock_workFunc__E)),
        ((xdc_UArg)(0x0)),
        ((xdc_UArg)(0x0)),
        (xdc_UInt)0xf,
        (xdc_UInt)0x8000,
        0,
        (xdc_UInt)0x0,
        (xdc_UInt)0x0,
        (ti_sysbios_knl_Queue_Handle)&ti_sysbios_knl_Swi_Module_State_0_readyQ__A[15],
        ((void*)0),
    },
}
Definition at line 1304 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_taskDisable__C
const __FAR__ CT__ti_sysbios_knl_Swi_taskDisable ti_sysbios_knl_Swi_taskDisable__C = ((CT__ti_sysbios_knl_Swi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
Definition at line 5511 of file mss_mrr_per4f.c.
ti_sysbios_knl_Swi_taskRestore__C
const __FAR__ CT__ti_sysbios_knl_Swi_taskRestore ti_sysbios_knl_Swi_taskRestore__C = ((CT__ti_sysbios_knl_Swi_taskRestore)((xdc_Fxn)ti_sysbios_knl_Task_restore__E))
Definition at line 5515 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_badAffinity__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badAffinity ti_sysbios_knl_Task_A_badAffinity__C = (((xdc_runtime_Assert_Id)1805) << 16 | 16)
Definition at line 5896 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_badPriority__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badPriority ti_sysbios_knl_Task_A_badPriority__C = (((xdc_runtime_Assert_Id)1720) << 16 | 16)
Definition at line 5888 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_badTaskState__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badTaskState ti_sysbios_knl_Task_A_badTaskState__C = (((xdc_runtime_Assert_Id)1549) << 16 | 16)
Definition at line 5876 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_badThreadType__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badThreadType ti_sysbios_knl_Task_A_badThreadType__C = (((xdc_runtime_Assert_Id)1480) << 16 | 16)
Definition at line 5872 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_badTimeout__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badTimeout ti_sysbios_knl_Task_A_badTimeout__C = (((xdc_runtime_Assert_Id)1770) << 16 | 16)
Definition at line 5892 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_invalidCoreId__C
const __FAR__ CT__ti_sysbios_knl_Task_A_invalidCoreId ti_sysbios_knl_Task_A_invalidCoreId__C = (((xdc_runtime_Assert_Id)1922) << 16 | 16)
Definition at line 5904 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_noPendElem__C
const __FAR__ CT__ti_sysbios_knl_Task_A_noPendElem ti_sysbios_knl_Task_A_noPendElem__C = (((xdc_runtime_Assert_Id)1603) << 16 | 16)
Definition at line 5880 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_sleepTaskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Task_A_sleepTaskDisabled ti_sysbios_knl_Task_A_sleepTaskDisabled__C = (((xdc_runtime_Assert_Id)1838) << 16 | 16)
Definition at line 5900 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_A_taskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Task_A_taskDisabled ti_sysbios_knl_Task_A_taskDisabled__C = (((xdc_runtime_Assert_Id)1657) << 16 | 16)
Definition at line 5884 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_allBlockedFunc__C
const __FAR__ CT__ti_sysbios_knl_Task_allBlockedFunc ti_sysbios_knl_Task_allBlockedFunc__C = ((CT__ti_sysbios_knl_Task_allBlockedFunc)0)
Definition at line 5920 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_checkStackFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_checkStackFlag ti_sysbios_knl_Task_checkStackFlag__C = 1
Definition at line 5928 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_defaultStackHeap__C
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackHeap ti_sysbios_knl_Task_defaultStackHeap__C = 0
Definition at line 5916 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_defaultStackSize__C
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackSize ti_sysbios_knl_Task_defaultStackSize__C = (xdc_SizeT)0x800
Definition at line 5912 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_deleteTerminatedTasks__C
const __FAR__ CT__ti_sysbios_knl_Task_deleteTerminatedTasks ti_sysbios_knl_Task_deleteTerminatedTasks__C = 0
Definition at line 5932 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_E_deleteNotAllowed__C
const __FAR__ CT__ti_sysbios_knl_Task_E_deleteNotAllowed ti_sysbios_knl_Task_E_deleteNotAllowed__C = (((xdc_runtime_Error_Id)4241) << 16 | 0)
Definition at line 5856 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_E_moduleStateCheckFailed__C
const __FAR__ CT__ti_sysbios_knl_Task_E_moduleStateCheckFailed ti_sysbios_knl_Task_E_moduleStateCheckFailed__C = (((xdc_runtime_Error_Id)4272) << 16 | 0)
Definition at line 5860 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_E_objectCheckFailed__C
const __FAR__ CT__ti_sysbios_knl_Task_E_objectCheckFailed ti_sysbios_knl_Task_E_objectCheckFailed__C = (((xdc_runtime_Error_Id)4345) << 16 | 0)
Definition at line 5864 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_E_objectNotInKernelSpace__C
const __FAR__ CT__ti_sysbios_knl_Task_E_objectNotInKernelSpace ti_sysbios_knl_Task_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)4412) << 16 | 0)
Definition at line 5868 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_E_spOutOfBounds__C
const __FAR__ CT__ti_sysbios_knl_Task_E_spOutOfBounds ti_sysbios_knl_Task_E_spOutOfBounds__C = (((xdc_runtime_Error_Id)4190) << 16 | 0)
Definition at line 5852 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_E_stackOverflow__C
const __FAR__ CT__ti_sysbios_knl_Task_E_stackOverflow ti_sysbios_knl_Task_E_stackOverflow__C = (((xdc_runtime_Error_Id)4147) << 16 | 0)
Definition at line 5848 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_hooks__C
const __FAR__ CT__ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__C = {0, 0}
Definition at line 5936 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_initStackFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_initStackFlag ti_sysbios_knl_Task_initStackFlag__C = 1
Definition at line 5924 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Instance_State_0_stack__A
__T1_ti_sysbios_knl_Task_Instance_State__stack ti_sysbios_knl_Task_Instance_State_0_stack__A
Definition at line 1338 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LD_block__C
const __FAR__ CT__ti_sysbios_knl_Task_LD_block ti_sysbios_knl_Task_LD_block__C = (((xdc_runtime_Log_Event)6023) << 16 | 512)
Definition at line 5820 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LD_exit__C
const __FAR__ CT__ti_sysbios_knl_Task_LD_exit ti_sysbios_knl_Task_LD_exit__C = (((xdc_runtime_Log_Event)6159) << 16 | 512)
Definition at line 5832 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LD_ready__C
const __FAR__ CT__ti_sysbios_knl_Task_LD_ready ti_sysbios_knl_Task_LD_ready__C = (((xdc_runtime_Log_Event)5982) << 16 | 512)
Definition at line 5816 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_noWork__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_noWork ti_sysbios_knl_Task_LM_noWork__C = (((xdc_runtime_Log_Event)6359) << 16 | 1024)
Definition at line 5844 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_schedule__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_schedule ti_sysbios_knl_Task_LM_schedule__C = (((xdc_runtime_Log_Event)6273) << 16 | 1024)
Definition at line 5840 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_setAffinity__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_setAffinity ti_sysbios_knl_Task_LM_setAffinity__C = (((xdc_runtime_Log_Event)6190) << 16 | 768)
Definition at line 5836 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_setPri__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_setPri ti_sysbios_knl_Task_LM_setPri__C = (((xdc_runtime_Log_Event)6103) << 16 | 768)
Definition at line 5828 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_sleep__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_sleep ti_sysbios_knl_Task_LM_sleep__C = (((xdc_runtime_Log_Event)5937) << 16 | 768)
Definition at line 5812 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_switch__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_switch ti_sysbios_knl_Task_LM_switch__C = (((xdc_runtime_Log_Event)5869) << 16 | 768)
Definition at line 5808 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_LM_yield__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_yield ti_sysbios_knl_Task_LM_yield__C = (((xdc_runtime_Log_Event)6055) << 16 | 768)
Definition at line 5824 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsEnabled ti_sysbios_knl_Task_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5740 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsIncluded ti_sysbios_knl_Task_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5744 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsMask ti_sysbios_knl_Task_Module__diagsMask__C = ((CT__ti_sysbios_knl_Task_Module__diagsMask)0)
Definition at line 5748 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__gateObj ti_sysbios_knl_Task_Module__gateObj__C = ((CT__ti_sysbios_knl_Task_Module__gateObj)0)
Definition at line 5752 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__gatePrms ti_sysbios_knl_Task_Module__gatePrms__C = ((CT__ti_sysbios_knl_Task_Module__gatePrms)0)
Definition at line 5756 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__id ti_sysbios_knl_Task_Module__id__C = (xdc_Bits16)0x801e
Definition at line 5760 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerDefined ti_sysbios_knl_Task_Module__loggerDefined__C = 0
Definition at line 5764 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn0 ti_sysbios_knl_Task_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn0)0)
Definition at line 5772 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn1 ti_sysbios_knl_Task_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn1)0)
Definition at line 5776 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn2 ti_sysbios_knl_Task_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn2)0)
Definition at line 5780 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn4 ti_sysbios_knl_Task_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn4)0)
Definition at line 5784 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn8 ti_sysbios_knl_Task_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn8)0)
Definition at line 5788 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerObj ti_sysbios_knl_Task_Module__loggerObj__C = ((CT__ti_sysbios_knl_Task_Module__loggerObj)0)
Definition at line 5768 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module__root__V
ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Task_Module__root__V.link,
    &ti_sysbios_knl_Task_Module__root__V.link},
}
Definition at line 5557 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Task_Object__first__S(), and ti_sysbios_knl_Task_Object__next__S().
ti_sysbios_knl_Task_Module__state__V
ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module__state__V
Initial value:
= {
    1,
    (xdc_UInt)0x0,
    0,
    (xdc_UInt)0x1,
    0,
    0,
    ((void*)ti_sysbios_knl_Task_Module_State_0_readyQ__A),
    ((void*)0),
    ((void*)0),
    ((void*)0),
    ((void*)0),
    ((void*)ti_sysbios_knl_Task_Module_State_0_idleTask__A),
    ((void*)0),
    1,
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_inactiveQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_inactiveQ.elem)),
        },
    },
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_terminatedQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_terminatedQ.elem)),
        },
    },
}
Definition at line 1386 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module_State_0_idleTask__A
__T1_ti_sysbios_knl_Task_Module_State__idleTask ti_sysbios_knl_Task_Module_State_0_idleTask__A
Initial value:
= {
    (ti_sysbios_knl_Task_Handle)&ti_sysbios_knl_Task_Object__table__V[0],
}
Definition at line 1383 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module_State_0_readyQ__A
__T1_ti_sysbios_knl_Task_Module_State__readyQ ti_sysbios_knl_Task_Module_State_0_readyQ__A
Definition at line 1380 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module_State_inactiveQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_inactiveQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_inactiveQ)
Definition at line 1664 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Module_State_terminatedQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_terminatedQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_terminatedQ)
Definition at line 1666 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_moduleStateCheckFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFlag ti_sysbios_knl_Task_moduleStateCheckFlag__C = 0
Definition at line 5948 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_moduleStateCheckFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFxn ti_sysbios_knl_Task_moduleStateCheckFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_moduleStateCheck__I))
Definition at line 5940 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_moduleStateCheckValueFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn ti_sysbios_knl_Task_moduleStateCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getModuleStateCheckValue__I))
Definition at line 5944 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_numConstructedTasks__C
const __FAR__ CT__ti_sysbios_knl_Task_numConstructedTasks ti_sysbios_knl_Task_numConstructedTasks__C = (xdc_UInt)0x0
Definition at line 5964 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_numPriorities__C
const __FAR__ CT__ti_sysbios_knl_Task_numPriorities ti_sysbios_knl_Task_numPriorities__C = (xdc_UInt)0x10
Definition at line 5908 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__count ti_sysbios_knl_Task_Object__count__C = 1
Definition at line 5792 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Task_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Task_Module__root__V.link,
    sizeof(ti_sysbios_knl_Task___S1) - sizeof(ti_sysbios_knl_Task_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Task_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Task_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Task_Params),
}
Definition at line 5527 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Task_construct(), ti_sysbios_knl_Task_create(), ti_sysbios_knl_Task_destruct(), ti_sysbios_knl_Task_Object__create__S(), and ti_sysbios_knl_Task_Object__delete__S().
ti_sysbios_knl_Task_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__heap ti_sysbios_knl_Task_Object__heap__C = 0
Definition at line 5796 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Task_Params ti_sysbios_knl_Task_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Task_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Task_Object__PARAMS__C.__iprms,
    ((xdc_UArg)(0x0)),
    ((xdc_UArg)(0x0)),
    (xdc_Int)0x1,
    ((xdc_Ptr)0),
    (xdc_SizeT)0x0,
    0,
    ((xdc_Ptr)0),
    1,
    (xdc_UInt)0x0,
    1,
    ((xdc_Ptr)0),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5531 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Task_Params__init__S().
ti_sysbios_knl_Task_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__sizeof ti_sysbios_knl_Task_Object__sizeof__C = sizeof(ti_sysbios_knl_Task_Object__)
Definition at line 5800 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__table ti_sysbios_knl_Task_Object__table__C = ti_sysbios_knl_Task_Object__table__V
Definition at line 5804 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_knl_Task_Object__get__S().
ti_sysbios_knl_Task_Object__table__V
ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__table__V
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Object__table__V[0].qElem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Object__table__V[0].qElem)),
        },
        (xdc_Int)0x0,
        (xdc_UInt)0x1,
        ((xdc_Ptr)0),
        ti_sysbios_knl_Task_Mode_INACTIVE,
        ((ti_sysbios_knl_Task_PendElem*)0),
        (xdc_SizeT)0x800,
        ((void*)ti_sysbios_knl_Task_Instance_State_0_stack__A),
        0,
        ((xdc_Void(*)(xdc_UArg,xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Idle_loop__E)),
        ((xdc_UArg)(0x0)),
        ((xdc_UArg)(0x0)),
        ((xdc_Ptr)0),
        ((void*)0),
        1,
        0,
        (xdc_UInt)0x0,
        (xdc_UInt)0x0,
        1,
        ((xdc_Ptr)0),
        (xdc_UInt32)0x0,
        ((xdc_Ptr)0),
    },
}
Definition at line 1357 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_objectCheckFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFlag ti_sysbios_knl_Task_objectCheckFlag__C = 0
Definition at line 5960 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_objectCheckFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFxn ti_sysbios_knl_Task_objectCheckFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_objectCheck__I))
Definition at line 5952 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_objectCheckValueFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckValueFxn ti_sysbios_knl_Task_objectCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getObjectCheckValue__I))
Definition at line 5956 of file mss_mrr_per4f.c.
ti_sysbios_knl_Task_startupHookFunc__C
const __FAR__ CT__ti_sysbios_knl_Task_startupHookFunc ti_sysbios_knl_Task_startupHookFunc__C = ((CT__ti_sysbios_knl_Task_startupHookFunc)0)
Definition at line 5968 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_A_invalidTimer__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_A_invalidTimer ti_sysbios_timers_rti_Timer_A_invalidTimer__C = (((xdc_runtime_Assert_Id)3548) << 16 | 16)
Definition at line 6157 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_anyMask__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_anyMask ti_sysbios_timers_rti_Timer_anyMask__C = (xdc_UInt)0x3
Definition at line 6177 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_continueOnSuspend__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_continueOnSuspend ti_sysbios_timers_rti_Timer_continueOnSuspend__C = 0
Definition at line 6181 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_E_cannotSupport__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_cannotSupport ti_sysbios_timers_rti_Timer_E_cannotSupport__C = (((xdc_runtime_Error_Id)5250) << 16 | 0)
Definition at line 6173 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidHwiMask ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C = (((xdc_runtime_Error_Id)5198) << 16 | 0)
Definition at line 6169 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_E_invalidTimer__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidTimer ti_sysbios_timers_rti_Timer_E_invalidTimer__C = (((xdc_runtime_Error_Id)5123) << 16 | 0)
Definition at line 6161 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_E_notAvailable__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_notAvailable ti_sysbios_timers_rti_Timer_E_notAvailable__C = (((xdc_runtime_Error_Id)5159) << 16 | 0)
Definition at line 6165 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsEnabled ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6089 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsIncluded ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6093 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsMask ti_sysbios_timers_rti_Timer_Module__diagsMask__C = ((CT__ti_sysbios_timers_rti_Timer_Module__diagsMask)0)
Definition at line 6097 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__gateObj__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gateObj ti_sysbios_timers_rti_Timer_Module__gateObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gateObj)0)
Definition at line 6101 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gatePrms ti_sysbios_timers_rti_Timer_Module__gatePrms__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gatePrms)0)
Definition at line 6105 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__id__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__id ti_sysbios_timers_rti_Timer_Module__id__C = (xdc_Bits16)0x8033
Definition at line 6109 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerDefined ti_sysbios_timers_rti_Timer_Module__loggerDefined__C = 0
Definition at line 6113 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0)0)
Definition at line 6121 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1)0)
Definition at line 6125 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2)0)
Definition at line 6129 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4)0)
Definition at line 6133 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8)0)
Definition at line 6137 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerObj ti_sysbios_timers_rti_Timer_Module__loggerObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerObj)0)
Definition at line 6117 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module__root__V
ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__root__V
Initial value:
= {
    {&ti_sysbios_timers_rti_Timer_Module__root__V.link,
    &ti_sysbios_timers_rti_Timer_Module__root__V.link},
}
Definition at line 6009 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_timers_rti_Timer_Object__first__S(), and ti_sysbios_timers_rti_Timer_Object__next__S().
ti_sysbios_timers_rti_Timer_Module__state__V
ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module__state__V
Initial value:
= {
    (xdc_UInt)0x2,
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_device__A),
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A),
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_handles__A),
}
Definition at line 1419 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module_State_0_device__A
__T1_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State_0_device__A
Initial value:
= {
    {
        (xdc_Int)0x2,
        (xdc_Int)(-0x0 - 1),
        ((xdc_Ptr)((void*)0xfffffc00)),
    },
    {
        (xdc_Int)0x3,
        (xdc_Int)(-0x0 - 1),
        ((xdc_Ptr)((void*)0xfffffc00)),
    },
}
Definition at line 1410 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module_State_0_handles__A
__T1_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State_0_handles__A
Initial value:
= {
    (ti_sysbios_timers_rti_Timer_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0],
    0,
}
Definition at line 1416 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A
__T1_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A
Initial value:
= {
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
}
Definition at line 1413 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_numTimerDevices__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_numTimerDevices ti_sysbios_timers_rti_Timer_numTimerDevices__C = (xdc_Int)0x2
Definition at line 6189 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Object__count__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__count ti_sysbios_timers_rti_Timer_Object__count__C = 1
Definition at line 6141 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_timers_rti_Timer_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_timers_rti_Timer_Module__root__V.link,
    sizeof(ti_sysbios_timers_rti_Timer___S1) - sizeof(ti_sysbios_timers_rti_Timer_Object2__),
    0,
    0,
    sizeof(ti_sysbios_timers_rti_Timer_Object2__),
    (xdc_CPtr)&ti_sysbios_timers_rti_Timer_Object__PARAMS__C,
    sizeof(ti_sysbios_timers_rti_Timer_Params),
}
Definition at line 5981 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_timers_rti_Timer_construct(), ti_sysbios_timers_rti_Timer_create(), ti_sysbios_timers_rti_Timer_destruct(), ti_sysbios_timers_rti_Timer_Object__create__S(), and ti_sysbios_timers_rti_Timer_Object__delete__S().
ti_sysbios_timers_rti_Timer_Object__heap__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__heap ti_sysbios_timers_rti_Timer_Object__heap__C = 0
Definition at line 6145 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Object__PARAMS__C
const __FAR__ ti_sysbios_timers_rti_Timer_Params ti_sysbios_timers_rti_Timer_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_timers_rti_Timer_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_timers_rti_Timer_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_ITimer_RunMode_CONTINUOUS,
    ti_sysbios_interfaces_ITimer_StartMode_AUTO,
    ((xdc_UArg)0),
    (xdc_UInt32)0x0,
    ti_sysbios_interfaces_ITimer_PeriodType_MICROSECS,
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0x0,
    },
    1,
    ((ti_sysbios_hal_Hwi_Params*)0),
    (xdc_UInt8)0x1,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5985 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_timers_rti_Timer_Params__init__S().
ti_sysbios_timers_rti_Timer_Object__sizeof__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__sizeof ti_sysbios_timers_rti_Timer_Object__sizeof__C = sizeof(ti_sysbios_timers_rti_Timer_Object__)
Definition at line 6149 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_Object__table__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__table ti_sysbios_timers_rti_Timer_Object__table__C = ti_sysbios_timers_rti_Timer_Object__table__V
Definition at line 6153 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_timers_rti_Timer_Object__get__S().
ti_sysbios_timers_rti_Timer_Object__table__V
ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__table__V
Initial value:
= {
    {
        0,
        1,
        (xdc_Int)0x0,
        ti_sysbios_interfaces_ITimer_RunMode_CONTINUOUS,
        ti_sysbios_interfaces_ITimer_StartMode_AUTO,
        (xdc_UInt)0x1,
        (xdc_UInt)0x3e8,
        ti_sysbios_interfaces_ITimer_PeriodType_MICROSECS,
        (xdc_UInt)0x2,
        ((xdc_UArg)0),
        ((xdc_Void(*)(xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I)),
        {
            (xdc_Bits32)0x0,
            (xdc_Bits32)0x0,
        },
        (ti_sysbios_hal_Hwi_Handle)&ti_sysbios_hal_Hwi_Object__table__V[0],
        1,
    },
}
Definition at line 1399 of file mss_mrr_per4f.c.
ti_sysbios_timers_rti_Timer_startupNeeded__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_startupNeeded ti_sysbios_timers_rti_Timer_startupNeeded__C = (xdc_UInt)0x1
Definition at line 6185 of file mss_mrr_per4f.c.
xdc_runtime_Assert_E_assertFailed__C
const __FAR__ CT__xdc_runtime_Assert_E_assertFailed xdc_runtime_Assert_E_assertFailed__C = (((xdc_runtime_Error_Id)3828) << 16 | 0)
Definition at line 6266 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Assert_Module__diagsEnabled xdc_runtime_Assert_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6198 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Assert_Module__diagsIncluded xdc_runtime_Assert_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6202 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Assert_Module__diagsMask xdc_runtime_Assert_Module__diagsMask__C = ((CT__xdc_runtime_Assert_Module__diagsMask)0)
Definition at line 6206 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Assert_Module__gateObj xdc_runtime_Assert_Module__gateObj__C = ((CT__xdc_runtime_Assert_Module__gateObj)0)
Definition at line 6210 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Assert_Module__gatePrms xdc_runtime_Assert_Module__gatePrms__C = ((CT__xdc_runtime_Assert_Module__gatePrms)0)
Definition at line 6214 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__id__C
const __FAR__ CT__xdc_runtime_Assert_Module__id xdc_runtime_Assert_Module__id__C = (xdc_Bits16)0x8002
Definition at line 6218 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerDefined xdc_runtime_Assert_Module__loggerDefined__C = 0
Definition at line 6222 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn0 xdc_runtime_Assert_Module__loggerFxn0__C = ((CT__xdc_runtime_Assert_Module__loggerFxn0)0)
Definition at line 6230 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn1 xdc_runtime_Assert_Module__loggerFxn1__C = ((CT__xdc_runtime_Assert_Module__loggerFxn1)0)
Definition at line 6234 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn2 xdc_runtime_Assert_Module__loggerFxn2__C = ((CT__xdc_runtime_Assert_Module__loggerFxn2)0)
Definition at line 6238 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn4 xdc_runtime_Assert_Module__loggerFxn4__C = ((CT__xdc_runtime_Assert_Module__loggerFxn4)0)
Definition at line 6242 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn8 xdc_runtime_Assert_Module__loggerFxn8__C = ((CT__xdc_runtime_Assert_Module__loggerFxn8)0)
Definition at line 6246 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerObj xdc_runtime_Assert_Module__loggerObj__C = ((CT__xdc_runtime_Assert_Module__loggerObj)0)
Definition at line 6226 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Object__count__C
const __FAR__ CT__xdc_runtime_Assert_Object__count xdc_runtime_Assert_Object__count__C = 0
Definition at line 6250 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Object__heap__C
const __FAR__ CT__xdc_runtime_Assert_Object__heap xdc_runtime_Assert_Object__heap__C = 0
Definition at line 6254 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Assert_Object__sizeof xdc_runtime_Assert_Object__sizeof__C = 0
Definition at line 6258 of file mss_mrr_per4f.c.
xdc_runtime_Assert_Object__table__C
const __FAR__ CT__xdc_runtime_Assert_Object__table xdc_runtime_Assert_Object__table__C = 0
Definition at line 6262 of file mss_mrr_per4f.c.
xdc_runtime_Core_A_initializedParams__C
const __FAR__ CT__xdc_runtime_Core_A_initializedParams xdc_runtime_Core_A_initializedParams__C = (((xdc_runtime_Assert_Id)1) << 16 | 16)
Definition at line 6343 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Core_Module__diagsEnabled xdc_runtime_Core_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6275 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Core_Module__diagsIncluded xdc_runtime_Core_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6279 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Core_Module__diagsMask xdc_runtime_Core_Module__diagsMask__C = ((CT__xdc_runtime_Core_Module__diagsMask)0)
Definition at line 6283 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Core_Module__gateObj xdc_runtime_Core_Module__gateObj__C = ((CT__xdc_runtime_Core_Module__gateObj)0)
Definition at line 6287 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Core_Module__gatePrms xdc_runtime_Core_Module__gatePrms__C = ((CT__xdc_runtime_Core_Module__gatePrms)0)
Definition at line 6291 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__id__C
const __FAR__ CT__xdc_runtime_Core_Module__id xdc_runtime_Core_Module__id__C = (xdc_Bits16)0x8003
Definition at line 6295 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerDefined xdc_runtime_Core_Module__loggerDefined__C = 0
Definition at line 6299 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn0 xdc_runtime_Core_Module__loggerFxn0__C = ((CT__xdc_runtime_Core_Module__loggerFxn0)0)
Definition at line 6307 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn1 xdc_runtime_Core_Module__loggerFxn1__C = ((CT__xdc_runtime_Core_Module__loggerFxn1)0)
Definition at line 6311 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn2 xdc_runtime_Core_Module__loggerFxn2__C = ((CT__xdc_runtime_Core_Module__loggerFxn2)0)
Definition at line 6315 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn4 xdc_runtime_Core_Module__loggerFxn4__C = ((CT__xdc_runtime_Core_Module__loggerFxn4)0)
Definition at line 6319 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn8 xdc_runtime_Core_Module__loggerFxn8__C = ((CT__xdc_runtime_Core_Module__loggerFxn8)0)
Definition at line 6323 of file mss_mrr_per4f.c.
xdc_runtime_Core_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerObj xdc_runtime_Core_Module__loggerObj__C = ((CT__xdc_runtime_Core_Module__loggerObj)0)
Definition at line 6303 of file mss_mrr_per4f.c.
xdc_runtime_Core_Object__count__C
const __FAR__ CT__xdc_runtime_Core_Object__count xdc_runtime_Core_Object__count__C = 0
Definition at line 6327 of file mss_mrr_per4f.c.
xdc_runtime_Core_Object__heap__C
const __FAR__ CT__xdc_runtime_Core_Object__heap xdc_runtime_Core_Object__heap__C = 0
Definition at line 6331 of file mss_mrr_per4f.c.
xdc_runtime_Core_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Core_Object__sizeof xdc_runtime_Core_Object__sizeof__C = 0
Definition at line 6335 of file mss_mrr_per4f.c.
xdc_runtime_Core_Object__table__C
const __FAR__ CT__xdc_runtime_Core_Object__table xdc_runtime_Core_Object__table__C = 0
Definition at line 6339 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsEnabled xdc_runtime_Defaults_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6352 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsIncluded xdc_runtime_Defaults_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6356 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsMask xdc_runtime_Defaults_Module__diagsMask__C = ((CT__xdc_runtime_Defaults_Module__diagsMask)0)
Definition at line 6360 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Defaults_Module__gateObj xdc_runtime_Defaults_Module__gateObj__C = ((CT__xdc_runtime_Defaults_Module__gateObj)0)
Definition at line 6364 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Defaults_Module__gatePrms xdc_runtime_Defaults_Module__gatePrms__C = ((CT__xdc_runtime_Defaults_Module__gatePrms)0)
Definition at line 6368 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__id__C
const __FAR__ CT__xdc_runtime_Defaults_Module__id xdc_runtime_Defaults_Module__id__C = (xdc_Bits16)0x8004
Definition at line 6372 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerDefined xdc_runtime_Defaults_Module__loggerDefined__C = 0
Definition at line 6376 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn0 xdc_runtime_Defaults_Module__loggerFxn0__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn0)0)
Definition at line 6384 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn1 xdc_runtime_Defaults_Module__loggerFxn1__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn1)0)
Definition at line 6388 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn2 xdc_runtime_Defaults_Module__loggerFxn2__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn2)0)
Definition at line 6392 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn4 xdc_runtime_Defaults_Module__loggerFxn4__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn4)0)
Definition at line 6396 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn8 xdc_runtime_Defaults_Module__loggerFxn8__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn8)0)
Definition at line 6400 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerObj xdc_runtime_Defaults_Module__loggerObj__C = ((CT__xdc_runtime_Defaults_Module__loggerObj)0)
Definition at line 6380 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Object__count__C
const __FAR__ CT__xdc_runtime_Defaults_Object__count xdc_runtime_Defaults_Object__count__C = 0
Definition at line 6404 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Object__heap__C
const __FAR__ CT__xdc_runtime_Defaults_Object__heap xdc_runtime_Defaults_Object__heap__C = 0
Definition at line 6408 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Defaults_Object__sizeof xdc_runtime_Defaults_Object__sizeof__C = 0
Definition at line 6412 of file mss_mrr_per4f.c.
xdc_runtime_Defaults_Object__table__C
const __FAR__ CT__xdc_runtime_Defaults_Object__table xdc_runtime_Defaults_Object__table__C = 0
Definition at line 6416 of file mss_mrr_per4f.c.
xdc_runtime_Diags_dictBase__C
const __FAR__ CT__xdc_runtime_Diags_dictBase xdc_runtime_Diags_dictBase__C = ((CT__xdc_runtime_Diags_dictBase)0)
Definition at line 6497 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Diags_Module__diagsEnabled xdc_runtime_Diags_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6425 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Diags_Module__diagsIncluded xdc_runtime_Diags_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6429 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Diags_Module__diagsMask xdc_runtime_Diags_Module__diagsMask__C = ((CT__xdc_runtime_Diags_Module__diagsMask)0)
Definition at line 6433 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Diags_Module__gateObj xdc_runtime_Diags_Module__gateObj__C = ((CT__xdc_runtime_Diags_Module__gateObj)0)
Definition at line 6437 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Diags_Module__gatePrms xdc_runtime_Diags_Module__gatePrms__C = ((CT__xdc_runtime_Diags_Module__gatePrms)0)
Definition at line 6441 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__id__C
const __FAR__ CT__xdc_runtime_Diags_Module__id xdc_runtime_Diags_Module__id__C = (xdc_Bits16)0x8005
Definition at line 6445 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerDefined xdc_runtime_Diags_Module__loggerDefined__C = 0
Definition at line 6449 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn0 xdc_runtime_Diags_Module__loggerFxn0__C = ((CT__xdc_runtime_Diags_Module__loggerFxn0)0)
Definition at line 6457 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn1 xdc_runtime_Diags_Module__loggerFxn1__C = ((CT__xdc_runtime_Diags_Module__loggerFxn1)0)
Definition at line 6461 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn2 xdc_runtime_Diags_Module__loggerFxn2__C = ((CT__xdc_runtime_Diags_Module__loggerFxn2)0)
Definition at line 6465 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn4 xdc_runtime_Diags_Module__loggerFxn4__C = ((CT__xdc_runtime_Diags_Module__loggerFxn4)0)
Definition at line 6469 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn8 xdc_runtime_Diags_Module__loggerFxn8__C = ((CT__xdc_runtime_Diags_Module__loggerFxn8)0)
Definition at line 6473 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerObj xdc_runtime_Diags_Module__loggerObj__C = ((CT__xdc_runtime_Diags_Module__loggerObj)0)
Definition at line 6453 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Object__count__C
const __FAR__ CT__xdc_runtime_Diags_Object__count xdc_runtime_Diags_Object__count__C = 0
Definition at line 6477 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Object__heap__C
const __FAR__ CT__xdc_runtime_Diags_Object__heap xdc_runtime_Diags_Object__heap__C = 0
Definition at line 6481 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Diags_Object__sizeof xdc_runtime_Diags_Object__sizeof__C = 0
Definition at line 6485 of file mss_mrr_per4f.c.
xdc_runtime_Diags_Object__table__C
const __FAR__ CT__xdc_runtime_Diags_Object__table xdc_runtime_Diags_Object__table__C = 0
Definition at line 6489 of file mss_mrr_per4f.c.
xdc_runtime_Diags_setMaskEnabled__C
const __FAR__ CT__xdc_runtime_Diags_setMaskEnabled xdc_runtime_Diags_setMaskEnabled__C = 0
Definition at line 6493 of file mss_mrr_per4f.c.
xdc_runtime_Error_E_generic__C
const __FAR__ CT__xdc_runtime_Error_E_generic xdc_runtime_Error_E_generic__C = (((xdc_runtime_Error_Id)3850) << 16 | 0)
Definition at line 6593 of file mss_mrr_per4f.c.
xdc_runtime_Error_E_memory__C
const __FAR__ CT__xdc_runtime_Error_E_memory xdc_runtime_Error_E_memory__C = (((xdc_runtime_Error_Id)3854) << 16 | 0)
Definition at line 6597 of file mss_mrr_per4f.c.
xdc_runtime_Error_E_msgCode__C
const __FAR__ CT__xdc_runtime_Error_E_msgCode xdc_runtime_Error_E_msgCode__C = (((xdc_runtime_Error_Id)3888) << 16 | 0)
Definition at line 6601 of file mss_mrr_per4f.c.
xdc_runtime_Error_IgnoreBlock
xdc_runtime_Error_Block xdc_runtime_Error_IgnoreBlock
Initial value:
= {
    ~0,
    {
        {0, 0}
    },
    0,
    0,
    {
        0,
        0,
        0
    }
}
Definition at line 1723 of file mss_mrr_per4f.c.
xdc_runtime_Error_maxDepth__C
const __FAR__ CT__xdc_runtime_Error_maxDepth xdc_runtime_Error_maxDepth__C = (xdc_UInt16)0x10
Definition at line 6613 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Error_Module__diagsEnabled xdc_runtime_Error_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6521 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Error_Module__diagsIncluded xdc_runtime_Error_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6525 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Error_Module__diagsMask xdc_runtime_Error_Module__diagsMask__C = ((CT__xdc_runtime_Error_Module__diagsMask)0)
Definition at line 6529 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Error_Module__gateObj xdc_runtime_Error_Module__gateObj__C = ((CT__xdc_runtime_Error_Module__gateObj)0)
Definition at line 6533 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Error_Module__gatePrms xdc_runtime_Error_Module__gatePrms__C = ((CT__xdc_runtime_Error_Module__gatePrms)0)
Definition at line 6537 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__id__C
const __FAR__ CT__xdc_runtime_Error_Module__id xdc_runtime_Error_Module__id__C = (xdc_Bits16)0x8006
Definition at line 6541 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerDefined xdc_runtime_Error_Module__loggerDefined__C = 0
Definition at line 6545 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn0 xdc_runtime_Error_Module__loggerFxn0__C = ((CT__xdc_runtime_Error_Module__loggerFxn0)0)
Definition at line 6553 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn1 xdc_runtime_Error_Module__loggerFxn1__C = ((CT__xdc_runtime_Error_Module__loggerFxn1)0)
Definition at line 6557 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn2 xdc_runtime_Error_Module__loggerFxn2__C = ((CT__xdc_runtime_Error_Module__loggerFxn2)0)
Definition at line 6561 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn4 xdc_runtime_Error_Module__loggerFxn4__C = ((CT__xdc_runtime_Error_Module__loggerFxn4)0)
Definition at line 6565 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn8 xdc_runtime_Error_Module__loggerFxn8__C = ((CT__xdc_runtime_Error_Module__loggerFxn8)0)
Definition at line 6569 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerObj xdc_runtime_Error_Module__loggerObj__C = ((CT__xdc_runtime_Error_Module__loggerObj)0)
Definition at line 6549 of file mss_mrr_per4f.c.
xdc_runtime_Error_Module__state__V
xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module__state__V
Initial value:
= {
    (xdc_UInt16)0x0,
}
Definition at line 1452 of file mss_mrr_per4f.c.
xdc_runtime_Error_Object__count__C
const __FAR__ CT__xdc_runtime_Error_Object__count xdc_runtime_Error_Object__count__C = 0
Definition at line 6573 of file mss_mrr_per4f.c.
xdc_runtime_Error_Object__heap__C
const __FAR__ CT__xdc_runtime_Error_Object__heap xdc_runtime_Error_Object__heap__C = 0
Definition at line 6577 of file mss_mrr_per4f.c.
xdc_runtime_Error_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Error_Object__sizeof xdc_runtime_Error_Object__sizeof__C = 0
Definition at line 6581 of file mss_mrr_per4f.c.
xdc_runtime_Error_Object__table__C
const __FAR__ CT__xdc_runtime_Error_Object__table xdc_runtime_Error_Object__table__C = 0
Definition at line 6585 of file mss_mrr_per4f.c.
xdc_runtime_Error_policy__C
const __FAR__ CT__xdc_runtime_Error_policy xdc_runtime_Error_policy__C = xdc_runtime_Error_UNWIND
Definition at line 6605 of file mss_mrr_per4f.c.
xdc_runtime_Error_policyFxn__C
const __FAR__ CT__xdc_runtime_Error_policyFxn xdc_runtime_Error_policyFxn__C = ((CT__xdc_runtime_Error_policyFxn)((xdc_Fxn)xdc_runtime_Error_policyDefault__E))
Definition at line 6589 of file mss_mrr_per4f.c.
xdc_runtime_Error_raiseHook__C
const __FAR__ CT__xdc_runtime_Error_raiseHook xdc_runtime_Error_raiseHook__C = ((CT__xdc_runtime_Error_raiseHook)((xdc_Fxn)ti_sysbios_BIOS_errorRaiseHook__I))
Definition at line 6609 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Gate_Module__diagsEnabled xdc_runtime_Gate_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6622 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Gate_Module__diagsIncluded xdc_runtime_Gate_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6626 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Gate_Module__diagsMask xdc_runtime_Gate_Module__diagsMask__C = ((CT__xdc_runtime_Gate_Module__diagsMask)0)
Definition at line 6630 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Gate_Module__gateObj xdc_runtime_Gate_Module__gateObj__C = ((CT__xdc_runtime_Gate_Module__gateObj)0)
Definition at line 6634 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Gate_Module__gatePrms xdc_runtime_Gate_Module__gatePrms__C = ((CT__xdc_runtime_Gate_Module__gatePrms)0)
Definition at line 6638 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__id__C
const __FAR__ CT__xdc_runtime_Gate_Module__id xdc_runtime_Gate_Module__id__C = (xdc_Bits16)0x8007
Definition at line 6642 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerDefined xdc_runtime_Gate_Module__loggerDefined__C = 0
Definition at line 6646 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn0 xdc_runtime_Gate_Module__loggerFxn0__C = ((CT__xdc_runtime_Gate_Module__loggerFxn0)0)
Definition at line 6654 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn1 xdc_runtime_Gate_Module__loggerFxn1__C = ((CT__xdc_runtime_Gate_Module__loggerFxn1)0)
Definition at line 6658 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn2 xdc_runtime_Gate_Module__loggerFxn2__C = ((CT__xdc_runtime_Gate_Module__loggerFxn2)0)
Definition at line 6662 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn4 xdc_runtime_Gate_Module__loggerFxn4__C = ((CT__xdc_runtime_Gate_Module__loggerFxn4)0)
Definition at line 6666 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn8 xdc_runtime_Gate_Module__loggerFxn8__C = ((CT__xdc_runtime_Gate_Module__loggerFxn8)0)
Definition at line 6670 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerObj xdc_runtime_Gate_Module__loggerObj__C = ((CT__xdc_runtime_Gate_Module__loggerObj)0)
Definition at line 6650 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Object__count__C
const __FAR__ CT__xdc_runtime_Gate_Object__count xdc_runtime_Gate_Object__count__C = 0
Definition at line 6674 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Object__heap__C
const __FAR__ CT__xdc_runtime_Gate_Object__heap xdc_runtime_Gate_Object__heap__C = 0
Definition at line 6678 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Gate_Object__sizeof xdc_runtime_Gate_Object__sizeof__C = 0
Definition at line 6682 of file mss_mrr_per4f.c.
xdc_runtime_Gate_Object__table__C
const __FAR__ CT__xdc_runtime_Gate_Object__table xdc_runtime_Gate_Object__table__C = 0
Definition at line 6686 of file mss_mrr_per4f.c.
xdc_runtime_IGateProvider_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IGateProvider_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 817 of file mss_mrr_per4f.c.
xdc_runtime_IHeap_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IHeap_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 808 of file mss_mrr_per4f.c.
xdc_runtime_IModule_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IModule_Interface__BASE__C = {0}
Definition at line 820 of file mss_mrr_per4f.c.
xdc_runtime_ISystemSupport_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ISystemSupport_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 814 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_construct__C
const __FAR__ CT__xdc_runtime_Log_L_construct xdc_runtime_Log_L_construct__C = (((xdc_runtime_Log_Event)5308) << 16 | 4)
Definition at line 6763 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_create__C
const __FAR__ CT__xdc_runtime_Log_L_create xdc_runtime_Log_L_create__C = (((xdc_runtime_Log_Event)5332) << 16 | 4)
Definition at line 6767 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_delete__C
const __FAR__ CT__xdc_runtime_Log_L_delete xdc_runtime_Log_L_delete__C = (((xdc_runtime_Log_Event)5372) << 16 | 4)
Definition at line 6775 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_destruct__C
const __FAR__ CT__xdc_runtime_Log_L_destruct xdc_runtime_Log_L_destruct__C = (((xdc_runtime_Log_Event)5353) << 16 | 4)
Definition at line 6771 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_error__C
const __FAR__ CT__xdc_runtime_Log_L_error xdc_runtime_Log_L_error__C = (((xdc_runtime_Log_Event)5389) << 16 | 192)
Definition at line 6779 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_info__C
const __FAR__ CT__xdc_runtime_Log_L_info xdc_runtime_Log_L_info__C = (((xdc_runtime_Log_Event)5419) << 16 | 16384)
Definition at line 6787 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_start__C
const __FAR__ CT__xdc_runtime_Log_L_start xdc_runtime_Log_L_start__C = (((xdc_runtime_Log_Event)5426) << 16 | 32768)
Definition at line 6791 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_startInstance__C
const __FAR__ CT__xdc_runtime_Log_L_startInstance xdc_runtime_Log_L_startInstance__C = (((xdc_runtime_Log_Event)5447) << 16 | 32768)
Definition at line 6799 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_stop__C
const __FAR__ CT__xdc_runtime_Log_L_stop xdc_runtime_Log_L_stop__C = (((xdc_runtime_Log_Event)5437) << 16 | 32768)
Definition at line 6795 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_stopInstance__C
const __FAR__ CT__xdc_runtime_Log_L_stopInstance xdc_runtime_Log_L_stopInstance__C = (((xdc_runtime_Log_Event)5466) << 16 | 32768)
Definition at line 6803 of file mss_mrr_per4f.c.
xdc_runtime_Log_L_warning__C
const __FAR__ CT__xdc_runtime_Log_L_warning xdc_runtime_Log_L_warning__C = (((xdc_runtime_Log_Event)5403) << 16 | 224)
Definition at line 6783 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Log_Module__diagsEnabled xdc_runtime_Log_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6695 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Log_Module__diagsIncluded xdc_runtime_Log_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6699 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Log_Module__diagsMask xdc_runtime_Log_Module__diagsMask__C = ((CT__xdc_runtime_Log_Module__diagsMask)0)
Definition at line 6703 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Log_Module__gateObj xdc_runtime_Log_Module__gateObj__C = ((CT__xdc_runtime_Log_Module__gateObj)0)
Definition at line 6707 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Log_Module__gatePrms xdc_runtime_Log_Module__gatePrms__C = ((CT__xdc_runtime_Log_Module__gatePrms)0)
Definition at line 6711 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__id__C
const __FAR__ CT__xdc_runtime_Log_Module__id xdc_runtime_Log_Module__id__C = (xdc_Bits16)0x8008
Definition at line 6715 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerDefined xdc_runtime_Log_Module__loggerDefined__C = 0
Definition at line 6719 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn0 xdc_runtime_Log_Module__loggerFxn0__C = ((CT__xdc_runtime_Log_Module__loggerFxn0)0)
Definition at line 6727 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn1 xdc_runtime_Log_Module__loggerFxn1__C = ((CT__xdc_runtime_Log_Module__loggerFxn1)0)
Definition at line 6731 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn2 xdc_runtime_Log_Module__loggerFxn2__C = ((CT__xdc_runtime_Log_Module__loggerFxn2)0)
Definition at line 6735 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn4 xdc_runtime_Log_Module__loggerFxn4__C = ((CT__xdc_runtime_Log_Module__loggerFxn4)0)
Definition at line 6739 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn8 xdc_runtime_Log_Module__loggerFxn8__C = ((CT__xdc_runtime_Log_Module__loggerFxn8)0)
Definition at line 6743 of file mss_mrr_per4f.c.
xdc_runtime_Log_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerObj xdc_runtime_Log_Module__loggerObj__C = ((CT__xdc_runtime_Log_Module__loggerObj)0)
Definition at line 6723 of file mss_mrr_per4f.c.
xdc_runtime_Log_Object__count__C
const __FAR__ CT__xdc_runtime_Log_Object__count xdc_runtime_Log_Object__count__C = 0
Definition at line 6747 of file mss_mrr_per4f.c.
xdc_runtime_Log_Object__heap__C
const __FAR__ CT__xdc_runtime_Log_Object__heap xdc_runtime_Log_Object__heap__C = 0
Definition at line 6751 of file mss_mrr_per4f.c.
xdc_runtime_Log_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Log_Object__sizeof xdc_runtime_Log_Object__sizeof__C = 0
Definition at line 6755 of file mss_mrr_per4f.c.
xdc_runtime_Log_Object__table__C
const __FAR__ CT__xdc_runtime_Log_Object__table xdc_runtime_Log_Object__table__C = 0
Definition at line 6759 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Main_Module__diagsEnabled xdc_runtime_Main_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6812 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Main_Module__diagsIncluded xdc_runtime_Main_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6816 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Main_Module__diagsMask xdc_runtime_Main_Module__diagsMask__C = ((CT__xdc_runtime_Main_Module__diagsMask)0)
Definition at line 6820 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Main_Module__gateObj xdc_runtime_Main_Module__gateObj__C = ((CT__xdc_runtime_Main_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 6824 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Main_Module__gatePrms xdc_runtime_Main_Module__gatePrms__C = ((CT__xdc_runtime_Main_Module__gatePrms)0)
Definition at line 6828 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__id__C
const __FAR__ CT__xdc_runtime_Main_Module__id xdc_runtime_Main_Module__id__C = (xdc_Bits16)0x8009
Definition at line 6832 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerDefined xdc_runtime_Main_Module__loggerDefined__C = 0
Definition at line 6836 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn0 xdc_runtime_Main_Module__loggerFxn0__C = ((CT__xdc_runtime_Main_Module__loggerFxn0)0)
Definition at line 6844 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn1 xdc_runtime_Main_Module__loggerFxn1__C = ((CT__xdc_runtime_Main_Module__loggerFxn1)0)
Definition at line 6848 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn2 xdc_runtime_Main_Module__loggerFxn2__C = ((CT__xdc_runtime_Main_Module__loggerFxn2)0)
Definition at line 6852 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn4 xdc_runtime_Main_Module__loggerFxn4__C = ((CT__xdc_runtime_Main_Module__loggerFxn4)0)
Definition at line 6856 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn8 xdc_runtime_Main_Module__loggerFxn8__C = ((CT__xdc_runtime_Main_Module__loggerFxn8)0)
Definition at line 6860 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerObj xdc_runtime_Main_Module__loggerObj__C = ((CT__xdc_runtime_Main_Module__loggerObj)0)
Definition at line 6840 of file mss_mrr_per4f.c.
xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Main_Object__count__C
const __FAR__ CT__xdc_runtime_Main_Object__count xdc_runtime_Main_Object__count__C = 0
Definition at line 6864 of file mss_mrr_per4f.c.
xdc_runtime_Main_Object__heap__C
const __FAR__ CT__xdc_runtime_Main_Object__heap xdc_runtime_Main_Object__heap__C = 0
Definition at line 6868 of file mss_mrr_per4f.c.
xdc_runtime_Main_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Main_Object__sizeof xdc_runtime_Main_Object__sizeof__C = 0
Definition at line 6872 of file mss_mrr_per4f.c.
xdc_runtime_Main_Object__table__C
const __FAR__ CT__xdc_runtime_Main_Object__table xdc_runtime_Main_Object__table__C = 0
Definition at line 6876 of file mss_mrr_per4f.c.
xdc_runtime_Memory_defaultHeapInstance__C
const __FAR__ CT__xdc_runtime_Memory_defaultHeapInstance xdc_runtime_Memory_defaultHeapInstance__C = (xdc_runtime_IHeap_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0]
Definition at line 6973 of file mss_mrr_per4f.c.
xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_Memory_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Memory_Module__diagsEnabled xdc_runtime_Memory_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6905 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Memory_Module__diagsIncluded xdc_runtime_Memory_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6909 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Memory_Module__diagsMask xdc_runtime_Memory_Module__diagsMask__C = ((CT__xdc_runtime_Memory_Module__diagsMask)0)
Definition at line 6913 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Memory_Module__gateObj xdc_runtime_Memory_Module__gateObj__C = ((CT__xdc_runtime_Memory_Module__gateObj)0)
Definition at line 6917 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Memory_Module__gatePrms xdc_runtime_Memory_Module__gatePrms__C = ((CT__xdc_runtime_Memory_Module__gatePrms)0)
Definition at line 6921 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__id__C
const __FAR__ CT__xdc_runtime_Memory_Module__id xdc_runtime_Memory_Module__id__C = (xdc_Bits16)0x800a
Definition at line 6925 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerDefined xdc_runtime_Memory_Module__loggerDefined__C = 0
Definition at line 6929 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn0 xdc_runtime_Memory_Module__loggerFxn0__C = ((CT__xdc_runtime_Memory_Module__loggerFxn0)0)
Definition at line 6937 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn1 xdc_runtime_Memory_Module__loggerFxn1__C = ((CT__xdc_runtime_Memory_Module__loggerFxn1)0)
Definition at line 6941 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn2 xdc_runtime_Memory_Module__loggerFxn2__C = ((CT__xdc_runtime_Memory_Module__loggerFxn2)0)
Definition at line 6945 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn4 xdc_runtime_Memory_Module__loggerFxn4__C = ((CT__xdc_runtime_Memory_Module__loggerFxn4)0)
Definition at line 6949 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn8 xdc_runtime_Memory_Module__loggerFxn8__C = ((CT__xdc_runtime_Memory_Module__loggerFxn8)0)
Definition at line 6953 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerObj xdc_runtime_Memory_Module__loggerObj__C = ((CT__xdc_runtime_Memory_Module__loggerObj)0)
Definition at line 6933 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Module__state__V
xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module__state__V
Initial value:
= {
    (xdc_SizeT)0x8,
}
Definition at line 1485 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Object__count__C
const __FAR__ CT__xdc_runtime_Memory_Object__count xdc_runtime_Memory_Object__count__C = 0
Definition at line 6957 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Object__heap__C
const __FAR__ CT__xdc_runtime_Memory_Object__heap xdc_runtime_Memory_Object__heap__C = 0
Definition at line 6961 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Memory_Object__sizeof xdc_runtime_Memory_Object__sizeof__C = 0
Definition at line 6965 of file mss_mrr_per4f.c.
xdc_runtime_Memory_Object__table__C
const __FAR__ CT__xdc_runtime_Memory_Object__table xdc_runtime_Memory_Object__table__C = 0
Definition at line 6969 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Registry_Module__diagsEnabled xdc_runtime_Registry_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7003 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Registry_Module__diagsIncluded xdc_runtime_Registry_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 7007 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Registry_Module__diagsMask xdc_runtime_Registry_Module__diagsMask__C = ((CT__xdc_runtime_Registry_Module__diagsMask)0)
Definition at line 7011 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Registry_Module__gateObj xdc_runtime_Registry_Module__gateObj__C = ((CT__xdc_runtime_Registry_Module__gateObj)0)
Definition at line 7015 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Registry_Module__gatePrms xdc_runtime_Registry_Module__gatePrms__C = ((CT__xdc_runtime_Registry_Module__gatePrms)0)
Definition at line 7019 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__id__C
const __FAR__ CT__xdc_runtime_Registry_Module__id xdc_runtime_Registry_Module__id__C = (xdc_Bits16)0x800b
Definition at line 7023 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerDefined xdc_runtime_Registry_Module__loggerDefined__C = 0
Definition at line 7027 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn0 xdc_runtime_Registry_Module__loggerFxn0__C = ((CT__xdc_runtime_Registry_Module__loggerFxn0)0)
Definition at line 7035 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn1 xdc_runtime_Registry_Module__loggerFxn1__C = ((CT__xdc_runtime_Registry_Module__loggerFxn1)0)
Definition at line 7039 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn2 xdc_runtime_Registry_Module__loggerFxn2__C = ((CT__xdc_runtime_Registry_Module__loggerFxn2)0)
Definition at line 7043 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn4 xdc_runtime_Registry_Module__loggerFxn4__C = ((CT__xdc_runtime_Registry_Module__loggerFxn4)0)
Definition at line 7047 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn8 xdc_runtime_Registry_Module__loggerFxn8__C = ((CT__xdc_runtime_Registry_Module__loggerFxn8)0)
Definition at line 7051 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerObj xdc_runtime_Registry_Module__loggerObj__C = ((CT__xdc_runtime_Registry_Module__loggerObj)0)
Definition at line 7031 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Module__state__V
xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module__state__V
Initial value:
= {
    ((xdc_runtime_Types_RegDesc*)0),
    (xdc_Bits16)0x7fff,
}
Definition at line 1504 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Object__count__C
const __FAR__ CT__xdc_runtime_Registry_Object__count xdc_runtime_Registry_Object__count__C = 0
Definition at line 7055 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Object__heap__C
const __FAR__ CT__xdc_runtime_Registry_Object__heap xdc_runtime_Registry_Object__heap__C = 0
Definition at line 7059 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Registry_Object__sizeof xdc_runtime_Registry_Object__sizeof__C = 0
Definition at line 7063 of file mss_mrr_per4f.c.
xdc_runtime_Registry_Object__table__C
const __FAR__ CT__xdc_runtime_Registry_Object__table xdc_runtime_Registry_Object__table__C = 0
Definition at line 7067 of file mss_mrr_per4f.c.
xdc_runtime_Startup_execImpl__C
const __FAR__ CT__xdc_runtime_Startup_execImpl xdc_runtime_Startup_execImpl__C = ((CT__xdc_runtime_Startup_execImpl)((xdc_Fxn)xdc_runtime_Startup_exec__I))
Definition at line 7214 of file mss_mrr_per4f.c.
xdc_runtime_Startup_firstFxns__A
const __T1_xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_heaps_HeapMem_init__I)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_hal_Hwi_initStack)),
}
Definition at line 1525 of file mss_mrr_per4f.c.
xdc_runtime_Startup_firstFxns__C
const __FAR__ CT__xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__C = {2, ((__T1_xdc_runtime_Startup_firstFxns *)xdc_runtime_Startup_firstFxns__A)}
Definition at line 7202 of file mss_mrr_per4f.c.
xdc_runtime_Startup_lastFxns__C
const __FAR__ CT__xdc_runtime_Startup_lastFxns xdc_runtime_Startup_lastFxns__C = {0, 0}
Definition at line 7206 of file mss_mrr_per4f.c.
xdc_runtime_Startup_maxPasses__C
const __FAR__ CT__xdc_runtime_Startup_maxPasses xdc_runtime_Startup_maxPasses__C = (xdc_Int)0x20
Definition at line 7198 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Startup_Module__diagsEnabled xdc_runtime_Startup_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7130 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Startup_Module__diagsIncluded xdc_runtime_Startup_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7134 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Startup_Module__diagsMask xdc_runtime_Startup_Module__diagsMask__C = ((CT__xdc_runtime_Startup_Module__diagsMask)0)
Definition at line 7138 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Startup_Module__gateObj xdc_runtime_Startup_Module__gateObj__C = ((CT__xdc_runtime_Startup_Module__gateObj)0)
Definition at line 7142 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Startup_Module__gatePrms xdc_runtime_Startup_Module__gatePrms__C = ((CT__xdc_runtime_Startup_Module__gatePrms)0)
Definition at line 7146 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__id__C
const __FAR__ CT__xdc_runtime_Startup_Module__id xdc_runtime_Startup_Module__id__C = (xdc_Bits16)0x800c
Definition at line 7150 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerDefined xdc_runtime_Startup_Module__loggerDefined__C = 0
Definition at line 7154 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn0 xdc_runtime_Startup_Module__loggerFxn0__C = ((CT__xdc_runtime_Startup_Module__loggerFxn0)0)
Definition at line 7162 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn1 xdc_runtime_Startup_Module__loggerFxn1__C = ((CT__xdc_runtime_Startup_Module__loggerFxn1)0)
Definition at line 7166 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn2 xdc_runtime_Startup_Module__loggerFxn2__C = ((CT__xdc_runtime_Startup_Module__loggerFxn2)0)
Definition at line 7170 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn4 xdc_runtime_Startup_Module__loggerFxn4__C = ((CT__xdc_runtime_Startup_Module__loggerFxn4)0)
Definition at line 7174 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn8 xdc_runtime_Startup_Module__loggerFxn8__C = ((CT__xdc_runtime_Startup_Module__loggerFxn8)0)
Definition at line 7178 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerObj xdc_runtime_Startup_Module__loggerObj__C = ((CT__xdc_runtime_Startup_Module__loggerObj)0)
Definition at line 7158 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Module__state__V
xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module__state__V
Initial value:
= {
    ((xdc_Int*)0),
    0,
    0,
}
Definition at line 1519 of file mss_mrr_per4f.c.
Referenced by ti_sysbios_family_arm_exc_Exception_Module__startupDone__F(), ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F(), ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F(), ti_sysbios_hal_Hwi_Module__startupDone__F(), ti_sysbios_heaps_HeapBuf_Module__startupDone__F(), ti_sysbios_knl_Clock_Module__startupDone__F(), ti_sysbios_knl_Swi_Module__startupDone__F(), ti_sysbios_knl_Task_Module__startupDone__F(), ti_sysbios_timers_rti_Timer_Module__startupDone__F(), and xdc_runtime_System_Module__startupDone__F().
xdc_runtime_Startup_Object__count__C
const __FAR__ CT__xdc_runtime_Startup_Object__count xdc_runtime_Startup_Object__count__C = 0
Definition at line 7182 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Object__heap__C
const __FAR__ CT__xdc_runtime_Startup_Object__heap xdc_runtime_Startup_Object__heap__C = 0
Definition at line 7186 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Startup_Object__sizeof xdc_runtime_Startup_Object__sizeof__C = 0
Definition at line 7190 of file mss_mrr_per4f.c.
xdc_runtime_Startup_Object__table__C
const __FAR__ CT__xdc_runtime_Startup_Object__table xdc_runtime_Startup_Object__table__C = 0
Definition at line 7194 of file mss_mrr_per4f.c.
xdc_runtime_Startup_sfxnRts__A
const __T1_xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__A
Initial value:
= {
    1,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
}
Definition at line 1561 of file mss_mrr_per4f.c.
xdc_runtime_Startup_sfxnRts__C
const __FAR__ CT__xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__C = ((CT__xdc_runtime_Startup_sfxnRts)xdc_runtime_Startup_sfxnRts__A)
Definition at line 7222 of file mss_mrr_per4f.c.
xdc_runtime_Startup_sfxnTab__A
const __T1_xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__A
Initial value:
= {
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)xdc_runtime_System_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Clock_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Swi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Task_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_heaps_HeapBuf_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_exc_Exception_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_hal_Hwi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_timers_rti_Timer_Module_startup__E)),
}
Definition at line 1558 of file mss_mrr_per4f.c.
xdc_runtime_Startup_sfxnTab__C
const __FAR__ CT__xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__C = ((CT__xdc_runtime_Startup_sfxnTab)xdc_runtime_Startup_sfxnTab__A)
Definition at line 7218 of file mss_mrr_per4f.c.
xdc_runtime_Startup_startModsFxn__C
const __FAR__ CT__xdc_runtime_Startup_startModsFxn xdc_runtime_Startup_startModsFxn__C = ((CT__xdc_runtime_Startup_startModsFxn)((xdc_Fxn)xdc_runtime_Startup_startMods__I))
Definition at line 7210 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_Startup_exec__I().
xdc_runtime_SysStd_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsEnabled xdc_runtime_SysStd_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7231 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsIncluded xdc_runtime_SysStd_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7235 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsMask xdc_runtime_SysStd_Module__diagsMask__C = ((CT__xdc_runtime_SysStd_Module__diagsMask)0)
Definition at line 7239 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__FXNS__C
const xdc_runtime_SysStd_Fxns__ xdc_runtime_SysStd_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ISystemSupport_Interface__BASE__C,
    &xdc_runtime_SysStd_Module__FXNS__C.__sfxns,
    xdc_runtime_SysStd_abort__E,
    xdc_runtime_SysStd_exit__E,
    xdc_runtime_SysStd_flush__E,
    xdc_runtime_SysStd_putch__E,
    xdc_runtime_SysStd_ready__E,
    {
        NULL,
        NULL,
        NULL,
        0x800e,
    }
}
Definition at line 941 of file mss_mrr_per4f.c.
Referenced by xdc_runtime_System_SupportProxy_Proxy__delegate__S().
xdc_runtime_SysStd_Module__gateObj__C
const __FAR__ CT__xdc_runtime_SysStd_Module__gateObj xdc_runtime_SysStd_Module__gateObj__C = ((CT__xdc_runtime_SysStd_Module__gateObj)0)
Definition at line 7243 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_SysStd_Module__gatePrms xdc_runtime_SysStd_Module__gatePrms__C = ((CT__xdc_runtime_SysStd_Module__gatePrms)0)
Definition at line 7247 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__id__C
const __FAR__ CT__xdc_runtime_SysStd_Module__id xdc_runtime_SysStd_Module__id__C = (xdc_Bits16)0x800e
Definition at line 7251 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerDefined xdc_runtime_SysStd_Module__loggerDefined__C = 0
Definition at line 7255 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn0 xdc_runtime_SysStd_Module__loggerFxn0__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn0)0)
Definition at line 7263 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn1 xdc_runtime_SysStd_Module__loggerFxn1__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn1)0)
Definition at line 7267 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn2 xdc_runtime_SysStd_Module__loggerFxn2__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn2)0)
Definition at line 7271 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn4 xdc_runtime_SysStd_Module__loggerFxn4__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn4)0)
Definition at line 7275 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn8 xdc_runtime_SysStd_Module__loggerFxn8__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn8)0)
Definition at line 7279 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerObj xdc_runtime_SysStd_Module__loggerObj__C = ((CT__xdc_runtime_SysStd_Module__loggerObj)0)
Definition at line 7259 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Object__count__C
const __FAR__ CT__xdc_runtime_SysStd_Object__count xdc_runtime_SysStd_Object__count__C = 0
Definition at line 7283 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Object__heap__C
const __FAR__ CT__xdc_runtime_SysStd_Object__heap xdc_runtime_SysStd_Object__heap__C = 0
Definition at line 7287 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Object__sizeof__C
const __FAR__ CT__xdc_runtime_SysStd_Object__sizeof xdc_runtime_SysStd_Object__sizeof__C = 0
Definition at line 7291 of file mss_mrr_per4f.c.
xdc_runtime_SysStd_Object__table__C
const __FAR__ CT__xdc_runtime_SysStd_Object__table xdc_runtime_SysStd_Object__table__C = 0
Definition at line 7295 of file mss_mrr_per4f.c.
xdc_runtime_System_A_cannotFitIntoArg__C
const __FAR__ CT__xdc_runtime_System_A_cannotFitIntoArg xdc_runtime_System_A_cannotFitIntoArg__C = (((xdc_runtime_Assert_Id)352) << 16 | 16)
Definition at line 7400 of file mss_mrr_per4f.c.
xdc_runtime_System_abortFxn__C
const __FAR__ CT__xdc_runtime_System_abortFxn xdc_runtime_System_abortFxn__C = ((CT__xdc_runtime_System_abortFxn)((xdc_Fxn)xdc_runtime_System_abortStd__E))
Definition at line 7408 of file mss_mrr_per4f.c.
xdc_runtime_System_exitFxn__C
const __FAR__ CT__xdc_runtime_System_exitFxn xdc_runtime_System_exitFxn__C = ((CT__xdc_runtime_System_exitFxn)((xdc_Fxn)xdc_runtime_System_exitStd__E))
Definition at line 7412 of file mss_mrr_per4f.c.
xdc_runtime_System_extendFxn__C
const __FAR__ CT__xdc_runtime_System_extendFxn xdc_runtime_System_extendFxn__C = ((CT__xdc_runtime_System_extendFxn)((xdc_Fxn)xdc_runtime_System_printfExtend__I))
Definition at line 7416 of file mss_mrr_per4f.c.
xdc_runtime_System_maxAtexitHandlers__C
const __FAR__ CT__xdc_runtime_System_maxAtexitHandlers xdc_runtime_System_maxAtexitHandlers__C = (xdc_Int)0x8
Definition at line 7404 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_System_Module__diagsEnabled xdc_runtime_System_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7332 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_System_Module__diagsIncluded xdc_runtime_System_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7336 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_System_Module__diagsMask xdc_runtime_System_Module__diagsMask__C = ((CT__xdc_runtime_System_Module__diagsMask)0)
Definition at line 7340 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__gateObj__C
const __FAR__ CT__xdc_runtime_System_Module__gateObj xdc_runtime_System_Module__gateObj__C = ((CT__xdc_runtime_System_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 7344 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_System_Module__gatePrms xdc_runtime_System_Module__gatePrms__C = ((CT__xdc_runtime_System_Module__gatePrms)0)
Definition at line 7348 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__id__C
const __FAR__ CT__xdc_runtime_System_Module__id xdc_runtime_System_Module__id__C = (xdc_Bits16)0x800d
Definition at line 7352 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_System_Module__loggerDefined xdc_runtime_System_Module__loggerDefined__C = 0
Definition at line 7356 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn0 xdc_runtime_System_Module__loggerFxn0__C = ((CT__xdc_runtime_System_Module__loggerFxn0)0)
Definition at line 7364 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn1 xdc_runtime_System_Module__loggerFxn1__C = ((CT__xdc_runtime_System_Module__loggerFxn1)0)
Definition at line 7368 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn2 xdc_runtime_System_Module__loggerFxn2__C = ((CT__xdc_runtime_System_Module__loggerFxn2)0)
Definition at line 7372 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn4 xdc_runtime_System_Module__loggerFxn4__C = ((CT__xdc_runtime_System_Module__loggerFxn4)0)
Definition at line 7376 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn8 xdc_runtime_System_Module__loggerFxn8__C = ((CT__xdc_runtime_System_Module__loggerFxn8)0)
Definition at line 7380 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_System_Module__loggerObj xdc_runtime_System_Module__loggerObj__C = ((CT__xdc_runtime_System_Module__loggerObj)0)
Definition at line 7360 of file mss_mrr_per4f.c.
xdc_runtime_System_Module__state__V
xdc_runtime_System_Module_State__ xdc_runtime_System_Module__state__V
Initial value:
= {
    ((void*)xdc_runtime_System_Module_State_0_atexitHandlers__A),
    (xdc_Int)0x0,
}
Definition at line 1583 of file mss_mrr_per4f.c.
xdc_runtime_System_Module_GateProxy_Module__root__V
xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__root__V
xdc_runtime_System_Module_State_0_atexitHandlers__A
__T1_xdc_runtime_System_Module_State__atexitHandlers xdc_runtime_System_Module_State_0_atexitHandlers__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
}
Definition at line 1580 of file mss_mrr_per4f.c.
xdc_runtime_System_Object__count__C
const __FAR__ CT__xdc_runtime_System_Object__count xdc_runtime_System_Object__count__C = 0
Definition at line 7384 of file mss_mrr_per4f.c.
xdc_runtime_System_Object__heap__C
const __FAR__ CT__xdc_runtime_System_Object__heap xdc_runtime_System_Object__heap__C = 0
Definition at line 7388 of file mss_mrr_per4f.c.
xdc_runtime_System_Object__sizeof__C
const __FAR__ CT__xdc_runtime_System_Object__sizeof xdc_runtime_System_Object__sizeof__C = 0
Definition at line 7392 of file mss_mrr_per4f.c.
xdc_runtime_System_Object__table__C
const __FAR__ CT__xdc_runtime_System_Object__table xdc_runtime_System_Object__table__C = 0
Definition at line 7396 of file mss_mrr_per4f.c.
xdc_runtime_Text_charCnt__C
const __FAR__ CT__xdc_runtime_Text_charCnt xdc_runtime_Text_charCnt__C = (xdc_Int16)0x1aee
Definition at line 14655 of file mss_mrr_per4f.c.
xdc_runtime_Text_charTab__A
const __T1_xdc_runtime_Text_charTab xdc_runtime_Text_charTab__A
Definition at line 1613 of file mss_mrr_per4f.c.
xdc_runtime_Text_charTab__C
const __FAR__ CT__xdc_runtime_Text_charTab xdc_runtime_Text_charTab__C = ((CT__xdc_runtime_Text_charTab)xdc_runtime_Text_charTab__A)
Definition at line 14647 of file mss_mrr_per4f.c.
xdc_runtime_Text_isLoaded__C
const __FAR__ CT__xdc_runtime_Text_isLoaded xdc_runtime_Text_isLoaded__C = 1
Definition at line 14643 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Text_Module__diagsEnabled xdc_runtime_Text_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 14563 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Text_Module__diagsIncluded xdc_runtime_Text_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 14567 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Text_Module__diagsMask xdc_runtime_Text_Module__diagsMask__C = ((CT__xdc_runtime_Text_Module__diagsMask)0)
Definition at line 14571 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Text_Module__gateObj xdc_runtime_Text_Module__gateObj__C = ((CT__xdc_runtime_Text_Module__gateObj)0)
Definition at line 14575 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Text_Module__gatePrms xdc_runtime_Text_Module__gatePrms__C = ((CT__xdc_runtime_Text_Module__gatePrms)0)
Definition at line 14579 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__id__C
const __FAR__ CT__xdc_runtime_Text_Module__id xdc_runtime_Text_Module__id__C = (xdc_Bits16)0x800f
Definition at line 14583 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerDefined xdc_runtime_Text_Module__loggerDefined__C = 0
Definition at line 14587 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn0 xdc_runtime_Text_Module__loggerFxn0__C = ((CT__xdc_runtime_Text_Module__loggerFxn0)0)
Definition at line 14595 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn1 xdc_runtime_Text_Module__loggerFxn1__C = ((CT__xdc_runtime_Text_Module__loggerFxn1)0)
Definition at line 14599 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn2 xdc_runtime_Text_Module__loggerFxn2__C = ((CT__xdc_runtime_Text_Module__loggerFxn2)0)
Definition at line 14603 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn4 xdc_runtime_Text_Module__loggerFxn4__C = ((CT__xdc_runtime_Text_Module__loggerFxn4)0)
Definition at line 14607 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn8 xdc_runtime_Text_Module__loggerFxn8__C = ((CT__xdc_runtime_Text_Module__loggerFxn8)0)
Definition at line 14611 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerObj xdc_runtime_Text_Module__loggerObj__C = ((CT__xdc_runtime_Text_Module__loggerObj)0)
Definition at line 14591 of file mss_mrr_per4f.c.
xdc_runtime_Text_Module__state__V
xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module__state__V
Initial value:
= {
    ((xdc_CPtr)(&xdc_runtime_Text_charTab__A[0])),
    ((xdc_CPtr)(&xdc_runtime_Text_nodeTab__A[0])),
}
Definition at line 1610 of file mss_mrr_per4f.c.
xdc_runtime_Text_nameEmpty__C
const __FAR__ CT__xdc_runtime_Text_nameEmpty xdc_runtime_Text_nameEmpty__C = "{empty-instance-name}"
Definition at line 14635 of file mss_mrr_per4f.c.
xdc_runtime_Text_nameStatic__C
const __FAR__ CT__xdc_runtime_Text_nameStatic xdc_runtime_Text_nameStatic__C = "{static-instance-name}"
Definition at line 14639 of file mss_mrr_per4f.c.
xdc_runtime_Text_nameUnknown__C
const __FAR__ CT__xdc_runtime_Text_nameUnknown xdc_runtime_Text_nameUnknown__C = "{unknown-instance-name}"
Definition at line 14631 of file mss_mrr_per4f.c.
xdc_runtime_Text_nodeCnt__C
const __FAR__ CT__xdc_runtime_Text_nodeCnt xdc_runtime_Text_nodeCnt__C = (xdc_Int16)0x34
Definition at line 14659 of file mss_mrr_per4f.c.
xdc_runtime_Text_nodeTab__A
const __T1_xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__A
Definition at line 1616 of file mss_mrr_per4f.c.
xdc_runtime_Text_nodeTab__C
const __FAR__ CT__xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__C = ((CT__xdc_runtime_Text_nodeTab)xdc_runtime_Text_nodeTab__A)
Definition at line 14651 of file mss_mrr_per4f.c.
xdc_runtime_Text_Object__count__C
const __FAR__ CT__xdc_runtime_Text_Object__count xdc_runtime_Text_Object__count__C = 0
Definition at line 14615 of file mss_mrr_per4f.c.
xdc_runtime_Text_Object__heap__C
const __FAR__ CT__xdc_runtime_Text_Object__heap xdc_runtime_Text_Object__heap__C = 0
Definition at line 14619 of file mss_mrr_per4f.c.
xdc_runtime_Text_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Text_Object__sizeof xdc_runtime_Text_Object__sizeof__C = 0
Definition at line 14623 of file mss_mrr_per4f.c.
xdc_runtime_Text_Object__table__C
const __FAR__ CT__xdc_runtime_Text_Object__table xdc_runtime_Text_Object__table__C = 0
Definition at line 14627 of file mss_mrr_per4f.c.
xdc_runtime_Text_registryModsLastId__C
const __FAR__ CT__xdc_runtime_Text_registryModsLastId xdc_runtime_Text_registryModsLastId__C = (xdc_UInt16)0x7fff
Definition at line 14667 of file mss_mrr_per4f.c.
xdc_runtime_Text_unnamedModsLastId__C
const __FAR__ CT__xdc_runtime_Text_unnamedModsLastId xdc_runtime_Text_unnamedModsLastId__C = (xdc_UInt16)0x4000
Definition at line 14663 of file mss_mrr_per4f.c.
xdc_runtime_Text_visitRopeFxn2__C
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn2 xdc_runtime_Text_visitRopeFxn2__C = ((CT__xdc_runtime_Text_visitRopeFxn2)((xdc_Fxn)xdc_runtime_Text_visitRope2__I))
Definition at line 14675 of file mss_mrr_per4f.c.
xdc_runtime_Text_visitRopeFxn__C
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn xdc_runtime_Text_visitRopeFxn__C = ((CT__xdc_runtime_Text_visitRopeFxn)((xdc_Fxn)xdc_runtime_Text_visitRope__I))
Definition at line 14671 of file mss_mrr_per4f.c.