TI-radar: mss_mrr_cli.c File Reference
mss_mrr_cli.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <xdc/runtime/System.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/uart/UART.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/control/mmwavelink/mmwavelink.h>
#include <ti/utils/cli/cli.h>
#include "common/mrr_config_consts.h"
#include "common/mmWave_XSS.h"
Functions
static int32_t MSS_CLISensorStart (int32_t argc, char *argv[])
This is the CLI Handler for starting the sensor.
static int32_t MSS_CLISensorStop (int32_t argc, char *argv[])
This is the CLI Handler for stopping the sensor.
static int32_t MSS_CLIBasicCfg (int32_t argc, char *argv[])
This is the CLI Handler for basic configuration.
static int32_t MSS_CLIAdvancedFrameCfg (int32_t argc, char *argv[])
This is the CLI Handler for advanced frame configuration.
void MSS_CLIInit (void)
This is the CLI Execution Task.
Function Documentation
MSS_CLIAdvancedFrameCfg()
static int32_t MSS_CLIAdvancedFrameCfg (int32_t argc, char * argv[]) static
This is the CLI Handler for advanced frame configuration.
[0] Number of arguments
[1] Arguments
Return values
Success 0
Error -1
Definition at line 221 of file mss_mrr_cli.c.
Referenced by MSS_CLIInit().
MSS_CLIBasicCfg()
static int32_t MSS_CLIBasicCfg (int32_t argc, char * argv[]) static
This is the CLI Handler for basic configuration.
[0] Number of arguments
[1] Arguments
Return values
Success 0
Error -1
Definition at line 146 of file mss_mrr_cli.c.
Referenced by MSS_CLIInit().
MSS_CLIInit()
void MSS_CLIInit (void)
This is the CLI Execution Task.
Return values
N/A
Definition at line 310 of file mss_mrr_cli.c.
References MCB_t::cfgStatus, MCB_t::commandUartHandle, MCB_t::ctrlHandle, gMCB, MCB_t::isMMWaveOpen, MSS_CLIAdvancedFrameCfg(), MSS_CLIBasicCfg(), MSS_CLISensorStart(), MSS_CLISensorStop(), and MCB_t::runningStatus.
Referenced by MSS_mmWaveInitTASK().
MSS_CLISensorStart()
static int32_t MSS_CLISensorStart (int32_t argc, char * argv[]) static
This is the CLI Handler for starting the sensor.
[0] Number of arguments
[1] Arguments
Return values
Success 0
Error -1
Definition at line 59 of file mss_mrr_cli.c.
Referenced by MSS_CLIInit().
MSS_CLISensorStop()
static int32_t MSS_CLISensorStop (int32_t argc, char * argv[]) static
This is the CLI Handler for stopping the sensor.
[0] Number of arguments
[1] Arguments
Return values
Success 0
Error -1
Definition at line 110 of file mss_mrr_cli.c.
Referenced by MSS_CLIInit().