TI-radar AWR1843 C674x DSP core: EKF_XYZ_Interface.h File Reference
EKF_XYZ_Interface.h File Reference
Interface the Extended Kalman Filter.
#include "EKF_XYZ_Consts.h"
Functions
void ekfInit (DSS_DataPathObj *restrict obj)
void ekfRun (const int32_t numMeas, trackingInputReport_t const *restrict measArray, DSS_DataPathObj *restrict obj, float const *restrict QvecList, const float td)
Detailed Description
Interface the Extended Kalman Filter.
Copyright (C) 2017 Texas Instruments Incorporated - http://www.ti.com/
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file EKF_XYZ_Interface.h.
Function Documentation
ekfInit()
void ekfInit (DSS_DataPathObj *restrict dataPathObj)
Description
This function initializes the memory used by the tracking function. It also initializes all the trackers to an invalid state, and then populates the 'process noise matrix' or 'Qmat'.
Parameters
[in] dataPathObj data path object
Return values
Not Applicable.
Definition at line 86 of file Extended_Kalman_Filter_xyz.c.
References FRAME_PERIODICITY_SEC, IS_INVALID, iX, iXd, iY, iYd, MAX_ACCEL_X_M_P_SECSQ, MAX_ACCEL_Y_M_P_SECSQ, MAX_TRK_OBJs, MRR_MAX_OBJ_OUT, N_MEASUREMENTS, N_STATES, N_UNIQ_ELEM_IN_HMAT, N_UNIQ_ELEM_IN_SYM_COVMAT, N_UNIQ_ELEM_IN_SYM_RESIDCOVMAT, and KFtrackerInstance::scratchPadFlt.
ekfRun()
void ekfRun (const int32_t numMeas, trackingInputReport_t const *restrict measArray, DSS_DataPathObj *restrict dataPathObj, float const *restrict QvecList, const float td)
Description
This function runs the kalmanfilter on a list of input data
Parameters
[in] numMeas The number of tracking inputs.
[in] measArray An array of structures holding the measurements.
[in] dataPathObj data path object
[in] QvecList A array of structures holding the 'process noise matrix.
[in] td The update rate of the measurement.
Return values
Not Applicable.
Definition at line 166 of file Extended_Kalman_Filter_xyz.c.
References AGED_OBJ_DELETION_THRESH, arrangeTracksByAge(), KFtrackerInstance::assocMeasIndx, computeHmat(), computePredictedMeas(), createNewTracks(), InitAssociatedMeasurementIndx(), initAssociatedTrackerIndx(), invalidateCurrTrack(), iRANGE, iRANGE_RATE, IS_ASSOCIATED, IS_INVALID, iSIN_AZIM, isTargetWithinDataAssociationThresh(), isWithinBoundingBox(), iY, kalmanGainComputation(), MAX_TRK_OBJs, NOT_ASSOCIATED, residualCovarianceComputation(), select_QVec(), selectMeas(), stateCovmatMeasurementUpdate(), stateCovmatTimeUpdate(), stateVecMeasurementUpdate(), stateVecTimeUpdate(), and symMatInv().