TI-radar AWR1843 C674x DSP core: Extended_Kalman_Filter_xyz.c File Reference
Extended_Kalman_Filter_xyz.c File Reference
Implements an 'Extended Kalman Filter' for radar tracking.
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <ti/mathlib/mathlib.h>
#include <ti/drivers/osal/DebugP.h>
#include <assert.h>
#include "dss_data_path.h"
#include "EKF_XYZ_Consts.h"
#include "EKF_XYZ_Interface.h"
Macros
#define DebugP_ASSERT_ENABLED 1
Functions
void InitAssociatedMeasurementIndx (int16_t *restrict assocMeasIndx, const int32_t numMeas)
void initAssociatedTrackerIndx (int16_t *restrict assocObjIndx, const int32_t numObj)
int32_t stateVecTimeUpdate (float *restrict state, const float td)
void stateCovmatTimeUpdate (float *restrict covmat, float const *restrict Qvec, const float td, KFtrackerInstance_t *restrict inst)
int32_t computePredictedMeas (float *restrict rrd, float const *restrict xyz, float *restrict p_invRange)
int32_t isTargetWithinDataAssociationThresh (float *restrict measResidual, float const *restrict state_rrd, float const *restrict meas_rrd, float const *restrict state_xyz, KFtrackerInstance_t *restrict inst, float *restrict pdistSq, int32_t tick, int32_t age)
int32_t symMatInv (float *restrict inv, float const *restrict m)
void computeHmat (float *restrict hMat, float const *restrict statevec_xyz, float const *restrict stateVec, const float invrange)
void residualCovarianceComputation (float *restrict residCovmat, float const *restrict state_covmat, float const *restrict measCovVec, float const *restrict hMat)
void kalmanGainComputation (float *restrict kalmanGain, float const *restrict state_covmat, float const *restrict hMat, float const *restrict invResidCovmat, KFtrackerInstance_t *inst)
int32_t stateVecMeasurementUpdate (float *restrict state, float const *restrict kalmanGain, float const *restrict measResidual)
void stateCovmatMeasurementUpdate (float *restrict covmat, float const *restrict kalmanGain, float const *restrict hMat, KFtrackerInstance_t *inst)
int32_t selectMeas (int16_t *restrict selectedMeas, trackingInputReport_t const *restrict measArray, int16_t *restrict assocMeasIndx, const int32_t nFree, const int32_t numUnassociatedMeas, const int32_t numMeasTotal)
void createNewTracks (DSS_DataPathObj *restrict dataPathObj, trackingInputReport_t const *restrict measArray, int16_t const *restrict freeTrackerIndxArray, int16_t const *restrict selectedIndxArr, const int32_t numSelected)
void initNewTracker (KFstate_t *restrict obj, trackingInputReport_t const *restrict meas)
float * select_QVec (float const *restrict QvecList, uint8_t tick, uint8_t age, const float range)
uint32_t isWithinBoundingBox (KFstate_t *restrict currTrack, DSS_DataPathObj *restrict dataPathObj)
void arrangeTracksByAge (KFstate_t *restrict TrackList, const uint32_t numTracksTotal)
int32_t invalidateCurrTrack (KFstate_t *restrict currTrack, int16_t *restrict freeTrackerIndxArray, int32_t nFree, int32_t iTrack)
void ekfInit (DSS_DataPathObj *restrict dataPathObj)
void ekfRun (const int32_t numMeas, trackingInputReport_t const *restrict measArray, DSS_DataPathObj *restrict dataPathObj, float const *restrict QvecList, const float td)
Detailed Description
Implements an 'Extended Kalman Filter' for radar tracking.
NOTE: (C) Copyright 2018 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file Extended_Kalman_Filter_xyz.c.
Macro Definition Documentation
DebugP_ASSERT_ENABLED
#define DebugP_ASSERT_ENABLED 1
Definition at line 44 of file Extended_Kalman_Filter_xyz.c.
Function Documentation
arrangeTracksByAge()
void arrangeTracksByAge (KFstate_t *restrict TrackList, const uint32_t numTracksTotal)
Description
Since we use a greedy algorithm to associate tracks and measurements, it is important that stable (older) tracks are associated before the newer (more unstable) tracks. This will ensure that newer tracks do not associate with measurements that would have better associated with older tracks.
Return values
Not Applicable.
Definition at line 400 of file Extended_Kalman_Filter_xyz.c.
References IS_VALID, KFstate::tick, and KFstate::validity.
Referenced by ekfRun().
computeHmat()
void computeHmat (float *restrict hMat, float const *restrict statevec_xyz, float const *restrict stateVecRrd, const float invrange)
Description
This function computes the observation matrix (hMat).
Parameters
[out] hMat a vector containing the non-zero elements of the hmat.
[in] statevec_xyz predicted state (in x y co-ordinates)
[in] stateVecRrd predicted measurents.
[in] invrange 1/r - computed in the computePredictedMeas function.
Return values
Not Applicable.
Definition at line 819 of file Extended_Kalman_Filter_xyz.c.
References iRANGE_RATE, iSIN_AZIM, iXd, iY, and iYd.
Referenced by ekfRun().
computePredictedMeas()
int32_t computePredictedMeas (float *restrict rrd, float const *restrict xyz, float *restrict p_invRange)
Description
This function computes the predicted measurements from the state vector. i.e. R = H(x);
Parameters
[out] rrd predicted measurement.
[in] xyz state.
[in] p_invRange The inv sqrt of the range is also computed and used in the hMat computation.
Return values
Not Applicable.
Definition at line 595 of file Extended_Kalman_Filter_xyz.c.
References iRANGE, iRANGE_RATE, IS_INVALID, IS_VALID, iSIN_AZIM, iX, iXd, iY, and iYd.
Referenced by ekfRun().
createNewTracks()
void createNewTracks (DSS_DataPathObj *restrict dataPathObj, trackingInputReport_t const *restrict measArray, int16_t const *restrict freeTrackerIndxArray, int16_t const *restrict selectedIndxArr, const int32_t numSelected)
Description
This function creates new tracks.
Parameters
[in,out] dataPathObj Data path object - for the 'trackerState' struct array.
[in] measArray List of input measurements
[in] freeTrackerIndexArray Number of free tracks.
[in] selectedIndxArr An array of the selected measurements for new tracks.
[in] numSelected. number of selected measurements.
Return values
not applicable
Definition at line 1313 of file Extended_Kalman_Filter_xyz.c.
References initNewTracker(), and IS_VALID.
Referenced by ekfRun().
ekfInit()
void ekfInit (DSS_DataPathObj *restrict dataPathObj)
Description
This function initializes the memory used by the tracking function. It also initializes all the trackers to an invalid state, and then populates the 'process noise matrix' or 'Qmat'.
Parameters
[in] dataPathObj data path object
Return values
Not Applicable.
Definition at line 86 of file Extended_Kalman_Filter_xyz.c.
References FRAME_PERIODICITY_SEC, IS_INVALID, iX, iXd, iY, iYd, MAX_ACCEL_X_M_P_SECSQ, MAX_ACCEL_Y_M_P_SECSQ, MAX_TRK_OBJs, MRR_MAX_OBJ_OUT, N_MEASUREMENTS, N_STATES, N_UNIQ_ELEM_IN_HMAT, N_UNIQ_ELEM_IN_SYM_COVMAT, N_UNIQ_ELEM_IN_SYM_RESIDCOVMAT, and KFtrackerInstance::scratchPadFlt.
ekfRun()
void ekfRun (const int32_t numMeas, trackingInputReport_t const *restrict measArray, DSS_DataPathObj *restrict dataPathObj, float const *restrict QvecList, const float td)
Description
This function runs the kalmanfilter on a list of input data
Parameters
[in] numMeas The number of tracking inputs.
[in] measArray An array of structures holding the measurements.
[in] dataPathObj data path object
[in] QvecList A array of structures holding the 'process noise matrix.
[in] td The update rate of the measurement.
Return values
Not Applicable.
Definition at line 166 of file Extended_Kalman_Filter_xyz.c.
References AGED_OBJ_DELETION_THRESH, arrangeTracksByAge(), KFtrackerInstance::assocMeasIndx, computeHmat(), computePredictedMeas(), createNewTracks(), InitAssociatedMeasurementIndx(), initAssociatedTrackerIndx(), invalidateCurrTrack(), iRANGE, iRANGE_RATE, IS_ASSOCIATED, IS_INVALID, iSIN_AZIM, isTargetWithinDataAssociationThresh(), isWithinBoundingBox(), iY, kalmanGainComputation(), MAX_TRK_OBJs, NOT_ASSOCIATED, residualCovarianceComputation(), select_QVec(), selectMeas(), stateCovmatMeasurementUpdate(), stateCovmatTimeUpdate(), stateVecMeasurementUpdate(), stateVecTimeUpdate(), and symMatInv().
InitAssociatedMeasurementIndx()
void InitAssociatedMeasurementIndx (int16_t *restrict assocMeasIndx, const int32_t numMeas)
Description
This function initializes the assocMeasIndx to state that no measurements have been associated to an existing tracker.
Parameters
[in] assocMeasIndx An array that will hold the mapping of the incoming measurement to the existing tracker to which it is associated to.
[in] nuMeas number of measurement (for this epoch).
Return values
Not Applicable.
Definition at line 454 of file Extended_Kalman_Filter_xyz.c.
References NOT_ASSOCIATED.
Referenced by ekfRun().
initAssociatedTrackerIndx()
void initAssociatedTrackerIndx (int16_t *restrict freeTrackerIndxArray, const int32_t numObj)
Description
This function initializes the freeTrackerIndxArray to state that no objects have been associated to an existing measurement.
Parameters
[in] freeTrackerIndxArray An array that will hold the mapping of the existing tracker to a measurement.
[in] numObj number of trackers (for this epoch).
Return values
Not Applicable.
Definition at line 477 of file Extended_Kalman_Filter_xyz.c.
References NOT_ASSOCIATED.
Referenced by ekfRun().
initNewTracker()
void initNewTracker (KFstate_t *restrict obj, trackingInputReport_t const *restrict meas)
Description
This function initialzes a new tracker.
Parameters
[out] obj pointer to the new tracker's state.
[in] meas set of measurements to initialize the tracker.
Return values
not applicable
Definition at line 1354 of file Extended_Kalman_Filter_xyz.c.
References iRANGE, iRANGE_RATE, iSIN_AZIM, iX, iXd, iXdXd, iXX, iY, iYd, iYdYd, iYY, and N_UNIQ_ELEM_IN_SYM_COVMAT.
Referenced by createNewTracks().
invalidateCurrTrack()
int32_t invalidateCurrTrack (KFstate_t *restrict currTrack, int16_t *restrict freeTrackerIndxArray, int32_t nFree, int32_t iTrack)
Description
This function invalidates a track by marking it as invalid, marking its index as invalid, incrementing the number of free tracks.
Parameters
[in,out] currTrack pointer to the tracker's state.
[in,out] freeTrackerIndxArray List of unassociated trackers.
[in] nFree current number of free trackers.
[in] iTrack current track Index.
Return values
updated number of free trackers.
Definition at line 1518 of file Extended_Kalman_Filter_xyz.c.
References IS_INVALID.
Referenced by ekfRun().
isTargetWithinDataAssociationThresh()
int32_t isTargetWithinDataAssociationThresh (float *restrict measResidual, float const *restrict state_rrd, float const *restrict meas_rrd, float const *restrict state_xyz, KFtrackerInstance_t *restrict inst, float *restrict pdistSq, int32_t tick, int32_t age)
Description
This function checks whether the predicted measurements are close to the new measurements (i.e. can they be associated). If they can be then the mean sq distance between the predicted and the new is passed back, so that the closest measurement is used.
Track association is not a traditional part of Kalman filtering, and hence our approach (based on experiment) is ad-hoc.
Parameters
[out] measResidual measurement residual.
[in] state_rrd predicted measurents.
[in] meas_rrd new measurements.
[in] state_xyz predicted state (in x y co-ordinates)
[in] inst KFtrackerInstance_t object (for scratchpad.)
[out] pdistSq The distance sq between predicted and new measurement. Only valid if the measurement is deemed to be 'associatable'.
[in] tick age of the Track. Newer tracks are given more leeway & in associating, as they take some time to converge.
Return values
IS_ASSOCIATED or NOT_ASSOCIATED.
Definition at line 648 of file Extended_Kalman_Filter_xyz.c.
References iRANGE, iRANGE_RATE, IS_ASSOCIATED, iSIN_AZIM, iX, iY, and NOT_ASSOCIATED.
Referenced by ekfRun().
isWithinBoundingBox()
uint32_t isWithinBoundingBox (KFstate_t *restrict currTrack, DSS_DataPathObj *restrict dataPathObj)
Description
This function validates a state by checking whether it is within a specific bounding box. For e.g if an object is behind the radar, there is no need to track it.
Parameters
[out] currTrack pointer to the tracker's state.
[in] dataPathObj data path object -> for max range.
Return values
true/false
Definition at line 1455 of file Extended_Kalman_Filter_xyz.c.
References IS_INVALID, IS_VALID, iX, iY, N_STATES, and N_UNIQ_ELEM_IN_SYM_COVMAT.
Referenced by ekfRun().
kalmanGainComputation()
void kalmanGainComputation (float *restrict kalmanGain, float const *restrict state_covmat, float const *restrict hMat, float const *restrict invResidCovmat, KFtrackerInstance_t * inst)
Description
This function performs the (near-optimal) kalman gain computation. i.e. in matlab kalmanGain = state_covmat*transpose(hMat)*inv(residCovmat)
Parameters
[out] kalmanGain kalman gain matrix.
[in] state_covmat state covariance matrix.
[in] hMat (observation matrix) Hmat
[in] measCovVec inverse of the residual covMat.
[in] inst KFtrackerInstance_t object (for scratchpad.)
Return values
Not Applicable.
Definition at line 962 of file Extended_Kalman_Filter_xyz.c.
References iAzAz, iRAz, iRdAz, iRdRd, iRR, iRRd, iXdXd, iXdYd, iXX, iXXd, iXY, iXYd, iYdYd, iYXd, iYY, iYYd, and KFtrackerInstance::kalmanGainTemp.
Referenced by ekfRun().
residualCovarianceComputation()
void residualCovarianceComputation (float *restrict residCovmat, float const *restrict state_covmat, float const *restrict measCovVec, float const *restrict hMat)
Description
This function performs the residual covariance matrix computation. i.e. residCovmat = hMat*state_covmat*transpose(hMat) + measCovVec
Parameters
[out] residCovmat residual covariance matrix.
[in] state_covmat state covariance matrix.
[in] measCovVec variance of the measurement.
[in] hMat (observation matrix) Hmat
Return values
Not Applicable.
Definition at line 861 of file Extended_Kalman_Filter_xyz.c.
References iAzAz, iRANGE, iRANGE_RATE, iRAz, iRdAz, iRdRd, iRR, iRRd, iSIN_AZIM, iXdXd, iXdYd, iXX, iXXd, iXY, iXYd, iYdYd, iYXd, iYY, and iYYd.
Referenced by ekfRun().
select_QVec()
float * select_QVec (float const *restrict QvecList, uint8_t tick, uint8_t age, const float range)
Description
This function selects a 'process noise matrix' based on the age of the tracker. If the tracker is new, then the 'process noise' is assumed to be high, so as to allow faster convergence. If the tracker is old, the process noise is computed as per the the unmodeled parameters. We also allow higher 'process noise' for closer objects, assuming that their higher SNR will compensate for the noisier measurements.
Parameters
[in] QvecList 3 arrays [N_STATES] long. A list of possible Qvec matrices.
[in] tick the number of valid association of the tracker.
[in] age the age of the tracker (i.e. the number of ticks before the last associated measurement).
[in] range the distance of the target being tracked.
Return values
pointer to the 'process noise diagonal'
Definition at line 1418 of file Extended_Kalman_Filter_xyz.c.
References N_STATES.
Referenced by ekfRun().
selectMeas()
int32_t selectMeas (int16_t *restrict selectedMeas, trackingInputReport_t const *restrict measArray, int16_t *restrict assocMeasIndx, const int32_t nFree, const int32_t numUnassociatedMeas, const int32_t numMeasTotal)
Description
This function selects the unassociated measurements that are to be used to create the new tracks.
Parameters
[out] selectedMeas The unassociated measurements selected for tracking.
[in] measArray List of input measurements
[in] assocMeasIndx An array declaring whether a measurement has been associated or not.
[in] nFree Number of free tracks.
[in] numUnassociatedMeas Number of unassociated measurements.
[in] numMeasTotal. Total number of measurements.
Return values
number of selected measurements. .
Definition at line 1244 of file Extended_Kalman_Filter_xyz.c.
References HIGH_SNR_RVAR_THRESH, iRANGE, IS_ASSOCIATED, and NOT_ASSOCIATED.
Referenced by ekfRun().
stateCovmatMeasurementUpdate()
void stateCovmatMeasurementUpdate (float *restrict covmat, float const *restrict const kalmanGain, float const *restrict const hMat, KFtrackerInstance_t * inst)
Description
This function performs the state covariance matrix update. i.e. in matlab P = (I - KH)*P
Parameters
[in,out] covmat updated state covariance matrix (P).
[in] kalmanGain Kalman gain (K).
[in] hMat observation matrix (H).
[in] KFtrackerInstance_t scratchpad pointers.
Return values
Not Applicable.
Definition at line 1129 of file Extended_Kalman_Filter_xyz.c.
References iXdXd, iXdYd, iXX, iXXd, iXY, iXYd, iYdYd, iYXd, iYY, iYYd, N_MEASUREMENTS, N_STATES, N_UNIQ_ELEM_IN_SYM_COVMAT, KFtrackerInstance::stateCovMattemp, and KFtrackerInstance::stateCovMattempP.
Referenced by ekfRun().
stateCovmatTimeUpdate()
void stateCovmatTimeUpdate (float *restrict covmat, float const *restrict Q, const float td, KFtrackerInstance_t *restrict inst)
Description
This function updates the state covariance matrix.
Parameters
[out] covmat state covariance matrix.
[in] Q process noise diagonal .
[in] td time delta.
[in] inst KFtrackerInstance_t (for scratchpad).
Return values
Not Applicable.
Definition at line 526 of file Extended_Kalman_Filter_xyz.c.
References iX, iXd, iXdXd, iXdYd, iXX, iXXd, iXY, iXYd, iY, iYd, iYdYd, iYXd, iYY, iYYd, and N_UNIQ_ELEM_IN_SYM_COVMAT.
Referenced by ekfRun().
stateVecMeasurementUpdate()
int32_t stateVecMeasurementUpdate (float *restrict state, float const *restrict kalmanGain, float const *restrict meas_residual)
Description
This function performs the state measurement update. i.e. in matlab state = state + kalmanGain*measResidual
Parameters
[in,out] state updated state .
[in] kalmanGain kalman gain matrix.
[in] meas_residual measurement residual.
Return values
Not Applicable.
Definition at line 1089 of file Extended_Kalman_Filter_xyz.c.
References IS_INVALID, IS_VALID, iY, N_MEASUREMENTS, and N_STATES.
Referenced by ekfRun().
stateVecTimeUpdate()
int32_t stateVecTimeUpdate (float *restrict state, const float td)
Description
This function updates the state vector.
Parameters
[in] state state vector.
[in] td time delta.
Return values
Is the object behind the radar?.
Definition at line 497 of file Extended_Kalman_Filter_xyz.c.
References IS_INVALID, IS_VALID, iX, iXd, iY, and iYd.
Referenced by ekfRun().
symMatInv()
int32_t symMatInv (float *restrict inv, float const *restrict m)
Description
This function computes the inverse of a symettric N_MEASUREMENTS x N_MEASUREMENTS matrix.
Parameters
[out] inv inverted matrix.
[in] m input matrix.
Return values
Not Applicable.
Definition at line 752 of file Extended_Kalman_Filter_xyz.c.
References EPS, and N_UNIQ_ELEM_IN_SYM_RESIDCOVMAT.
Referenced by ekfRun().