TI-radar AWR1843 C674x DSP core: clusteringDBscan.h File Reference
clusteringDBscan.h File Reference
DBscan clustering module.
Macros
#define POINT_UNKNOWN 0
#defines for the state of the detected points w.r.t to the clustering algorithms.
#define POINT_VISITED 1
Functions
uint16_t clusteringDBscan_findNeighbors2Fixed (MmwDemo_detectedObjActual *restrict detObj2D, uint16_t point, uint16_t *restrict neigh, uint16_t numPoints, int32_t epsilon2, int32_t epsilon, float weight, int32_t vFactor, char *restrict visited, uint16_t *restrict newCount, uint16_t dBScanNeighbourLim)
void clusteringDBscan_calcInfoFixed (uint16_t clusterOriginator, MmwDemo_detectedObjActual *restrict detObj2D, uint16_t *restrict neighStart, uint16_t *restrict neighLast, clusteringDBscanReport_t *restrict report, trackingInputReport_t *restrict trackingInput, DSS_DataPathObj *obj)
int32_t clusteringDBscanRun (clusteringDBscanInstance_t *inst, DSS_DataPathObj *obj, uint16_t numDetetectedObj, clusteringDBscanOutput_t *output, trackingInputReport_t *trackingInput)
Detailed Description
DBscan clustering module.
Copyright (C) 2017 Texas Instruments Incorporated - http://www.ti.com/
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file clusteringDBscan.h.
Macro Definition Documentation
POINT_UNKNOWN
#define POINT_UNKNOWN 0
#defines for the state of the detected points w.r.t to the clustering algorithms.
Definition at line 45 of file clusteringDBscan.h.
POINT_VISITED
#define POINT_VISITED 1
Definition at line 46 of file clusteringDBscan.h.
Function Documentation
clusteringDBscan_calcInfoFixed()
void clusteringDBscan_calcInfoFixed (uint16_t clusterOriginator, MmwDemo_detectedObjActual *restrict detObj2D, uint16_t *restrict neighStart, uint16_t *restrict neighLast, clusteringDBscanReport_t *restrict report, trackingInputReport_t *restrict trackingInput, DSS_DataPathObj * obj)
Definition at line 355 of file clusteringDBscan.c.
Referenced by clusteringDBscanRun().
clusteringDBscan_findNeighbors2Fixed()
uint16_t clusteringDBscan_findNeighbors2Fixed (MmwDemo_detectedObjActual *restrict detObj2D, uint16_t point, uint16_t *restrict neigh, uint16_t numPoints, int32_t epsilon2, int32_t epsilon, float weight, int32_t vFactor, char *restrict visited, uint16_t *restrict newCount, uint16_t dBScanNeighbourLim)
Definition at line 247 of file clusteringDBscan.c.
References POINT_VISITED.
Referenced by clusteringDBscanRun().
clusteringDBscanRun()
int32_t clusteringDBscanRun (clusteringDBscanInstance_t * inst, DSS_DataPathObj * obj, uint16_t numDetetectedObj, clusteringDBscanOutput_t * output, trackingInputReport_t * trackingInput)
Definition at line 79 of file clusteringDBscan.c.
References clusteringDBscan_calcInfoFixed(), clusteringDBscan_findNeighbors2Fixed(), DBSCAN_ERROR_CLUSTER_LIMIT_REACHED, DBSCAN_OK, clusteringDBscanInstance::dBScanNeighbourLim, DSS_DataPathObj_t::detObj2D, clusteringDBscanInstance::epsilon, clusteringDBscanInstance::fixedPointScale, clusteringDBscanOutput::IndexArray, clusteringDBscanInstance::maxClusters, clusteringDBscanInstance::minPointsInCluster, clusteringDBscanInstance::neighbors, clusteringDBscanOutput::numCluster, POINT_UNKNOWN, POINT_VISITED, clusteringDBscanOutput::report, clusteringDBscanInstance::scope, clusteringDBscanInstance::vFactor, clusteringDBscanInstance::visited, and clusteringDBscanInstance::weight.