TI-radar AWR1843 C674x DSP core: dss_config_edma_util.c File Reference
dss_config_edma_util.c File Reference
EDMA Configuration Utility API implementation.
#include <xdc/runtime/System.h>
#include <ti/drivers/edma/edma.h>
#include "dss_config_edma_util.h"
Macros
#define MAX(x, y) ((x) > (y) ? (x) : (y))
Functions
static int32_t EDMA_setup_shadow_link (EDMA_Handle handle, uint8_t chId, uint16_t shadowParamId, EDMA_paramSetConfig_t *config, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_configType1 (EDMA_Handle handle, uint8_t *srcBuff, uint8_t *dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t aCount, uint16_t bCount, int16_t srcBIdx, int16_t dstBIdx, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_configType2a (EDMA_Handle handle, uint8_t *srcBuff, uint8_t *dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t sampleLenInBytes, uint16_t numRangeBins, uint8_t numTxAnt, uint8_t numRxAnt, uint16_t numDopplerBins, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_configType2b (EDMA_Handle handle, uint8_t *srcBuff, uint8_t *dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t sampleLenInBytes, uint16_t numRangeBins, uint8_t numTxAnt, uint8_t numRxAnt, uint16_t numDopplerBins, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_configType3 (EDMA_Handle handle, uint8_t *srcBuff, uint8_t *dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t aCount, uint16_t bCount, int16_t srcBIdx, int16_t destBIdx, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_triggerType3 (EDMA_Handle handle, uint8_t *srcBuff, uint8_t *dstBuff, uint8_t chId, uint8_t triggerEnabled)
Detailed Description
EDMA Configuration Utility API implementation.
NOTE: (C) Copyright 2018 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file dss_config_edma_util.c.
Macro Definition Documentation
MAX
#define MAX (x, y) ((x) > (y) ? (x) : (y))
Definition at line 44 of file dss_config_edma_util.c.
Function Documentation
EDMA_setup_shadow_link()
static int32_t EDMA_setup_shadow_link (EDMA_Handle handle, uint8_t chId, uint16_t shadowParamId, EDMA_paramSetConfig_t * config, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg) static
Definition at line 51 of file dss_config_edma_util.c.
Referenced by EDMAutil_configType1(), EDMAutil_configType2a(), EDMAutil_configType2b(), and EDMAutil_configType3().
EDMAutil_configType1()
int32_t EDMAutil_configType1 (EDMA_Handle handle, uint8_t * srcBuff, uint8_t * dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t aCount, uint16_t bCount, int16_t srcBIdx, int16_t dstBIdx, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Definition at line 86 of file dss_config_edma_util.c.
References EDMA_setup_shadow_link().
Referenced by MmwDemo_dataPathConfigEdma().
EDMAutil_configType2a()
int32_t EDMAutil_configType2a (EDMA_Handle handle, uint8_t * srcBuff, uint8_t * dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t sampleLenInBytes, uint16_t numRangeBins, uint8_t numTxAnt, uint8_t numRxAnt, uint16_t numDopplerBins, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Definition at line 153 of file dss_config_edma_util.c.
References EDMA_setup_shadow_link().
Referenced by MmwDemo_dataPathConfigEdma().
EDMAutil_configType2b()
int32_t EDMAutil_configType2b (EDMA_Handle handle, uint8_t * srcBuff, uint8_t * dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t sampleLenInBytes, uint16_t numRangeBins, uint8_t numTxAnt, uint8_t numRxAnt, uint16_t numDopplerBins, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Definition at line 220 of file dss_config_edma_util.c.
References EDMA_setup_shadow_link(), and MAX.
EDMAutil_configType3()
int32_t EDMAutil_configType3 (EDMA_Handle handle, uint8_t * srcBuff, uint8_t * dstBuff, uint8_t chId, bool isEventTriggered, uint16_t shadowParamId, uint16_t aCount, uint16_t bCount, int16_t srcBIdx, int16_t destBIdx, uint8_t eventQueueId, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Definition at line 297 of file dss_config_edma_util.c.
References EDMA_setup_shadow_link().
Referenced by MmwDemo_dataPathConfigEdma().
EDMAutil_triggerType3()
int32_t EDMAutil_triggerType3 (EDMA_Handle handle, uint8_t * srcBuff, uint8_t * dstBuff, uint8_t chId, uint8_t triggerEnabled)
Definition at line 364 of file dss_config_edma_util.c.
Referenced by MmwDemo_processChirp().