TI-radar AWR1843 C674x DSP core: Debug/configPkg/package/cfg/dss_mrr_pe674.c File Reference
dss_mrr_pe674.c File Reference
#include <xdc/std.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/family/c62/IntrinsicsSupport.h>
#include <ti/sysbios/family/c62/TaskSupport.h>
#include <ti/sysbios/family/c64p/Cache.h>
#include <ti/sysbios/family/c64p/EventCombiner.h>
#include <ti/sysbios/family/c64p/Exception.h>
#include <ti/sysbios/family/c64p/Hwi.h>
#include <ti/sysbios/family/c64p/TimestampProvider.h>
#include <ti/sysbios/gates/GateHwi.h>
#include <ti/sysbios/gates/GateMutex.h>
#include <ti/sysbios/hal/Hwi.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Idle.h>
#include <ti/sysbios/knl/Intrinsics.h>
#include <ti/sysbios/knl/Queue.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/rts/ti/ThreadLocalStorage.h>
#include <ti/sysbios/timers/rti/Timer.h>
#include <ti/sysbios/utils/Load.h>
#include <xdc/runtime/Assert.h>
#include <xdc/runtime/Core.h>
#include <xdc/runtime/Defaults.h>
#include <xdc/runtime/Diags.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Gate.h>
#include <xdc/runtime/Log.h>
#include <xdc/runtime/Main.h>
#include <xdc/runtime/Memory.h>
#include <xdc/runtime/Registry.h>
#include <xdc/runtime/Startup.h>
#include <xdc/runtime/SysStd.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Text.h>
#include <xdc/runtime/Timestamp.h>
#include <xdc/runtime/TimestampNull.h>
#include <limits.h>
#include <xdc/runtime/Types.h>
#include <xdc/runtime/System__internal.h>
#include <_lock.h>
#include <ti/sysbios/hal/Core.h>
#include <string.h>
Data Structures
struct ti_sysbios_BIOS_RtsGateProxy_Module__
struct ti_sysbios_knl_Queue_Object__
struct ti_sysbios_knl_Queue_Object2__
struct ti_sysbios_knl_Semaphore_Object__
struct ti_sysbios_knl_Semaphore_Object2__
struct ti_sysbios_gates_GateMutex_Object__
struct ti_sysbios_gates_GateMutex_Object2__
struct ti_sysbios_BIOS_RtsGateProxy_Object2__
struct ti_sysbios_family_c64p_Hwi_Module__
struct ti_sysbios_family_c64p_Hwi_Object__
struct ti_sysbios_family_c64p_Hwi_Object2__
struct ti_sysbios_gates_GateHwi_Module__
struct ti_sysbios_gates_GateHwi_Object__
struct ti_sysbios_gates_GateHwi_Object2__
struct ti_sysbios_gates_GateMutex_Module__
struct ti_sysbios_hal_Hwi_Module__
struct ti_sysbios_hal_Hwi_Object__
struct ti_sysbios_hal_Hwi_Object2__
struct ti_sysbios_hal_Hwi_HwiProxy_Module__
struct ti_sysbios_hal_Hwi_HwiProxy_Object2__
struct ti_sysbios_heaps_HeapMem_Module__
struct ti_sysbios_heaps_HeapMem_Object__
struct ti_sysbios_heaps_HeapMem_Object2__
struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Object2__
struct ti_sysbios_knl_Clock_Module__
struct ti_sysbios_knl_Clock_Object__
struct ti_sysbios_knl_Clock_Object2__
struct ti_sysbios_knl_Clock_TimerProxy_Module__
struct ti_sysbios_timers_rti_Timer_Object__
struct ti_sysbios_timers_rti_Timer_Object2__
struct ti_sysbios_knl_Clock_TimerProxy_Object2__
struct ti_sysbios_knl_Event_Module__
struct ti_sysbios_knl_Event_Object__
struct ti_sysbios_knl_Event_Object2__
struct ti_sysbios_knl_Queue_Module__
struct ti_sysbios_knl_Semaphore_Module__
struct ti_sysbios_knl_Task_Module__
struct ti_sysbios_knl_Task_Object__
struct ti_sysbios_knl_Task_Object2__
struct ti_sysbios_timers_rti_Timer_Module__
struct xdc_runtime_Main_Module_GateProxy_Module__
struct xdc_runtime_Main_Module_GateProxy_Object2__
struct xdc_runtime_Memory_HeapProxy_Module__
struct xdc_runtime_Memory_HeapProxy_Object2__
struct xdc_runtime_System_Module_GateProxy_Module__
struct xdc_runtime_System_Module_GateProxy_Object2__
struct ti_sysbios_BIOS_Module_State__
struct ti_sysbios_family_c64p_Cache_Module_State__
struct ti_sysbios_family_c64p_EventCombiner_Module_State__
struct ti_sysbios_family_c64p_Exception_Module_State__
struct ti_sysbios_family_c64p_Hwi_Module_State__
struct ti_sysbios_knl_Clock_Module_State__
struct ti_sysbios_knl_Task_Module_State__
struct ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__
struct ti_sysbios_timers_rti_Timer_Module_State__
struct ti_sysbios_utils_Load_Module_State__
struct xdc_runtime_Error_Module_State__
struct xdc_runtime_Memory_Module_State__
struct xdc_runtime_Registry_Module_State__
struct xdc_runtime_Startup_Module_State__
struct xdc_runtime_System_Module_State__
struct xdc_runtime_Text_Module_State__
union Header
struct ti_sysbios_family_c64p_Hwi___S1
struct ti_sysbios_gates_GateHwi___S1
struct ti_sysbios_gates_GateMutex___S1
struct ti_sysbios_hal_Hwi___S1
struct ti_sysbios_heaps_HeapMem___S1
struct ti_sysbios_knl_Clock___S1
struct ti_sysbios_knl_Event___S1
struct ti_sysbios_knl_Queue___S1
struct ti_sysbios_knl_Semaphore___S1
struct ti_sysbios_knl_Task___S1
struct ti_sysbios_timers_rti_Timer___S1
Macros
#define __nested__
#define __config__
#define ATTRIBUTE __attribute__ ((used))
#define Module__MID ti_sysbios_BIOS_RtsGateProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_BIOS_RtsGateProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_BIOS_RtsGateProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_BIOS_RtsGateProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_BIOS_RtsGateProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_BIOS_RtsGateProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_BIOS_RtsGateProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_BIOS_RtsGateProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_family_c64p_Hwi_Module__id__C
#define Module__DGSINCL ti_sysbios_family_c64p_Hwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_family_c64p_Hwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_family_c64p_Hwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_family_c64p_Hwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_family_c64p_Hwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_family_c64p_Hwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_family_c64p_Hwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_family_c64p_Hwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_family_c64p_Hwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_family_c64p_Hwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_family_c64p_Hwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_family_c64p_Hwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_family_c64p_Hwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_family_c64p_Hwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_family_c64p_Hwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_family_c64p_Hwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_family_c64p_Hwi_Module_GateProxy_query
#define Module__MID ti_sysbios_gates_GateHwi_Module__id__C
#define Module__DGSINCL ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_gates_GateHwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_gates_GateHwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_gates_GateHwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_gates_GateHwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_gates_GateHwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_gates_GateHwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_gates_GateHwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_gates_GateHwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_gates_GateHwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_gates_GateHwi_Module_GateProxy_query
#define Module__MID ti_sysbios_gates_GateMutex_Module__id__C
#define Module__DGSINCL ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_gates_GateMutex_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_gates_GateMutex_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_gates_GateMutex_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_gates_GateMutex_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_gates_GateMutex_Module__gatePrms__C
#define Module__GP_create ti_sysbios_gates_GateMutex_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_gates_GateMutex_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_gates_GateMutex_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_gates_GateMutex_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_gates_GateMutex_Module_GateProxy_query
#define Module__MID ti_sysbios_hal_Hwi_Module__id__C
#define Module__DGSINCL ti_sysbios_hal_Hwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_hal_Hwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_hal_Hwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_hal_Hwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_hal_Hwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_hal_Hwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_hal_Hwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_hal_Hwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_hal_Hwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_hal_Hwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_hal_Hwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_hal_Hwi_Module_GateProxy_query
#define Module__MID ti_sysbios_hal_Hwi_HwiProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_hal_Hwi_HwiProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_hal_Hwi_HwiProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_hal_Hwi_HwiProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_hal_Hwi_HwiProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_hal_Hwi_HwiProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_hal_Hwi_HwiProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_hal_Hwi_HwiProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapMem_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Clock_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Clock_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Clock_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Clock_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Clock_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Clock_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Clock_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Clock_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Clock_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Clock_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Clock_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Clock_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Clock_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Clock_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Clock_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Clock_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Clock_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Clock_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Clock_TimerProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Clock_TimerProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Clock_TimerProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Clock_TimerProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Clock_TimerProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Clock_TimerProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Clock_TimerProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Clock_TimerProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Event_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Event_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Event_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Event_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Event_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Event_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Event_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Event_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Event_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Event_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Event_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Event_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Event_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Event_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Event_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Event_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Event_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Event_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Queue_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Queue_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Queue_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Queue_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Queue_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Queue_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Queue_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Queue_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Queue_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Queue_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Queue_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Queue_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Queue_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Queue_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Queue_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Queue_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Queue_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Queue_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Semaphore_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Semaphore_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Semaphore_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Semaphore_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Semaphore_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Semaphore_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Semaphore_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Semaphore_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Semaphore_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Semaphore_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Semaphore_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Task_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Task_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Task_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Task_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Task_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Task_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Task_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Task_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Task_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Task_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Task_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Task_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Task_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Task_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Task_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Task_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Task_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Task_Module_GateProxy_query
#define Module__MID ti_sysbios_timers_rti_Timer_Module__id__C
#define Module__DGSINCL ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_timers_rti_Timer_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_timers_rti_Timer_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_timers_rti_Timer_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_timers_rti_Timer_Module__gatePrms__C
#define Module__GP_create ti_sysbios_timers_rti_Timer_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_timers_rti_Timer_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_timers_rti_Timer_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_timers_rti_Timer_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_timers_rti_Timer_Module_GateProxy_query
#define Module__MID xdc_runtime_Main_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_Main_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_Main_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_Main_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_Main_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_Main_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_Main_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_Main_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_Main_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_Main_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_Main_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_Main_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_Main_Module_GateProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_Memory_HeapProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_Memory_HeapProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_Memory_HeapProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_Memory_HeapProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_Memory_HeapProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_Memory_HeapProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_Memory_HeapProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_Memory_HeapProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_Memory_HeapProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_Memory_HeapProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_Memory_HeapProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_Memory_HeapProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_Memory_HeapProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_Memory_HeapProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_Memory_HeapProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_Memory_HeapProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_Memory_HeapProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_Memory_HeapProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_System_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_System_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_System_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_System_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_System_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_System_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_System_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_System_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_System_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_System_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_System_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_System_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_System_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_System_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_System_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_System_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_System_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_System_Module_GateProxy_Module_GateProxy_query
Typedefs
typedef struct ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__
typedef struct ti_sysbios_knl_Queue_Object__ ti_sysbios_knl_Queue_Object__
typedef struct ti_sysbios_knl_Semaphore_Object__ ti_sysbios_knl_Semaphore_Object__
typedef struct ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_BIOS_RtsGateProxy_Object__
typedef struct ti_sysbios_family_c64p_Hwi_Module__ ti_sysbios_family_c64p_Hwi_Module__
typedef struct ti_sysbios_family_c64p_Hwi_Object__ ti_sysbios_family_c64p_Hwi_Object__
typedef struct ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__
typedef struct ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__
typedef struct ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__
typedef struct ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__
typedef struct ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__
typedef struct ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__
typedef ti_sysbios_family_c64p_Hwi_Object__ ti_sysbios_hal_Hwi_HwiProxy_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__
typedef struct ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
typedef struct ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__
typedef struct ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__
typedef struct ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__
typedef struct ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__
typedef ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_knl_Clock_TimerProxy_Object__
typedef struct ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__
typedef struct ti_sysbios_knl_Event_Object__ ti_sysbios_knl_Event_Object__
typedef struct ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__
typedef struct ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__
typedef struct ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__
typedef struct ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__
typedef struct ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__
typedef struct xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_Main_Module_GateProxy_Object__
typedef struct xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__
typedef ti_sysbios_heaps_HeapMem_Object__ xdc_runtime_Memory_HeapProxy_Object__
typedef struct xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_System_Module_GateProxy_Object__
typedef struct ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module_State__
typedef struct ti_sysbios_family_c64p_Cache_Module_State__ ti_sysbios_family_c64p_Cache_Module_State__
typedef struct ti_sysbios_family_c64p_EventCombiner_Module_State__ ti_sysbios_family_c64p_EventCombiner_Module_State__
typedef struct ti_sysbios_family_c64p_Exception_Module_State__ ti_sysbios_family_c64p_Exception_Module_State__
typedef struct ti_sysbios_family_c64p_Hwi_Module_State__ ti_sysbios_family_c64p_Hwi_Module_State__
typedef struct ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module_State__
typedef struct ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module_State__
typedef struct ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__ ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__
typedef struct ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module_State__
typedef struct ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module_State__
typedef struct xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module_State__
typedef struct xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module_State__
typedef struct xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module_State__
typedef struct xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module_State__
typedef struct xdc_runtime_System_Module_State__ xdc_runtime_System_Module_State__
typedef struct xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module_State__
typedef union Header Header
Functions
xdc_Void ti_sysbios_BIOS_startFunc (xdc_Void)
xdc_Void ti_sysbios_BIOS_exitFunc (xdc_Int)
xdc_Void ti_sysbios_family_c64p_EventCombiner_unused (xdc_UArg)
xdc_Void ti_sysbios_family_c64p_EventCombiner_dispatch (xdc_UArg)
xdc_UInt ti_sysbios_knl_Task_disable__E (xdc_Void)
xdc_Void ti_sysbios_knl_Task_restoreHwi__E (xdc_UInt)
xdc_Void ti_sysbios_knl_Clock_doTick__I (xdc_UArg)
xdc_Void DSP_sleep (xdc_Void)
xdc_Void ti_sysbios_hal_Hwi_checkStack (xdc_Void)
xdc_Void ti_sysbios_utils_Load_taskRegHook__E (xdc_Int)
xdc_Void ti_sysbios_hal_Hwi_initStack (xdc_Void)
xdc_Int xdc_runtime_System_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_c64p_EventCombiner_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_c64p_Exception_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_c64p_Hwi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_c64p_TimestampProvider_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_c64p_Cache_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Clock_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Task_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_hal_Hwi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_timers_rti_Timer_Module_startup__E (xdc_Int)
xdc_Int xdc_runtime_System_printfExtend__I (xdc_Char **, xdc_CString *, xdc_VaList *, xdc_runtime_System_ParseData *)
xdc__META (__ASM__, "@(#)__ASM__ = C:/Users/astro/workspace_v9_2/mrr_18xx_dss/Debug/configPkg/package/cfg/dss_mrr_pe674")
xdc__META (__ISA__, "@(#)__ISA__ = 674")
xdc__META (__PLAT__, "@(#)__PLAT__ = ti.platforms.c6x")
xdc__META (__TARG__, "@(#)__TARG__ = ti.targets.elf.C674")
xdc__META (__TRDR__, "@(#)__TRDR__ = ti.targets.omf.elf.Elf32")
xdc_Bool xdc_runtime_System_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_c64p_EventCombiner_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_c64p_Exception_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_c64p_Hwi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_c64p_Cache_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__F (void)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__F (void)
xdc_Void xdc_runtime_Startup_exec__I (void)
xdc_Void xdc_runtime_Startup_reset__I (void)
void xdc_runtime_Text_visitRope__I (xdc_runtime_Text_RopeId rope, xdc_Fxn visFxn, xdc_Ptr visState)
asm (" .sect \".vecs\" ")
asm (" .align 0x400 ")
asm (" .nocmp ")
asm (" .global ti_sysbios_family_c64p_Hwi0 ")
asm ("ti_sysbios_family_c64p_Hwi0: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int0 ")
asm (" .global _c_int00 ")
asm ("ti_sysbios_family_c64p_Hwi_int0: ")
asm (" nop ")
asm (" mvkl _c_int00, b0 ")
asm (" mvkh _c_int00, b0 ")
asm (" b b0 ")
asm (" nop 4 ")
asm (" .global ti_sysbios_family_c64p_Hwi_int1 ")
asm (" .global ti_sysbios_family_c64p_Exception_dispatch__E ")
asm ("ti_sysbios_family_c64p_Hwi_int1: ")
asm (" stw b0, *b15--[2] ")
asm (" mvk 1, b0 ")
asm (" stw b0, *b15[1] ")
asm (" ldw *++b15[2], b0 ")
asm (" .global ti_sysbios_family_c64p_Hwi_int2 ")
asm ("ti_sysbios_family_c64p_Hwi_int2: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int3 ")
asm ("ti_sysbios_family_c64p_Hwi_int3: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int4 ")
asm ("ti_sysbios_family_c64p_Hwi_int4: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int5 ")
asm ("ti_sysbios_family_c64p_Hwi_int5: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int6 ")
asm ("ti_sysbios_family_c64p_Hwi_int6: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int7 ")
asm (" .global ti_sysbios_family_c64p_Hwi_dispatchAlways ")
asm ("ti_sysbios_family_c64p_Hwi_int7: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int8 ")
asm ("ti_sysbios_family_c64p_Hwi_int8: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int9 ")
asm ("ti_sysbios_family_c64p_Hwi_int9: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int10 ")
asm ("ti_sysbios_family_c64p_Hwi_int10: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int11 ")
asm ("ti_sysbios_family_c64p_Hwi_int11: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int12 ")
asm ("ti_sysbios_family_c64p_Hwi_int12: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int13 ")
asm ("ti_sysbios_family_c64p_Hwi_int13: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int14 ")
asm ("ti_sysbios_family_c64p_Hwi_int14: ")
asm (" .global ti_sysbios_family_c64p_Hwi_int15 ")
asm ("ti_sysbios_family_c64p_Hwi_int15: ")
Void ti_sysbios_BIOS_atExitFunc__I (Int)
Void ti_sysbios_BIOS_registerRTSLock ()
Void ti_sysbios_timers_rti_Timer_startup__E ()
Void ti_sysbios_BIOS_startFunc__I ()
Void ti_sysbios_BIOS_rtsLock ()
Void ti_sysbios_BIOS_rtsUnlock ()
Void ti_sysbios_BIOS_nullFunc__I ()
Void ti_sysbios_BIOS_registerRTSLock (Void)
Void ti_sysbios_BIOS_removeRTSLock (Void)
Void ti_sysbios_BIOS_exitFunc (Int stat)
Void ti_sysbios_BIOS_errorRaiseHook (xdc_runtime_Error_Block *eb)
Void ti_sysbios_knl_Clock_doTick__I (UArg arg)
Void ti_sysbios_utils_Load_update__E ()
static Void * ti_sysbios_rts_MemAlloc_alloc (SizeT size)
Void ATTRIBUTE * malloc (SizeT size)
Void ATTRIBUTE * memalign (SizeT alignment, SizeT size)
Void ATTRIBUTE * calloc (SizeT nmemb, SizeT size)
Void ATTRIBUTE free (Void *ptr)
Void ATTRIBUTE * realloc (Void *ptr, SizeT size)
xdc_Int xdc_runtime_System_printf_va__E (xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_printf__E (xdc_CString fmt,...)
xdc_Int xdc_runtime_System_aprintf_va__E (xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_aprintf__E (xdc_CString fmt,...)
xdc_Int xdc_runtime_System_sprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_sprintf__E (xdc_Char buf[], xdc_CString fmt,...)
xdc_Int xdc_runtime_System_asprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_asprintf__E (xdc_Char buf[], xdc_CString fmt,...)
xdc_Int xdc_runtime_System_snprintf_va__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_snprintf__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt,...)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S (void)
ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_RtsGateProxy_create (const ti_sysbios_BIOS_RtsGateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_BIOS_RtsGateProxy_delete (ti_sysbios_BIOS_RtsGateProxy_Handle *instp)
void ti_sysbios_BIOS_RtsGateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_BIOS_RtsGateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_query__E (xdc_Int qual)
xdc_IArg ti_sysbios_BIOS_RtsGateProxy_enter__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst)
xdc_Void ti_sysbios_BIOS_RtsGateProxy_leave__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst, xdc_IArg key)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S (void)
ti_sysbios_hal_Hwi_HwiProxy_Handle ti_sysbios_hal_Hwi_HwiProxy_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_HwiProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_HwiProxy_delete (ti_sysbios_hal_Hwi_HwiProxy_Handle *instp)
void ti_sysbios_hal_Hwi_HwiProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo *stkInfo, xdc_Bool computeStackDepth)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo *stkInfo, xdc_Bool computeStackDepth, xdc_UInt coreId)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_startup__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disable__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enable__E (void)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restore__E (xdc_UInt key)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E (void)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_post__E (xdc_UInt intNum)
xdc_Char * ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E (xdc_UInt intNum)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E (xdc_UInt intNum)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E (xdc_UInt intNum, xdc_UInt key)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E (xdc_UInt intNum)
ti_sysbios_interfaces_IHwi_FuncPtr ti_sysbios_hal_Hwi_HwiProxy_getFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_UArg *arg)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, ti_sysbios_interfaces_IHwi_FuncPtr fxn, xdc_UArg arg)
xdc_Ptr ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id, xdc_Ptr hookContext)
ti_sysbios_interfaces_IHwi_Irp ti_sysbios_hal_Hwi_HwiProxy_getIrp__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S (void)
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle ti_sysbios_heaps_HeapMem_Module_GateProxy_create (const ti_sysbios_heaps_HeapMem_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapMem_Module_GateProxy_delete (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle *instp)
void ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst)
xdc_Void ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S (void)
ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_TimerProxy_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_knl_Clock_TimerProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Clock_TimerProxy_delete (ti_sysbios_knl_Clock_TimerProxy_Handle *instp)
void ti_sysbios_knl_Clock_TimerProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_knl_Clock_TimerProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_UInt ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E (void)
ti_sysbios_interfaces_ITimer_Status ti_sysbios_knl_Clock_TimerProxy_getStatus__E (xdc_UInt id)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_startup__E (void)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setNextTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 ticks)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_start__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_stop__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 period)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 microsecs)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCount__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_getFreq__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_runtime_Types_FreqHz *freq)
ti_sysbios_interfaces_ITimer_FuncPtr ti_sysbios_knl_Clock_TimerProxy_getFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UArg *arg)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, ti_sysbios_interfaces_ITimer_FuncPtr fxn, xdc_UArg arg)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_trigger__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 cycles)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 tickPeriod)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_Bool save)
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S (void)
xdc_UInt ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E (xdc_UInt bits)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S (void)
xdc_Ptr ti_sysbios_knl_Task_SupportProxy_start__E (xdc_Ptr curTask, ti_sysbios_interfaces_ITaskSupport_FuncPtr enterFxn, ti_sysbios_interfaces_ITaskSupport_FuncPtr exitFxn, xdc_runtime_Error_Block *eb)
xdc_Void ti_sysbios_knl_Task_SupportProxy_swap__E (xdc_Ptr *oldtskContext, xdc_Ptr *newtskContext)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_checkStack__E (xdc_Char *stack, xdc_SizeT size)
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_stackUsed__E (xdc_Char *stack, xdc_SizeT size)
xdc_UInt ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E (void)
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E (void)
xdc_Bool xdc_runtime_Main_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_Main_Module_GateProxy_Handle xdc_runtime_Main_Module_GateProxy_create (const xdc_runtime_Main_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_Main_Module_GateProxy_delete (xdc_runtime_Main_Module_GateProxy_Handle *instp)
void xdc_runtime_Main_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_Main_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_Main_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_Main_Module_GateProxy_enter__E (xdc_runtime_Main_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_Main_Module_GateProxy_leave__E (xdc_runtime_Main_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_Memory_HeapProxy_Module__startupDone__S (void)
xdc_runtime_Memory_HeapProxy_Handle xdc_runtime_Memory_HeapProxy_create (const xdc_runtime_Memory_HeapProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_Memory_HeapProxy_delete (xdc_runtime_Memory_HeapProxy_Handle *instp)
void xdc_runtime_Memory_HeapProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_Memory_HeapProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Ptr xdc_runtime_Memory_HeapProxy_alloc__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_SizeT size, xdc_SizeT align, xdc_runtime_Error_Block *eb)
xdc_Void xdc_runtime_Memory_HeapProxy_free__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_Ptr block, xdc_SizeT size)
xdc_Bool xdc_runtime_Memory_HeapProxy_isBlocking__E (xdc_runtime_Memory_HeapProxy_Handle __inst)
xdc_Void xdc_runtime_Memory_HeapProxy_getStats__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_runtime_Memory_Stats *stats)
xdc_Bool xdc_runtime_System_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_System_Module_GateProxy_Handle xdc_runtime_System_Module_GateProxy_create (const xdc_runtime_System_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_System_Module_GateProxy_delete (xdc_runtime_System_Module_GateProxy_Handle *instp)
void xdc_runtime_System_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_System_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_System_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_System_Module_GateProxy_enter__E (xdc_runtime_System_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_System_Module_GateProxy_leave__E (xdc_runtime_System_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_System_SupportProxy_Module__startupDone__S (void)
xdc_Void xdc_runtime_System_SupportProxy_abort__E (xdc_CString str)
xdc_Void xdc_runtime_System_SupportProxy_exit__E (xdc_Int stat)
xdc_Void xdc_runtime_System_SupportProxy_flush__E (void)
xdc_Void xdc_runtime_System_SupportProxy_putch__E (xdc_Char ch)
xdc_Bool xdc_runtime_System_SupportProxy_ready__E (void)
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S (void)
xdc_Bits32 xdc_runtime_Timestamp_SupportProxy_get32__E (void)
xdc_Void xdc_runtime_Timestamp_SupportProxy_get64__E (xdc_runtime_Types_Timestamp64 *result)
xdc_Void xdc_runtime_Timestamp_SupportProxy_getFreq__E (xdc_runtime_Types_FreqHz *freq)
xdc_runtime_IHeap_Handle xdc_runtime_IHeap_create (xdc_runtime_IHeap_Module mod, const xdc_runtime_IHeap_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IHeap_delete (xdc_runtime_IHeap_Handle *instp)
xdc_runtime_IGateProvider_Handle xdc_runtime_IGateProvider_create (xdc_runtime_IGateProvider_Module mod, const xdc_runtime_IGateProvider_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IGateProvider_delete (xdc_runtime_IGateProvider_Handle *instp)
xdc_Bool ti_sysbios_BIOS_Module__startupDone__S (void)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_family_c62_IntrinsicsSupport_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_c62_TaskSupport_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_c64p_Cache_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_c64p_EventCombiner_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_c64p_Exception_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_c64p_Hwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_family_c64p_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_family_c64p_Hwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__first__S (void)
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_family_c64p_Hwi_Handle ti_sysbios_family_c64p_Hwi_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_c64p_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_family_c64p_Hwi_construct (ti_sysbios_family_c64p_Hwi_Struct *__obj, xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_c64p_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_family_c64p_Hwi_destruct (ti_sysbios_family_c64p_Hwi_Struct *obj)
xdc_Void ti_sysbios_family_c64p_Hwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_family_c64p_Hwi_delete (ti_sysbios_family_c64p_Hwi_Handle *instp)
xdc_Bool ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__S (void)
xdc_Bool ti_sysbios_gates_GateHwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_gates_GateHwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_gates_GateHwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__first__S (void)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_gates_GateHwi_Handle ti_sysbios_gates_GateHwi_create (const ti_sysbios_gates_GateHwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_gates_GateHwi_construct (ti_sysbios_gates_GateHwi_Struct *__obj, const ti_sysbios_gates_GateHwi_Params *__paramsPtr)
void ti_sysbios_gates_GateHwi_destruct (ti_sysbios_gates_GateHwi_Struct *obj)
xdc_Void ti_sysbios_gates_GateHwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_gates_GateHwi_delete (ti_sysbios_gates_GateHwi_Handle *instp)
xdc_Bool ti_sysbios_gates_GateMutex_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_gates_GateMutex_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_gates_GateMutex_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__first__S (void)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_gates_GateMutex_Handle ti_sysbios_gates_GateMutex_create (const ti_sysbios_gates_GateMutex_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_gates_GateMutex_construct (ti_sysbios_gates_GateMutex_Struct *__obj, const ti_sysbios_gates_GateMutex_Params *__paramsPtr)
void ti_sysbios_gates_GateMutex_destruct (ti_sysbios_gates_GateMutex_Struct *obj)
xdc_Void ti_sysbios_gates_GateMutex_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_gates_GateMutex_delete (ti_sysbios_gates_GateMutex_Handle *instp)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_hal_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_hal_Hwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_hal_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_hal_Hwi_Object__first__S (void)
xdc_Ptr ti_sysbios_hal_Hwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_hal_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_hal_Hwi_Handle ti_sysbios_hal_Hwi_create (xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_construct (ti_sysbios_hal_Hwi_Struct *__obj, xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_destruct (ti_sysbios_hal_Hwi_Struct *obj)
xdc_Void ti_sysbios_hal_Hwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_hal_Hwi_delete (ti_sysbios_hal_Hwi_Handle *instp)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_heaps_HeapMem_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapMem_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_heaps_HeapMem_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__first__S (void)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_heaps_HeapMem_Handle ti_sysbios_heaps_HeapMem_create (const ti_sysbios_heaps_HeapMem_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapMem_construct (ti_sysbios_heaps_HeapMem_Struct *__obj, const ti_sysbios_heaps_HeapMem_Params *__paramsPtr)
void ti_sysbios_heaps_HeapMem_destruct (ti_sysbios_heaps_HeapMem_Struct *obj)
xdc_Void ti_sysbios_heaps_HeapMem_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_heaps_HeapMem_delete (ti_sysbios_heaps_HeapMem_Handle *instp)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Clock_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Clock_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Clock_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Clock_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Clock_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Clock_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Clock_Handle ti_sysbios_knl_Clock_create (ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Clock_construct (ti_sysbios_knl_Clock_Struct *__obj, ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params *__paramsPtr)
void ti_sysbios_knl_Clock_destruct (ti_sysbios_knl_Clock_Struct *obj)
xdc_Void ti_sysbios_knl_Clock_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Clock_delete (ti_sysbios_knl_Clock_Handle *instp)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Event_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Event_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Event_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Event_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Event_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Event_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Event_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Event_Handle ti_sysbios_knl_Event_create (const ti_sysbios_knl_Event_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Event_construct (ti_sysbios_knl_Event_Struct *__obj, const ti_sysbios_knl_Event_Params *__paramsPtr)
void ti_sysbios_knl_Event_destruct (ti_sysbios_knl_Event_Struct *obj)
xdc_Void ti_sysbios_knl_Event_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Event_delete (ti_sysbios_knl_Event_Handle *instp)
xdc_Bool ti_sysbios_knl_Idle_Module__startupDone__S (void)
xdc_Bool ti_sysbios_knl_Intrinsics_Module__startupDone__S (void)
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Queue_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Queue_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Queue_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Queue_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Queue_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Queue_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Queue_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Queue_create (const ti_sysbios_knl_Queue_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Queue_construct (ti_sysbios_knl_Queue_Struct *__obj, const ti_sysbios_knl_Queue_Params *__paramsPtr)
void ti_sysbios_knl_Queue_destruct (ti_sysbios_knl_Queue_Struct *obj)
xdc_Void ti_sysbios_knl_Queue_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Queue_delete (ti_sysbios_knl_Queue_Handle *instp)
xdc_Bool ti_sysbios_knl_Semaphore_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Semaphore_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Semaphore_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Semaphore_Handle ti_sysbios_knl_Semaphore_create (xdc_Int count, const ti_sysbios_knl_Semaphore_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Semaphore_construct (ti_sysbios_knl_Semaphore_Struct *__obj, xdc_Int count, const ti_sysbios_knl_Semaphore_Params *__paramsPtr)
void ti_sysbios_knl_Semaphore_destruct (ti_sysbios_knl_Semaphore_Struct *obj)
xdc_Void ti_sysbios_knl_Semaphore_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Semaphore_delete (ti_sysbios_knl_Semaphore_Handle *instp)
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Task_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Task_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Task_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Task_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Task_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Task_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Task_Handle ti_sysbios_knl_Task_create (ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Task_construct (ti_sysbios_knl_Task_Struct *__obj, ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Task_destruct (ti_sysbios_knl_Task_Struct *obj)
xdc_Void ti_sysbios_knl_Task_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Task_delete (ti_sysbios_knl_Task_Handle *instp)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_rts_ti_ThreadLocalStorage_Module__startupDone__S (void)
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_timers_rti_Timer_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_timers_rti_Timer_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__first__S (void)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_timers_rti_Timer_Handle ti_sysbios_timers_rti_Timer_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_timers_rti_Timer_construct (ti_sysbios_timers_rti_Timer_Struct *__obj, xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_timers_rti_Timer_destruct (ti_sysbios_timers_rti_Timer_Struct *obj)
xdc_Void ti_sysbios_timers_rti_Timer_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_timers_rti_Timer_delete (ti_sysbios_timers_rti_Timer_Handle *instp)
xdc_Bool ti_sysbios_utils_Load_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Assert_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Core_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Defaults_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Diags_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Error_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Gate_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Log_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Main_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Memory_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Memory_HeapProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Memory_HeapProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Registry_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Startup_Module__startupDone__S (void)
xdc_Bool xdc_runtime_SysStd_Module__startupDone__S (void)
xdc_Bool xdc_runtime_System_Module__startupDone__S (void)
xdc_Bool xdc_runtime_System_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_System_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_System_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_System_SupportProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Text_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Timestamp_Module__startupDone__S (void)
xdc_Bool xdc_runtime_TimestampNull_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Timestamp_SupportProxy_Proxy__delegate__S (void)
int __xdc__init (void)
Variables
ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_family_c64p_Hwi_Module__ ti_sysbios_family_c64p_Hwi_Module__root__V
ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__root__V
ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__root__V
ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__root__V
ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__root__V
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__root__V
ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__root__V
ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__root__V
ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__root__V
ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__root__V
ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__root__V
xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__root__V
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IHeap_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ISystemSupport_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ITimestampProvider_Interface__BASE__C = {&xdc_runtime_ITimestampClient_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IGateProvider_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IModule_Interface__BASE__C = {0}
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ITimestampClient_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const ti_sysbios_gates_GateHwi_Fxns__ ti_sysbios_gates_GateHwi_Module__FXNS__C
const ti_sysbios_gates_GateMutex_Fxns__ ti_sysbios_gates_GateMutex_Module__FXNS__C
const ti_sysbios_heaps_HeapMem_Fxns__ ti_sysbios_heaps_HeapMem_Module__FXNS__C
const xdc_runtime_SysStd_Fxns__ xdc_runtime_SysStd_Module__FXNS__C
const xdc_runtime_Timestamp_Fxns__ xdc_runtime_Timestamp_Module__FXNS__C
const xdc_runtime_TimestampNull_Fxns__ xdc_runtime_TimestampNull_Module__FXNS__C
ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module__state__V
ti_sysbios_family_c64p_Cache_Module_State__ ti_sysbios_family_c64p_Cache_Module__state__V
ti_sysbios_family_c64p_EventCombiner_Module_State__ ti_sysbios_family_c64p_EventCombiner_Module__state__V
ti_sysbios_family_c64p_Exception_Module_State__ ti_sysbios_family_c64p_Exception_Module__state__V
ti_sysbios_family_c64p_Hwi_Object__ ti_sysbios_family_c64p_Hwi_Object__table__V [5]
void * ti_sysbios_family_c64p_Hwi0
void * __TI_STATIC_BASE
ti_sysbios_family_c64p_Hwi_Module_State__ ti_sysbios_family_c64p_Hwi_Module__state__V
ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__table__V [1]
ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__table__V [2]
ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__table__V [1]
__T1_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A [16384]
ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__table__V [1]
ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module__state__V
const __T1_ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__A [3]
const __T1_ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__A [3]
__T1_ti_sysbios_knl_Task_Instance_State__stack ti_sysbios_knl_Task_Instance_State_0_stack__A [800]
__T1_ti_sysbios_knl_Task_Instance_State__hookEnv ti_sysbios_knl_Task_Instance_State_0_hookEnv__A [1]
ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__table__V [1]
__T1_ti_sysbios_knl_Task_Module_State__readyQ ti_sysbios_knl_Task_Module_State_0_readyQ__A [16]
__T1_ti_sysbios_knl_Task_Module_State__idleTask ti_sysbios_knl_Task_Module_State_0_idleTask__A [1]
ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module__state__V
const __T1_ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__A [1]
ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__ ti_sysbios_rts_ti_ThreadLocalStorage_Module__state__V
ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__table__V [1]
__T1_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State_0_device__A [2]
__T1_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A [2]
__T1_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State_0_handles__A [2]
ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module__state__V
__T1_ti_sysbios_utils_Load_Module_State__taskStartTime ti_sysbios_utils_Load_Module_State_0_taskStartTime__A [1]
__T1_ti_sysbios_utils_Load_Module_State__runningTask ti_sysbios_utils_Load_Module_State_0_runningTask__A [1]
__T1_ti_sysbios_utils_Load_Module_State__taskEnv ti_sysbios_utils_Load_Module_State_0_taskEnv__A [1]
ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module__state__V
xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module__state__V
xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module__state__V
xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module__state__V
xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module__state__V
const __T1_xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__A [2]
const __T1_xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__A [10]
const __T1_xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__A [10]
xdc_runtime_System_Module_State__ xdc_runtime_System_Module__state__V
xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module__state__V
const __T1_xdc_runtime_Text_charTab xdc_runtime_Text_charTab__A [1]
const __T1_xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__A [1]
const __FAR__ xdc_SizeT ti_sysbios_gates_GateMutex_Instance_State_sem__O = offsetof(ti_sysbios_gates_GateMutex_Object__,Object_field_sem)
const __FAR__ xdc_SizeT ti_sysbios_knl_Clock_Module_State_clockQ__O = offsetof(ti_sysbios_knl_Clock_Module_State__,Object_field_clockQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Event_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Event_Object__,Object_field_pendQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Semaphore_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Semaphore_Object__,Object_field_pendQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_inactiveQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_inactiveQ)
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_terminatedQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_terminatedQ)
const __FAR__ xdc_SizeT ti_sysbios_utils_Load_Module_State_taskList__O = offsetof(ti_sysbios_utils_Load_Module_State__,Object_field_taskList)
xdc_runtime_Error_Block xdc_runtime_Error_IgnoreBlock
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsEnabled ti_sysbios_BIOS_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsIncluded ti_sysbios_BIOS_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsMask ti_sysbios_BIOS_Module__diagsMask__C = ((CT__ti_sysbios_BIOS_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__gateObj ti_sysbios_BIOS_Module__gateObj__C = ((CT__ti_sysbios_BIOS_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__gatePrms ti_sysbios_BIOS_Module__gatePrms__C = ((CT__ti_sysbios_BIOS_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__id ti_sysbios_BIOS_Module__id__C = (xdc_Bits16)0x1b
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerDefined ti_sysbios_BIOS_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerObj ti_sysbios_BIOS_Module__loggerObj__C = ((CT__ti_sysbios_BIOS_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn0 ti_sysbios_BIOS_Module__loggerFxn0__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn1 ti_sysbios_BIOS_Module__loggerFxn1__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn2 ti_sysbios_BIOS_Module__loggerFxn2__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn4 ti_sysbios_BIOS_Module__loggerFxn4__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn8 ti_sysbios_BIOS_Module__loggerFxn8__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_BIOS_Object__count ti_sysbios_BIOS_Object__count__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Object__heap ti_sysbios_BIOS_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Object__sizeof ti_sysbios_BIOS_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_BIOS_Object__table ti_sysbios_BIOS_Object__table__C = 0
const __FAR__ CT__ti_sysbios_BIOS_smpEnabled ti_sysbios_BIOS_smpEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_mpeEnabled ti_sysbios_BIOS_mpeEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_cpuFreq ti_sysbios_BIOS_cpuFreq__C
const __FAR__ CT__ti_sysbios_BIOS_runtimeCreatesEnabled ti_sysbios_BIOS_runtimeCreatesEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_taskEnabled ti_sysbios_BIOS_taskEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_swiEnabled ti_sysbios_BIOS_swiEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_clockEnabled ti_sysbios_BIOS_clockEnabled__C = 1
const __FAR__ CT__ti_sysbios_BIOS_defaultKernelHeapInstance ti_sysbios_BIOS_defaultKernelHeapInstance__C = 0
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSize ti_sysbios_BIOS_kernelHeapSize__C = (xdc_SizeT)0x1000
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSection ti_sysbios_BIOS_kernelHeapSection__C = ".kernel_heap"
const __FAR__ CT__ti_sysbios_BIOS_heapSize ti_sysbios_BIOS_heapSize__C = (xdc_SizeT)0x1000
const __FAR__ CT__ti_sysbios_BIOS_heapSection ti_sysbios_BIOS_heapSection__C = 0
const __FAR__ CT__ti_sysbios_BIOS_heapTrackEnabled ti_sysbios_BIOS_heapTrackEnabled__C = 0
const __FAR__ CT__ti_sysbios_BIOS_setupSecureContext ti_sysbios_BIOS_setupSecureContext__C = 0
const __FAR__ CT__ti_sysbios_BIOS_useSK ti_sysbios_BIOS_useSK__C = 0
const __FAR__ CT__ti_sysbios_BIOS_installedErrorHook ti_sysbios_BIOS_installedErrorHook__C = ((CT__ti_sysbios_BIOS_installedErrorHook)((xdc_Fxn)xdc_runtime_Error_print__E))
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsEnabled ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsIncluded ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__id ti_sysbios_family_c62_IntrinsicsSupport_Module__id__C = (xdc_Bits16)0x2e
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerDefined ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__count ti_sysbios_family_c62_IntrinsicsSupport_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__heap ti_sysbios_family_c62_IntrinsicsSupport_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__sizeof ti_sysbios_family_c62_IntrinsicsSupport_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__table ti_sysbios_family_c62_IntrinsicsSupport_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__diagsEnabled ti_sysbios_family_c62_TaskSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__diagsIncluded ti_sysbios_family_c62_TaskSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__diagsMask ti_sysbios_family_c62_TaskSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__gateObj ti_sysbios_family_c62_TaskSupport_Module__gateObj__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__gatePrms ti_sysbios_family_c62_TaskSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__id ti_sysbios_family_c62_TaskSupport_Module__id__C = (xdc_Bits16)0x2d
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerDefined ti_sysbios_family_c62_TaskSupport_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerObj ti_sysbios_family_c62_TaskSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__count ti_sysbios_family_c62_TaskSupport_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__heap ti_sysbios_family_c62_TaskSupport_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__sizeof ti_sysbios_family_c62_TaskSupport_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__table ti_sysbios_family_c62_TaskSupport_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_defaultStackSize ti_sysbios_family_c62_TaskSupport_defaultStackSize__C = (xdc_SizeT)0x800
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_stackAlignment ti_sysbios_family_c62_TaskSupport_stackAlignment__C = (xdc_UInt)0x8
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__diagsEnabled ti_sysbios_family_c64p_Cache_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__diagsIncluded ti_sysbios_family_c64p_Cache_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__diagsMask ti_sysbios_family_c64p_Cache_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_Cache_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__gateObj ti_sysbios_family_c64p_Cache_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_Cache_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__gatePrms ti_sysbios_family_c64p_Cache_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_Cache_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__id ti_sysbios_family_c64p_Cache_Module__id__C = (xdc_Bits16)0x1a
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerDefined ti_sysbios_family_c64p_Cache_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerObj ti_sysbios_family_c64p_Cache_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn0 ti_sysbios_family_c64p_Cache_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn1 ti_sysbios_family_c64p_Cache_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn2 ti_sysbios_family_c64p_Cache_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn4 ti_sysbios_family_c64p_Cache_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn8 ti_sysbios_family_c64p_Cache_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__count ti_sysbios_family_c64p_Cache_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__heap ti_sysbios_family_c64p_Cache_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__sizeof ti_sysbios_family_c64p_Cache_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__table ti_sysbios_family_c64p_Cache_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_initSize ti_sysbios_family_c64p_Cache_initSize__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFA_CFG ti_sysbios_family_c64p_Cache_EMIFA_CFG__C = ((CT__ti_sysbios_family_c64p_Cache_EMIFA_CFG)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFA_BASE ti_sysbios_family_c64p_Cache_EMIFA_BASE__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFA_LENGTH ti_sysbios_family_c64p_Cache_EMIFA_LENGTH__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFB_CFG ti_sysbios_family_c64p_Cache_EMIFB_CFG__C = ((CT__ti_sysbios_family_c64p_Cache_EMIFB_CFG)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFB_BASE ti_sysbios_family_c64p_Cache_EMIFB_BASE__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFB_LENGTH ti_sysbios_family_c64p_Cache_EMIFB_LENGTH__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFC_CFG ti_sysbios_family_c64p_Cache_EMIFC_CFG__C = ((CT__ti_sysbios_family_c64p_Cache_EMIFC_CFG)0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFC_BASE ti_sysbios_family_c64p_Cache_EMIFC_BASE__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFC_LENGTH ti_sysbios_family_c64p_Cache_EMIFC_LENGTH__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR0_31 ti_sysbios_family_c64p_Cache_MAR0_31__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR32_63 ti_sysbios_family_c64p_Cache_MAR32_63__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR64_95 ti_sysbios_family_c64p_Cache_MAR64_95__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR96_127 ti_sysbios_family_c64p_Cache_MAR96_127__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR128_159 ti_sysbios_family_c64p_Cache_MAR128_159__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR160_191 ti_sysbios_family_c64p_Cache_MAR160_191__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR192_223 ti_sysbios_family_c64p_Cache_MAR192_223__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR224_255 ti_sysbios_family_c64p_Cache_MAR224_255__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_family_c64p_Cache_E_invalidL1CacheSize ti_sysbios_family_c64p_Cache_E_invalidL1CacheSize__C = (((xdc_runtime_Error_Id)17) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Cache_E_invalidL2CacheSize ti_sysbios_family_c64p_Cache_E_invalidL2CacheSize__C = (((xdc_runtime_Error_Id)18) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsEnabled ti_sysbios_family_c64p_EventCombiner_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsIncluded ti_sysbios_family_c64p_EventCombiner_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsMask ti_sysbios_family_c64p_EventCombiner_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__gateObj ti_sysbios_family_c64p_EventCombiner_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__gatePrms ti_sysbios_family_c64p_EventCombiner_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__id ti_sysbios_family_c64p_EventCombiner_Module__id__C = (xdc_Bits16)0x16
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerDefined ti_sysbios_family_c64p_EventCombiner_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerObj ti_sysbios_family_c64p_EventCombiner_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__count ti_sysbios_family_c64p_EventCombiner_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__heap ti_sysbios_family_c64p_EventCombiner_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__sizeof ti_sysbios_family_c64p_EventCombiner_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__table ti_sysbios_family_c64p_EventCombiner_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_EVTRegs ti_sysbios_family_c64p_EventCombiner_EVTRegs__C = ((CT__ti_sysbios_family_c64p_EventCombiner_EVTRegs)(0x1800000))
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_A_invalidEventId ti_sysbios_family_c64p_EventCombiner_A_invalidEventId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_E_unpluggedEvent ti_sysbios_family_c64p_EventCombiner_E_unpluggedEvent__C = (((xdc_runtime_Error_Id)9) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_EVTMASK ti_sysbios_family_c64p_EventCombiner_EVTMASK__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__diagsEnabled ti_sysbios_family_c64p_Exception_Module__diagsEnabled__C = (xdc_Bits32)0x190
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__diagsIncluded ti_sysbios_family_c64p_Exception_Module__diagsIncluded__C = (xdc_Bits32)0x190
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__diagsMask ti_sysbios_family_c64p_Exception_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_Exception_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__gateObj ti_sysbios_family_c64p_Exception_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_Exception_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__gatePrms ti_sysbios_family_c64p_Exception_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_Exception_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__id ti_sysbios_family_c64p_Exception_Module__id__C = (xdc_Bits16)0x17
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerDefined ti_sysbios_family_c64p_Exception_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerObj ti_sysbios_family_c64p_Exception_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn0 ti_sysbios_family_c64p_Exception_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn1 ti_sysbios_family_c64p_Exception_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn2 ti_sysbios_family_c64p_Exception_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn4 ti_sysbios_family_c64p_Exception_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn8 ti_sysbios_family_c64p_Exception_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__count ti_sysbios_family_c64p_Exception_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__heap ti_sysbios_family_c64p_Exception_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__sizeof ti_sysbios_family_c64p_Exception_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__table ti_sysbios_family_c64p_Exception_Object__table__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_E_exceptionMin ti_sysbios_family_c64p_Exception_E_exceptionMin__C = (((xdc_runtime_Error_Id)10) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_E_exceptionMax ti_sysbios_family_c64p_Exception_E_exceptionMax__C = (((xdc_runtime_Error_Id)11) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_useInternalBuffer ti_sysbios_family_c64p_Exception_useInternalBuffer__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_enableExternalMPC ti_sysbios_family_c64p_Exception_enableExternalMPC__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Exception_enablePrint ti_sysbios_family_c64p_Exception_enablePrint__C = 1
const __FAR__ CT__ti_sysbios_family_c64p_Exception_exceptionHook ti_sysbios_family_c64p_Exception_exceptionHook__C = ((CT__ti_sysbios_family_c64p_Exception_exceptionHook)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_internalHook ti_sysbios_family_c64p_Exception_internalHook__C = ((CT__ti_sysbios_family_c64p_Exception_internalHook)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_externalHook ti_sysbios_family_c64p_Exception_externalHook__C = ((CT__ti_sysbios_family_c64p_Exception_externalHook)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_nmiHook ti_sysbios_family_c64p_Exception_nmiHook__C = ((CT__ti_sysbios_family_c64p_Exception_nmiHook)0)
const __FAR__ CT__ti_sysbios_family_c64p_Exception_returnHook ti_sysbios_family_c64p_Exception_returnHook__C = ((CT__ti_sysbios_family_c64p_Exception_returnHook)0)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_family_c64p_Hwi_Object__DESC__C
const __FAR__ ti_sysbios_family_c64p_Hwi_Params ti_sysbios_family_c64p_Hwi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__diagsEnabled ti_sysbios_family_c64p_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__diagsIncluded ti_sysbios_family_c64p_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__diagsMask ti_sysbios_family_c64p_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__gateObj ti_sysbios_family_c64p_Hwi_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__gatePrms ti_sysbios_family_c64p_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__id ti_sysbios_family_c64p_Hwi_Module__id__C = (xdc_Bits16)0x18
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerDefined ti_sysbios_family_c64p_Hwi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerObj ti_sysbios_family_c64p_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn0 ti_sysbios_family_c64p_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn1 ti_sysbios_family_c64p_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn2 ti_sysbios_family_c64p_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn4 ti_sysbios_family_c64p_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn8 ti_sysbios_family_c64p_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__count ti_sysbios_family_c64p_Hwi_Object__count__C = 5
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__heap ti_sysbios_family_c64p_Hwi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__sizeof ti_sysbios_family_c64p_Hwi_Object__sizeof__C = sizeof(ti_sysbios_family_c64p_Hwi_Object__)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__table ti_sysbios_family_c64p_Hwi_Object__table__C = ti_sysbios_family_c64p_Hwi_Object__table__V
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherAutoNestingSupport ti_sysbios_family_c64p_Hwi_dispatcherAutoNestingSupport__C = 1
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherSwiSupport ti_sysbios_family_c64p_Hwi_dispatcherSwiSupport__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherTaskSupport ti_sysbios_family_c64p_Hwi_dispatcherTaskSupport__C = 1
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherIrpTrackingSupport ti_sysbios_family_c64p_Hwi_dispatcherIrpTrackingSupport__C = 1
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_INTRMUX1Address ti_sysbios_family_c64p_Hwi_INTRMUX1Address__C = ((CT__ti_sysbios_family_c64p_Hwi_INTRMUX1Address)(0x1800104))
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_alreadyDefined ti_sysbios_family_c64p_Hwi_E_alreadyDefined__C = (((xdc_runtime_Error_Id)12) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_handleNotFound ti_sysbios_family_c64p_Hwi_E_handleNotFound__C = (((xdc_runtime_Error_Id)13) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_allocSCFailed ti_sysbios_family_c64p_Hwi_E_allocSCFailed__C = (((xdc_runtime_Error_Id)14) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_registerSCFailed ti_sysbios_family_c64p_Hwi_E_registerSCFailed__C = (((xdc_runtime_Error_Id)15) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_invalidIntNum ti_sysbios_family_c64p_Hwi_E_invalidIntNum__C = (((xdc_runtime_Error_Id)16) << 16 | 0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_LM_begin ti_sysbios_family_c64p_Hwi_LM_begin__C = (((xdc_runtime_Log_Event)12) << 16 | 768)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_LD_end ti_sysbios_family_c64p_Hwi_LD_end__C = (((xdc_runtime_Log_Event)13) << 16 | 512)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_enableException ti_sysbios_family_c64p_Hwi_enableException__C = 1
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_swiDisable ti_sysbios_family_c64p_Hwi_swiDisable__C = ((CT__ti_sysbios_family_c64p_Hwi_swiDisable)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_swiRestoreHwi ti_sysbios_family_c64p_Hwi_swiRestoreHwi__C = ((CT__ti_sysbios_family_c64p_Hwi_swiRestoreHwi)0)
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_taskDisable ti_sysbios_family_c64p_Hwi_taskDisable__C = ((CT__ti_sysbios_family_c64p_Hwi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_taskRestoreHwi ti_sysbios_family_c64p_Hwi_taskRestoreHwi__C = ((CT__ti_sysbios_family_c64p_Hwi_taskRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Task_restoreHwi__E))
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_hooks ti_sysbios_family_c64p_Hwi_hooks__C = {0, 0}
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsEnabled ti_sysbios_family_c64p_TimestampProvider_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsIncluded ti_sysbios_family_c64p_TimestampProvider_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__gateObj ti_sysbios_family_c64p_TimestampProvider_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__id ti_sysbios_family_c64p_TimestampProvider_Module__id__C = (xdc_Bits16)0x19
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerDefined ti_sysbios_family_c64p_TimestampProvider_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__count ti_sysbios_family_c64p_TimestampProvider_Object__count__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__heap ti_sysbios_family_c64p_TimestampProvider_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__sizeof ti_sysbios_family_c64p_TimestampProvider_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__table ti_sysbios_family_c64p_TimestampProvider_Object__table__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateHwi_Object__DESC__C
const __FAR__ ti_sysbios_gates_GateHwi_Params ti_sysbios_gates_GateHwi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsEnabled ti_sysbios_gates_GateHwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsIncluded ti_sysbios_gates_GateHwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsMask ti_sysbios_gates_GateHwi_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateHwi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gateObj ti_sysbios_gates_GateHwi_Module__gateObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gatePrms ti_sysbios_gates_GateHwi_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateHwi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__id ti_sysbios_gates_GateHwi_Module__id__C = (xdc_Bits16)0x2f
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerDefined ti_sysbios_gates_GateHwi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerObj ti_sysbios_gates_GateHwi_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__count ti_sysbios_gates_GateHwi_Object__count__C = 1
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__heap ti_sysbios_gates_GateHwi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__sizeof ti_sysbios_gates_GateHwi_Object__sizeof__C = sizeof(ti_sysbios_gates_GateHwi_Object__)
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__table ti_sysbios_gates_GateHwi_Object__table__C = ti_sysbios_gates_GateHwi_Object__table__V
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateMutex_Object__DESC__C
const __FAR__ ti_sysbios_gates_GateMutex_Params ti_sysbios_gates_GateMutex_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsEnabled ti_sysbios_gates_GateMutex_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsIncluded ti_sysbios_gates_GateMutex_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsMask ti_sysbios_gates_GateMutex_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateMutex_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gateObj ti_sysbios_gates_GateMutex_Module__gateObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gatePrms ti_sysbios_gates_GateMutex_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateMutex_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__id ti_sysbios_gates_GateMutex_Module__id__C = (xdc_Bits16)0x30
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerDefined ti_sysbios_gates_GateMutex_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerObj ti_sysbios_gates_GateMutex_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__count ti_sysbios_gates_GateMutex_Object__count__C = 2
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__heap ti_sysbios_gates_GateMutex_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__sizeof ti_sysbios_gates_GateMutex_Object__sizeof__C = sizeof(ti_sysbios_gates_GateMutex_Object__)
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__table ti_sysbios_gates_GateMutex_Object__table__C = ti_sysbios_gates_GateMutex_Object__table__V
const __FAR__ CT__ti_sysbios_gates_GateMutex_A_badContext ti_sysbios_gates_GateMutex_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_hal_Hwi_Object__DESC__C
const __FAR__ ti_sysbios_hal_Hwi_Params ti_sysbios_hal_Hwi_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsEnabled ti_sysbios_hal_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsIncluded ti_sysbios_hal_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsMask ti_sysbios_hal_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_hal_Hwi_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gateObj ti_sysbios_hal_Hwi_Module__gateObj__C = ((CT__ti_sysbios_hal_Hwi_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gatePrms ti_sysbios_hal_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_hal_Hwi_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__id ti_sysbios_hal_Hwi_Module__id__C = (xdc_Bits16)0x2b
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerDefined ti_sysbios_hal_Hwi_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerObj ti_sysbios_hal_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__count ti_sysbios_hal_Hwi_Object__count__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__heap ti_sysbios_hal_Hwi_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__sizeof ti_sysbios_hal_Hwi_Object__sizeof__C = sizeof(ti_sysbios_hal_Hwi_Object__)
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__table ti_sysbios_hal_Hwi_Object__table__C = ti_sysbios_hal_Hwi_Object__table__V
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherSwiSupport ti_sysbios_hal_Hwi_dispatcherSwiSupport__C = 0
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherTaskSupport ti_sysbios_hal_Hwi_dispatcherTaskSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C = 1
const __FAR__ CT__ti_sysbios_hal_Hwi_E_stackOverflow ti_sysbios_hal_Hwi_E_stackOverflow__C = (((xdc_runtime_Error_Id)29) << 16 | 0)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapMem_Object__DESC__C
const __FAR__ ti_sysbios_heaps_HeapMem_Params ti_sysbios_heaps_HeapMem_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsEnabled ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsIncluded ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsMask ti_sysbios_heaps_HeapMem_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapMem_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gateObj ti_sysbios_heaps_HeapMem_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[0]))
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gatePrms ti_sysbios_heaps_HeapMem_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__id ti_sysbios_heaps_HeapMem_Module__id__C = (xdc_Bits16)0x27
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerDefined ti_sysbios_heaps_HeapMem_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerObj ti_sysbios_heaps_HeapMem_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__count ti_sysbios_heaps_HeapMem_Object__count__C = 1
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__heap ti_sysbios_heaps_HeapMem_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__sizeof ti_sysbios_heaps_HeapMem_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapMem_Object__)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__table ti_sysbios_heaps_HeapMem_Object__table__C = ti_sysbios_heaps_HeapMem_Object__table__V
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_zeroBlock ti_sysbios_heaps_HeapMem_A_zeroBlock__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_heapSize ti_sysbios_heaps_HeapMem_A_heapSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_align ti_sysbios_heaps_HeapMem_A_align__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_E_memory ti_sysbios_heaps_HeapMem_E_memory__C = (((xdc_runtime_Error_Id)27) << 16 | 0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_invalidFree ti_sysbios_heaps_HeapMem_A_invalidFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr)0)
const __FAR__ CT__ti_sysbios_heaps_HeapMem_reqAlign ti_sysbios_heaps_HeapMem_reqAlign__C = (xdc_SizeT)0x8
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Clock_Object__DESC__C
const __FAR__ ti_sysbios_knl_Clock_Params ti_sysbios_knl_Clock_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsEnabled ti_sysbios_knl_Clock_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsIncluded ti_sysbios_knl_Clock_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsMask ti_sysbios_knl_Clock_Module__diagsMask__C = ((CT__ti_sysbios_knl_Clock_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gateObj ti_sysbios_knl_Clock_Module__gateObj__C = ((CT__ti_sysbios_knl_Clock_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gatePrms ti_sysbios_knl_Clock_Module__gatePrms__C = ((CT__ti_sysbios_knl_Clock_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__id ti_sysbios_knl_Clock_Module__id__C = (xdc_Bits16)0x1d
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerDefined ti_sysbios_knl_Clock_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerObj ti_sysbios_knl_Clock_Module__loggerObj__C = ((CT__ti_sysbios_knl_Clock_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn0 ti_sysbios_knl_Clock_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn1 ti_sysbios_knl_Clock_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn2 ti_sysbios_knl_Clock_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn4 ti_sysbios_knl_Clock_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn8 ti_sysbios_knl_Clock_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Clock_Object__count ti_sysbios_knl_Clock_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_Object__heap ti_sysbios_knl_Clock_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_Object__sizeof ti_sysbios_knl_Clock_Object__sizeof__C = sizeof(ti_sysbios_knl_Clock_Object__)
const __FAR__ CT__ti_sysbios_knl_Clock_Object__table ti_sysbios_knl_Clock_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Clock_LW_delayed ti_sysbios_knl_Clock_LW_delayed__C = (((xdc_runtime_Log_Event)14) << 16 | 1024)
const __FAR__ CT__ti_sysbios_knl_Clock_LM_tick ti_sysbios_knl_Clock_LM_tick__C = (((xdc_runtime_Log_Event)15) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Clock_LM_begin ti_sysbios_knl_Clock_LM_begin__C = (((xdc_runtime_Log_Event)16) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Clock_A_clockDisabled ti_sysbios_knl_Clock_A_clockDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Clock_A_badThreadType ti_sysbios_knl_Clock_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Clock_serviceMargin ti_sysbios_knl_Clock_serviceMargin__C = (xdc_UInt32)0x0
const __FAR__ CT__ti_sysbios_knl_Clock_tickSource ti_sysbios_knl_Clock_tickSource__C = ti_sysbios_knl_Clock_TickSource_TIMER
const __FAR__ CT__ti_sysbios_knl_Clock_tickMode ti_sysbios_knl_Clock_tickMode__C = ti_sysbios_knl_Clock_TickMode_PERIODIC
const __FAR__ CT__ti_sysbios_knl_Clock_timerId ti_sysbios_knl_Clock_timerId__C = (xdc_UInt)(-0x0 - 1)
const __FAR__ CT__ti_sysbios_knl_Clock_tickPeriod ti_sysbios_knl_Clock_tickPeriod__C = (xdc_UInt32)0x3e8
const __FAR__ CT__ti_sysbios_knl_Clock_doTickFunc ti_sysbios_knl_Clock_doTickFunc__C = ((CT__ti_sysbios_knl_Clock_doTickFunc)((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I))
const __FAR__ CT__ti_sysbios_knl_Clock_triggerClock ti_sysbios_knl_Clock_triggerClock__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Event_Object__DESC__C
const __FAR__ ti_sysbios_knl_Event_Params ti_sysbios_knl_Event_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsEnabled ti_sysbios_knl_Event_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsIncluded ti_sysbios_knl_Event_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsMask ti_sysbios_knl_Event_Module__diagsMask__C = ((CT__ti_sysbios_knl_Event_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__gateObj ti_sysbios_knl_Event_Module__gateObj__C = ((CT__ti_sysbios_knl_Event_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__gatePrms ti_sysbios_knl_Event_Module__gatePrms__C = ((CT__ti_sysbios_knl_Event_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__id ti_sysbios_knl_Event_Module__id__C = (xdc_Bits16)0x20
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerDefined ti_sysbios_knl_Event_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerObj ti_sysbios_knl_Event_Module__loggerObj__C = ((CT__ti_sysbios_knl_Event_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn0 ti_sysbios_knl_Event_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn1 ti_sysbios_knl_Event_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn2 ti_sysbios_knl_Event_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn4 ti_sysbios_knl_Event_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn8 ti_sysbios_knl_Event_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Event_Object__count ti_sysbios_knl_Event_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_Object__heap ti_sysbios_knl_Event_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_Object__sizeof ti_sysbios_knl_Event_Object__sizeof__C = sizeof(ti_sysbios_knl_Event_Object__)
const __FAR__ CT__ti_sysbios_knl_Event_Object__table ti_sysbios_knl_Event_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Event_LM_post ti_sysbios_knl_Event_LM_post__C = (((xdc_runtime_Log_Event)17) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Event_LM_pend ti_sysbios_knl_Event_LM_pend__C = (((xdc_runtime_Log_Event)18) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventMasks ti_sysbios_knl_Event_A_nullEventMasks__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventId ti_sysbios_knl_Event_A_nullEventId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_eventInUse ti_sysbios_knl_Event_A_eventInUse__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_badContext ti_sysbios_knl_Event_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Event_A_pendTaskDisabled ti_sysbios_knl_Event_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsEnabled ti_sysbios_knl_Idle_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsIncluded ti_sysbios_knl_Idle_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsMask ti_sysbios_knl_Idle_Module__diagsMask__C = ((CT__ti_sysbios_knl_Idle_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gateObj ti_sysbios_knl_Idle_Module__gateObj__C = ((CT__ti_sysbios_knl_Idle_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gatePrms ti_sysbios_knl_Idle_Module__gatePrms__C = ((CT__ti_sysbios_knl_Idle_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__id ti_sysbios_knl_Idle_Module__id__C = (xdc_Bits16)0x1e
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerDefined ti_sysbios_knl_Idle_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerObj ti_sysbios_knl_Idle_Module__loggerObj__C = ((CT__ti_sysbios_knl_Idle_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn0 ti_sysbios_knl_Idle_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn1 ti_sysbios_knl_Idle_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn2 ti_sysbios_knl_Idle_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn4 ti_sysbios_knl_Idle_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn8 ti_sysbios_knl_Idle_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Idle_Object__count ti_sysbios_knl_Idle_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Object__heap ti_sysbios_knl_Idle_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Object__sizeof ti_sysbios_knl_Idle_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_Object__table ti_sysbios_knl_Idle_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__C = {3, ((__T1_ti_sysbios_knl_Idle_funcList *)ti_sysbios_knl_Idle_funcList__A)}
const __FAR__ CT__ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__C = {3, ((__T1_ti_sysbios_knl_Idle_coreList *)ti_sysbios_knl_Idle_coreList__A)}
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsEnabled ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsIncluded ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsMask ti_sysbios_knl_Intrinsics_Module__diagsMask__C = ((CT__ti_sysbios_knl_Intrinsics_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gateObj ti_sysbios_knl_Intrinsics_Module__gateObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gatePrms ti_sysbios_knl_Intrinsics_Module__gatePrms__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__id ti_sysbios_knl_Intrinsics_Module__id__C = (xdc_Bits16)0x1f
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerDefined ti_sysbios_knl_Intrinsics_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerObj ti_sysbios_knl_Intrinsics_Module__loggerObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0 ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1 ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2 ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4 ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8 ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__count ti_sysbios_knl_Intrinsics_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__heap ti_sysbios_knl_Intrinsics_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__sizeof ti_sysbios_knl_Intrinsics_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__table ti_sysbios_knl_Intrinsics_Object__table__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Queue_Object__DESC__C
const __FAR__ ti_sysbios_knl_Queue_Params ti_sysbios_knl_Queue_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsEnabled ti_sysbios_knl_Queue_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsIncluded ti_sysbios_knl_Queue_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsMask ti_sysbios_knl_Queue_Module__diagsMask__C = ((CT__ti_sysbios_knl_Queue_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gateObj ti_sysbios_knl_Queue_Module__gateObj__C = ((CT__ti_sysbios_knl_Queue_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gatePrms ti_sysbios_knl_Queue_Module__gatePrms__C = ((CT__ti_sysbios_knl_Queue_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__id ti_sysbios_knl_Queue_Module__id__C = (xdc_Bits16)0x21
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerDefined ti_sysbios_knl_Queue_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerObj ti_sysbios_knl_Queue_Module__loggerObj__C = ((CT__ti_sysbios_knl_Queue_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn0 ti_sysbios_knl_Queue_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn1 ti_sysbios_knl_Queue_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn2 ti_sysbios_knl_Queue_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn4 ti_sysbios_knl_Queue_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn8 ti_sysbios_knl_Queue_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Queue_Object__count ti_sysbios_knl_Queue_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Queue_Object__heap ti_sysbios_knl_Queue_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Queue_Object__sizeof ti_sysbios_knl_Queue_Object__sizeof__C = sizeof(ti_sysbios_knl_Queue_Object__)
const __FAR__ CT__ti_sysbios_knl_Queue_Object__table ti_sysbios_knl_Queue_Object__table__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Semaphore_Object__DESC__C
const __FAR__ ti_sysbios_knl_Semaphore_Params ti_sysbios_knl_Semaphore_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsEnabled ti_sysbios_knl_Semaphore_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsIncluded ti_sysbios_knl_Semaphore_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsMask ti_sysbios_knl_Semaphore_Module__diagsMask__C = ((CT__ti_sysbios_knl_Semaphore_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gateObj ti_sysbios_knl_Semaphore_Module__gateObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gatePrms ti_sysbios_knl_Semaphore_Module__gatePrms__C = ((CT__ti_sysbios_knl_Semaphore_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__id ti_sysbios_knl_Semaphore_Module__id__C = (xdc_Bits16)0x22
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerDefined ti_sysbios_knl_Semaphore_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerObj ti_sysbios_knl_Semaphore_Module__loggerObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__count ti_sysbios_knl_Semaphore_Object__count__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__heap ti_sysbios_knl_Semaphore_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__sizeof ti_sysbios_knl_Semaphore_Object__sizeof__C = sizeof(ti_sysbios_knl_Semaphore_Object__)
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__table ti_sysbios_knl_Semaphore_Object__table__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_post ti_sysbios_knl_Semaphore_LM_post__C = (((xdc_runtime_Log_Event)19) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_pend ti_sysbios_knl_Semaphore_LM_pend__C = (((xdc_runtime_Log_Event)20) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_noEvents ti_sysbios_knl_Semaphore_A_noEvents__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_invTimeout ti_sysbios_knl_Semaphore_A_invTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_badContext ti_sysbios_knl_Semaphore_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_overflow ti_sysbios_knl_Semaphore_A_overflow__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_pendTaskDisabled ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)19) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsEvents ti_sysbios_knl_Semaphore_supportsEvents__C = 0
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsPriority ti_sysbios_knl_Semaphore_supportsPriority__C = 1
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventPost ti_sysbios_knl_Semaphore_eventPost__C = ((CT__ti_sysbios_knl_Semaphore_eventPost)0)
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventSync ti_sysbios_knl_Semaphore_eventSync__C = ((CT__ti_sysbios_knl_Semaphore_eventSync)0)
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Task_Object__DESC__C
const __FAR__ ti_sysbios_knl_Task_Params ti_sysbios_knl_Task_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsEnabled ti_sysbios_knl_Task_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsIncluded ti_sysbios_knl_Task_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsMask ti_sysbios_knl_Task_Module__diagsMask__C = ((CT__ti_sysbios_knl_Task_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__gateObj ti_sysbios_knl_Task_Module__gateObj__C = ((CT__ti_sysbios_knl_Task_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__gatePrms ti_sysbios_knl_Task_Module__gatePrms__C = ((CT__ti_sysbios_knl_Task_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__id ti_sysbios_knl_Task_Module__id__C = (xdc_Bits16)0x23
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerDefined ti_sysbios_knl_Task_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerObj ti_sysbios_knl_Task_Module__loggerObj__C = ((CT__ti_sysbios_knl_Task_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn0 ti_sysbios_knl_Task_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn1 ti_sysbios_knl_Task_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn2 ti_sysbios_knl_Task_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn4 ti_sysbios_knl_Task_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn8 ti_sysbios_knl_Task_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_knl_Task_Object__count ti_sysbios_knl_Task_Object__count__C = 1
const __FAR__ CT__ti_sysbios_knl_Task_Object__heap ti_sysbios_knl_Task_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_Object__sizeof ti_sysbios_knl_Task_Object__sizeof__C = sizeof(ti_sysbios_knl_Task_Object__)
const __FAR__ CT__ti_sysbios_knl_Task_Object__table ti_sysbios_knl_Task_Object__table__C = ti_sysbios_knl_Task_Object__table__V
const __FAR__ CT__ti_sysbios_knl_Task_LM_switch ti_sysbios_knl_Task_LM_switch__C = (((xdc_runtime_Log_Event)21) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LM_sleep ti_sysbios_knl_Task_LM_sleep__C = (((xdc_runtime_Log_Event)22) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LD_ready ti_sysbios_knl_Task_LD_ready__C = (((xdc_runtime_Log_Event)23) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Task_LD_block ti_sysbios_knl_Task_LD_block__C = (((xdc_runtime_Log_Event)24) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Task_LM_yield ti_sysbios_knl_Task_LM_yield__C = (((xdc_runtime_Log_Event)25) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LM_setPri ti_sysbios_knl_Task_LM_setPri__C = (((xdc_runtime_Log_Event)26) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LD_exit ti_sysbios_knl_Task_LD_exit__C = (((xdc_runtime_Log_Event)27) << 16 | 512)
const __FAR__ CT__ti_sysbios_knl_Task_LM_setAffinity ti_sysbios_knl_Task_LM_setAffinity__C = (((xdc_runtime_Log_Event)28) << 16 | 768)
const __FAR__ CT__ti_sysbios_knl_Task_LM_schedule ti_sysbios_knl_Task_LM_schedule__C = (((xdc_runtime_Log_Event)29) << 16 | 1024)
const __FAR__ CT__ti_sysbios_knl_Task_LM_noWork ti_sysbios_knl_Task_LM_noWork__C = (((xdc_runtime_Log_Event)30) << 16 | 1024)
const __FAR__ CT__ti_sysbios_knl_Task_E_stackOverflow ti_sysbios_knl_Task_E_stackOverflow__C = (((xdc_runtime_Error_Id)20) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_spOutOfBounds ti_sysbios_knl_Task_E_spOutOfBounds__C = (((xdc_runtime_Error_Id)21) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_deleteNotAllowed ti_sysbios_knl_Task_E_deleteNotAllowed__C = (((xdc_runtime_Error_Id)22) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_moduleStateCheckFailed ti_sysbios_knl_Task_E_moduleStateCheckFailed__C = (((xdc_runtime_Error_Id)23) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_objectCheckFailed ti_sysbios_knl_Task_E_objectCheckFailed__C = (((xdc_runtime_Error_Id)24) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_E_objectNotInKernelSpace ti_sysbios_knl_Task_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)25) << 16 | 0)
const __FAR__ CT__ti_sysbios_knl_Task_A_badThreadType ti_sysbios_knl_Task_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badTaskState ti_sysbios_knl_Task_A_badTaskState__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_noPendElem ti_sysbios_knl_Task_A_noPendElem__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_taskDisabled ti_sysbios_knl_Task_A_taskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badPriority ti_sysbios_knl_Task_A_badPriority__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badTimeout ti_sysbios_knl_Task_A_badTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_badAffinity ti_sysbios_knl_Task_A_badAffinity__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_sleepTaskDisabled ti_sysbios_knl_Task_A_sleepTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_A_invalidCoreId ti_sysbios_knl_Task_A_invalidCoreId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_knl_Task_numPriorities ti_sysbios_knl_Task_numPriorities__C = (xdc_UInt)0x10
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackSize ti_sysbios_knl_Task_defaultStackSize__C = (xdc_SizeT)0x5dc
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackHeap ti_sysbios_knl_Task_defaultStackHeap__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_allBlockedFunc ti_sysbios_knl_Task_allBlockedFunc__C = ((CT__ti_sysbios_knl_Task_allBlockedFunc)0)
const __FAR__ CT__ti_sysbios_knl_Task_initStackFlag ti_sysbios_knl_Task_initStackFlag__C = 1
const __FAR__ CT__ti_sysbios_knl_Task_checkStackFlag ti_sysbios_knl_Task_checkStackFlag__C = 1
const __FAR__ CT__ti_sysbios_knl_Task_deleteTerminatedTasks ti_sysbios_knl_Task_deleteTerminatedTasks__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__C = {1, ((__T1_ti_sysbios_knl_Task_hooks *)ti_sysbios_knl_Task_hooks__A)}
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFxn ti_sysbios_knl_Task_moduleStateCheckFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_moduleStateCheck__I))
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn ti_sysbios_knl_Task_moduleStateCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getModuleStateCheckValue__I))
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFlag ti_sysbios_knl_Task_moduleStateCheckFlag__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFxn ti_sysbios_knl_Task_objectCheckFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_objectCheck__I))
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckValueFxn ti_sysbios_knl_Task_objectCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getObjectCheckValue__I))
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFlag ti_sysbios_knl_Task_objectCheckFlag__C = 0
const __FAR__ CT__ti_sysbios_knl_Task_numConstructedTasks ti_sysbios_knl_Task_numConstructedTasks__C = (xdc_UInt)0x0
const __FAR__ CT__ti_sysbios_knl_Task_startupHookFunc ti_sysbios_knl_Task_startupHookFunc__C = ((CT__ti_sysbios_knl_Task_startupHookFunc)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsEnabled ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsIncluded ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__id ti_sysbios_rts_ti_ThreadLocalStorage_Module__id__C = (xdc_Bits16)0x2a
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerDefined ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__count ti_sysbios_rts_ti_ThreadLocalStorage_Object__count__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__heap ti_sysbios_rts_ti_ThreadLocalStorage_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__sizeof ti_sysbios_rts_ti_ThreadLocalStorage_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__table ti_sysbios_rts_ti_ThreadLocalStorage_Object__table__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_heapHandle ti_sysbios_rts_ti_ThreadLocalStorage_heapHandle__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_enableTLSSupport ti_sysbios_rts_ti_ThreadLocalStorage_enableTLSSupport__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_TItlsSectMemory ti_sysbios_rts_ti_ThreadLocalStorage_TItlsSectMemory__C = 0
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_TItls_initSectMemory ti_sysbios_rts_ti_ThreadLocalStorage_TItls_initSectMemory__C = 0
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_timers_rti_Timer_Object__DESC__C
const __FAR__ ti_sysbios_timers_rti_Timer_Params ti_sysbios_timers_rti_Timer_Object__PARAMS__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsEnabled ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsIncluded ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsMask ti_sysbios_timers_rti_Timer_Module__diagsMask__C = ((CT__ti_sysbios_timers_rti_Timer_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gateObj ti_sysbios_timers_rti_Timer_Module__gateObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gatePrms ti_sysbios_timers_rti_Timer_Module__gatePrms__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__id ti_sysbios_timers_rti_Timer_Module__id__C = (xdc_Bits16)0x31
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerDefined ti_sysbios_timers_rti_Timer_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerObj ti_sysbios_timers_rti_Timer_Module__loggerObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__count ti_sysbios_timers_rti_Timer_Object__count__C = 1
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__heap ti_sysbios_timers_rti_Timer_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__sizeof ti_sysbios_timers_rti_Timer_Object__sizeof__C = sizeof(ti_sysbios_timers_rti_Timer_Object__)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__table ti_sysbios_timers_rti_Timer_Object__table__C = ti_sysbios_timers_rti_Timer_Object__table__V
const __FAR__ CT__ti_sysbios_timers_rti_Timer_A_invalidTimer ti_sysbios_timers_rti_Timer_A_invalidTimer__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidTimer ti_sysbios_timers_rti_Timer_E_invalidTimer__C = (((xdc_runtime_Error_Id)31) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_notAvailable ti_sysbios_timers_rti_Timer_E_notAvailable__C = (((xdc_runtime_Error_Id)32) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidHwiMask ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C = (((xdc_runtime_Error_Id)33) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_cannotSupport ti_sysbios_timers_rti_Timer_E_cannotSupport__C = (((xdc_runtime_Error_Id)34) << 16 | 0)
const __FAR__ CT__ti_sysbios_timers_rti_Timer_anyMask ti_sysbios_timers_rti_Timer_anyMask__C = (xdc_UInt)0x3
const __FAR__ CT__ti_sysbios_timers_rti_Timer_continueOnSuspend ti_sysbios_timers_rti_Timer_continueOnSuspend__C = 0
const __FAR__ CT__ti_sysbios_timers_rti_Timer_startupNeeded ti_sysbios_timers_rti_Timer_startupNeeded__C = (xdc_UInt)0x1
const __FAR__ CT__ti_sysbios_timers_rti_Timer_numTimerDevices ti_sysbios_timers_rti_Timer_numTimerDevices__C = (xdc_Int)0x2
const __FAR__ CT__ti_sysbios_utils_Load_Module__diagsEnabled ti_sysbios_utils_Load_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_utils_Load_Module__diagsIncluded ti_sysbios_utils_Load_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__ti_sysbios_utils_Load_Module__diagsMask ti_sysbios_utils_Load_Module__diagsMask__C = ((CT__ti_sysbios_utils_Load_Module__diagsMask)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__gateObj ti_sysbios_utils_Load_Module__gateObj__C = ((CT__ti_sysbios_utils_Load_Module__gateObj)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__gatePrms ti_sysbios_utils_Load_Module__gatePrms__C = ((CT__ti_sysbios_utils_Load_Module__gatePrms)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__id ti_sysbios_utils_Load_Module__id__C = (xdc_Bits16)0x29
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerDefined ti_sysbios_utils_Load_Module__loggerDefined__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerObj ti_sysbios_utils_Load_Module__loggerObj__C = ((CT__ti_sysbios_utils_Load_Module__loggerObj)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn0 ti_sysbios_utils_Load_Module__loggerFxn0__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn0)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn1 ti_sysbios_utils_Load_Module__loggerFxn1__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn1)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn2 ti_sysbios_utils_Load_Module__loggerFxn2__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn2)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn4 ti_sysbios_utils_Load_Module__loggerFxn4__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn4)0)
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn8 ti_sysbios_utils_Load_Module__loggerFxn8__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn8)0)
const __FAR__ CT__ti_sysbios_utils_Load_Object__count ti_sysbios_utils_Load_Object__count__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_Object__heap ti_sysbios_utils_Load_Object__heap__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_Object__sizeof ti_sysbios_utils_Load_Object__sizeof__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_Object__table ti_sysbios_utils_Load_Object__table__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_LS_cpuLoad ti_sysbios_utils_Load_LS_cpuLoad__C = (((xdc_runtime_Log_Event)31) << 16 | 2048)
const __FAR__ CT__ti_sysbios_utils_Load_LS_hwiLoad ti_sysbios_utils_Load_LS_hwiLoad__C = (((xdc_runtime_Log_Event)32) << 16 | 2048)
const __FAR__ CT__ti_sysbios_utils_Load_LS_swiLoad ti_sysbios_utils_Load_LS_swiLoad__C = (((xdc_runtime_Log_Event)33) << 16 | 2048)
const __FAR__ CT__ti_sysbios_utils_Load_LS_taskLoad ti_sysbios_utils_Load_LS_taskLoad__C = (((xdc_runtime_Log_Event)34) << 16 | 2048)
const __FAR__ CT__ti_sysbios_utils_Load_postUpdate ti_sysbios_utils_Load_postUpdate__C = ((CT__ti_sysbios_utils_Load_postUpdate)0)
const __FAR__ CT__ti_sysbios_utils_Load_updateInIdle ti_sysbios_utils_Load_updateInIdle__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_windowInMs ti_sysbios_utils_Load_windowInMs__C = (xdc_UInt)0x1f4
const __FAR__ CT__ti_sysbios_utils_Load_hwiEnabled ti_sysbios_utils_Load_hwiEnabled__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_swiEnabled ti_sysbios_utils_Load_swiEnabled__C = 0
const __FAR__ CT__ti_sysbios_utils_Load_taskEnabled ti_sysbios_utils_Load_taskEnabled__C = 1
const __FAR__ CT__ti_sysbios_utils_Load_autoAddTasks ti_sysbios_utils_Load_autoAddTasks__C = 1
const __FAR__ CT__xdc_runtime_Assert_Module__diagsEnabled xdc_runtime_Assert_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Assert_Module__diagsIncluded xdc_runtime_Assert_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Assert_Module__diagsMask xdc_runtime_Assert_Module__diagsMask__C = ((CT__xdc_runtime_Assert_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Assert_Module__gateObj xdc_runtime_Assert_Module__gateObj__C = ((CT__xdc_runtime_Assert_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Assert_Module__gatePrms xdc_runtime_Assert_Module__gatePrms__C = ((CT__xdc_runtime_Assert_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Assert_Module__id xdc_runtime_Assert_Module__id__C = (xdc_Bits16)0x1
const __FAR__ CT__xdc_runtime_Assert_Module__loggerDefined xdc_runtime_Assert_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Assert_Module__loggerObj xdc_runtime_Assert_Module__loggerObj__C = ((CT__xdc_runtime_Assert_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn0 xdc_runtime_Assert_Module__loggerFxn0__C = ((CT__xdc_runtime_Assert_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn1 xdc_runtime_Assert_Module__loggerFxn1__C = ((CT__xdc_runtime_Assert_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn2 xdc_runtime_Assert_Module__loggerFxn2__C = ((CT__xdc_runtime_Assert_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn4 xdc_runtime_Assert_Module__loggerFxn4__C = ((CT__xdc_runtime_Assert_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn8 xdc_runtime_Assert_Module__loggerFxn8__C = ((CT__xdc_runtime_Assert_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Assert_Object__count xdc_runtime_Assert_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Assert_Object__heap xdc_runtime_Assert_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Assert_Object__sizeof xdc_runtime_Assert_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Assert_Object__table xdc_runtime_Assert_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Assert_E_assertFailed xdc_runtime_Assert_E_assertFailed__C = (((xdc_runtime_Error_Id)1) << 16 | 0)
const __FAR__ CT__xdc_runtime_Core_Module__diagsEnabled xdc_runtime_Core_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Core_Module__diagsIncluded xdc_runtime_Core_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Core_Module__diagsMask xdc_runtime_Core_Module__diagsMask__C = ((CT__xdc_runtime_Core_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Core_Module__gateObj xdc_runtime_Core_Module__gateObj__C = ((CT__xdc_runtime_Core_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Core_Module__gatePrms xdc_runtime_Core_Module__gatePrms__C = ((CT__xdc_runtime_Core_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Core_Module__id xdc_runtime_Core_Module__id__C = (xdc_Bits16)0x2
const __FAR__ CT__xdc_runtime_Core_Module__loggerDefined xdc_runtime_Core_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Core_Module__loggerObj xdc_runtime_Core_Module__loggerObj__C = ((CT__xdc_runtime_Core_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn0 xdc_runtime_Core_Module__loggerFxn0__C = ((CT__xdc_runtime_Core_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn1 xdc_runtime_Core_Module__loggerFxn1__C = ((CT__xdc_runtime_Core_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn2 xdc_runtime_Core_Module__loggerFxn2__C = ((CT__xdc_runtime_Core_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn4 xdc_runtime_Core_Module__loggerFxn4__C = ((CT__xdc_runtime_Core_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn8 xdc_runtime_Core_Module__loggerFxn8__C = ((CT__xdc_runtime_Core_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Core_Object__count xdc_runtime_Core_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Core_Object__heap xdc_runtime_Core_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Core_Object__sizeof xdc_runtime_Core_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Core_Object__table xdc_runtime_Core_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Core_A_initializedParams xdc_runtime_Core_A_initializedParams__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsEnabled xdc_runtime_Defaults_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsIncluded xdc_runtime_Defaults_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsMask xdc_runtime_Defaults_Module__diagsMask__C = ((CT__xdc_runtime_Defaults_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__gateObj xdc_runtime_Defaults_Module__gateObj__C = ((CT__xdc_runtime_Defaults_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__gatePrms xdc_runtime_Defaults_Module__gatePrms__C = ((CT__xdc_runtime_Defaults_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__id xdc_runtime_Defaults_Module__id__C = (xdc_Bits16)0x3
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerDefined xdc_runtime_Defaults_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerObj xdc_runtime_Defaults_Module__loggerObj__C = ((CT__xdc_runtime_Defaults_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn0 xdc_runtime_Defaults_Module__loggerFxn0__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn1 xdc_runtime_Defaults_Module__loggerFxn1__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn2 xdc_runtime_Defaults_Module__loggerFxn2__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn4 xdc_runtime_Defaults_Module__loggerFxn4__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn8 xdc_runtime_Defaults_Module__loggerFxn8__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Defaults_Object__count xdc_runtime_Defaults_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Object__heap xdc_runtime_Defaults_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Object__sizeof xdc_runtime_Defaults_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Defaults_Object__table xdc_runtime_Defaults_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Diags_Module__diagsEnabled xdc_runtime_Diags_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Diags_Module__diagsIncluded xdc_runtime_Diags_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Diags_Module__diagsMask xdc_runtime_Diags_Module__diagsMask__C = ((CT__xdc_runtime_Diags_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Diags_Module__gateObj xdc_runtime_Diags_Module__gateObj__C = ((CT__xdc_runtime_Diags_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Diags_Module__gatePrms xdc_runtime_Diags_Module__gatePrms__C = ((CT__xdc_runtime_Diags_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Diags_Module__id xdc_runtime_Diags_Module__id__C = (xdc_Bits16)0x4
const __FAR__ CT__xdc_runtime_Diags_Module__loggerDefined xdc_runtime_Diags_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Diags_Module__loggerObj xdc_runtime_Diags_Module__loggerObj__C = ((CT__xdc_runtime_Diags_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn0 xdc_runtime_Diags_Module__loggerFxn0__C = ((CT__xdc_runtime_Diags_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn1 xdc_runtime_Diags_Module__loggerFxn1__C = ((CT__xdc_runtime_Diags_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn2 xdc_runtime_Diags_Module__loggerFxn2__C = ((CT__xdc_runtime_Diags_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn4 xdc_runtime_Diags_Module__loggerFxn4__C = ((CT__xdc_runtime_Diags_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn8 xdc_runtime_Diags_Module__loggerFxn8__C = ((CT__xdc_runtime_Diags_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Diags_Object__count xdc_runtime_Diags_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Diags_Object__heap xdc_runtime_Diags_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Diags_Object__sizeof xdc_runtime_Diags_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Diags_Object__table xdc_runtime_Diags_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Diags_setMaskEnabled xdc_runtime_Diags_setMaskEnabled__C = 0
const __FAR__ CT__xdc_runtime_Diags_dictBase xdc_runtime_Diags_dictBase__C = ((CT__xdc_runtime_Diags_dictBase)0)
const __FAR__ CT__xdc_runtime_Error_Module__diagsEnabled xdc_runtime_Error_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Error_Module__diagsIncluded xdc_runtime_Error_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Error_Module__diagsMask xdc_runtime_Error_Module__diagsMask__C = ((CT__xdc_runtime_Error_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Error_Module__gateObj xdc_runtime_Error_Module__gateObj__C = ((CT__xdc_runtime_Error_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Error_Module__gatePrms xdc_runtime_Error_Module__gatePrms__C = ((CT__xdc_runtime_Error_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Error_Module__id xdc_runtime_Error_Module__id__C = (xdc_Bits16)0x5
const __FAR__ CT__xdc_runtime_Error_Module__loggerDefined xdc_runtime_Error_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Error_Module__loggerObj xdc_runtime_Error_Module__loggerObj__C = ((CT__xdc_runtime_Error_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn0 xdc_runtime_Error_Module__loggerFxn0__C = ((CT__xdc_runtime_Error_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn1 xdc_runtime_Error_Module__loggerFxn1__C = ((CT__xdc_runtime_Error_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn2 xdc_runtime_Error_Module__loggerFxn2__C = ((CT__xdc_runtime_Error_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn4 xdc_runtime_Error_Module__loggerFxn4__C = ((CT__xdc_runtime_Error_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn8 xdc_runtime_Error_Module__loggerFxn8__C = ((CT__xdc_runtime_Error_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Error_Object__count xdc_runtime_Error_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Error_Object__heap xdc_runtime_Error_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Error_Object__sizeof xdc_runtime_Error_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Error_Object__table xdc_runtime_Error_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Error_policyFxn xdc_runtime_Error_policyFxn__C = ((CT__xdc_runtime_Error_policyFxn)((xdc_Fxn)xdc_runtime_Error_policyDefault__E))
const __FAR__ CT__xdc_runtime_Error_E_generic xdc_runtime_Error_E_generic__C = (((xdc_runtime_Error_Id)2) << 16 | 0)
const __FAR__ CT__xdc_runtime_Error_E_memory xdc_runtime_Error_E_memory__C = (((xdc_runtime_Error_Id)3) << 16 | 0)
const __FAR__ CT__xdc_runtime_Error_E_msgCode xdc_runtime_Error_E_msgCode__C = (((xdc_runtime_Error_Id)4) << 16 | 0)
const __FAR__ CT__xdc_runtime_Error_policy xdc_runtime_Error_policy__C = xdc_runtime_Error_UNWIND
const __FAR__ CT__xdc_runtime_Error_raiseHook xdc_runtime_Error_raiseHook__C = ((CT__xdc_runtime_Error_raiseHook)((xdc_Fxn)ti_sysbios_BIOS_errorRaiseHook__I))
const __FAR__ CT__xdc_runtime_Error_maxDepth xdc_runtime_Error_maxDepth__C = (xdc_UInt16)0x10
const __FAR__ CT__xdc_runtime_Gate_Module__diagsEnabled xdc_runtime_Gate_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Gate_Module__diagsIncluded xdc_runtime_Gate_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Gate_Module__diagsMask xdc_runtime_Gate_Module__diagsMask__C = ((CT__xdc_runtime_Gate_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Gate_Module__gateObj xdc_runtime_Gate_Module__gateObj__C = ((CT__xdc_runtime_Gate_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Gate_Module__gatePrms xdc_runtime_Gate_Module__gatePrms__C = ((CT__xdc_runtime_Gate_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Gate_Module__id xdc_runtime_Gate_Module__id__C = (xdc_Bits16)0x6
const __FAR__ CT__xdc_runtime_Gate_Module__loggerDefined xdc_runtime_Gate_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Gate_Module__loggerObj xdc_runtime_Gate_Module__loggerObj__C = ((CT__xdc_runtime_Gate_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn0 xdc_runtime_Gate_Module__loggerFxn0__C = ((CT__xdc_runtime_Gate_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn1 xdc_runtime_Gate_Module__loggerFxn1__C = ((CT__xdc_runtime_Gate_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn2 xdc_runtime_Gate_Module__loggerFxn2__C = ((CT__xdc_runtime_Gate_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn4 xdc_runtime_Gate_Module__loggerFxn4__C = ((CT__xdc_runtime_Gate_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn8 xdc_runtime_Gate_Module__loggerFxn8__C = ((CT__xdc_runtime_Gate_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Gate_Object__count xdc_runtime_Gate_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Gate_Object__heap xdc_runtime_Gate_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Gate_Object__sizeof xdc_runtime_Gate_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Gate_Object__table xdc_runtime_Gate_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Log_Module__diagsEnabled xdc_runtime_Log_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Log_Module__diagsIncluded xdc_runtime_Log_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Log_Module__diagsMask xdc_runtime_Log_Module__diagsMask__C = ((CT__xdc_runtime_Log_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Log_Module__gateObj xdc_runtime_Log_Module__gateObj__C = ((CT__xdc_runtime_Log_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Log_Module__gatePrms xdc_runtime_Log_Module__gatePrms__C = ((CT__xdc_runtime_Log_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Log_Module__id xdc_runtime_Log_Module__id__C = (xdc_Bits16)0x7
const __FAR__ CT__xdc_runtime_Log_Module__loggerDefined xdc_runtime_Log_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Log_Module__loggerObj xdc_runtime_Log_Module__loggerObj__C = ((CT__xdc_runtime_Log_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn0 xdc_runtime_Log_Module__loggerFxn0__C = ((CT__xdc_runtime_Log_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn1 xdc_runtime_Log_Module__loggerFxn1__C = ((CT__xdc_runtime_Log_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn2 xdc_runtime_Log_Module__loggerFxn2__C = ((CT__xdc_runtime_Log_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn4 xdc_runtime_Log_Module__loggerFxn4__C = ((CT__xdc_runtime_Log_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn8 xdc_runtime_Log_Module__loggerFxn8__C = ((CT__xdc_runtime_Log_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Log_Object__count xdc_runtime_Log_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Log_Object__heap xdc_runtime_Log_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Log_Object__sizeof xdc_runtime_Log_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Log_Object__table xdc_runtime_Log_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Log_L_construct xdc_runtime_Log_L_construct__C = (((xdc_runtime_Log_Event)1) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_create xdc_runtime_Log_L_create__C = (((xdc_runtime_Log_Event)2) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_destruct xdc_runtime_Log_L_destruct__C = (((xdc_runtime_Log_Event)3) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_delete xdc_runtime_Log_L_delete__C = (((xdc_runtime_Log_Event)4) << 16 | 4)
const __FAR__ CT__xdc_runtime_Log_L_error xdc_runtime_Log_L_error__C = (((xdc_runtime_Log_Event)5) << 16 | 192)
const __FAR__ CT__xdc_runtime_Log_L_warning xdc_runtime_Log_L_warning__C = (((xdc_runtime_Log_Event)6) << 16 | 224)
const __FAR__ CT__xdc_runtime_Log_L_info xdc_runtime_Log_L_info__C = (((xdc_runtime_Log_Event)7) << 16 | 16384)
const __FAR__ CT__xdc_runtime_Log_L_start xdc_runtime_Log_L_start__C = (((xdc_runtime_Log_Event)8) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Log_L_stop xdc_runtime_Log_L_stop__C = (((xdc_runtime_Log_Event)9) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Log_L_startInstance xdc_runtime_Log_L_startInstance__C = (((xdc_runtime_Log_Event)10) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Log_L_stopInstance xdc_runtime_Log_L_stopInstance__C = (((xdc_runtime_Log_Event)11) << 16 | 32768)
const __FAR__ CT__xdc_runtime_Main_Module__diagsEnabled xdc_runtime_Main_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Main_Module__diagsIncluded xdc_runtime_Main_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Main_Module__diagsMask xdc_runtime_Main_Module__diagsMask__C = ((CT__xdc_runtime_Main_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Main_Module__gateObj xdc_runtime_Main_Module__gateObj__C = ((CT__xdc_runtime_Main_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
const __FAR__ CT__xdc_runtime_Main_Module__gatePrms xdc_runtime_Main_Module__gatePrms__C = ((CT__xdc_runtime_Main_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Main_Module__id xdc_runtime_Main_Module__id__C = (xdc_Bits16)0x8
const __FAR__ CT__xdc_runtime_Main_Module__loggerDefined xdc_runtime_Main_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Main_Module__loggerObj xdc_runtime_Main_Module__loggerObj__C = ((CT__xdc_runtime_Main_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn0 xdc_runtime_Main_Module__loggerFxn0__C = ((CT__xdc_runtime_Main_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn1 xdc_runtime_Main_Module__loggerFxn1__C = ((CT__xdc_runtime_Main_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn2 xdc_runtime_Main_Module__loggerFxn2__C = ((CT__xdc_runtime_Main_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn4 xdc_runtime_Main_Module__loggerFxn4__C = ((CT__xdc_runtime_Main_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn8 xdc_runtime_Main_Module__loggerFxn8__C = ((CT__xdc_runtime_Main_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Main_Object__count xdc_runtime_Main_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Main_Object__heap xdc_runtime_Main_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Main_Object__sizeof xdc_runtime_Main_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Main_Object__table xdc_runtime_Main_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Memory_Module__diagsEnabled xdc_runtime_Memory_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Memory_Module__diagsIncluded xdc_runtime_Memory_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Memory_Module__diagsMask xdc_runtime_Memory_Module__diagsMask__C = ((CT__xdc_runtime_Memory_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Memory_Module__gateObj xdc_runtime_Memory_Module__gateObj__C = ((CT__xdc_runtime_Memory_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Memory_Module__gatePrms xdc_runtime_Memory_Module__gatePrms__C = ((CT__xdc_runtime_Memory_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Memory_Module__id xdc_runtime_Memory_Module__id__C = (xdc_Bits16)0x9
const __FAR__ CT__xdc_runtime_Memory_Module__loggerDefined xdc_runtime_Memory_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Memory_Module__loggerObj xdc_runtime_Memory_Module__loggerObj__C = ((CT__xdc_runtime_Memory_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn0 xdc_runtime_Memory_Module__loggerFxn0__C = ((CT__xdc_runtime_Memory_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn1 xdc_runtime_Memory_Module__loggerFxn1__C = ((CT__xdc_runtime_Memory_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn2 xdc_runtime_Memory_Module__loggerFxn2__C = ((CT__xdc_runtime_Memory_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn4 xdc_runtime_Memory_Module__loggerFxn4__C = ((CT__xdc_runtime_Memory_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn8 xdc_runtime_Memory_Module__loggerFxn8__C = ((CT__xdc_runtime_Memory_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Memory_Object__count xdc_runtime_Memory_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Memory_Object__heap xdc_runtime_Memory_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Memory_Object__sizeof xdc_runtime_Memory_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Memory_Object__table xdc_runtime_Memory_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Memory_defaultHeapInstance xdc_runtime_Memory_defaultHeapInstance__C = (xdc_runtime_IHeap_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0]
const __FAR__ CT__xdc_runtime_Registry_Module__diagsEnabled xdc_runtime_Registry_Module__diagsEnabled__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Registry_Module__diagsIncluded xdc_runtime_Registry_Module__diagsIncluded__C = (xdc_Bits32)0x90
const __FAR__ CT__xdc_runtime_Registry_Module__diagsMask xdc_runtime_Registry_Module__diagsMask__C = ((CT__xdc_runtime_Registry_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Registry_Module__gateObj xdc_runtime_Registry_Module__gateObj__C = ((CT__xdc_runtime_Registry_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Registry_Module__gatePrms xdc_runtime_Registry_Module__gatePrms__C = ((CT__xdc_runtime_Registry_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Registry_Module__id xdc_runtime_Registry_Module__id__C = (xdc_Bits16)0xa
const __FAR__ CT__xdc_runtime_Registry_Module__loggerDefined xdc_runtime_Registry_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Registry_Module__loggerObj xdc_runtime_Registry_Module__loggerObj__C = ((CT__xdc_runtime_Registry_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn0 xdc_runtime_Registry_Module__loggerFxn0__C = ((CT__xdc_runtime_Registry_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn1 xdc_runtime_Registry_Module__loggerFxn1__C = ((CT__xdc_runtime_Registry_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn2 xdc_runtime_Registry_Module__loggerFxn2__C = ((CT__xdc_runtime_Registry_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn4 xdc_runtime_Registry_Module__loggerFxn4__C = ((CT__xdc_runtime_Registry_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn8 xdc_runtime_Registry_Module__loggerFxn8__C = ((CT__xdc_runtime_Registry_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Registry_Object__count xdc_runtime_Registry_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Registry_Object__heap xdc_runtime_Registry_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Registry_Object__sizeof xdc_runtime_Registry_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Registry_Object__table xdc_runtime_Registry_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Startup_Module__diagsEnabled xdc_runtime_Startup_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Startup_Module__diagsIncluded xdc_runtime_Startup_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Startup_Module__diagsMask xdc_runtime_Startup_Module__diagsMask__C = ((CT__xdc_runtime_Startup_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Startup_Module__gateObj xdc_runtime_Startup_Module__gateObj__C = ((CT__xdc_runtime_Startup_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Startup_Module__gatePrms xdc_runtime_Startup_Module__gatePrms__C = ((CT__xdc_runtime_Startup_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Startup_Module__id xdc_runtime_Startup_Module__id__C = (xdc_Bits16)0xb
const __FAR__ CT__xdc_runtime_Startup_Module__loggerDefined xdc_runtime_Startup_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Startup_Module__loggerObj xdc_runtime_Startup_Module__loggerObj__C = ((CT__xdc_runtime_Startup_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn0 xdc_runtime_Startup_Module__loggerFxn0__C = ((CT__xdc_runtime_Startup_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn1 xdc_runtime_Startup_Module__loggerFxn1__C = ((CT__xdc_runtime_Startup_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn2 xdc_runtime_Startup_Module__loggerFxn2__C = ((CT__xdc_runtime_Startup_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn4 xdc_runtime_Startup_Module__loggerFxn4__C = ((CT__xdc_runtime_Startup_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn8 xdc_runtime_Startup_Module__loggerFxn8__C = ((CT__xdc_runtime_Startup_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Startup_Object__count xdc_runtime_Startup_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Startup_Object__heap xdc_runtime_Startup_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Startup_Object__sizeof xdc_runtime_Startup_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Startup_Object__table xdc_runtime_Startup_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Startup_maxPasses xdc_runtime_Startup_maxPasses__C = (xdc_Int)0x20
const __FAR__ CT__xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__C = {2, ((__T1_xdc_runtime_Startup_firstFxns *)xdc_runtime_Startup_firstFxns__A)}
const __FAR__ CT__xdc_runtime_Startup_lastFxns xdc_runtime_Startup_lastFxns__C = {0, 0}
const __FAR__ CT__xdc_runtime_Startup_startModsFxn xdc_runtime_Startup_startModsFxn__C = ((CT__xdc_runtime_Startup_startModsFxn)((xdc_Fxn)xdc_runtime_Startup_startMods__I))
const __FAR__ CT__xdc_runtime_Startup_execImpl xdc_runtime_Startup_execImpl__C = ((CT__xdc_runtime_Startup_execImpl)((xdc_Fxn)xdc_runtime_Startup_exec__I))
const __FAR__ CT__xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__C = ((CT__xdc_runtime_Startup_sfxnTab)xdc_runtime_Startup_sfxnTab__A)
const __FAR__ CT__xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__C = ((CT__xdc_runtime_Startup_sfxnRts)xdc_runtime_Startup_sfxnRts__A)
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsEnabled xdc_runtime_SysStd_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsIncluded xdc_runtime_SysStd_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsMask xdc_runtime_SysStd_Module__diagsMask__C = ((CT__xdc_runtime_SysStd_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__gateObj xdc_runtime_SysStd_Module__gateObj__C = ((CT__xdc_runtime_SysStd_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__gatePrms xdc_runtime_SysStd_Module__gatePrms__C = ((CT__xdc_runtime_SysStd_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__id xdc_runtime_SysStd_Module__id__C = (xdc_Bits16)0xd
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerDefined xdc_runtime_SysStd_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerObj xdc_runtime_SysStd_Module__loggerObj__C = ((CT__xdc_runtime_SysStd_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn0 xdc_runtime_SysStd_Module__loggerFxn0__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn1 xdc_runtime_SysStd_Module__loggerFxn1__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn2 xdc_runtime_SysStd_Module__loggerFxn2__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn4 xdc_runtime_SysStd_Module__loggerFxn4__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn8 xdc_runtime_SysStd_Module__loggerFxn8__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_SysStd_Object__count xdc_runtime_SysStd_Object__count__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Object__heap xdc_runtime_SysStd_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Object__sizeof xdc_runtime_SysStd_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_SysStd_Object__table xdc_runtime_SysStd_Object__table__C = 0
const __FAR__ CT__xdc_runtime_System_Module__diagsEnabled xdc_runtime_System_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_System_Module__diagsIncluded xdc_runtime_System_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_System_Module__diagsMask xdc_runtime_System_Module__diagsMask__C = ((CT__xdc_runtime_System_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_System_Module__gateObj xdc_runtime_System_Module__gateObj__C = ((CT__xdc_runtime_System_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
const __FAR__ CT__xdc_runtime_System_Module__gatePrms xdc_runtime_System_Module__gatePrms__C = ((CT__xdc_runtime_System_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_System_Module__id xdc_runtime_System_Module__id__C = (xdc_Bits16)0xc
const __FAR__ CT__xdc_runtime_System_Module__loggerDefined xdc_runtime_System_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_System_Module__loggerObj xdc_runtime_System_Module__loggerObj__C = ((CT__xdc_runtime_System_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn0 xdc_runtime_System_Module__loggerFxn0__C = ((CT__xdc_runtime_System_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn1 xdc_runtime_System_Module__loggerFxn1__C = ((CT__xdc_runtime_System_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn2 xdc_runtime_System_Module__loggerFxn2__C = ((CT__xdc_runtime_System_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn4 xdc_runtime_System_Module__loggerFxn4__C = ((CT__xdc_runtime_System_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn8 xdc_runtime_System_Module__loggerFxn8__C = ((CT__xdc_runtime_System_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_System_Object__count xdc_runtime_System_Object__count__C = 0
const __FAR__ CT__xdc_runtime_System_Object__heap xdc_runtime_System_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_System_Object__sizeof xdc_runtime_System_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_System_Object__table xdc_runtime_System_Object__table__C = 0
const __FAR__ CT__xdc_runtime_System_A_cannotFitIntoArg xdc_runtime_System_A_cannotFitIntoArg__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
const __FAR__ CT__xdc_runtime_System_maxAtexitHandlers xdc_runtime_System_maxAtexitHandlers__C = (xdc_Int)0x0
const __FAR__ CT__xdc_runtime_System_abortFxn xdc_runtime_System_abortFxn__C = ((CT__xdc_runtime_System_abortFxn)((xdc_Fxn)xdc_runtime_System_abortStd__E))
const __FAR__ CT__xdc_runtime_System_exitFxn xdc_runtime_System_exitFxn__C = ((CT__xdc_runtime_System_exitFxn)((xdc_Fxn)xdc_runtime_System_exitStd__E))
const __FAR__ CT__xdc_runtime_System_extendFxn xdc_runtime_System_extendFxn__C = ((CT__xdc_runtime_System_extendFxn)((xdc_Fxn)xdc_runtime_System_printfExtend__I))
const __FAR__ CT__xdc_runtime_Text_Module__diagsEnabled xdc_runtime_Text_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Text_Module__diagsIncluded xdc_runtime_Text_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Text_Module__diagsMask xdc_runtime_Text_Module__diagsMask__C = ((CT__xdc_runtime_Text_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Text_Module__gateObj xdc_runtime_Text_Module__gateObj__C = ((CT__xdc_runtime_Text_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Text_Module__gatePrms xdc_runtime_Text_Module__gatePrms__C = ((CT__xdc_runtime_Text_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Text_Module__id xdc_runtime_Text_Module__id__C = (xdc_Bits16)0xe
const __FAR__ CT__xdc_runtime_Text_Module__loggerDefined xdc_runtime_Text_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Text_Module__loggerObj xdc_runtime_Text_Module__loggerObj__C = ((CT__xdc_runtime_Text_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn0 xdc_runtime_Text_Module__loggerFxn0__C = ((CT__xdc_runtime_Text_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn1 xdc_runtime_Text_Module__loggerFxn1__C = ((CT__xdc_runtime_Text_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn2 xdc_runtime_Text_Module__loggerFxn2__C = ((CT__xdc_runtime_Text_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn4 xdc_runtime_Text_Module__loggerFxn4__C = ((CT__xdc_runtime_Text_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn8 xdc_runtime_Text_Module__loggerFxn8__C = ((CT__xdc_runtime_Text_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Text_Object__count xdc_runtime_Text_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Text_Object__heap xdc_runtime_Text_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Text_Object__sizeof xdc_runtime_Text_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Text_Object__table xdc_runtime_Text_Object__table__C = 0
const __FAR__ CT__xdc_runtime_Text_nameUnknown xdc_runtime_Text_nameUnknown__C = "{unknown-instance-name}"
const __FAR__ CT__xdc_runtime_Text_nameEmpty xdc_runtime_Text_nameEmpty__C = "{empty-instance-name}"
const __FAR__ CT__xdc_runtime_Text_nameStatic xdc_runtime_Text_nameStatic__C = "{static-instance-name}"
const __FAR__ CT__xdc_runtime_Text_isLoaded xdc_runtime_Text_isLoaded__C = 0
const __FAR__ CT__xdc_runtime_Text_charTab xdc_runtime_Text_charTab__C = ((CT__xdc_runtime_Text_charTab)xdc_runtime_Text_charTab__A)
const __FAR__ CT__xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__C = ((CT__xdc_runtime_Text_nodeTab)xdc_runtime_Text_nodeTab__A)
const __FAR__ CT__xdc_runtime_Text_charCnt xdc_runtime_Text_charCnt__C = (xdc_Int16)0x1
const __FAR__ CT__xdc_runtime_Text_nodeCnt xdc_runtime_Text_nodeCnt__C = (xdc_Int16)0x1
const __FAR__ CT__xdc_runtime_Text_unnamedModsLastId xdc_runtime_Text_unnamedModsLastId__C = (xdc_UInt16)0x4000
const __FAR__ CT__xdc_runtime_Text_registryModsLastId xdc_runtime_Text_registryModsLastId__C = (xdc_UInt16)0x7fff
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn xdc_runtime_Text_visitRopeFxn__C = ((CT__xdc_runtime_Text_visitRopeFxn)((xdc_Fxn)xdc_runtime_Text_visitRope__I))
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn2 xdc_runtime_Text_visitRopeFxn2__C = ((CT__xdc_runtime_Text_visitRopeFxn2)((xdc_Fxn)xdc_runtime_Text_visitRope2__I))
const __FAR__ CT__xdc_runtime_Timestamp_Module__diagsEnabled xdc_runtime_Timestamp_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Timestamp_Module__diagsIncluded xdc_runtime_Timestamp_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_Timestamp_Module__diagsMask xdc_runtime_Timestamp_Module__diagsMask__C = ((CT__xdc_runtime_Timestamp_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__gateObj xdc_runtime_Timestamp_Module__gateObj__C = ((CT__xdc_runtime_Timestamp_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__gatePrms xdc_runtime_Timestamp_Module__gatePrms__C = ((CT__xdc_runtime_Timestamp_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__id xdc_runtime_Timestamp_Module__id__C = (xdc_Bits16)0xf
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerDefined xdc_runtime_Timestamp_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerObj xdc_runtime_Timestamp_Module__loggerObj__C = ((CT__xdc_runtime_Timestamp_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn0 xdc_runtime_Timestamp_Module__loggerFxn0__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn1 xdc_runtime_Timestamp_Module__loggerFxn1__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn2 xdc_runtime_Timestamp_Module__loggerFxn2__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn4 xdc_runtime_Timestamp_Module__loggerFxn4__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn8 xdc_runtime_Timestamp_Module__loggerFxn8__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_Timestamp_Object__count xdc_runtime_Timestamp_Object__count__C = 0
const __FAR__ CT__xdc_runtime_Timestamp_Object__heap xdc_runtime_Timestamp_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_Timestamp_Object__sizeof xdc_runtime_Timestamp_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_Timestamp_Object__table xdc_runtime_Timestamp_Object__table__C = 0
const __FAR__ CT__xdc_runtime_TimestampNull_Module__diagsEnabled xdc_runtime_TimestampNull_Module__diagsEnabled__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_TimestampNull_Module__diagsIncluded xdc_runtime_TimestampNull_Module__diagsIncluded__C = (xdc_Bits32)0x10
const __FAR__ CT__xdc_runtime_TimestampNull_Module__diagsMask xdc_runtime_TimestampNull_Module__diagsMask__C = ((CT__xdc_runtime_TimestampNull_Module__diagsMask)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__gateObj xdc_runtime_TimestampNull_Module__gateObj__C = ((CT__xdc_runtime_TimestampNull_Module__gateObj)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__gatePrms xdc_runtime_TimestampNull_Module__gatePrms__C = ((CT__xdc_runtime_TimestampNull_Module__gatePrms)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__id xdc_runtime_TimestampNull_Module__id__C = (xdc_Bits16)0x10
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerDefined xdc_runtime_TimestampNull_Module__loggerDefined__C = 0
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerObj xdc_runtime_TimestampNull_Module__loggerObj__C = ((CT__xdc_runtime_TimestampNull_Module__loggerObj)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn0 xdc_runtime_TimestampNull_Module__loggerFxn0__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn0)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn1 xdc_runtime_TimestampNull_Module__loggerFxn1__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn1)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn2 xdc_runtime_TimestampNull_Module__loggerFxn2__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn2)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn4 xdc_runtime_TimestampNull_Module__loggerFxn4__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn4)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn8 xdc_runtime_TimestampNull_Module__loggerFxn8__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn8)0)
const __FAR__ CT__xdc_runtime_TimestampNull_Object__count xdc_runtime_TimestampNull_Object__count__C = 0
const __FAR__ CT__xdc_runtime_TimestampNull_Object__heap xdc_runtime_TimestampNull_Object__heap__C = 0
const __FAR__ CT__xdc_runtime_TimestampNull_Object__sizeof xdc_runtime_TimestampNull_Object__sizeof__C = 0
const __FAR__ CT__xdc_runtime_TimestampNull_Object__table xdc_runtime_TimestampNull_Object__table__C = 0
__FAR__ int(*volatile __xdc__init__addr)(void) = &__xdc__init
const ti_sysbios_heaps_HeapMem_Handle heap0 = (ti_sysbios_heaps_HeapMem_Handle)((ti_sysbios_heaps_HeapMem_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0])
Macro Definition Documentation
__config__
#define __config__
Definition at line 9 of file dss_mrr_pe674.c.
__nested__
#define __nested__
Definition at line 8 of file dss_mrr_pe674.c.
ATTRIBUTE
#define ATTRIBUTE __attribute__ ((used))
Definition at line 2764 of file dss_mrr_pe674.c.
Module__DGSENAB [1/18]
#define Module__DGSENAB ti_sysbios_BIOS_RtsGateProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [2/18]
#define Module__DGSENAB ti_sysbios_family_c64p_Hwi_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [3/18]
#define Module__DGSENAB ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [4/18]
#define Module__DGSENAB ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [5/18]
#define Module__DGSENAB ti_sysbios_hal_Hwi_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [6/18]
#define Module__DGSENAB ti_sysbios_hal_Hwi_HwiProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [7/18]
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [8/18]
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [9/18]
#define Module__DGSENAB ti_sysbios_knl_Clock_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [10/18]
#define Module__DGSENAB ti_sysbios_knl_Clock_TimerProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [11/18]
#define Module__DGSENAB ti_sysbios_knl_Event_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [12/18]
#define Module__DGSENAB ti_sysbios_knl_Queue_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [13/18]
#define Module__DGSENAB ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [14/18]
#define Module__DGSENAB ti_sysbios_knl_Task_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [15/18]
#define Module__DGSENAB ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [16/18]
#define Module__DGSENAB xdc_runtime_Main_Module_GateProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [17/18]
#define Module__DGSENAB xdc_runtime_Memory_HeapProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSENAB [18/18]
#define Module__DGSENAB xdc_runtime_System_Module_GateProxy_Module__diagsEnabled__C
Definition at line 13181 of file dss_mrr_pe674.c.
Module__DGSINCL [1/18]
#define Module__DGSINCL ti_sysbios_BIOS_RtsGateProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [2/18]
#define Module__DGSINCL ti_sysbios_family_c64p_Hwi_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [3/18]
#define Module__DGSINCL ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [4/18]
#define Module__DGSINCL ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [5/18]
#define Module__DGSINCL ti_sysbios_hal_Hwi_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [6/18]
#define Module__DGSINCL ti_sysbios_hal_Hwi_HwiProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [7/18]
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [8/18]
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [9/18]
#define Module__DGSINCL ti_sysbios_knl_Clock_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [10/18]
#define Module__DGSINCL ti_sysbios_knl_Clock_TimerProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [11/18]
#define Module__DGSINCL ti_sysbios_knl_Event_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [12/18]
#define Module__DGSINCL ti_sysbios_knl_Queue_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [13/18]
#define Module__DGSINCL ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [14/18]
#define Module__DGSINCL ti_sysbios_knl_Task_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [15/18]
#define Module__DGSINCL ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [16/18]
#define Module__DGSINCL xdc_runtime_Main_Module_GateProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [17/18]
#define Module__DGSINCL xdc_runtime_Memory_HeapProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSINCL [18/18]
#define Module__DGSINCL xdc_runtime_System_Module_GateProxy_Module__diagsIncluded__C
Definition at line 13174 of file dss_mrr_pe674.c.
Module__DGSMASK [1/18]
#define Module__DGSMASK ti_sysbios_BIOS_RtsGateProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [2/18]
#define Module__DGSMASK ti_sysbios_family_c64p_Hwi_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [3/18]
#define Module__DGSMASK ti_sysbios_gates_GateHwi_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [4/18]
#define Module__DGSMASK ti_sysbios_gates_GateMutex_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [5/18]
#define Module__DGSMASK ti_sysbios_hal_Hwi_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [6/18]
#define Module__DGSMASK ti_sysbios_hal_Hwi_HwiProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [7/18]
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [8/18]
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [9/18]
#define Module__DGSMASK ti_sysbios_knl_Clock_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [10/18]
#define Module__DGSMASK ti_sysbios_knl_Clock_TimerProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [11/18]
#define Module__DGSMASK ti_sysbios_knl_Event_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [12/18]
#define Module__DGSMASK ti_sysbios_knl_Queue_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [13/18]
#define Module__DGSMASK ti_sysbios_knl_Semaphore_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [14/18]
#define Module__DGSMASK ti_sysbios_knl_Task_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [15/18]
#define Module__DGSMASK ti_sysbios_timers_rti_Timer_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [16/18]
#define Module__DGSMASK xdc_runtime_Main_Module_GateProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [17/18]
#define Module__DGSMASK xdc_runtime_Memory_HeapProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__DGSMASK [18/18]
#define Module__DGSMASK xdc_runtime_System_Module_GateProxy_Module__diagsMask__C
Definition at line 13188 of file dss_mrr_pe674.c.
Module__G_OBJ [1/18]
#define Module__G_OBJ ti_sysbios_BIOS_RtsGateProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [2/18]
#define Module__G_OBJ ti_sysbios_family_c64p_Hwi_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [3/18]
#define Module__G_OBJ ti_sysbios_gates_GateHwi_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [4/18]
#define Module__G_OBJ ti_sysbios_gates_GateMutex_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [5/18]
#define Module__G_OBJ ti_sysbios_hal_Hwi_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [6/18]
#define Module__G_OBJ ti_sysbios_hal_Hwi_HwiProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [7/18]
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [8/18]
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [9/18]
#define Module__G_OBJ ti_sysbios_knl_Clock_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [10/18]
#define Module__G_OBJ ti_sysbios_knl_Clock_TimerProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [11/18]
#define Module__G_OBJ ti_sysbios_knl_Event_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [12/18]
#define Module__G_OBJ ti_sysbios_knl_Queue_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [13/18]
#define Module__G_OBJ ti_sysbios_knl_Semaphore_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [14/18]
#define Module__G_OBJ ti_sysbios_knl_Task_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [15/18]
#define Module__G_OBJ ti_sysbios_timers_rti_Timer_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [16/18]
#define Module__G_OBJ xdc_runtime_Main_Module_GateProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [17/18]
#define Module__G_OBJ xdc_runtime_Memory_HeapProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_OBJ [18/18]
#define Module__G_OBJ xdc_runtime_System_Module_GateProxy_Module__gateObj__C
Definition at line 13245 of file dss_mrr_pe674.c.
Module__G_PRMS [1/18]
#define Module__G_PRMS ti_sysbios_BIOS_RtsGateProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [2/18]
#define Module__G_PRMS ti_sysbios_family_c64p_Hwi_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [3/18]
#define Module__G_PRMS ti_sysbios_gates_GateHwi_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [4/18]
#define Module__G_PRMS ti_sysbios_gates_GateMutex_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [5/18]
#define Module__G_PRMS ti_sysbios_hal_Hwi_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [6/18]
#define Module__G_PRMS ti_sysbios_hal_Hwi_HwiProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [7/18]
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [8/18]
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [9/18]
#define Module__G_PRMS ti_sysbios_knl_Clock_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [10/18]
#define Module__G_PRMS ti_sysbios_knl_Clock_TimerProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [11/18]
#define Module__G_PRMS ti_sysbios_knl_Event_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [12/18]
#define Module__G_PRMS ti_sysbios_knl_Queue_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [13/18]
#define Module__G_PRMS ti_sysbios_knl_Semaphore_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [14/18]
#define Module__G_PRMS ti_sysbios_knl_Task_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [15/18]
#define Module__G_PRMS ti_sysbios_timers_rti_Timer_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [16/18]
#define Module__G_PRMS xdc_runtime_Main_Module_GateProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [17/18]
#define Module__G_PRMS xdc_runtime_Memory_HeapProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__G_PRMS [18/18]
#define Module__G_PRMS xdc_runtime_System_Module_GateProxy_Module__gatePrms__C
Definition at line 13252 of file dss_mrr_pe674.c.
Module__GP_create [1/18]
#define Module__GP_create ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [2/18]
#define Module__GP_create ti_sysbios_family_c64p_Hwi_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [3/18]
#define Module__GP_create ti_sysbios_gates_GateHwi_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [4/18]
#define Module__GP_create ti_sysbios_gates_GateMutex_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [5/18]
#define Module__GP_create ti_sysbios_hal_Hwi_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [6/18]
#define Module__GP_create ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [7/18]
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [8/18]
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [9/18]
#define Module__GP_create ti_sysbios_knl_Clock_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [10/18]
#define Module__GP_create ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [11/18]
#define Module__GP_create ti_sysbios_knl_Event_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [12/18]
#define Module__GP_create ti_sysbios_knl_Queue_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [13/18]
#define Module__GP_create ti_sysbios_knl_Semaphore_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [14/18]
#define Module__GP_create ti_sysbios_knl_Task_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [15/18]
#define Module__GP_create ti_sysbios_timers_rti_Timer_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [16/18]
#define Module__GP_create xdc_runtime_Main_Module_GateProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [17/18]
#define Module__GP_create xdc_runtime_Memory_HeapProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_create [18/18]
#define Module__GP_create xdc_runtime_System_Module_GateProxy_Module_GateProxy_create
Definition at line 13256 of file dss_mrr_pe674.c.
Module__GP_delete [1/18]
#define Module__GP_delete ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [2/18]
#define Module__GP_delete ti_sysbios_family_c64p_Hwi_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [3/18]
#define Module__GP_delete ti_sysbios_gates_GateHwi_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [4/18]
#define Module__GP_delete ti_sysbios_gates_GateMutex_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [5/18]
#define Module__GP_delete ti_sysbios_hal_Hwi_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [6/18]
#define Module__GP_delete ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [7/18]
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [8/18]
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [9/18]
#define Module__GP_delete ti_sysbios_knl_Clock_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [10/18]
#define Module__GP_delete ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [11/18]
#define Module__GP_delete ti_sysbios_knl_Event_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [12/18]
#define Module__GP_delete ti_sysbios_knl_Queue_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [13/18]
#define Module__GP_delete ti_sysbios_knl_Semaphore_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [14/18]
#define Module__GP_delete ti_sysbios_knl_Task_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [15/18]
#define Module__GP_delete ti_sysbios_timers_rti_Timer_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [16/18]
#define Module__GP_delete xdc_runtime_Main_Module_GateProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [17/18]
#define Module__GP_delete xdc_runtime_Memory_HeapProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_delete [18/18]
#define Module__GP_delete xdc_runtime_System_Module_GateProxy_Module_GateProxy_delete
Definition at line 13258 of file dss_mrr_pe674.c.
Module__GP_enter [1/18]
#define Module__GP_enter ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [2/18]
#define Module__GP_enter ti_sysbios_family_c64p_Hwi_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [3/18]
#define Module__GP_enter ti_sysbios_gates_GateHwi_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [4/18]
#define Module__GP_enter ti_sysbios_gates_GateMutex_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [5/18]
#define Module__GP_enter ti_sysbios_hal_Hwi_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [6/18]
#define Module__GP_enter ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [7/18]
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [8/18]
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [9/18]
#define Module__GP_enter ti_sysbios_knl_Clock_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [10/18]
#define Module__GP_enter ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [11/18]
#define Module__GP_enter ti_sysbios_knl_Event_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [12/18]
#define Module__GP_enter ti_sysbios_knl_Queue_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [13/18]
#define Module__GP_enter ti_sysbios_knl_Semaphore_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [14/18]
#define Module__GP_enter ti_sysbios_knl_Task_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [15/18]
#define Module__GP_enter ti_sysbios_timers_rti_Timer_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [16/18]
#define Module__GP_enter xdc_runtime_Main_Module_GateProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [17/18]
#define Module__GP_enter xdc_runtime_Memory_HeapProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_enter [18/18]
#define Module__GP_enter xdc_runtime_System_Module_GateProxy_Module_GateProxy_enter
Definition at line 13260 of file dss_mrr_pe674.c.
Module__GP_leave [1/18]
#define Module__GP_leave ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [2/18]
#define Module__GP_leave ti_sysbios_family_c64p_Hwi_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [3/18]
#define Module__GP_leave ti_sysbios_gates_GateHwi_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [4/18]
#define Module__GP_leave ti_sysbios_gates_GateMutex_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [5/18]
#define Module__GP_leave ti_sysbios_hal_Hwi_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [6/18]
#define Module__GP_leave ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [7/18]
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [8/18]
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [9/18]
#define Module__GP_leave ti_sysbios_knl_Clock_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [10/18]
#define Module__GP_leave ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [11/18]
#define Module__GP_leave ti_sysbios_knl_Event_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [12/18]
#define Module__GP_leave ti_sysbios_knl_Queue_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [13/18]
#define Module__GP_leave ti_sysbios_knl_Semaphore_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [14/18]
#define Module__GP_leave ti_sysbios_knl_Task_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [15/18]
#define Module__GP_leave ti_sysbios_timers_rti_Timer_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [16/18]
#define Module__GP_leave xdc_runtime_Main_Module_GateProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [17/18]
#define Module__GP_leave xdc_runtime_Memory_HeapProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_leave [18/18]
#define Module__GP_leave xdc_runtime_System_Module_GateProxy_Module_GateProxy_leave
Definition at line 13262 of file dss_mrr_pe674.c.
Module__GP_query [1/18]
#define Module__GP_query ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [2/18]
#define Module__GP_query ti_sysbios_family_c64p_Hwi_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [3/18]
#define Module__GP_query ti_sysbios_gates_GateHwi_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [4/18]
#define Module__GP_query ti_sysbios_gates_GateMutex_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [5/18]
#define Module__GP_query ti_sysbios_hal_Hwi_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [6/18]
#define Module__GP_query ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [7/18]
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [8/18]
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [9/18]
#define Module__GP_query ti_sysbios_knl_Clock_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [10/18]
#define Module__GP_query ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [11/18]
#define Module__GP_query ti_sysbios_knl_Event_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [12/18]
#define Module__GP_query ti_sysbios_knl_Queue_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [13/18]
#define Module__GP_query ti_sysbios_knl_Semaphore_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [14/18]
#define Module__GP_query ti_sysbios_knl_Task_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [15/18]
#define Module__GP_query ti_sysbios_timers_rti_Timer_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [16/18]
#define Module__GP_query xdc_runtime_Main_Module_GateProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [17/18]
#define Module__GP_query xdc_runtime_Memory_HeapProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__GP_query [18/18]
#define Module__GP_query xdc_runtime_System_Module_GateProxy_Module_GateProxy_query
Definition at line 13264 of file dss_mrr_pe674.c.
Module__LOGDEF [1/18]
#define Module__LOGDEF ti_sysbios_BIOS_RtsGateProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [2/18]
#define Module__LOGDEF ti_sysbios_family_c64p_Hwi_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [3/18]
#define Module__LOGDEF ti_sysbios_gates_GateHwi_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [4/18]
#define Module__LOGDEF ti_sysbios_gates_GateMutex_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [5/18]
#define Module__LOGDEF ti_sysbios_hal_Hwi_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [6/18]
#define Module__LOGDEF ti_sysbios_hal_Hwi_HwiProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [7/18]
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [8/18]
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [9/18]
#define Module__LOGDEF ti_sysbios_knl_Clock_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [10/18]
#define Module__LOGDEF ti_sysbios_knl_Clock_TimerProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [11/18]
#define Module__LOGDEF ti_sysbios_knl_Event_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [12/18]
#define Module__LOGDEF ti_sysbios_knl_Queue_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [13/18]
#define Module__LOGDEF ti_sysbios_knl_Semaphore_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [14/18]
#define Module__LOGDEF ti_sysbios_knl_Task_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [15/18]
#define Module__LOGDEF ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [16/18]
#define Module__LOGDEF xdc_runtime_Main_Module_GateProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [17/18]
#define Module__LOGDEF xdc_runtime_Memory_HeapProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGDEF [18/18]
#define Module__LOGDEF xdc_runtime_System_Module_GateProxy_Module__loggerDefined__C
Definition at line 13195 of file dss_mrr_pe674.c.
Module__LOGFXN0 [1/18]
#define Module__LOGFXN0 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [2/18]
#define Module__LOGFXN0 ti_sysbios_family_c64p_Hwi_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [3/18]
#define Module__LOGFXN0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [4/18]
#define Module__LOGFXN0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [5/18]
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [6/18]
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [7/18]
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [8/18]
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [9/18]
#define Module__LOGFXN0 ti_sysbios_knl_Clock_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [10/18]
#define Module__LOGFXN0 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [11/18]
#define Module__LOGFXN0 ti_sysbios_knl_Event_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [12/18]
#define Module__LOGFXN0 ti_sysbios_knl_Queue_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [13/18]
#define Module__LOGFXN0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [14/18]
#define Module__LOGFXN0 ti_sysbios_knl_Task_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [15/18]
#define Module__LOGFXN0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [16/18]
#define Module__LOGFXN0 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [17/18]
#define Module__LOGFXN0 xdc_runtime_Memory_HeapProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN0 [18/18]
#define Module__LOGFXN0 xdc_runtime_System_Module_GateProxy_Module__loggerFxn0__C
Definition at line 13210 of file dss_mrr_pe674.c.
Module__LOGFXN1 [1/18]
#define Module__LOGFXN1 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [2/18]
#define Module__LOGFXN1 ti_sysbios_family_c64p_Hwi_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [3/18]
#define Module__LOGFXN1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [4/18]
#define Module__LOGFXN1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [5/18]
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [6/18]
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [7/18]
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [8/18]
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [9/18]
#define Module__LOGFXN1 ti_sysbios_knl_Clock_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [10/18]
#define Module__LOGFXN1 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [11/18]
#define Module__LOGFXN1 ti_sysbios_knl_Event_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [12/18]
#define Module__LOGFXN1 ti_sysbios_knl_Queue_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [13/18]
#define Module__LOGFXN1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [14/18]
#define Module__LOGFXN1 ti_sysbios_knl_Task_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [15/18]
#define Module__LOGFXN1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [16/18]
#define Module__LOGFXN1 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [17/18]
#define Module__LOGFXN1 xdc_runtime_Memory_HeapProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN1 [18/18]
#define Module__LOGFXN1 xdc_runtime_System_Module_GateProxy_Module__loggerFxn1__C
Definition at line 13217 of file dss_mrr_pe674.c.
Module__LOGFXN2 [1/18]
#define Module__LOGFXN2 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [2/18]
#define Module__LOGFXN2 ti_sysbios_family_c64p_Hwi_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [3/18]
#define Module__LOGFXN2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [4/18]
#define Module__LOGFXN2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [5/18]
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [6/18]
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [7/18]
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [8/18]
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [9/18]
#define Module__LOGFXN2 ti_sysbios_knl_Clock_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [10/18]
#define Module__LOGFXN2 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [11/18]
#define Module__LOGFXN2 ti_sysbios_knl_Event_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [12/18]
#define Module__LOGFXN2 ti_sysbios_knl_Queue_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [13/18]
#define Module__LOGFXN2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [14/18]
#define Module__LOGFXN2 ti_sysbios_knl_Task_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [15/18]
#define Module__LOGFXN2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [16/18]
#define Module__LOGFXN2 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [17/18]
#define Module__LOGFXN2 xdc_runtime_Memory_HeapProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN2 [18/18]
#define Module__LOGFXN2 xdc_runtime_System_Module_GateProxy_Module__loggerFxn2__C
Definition at line 13224 of file dss_mrr_pe674.c.
Module__LOGFXN4 [1/18]
#define Module__LOGFXN4 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [2/18]
#define Module__LOGFXN4 ti_sysbios_family_c64p_Hwi_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [3/18]
#define Module__LOGFXN4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [4/18]
#define Module__LOGFXN4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [5/18]
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [6/18]
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [7/18]
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [8/18]
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [9/18]
#define Module__LOGFXN4 ti_sysbios_knl_Clock_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [10/18]
#define Module__LOGFXN4 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [11/18]
#define Module__LOGFXN4 ti_sysbios_knl_Event_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [12/18]
#define Module__LOGFXN4 ti_sysbios_knl_Queue_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [13/18]
#define Module__LOGFXN4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [14/18]
#define Module__LOGFXN4 ti_sysbios_knl_Task_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [15/18]
#define Module__LOGFXN4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [16/18]
#define Module__LOGFXN4 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [17/18]
#define Module__LOGFXN4 xdc_runtime_Memory_HeapProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN4 [18/18]
#define Module__LOGFXN4 xdc_runtime_System_Module_GateProxy_Module__loggerFxn4__C
Definition at line 13231 of file dss_mrr_pe674.c.
Module__LOGFXN8 [1/18]
#define Module__LOGFXN8 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [2/18]
#define Module__LOGFXN8 ti_sysbios_family_c64p_Hwi_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [3/18]
#define Module__LOGFXN8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [4/18]
#define Module__LOGFXN8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [5/18]
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [6/18]
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [7/18]
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [8/18]
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [9/18]
#define Module__LOGFXN8 ti_sysbios_knl_Clock_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [10/18]
#define Module__LOGFXN8 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [11/18]
#define Module__LOGFXN8 ti_sysbios_knl_Event_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [12/18]
#define Module__LOGFXN8 ti_sysbios_knl_Queue_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [13/18]
#define Module__LOGFXN8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [14/18]
#define Module__LOGFXN8 ti_sysbios_knl_Task_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [15/18]
#define Module__LOGFXN8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [16/18]
#define Module__LOGFXN8 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [17/18]
#define Module__LOGFXN8 xdc_runtime_Memory_HeapProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGFXN8 [18/18]
#define Module__LOGFXN8 xdc_runtime_System_Module_GateProxy_Module__loggerFxn8__C
Definition at line 13238 of file dss_mrr_pe674.c.
Module__LOGOBJ [1/18]
#define Module__LOGOBJ ti_sysbios_BIOS_RtsGateProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [2/18]
#define Module__LOGOBJ ti_sysbios_family_c64p_Hwi_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [3/18]
#define Module__LOGOBJ ti_sysbios_gates_GateHwi_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [4/18]
#define Module__LOGOBJ ti_sysbios_gates_GateMutex_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [5/18]
#define Module__LOGOBJ ti_sysbios_hal_Hwi_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [6/18]
#define Module__LOGOBJ ti_sysbios_hal_Hwi_HwiProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [7/18]
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [8/18]
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [9/18]
#define Module__LOGOBJ ti_sysbios_knl_Clock_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [10/18]
#define Module__LOGOBJ ti_sysbios_knl_Clock_TimerProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [11/18]
#define Module__LOGOBJ ti_sysbios_knl_Event_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [12/18]
#define Module__LOGOBJ ti_sysbios_knl_Queue_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [13/18]
#define Module__LOGOBJ ti_sysbios_knl_Semaphore_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [14/18]
#define Module__LOGOBJ ti_sysbios_knl_Task_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [15/18]
#define Module__LOGOBJ ti_sysbios_timers_rti_Timer_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [16/18]
#define Module__LOGOBJ xdc_runtime_Main_Module_GateProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [17/18]
#define Module__LOGOBJ xdc_runtime_Memory_HeapProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__LOGOBJ [18/18]
#define Module__LOGOBJ xdc_runtime_System_Module_GateProxy_Module__loggerObj__C
Definition at line 13203 of file dss_mrr_pe674.c.
Module__MID [1/18]
#define Module__MID ti_sysbios_BIOS_RtsGateProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [2/18]
#define Module__MID ti_sysbios_family_c64p_Hwi_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [3/18]
#define Module__MID ti_sysbios_gates_GateHwi_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [4/18]
#define Module__MID ti_sysbios_gates_GateMutex_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [5/18]
#define Module__MID ti_sysbios_hal_Hwi_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [6/18]
#define Module__MID ti_sysbios_hal_Hwi_HwiProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [7/18]
#define Module__MID ti_sysbios_heaps_HeapMem_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [8/18]
#define Module__MID ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [9/18]
#define Module__MID ti_sysbios_knl_Clock_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [10/18]
#define Module__MID ti_sysbios_knl_Clock_TimerProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [11/18]
#define Module__MID ti_sysbios_knl_Event_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [12/18]
#define Module__MID ti_sysbios_knl_Queue_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [13/18]
#define Module__MID ti_sysbios_knl_Semaphore_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [14/18]
#define Module__MID ti_sysbios_knl_Task_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [15/18]
#define Module__MID ti_sysbios_timers_rti_Timer_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [16/18]
#define Module__MID xdc_runtime_Main_Module_GateProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [17/18]
#define Module__MID xdc_runtime_Memory_HeapProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Module__MID [18/18]
#define Module__MID xdc_runtime_System_Module_GateProxy_Module__id__C
Definition at line 13167 of file dss_mrr_pe674.c.
Typedef Documentation
Header
typedef union Header Header
ti_sysbios_BIOS_Module_State__
typedef struct ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module_State__
ti_sysbios_BIOS_RtsGateProxy_Module__
typedef struct ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__
ti_sysbios_BIOS_RtsGateProxy_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_BIOS_RtsGateProxy_Object__
Definition at line 147 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module_State__
typedef struct ti_sysbios_family_c64p_Cache_Module_State__ ti_sysbios_family_c64p_Cache_Module_State__
ti_sysbios_family_c64p_EventCombiner_Module_State__
typedef struct ti_sysbios_family_c64p_EventCombiner_Module_State__ ti_sysbios_family_c64p_EventCombiner_Module_State__
ti_sysbios_family_c64p_Exception_Module_State__
typedef struct ti_sysbios_family_c64p_Exception_Module_State__ ti_sysbios_family_c64p_Exception_Module_State__
ti_sysbios_family_c64p_Hwi_Module__
typedef struct ti_sysbios_family_c64p_Hwi_Module__ ti_sysbios_family_c64p_Hwi_Module__
ti_sysbios_family_c64p_Hwi_Module_State__
typedef struct ti_sysbios_family_c64p_Hwi_Module_State__ ti_sysbios_family_c64p_Hwi_Module_State__
ti_sysbios_family_c64p_Hwi_Object__
typedef struct ti_sysbios_family_c64p_Hwi_Object__ ti_sysbios_family_c64p_Hwi_Object__
ti_sysbios_gates_GateHwi_Module__
typedef struct ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__
ti_sysbios_gates_GateHwi_Object__
typedef struct ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__
ti_sysbios_gates_GateMutex_Module__
typedef struct ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__
ti_sysbios_gates_GateMutex_Object__
typedef struct ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__
ti_sysbios_hal_Hwi_HwiProxy_Module__
typedef struct ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__
ti_sysbios_hal_Hwi_HwiProxy_Object__
typedef ti_sysbios_family_c64p_Hwi_Object__ ti_sysbios_hal_Hwi_HwiProxy_Object__
Definition at line 295 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__
typedef struct ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__
ti_sysbios_hal_Hwi_Object__
typedef struct ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__
ti_sysbios_heaps_HeapMem_Module__
typedef struct ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
typedef struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
Definition at line 347 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Object__
typedef struct ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__
ti_sysbios_knl_Clock_Module__
typedef struct ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__
ti_sysbios_knl_Clock_Module_State__
typedef struct ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module_State__
ti_sysbios_knl_Clock_Object__
typedef struct ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__
ti_sysbios_knl_Clock_TimerProxy_Module__
typedef struct ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__
ti_sysbios_knl_Clock_TimerProxy_Object__
typedef ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_knl_Clock_TimerProxy_Object__
Definition at line 425 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__
typedef struct ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__
ti_sysbios_knl_Event_Object__
typedef struct ti_sysbios_knl_Event_Object__ ti_sysbios_knl_Event_Object__
ti_sysbios_knl_Queue_Module__
typedef struct ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__
ti_sysbios_knl_Queue_Object__
typedef struct ti_sysbios_knl_Queue_Object__ ti_sysbios_knl_Queue_Object__
ti_sysbios_knl_Semaphore_Module__
typedef struct ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__
ti_sysbios_knl_Semaphore_Object__
typedef struct ti_sysbios_knl_Semaphore_Object__ ti_sysbios_knl_Semaphore_Object__
ti_sysbios_knl_Task_Module__
typedef struct ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__
ti_sysbios_knl_Task_Module_State__
typedef struct ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module_State__
ti_sysbios_knl_Task_Object__
typedef struct ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__
ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__
typedef struct ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__ ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__
ti_sysbios_timers_rti_Timer_Module__
typedef struct ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__
ti_sysbios_timers_rti_Timer_Module_State__
typedef struct ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module_State__
ti_sysbios_timers_rti_Timer_Object__
typedef struct ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__
ti_sysbios_utils_Load_Module_State__
typedef struct ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module_State__
xdc_runtime_Error_Module_State__
typedef struct xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module_State__
xdc_runtime_Main_Module_GateProxy_Module__
typedef struct xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__
xdc_runtime_Main_Module_GateProxy_Object__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_Main_Module_GateProxy_Object__
Definition at line 638 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_Module__
typedef struct xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__
xdc_runtime_Memory_HeapProxy_Object__
typedef ti_sysbios_heaps_HeapMem_Object__ xdc_runtime_Memory_HeapProxy_Object__
Definition at line 667 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module_State__
typedef struct xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module_State__
xdc_runtime_Registry_Module_State__
typedef struct xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module_State__
xdc_runtime_Startup_Module_State__
typedef struct xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module_State__
xdc_runtime_System_Module_GateProxy_Module__
typedef struct xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__
xdc_runtime_System_Module_GateProxy_Object__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_System_Module_GateProxy_Object__
Definition at line 711 of file dss_mrr_pe674.c.
xdc_runtime_System_Module_State__
typedef struct xdc_runtime_System_Module_State__ xdc_runtime_System_Module_State__
xdc_runtime_Text_Module_State__
typedef struct xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module_State__
Function Documentation
__xdc__init()
int __xdc__init (void)
asm() [1/49]
asm (" .align 0x400 ")
asm() [2/49]
asm (" .global _c_int00 ")
asm() [3/49]
asm (" .global ti_sysbios_family_c64p_Exception_dispatch__E ")
asm() [4/49]
asm (" .global ti_sysbios_family_c64p_Hwi0 ")
asm() [5/49]
asm (" .global ti_sysbios_family_c64p_Hwi_dispatchAlways ")
asm() [6/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int0 ")
asm() [7/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int1 ")
asm() [8/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int10 ")
asm() [9/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int11 ")
asm() [10/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int12 ")
asm() [11/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int13 ")
asm() [12/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int14 ")
asm() [13/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int15 ")
asm() [14/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int2 ")
asm() [15/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int3 ")
asm() [16/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int4 ")
asm() [17/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int5 ")
asm() [18/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int6 ")
asm() [19/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int7 ")
asm() [20/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int8 ")
asm() [21/49]
asm (" .global ti_sysbios_family_c64p_Hwi_int9 ")
asm() [22/49]
asm (" .nocmp ")
asm() [23/49]
asm (" .sect \".vecs\" ")
asm() [24/49]
asm (" b b0 ")
asm() [25/49]
asm (" ldw *++ b15[2], b0 ")
asm() [26/49]
asm (" mvk 1, b0 ")
asm() [27/49]
asm (" mvkh _c_int00, b0 ")
asm() [28/49]
asm (" mvkl _c_int00, b0 ")
asm() [29/49]
asm (" nop ")
asm() [30/49]
asm (" nop 4 ")
asm() [31/49]
asm (" stw b0, *b15-- " [2])
asm() [32/49]
asm (" stw b0, *b15 " [1])
asm() [33/49]
asm ("ti_sysbios_family_c64p_Hwi0: ")
asm() [34/49]
asm ("ti_sysbios_family_c64p_Hwi_int0: ")
asm() [35/49]
asm ("ti_sysbios_family_c64p_Hwi_int10: ")
asm() [36/49]
asm ("ti_sysbios_family_c64p_Hwi_int11: ")
asm() [37/49]
asm ("ti_sysbios_family_c64p_Hwi_int12: ")
asm() [38/49]
asm ("ti_sysbios_family_c64p_Hwi_int13: ")
asm() [39/49]
asm ("ti_sysbios_family_c64p_Hwi_int14: ")
asm() [40/49]
asm ("ti_sysbios_family_c64p_Hwi_int15: ")
asm() [41/49]
asm ("ti_sysbios_family_c64p_Hwi_int1: ")
asm() [42/49]
asm ("ti_sysbios_family_c64p_Hwi_int2: ")
asm() [43/49]
asm ("ti_sysbios_family_c64p_Hwi_int3: ")
asm() [44/49]
asm ("ti_sysbios_family_c64p_Hwi_int4: ")
asm() [45/49]
asm ("ti_sysbios_family_c64p_Hwi_int5: ")
asm() [46/49]
asm ("ti_sysbios_family_c64p_Hwi_int6: ")
asm() [47/49]
asm ("ti_sysbios_family_c64p_Hwi_int7: ")
asm() [48/49]
asm ("ti_sysbios_family_c64p_Hwi_int8: ")
asm() [49/49]
asm ("ti_sysbios_family_c64p_Hwi_int9: ")
calloc()
Void ATTRIBUTE* calloc (SizeT nmemb, SizeT size)
Definition at line 2878 of file dss_mrr_pe674.c.
References ti_sysbios_rts_MemAlloc_alloc().
DSP_sleep()
xdc_Void DSP_sleep (xdc_Void)
free()
Void ATTRIBUTE free (Void * ptr)
Definition at line 2901 of file dss_mrr_pe674.c.
References Header::actualBuf, Header::header, and Header::size.
Referenced by realloc().
malloc()
Void ATTRIBUTE* malloc (SizeT size)
Definition at line 2829 of file dss_mrr_pe674.c.
References ti_sysbios_rts_MemAlloc_alloc().
Referenced by realloc().
memalign()
Void ATTRIBUTE* memalign (SizeT alignment, SizeT size)
Definition at line 2838 of file dss_mrr_pe674.c.
References Header::actualBuf, Header::header, and Header::size.
realloc()
Void ATTRIBUTE* realloc (Void * ptr, SizeT size)
Definition at line 2917 of file dss_mrr_pe674.c.
References free(), Header::header, malloc(), and Header::size.
ti_sysbios_BIOS_atExitFunc__I()
Void ti_sysbios_BIOS_atExitFunc__I (Int notused)
Definition at line 2590 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_startFunc__I().
ti_sysbios_BIOS_errorRaiseHook()
Void ti_sysbios_BIOS_errorRaiseHook (xdc_runtime_Error_Block * eb)
Definition at line 2679 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_removeRTSLock().
ti_sysbios_BIOS_exitFunc() [1/2]
Void ti_sysbios_BIOS_exitFunc (Int stat)
Definition at line 2665 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_removeRTSLock().
ti_sysbios_BIOS_exitFunc() [2/2]
xdc_Void ti_sysbios_BIOS_exitFunc (xdc_Int)
ti_sysbios_BIOS_Module__startupDone__S()
xdc_Bool ti_sysbios_BIOS_Module__startupDone__S (void)
Definition at line 9428 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_nullFunc__I()
Void ti_sysbios_BIOS_nullFunc__I ()
Definition at line 2636 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_registerRTSLock() [1/2]
Void ti_sysbios_BIOS_registerRTSLock ()
Referenced by ti_sysbios_BIOS_startFunc__I().
ti_sysbios_BIOS_registerRTSLock() [2/2]
Void ti_sysbios_BIOS_registerRTSLock (Void)
Definition at line 2643 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_Module__state__V, ti_sysbios_BIOS_rtsLock(), and ti_sysbios_BIOS_rtsUnlock().
ti_sysbios_BIOS_removeRTSLock()
Void ti_sysbios_BIOS_removeRTSLock (Void)
Definition at line 2654 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_errorRaiseHook(), and ti_sysbios_BIOS_exitFunc().
ti_sysbios_BIOS_RtsGateProxy_create()
ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_RtsGateProxy_create (const ti_sysbios_BIOS_RtsGateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8480 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_create().
ti_sysbios_BIOS_RtsGateProxy_delete()
void ti_sysbios_BIOS_RtsGateProxy_delete (ti_sysbios_BIOS_RtsGateProxy_Handle * instp)
Definition at line 8486 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_BIOS_RtsGateProxy_enter__E()
xdc_IArg ti_sysbios_BIOS_RtsGateProxy_enter__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst)
Definition at line 8510 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_RtsGateProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_BIOS_RtsGateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8498 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Handle__label__S().
ti_sysbios_BIOS_RtsGateProxy_leave__E()
xdc_Void ti_sysbios_BIOS_RtsGateProxy_leave__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst, xdc_IArg key)
Definition at line 8516 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S (void)
Definition at line 8474 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Module__startupDone__S().
ti_sysbios_BIOS_RtsGateProxy_Params__init__S()
void ti_sysbios_BIOS_RtsGateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8492 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Params__init__S().
ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S (void)
Definition at line 9543 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S (void)
Definition at line 9547 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Module__FXNS__C.
ti_sysbios_BIOS_RtsGateProxy_query__E()
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_query__E (xdc_Int qual)
Definition at line 8504 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_rtsLock()
Void ti_sysbios_BIOS_rtsLock ()
Definition at line 2606 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_registerRTSLock().
ti_sysbios_BIOS_rtsUnlock()
Void ti_sysbios_BIOS_rtsUnlock ()
Definition at line 2622 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_registerRTSLock().
ti_sysbios_BIOS_startFunc()
xdc_Void ti_sysbios_BIOS_startFunc (xdc_Void)
ti_sysbios_BIOS_startFunc__I()
Void ti_sysbios_BIOS_startFunc__I ()
Definition at line 2568 of file dss_mrr_pe674.c.
References ti_sysbios_BIOS_atExitFunc__I(), ti_sysbios_BIOS_registerRTSLock(), and ti_sysbios_timers_rti_Timer_startup__E().
ti_sysbios_family_c62_IntrinsicsSupport_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c62_IntrinsicsSupport_Module__startupDone__S (void)
Definition at line 9559 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S().
ti_sysbios_family_c62_TaskSupport_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c62_TaskSupport_Module__startupDone__S (void)
Definition at line 9571 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S().
ti_sysbios_family_c64p_Cache_Module__startupDone__F()
xdc_Bool ti_sysbios_family_c64p_Cache_Module__startupDone__F (void)
Definition at line 2076 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_c64p_Cache_Module__startupDone__S().
ti_sysbios_family_c64p_Cache_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c64p_Cache_Module__startupDone__S (void)
Definition at line 9583 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Cache_Module__startupDone__F().
ti_sysbios_family_c64p_Cache_Module_startup__E()
xdc_Int ti_sysbios_family_c64p_Cache_Module_startup__E (xdc_Int)
ti_sysbios_family_c64p_EventCombiner_dispatch()
xdc_Void ti_sysbios_family_c64p_EventCombiner_dispatch (xdc_UArg)
ti_sysbios_family_c64p_EventCombiner_Module__startupDone__F()
xdc_Bool ti_sysbios_family_c64p_EventCombiner_Module__startupDone__F (void)
Definition at line 2060 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_c64p_EventCombiner_Module__startupDone__S().
ti_sysbios_family_c64p_EventCombiner_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c64p_EventCombiner_Module__startupDone__S (void)
Definition at line 9595 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_EventCombiner_Module__startupDone__F().
ti_sysbios_family_c64p_EventCombiner_Module_startup__E()
xdc_Int ti_sysbios_family_c64p_EventCombiner_Module_startup__E (xdc_Int)
ti_sysbios_family_c64p_EventCombiner_unused()
xdc_Void ti_sysbios_family_c64p_EventCombiner_unused (xdc_UArg)
ti_sysbios_family_c64p_Exception_Module__startupDone__F()
xdc_Bool ti_sysbios_family_c64p_Exception_Module__startupDone__F (void)
Definition at line 2064 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_c64p_Exception_Module__startupDone__S().
ti_sysbios_family_c64p_Exception_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c64p_Exception_Module__startupDone__S (void)
Definition at line 9607 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Exception_Module__startupDone__F().
ti_sysbios_family_c64p_Exception_Module_startup__E()
xdc_Int ti_sysbios_family_c64p_Exception_Module_startup__E (xdc_Int)
ti_sysbios_family_c64p_Hwi_construct()
void ti_sysbios_family_c64p_Hwi_construct (ti_sysbios_family_c64p_Hwi_Struct * __obj, xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_c64p_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 9835 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__DESC__C.
ti_sysbios_family_c64p_Hwi_create()
ti_sysbios_family_c64p_Hwi_Handle ti_sysbios_family_c64p_Hwi_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_c64p_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 9811 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__DESC__C.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_create().
ti_sysbios_family_c64p_Hwi_delete()
void ti_sysbios_family_c64p_Hwi_delete (ti_sysbios_family_c64p_Hwi_Handle * instp)
Definition at line 9865 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__delete__S().
ti_sysbios_family_c64p_Hwi_destruct()
void ti_sysbios_family_c64p_Hwi_destruct (ti_sysbios_family_c64p_Hwi_Struct * obj)
Definition at line 9852 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__DESC__C.
ti_sysbios_family_c64p_Hwi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_family_c64p_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9729 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S().
ti_sysbios_family_c64p_Hwi_Module__startupDone__F()
xdc_Bool ti_sysbios_family_c64p_Hwi_Module__startupDone__F (void)
Definition at line 2068 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_c64p_Hwi_Module__startupDone__S().
ti_sysbios_family_c64p_Hwi_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c64p_Hwi_Module__startupDone__S (void)
Definition at line 9723 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Module__startupDone__F().
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S().
ti_sysbios_family_c64p_Hwi_Module_startup__E()
xdc_Int ti_sysbios_family_c64p_Hwi_Module_startup__E (xdc_Int)
ti_sysbios_family_c64p_Hwi_Object__create__S()
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 9782 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__DESC__C.
ti_sysbios_family_c64p_Hwi_Object__delete__S()
xdc_Void ti_sysbios_family_c64p_Hwi_Object__delete__S (xdc_Ptr instp)
Definition at line 9858 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__DESC__C.
Referenced by ti_sysbios_family_c64p_Hwi_delete(), and ti_sysbios_hal_Hwi_HwiProxy_delete().
ti_sysbios_family_c64p_Hwi_Object__first__S()
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__first__S (void)
Definition at line 9756 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Module__::link, and ti_sysbios_family_c64p_Hwi_Module__root__V.
ti_sysbios_family_c64p_Hwi_Object__get__S()
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 9745 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__table__C.
ti_sysbios_family_c64p_Hwi_Object__next__S()
xdc_Ptr ti_sysbios_family_c64p_Hwi_Object__next__S (xdc_Ptr obj)
Definition at line 9769 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Module__::link, and ti_sysbios_family_c64p_Hwi_Module__root__V.
ti_sysbios_family_c64p_Hwi_Params__init__S()
xdc_Void ti_sysbios_family_c64p_Hwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9739 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__PARAMS__C.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Params__init__S().
ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__F()
xdc_Bool ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__F (void)
Definition at line 2072 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__S().
ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__S()
xdc_Bool ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__S (void)
Definition at line 9876 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__F().
Referenced by xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S().
ti_sysbios_family_c64p_TimestampProvider_Module_startup__E()
xdc_Int ti_sysbios_family_c64p_TimestampProvider_Module_startup__E (xdc_Int)
ti_sysbios_gates_GateHwi_construct()
void ti_sysbios_gates_GateHwi_construct (ti_sysbios_gates_GateHwi_Struct * __obj, const ti_sysbios_gates_GateHwi_Params * __paramsPtr)
Definition at line 10091 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
ti_sysbios_gates_GateHwi_create()
ti_sysbios_gates_GateHwi_Handle ti_sysbios_gates_GateHwi_create (const ti_sysbios_gates_GateHwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10073 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
Referenced by xdc_runtime_Main_Module_GateProxy_create(), and xdc_runtime_System_Module_GateProxy_create().
ti_sysbios_gates_GateHwi_delete()
void ti_sysbios_gates_GateHwi_delete (ti_sysbios_gates_GateHwi_Handle * instp)
Definition at line 10116 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
ti_sysbios_gates_GateHwi_destruct()
void ti_sysbios_gates_GateHwi_destruct (ti_sysbios_gates_GateHwi_Struct * obj)
Definition at line 10103 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
ti_sysbios_gates_GateHwi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_gates_GateHwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9998 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Main_Module_GateProxy_Handle__label__S(), and xdc_runtime_System_Module_GateProxy_Handle__label__S().
ti_sysbios_gates_GateHwi_Module__startupDone__S()
xdc_Bool ti_sysbios_gates_GateHwi_Module__startupDone__S (void)
Definition at line 9992 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Main_Module_GateProxy_Module__startupDone__S(), and xdc_runtime_System_Module_GateProxy_Module__startupDone__S().
ti_sysbios_gates_GateHwi_Object__create__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10051 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
ti_sysbios_gates_GateHwi_Object__delete__S()
xdc_Void ti_sysbios_gates_GateHwi_Object__delete__S (xdc_Ptr instp)
Definition at line 10109 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__DESC__C.
Referenced by ti_sysbios_gates_GateHwi_delete(), xdc_runtime_Main_Module_GateProxy_delete(), and xdc_runtime_System_Module_GateProxy_delete().
ti_sysbios_gates_GateHwi_Object__first__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__first__S (void)
Definition at line 10025 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Module__::link, and ti_sysbios_gates_GateHwi_Module__root__V.
ti_sysbios_gates_GateHwi_Object__get__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10014 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__table__C.
ti_sysbios_gates_GateHwi_Object__next__S()
xdc_Ptr ti_sysbios_gates_GateHwi_Object__next__S (xdc_Ptr obj)
Definition at line 10038 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Module__::link, and ti_sysbios_gates_GateHwi_Module__root__V.
ti_sysbios_gates_GateHwi_Params__init__S()
xdc_Void ti_sysbios_gates_GateHwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10008 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__PARAMS__C.
Referenced by xdc_runtime_Main_Module_GateProxy_Params__init__S(), and xdc_runtime_System_Module_GateProxy_Params__init__S().
ti_sysbios_gates_GateMutex_construct()
void ti_sysbios_gates_GateMutex_construct (ti_sysbios_gates_GateMutex_Struct * __obj, const ti_sysbios_gates_GateMutex_Params * __paramsPtr)
Definition at line 10330 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
ti_sysbios_gates_GateMutex_create()
ti_sysbios_gates_GateMutex_Handle ti_sysbios_gates_GateMutex_create (const ti_sysbios_gates_GateMutex_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10312 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
Referenced by ti_sysbios_BIOS_RtsGateProxy_create(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_create().
ti_sysbios_gates_GateMutex_delete()
void ti_sysbios_gates_GateMutex_delete (ti_sysbios_gates_GateMutex_Handle * instp)
Definition at line 10355 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_gates_GateMutex_destruct()
void ti_sysbios_gates_GateMutex_destruct (ti_sysbios_gates_GateMutex_Struct * obj)
Definition at line 10342 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
ti_sysbios_gates_GateMutex_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_gates_GateMutex_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10237 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Handle__label__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S().
ti_sysbios_gates_GateMutex_Module__startupDone__S()
xdc_Bool ti_sysbios_gates_GateMutex_Module__startupDone__S (void)
Definition at line 10231 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S().
ti_sysbios_gates_GateMutex_Object__create__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10290 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
ti_sysbios_gates_GateMutex_Object__delete__S()
xdc_Void ti_sysbios_gates_GateMutex_Object__delete__S (xdc_Ptr instp)
Definition at line 10348 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__DESC__C.
Referenced by ti_sysbios_BIOS_RtsGateProxy_delete(), ti_sysbios_gates_GateMutex_delete(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_delete().
ti_sysbios_gates_GateMutex_Object__first__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__first__S (void)
Definition at line 10264 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Module__::link, and ti_sysbios_gates_GateMutex_Module__root__V.
ti_sysbios_gates_GateMutex_Object__get__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10253 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__table__C.
ti_sysbios_gates_GateMutex_Object__next__S()
xdc_Ptr ti_sysbios_gates_GateMutex_Object__next__S (xdc_Ptr obj)
Definition at line 10277 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Module__::link, and ti_sysbios_gates_GateMutex_Module__root__V.
ti_sysbios_gates_GateMutex_Params__init__S()
xdc_Void ti_sysbios_gates_GateMutex_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10247 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__PARAMS__C.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Params__init__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S().
ti_sysbios_hal_Hwi_checkStack()
xdc_Void ti_sysbios_hal_Hwi_checkStack (xdc_Void)
ti_sysbios_hal_Hwi_construct()
void ti_sysbios_hal_Hwi_construct (ti_sysbios_hal_Hwi_Struct * __obj, xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10582 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_create()
ti_sysbios_hal_Hwi_Handle ti_sysbios_hal_Hwi_create (xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10558 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_delete()
void ti_sysbios_hal_Hwi_delete (ti_sysbios_hal_Hwi_Handle * instp)
Definition at line 10612 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__delete__S().
ti_sysbios_hal_Hwi_destruct()
void ti_sysbios_hal_Hwi_destruct (ti_sysbios_hal_Hwi_Struct * obj)
Definition at line 10599 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_hal_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10476 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E (xdc_UInt intNum)
Definition at line 8631 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_create()
ti_sysbios_hal_Hwi_HwiProxy_Handle ti_sysbios_hal_Hwi_HwiProxy_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_HwiProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8535 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_create().
ti_sysbios_hal_Hwi_HwiProxy_delete()
void ti_sysbios_hal_Hwi_HwiProxy_delete (ti_sysbios_hal_Hwi_HwiProxy_Handle * instp)
Definition at line 8541 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Object__delete__S().
ti_sysbios_hal_Hwi_HwiProxy_disable__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disable__E (void)
Definition at line 8577 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E (xdc_UInt intNum)
Definition at line 8613 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_enable__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enable__E (void)
Definition at line 8583 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E()
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E (xdc_UInt intNum)
Definition at line 8619 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo * stkInfo, xdc_Bool computeStackDepth, xdc_UInt coreId)
Definition at line 8565 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_getFunc__E()
ti_sysbios_interfaces_IHwi_FuncPtr ti_sysbios_hal_Hwi_HwiProxy_getFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_UArg * arg)
Definition at line 8637 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E()
xdc_Ptr ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id)
Definition at line 8649 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_getIrp__E()
ti_sysbios_interfaces_IHwi_Irp ti_sysbios_hal_Hwi_HwiProxy_getIrp__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst)
Definition at line 8661 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo * stkInfo, xdc_Bool computeStackDepth)
Definition at line 8559 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E()
xdc_Char* ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E (void)
Definition at line 8607 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8553 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Handle__label__S().
ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S (void)
Definition at line 8529 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Module__startupDone__S().
ti_sysbios_hal_Hwi_HwiProxy_Params__init__S()
void ti_sysbios_hal_Hwi_HwiProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8547 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_Hwi_Params__init__S().
ti_sysbios_hal_Hwi_HwiProxy_post__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_post__E (xdc_UInt intNum)
Definition at line 8601 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S (void)
Definition at line 10726 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S (void)
Definition at line 10730 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_restore__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restore__E (xdc_UInt key)
Definition at line 8589 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E (xdc_UInt intNum, xdc_UInt key)
Definition at line 8625 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_setFunc__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, ti_sysbios_interfaces_IHwi_FuncPtr fxn, xdc_UArg arg)
Definition at line 8643 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id, xdc_Ptr hookContext)
Definition at line 8655 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_startup__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_startup__E (void)
Definition at line 8571 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E()
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E (void)
Definition at line 8595 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_initStack()
xdc_Void ti_sysbios_hal_Hwi_initStack (xdc_Void)
ti_sysbios_hal_Hwi_Module__startupDone__F()
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__F (void)
Definition at line 2088 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_hal_Hwi_Module__startupDone__S().
ti_sysbios_hal_Hwi_Module__startupDone__S()
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__S (void)
Definition at line 10470 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Module__startupDone__F().
ti_sysbios_hal_Hwi_Module_startup__E()
xdc_Int ti_sysbios_hal_Hwi_Module_startup__E (xdc_Int)
ti_sysbios_hal_Hwi_Object__create__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10529 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
ti_sysbios_hal_Hwi_Object__delete__S()
xdc_Void ti_sysbios_hal_Hwi_Object__delete__S (xdc_Ptr instp)
Definition at line 10605 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__DESC__C.
Referenced by ti_sysbios_hal_Hwi_delete().
ti_sysbios_hal_Hwi_Object__first__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__first__S (void)
Definition at line 10503 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Module__::link, and ti_sysbios_hal_Hwi_Module__root__V.
ti_sysbios_hal_Hwi_Object__get__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10492 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__table__C.
ti_sysbios_hal_Hwi_Object__next__S()
xdc_Ptr ti_sysbios_hal_Hwi_Object__next__S (xdc_Ptr obj)
Definition at line 10516 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Module__::link, and ti_sysbios_hal_Hwi_Module__root__V.
ti_sysbios_hal_Hwi_Params__init__S()
xdc_Void ti_sysbios_hal_Hwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10486 of file dss_mrr_pe674.c.
References ti_sysbios_hal_Hwi_Object__PARAMS__C.
ti_sysbios_heaps_HeapMem_construct()
void ti_sysbios_heaps_HeapMem_construct (ti_sysbios_heaps_HeapMem_Struct * __obj, const ti_sysbios_heaps_HeapMem_Params * __paramsPtr)
Definition at line 10945 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
ti_sysbios_heaps_HeapMem_create()
ti_sysbios_heaps_HeapMem_Handle ti_sysbios_heaps_HeapMem_create (const ti_sysbios_heaps_HeapMem_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10927 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
Referenced by xdc_runtime_Memory_HeapProxy_create().
ti_sysbios_heaps_HeapMem_delete()
void ti_sysbios_heaps_HeapMem_delete (ti_sysbios_heaps_HeapMem_Handle * instp)
Definition at line 10970 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__delete__S().
ti_sysbios_heaps_HeapMem_destruct()
void ti_sysbios_heaps_HeapMem_destruct (ti_sysbios_heaps_HeapMem_Struct * obj)
Definition at line 10957 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
ti_sysbios_heaps_HeapMem_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapMem_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10852 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Memory_HeapProxy_Handle__label__S().
ti_sysbios_heaps_HeapMem_Module__startupDone__S()
xdc_Bool ti_sysbios_heaps_HeapMem_Module__startupDone__S (void)
Definition at line 10846 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Memory_HeapProxy_Module__startupDone__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_create()
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle ti_sysbios_heaps_HeapMem_Module_GateProxy_create (const ti_sysbios_heaps_HeapMem_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8680 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_create().
ti_sysbios_heaps_HeapMem_Module_GateProxy_delete()
void ti_sysbios_heaps_HeapMem_Module_GateProxy_delete (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle * instp)
Definition at line 8686 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E()
xdc_IArg ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst)
Definition at line 8710 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8698 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Handle__label__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E()
xdc_Void ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 8716 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S (void)
Definition at line 8674 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Module__startupDone__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S()
void ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8692 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Params__init__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 11084 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 11088 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateMutex_Module__FXNS__C.
ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E()
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 8704 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Object__create__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10905 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
ti_sysbios_heaps_HeapMem_Object__delete__S()
xdc_Void ti_sysbios_heaps_HeapMem_Object__delete__S (xdc_Ptr instp)
Definition at line 10963 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__DESC__C.
Referenced by ti_sysbios_heaps_HeapMem_delete(), and xdc_runtime_Memory_HeapProxy_delete().
ti_sysbios_heaps_HeapMem_Object__first__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__first__S (void)
Definition at line 10879 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Module__::link, and ti_sysbios_heaps_HeapMem_Module__root__V.
ti_sysbios_heaps_HeapMem_Object__get__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10868 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__table__C.
ti_sysbios_heaps_HeapMem_Object__next__S()
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__next__S (xdc_Ptr obj)
Definition at line 10892 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Module__::link, and ti_sysbios_heaps_HeapMem_Module__root__V.
ti_sysbios_heaps_HeapMem_Params__init__S()
xdc_Void ti_sysbios_heaps_HeapMem_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10862 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__PARAMS__C.
Referenced by xdc_runtime_Memory_HeapProxy_Params__init__S().
ti_sysbios_knl_Clock_construct()
void ti_sysbios_knl_Clock_construct (ti_sysbios_knl_Clock_Struct * __obj, ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params * __paramsPtr)
Definition at line 11304 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_create()
ti_sysbios_knl_Clock_Handle ti_sysbios_knl_Clock_create (ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11286 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_delete()
void ti_sysbios_knl_Clock_delete (ti_sysbios_knl_Clock_Handle * instp)
Definition at line 11329 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__delete__S().
ti_sysbios_knl_Clock_destruct()
void ti_sysbios_knl_Clock_destruct (ti_sysbios_knl_Clock_Struct * obj)
Definition at line 11316 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_doTick__I() [1/2]
Void ti_sysbios_knl_Clock_doTick__I (UArg arg)
Definition at line 2704 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Module__state__V.
ti_sysbios_knl_Clock_doTick__I() [2/2]
xdc_Void ti_sysbios_knl_Clock_doTick__I (xdc_UArg)
ti_sysbios_knl_Clock_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Clock_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 11210 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__startupDone__F()
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__F (void)
Definition at line 2080 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Clock_Module__startupDone__S().
ti_sysbios_knl_Clock_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__S (void)
Definition at line 11204 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Module__startupDone__F().
ti_sysbios_knl_Clock_Module_startup__E()
xdc_Int ti_sysbios_knl_Clock_Module_startup__E (xdc_Int)
ti_sysbios_knl_Clock_Object__create__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 11263 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
ti_sysbios_knl_Clock_Object__delete__S()
xdc_Void ti_sysbios_knl_Clock_Object__delete__S (xdc_Ptr instp)
Definition at line 11322 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__DESC__C.
Referenced by ti_sysbios_knl_Clock_delete().
ti_sysbios_knl_Clock_Object__first__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__first__S (void)
Definition at line 11237 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Module__::link, and ti_sysbios_knl_Clock_Module__root__V.
ti_sysbios_knl_Clock_Object__get__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 11226 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Object__next__S()
xdc_Ptr ti_sysbios_knl_Clock_Object__next__S (xdc_Ptr obj)
Definition at line 11250 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Module__::link, and ti_sysbios_knl_Clock_Module__root__V.
ti_sysbios_knl_Clock_Params__init__S()
xdc_Void ti_sysbios_knl_Clock_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 11220 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Clock_Object__PARAMS__C.
ti_sysbios_knl_Clock_TimerProxy_create()
ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_TimerProxy_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_knl_Clock_TimerProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8735 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_create().
ti_sysbios_knl_Clock_TimerProxy_delete()
void ti_sysbios_knl_Clock_TimerProxy_delete (ti_sysbios_knl_Clock_TimerProxy_Handle * instp)
Definition at line 8741 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__delete__S().
ti_sysbios_knl_Clock_TimerProxy_getCount__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCount__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8819 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_Bool save)
Definition at line 8861 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8849 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 tickPeriod)
Definition at line 8855 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getFreq__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_getFreq__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_runtime_Types_FreqHz * freq)
Definition at line 8825 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getFunc__E()
ti_sysbios_interfaces_ITimer_FuncPtr ti_sysbios_knl_Clock_TimerProxy_getFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UArg * arg)
Definition at line 8831 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8777 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E()
xdc_UInt ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E (void)
Definition at line 8759 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getPeriod__E()
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8813 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_getStatus__E()
ti_sysbios_interfaces_ITimer_Status ti_sysbios_knl_Clock_TimerProxy_getStatus__E (xdc_UInt id)
Definition at line 8765 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Clock_TimerProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8753 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Handle__label__S().
ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S (void)
Definition at line 8729 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__S().
ti_sysbios_knl_Clock_TimerProxy_Params__init__S()
void ti_sysbios_knl_Clock_TimerProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8747 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Params__init__S().
ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S (void)
Definition at line 11443 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S (void)
Definition at line 11447 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_setFunc__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, ti_sysbios_interfaces_ITimer_FuncPtr fxn, xdc_UArg arg)
Definition at line 8837 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_setNextTick__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setNextTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 ticks)
Definition at line 8783 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_setPeriod__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 period)
Definition at line 8801 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E()
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 microsecs)
Definition at line 8807 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_start__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_start__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8789 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_startup__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_startup__E (void)
Definition at line 8771 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_stop__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_stop__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8795 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_trigger__E()
xdc_Void ti_sysbios_knl_Clock_TimerProxy_trigger__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 cycles)
Definition at line 8843 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_construct()
void ti_sysbios_knl_Event_construct (ti_sysbios_knl_Event_Struct * __obj, const ti_sysbios_knl_Event_Params * __paramsPtr)
Definition at line 11662 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_create()
ti_sysbios_knl_Event_Handle ti_sysbios_knl_Event_create (const ti_sysbios_knl_Event_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11644 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_delete()
void ti_sysbios_knl_Event_delete (ti_sysbios_knl_Event_Handle * instp)
Definition at line 11687 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__delete__S().
ti_sysbios_knl_Event_destruct()
void ti_sysbios_knl_Event_destruct (ti_sysbios_knl_Event_Struct * obj)
Definition at line 11674 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Event_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 11569 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Event_Module__startupDone__S (void)
Definition at line 11563 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Object__create__S()
xdc_Ptr ti_sysbios_knl_Event_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 11622 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__DESC__C.
ti_sysbios_knl_Event_Object__delete__S()
xdc_Void ti_sysbios_knl_Event_Object__delete__S (xdc_Ptr instp)
Definition at line 11680 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__DESC__C.
Referenced by ti_sysbios_knl_Event_delete().
ti_sysbios_knl_Event_Object__first__S()
xdc_Ptr ti_sysbios_knl_Event_Object__first__S (void)
Definition at line 11596 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Module__::link, and ti_sysbios_knl_Event_Module__root__V.
ti_sysbios_knl_Event_Object__get__S()
xdc_Ptr ti_sysbios_knl_Event_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 11585 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Object__next__S()
xdc_Ptr ti_sysbios_knl_Event_Object__next__S (xdc_Ptr obj)
Definition at line 11609 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Module__::link, and ti_sysbios_knl_Event_Module__root__V.
ti_sysbios_knl_Event_Params__init__S()
xdc_Void ti_sysbios_knl_Event_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 11579 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Event_Object__PARAMS__C.
ti_sysbios_knl_Idle_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Idle_Module__startupDone__S (void)
Definition at line 11698 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Intrinsics_Module__startupDone__S (void)
Definition at line 11710 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E()
xdc_UInt ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E (xdc_UInt bits)
Definition at line 8880 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S (void)
Definition at line 8874 of file dss_mrr_pe674.c.
References ti_sysbios_family_c62_IntrinsicsSupport_Module__startupDone__S().
ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S (void)
Definition at line 11722 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S (void)
Definition at line 11726 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_construct()
void ti_sysbios_knl_Queue_construct (ti_sysbios_knl_Queue_Struct * __obj, const ti_sysbios_knl_Queue_Params * __paramsPtr)
Definition at line 11940 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_create()
ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Queue_create (const ti_sysbios_knl_Queue_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11922 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_delete()
void ti_sysbios_knl_Queue_delete (ti_sysbios_knl_Queue_Handle * instp)
Definition at line 11965 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__delete__S().
ti_sysbios_knl_Queue_destruct()
void ti_sysbios_knl_Queue_destruct (ti_sysbios_knl_Queue_Struct * obj)
Definition at line 11952 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Queue_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 11847 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Queue_Module__startupDone__S (void)
Definition at line 11841 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Object__create__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 11900 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
ti_sysbios_knl_Queue_Object__delete__S()
xdc_Void ti_sysbios_knl_Queue_Object__delete__S (xdc_Ptr instp)
Definition at line 11958 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__DESC__C.
Referenced by ti_sysbios_knl_Queue_delete().
ti_sysbios_knl_Queue_Object__first__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__first__S (void)
Definition at line 11874 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Module__::link, and ti_sysbios_knl_Queue_Module__root__V.
ti_sysbios_knl_Queue_Object__get__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 11863 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Object__next__S()
xdc_Ptr ti_sysbios_knl_Queue_Object__next__S (xdc_Ptr obj)
Definition at line 11887 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Module__::link, and ti_sysbios_knl_Queue_Module__root__V.
ti_sysbios_knl_Queue_Params__init__S()
xdc_Void ti_sysbios_knl_Queue_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 11857 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Queue_Object__PARAMS__C.
ti_sysbios_knl_Semaphore_construct()
void ti_sysbios_knl_Semaphore_construct (ti_sysbios_knl_Semaphore_Struct * __obj, xdc_Int count, const ti_sysbios_knl_Semaphore_Params * __paramsPtr)
Definition at line 12180 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_create()
ti_sysbios_knl_Semaphore_Handle ti_sysbios_knl_Semaphore_create (xdc_Int count, const ti_sysbios_knl_Semaphore_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12162 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_delete()
void ti_sysbios_knl_Semaphore_delete (ti_sysbios_knl_Semaphore_Handle * instp)
Definition at line 12205 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__delete__S().
ti_sysbios_knl_Semaphore_destruct()
void ti_sysbios_knl_Semaphore_destruct (ti_sysbios_knl_Semaphore_Struct * obj)
Definition at line 12192 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Semaphore_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12086 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Semaphore_Module__startupDone__S (void)
Definition at line 12080 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Object__create__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12139 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
ti_sysbios_knl_Semaphore_Object__delete__S()
xdc_Void ti_sysbios_knl_Semaphore_Object__delete__S (xdc_Ptr instp)
Definition at line 12198 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__DESC__C.
Referenced by ti_sysbios_knl_Semaphore_delete().
ti_sysbios_knl_Semaphore_Object__first__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__first__S (void)
Definition at line 12113 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Module__::link, and ti_sysbios_knl_Semaphore_Module__root__V.
ti_sysbios_knl_Semaphore_Object__get__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12102 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Object__next__S()
xdc_Ptr ti_sysbios_knl_Semaphore_Object__next__S (xdc_Ptr obj)
Definition at line 12126 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Module__::link, and ti_sysbios_knl_Semaphore_Module__root__V.
ti_sysbios_knl_Semaphore_Params__init__S()
xdc_Void ti_sysbios_knl_Semaphore_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12096 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Semaphore_Object__PARAMS__C.
ti_sysbios_knl_Task_construct()
void ti_sysbios_knl_Task_construct (ti_sysbios_knl_Task_Struct * __obj, ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12432 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_create()
ti_sysbios_knl_Task_Handle ti_sysbios_knl_Task_create (ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12408 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_delete()
void ti_sysbios_knl_Task_delete (ti_sysbios_knl_Task_Handle * instp)
Definition at line 12462 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__delete__S().
ti_sysbios_knl_Task_destruct()
void ti_sysbios_knl_Task_destruct (ti_sysbios_knl_Task_Struct * obj)
Definition at line 12449 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_disable__E()
xdc_UInt ti_sysbios_knl_Task_disable__E (xdc_Void)
ti_sysbios_knl_Task_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_knl_Task_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12326 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__startupDone__F()
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__F (void)
Definition at line 2084 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Task_Module__startupDone__S().
ti_sysbios_knl_Task_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__S (void)
Definition at line 12320 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Module__startupDone__F().
ti_sysbios_knl_Task_Module_startup__E()
xdc_Int ti_sysbios_knl_Task_Module_startup__E (xdc_Int)
ti_sysbios_knl_Task_Object__create__S()
xdc_Ptr ti_sysbios_knl_Task_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12379 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__DESC__C.
ti_sysbios_knl_Task_Object__delete__S()
xdc_Void ti_sysbios_knl_Task_Object__delete__S (xdc_Ptr instp)
Definition at line 12455 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__DESC__C.
Referenced by ti_sysbios_knl_Task_delete().
ti_sysbios_knl_Task_Object__first__S()
xdc_Ptr ti_sysbios_knl_Task_Object__first__S (void)
Definition at line 12353 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Module__::link, and ti_sysbios_knl_Task_Module__root__V.
ti_sysbios_knl_Task_Object__get__S()
xdc_Ptr ti_sysbios_knl_Task_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12342 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__table__C.
ti_sysbios_knl_Task_Object__next__S()
xdc_Ptr ti_sysbios_knl_Task_Object__next__S (xdc_Ptr obj)
Definition at line 12366 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Module__::link, and ti_sysbios_knl_Task_Module__root__V.
ti_sysbios_knl_Task_Params__init__S()
xdc_Void ti_sysbios_knl_Task_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12336 of file dss_mrr_pe674.c.
References ti_sysbios_knl_Task_Object__PARAMS__C.
ti_sysbios_knl_Task_restoreHwi__E()
xdc_Void ti_sysbios_knl_Task_restoreHwi__E (xdc_UInt)
ti_sysbios_knl_Task_SupportProxy_checkStack__E()
xdc_Bool ti_sysbios_knl_Task_SupportProxy_checkStack__E (xdc_Char * stack, xdc_SizeT size)
Definition at line 8911 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E()
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E (void)
Definition at line 8929 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E()
xdc_UInt ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E (void)
Definition at line 8923 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S()
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S (void)
Definition at line 8893 of file dss_mrr_pe674.c.
References ti_sysbios_family_c62_TaskSupport_Module__startupDone__S().
ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S()
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S (void)
Definition at line 12473 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S()
xdc_CPtr ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S (void)
Definition at line 12477 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_stackUsed__E()
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_stackUsed__E (xdc_Char * stack, xdc_SizeT size)
Definition at line 8917 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_start__E()
xdc_Ptr ti_sysbios_knl_Task_SupportProxy_start__E (xdc_Ptr curTask, ti_sysbios_interfaces_ITaskSupport_FuncPtr enterFxn, ti_sysbios_interfaces_ITaskSupport_FuncPtr exitFxn, xdc_runtime_Error_Block * eb)
Definition at line 8899 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_SupportProxy_swap__E()
xdc_Void ti_sysbios_knl_Task_SupportProxy_swap__E (xdc_Ptr * oldtskContext, xdc_Ptr * newtskContext)
Definition at line 8905 of file dss_mrr_pe674.c.
ti_sysbios_rts_MemAlloc_alloc()
static Void* ti_sysbios_rts_MemAlloc_alloc (SizeT size) static
Definition at line 2802 of file dss_mrr_pe674.c.
References Header::actualBuf, Header::header, and Header::size.
Referenced by calloc(), and malloc().
ti_sysbios_rts_ti_ThreadLocalStorage_Module__startupDone__S()
xdc_Bool ti_sysbios_rts_ti_ThreadLocalStorage_Module__startupDone__S (void)
Definition at line 12488 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_construct()
void ti_sysbios_timers_rti_Timer_construct (ti_sysbios_timers_rti_Timer_Struct * __obj, xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12716 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
ti_sysbios_timers_rti_Timer_create()
ti_sysbios_timers_rti_Timer_Handle ti_sysbios_timers_rti_Timer_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12692 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
Referenced by ti_sysbios_knl_Clock_TimerProxy_create().
ti_sysbios_timers_rti_Timer_delete()
void ti_sysbios_timers_rti_Timer_delete (ti_sysbios_timers_rti_Timer_Handle * instp)
Definition at line 12746 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__delete__S().
ti_sysbios_timers_rti_Timer_destruct()
void ti_sysbios_timers_rti_Timer_destruct (ti_sysbios_timers_rti_Timer_Struct * obj)
Definition at line 12733 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
ti_sysbios_timers_rti_Timer_Handle__label__S()
xdc_runtime_Types_Label* ti_sysbios_timers_rti_Timer_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12610 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Clock_TimerProxy_Handle__label__S().
ti_sysbios_timers_rti_Timer_Module__startupDone__F()
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__F (void)
Definition at line 2092 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_timers_rti_Timer_Module__startupDone__S().
ti_sysbios_timers_rti_Timer_Module__startupDone__S()
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__S (void)
Definition at line 12604 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__F().
Referenced by ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S().
ti_sysbios_timers_rti_Timer_Module_startup__E()
xdc_Int ti_sysbios_timers_rti_Timer_Module_startup__E (xdc_Int)
ti_sysbios_timers_rti_Timer_Object__create__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12663 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
ti_sysbios_timers_rti_Timer_Object__delete__S()
xdc_Void ti_sysbios_timers_rti_Timer_Object__delete__S (xdc_Ptr instp)
Definition at line 12739 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__DESC__C.
Referenced by ti_sysbios_knl_Clock_TimerProxy_delete(), and ti_sysbios_timers_rti_Timer_delete().
ti_sysbios_timers_rti_Timer_Object__first__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__first__S (void)
Definition at line 12637 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Module__::link, and ti_sysbios_timers_rti_Timer_Module__root__V.
ti_sysbios_timers_rti_Timer_Object__get__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12626 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__table__C.
ti_sysbios_timers_rti_Timer_Object__next__S()
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__next__S (xdc_Ptr obj)
Definition at line 12650 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Module__::link, and ti_sysbios_timers_rti_Timer_Module__root__V.
ti_sysbios_timers_rti_Timer_Params__init__S()
xdc_Void ti_sysbios_timers_rti_Timer_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12620 of file dss_mrr_pe674.c.
References ti_sysbios_timers_rti_Timer_Object__PARAMS__C.
Referenced by ti_sysbios_knl_Clock_TimerProxy_Params__init__S().
ti_sysbios_timers_rti_Timer_startup__E()
Void ti_sysbios_timers_rti_Timer_startup__E ()
Referenced by ti_sysbios_BIOS_startFunc__I().
ti_sysbios_utils_Load_Module__startupDone__S()
xdc_Bool ti_sysbios_utils_Load_Module__startupDone__S (void)
Definition at line 12757 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_taskRegHook__E()
xdc_Void ti_sysbios_utils_Load_taskRegHook__E (xdc_Int)
ti_sysbios_utils_Load_update__E()
Void ti_sysbios_utils_Load_update__E ()
Definition at line 2735 of file dss_mrr_pe674.c.
xdc__META() [1/5]
xdc__META (__ASM__)
xdc__META() [2/5]
xdc__META (__ISA__)
xdc__META() [3/5]
xdc__META (__PLAT__)
xdc__META() [4/5]
xdc__META (__TARG__)
xdc__META() [5/5]
xdc__META (__TRDR__)
xdc_runtime_Assert_Module__startupDone__S()
xdc_Bool xdc_runtime_Assert_Module__startupDone__S (void)
Definition at line 12769 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__startupDone__S()
xdc_Bool xdc_runtime_Core_Module__startupDone__S (void)
Definition at line 12781 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__startupDone__S()
xdc_Bool xdc_runtime_Defaults_Module__startupDone__S (void)
Definition at line 12793 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__startupDone__S()
xdc_Bool xdc_runtime_Diags_Module__startupDone__S (void)
Definition at line 12805 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__startupDone__S()
xdc_Bool xdc_runtime_Error_Module__startupDone__S (void)
Definition at line 12817 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__startupDone__S()
xdc_Bool xdc_runtime_Gate_Module__startupDone__S (void)
Definition at line 12829 of file dss_mrr_pe674.c.
xdc_runtime_IGateProvider_create()
xdc_runtime_IGateProvider_Handle xdc_runtime_IGateProvider_create (xdc_runtime_IGateProvider_Module mod, const xdc_runtime_IGateProvider_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9411 of file dss_mrr_pe674.c.
xdc_runtime_IGateProvider_delete()
void xdc_runtime_IGateProvider_delete (xdc_runtime_IGateProvider_Handle * instp)
Definition at line 9417 of file dss_mrr_pe674.c.
xdc_runtime_IHeap_create()
xdc_runtime_IHeap_Handle xdc_runtime_IHeap_create (xdc_runtime_IHeap_Module mod, const xdc_runtime_IHeap_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9394 of file dss_mrr_pe674.c.
xdc_runtime_IHeap_delete()
void xdc_runtime_IHeap_delete (xdc_runtime_IHeap_Handle * instp)
Definition at line 9400 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__startupDone__S()
xdc_Bool xdc_runtime_Log_Module__startupDone__S (void)
Definition at line 12841 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__startupDone__S()
xdc_Bool xdc_runtime_Main_Module__startupDone__S (void)
Definition at line 12853 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module_GateProxy_create()
xdc_runtime_Main_Module_GateProxy_Handle xdc_runtime_Main_Module_GateProxy_create (const xdc_runtime_Main_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8948 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_create().
xdc_runtime_Main_Module_GateProxy_delete()
void xdc_runtime_Main_Module_GateProxy_delete (xdc_runtime_Main_Module_GateProxy_Handle * instp)
Definition at line 8954 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_runtime_Main_Module_GateProxy_enter__E()
xdc_IArg xdc_runtime_Main_Module_GateProxy_enter__E (xdc_runtime_Main_Module_GateProxy_Handle __inst)
Definition at line 8978 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module_GateProxy_Handle__label__S()
xdc_runtime_Types_Label* xdc_runtime_Main_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8966 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_runtime_Main_Module_GateProxy_leave__E()
xdc_Void xdc_runtime_Main_Module_GateProxy_leave__E (xdc_runtime_Main_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 8984 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module_GateProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_Main_Module_GateProxy_Module__startupDone__S (void)
Definition at line 8942 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
xdc_runtime_Main_Module_GateProxy_Params__init__S()
void xdc_runtime_Main_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8960 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 12968 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 12972 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_runtime_Main_Module_GateProxy_query__E()
xdc_Bool xdc_runtime_Main_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 8972 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_alloc__E()
xdc_Ptr xdc_runtime_Memory_HeapProxy_alloc__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_SizeT size, xdc_SizeT align, xdc_runtime_Error_Block * eb)
Definition at line 9027 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_create()
xdc_runtime_Memory_HeapProxy_Handle xdc_runtime_Memory_HeapProxy_create (const xdc_runtime_Memory_HeapProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9003 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_create().
xdc_runtime_Memory_HeapProxy_delete()
void xdc_runtime_Memory_HeapProxy_delete (xdc_runtime_Memory_HeapProxy_Handle * instp)
Definition at line 9009 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Object__delete__S().
xdc_runtime_Memory_HeapProxy_free__E()
xdc_Void xdc_runtime_Memory_HeapProxy_free__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_Ptr block, xdc_SizeT size)
Definition at line 9033 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_getStats__E()
xdc_Void xdc_runtime_Memory_HeapProxy_getStats__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_runtime_Memory_Stats * stats)
Definition at line 9045 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_Handle__label__S()
xdc_runtime_Types_Label* xdc_runtime_Memory_HeapProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9021 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Handle__label__S().
xdc_runtime_Memory_HeapProxy_isBlocking__E()
xdc_Bool xdc_runtime_Memory_HeapProxy_isBlocking__E (xdc_runtime_Memory_HeapProxy_Handle __inst)
Definition at line 9039 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_Memory_HeapProxy_Module__startupDone__S (void)
Definition at line 8997 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Module__startupDone__S().
xdc_runtime_Memory_HeapProxy_Params__init__S()
void xdc_runtime_Memory_HeapProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9015 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Params__init__S().
xdc_runtime_Memory_HeapProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_Memory_HeapProxy_Proxy__abstract__S (void)
Definition at line 13099 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_Memory_HeapProxy_Proxy__delegate__S (void)
Definition at line 13103 of file dss_mrr_pe674.c.
References ti_sysbios_heaps_HeapMem_Module__FXNS__C.
xdc_runtime_Memory_Module__startupDone__S()
xdc_Bool xdc_runtime_Memory_Module__startupDone__S (void)
Definition at line 12984 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__startupDone__S()
xdc_Bool xdc_runtime_Registry_Module__startupDone__S (void)
Definition at line 13115 of file dss_mrr_pe674.c.
xdc_runtime_Startup_exec__I()
xdc_Void xdc_runtime_Startup_exec__I (void)
Definition at line 2121 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_startModsFxn__C.
xdc_runtime_Startup_Module__startupDone__S()
xdc_Bool xdc_runtime_Startup_Module__startupDone__S (void)
Definition at line 13127 of file dss_mrr_pe674.c.
xdc_runtime_Startup_reset__I()
xdc_Void xdc_runtime_Startup_reset__I (void)
Definition at line 2158 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__startupDone__S()
xdc_Bool xdc_runtime_SysStd_Module__startupDone__S (void)
Definition at line 13139 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_System_SupportProxy_Module__startupDone__S().
xdc_runtime_System_aprintf__E()
xdc_Int xdc_runtime_System_aprintf__E (xdc_CString fmt, ...)
Definition at line 8401 of file dss_mrr_pe674.c.
xdc_runtime_System_aprintf_va__E()
xdc_Int xdc_runtime_System_aprintf_va__E (xdc_CString fmt, va_list __va)
Definition at line 8395 of file dss_mrr_pe674.c.
xdc_runtime_System_asprintf__E()
xdc_Int xdc_runtime_System_asprintf__E (xdc_Char buf[], xdc_CString fmt, ...)
Definition at line 8437 of file dss_mrr_pe674.c.
xdc_runtime_System_asprintf_va__E()
xdc_Int xdc_runtime_System_asprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
Definition at line 8431 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__startupDone__F()
xdc_Bool xdc_runtime_System_Module__startupDone__F (void)
Definition at line 2056 of file dss_mrr_pe674.c.
References xdc_runtime_Startup_Module__state__V.
Referenced by xdc_runtime_System_Module__startupDone__S().
xdc_runtime_System_Module__startupDone__S()
xdc_Bool xdc_runtime_System_Module__startupDone__S (void)
Definition at line 13151 of file dss_mrr_pe674.c.
References xdc_runtime_System_Module__startupDone__F().
xdc_runtime_System_Module_GateProxy_create()
xdc_runtime_System_Module_GateProxy_Handle xdc_runtime_System_Module_GateProxy_create (const xdc_runtime_System_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9064 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_create().
xdc_runtime_System_Module_GateProxy_delete()
void xdc_runtime_System_Module_GateProxy_delete (xdc_runtime_System_Module_GateProxy_Handle * instp)
Definition at line 9070 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_runtime_System_Module_GateProxy_enter__E()
xdc_IArg xdc_runtime_System_Module_GateProxy_enter__E (xdc_runtime_System_Module_GateProxy_Handle __inst)
Definition at line 9094 of file dss_mrr_pe674.c.
xdc_runtime_System_Module_GateProxy_Handle__label__S()
xdc_runtime_Types_Label* xdc_runtime_System_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9082 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_runtime_System_Module_GateProxy_leave__E()
xdc_Void xdc_runtime_System_Module_GateProxy_leave__E (xdc_runtime_System_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 9100 of file dss_mrr_pe674.c.
xdc_runtime_System_Module_GateProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_System_Module_GateProxy_Module__startupDone__S (void)
Definition at line 9058 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
xdc_runtime_System_Module_GateProxy_Params__init__S()
void xdc_runtime_System_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9076 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_runtime_System_Module_GateProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_System_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 13266 of file dss_mrr_pe674.c.
xdc_runtime_System_Module_GateProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_System_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 13270 of file dss_mrr_pe674.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_runtime_System_Module_GateProxy_query__E()
xdc_Bool xdc_runtime_System_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 9088 of file dss_mrr_pe674.c.
xdc_runtime_System_Module_startup__E()
xdc_Int xdc_runtime_System_Module_startup__E (xdc_Int)
xdc_runtime_System_printf__E()
xdc_Int xdc_runtime_System_printf__E (xdc_CString fmt, ...)
Definition at line 8383 of file dss_mrr_pe674.c.
xdc_runtime_System_printf_va__E()
xdc_Int xdc_runtime_System_printf_va__E (xdc_CString fmt, va_list __va)
Definition at line 8377 of file dss_mrr_pe674.c.
xdc_runtime_System_printfExtend__I()
xdc_Int xdc_runtime_System_printfExtend__I (xdc_Char ** pbuf, xdc_CString * pfmt, xdc_VaList * pva, xdc_runtime_System_ParseData * parse)
Definition at line 2187 of file dss_mrr_pe674.c.
xdc_runtime_System_snprintf__E()
xdc_Int xdc_runtime_System_snprintf__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, ...)
Definition at line 8455 of file dss_mrr_pe674.c.
xdc_runtime_System_snprintf_va__E()
xdc_Int xdc_runtime_System_snprintf_va__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, va_list __va)
Definition at line 8449 of file dss_mrr_pe674.c.
xdc_runtime_System_sprintf__E()
xdc_Int xdc_runtime_System_sprintf__E (xdc_Char buf[], xdc_CString fmt, ...)
Definition at line 8419 of file dss_mrr_pe674.c.
xdc_runtime_System_sprintf_va__E()
xdc_Int xdc_runtime_System_sprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
Definition at line 8413 of file dss_mrr_pe674.c.
xdc_runtime_System_SupportProxy_abort__E()
xdc_Void xdc_runtime_System_SupportProxy_abort__E (xdc_CString str)
Definition at line 9119 of file dss_mrr_pe674.c.
xdc_runtime_System_SupportProxy_exit__E()
xdc_Void xdc_runtime_System_SupportProxy_exit__E (xdc_Int stat)
Definition at line 9125 of file dss_mrr_pe674.c.
xdc_runtime_System_SupportProxy_flush__E()
xdc_Void xdc_runtime_System_SupportProxy_flush__E (void)
Definition at line 9131 of file dss_mrr_pe674.c.
xdc_runtime_System_SupportProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_System_SupportProxy_Module__startupDone__S (void)
Definition at line 9113 of file dss_mrr_pe674.c.
References xdc_runtime_SysStd_Module__startupDone__S().
xdc_runtime_System_SupportProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_System_SupportProxy_Proxy__abstract__S (void)
Definition at line 13282 of file dss_mrr_pe674.c.
xdc_runtime_System_SupportProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_System_SupportProxy_Proxy__delegate__S (void)
Definition at line 13286 of file dss_mrr_pe674.c.
References xdc_runtime_SysStd_Module__FXNS__C.
xdc_runtime_System_SupportProxy_putch__E()
xdc_Void xdc_runtime_System_SupportProxy_putch__E (xdc_Char ch)
Definition at line 9137 of file dss_mrr_pe674.c.
xdc_runtime_System_SupportProxy_ready__E()
xdc_Bool xdc_runtime_System_SupportProxy_ready__E (void)
Definition at line 9143 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__startupDone__S()
xdc_Bool xdc_runtime_Text_Module__startupDone__S (void)
Definition at line 13297 of file dss_mrr_pe674.c.
xdc_runtime_Text_visitRope__I()
void xdc_runtime_Text_visitRope__I (xdc_runtime_Text_RopeId rope, xdc_Fxn visFxn, xdc_Ptr visState)
Definition at line 2347 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__startupDone__S()
xdc_Bool xdc_runtime_Timestamp_Module__startupDone__S (void)
Definition at line 13309 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_SupportProxy_get32__E()
xdc_Bits32 xdc_runtime_Timestamp_SupportProxy_get32__E (void)
Definition at line 9162 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_SupportProxy_get64__E()
xdc_Void xdc_runtime_Timestamp_SupportProxy_get64__E (xdc_runtime_Types_Timestamp64 * result)
Definition at line 9168 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_SupportProxy_getFreq__E()
xdc_Void xdc_runtime_Timestamp_SupportProxy_getFreq__E (xdc_runtime_Types_FreqHz * freq)
Definition at line 9174 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S()
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S (void)
Definition at line 9156 of file dss_mrr_pe674.c.
References ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__S().
xdc_runtime_Timestamp_SupportProxy_Proxy__abstract__S()
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Proxy__abstract__S (void)
Definition at line 13333 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_SupportProxy_Proxy__delegate__S()
xdc_CPtr xdc_runtime_Timestamp_SupportProxy_Proxy__delegate__S (void)
Definition at line 13337 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__startupDone__S()
xdc_Bool xdc_runtime_TimestampNull_Module__startupDone__S (void)
Definition at line 13321 of file dss_mrr_pe674.c.
Variable Documentation
__TI_STATIC_BASE
void* __TI_STATIC_BASE
__xdc__init__addr
__FAR__ int(* volatile __xdc__init__addr) (void) = &__xdc__init
Definition at line 13357 of file dss_mrr_pe674.c.
heap0
const ti_sysbios_heaps_HeapMem_Handle heap0 = (ti_sysbios_heaps_HeapMem_Handle)((ti_sysbios_heaps_HeapMem_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0])
Definition at line 13373 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_clockEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_clockEnabled ti_sysbios_BIOS_clockEnabled__C = 1
Definition at line 3106 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_cpuFreq__C
const __FAR__ CT__ti_sysbios_BIOS_cpuFreq ti_sysbios_BIOS_cpuFreq__C
Initial value:
= {
    (xdc_Bits32)0x0,
    (xdc_Bits32)0x23c34600,
}
Definition at line 3087 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_defaultKernelHeapInstance__C
const __FAR__ CT__ti_sysbios_BIOS_defaultKernelHeapInstance ti_sysbios_BIOS_defaultKernelHeapInstance__C = 0
Definition at line 3110 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_heapSection__C
const __FAR__ CT__ti_sysbios_BIOS_heapSection ti_sysbios_BIOS_heapSection__C = 0
Definition at line 3126 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_heapSize__C
const __FAR__ CT__ti_sysbios_BIOS_heapSize ti_sysbios_BIOS_heapSize__C = (xdc_SizeT)0x1000
Definition at line 3122 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_heapTrackEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_heapTrackEnabled ti_sysbios_BIOS_heapTrackEnabled__C = 0
Definition at line 3130 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_installedErrorHook__C
const __FAR__ CT__ti_sysbios_BIOS_installedErrorHook ti_sysbios_BIOS_installedErrorHook__C = ((CT__ti_sysbios_BIOS_installedErrorHook)((xdc_Fxn)xdc_runtime_Error_print__E))
Definition at line 3142 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_kernelHeapSection__C
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSection ti_sysbios_BIOS_kernelHeapSection__C = ".kernel_heap"
Definition at line 3118 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_kernelHeapSize__C
const __FAR__ CT__ti_sysbios_BIOS_kernelHeapSize ti_sysbios_BIOS_kernelHeapSize__C = (xdc_SizeT)0x1000
Definition at line 3114 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsEnabled ti_sysbios_BIOS_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3011 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsIncluded ti_sysbios_BIOS_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3015 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_BIOS_Module__diagsMask ti_sysbios_BIOS_Module__diagsMask__C = ((CT__ti_sysbios_BIOS_Module__diagsMask)0)
Definition at line 3019 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__gateObj__C
const __FAR__ CT__ti_sysbios_BIOS_Module__gateObj ti_sysbios_BIOS_Module__gateObj__C = ((CT__ti_sysbios_BIOS_Module__gateObj)0)
Definition at line 3023 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_BIOS_Module__gatePrms ti_sysbios_BIOS_Module__gatePrms__C = ((CT__ti_sysbios_BIOS_Module__gatePrms)0)
Definition at line 3027 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__id__C
const __FAR__ CT__ti_sysbios_BIOS_Module__id ti_sysbios_BIOS_Module__id__C = (xdc_Bits16)0x1b
Definition at line 3031 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerDefined ti_sysbios_BIOS_Module__loggerDefined__C = 0
Definition at line 3035 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn0 ti_sysbios_BIOS_Module__loggerFxn0__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn0)0)
Definition at line 3043 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn1 ti_sysbios_BIOS_Module__loggerFxn1__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn1)0)
Definition at line 3047 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn2 ti_sysbios_BIOS_Module__loggerFxn2__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn2)0)
Definition at line 3051 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn4 ti_sysbios_BIOS_Module__loggerFxn4__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn4)0)
Definition at line 3055 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerFxn8 ti_sysbios_BIOS_Module__loggerFxn8__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn8)0)
Definition at line 3059 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_BIOS_Module__loggerObj ti_sysbios_BIOS_Module__loggerObj__C = ((CT__ti_sysbios_BIOS_Module__loggerObj)0)
Definition at line 3039 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Module__state__V
ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module__state__V
Initial value:
= {
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0x23c34600,
    },
    (xdc_UInt)0x0,
    ((xdc_IArg)(0x0)),
    (ti_sysbios_BIOS_RtsGateProxy_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[1],
    ti_sysbios_BIOS_ThreadType_Main,
    ((void*)0),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_BIOS_startFunc)),
    ((xdc_Void(*)(xdc_Int))((xdc_Fxn)ti_sysbios_BIOS_exitFunc)),
}
Definition at line 920 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_BIOS_atExitFunc__I(), ti_sysbios_BIOS_registerRTSLock(), ti_sysbios_BIOS_removeRTSLock(), ti_sysbios_BIOS_rtsLock(), and ti_sysbios_BIOS_rtsUnlock().
ti_sysbios_BIOS_mpeEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_mpeEnabled ti_sysbios_BIOS_mpeEnabled__C = 0
Definition at line 3083 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Object__count__C
const __FAR__ CT__ti_sysbios_BIOS_Object__count ti_sysbios_BIOS_Object__count__C = 0
Definition at line 3063 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Object__heap__C
const __FAR__ CT__ti_sysbios_BIOS_Object__heap ti_sysbios_BIOS_Object__heap__C = 0
Definition at line 3067 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Object__sizeof__C
const __FAR__ CT__ti_sysbios_BIOS_Object__sizeof ti_sysbios_BIOS_Object__sizeof__C = 0
Definition at line 3071 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_Object__table__C
const __FAR__ CT__ti_sysbios_BIOS_Object__table ti_sysbios_BIOS_Object__table__C = 0
Definition at line 3075 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_BIOS_runtimeCreatesEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_runtimeCreatesEnabled ti_sysbios_BIOS_runtimeCreatesEnabled__C = 1
Definition at line 3094 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_setupSecureContext__C
const __FAR__ CT__ti_sysbios_BIOS_setupSecureContext ti_sysbios_BIOS_setupSecureContext__C = 0
Definition at line 3134 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_smpEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_smpEnabled ti_sysbios_BIOS_smpEnabled__C = 0
Definition at line 3079 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_swiEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_swiEnabled ti_sysbios_BIOS_swiEnabled__C = 0
Definition at line 3102 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_taskEnabled__C
const __FAR__ CT__ti_sysbios_BIOS_taskEnabled ti_sysbios_BIOS_taskEnabled__C = 1
Definition at line 3098 of file dss_mrr_pe674.c.
ti_sysbios_BIOS_useSK__C
const __FAR__ CT__ti_sysbios_BIOS_useSK ti_sysbios_BIOS_useSK__C = 0
Definition at line 3138 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsEnabled ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3156 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsIncluded ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3160 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__diagsMask)0)
Definition at line 3164 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gateObj)0)
Definition at line 3168 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__gatePrms)0)
Definition at line 3172 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__id__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__id ti_sysbios_family_c62_IntrinsicsSupport_Module__id__C = (xdc_Bits16)0x2e
Definition at line 3176 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerDefined ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerDefined__C = 0
Definition at line 3180 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn0)0)
Definition at line 3188 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn1)0)
Definition at line 3192 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn2)0)
Definition at line 3196 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn4)0)
Definition at line 3200 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8 ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerFxn8)0)
Definition at line 3204 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_c62_IntrinsicsSupport_Module__loggerObj)0)
Definition at line 3184 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Object__count__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__count ti_sysbios_family_c62_IntrinsicsSupport_Object__count__C = 0
Definition at line 3208 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__heap ti_sysbios_family_c62_IntrinsicsSupport_Object__heap__C = 0
Definition at line 3212 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__sizeof ti_sysbios_family_c62_IntrinsicsSupport_Object__sizeof__C = 0
Definition at line 3216 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_IntrinsicsSupport_Object__table__C
const __FAR__ CT__ti_sysbios_family_c62_IntrinsicsSupport_Object__table ti_sysbios_family_c62_IntrinsicsSupport_Object__table__C = 0
Definition at line 3220 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_defaultStackSize__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_defaultStackSize ti_sysbios_family_c62_TaskSupport_defaultStackSize__C = (xdc_SizeT)0x800
Definition at line 3297 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__diagsEnabled ti_sysbios_family_c62_TaskSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3229 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__diagsIncluded ti_sysbios_family_c62_TaskSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3233 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__diagsMask ti_sysbios_family_c62_TaskSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__diagsMask)0)
Definition at line 3237 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__gateObj ti_sysbios_family_c62_TaskSupport_Module__gateObj__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__gateObj)0)
Definition at line 3241 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__gatePrms ti_sysbios_family_c62_TaskSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__gatePrms)0)
Definition at line 3245 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__id__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__id ti_sysbios_family_c62_TaskSupport_Module__id__C = (xdc_Bits16)0x2d
Definition at line 3249 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerDefined ti_sysbios_family_c62_TaskSupport_Module__loggerDefined__C = 0
Definition at line 3253 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn0)0)
Definition at line 3261 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn1)0)
Definition at line 3265 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn2)0)
Definition at line 3269 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn4)0)
Definition at line 3273 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8 ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerFxn8)0)
Definition at line 3277 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Module__loggerObj ti_sysbios_family_c62_TaskSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_c62_TaskSupport_Module__loggerObj)0)
Definition at line 3257 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Object__count__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__count ti_sysbios_family_c62_TaskSupport_Object__count__C = 0
Definition at line 3281 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__heap ti_sysbios_family_c62_TaskSupport_Object__heap__C = 0
Definition at line 3285 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__sizeof ti_sysbios_family_c62_TaskSupport_Object__sizeof__C = 0
Definition at line 3289 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_Object__table__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_Object__table ti_sysbios_family_c62_TaskSupport_Object__table__C = 0
Definition at line 3293 of file dss_mrr_pe674.c.
ti_sysbios_family_c62_TaskSupport_stackAlignment__C
const __FAR__ CT__ti_sysbios_family_c62_TaskSupport_stackAlignment ti_sysbios_family_c62_TaskSupport_stackAlignment__C = (xdc_UInt)0x8
Definition at line 3301 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_E_invalidL1CacheSize__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_E_invalidL1CacheSize ti_sysbios_family_c64p_Cache_E_invalidL1CacheSize__C = (((xdc_runtime_Error_Id)17) << 16 | 0)
Definition at line 3469 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_E_invalidL2CacheSize__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_E_invalidL2CacheSize ti_sysbios_family_c64p_Cache_E_invalidL2CacheSize__C = (((xdc_runtime_Error_Id)18) << 16 | 0)
Definition at line 3473 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFA_BASE__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFA_BASE ti_sysbios_family_c64p_Cache_EMIFA_BASE__C = (xdc_UInt)0x0
Definition at line 3405 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFA_CFG__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFA_CFG ti_sysbios_family_c64p_Cache_EMIFA_CFG__C = ((CT__ti_sysbios_family_c64p_Cache_EMIFA_CFG)0)
Definition at line 3401 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFA_LENGTH__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFA_LENGTH ti_sysbios_family_c64p_Cache_EMIFA_LENGTH__C = (xdc_UInt)0x0
Definition at line 3409 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFB_BASE__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFB_BASE ti_sysbios_family_c64p_Cache_EMIFB_BASE__C = (xdc_UInt)0x0
Definition at line 3417 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFB_CFG__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFB_CFG ti_sysbios_family_c64p_Cache_EMIFB_CFG__C = ((CT__ti_sysbios_family_c64p_Cache_EMIFB_CFG)0)
Definition at line 3413 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFB_LENGTH__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFB_LENGTH ti_sysbios_family_c64p_Cache_EMIFB_LENGTH__C = (xdc_UInt)0x0
Definition at line 3421 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFC_BASE__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFC_BASE ti_sysbios_family_c64p_Cache_EMIFC_BASE__C = (xdc_UInt)0x0
Definition at line 3429 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFC_CFG__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFC_CFG ti_sysbios_family_c64p_Cache_EMIFC_CFG__C = ((CT__ti_sysbios_family_c64p_Cache_EMIFC_CFG)0)
Definition at line 3425 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_EMIFC_LENGTH__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_EMIFC_LENGTH ti_sysbios_family_c64p_Cache_EMIFC_LENGTH__C = (xdc_UInt)0x0
Definition at line 3433 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_initSize__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_initSize ti_sysbios_family_c64p_Cache_initSize__C
Initial value:
= {
    ti_sysbios_family_c64p_Cache_L1Size_32K,
    ti_sysbios_family_c64p_Cache_L1Size_32K,
    ti_sysbios_family_c64p_Cache_L2Size_0K,
}
Definition at line 3393 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR0_31__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR0_31 ti_sysbios_family_c64p_Cache_MAR0_31__C = (xdc_UInt32)0x0
Definition at line 3437 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR128_159__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR128_159 ti_sysbios_family_c64p_Cache_MAR128_159__C = (xdc_UInt32)0x0
Definition at line 3453 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR160_191__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR160_191 ti_sysbios_family_c64p_Cache_MAR160_191__C = (xdc_UInt32)0x0
Definition at line 3457 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR192_223__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR192_223 ti_sysbios_family_c64p_Cache_MAR192_223__C = (xdc_UInt32)0x0
Definition at line 3461 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR224_255__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR224_255 ti_sysbios_family_c64p_Cache_MAR224_255__C = (xdc_UInt32)0x0
Definition at line 3465 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR32_63__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR32_63 ti_sysbios_family_c64p_Cache_MAR32_63__C = (xdc_UInt32)0x0
Definition at line 3441 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR64_95__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR64_95 ti_sysbios_family_c64p_Cache_MAR64_95__C = (xdc_UInt32)0x0
Definition at line 3445 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_MAR96_127__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_MAR96_127 ti_sysbios_family_c64p_Cache_MAR96_127__C = (xdc_UInt32)0x0
Definition at line 3449 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__diagsEnabled ti_sysbios_family_c64p_Cache_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3325 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__diagsIncluded ti_sysbios_family_c64p_Cache_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3329 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__diagsMask ti_sysbios_family_c64p_Cache_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_Cache_Module__diagsMask)0)
Definition at line 3333 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__gateObj ti_sysbios_family_c64p_Cache_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_Cache_Module__gateObj)0)
Definition at line 3337 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__gatePrms ti_sysbios_family_c64p_Cache_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_Cache_Module__gatePrms)0)
Definition at line 3341 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__id__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__id ti_sysbios_family_c64p_Cache_Module__id__C = (xdc_Bits16)0x1a
Definition at line 3345 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerDefined ti_sysbios_family_c64p_Cache_Module__loggerDefined__C = 0
Definition at line 3349 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn0 ti_sysbios_family_c64p_Cache_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn0)0)
Definition at line 3357 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn1 ti_sysbios_family_c64p_Cache_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn1)0)
Definition at line 3361 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn2 ti_sysbios_family_c64p_Cache_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn2)0)
Definition at line 3365 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn4 ti_sysbios_family_c64p_Cache_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn4)0)
Definition at line 3369 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn8 ti_sysbios_family_c64p_Cache_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerFxn8)0)
Definition at line 3373 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Module__loggerObj ti_sysbios_family_c64p_Cache_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_Cache_Module__loggerObj)0)
Definition at line 3353 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Module__state__V
ti_sysbios_family_c64p_Cache_Module_State__ ti_sysbios_family_c64p_Cache_Module__state__V
Initial value:
= {
    ((xdc_UInt32*)0),
}
Definition at line 948 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Object__count__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__count ti_sysbios_family_c64p_Cache_Object__count__C = 0
Definition at line 3377 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__heap ti_sysbios_family_c64p_Cache_Object__heap__C = 0
Definition at line 3381 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__sizeof ti_sysbios_family_c64p_Cache_Object__sizeof__C = 0
Definition at line 3385 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Cache_Object__table__C
const __FAR__ CT__ti_sysbios_family_c64p_Cache_Object__table ti_sysbios_family_c64p_Cache_Object__table__C = 0
Definition at line 3389 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_A_invalidEventId__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_A_invalidEventId ti_sysbios_family_c64p_EventCombiner_A_invalidEventId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4082 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_E_unpluggedEvent__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_E_unpluggedEvent ti_sysbios_family_c64p_EventCombiner_E_unpluggedEvent__C = (((xdc_runtime_Error_Id)9) << 16 | 0)
Definition at line 4086 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_EVTMASK__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_EVTMASK ti_sysbios_family_c64p_EventCombiner_EVTMASK__C
Initial value:
= {
    (xdc_Bits32)(-0x0 - 1),
    (xdc_Bits32)(-0x0 - 1),
    (xdc_Bits32)(-0x0 - 1),
    (xdc_Bits32)(-0x0 - 1),
}
Definition at line 4090 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_EVTRegs__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_EVTRegs ti_sysbios_family_c64p_EventCombiner_EVTRegs__C = ((CT__ti_sysbios_family_c64p_EventCombiner_EVTRegs)(0x1800000))
Definition at line 4078 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsEnabled ti_sysbios_family_c64p_EventCombiner_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4010 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsIncluded ti_sysbios_family_c64p_EventCombiner_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4014 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsMask ti_sysbios_family_c64p_EventCombiner_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__diagsMask)0)
Definition at line 4018 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__gateObj ti_sysbios_family_c64p_EventCombiner_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__gateObj)0)
Definition at line 4022 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__gatePrms ti_sysbios_family_c64p_EventCombiner_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__gatePrms)0)
Definition at line 4026 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__id__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__id ti_sysbios_family_c64p_EventCombiner_Module__id__C = (xdc_Bits16)0x16
Definition at line 4030 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerDefined ti_sysbios_family_c64p_EventCombiner_Module__loggerDefined__C = 0
Definition at line 4034 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn0)0)
Definition at line 4042 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn1)0)
Definition at line 4046 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn2)0)
Definition at line 4050 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn4)0)
Definition at line 4054 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8 ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerFxn8)0)
Definition at line 4058 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerObj ti_sysbios_family_c64p_EventCombiner_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_EventCombiner_Module__loggerObj)0)
Definition at line 4038 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Module__state__V
ti_sysbios_family_c64p_EventCombiner_Module_State__ ti_sysbios_family_c64p_EventCombiner_Module__state__V
Definition at line 1345 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Object__count__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__count ti_sysbios_family_c64p_EventCombiner_Object__count__C = 0
Definition at line 4062 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__heap ti_sysbios_family_c64p_EventCombiner_Object__heap__C = 0
Definition at line 4066 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__sizeof ti_sysbios_family_c64p_EventCombiner_Object__sizeof__C = 0
Definition at line 4070 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_EventCombiner_Object__table__C
const __FAR__ CT__ti_sysbios_family_c64p_EventCombiner_Object__table ti_sysbios_family_c64p_EventCombiner_Object__table__C = 0
Definition at line 4074 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_E_exceptionMax__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_E_exceptionMax ti_sysbios_family_c64p_Exception_E_exceptionMax__C = (((xdc_runtime_Error_Id)11) << 16 | 0)
Definition at line 4216 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_E_exceptionMin__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_E_exceptionMin ti_sysbios_family_c64p_Exception_E_exceptionMin__C = (((xdc_runtime_Error_Id)10) << 16 | 0)
Definition at line 4212 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_enableExternalMPC__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_enableExternalMPC ti_sysbios_family_c64p_Exception_enableExternalMPC__C = 0
Definition at line 4224 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_enablePrint__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_enablePrint ti_sysbios_family_c64p_Exception_enablePrint__C = 1
Definition at line 4228 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_exceptionHook__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_exceptionHook ti_sysbios_family_c64p_Exception_exceptionHook__C = ((CT__ti_sysbios_family_c64p_Exception_exceptionHook)0)
Definition at line 4232 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_externalHook__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_externalHook ti_sysbios_family_c64p_Exception_externalHook__C = ((CT__ti_sysbios_family_c64p_Exception_externalHook)0)
Definition at line 4240 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_internalHook__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_internalHook ti_sysbios_family_c64p_Exception_internalHook__C = ((CT__ti_sysbios_family_c64p_Exception_internalHook)0)
Definition at line 4236 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__diagsEnabled ti_sysbios_family_c64p_Exception_Module__diagsEnabled__C = (xdc_Bits32)0x190
Definition at line 4144 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__diagsIncluded ti_sysbios_family_c64p_Exception_Module__diagsIncluded__C = (xdc_Bits32)0x190
Definition at line 4148 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__diagsMask ti_sysbios_family_c64p_Exception_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_Exception_Module__diagsMask)0)
Definition at line 4152 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__gateObj ti_sysbios_family_c64p_Exception_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_Exception_Module__gateObj)0)
Definition at line 4156 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__gatePrms ti_sysbios_family_c64p_Exception_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_Exception_Module__gatePrms)0)
Definition at line 4160 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__id__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__id ti_sysbios_family_c64p_Exception_Module__id__C = (xdc_Bits16)0x17
Definition at line 4164 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerDefined ti_sysbios_family_c64p_Exception_Module__loggerDefined__C = 0
Definition at line 4168 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn0 ti_sysbios_family_c64p_Exception_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn0)0)
Definition at line 4176 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn1 ti_sysbios_family_c64p_Exception_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn1)0)
Definition at line 4180 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn2 ti_sysbios_family_c64p_Exception_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn2)0)
Definition at line 4184 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn4 ti_sysbios_family_c64p_Exception_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn4)0)
Definition at line 4188 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn8 ti_sysbios_family_c64p_Exception_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerFxn8)0)
Definition at line 4192 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Module__loggerObj ti_sysbios_family_c64p_Exception_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_Exception_Module__loggerObj)0)
Definition at line 4172 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Module__state__V
ti_sysbios_family_c64p_Exception_Module_State__ ti_sysbios_family_c64p_Exception_Module__state__V
Initial value:
= {
    (xdc_Bits32)0x0,
    (xdc_Bits32)0x0,
    (xdc_Bits32)0x0,
    (xdc_Bits32)0x0,
    ((xdc_Void(*)(xdc_Void))0),
    ((ti_sysbios_family_c64p_Exception_Context*)0),
    {
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
        (xdc_Char)0x0,
    },
    ((xdc_Char*)0),
    ((void*)0),
}
Definition at line 1366 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_nmiHook__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_nmiHook ti_sysbios_family_c64p_Exception_nmiHook__C = ((CT__ti_sysbios_family_c64p_Exception_nmiHook)0)
Definition at line 4244 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Object__count__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__count ti_sysbios_family_c64p_Exception_Object__count__C = 0
Definition at line 4196 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__heap ti_sysbios_family_c64p_Exception_Object__heap__C = 0
Definition at line 4200 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__sizeof ti_sysbios_family_c64p_Exception_Object__sizeof__C = 0
Definition at line 4204 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_Object__table__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_Object__table ti_sysbios_family_c64p_Exception_Object__table__C = 0
Definition at line 4208 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_returnHook__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_returnHook ti_sysbios_family_c64p_Exception_returnHook__C = ((CT__ti_sysbios_family_c64p_Exception_returnHook)0)
Definition at line 4248 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Exception_useInternalBuffer__C
const __FAR__ CT__ti_sysbios_family_c64p_Exception_useInternalBuffer ti_sysbios_family_c64p_Exception_useInternalBuffer__C = 0
Definition at line 4220 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi0
void* ti_sysbios_family_c64p_Hwi0
ti_sysbios_family_c64p_Hwi_dispatcherAutoNestingSupport__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherAutoNestingSupport ti_sysbios_family_c64p_Hwi_dispatcherAutoNestingSupport__C = 1
Definition at line 4460 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_dispatcherIrpTrackingSupport__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherIrpTrackingSupport ti_sysbios_family_c64p_Hwi_dispatcherIrpTrackingSupport__C = 1
Definition at line 4472 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_dispatcherSwiSupport__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherSwiSupport ti_sysbios_family_c64p_Hwi_dispatcherSwiSupport__C = 0
Definition at line 4464 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_dispatcherTaskSupport__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_dispatcherTaskSupport ti_sysbios_family_c64p_Hwi_dispatcherTaskSupport__C = 1
Definition at line 4468 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_E_allocSCFailed__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_allocSCFailed ti_sysbios_family_c64p_Hwi_E_allocSCFailed__C = (((xdc_runtime_Error_Id)14) << 16 | 0)
Definition at line 4488 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_E_alreadyDefined__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_alreadyDefined ti_sysbios_family_c64p_Hwi_E_alreadyDefined__C = (((xdc_runtime_Error_Id)12) << 16 | 0)
Definition at line 4480 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_E_handleNotFound__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_handleNotFound ti_sysbios_family_c64p_Hwi_E_handleNotFound__C = (((xdc_runtime_Error_Id)13) << 16 | 0)
Definition at line 4484 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_E_invalidIntNum__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_invalidIntNum ti_sysbios_family_c64p_Hwi_E_invalidIntNum__C = (((xdc_runtime_Error_Id)16) << 16 | 0)
Definition at line 4496 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_E_registerSCFailed__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_E_registerSCFailed ti_sysbios_family_c64p_Hwi_E_registerSCFailed__C = (((xdc_runtime_Error_Id)15) << 16 | 0)
Definition at line 4492 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_enableException__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_enableException ti_sysbios_family_c64p_Hwi_enableException__C = 1
Definition at line 4508 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_hooks__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_hooks ti_sysbios_family_c64p_Hwi_hooks__C = {0, 0}
Definition at line 4528 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_INTRMUX1Address__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_INTRMUX1Address ti_sysbios_family_c64p_Hwi_INTRMUX1Address__C = ((CT__ti_sysbios_family_c64p_Hwi_INTRMUX1Address)(0x1800104))
Definition at line 4476 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_LD_end__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_LD_end ti_sysbios_family_c64p_Hwi_LD_end__C = (((xdc_runtime_Log_Event)13) << 16 | 512)
Definition at line 4504 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_LM_begin__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_LM_begin ti_sysbios_family_c64p_Hwi_LM_begin__C = (((xdc_runtime_Log_Event)12) << 16 | 768)
Definition at line 4500 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__diagsEnabled ti_sysbios_family_c64p_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4392 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__diagsIncluded ti_sysbios_family_c64p_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4396 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__diagsMask ti_sysbios_family_c64p_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__diagsMask)0)
Definition at line 4400 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__gateObj ti_sysbios_family_c64p_Hwi_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__gateObj)0)
Definition at line 4404 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__gatePrms ti_sysbios_family_c64p_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__gatePrms)0)
Definition at line 4408 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__id__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__id ti_sysbios_family_c64p_Hwi_Module__id__C = (xdc_Bits16)0x18
Definition at line 4412 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerDefined ti_sysbios_family_c64p_Hwi_Module__loggerDefined__C = 0
Definition at line 4416 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn0 ti_sysbios_family_c64p_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn0)0)
Definition at line 4424 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn1 ti_sysbios_family_c64p_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn1)0)
Definition at line 4428 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn2 ti_sysbios_family_c64p_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn2)0)
Definition at line 4432 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn4 ti_sysbios_family_c64p_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn4)0)
Definition at line 4436 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn8 ti_sysbios_family_c64p_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerFxn8)0)
Definition at line 4440 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Module__loggerObj ti_sysbios_family_c64p_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_Hwi_Module__loggerObj)0)
Definition at line 4420 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Module__root__V
ti_sysbios_family_c64p_Hwi_Module__ ti_sysbios_family_c64p_Hwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_family_c64p_Hwi_Module__root__V.link,
    &ti_sysbios_family_c64p_Hwi_Module__root__V.link},
}
Definition at line 4279 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_family_c64p_Hwi_Object__first__S(), and ti_sysbios_family_c64p_Hwi_Object__next__S().
ti_sysbios_family_c64p_Hwi_Module__state__V
ti_sysbios_family_c64p_Hwi_Module_State__ ti_sysbios_family_c64p_Hwi_Module__state__V
Definition at line 1408 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Object__count__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__count ti_sysbios_family_c64p_Hwi_Object__count__C = 5
Definition at line 4444 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_family_c64p_Hwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_family_c64p_Hwi_Module__root__V.link,
    sizeof(ti_sysbios_family_c64p_Hwi___S1) - sizeof(ti_sysbios_family_c64p_Hwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_family_c64p_Hwi_Object2__),
    (xdc_CPtr)&ti_sysbios_family_c64p_Hwi_Object__PARAMS__C,
    sizeof(ti_sysbios_family_c64p_Hwi_Params),
}
Definition at line 4256 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_family_c64p_Hwi_construct(), ti_sysbios_family_c64p_Hwi_create(), ti_sysbios_family_c64p_Hwi_destruct(), ti_sysbios_family_c64p_Hwi_Object__create__S(), and ti_sysbios_family_c64p_Hwi_Object__delete__S().
ti_sysbios_family_c64p_Hwi_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__heap ti_sysbios_family_c64p_Hwi_Object__heap__C = 0
Definition at line 4448 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Object__PARAMS__C
const __FAR__ ti_sysbios_family_c64p_Hwi_Params ti_sysbios_family_c64p_Hwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_family_c64p_Hwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_family_c64p_Hwi_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_IHwi_MaskingOption_SELF,
    ((xdc_UArg)(0x0)),
    1,
    (xdc_Int)(-0x0 - 1),
    (xdc_Int)0x0,
    (xdc_Bits16)0x0,
    (xdc_Bits16)0x0,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4260 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_family_c64p_Hwi_Params__init__S().
ti_sysbios_family_c64p_Hwi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__sizeof ti_sysbios_family_c64p_Hwi_Object__sizeof__C = sizeof(ti_sysbios_family_c64p_Hwi_Object__)
Definition at line 4452 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_Object__table__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_Object__table ti_sysbios_family_c64p_Hwi_Object__table__C = ti_sysbios_family_c64p_Hwi_Object__table__V
Definition at line 4456 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_family_c64p_Hwi_Object__get__S().
ti_sysbios_family_c64p_Hwi_Object__table__V
ti_sysbios_family_c64p_Hwi_Object__ ti_sysbios_family_c64p_Hwi_Object__table__V
Definition at line 1386 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_swiDisable__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_swiDisable ti_sysbios_family_c64p_Hwi_swiDisable__C = ((CT__ti_sysbios_family_c64p_Hwi_swiDisable)0)
Definition at line 4512 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_swiRestoreHwi__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_swiRestoreHwi ti_sysbios_family_c64p_Hwi_swiRestoreHwi__C = ((CT__ti_sysbios_family_c64p_Hwi_swiRestoreHwi)0)
Definition at line 4516 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_taskDisable__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_taskDisable ti_sysbios_family_c64p_Hwi_taskDisable__C = ((CT__ti_sysbios_family_c64p_Hwi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
Definition at line 4520 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_Hwi_taskRestoreHwi__C
const __FAR__ CT__ti_sysbios_family_c64p_Hwi_taskRestoreHwi ti_sysbios_family_c64p_Hwi_taskRestoreHwi__C = ((CT__ti_sysbios_family_c64p_Hwi_taskRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Task_restoreHwi__E))
Definition at line 4524 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsEnabled ti_sysbios_family_c64p_TimestampProvider_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 4537 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsIncluded ti_sysbios_family_c64p_TimestampProvider_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 4541 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__diagsMask)0)
Definition at line 4545 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__gateObj__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__gateObj ti_sysbios_family_c64p_TimestampProvider_Module__gateObj__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__gateObj)0)
Definition at line 4549 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__gatePrms)0)
Definition at line 4553 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__id__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__id ti_sysbios_family_c64p_TimestampProvider_Module__id__C = (xdc_Bits16)0x19
Definition at line 4557 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerDefined ti_sysbios_family_c64p_TimestampProvider_Module__loggerDefined__C = 0
Definition at line 4561 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn0)0)
Definition at line 4569 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn1)0)
Definition at line 4573 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn2)0)
Definition at line 4577 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn4)0)
Definition at line 4581 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8 ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerFxn8)0)
Definition at line 4585 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj__C = ((CT__ti_sysbios_family_c64p_TimestampProvider_Module__loggerObj)0)
Definition at line 4565 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Object__count__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__count ti_sysbios_family_c64p_TimestampProvider_Object__count__C = 0
Definition at line 4589 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Object__heap__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__heap ti_sysbios_family_c64p_TimestampProvider_Object__heap__C = 0
Definition at line 4593 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Object__sizeof__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__sizeof ti_sysbios_family_c64p_TimestampProvider_Object__sizeof__C = 0
Definition at line 4597 of file dss_mrr_pe674.c.
ti_sysbios_family_c64p_TimestampProvider_Object__table__C
const __FAR__ CT__ti_sysbios_family_c64p_TimestampProvider_Object__table ti_sysbios_family_c64p_TimestampProvider_Object__table__C = 0
Definition at line 4601 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsEnabled ti_sysbios_gates_GateHwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4639 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsIncluded ti_sysbios_gates_GateHwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4643 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__diagsMask ti_sysbios_gates_GateHwi_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateHwi_Module__diagsMask)0)
Definition at line 4647 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__FXNS__C
const ti_sysbios_gates_GateHwi_Fxns__ ti_sysbios_gates_GateHwi_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IGateProvider_Interface__BASE__C,
    &ti_sysbios_gates_GateHwi_Module__FXNS__C.__sfxns,
    ti_sysbios_gates_GateHwi_query__E,
    ti_sysbios_gates_GateHwi_enter__E,
    ti_sysbios_gates_GateHwi_leave__E,
    {
        ti_sysbios_gates_GateHwi_Object__create__S,
        ti_sysbios_gates_GateHwi_Object__delete__S,
        ti_sysbios_gates_GateHwi_Handle__label__S,
        0x2f,
    }
}
Definition at line 774 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S(), and xdc_runtime_System_Module_GateProxy_Proxy__delegate__S().
ti_sysbios_gates_GateHwi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gateObj ti_sysbios_gates_GateHwi_Module__gateObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__gateObj)0)
Definition at line 4651 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__gatePrms ti_sysbios_gates_GateHwi_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateHwi_Module__gatePrms)0)
Definition at line 4655 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__id__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__id ti_sysbios_gates_GateHwi_Module__id__C = (xdc_Bits16)0x2f
Definition at line 4659 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerDefined ti_sysbios_gates_GateHwi_Module__loggerDefined__C = 0
Definition at line 4663 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0)0)
Definition at line 4671 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1)0)
Definition at line 4675 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2)0)
Definition at line 4679 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4)0)
Definition at line 4683 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8)0)
Definition at line 4687 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Module__loggerObj ti_sysbios_gates_GateHwi_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerObj)0)
Definition at line 4667 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Module__root__V
ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_gates_GateHwi_Module__root__V.link,
    &ti_sysbios_gates_GateHwi_Module__root__V.link},
}
Definition at line 4625 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateHwi_Object__first__S(), and ti_sysbios_gates_GateHwi_Object__next__S().
ti_sysbios_gates_GateHwi_Object__count__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__count ti_sysbios_gates_GateHwi_Object__count__C = 1
Definition at line 4691 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateHwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_gates_GateHwi_Module__FXNS__C,
    &ti_sysbios_gates_GateHwi_Module__root__V.link,
    sizeof(ti_sysbios_gates_GateHwi___S1) - sizeof(ti_sysbios_gates_GateHwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_gates_GateHwi_Object2__),
    (xdc_CPtr)&ti_sysbios_gates_GateHwi_Object__PARAMS__C,
    sizeof(ti_sysbios_gates_GateHwi_Params),
}
Definition at line 4609 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateHwi_construct(), ti_sysbios_gates_GateHwi_create(), ti_sysbios_gates_GateHwi_destruct(), ti_sysbios_gates_GateHwi_Object__create__S(), and ti_sysbios_gates_GateHwi_Object__delete__S().
ti_sysbios_gates_GateHwi_Object__heap__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__heap ti_sysbios_gates_GateHwi_Object__heap__C = 0
Definition at line 4695 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Object__PARAMS__C
const __FAR__ ti_sysbios_gates_GateHwi_Params ti_sysbios_gates_GateHwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_gates_GateHwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_gates_GateHwi_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4613 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateHwi_Params__init__S().
ti_sysbios_gates_GateHwi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__sizeof ti_sysbios_gates_GateHwi_Object__sizeof__C = sizeof(ti_sysbios_gates_GateHwi_Object__)
Definition at line 4699 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateHwi_Object__table__C
const __FAR__ CT__ti_sysbios_gates_GateHwi_Object__table ti_sysbios_gates_GateHwi_Object__table__C = ti_sysbios_gates_GateHwi_Object__table__V
Definition at line 4703 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateHwi_Object__get__S().
ti_sysbios_gates_GateHwi_Object__table__V
ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__table__V
Initial value:
= {
    {
        &ti_sysbios_gates_GateHwi_Module__FXNS__C,
    },
}
Definition at line 1427 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_A_badContext__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_A_badContext ti_sysbios_gates_GateMutex_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4838 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Instance_State_sem__O
const __FAR__ xdc_SizeT ti_sysbios_gates_GateMutex_Instance_State_sem__O = offsetof(ti_sysbios_gates_GateMutex_Object__,Object_field_sem)
Definition at line 1935 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsEnabled ti_sysbios_gates_GateMutex_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4770 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsIncluded ti_sysbios_gates_GateMutex_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4774 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__diagsMask ti_sysbios_gates_GateMutex_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateMutex_Module__diagsMask)0)
Definition at line 4778 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__FXNS__C
const ti_sysbios_gates_GateMutex_Fxns__ ti_sysbios_gates_GateMutex_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IGateProvider_Interface__BASE__C,
    &ti_sysbios_gates_GateMutex_Module__FXNS__C.__sfxns,
    ti_sysbios_gates_GateMutex_query__E,
    ti_sysbios_gates_GateMutex_enter__E,
    ti_sysbios_gates_GateMutex_leave__E,
    {
        ti_sysbios_gates_GateMutex_Object__create__S,
        ti_sysbios_gates_GateMutex_Object__delete__S,
        ti_sysbios_gates_GateMutex_Handle__label__S,
        0x30,
    }
}
Definition at line 795 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S().
ti_sysbios_gates_GateMutex_Module__gateObj__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gateObj ti_sysbios_gates_GateMutex_Module__gateObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__gateObj)0)
Definition at line 4782 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__gatePrms ti_sysbios_gates_GateMutex_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateMutex_Module__gatePrms)0)
Definition at line 4786 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__id__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__id ti_sysbios_gates_GateMutex_Module__id__C = (xdc_Bits16)0x30
Definition at line 4790 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerDefined ti_sysbios_gates_GateMutex_Module__loggerDefined__C = 0
Definition at line 4794 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0)0)
Definition at line 4802 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1)0)
Definition at line 4806 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2)0)
Definition at line 4810 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4)0)
Definition at line 4814 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8)0)
Definition at line 4818 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Module__loggerObj ti_sysbios_gates_GateMutex_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerObj)0)
Definition at line 4798 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Module__root__V
ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__root__V
Initial value:
= {
    {&ti_sysbios_gates_GateMutex_Module__root__V.link,
    &ti_sysbios_gates_GateMutex_Module__root__V.link},
}
Definition at line 4727 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateMutex_Object__first__S(), and ti_sysbios_gates_GateMutex_Object__next__S().
ti_sysbios_gates_GateMutex_Object__count__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__count ti_sysbios_gates_GateMutex_Object__count__C = 2
Definition at line 4822 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateMutex_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_gates_GateMutex_Module__FXNS__C,
    &ti_sysbios_gates_GateMutex_Module__root__V.link,
    sizeof(ti_sysbios_gates_GateMutex___S1) - sizeof(ti_sysbios_gates_GateMutex_Object2__),
    0,
    0,
    sizeof(ti_sysbios_gates_GateMutex_Object2__),
    (xdc_CPtr)&ti_sysbios_gates_GateMutex_Object__PARAMS__C,
    sizeof(ti_sysbios_gates_GateMutex_Params),
}
Definition at line 4711 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateMutex_construct(), ti_sysbios_gates_GateMutex_create(), ti_sysbios_gates_GateMutex_destruct(), ti_sysbios_gates_GateMutex_Object__create__S(), and ti_sysbios_gates_GateMutex_Object__delete__S().
ti_sysbios_gates_GateMutex_Object__heap__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__heap ti_sysbios_gates_GateMutex_Object__heap__C = 0
Definition at line 4826 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Object__PARAMS__C
const __FAR__ ti_sysbios_gates_GateMutex_Params ti_sysbios_gates_GateMutex_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_gates_GateMutex_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_gates_GateMutex_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4715 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateMutex_Params__init__S().
ti_sysbios_gates_GateMutex_Object__sizeof__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__sizeof ti_sysbios_gates_GateMutex_Object__sizeof__C = sizeof(ti_sysbios_gates_GateMutex_Object__)
Definition at line 4830 of file dss_mrr_pe674.c.
ti_sysbios_gates_GateMutex_Object__table__C
const __FAR__ CT__ti_sysbios_gates_GateMutex_Object__table ti_sysbios_gates_GateMutex_Object__table__C = ti_sysbios_gates_GateMutex_Object__table__V
Definition at line 4834 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_gates_GateMutex_Object__get__S().
ti_sysbios_gates_GateMutex_Object__table__V
ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__table__V
Definition at line 1435 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C = 1
Definition at line 4950 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C = 1
Definition at line 4962 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_dispatcherSwiSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherSwiSupport ti_sysbios_hal_Hwi_dispatcherSwiSupport__C = 0
Definition at line 4954 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_dispatcherTaskSupport__C
const __FAR__ CT__ti_sysbios_hal_Hwi_dispatcherTaskSupport ti_sysbios_hal_Hwi_dispatcherTaskSupport__C = 1
Definition at line 4958 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_E_stackOverflow__C
const __FAR__ CT__ti_sysbios_hal_Hwi_E_stackOverflow ti_sysbios_hal_Hwi_E_stackOverflow__C = (((xdc_runtime_Error_Id)29) << 16 | 0)
Definition at line 4966 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_hal_Hwi_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsEnabled ti_sysbios_hal_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4882 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsIncluded ti_sysbios_hal_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4886 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__diagsMask ti_sysbios_hal_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_hal_Hwi_Module__diagsMask)0)
Definition at line 4890 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__gateObj__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gateObj ti_sysbios_hal_Hwi_Module__gateObj__C = ((CT__ti_sysbios_hal_Hwi_Module__gateObj)0)
Definition at line 4894 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__gatePrms ti_sysbios_hal_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_hal_Hwi_Module__gatePrms)0)
Definition at line 4898 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__id__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__id ti_sysbios_hal_Hwi_Module__id__C = (xdc_Bits16)0x2b
Definition at line 4902 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerDefined ti_sysbios_hal_Hwi_Module__loggerDefined__C = 0
Definition at line 4906 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn0)0)
Definition at line 4914 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn1)0)
Definition at line 4918 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn2)0)
Definition at line 4922 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn4)0)
Definition at line 4926 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerFxn8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn8)0)
Definition at line 4930 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Module__loggerObj ti_sysbios_hal_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerObj)0)
Definition at line 4910 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Module__root__V
ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_hal_Hwi_Module__root__V.link,
    &ti_sysbios_hal_Hwi_Module__root__V.link},
}
Definition at line 4867 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_hal_Hwi_Object__first__S(), and ti_sysbios_hal_Hwi_Object__next__S().
ti_sysbios_hal_Hwi_Object__count__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__count ti_sysbios_hal_Hwi_Object__count__C = 1
Definition at line 4934 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_hal_Hwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_hal_Hwi_Module__root__V.link,
    sizeof(ti_sysbios_hal_Hwi___S1) - sizeof(ti_sysbios_hal_Hwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_hal_Hwi_Object2__),
    (xdc_CPtr)&ti_sysbios_hal_Hwi_Object__PARAMS__C,
    sizeof(ti_sysbios_hal_Hwi_Params),
}
Definition at line 4846 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_hal_Hwi_construct(), ti_sysbios_hal_Hwi_create(), ti_sysbios_hal_Hwi_destruct(), ti_sysbios_hal_Hwi_Object__create__S(), and ti_sysbios_hal_Hwi_Object__delete__S().
ti_sysbios_hal_Hwi_Object__heap__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__heap ti_sysbios_hal_Hwi_Object__heap__C = 0
Definition at line 4938 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Object__PARAMS__C
const __FAR__ ti_sysbios_hal_Hwi_Params ti_sysbios_hal_Hwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_hal_Hwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_hal_Hwi_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_IHwi_MaskingOption_SELF,
    ((xdc_UArg)(0x0)),
    1,
    (xdc_Int)(-0x0 - 1),
    (xdc_Int)(-0x0 - 1),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4850 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_hal_Hwi_Params__init__S().
ti_sysbios_hal_Hwi_Object__sizeof__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__sizeof ti_sysbios_hal_Hwi_Object__sizeof__C = sizeof(ti_sysbios_hal_Hwi_Object__)
Definition at line 4942 of file dss_mrr_pe674.c.
ti_sysbios_hal_Hwi_Object__table__C
const __FAR__ CT__ti_sysbios_hal_Hwi_Object__table ti_sysbios_hal_Hwi_Object__table__C = ti_sysbios_hal_Hwi_Object__table__V
Definition at line 4946 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_hal_Hwi_Object__get__S().
ti_sysbios_hal_Hwi_Object__table__V
ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__table__V
Initial value:
= {
    {
        0,
        (ti_sysbios_hal_Hwi_HwiProxy_Handle)&ti_sysbios_family_c64p_Hwi_Object__table__V[4],
    },
}
Definition at line 1443 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_A_align__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_align ti_sysbios_heaps_HeapMem_A_align__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5098 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_A_heapSize__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_heapSize ti_sysbios_heaps_HeapMem_A_heapSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5094 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_A_invalidFree__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_invalidFree ti_sysbios_heaps_HeapMem_A_invalidFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5106 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_A_zeroBlock__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_A_zeroBlock ti_sysbios_heaps_HeapMem_A_zeroBlock__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5090 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_E_memory__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_E_memory ti_sysbios_heaps_HeapMem_E_memory__C = (((xdc_runtime_Error_Id)27) << 16 | 0)
Definition at line 5102 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A
__T1_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A
Definition at line 1459 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsEnabled ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5022 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsIncluded ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5026 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__diagsMask ti_sysbios_heaps_HeapMem_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapMem_Module__diagsMask)0)
Definition at line 5030 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__FXNS__C
const ti_sysbios_heaps_HeapMem_Fxns__ ti_sysbios_heaps_HeapMem_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IHeap_Interface__BASE__C,
    &ti_sysbios_heaps_HeapMem_Module__FXNS__C.__sfxns,
    ti_sysbios_heaps_HeapMem_alloc__E,
    ti_sysbios_heaps_HeapMem_free__E,
    ti_sysbios_heaps_HeapMem_isBlocking__E,
    ti_sysbios_heaps_HeapMem_getStats__E,
    {
        ti_sysbios_heaps_HeapMem_Object__create__S,
        ti_sysbios_heaps_HeapMem_Object__delete__S,
        ti_sysbios_heaps_HeapMem_Handle__label__S,
        0x27,
    }
}
Definition at line 816 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Memory_HeapProxy_Proxy__delegate__S().
ti_sysbios_heaps_HeapMem_Module__gateObj__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gateObj ti_sysbios_heaps_HeapMem_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[0]))
Definition at line 5034 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__gatePrms ti_sysbios_heaps_HeapMem_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gatePrms)0)
Definition at line 5038 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__id__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__id ti_sysbios_heaps_HeapMem_Module__id__C = (xdc_Bits16)0x27
Definition at line 5042 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerDefined ti_sysbios_heaps_HeapMem_Module__loggerDefined__C = 0
Definition at line 5046 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0)0)
Definition at line 5054 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1)0)
Definition at line 5058 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2)0)
Definition at line 5062 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4)0)
Definition at line 5066 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8)0)
Definition at line 5070 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Module__loggerObj ti_sysbios_heaps_HeapMem_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerObj)0)
Definition at line 5050 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Module__root__V
ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__root__V
Initial value:
= {
    {&ti_sysbios_heaps_HeapMem_Module__root__V.link,
    &ti_sysbios_heaps_HeapMem_Module__root__V.link},
}
Definition at line 5001 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_heaps_HeapMem_Object__first__S(), and ti_sysbios_heaps_HeapMem_Object__next__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_heaps_HeapMem_Object__count__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__count ti_sysbios_heaps_HeapMem_Object__count__C = 1
Definition at line 5074 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapMem_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_heaps_HeapMem_Module__FXNS__C,
    &ti_sysbios_heaps_HeapMem_Module__root__V.link,
    sizeof(ti_sysbios_heaps_HeapMem___S1) - sizeof(ti_sysbios_heaps_HeapMem_Object2__),
    0,
    0,
    sizeof(ti_sysbios_heaps_HeapMem_Object2__),
    (xdc_CPtr)&ti_sysbios_heaps_HeapMem_Object__PARAMS__C,
    sizeof(ti_sysbios_heaps_HeapMem_Params),
}
Definition at line 4979 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_heaps_HeapMem_construct(), ti_sysbios_heaps_HeapMem_create(), ti_sysbios_heaps_HeapMem_destruct(), ti_sysbios_heaps_HeapMem_Object__create__S(), and ti_sysbios_heaps_HeapMem_Object__delete__S().
ti_sysbios_heaps_HeapMem_Object__heap__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__heap ti_sysbios_heaps_HeapMem_Object__heap__C = 0
Definition at line 5078 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Object__PARAMS__C
const __FAR__ ti_sysbios_heaps_HeapMem_Params ti_sysbios_heaps_HeapMem_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_heaps_HeapMem_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_heaps_HeapMem_Object__PARAMS__C.__iprms,
    (xdc_SizeT)0x0,
    ((xdc_Ptr)(0x0)),
    ((xdc_UArg)(0x0)),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4983 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_heaps_HeapMem_Params__init__S().
ti_sysbios_heaps_HeapMem_Object__sizeof__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__sizeof ti_sysbios_heaps_HeapMem_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapMem_Object__)
Definition at line 5082 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_Object__table__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_Object__table ti_sysbios_heaps_HeapMem_Object__table__C = ti_sysbios_heaps_HeapMem_Object__table__V
Definition at line 5086 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_heaps_HeapMem_Object__get__S().
ti_sysbios_heaps_HeapMem_Object__table__V
ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__table__V
Initial value:
= {
    {
        &ti_sysbios_heaps_HeapMem_Module__FXNS__C,
        ((xdc_UArg)(0x8)),
        ((void*)ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A),
        {
            ((ti_sysbios_heaps_HeapMem_Header*)0),
            ((xdc_UArg)(0x4000)),
        },
        (xdc_SizeT)0x8,
    },
}
Definition at line 1478 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr)0)
Definition at line 5110 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr)0)
Definition at line 5114 of file dss_mrr_pe674.c.
ti_sysbios_heaps_HeapMem_reqAlign__C
const __FAR__ CT__ti_sysbios_heaps_HeapMem_reqAlign ti_sysbios_heaps_HeapMem_reqAlign__C = (xdc_SizeT)0x8
Definition at line 5118 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_A_badThreadType__C
const __FAR__ CT__ti_sysbios_knl_Clock_A_badThreadType ti_sysbios_knl_Clock_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5271 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_A_clockDisabled__C
const __FAR__ CT__ti_sysbios_knl_Clock_A_clockDisabled ti_sysbios_knl_Clock_A_clockDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5267 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_doTickFunc__C
const __FAR__ CT__ti_sysbios_knl_Clock_doTickFunc ti_sysbios_knl_Clock_doTickFunc__C = ((CT__ti_sysbios_knl_Clock_doTickFunc)((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I))
Definition at line 5295 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_LM_begin__C
const __FAR__ CT__ti_sysbios_knl_Clock_LM_begin ti_sysbios_knl_Clock_LM_begin__C = (((xdc_runtime_Log_Event)16) << 16 | 768)
Definition at line 5263 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_LM_tick__C
const __FAR__ CT__ti_sysbios_knl_Clock_LM_tick ti_sysbios_knl_Clock_LM_tick__C = (((xdc_runtime_Log_Event)15) << 16 | 768)
Definition at line 5259 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_LW_delayed__C
const __FAR__ CT__ti_sysbios_knl_Clock_LW_delayed ti_sysbios_knl_Clock_LW_delayed__C = (((xdc_runtime_Log_Event)14) << 16 | 1024)
Definition at line 5255 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsEnabled ti_sysbios_knl_Clock_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5187 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsIncluded ti_sysbios_knl_Clock_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5191 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__diagsMask ti_sysbios_knl_Clock_Module__diagsMask__C = ((CT__ti_sysbios_knl_Clock_Module__diagsMask)0)
Definition at line 5195 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gateObj ti_sysbios_knl_Clock_Module__gateObj__C = ((CT__ti_sysbios_knl_Clock_Module__gateObj)0)
Definition at line 5199 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__gatePrms ti_sysbios_knl_Clock_Module__gatePrms__C = ((CT__ti_sysbios_knl_Clock_Module__gatePrms)0)
Definition at line 5203 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__id ti_sysbios_knl_Clock_Module__id__C = (xdc_Bits16)0x1d
Definition at line 5207 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerDefined ti_sysbios_knl_Clock_Module__loggerDefined__C = 0
Definition at line 5211 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn0 ti_sysbios_knl_Clock_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn0)0)
Definition at line 5219 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn1 ti_sysbios_knl_Clock_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn1)0)
Definition at line 5223 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn2 ti_sysbios_knl_Clock_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn2)0)
Definition at line 5227 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn4 ti_sysbios_knl_Clock_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn4)0)
Definition at line 5231 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerFxn8 ti_sysbios_knl_Clock_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn8)0)
Definition at line 5235 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Clock_Module__loggerObj ti_sysbios_knl_Clock_Module__loggerObj__C = ((CT__ti_sysbios_knl_Clock_Module__loggerObj)0)
Definition at line 5215 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Module__root__V
ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Clock_Module__root__V.link,
    &ti_sysbios_knl_Clock_Module__root__V.link},
}
Definition at line 5150 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Clock_Object__first__S(), and ti_sysbios_knl_Clock_Object__next__S().
ti_sysbios_knl_Clock_Module__state__V
ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module__state__V
Initial value:
= {
    (xdc_UInt32)0x0,
    (xdc_UInt)0x0,
    (ti_sysbios_knl_Clock_TimerProxy_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0],
    0,
    (xdc_UInt)0x1,
    (xdc_UInt32)0x1,
    (xdc_UInt32)0x0,
    0,
    0,
    0,
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Module__state__V.Object_field_clockQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Module__state__V.Object_field_clockQ.elem)),
        },
    },
}
Definition at line 1506 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Clock_doTick__I().
ti_sysbios_knl_Clock_Module_State_clockQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Clock_Module_State_clockQ__O = offsetof(ti_sysbios_knl_Clock_Module_State__,Object_field_clockQ)
Definition at line 1943 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__count ti_sysbios_knl_Clock_Object__count__C = 0
Definition at line 5239 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Clock_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Clock_Module__root__V.link,
    sizeof(ti_sysbios_knl_Clock___S1) - sizeof(ti_sysbios_knl_Clock_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Clock_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Clock_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Clock_Params),
}
Definition at line 5131 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Clock_construct(), ti_sysbios_knl_Clock_create(), ti_sysbios_knl_Clock_destruct(), ti_sysbios_knl_Clock_Object__create__S(), and ti_sysbios_knl_Clock_Object__delete__S().
ti_sysbios_knl_Clock_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__heap ti_sysbios_knl_Clock_Object__heap__C = 0
Definition at line 5243 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Clock_Params ti_sysbios_knl_Clock_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Clock_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Clock_Object__PARAMS__C.__iprms,
    0,
    (xdc_UInt32)0x0,
    ((xdc_UArg)0),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5135 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Clock_Params__init__S().
ti_sysbios_knl_Clock_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__sizeof ti_sysbios_knl_Clock_Object__sizeof__C = sizeof(ti_sysbios_knl_Clock_Object__)
Definition at line 5247 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Clock_Object__table ti_sysbios_knl_Clock_Object__table__C = 0
Definition at line 5251 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_serviceMargin__C
const __FAR__ CT__ti_sysbios_knl_Clock_serviceMargin ti_sysbios_knl_Clock_serviceMargin__C = (xdc_UInt32)0x0
Definition at line 5275 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_tickMode__C
const __FAR__ CT__ti_sysbios_knl_Clock_tickMode ti_sysbios_knl_Clock_tickMode__C = ti_sysbios_knl_Clock_TickMode_PERIODIC
Definition at line 5283 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_tickPeriod__C
const __FAR__ CT__ti_sysbios_knl_Clock_tickPeriod ti_sysbios_knl_Clock_tickPeriod__C = (xdc_UInt32)0x3e8
Definition at line 5291 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_tickSource__C
const __FAR__ CT__ti_sysbios_knl_Clock_tickSource ti_sysbios_knl_Clock_tickSource__C = ti_sysbios_knl_Clock_TickSource_TIMER
Definition at line 5279 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_timerId__C
const __FAR__ CT__ti_sysbios_knl_Clock_timerId ti_sysbios_knl_Clock_timerId__C = (xdc_UInt)(-0x0 - 1)
Definition at line 5287 of file dss_mrr_pe674.c.
ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Clock_triggerClock__C
const __FAR__ CT__ti_sysbios_knl_Clock_triggerClock ti_sysbios_knl_Clock_triggerClock__C = 0
Definition at line 5299 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_A_badContext__C
const __FAR__ CT__ti_sysbios_knl_Event_A_badContext ti_sysbios_knl_Event_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5423 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_A_eventInUse__C
const __FAR__ CT__ti_sysbios_knl_Event_A_eventInUse ti_sysbios_knl_Event_A_eventInUse__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5419 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_A_nullEventId__C
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventId ti_sysbios_knl_Event_A_nullEventId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5415 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_A_nullEventMasks__C
const __FAR__ CT__ti_sysbios_knl_Event_A_nullEventMasks ti_sysbios_knl_Event_A_nullEventMasks__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5411 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_A_pendTaskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Event_A_pendTaskDisabled ti_sysbios_knl_Event_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5427 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Instance_State_pendQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Event_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Event_Object__,Object_field_pendQ)
Definition at line 1951 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_LM_pend__C
const __FAR__ CT__ti_sysbios_knl_Event_LM_pend ti_sysbios_knl_Event_LM_pend__C = (((xdc_runtime_Log_Event)18) << 16 | 768)
Definition at line 5407 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_LM_post__C
const __FAR__ CT__ti_sysbios_knl_Event_LM_post ti_sysbios_knl_Event_LM_post__C = (((xdc_runtime_Log_Event)17) << 16 | 768)
Definition at line 5403 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsEnabled ti_sysbios_knl_Event_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5335 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsIncluded ti_sysbios_knl_Event_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5339 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__diagsMask ti_sysbios_knl_Event_Module__diagsMask__C = ((CT__ti_sysbios_knl_Event_Module__diagsMask)0)
Definition at line 5343 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__gateObj ti_sysbios_knl_Event_Module__gateObj__C = ((CT__ti_sysbios_knl_Event_Module__gateObj)0)
Definition at line 5347 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__gatePrms ti_sysbios_knl_Event_Module__gatePrms__C = ((CT__ti_sysbios_knl_Event_Module__gatePrms)0)
Definition at line 5351 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__id ti_sysbios_knl_Event_Module__id__C = (xdc_Bits16)0x20
Definition at line 5355 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerDefined ti_sysbios_knl_Event_Module__loggerDefined__C = 0
Definition at line 5359 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn0 ti_sysbios_knl_Event_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn0)0)
Definition at line 5367 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn1 ti_sysbios_knl_Event_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn1)0)
Definition at line 5371 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn2 ti_sysbios_knl_Event_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn2)0)
Definition at line 5375 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn4 ti_sysbios_knl_Event_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn4)0)
Definition at line 5379 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerFxn8 ti_sysbios_knl_Event_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn8)0)
Definition at line 5383 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Event_Module__loggerObj ti_sysbios_knl_Event_Module__loggerObj__C = ((CT__ti_sysbios_knl_Event_Module__loggerObj)0)
Definition at line 5363 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Module__root__V
ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Event_Module__root__V.link,
    &ti_sysbios_knl_Event_Module__root__V.link},
}
Definition at line 5328 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Event_Object__first__S(), and ti_sysbios_knl_Event_Object__next__S().
ti_sysbios_knl_Event_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__count ti_sysbios_knl_Event_Object__count__C = 0
Definition at line 5387 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Event_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Event_Module__root__V.link,
    sizeof(ti_sysbios_knl_Event___S1) - sizeof(ti_sysbios_knl_Event_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Event_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Event_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Event_Params),
}
Definition at line 5312 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Event_construct(), ti_sysbios_knl_Event_create(), ti_sysbios_knl_Event_destruct(), ti_sysbios_knl_Event_Object__create__S(), and ti_sysbios_knl_Event_Object__delete__S().
ti_sysbios_knl_Event_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__heap ti_sysbios_knl_Event_Object__heap__C = 0
Definition at line 5391 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Event_Params ti_sysbios_knl_Event_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Event_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Event_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5316 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Event_Params__init__S().
ti_sysbios_knl_Event_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__sizeof ti_sysbios_knl_Event_Object__sizeof__C = sizeof(ti_sysbios_knl_Event_Object__)
Definition at line 5395 of file dss_mrr_pe674.c.
ti_sysbios_knl_Event_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Event_Object__table ti_sysbios_knl_Event_Object__table__C = 0
Definition at line 5399 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_coreList__A
const __T1_ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__A
Initial value:
= {
    (xdc_UInt)0x0,
    (xdc_UInt)0x0,
    (xdc_UInt)0x0,
}
Definition at line 1536 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_coreList__C
const __FAR__ CT__ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__C = {3, ((__T1_ti_sysbios_knl_Idle_coreList *)ti_sysbios_knl_Idle_coreList__A)}
Definition at line 5524 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_funcList__A
const __T1_ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)DSP_sleep)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_utils_Load_idleFxn__E)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_hal_Hwi_checkStack)),
}
Definition at line 1533 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_funcList__C
const __FAR__ CT__ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__C = {3, ((__T1_ti_sysbios_knl_Idle_funcList *)ti_sysbios_knl_Idle_funcList__A)}
Definition at line 5520 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsEnabled ti_sysbios_knl_Idle_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5452 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsIncluded ti_sysbios_knl_Idle_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5456 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__diagsMask ti_sysbios_knl_Idle_Module__diagsMask__C = ((CT__ti_sysbios_knl_Idle_Module__diagsMask)0)
Definition at line 5460 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gateObj ti_sysbios_knl_Idle_Module__gateObj__C = ((CT__ti_sysbios_knl_Idle_Module__gateObj)0)
Definition at line 5464 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__gatePrms ti_sysbios_knl_Idle_Module__gatePrms__C = ((CT__ti_sysbios_knl_Idle_Module__gatePrms)0)
Definition at line 5468 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__id ti_sysbios_knl_Idle_Module__id__C = (xdc_Bits16)0x1e
Definition at line 5472 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerDefined ti_sysbios_knl_Idle_Module__loggerDefined__C = 0
Definition at line 5476 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn0 ti_sysbios_knl_Idle_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn0)0)
Definition at line 5484 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn1 ti_sysbios_knl_Idle_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn1)0)
Definition at line 5488 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn2 ti_sysbios_knl_Idle_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn2)0)
Definition at line 5492 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn4 ti_sysbios_knl_Idle_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn4)0)
Definition at line 5496 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerFxn8 ti_sysbios_knl_Idle_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn8)0)
Definition at line 5500 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Idle_Module__loggerObj ti_sysbios_knl_Idle_Module__loggerObj__C = ((CT__ti_sysbios_knl_Idle_Module__loggerObj)0)
Definition at line 5480 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__count ti_sysbios_knl_Idle_Object__count__C = 0
Definition at line 5504 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__heap ti_sysbios_knl_Idle_Object__heap__C = 0
Definition at line 5508 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__sizeof ti_sysbios_knl_Idle_Object__sizeof__C = 0
Definition at line 5512 of file dss_mrr_pe674.c.
ti_sysbios_knl_Idle_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Idle_Object__table ti_sysbios_knl_Idle_Object__table__C = 0
Definition at line 5516 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsEnabled ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5533 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsIncluded ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5537 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__diagsMask ti_sysbios_knl_Intrinsics_Module__diagsMask__C = ((CT__ti_sysbios_knl_Intrinsics_Module__diagsMask)0)
Definition at line 5541 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gateObj ti_sysbios_knl_Intrinsics_Module__gateObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gateObj)0)
Definition at line 5545 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__gatePrms ti_sysbios_knl_Intrinsics_Module__gatePrms__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gatePrms)0)
Definition at line 5549 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__id ti_sysbios_knl_Intrinsics_Module__id__C = (xdc_Bits16)0x1f
Definition at line 5553 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerDefined ti_sysbios_knl_Intrinsics_Module__loggerDefined__C = 0
Definition at line 5557 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0 ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0)0)
Definition at line 5565 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1 ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1)0)
Definition at line 5569 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2 ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2)0)
Definition at line 5573 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4 ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4)0)
Definition at line 5577 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8 ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8)0)
Definition at line 5581 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Module__loggerObj ti_sysbios_knl_Intrinsics_Module__loggerObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerObj)0)
Definition at line 5561 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__count ti_sysbios_knl_Intrinsics_Object__count__C = 0
Definition at line 5585 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__heap ti_sysbios_knl_Intrinsics_Object__heap__C = 0
Definition at line 5589 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__sizeof ti_sysbios_knl_Intrinsics_Object__sizeof__C = 0
Definition at line 5593 of file dss_mrr_pe674.c.
ti_sysbios_knl_Intrinsics_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Intrinsics_Object__table ti_sysbios_knl_Intrinsics_Object__table__C = 0
Definition at line 5597 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsEnabled ti_sysbios_knl_Queue_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5633 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsIncluded ti_sysbios_knl_Queue_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5637 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__diagsMask ti_sysbios_knl_Queue_Module__diagsMask__C = ((CT__ti_sysbios_knl_Queue_Module__diagsMask)0)
Definition at line 5641 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gateObj ti_sysbios_knl_Queue_Module__gateObj__C = ((CT__ti_sysbios_knl_Queue_Module__gateObj)0)
Definition at line 5645 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__gatePrms ti_sysbios_knl_Queue_Module__gatePrms__C = ((CT__ti_sysbios_knl_Queue_Module__gatePrms)0)
Definition at line 5649 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__id ti_sysbios_knl_Queue_Module__id__C = (xdc_Bits16)0x21
Definition at line 5653 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerDefined ti_sysbios_knl_Queue_Module__loggerDefined__C = 0
Definition at line 5657 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn0 ti_sysbios_knl_Queue_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn0)0)
Definition at line 5665 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn1 ti_sysbios_knl_Queue_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn1)0)
Definition at line 5669 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn2 ti_sysbios_knl_Queue_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn2)0)
Definition at line 5673 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn4 ti_sysbios_knl_Queue_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn4)0)
Definition at line 5677 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerFxn8 ti_sysbios_knl_Queue_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn8)0)
Definition at line 5681 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Queue_Module__loggerObj ti_sysbios_knl_Queue_Module__loggerObj__C = ((CT__ti_sysbios_knl_Queue_Module__loggerObj)0)
Definition at line 5661 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Module__root__V
ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Queue_Module__root__V.link,
    &ti_sysbios_knl_Queue_Module__root__V.link},
}
Definition at line 5626 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Queue_Object__first__S(), and ti_sysbios_knl_Queue_Object__next__S().
ti_sysbios_knl_Queue_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__count ti_sysbios_knl_Queue_Object__count__C = 0
Definition at line 5685 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Queue_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Queue_Module__root__V.link,
    sizeof(ti_sysbios_knl_Queue___S1) - sizeof(ti_sysbios_knl_Queue_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Queue_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Queue_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Queue_Params),
}
Definition at line 5610 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Queue_construct(), ti_sysbios_knl_Queue_create(), ti_sysbios_knl_Queue_destruct(), ti_sysbios_knl_Queue_Object__create__S(), and ti_sysbios_knl_Queue_Object__delete__S().
ti_sysbios_knl_Queue_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__heap ti_sysbios_knl_Queue_Object__heap__C = 0
Definition at line 5689 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Queue_Params ti_sysbios_knl_Queue_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Queue_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Queue_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5614 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Queue_Params__init__S().
ti_sysbios_knl_Queue_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__sizeof ti_sysbios_knl_Queue_Object__sizeof__C = sizeof(ti_sysbios_knl_Queue_Object__)
Definition at line 5693 of file dss_mrr_pe674.c.
ti_sysbios_knl_Queue_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Queue_Object__table ti_sysbios_knl_Queue_Object__table__C = 0
Definition at line 5697 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_A_badContext__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_badContext ti_sysbios_knl_Semaphore_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5815 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_A_invTimeout__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_invTimeout ti_sysbios_knl_Semaphore_A_invTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5811 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_A_noEvents__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_noEvents ti_sysbios_knl_Semaphore_A_noEvents__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5807 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_A_overflow__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_overflow ti_sysbios_knl_Semaphore_A_overflow__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5819 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_A_pendTaskDisabled ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5823 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)19) << 16 | 0)
Definition at line 5827 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_eventPost__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventPost ti_sysbios_knl_Semaphore_eventPost__C = ((CT__ti_sysbios_knl_Semaphore_eventPost)0)
Definition at line 5839 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_eventSync__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_eventSync ti_sysbios_knl_Semaphore_eventSync__C = ((CT__ti_sysbios_knl_Semaphore_eventSync)0)
Definition at line 5843 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Instance_State_pendQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Semaphore_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Semaphore_Object__,Object_field_pendQ)
Definition at line 1959 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_LM_pend__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_pend ti_sysbios_knl_Semaphore_LM_pend__C = (((xdc_runtime_Log_Event)20) << 16 | 768)
Definition at line 5803 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_LM_post__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_LM_post ti_sysbios_knl_Semaphore_LM_post__C = (((xdc_runtime_Log_Event)19) << 16 | 768)
Definition at line 5799 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsEnabled ti_sysbios_knl_Semaphore_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5731 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsIncluded ti_sysbios_knl_Semaphore_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5735 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__diagsMask ti_sysbios_knl_Semaphore_Module__diagsMask__C = ((CT__ti_sysbios_knl_Semaphore_Module__diagsMask)0)
Definition at line 5739 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gateObj ti_sysbios_knl_Semaphore_Module__gateObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__gateObj)0)
Definition at line 5743 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__gatePrms ti_sysbios_knl_Semaphore_Module__gatePrms__C = ((CT__ti_sysbios_knl_Semaphore_Module__gatePrms)0)
Definition at line 5747 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__id ti_sysbios_knl_Semaphore_Module__id__C = (xdc_Bits16)0x22
Definition at line 5751 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerDefined ti_sysbios_knl_Semaphore_Module__loggerDefined__C = 0
Definition at line 5755 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0)0)
Definition at line 5763 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1)0)
Definition at line 5767 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2)0)
Definition at line 5771 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4)0)
Definition at line 5775 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8)0)
Definition at line 5779 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Module__loggerObj ti_sysbios_knl_Semaphore_Module__loggerObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerObj)0)
Definition at line 5759 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Module__root__V
ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Semaphore_Module__root__V.link,
    &ti_sysbios_knl_Semaphore_Module__root__V.link},
}
Definition at line 5724 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Semaphore_Object__first__S(), and ti_sysbios_knl_Semaphore_Object__next__S().
ti_sysbios_knl_Semaphore_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__count ti_sysbios_knl_Semaphore_Object__count__C = 0
Definition at line 5783 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Semaphore_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Semaphore_Module__root__V.link,
    sizeof(ti_sysbios_knl_Semaphore___S1) - sizeof(ti_sysbios_knl_Semaphore_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Semaphore_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Semaphore_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Semaphore_Params),
}
Definition at line 5705 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Semaphore_construct(), ti_sysbios_knl_Semaphore_create(), ti_sysbios_knl_Semaphore_destruct(), ti_sysbios_knl_Semaphore_Object__create__S(), and ti_sysbios_knl_Semaphore_Object__delete__S().
ti_sysbios_knl_Semaphore_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__heap ti_sysbios_knl_Semaphore_Object__heap__C = 0
Definition at line 5787 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Semaphore_Params ti_sysbios_knl_Semaphore_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Semaphore_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Semaphore_Object__PARAMS__C.__iprms,
    0,
    (xdc_UInt)0x1,
    ti_sysbios_knl_Semaphore_Mode_COUNTING,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5709 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Semaphore_Params__init__S().
ti_sysbios_knl_Semaphore_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__sizeof ti_sysbios_knl_Semaphore_Object__sizeof__C = sizeof(ti_sysbios_knl_Semaphore_Object__)
Definition at line 5791 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_Object__table ti_sysbios_knl_Semaphore_Object__table__C = 0
Definition at line 5795 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_supportsEvents__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsEvents ti_sysbios_knl_Semaphore_supportsEvents__C = 0
Definition at line 5831 of file dss_mrr_pe674.c.
ti_sysbios_knl_Semaphore_supportsPriority__C
const __FAR__ CT__ti_sysbios_knl_Semaphore_supportsPriority ti_sysbios_knl_Semaphore_supportsPriority__C = 1
Definition at line 5835 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_badAffinity__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badAffinity ti_sysbios_knl_Task_A_badAffinity__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6236 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_badPriority__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badPriority ti_sysbios_knl_Task_A_badPriority__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6228 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_badTaskState__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badTaskState ti_sysbios_knl_Task_A_badTaskState__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6216 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_badThreadType__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badThreadType ti_sysbios_knl_Task_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6212 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_badTimeout__C
const __FAR__ CT__ti_sysbios_knl_Task_A_badTimeout ti_sysbios_knl_Task_A_badTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6232 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_invalidCoreId__C
const __FAR__ CT__ti_sysbios_knl_Task_A_invalidCoreId ti_sysbios_knl_Task_A_invalidCoreId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6244 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_noPendElem__C
const __FAR__ CT__ti_sysbios_knl_Task_A_noPendElem ti_sysbios_knl_Task_A_noPendElem__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6220 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_sleepTaskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Task_A_sleepTaskDisabled ti_sysbios_knl_Task_A_sleepTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6240 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_A_taskDisabled__C
const __FAR__ CT__ti_sysbios_knl_Task_A_taskDisabled ti_sysbios_knl_Task_A_taskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6224 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_allBlockedFunc__C
const __FAR__ CT__ti_sysbios_knl_Task_allBlockedFunc ti_sysbios_knl_Task_allBlockedFunc__C = ((CT__ti_sysbios_knl_Task_allBlockedFunc)0)
Definition at line 6260 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_checkStackFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_checkStackFlag ti_sysbios_knl_Task_checkStackFlag__C = 1
Definition at line 6268 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_defaultStackHeap__C
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackHeap ti_sysbios_knl_Task_defaultStackHeap__C = 0
Definition at line 6256 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_defaultStackSize__C
const __FAR__ CT__ti_sysbios_knl_Task_defaultStackSize ti_sysbios_knl_Task_defaultStackSize__C = (xdc_SizeT)0x5dc
Definition at line 6252 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_deleteTerminatedTasks__C
const __FAR__ CT__ti_sysbios_knl_Task_deleteTerminatedTasks ti_sysbios_knl_Task_deleteTerminatedTasks__C = 0
Definition at line 6272 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_E_deleteNotAllowed__C
const __FAR__ CT__ti_sysbios_knl_Task_E_deleteNotAllowed ti_sysbios_knl_Task_E_deleteNotAllowed__C = (((xdc_runtime_Error_Id)22) << 16 | 0)
Definition at line 6196 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_E_moduleStateCheckFailed__C
const __FAR__ CT__ti_sysbios_knl_Task_E_moduleStateCheckFailed ti_sysbios_knl_Task_E_moduleStateCheckFailed__C = (((xdc_runtime_Error_Id)23) << 16 | 0)
Definition at line 6200 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_E_objectCheckFailed__C
const __FAR__ CT__ti_sysbios_knl_Task_E_objectCheckFailed ti_sysbios_knl_Task_E_objectCheckFailed__C = (((xdc_runtime_Error_Id)24) << 16 | 0)
Definition at line 6204 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_E_objectNotInKernelSpace__C
const __FAR__ CT__ti_sysbios_knl_Task_E_objectNotInKernelSpace ti_sysbios_knl_Task_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)25) << 16 | 0)
Definition at line 6208 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_E_spOutOfBounds__C
const __FAR__ CT__ti_sysbios_knl_Task_E_spOutOfBounds ti_sysbios_knl_Task_E_spOutOfBounds__C = (((xdc_runtime_Error_Id)21) << 16 | 0)
Definition at line 6192 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_E_stackOverflow__C
const __FAR__ CT__ti_sysbios_knl_Task_E_stackOverflow ti_sysbios_knl_Task_E_stackOverflow__C = (((xdc_runtime_Error_Id)20) << 16 | 0)
Definition at line 6188 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_hooks__A
const __T1_ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__A
Initial value:
= {
    {
        ((xdc_Void(*)(xdc_Int))((xdc_Fxn)ti_sysbios_utils_Load_taskRegHook__E)),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle,xdc_runtime_Error_Block*))((xdc_Fxn)ti_sysbios_utils_Load_taskCreateHook__E)),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle))0),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle,ti_sysbios_knl_Task_Handle))((xdc_Fxn)ti_sysbios_utils_Load_taskSwitchHook__E)),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle))0),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle))((xdc_Fxn)ti_sysbios_utils_Load_taskDeleteHook__E)),
    },
}
Definition at line 1624 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_hooks__C
const __FAR__ CT__ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__C = {1, ((__T1_ti_sysbios_knl_Task_hooks *)ti_sysbios_knl_Task_hooks__A)}
Definition at line 6276 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_initStackFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_initStackFlag ti_sysbios_knl_Task_initStackFlag__C = 1
Definition at line 6264 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Instance_State_0_hookEnv__A
__T1_ti_sysbios_knl_Task_Instance_State__hookEnv ti_sysbios_knl_Task_Instance_State_0_hookEnv__A
Definition at line 1586 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Instance_State_0_stack__A
__T1_ti_sysbios_knl_Task_Instance_State__stack ti_sysbios_knl_Task_Instance_State_0_stack__A
Definition at line 1567 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LD_block__C
const __FAR__ CT__ti_sysbios_knl_Task_LD_block ti_sysbios_knl_Task_LD_block__C = (((xdc_runtime_Log_Event)24) << 16 | 512)
Definition at line 6160 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LD_exit__C
const __FAR__ CT__ti_sysbios_knl_Task_LD_exit ti_sysbios_knl_Task_LD_exit__C = (((xdc_runtime_Log_Event)27) << 16 | 512)
Definition at line 6172 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LD_ready__C
const __FAR__ CT__ti_sysbios_knl_Task_LD_ready ti_sysbios_knl_Task_LD_ready__C = (((xdc_runtime_Log_Event)23) << 16 | 512)
Definition at line 6156 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_noWork__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_noWork ti_sysbios_knl_Task_LM_noWork__C = (((xdc_runtime_Log_Event)30) << 16 | 1024)
Definition at line 6184 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_schedule__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_schedule ti_sysbios_knl_Task_LM_schedule__C = (((xdc_runtime_Log_Event)29) << 16 | 1024)
Definition at line 6180 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_setAffinity__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_setAffinity ti_sysbios_knl_Task_LM_setAffinity__C = (((xdc_runtime_Log_Event)28) << 16 | 768)
Definition at line 6176 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_setPri__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_setPri ti_sysbios_knl_Task_LM_setPri__C = (((xdc_runtime_Log_Event)26) << 16 | 768)
Definition at line 6168 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_sleep__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_sleep ti_sysbios_knl_Task_LM_sleep__C = (((xdc_runtime_Log_Event)22) << 16 | 768)
Definition at line 6152 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_switch__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_switch ti_sysbios_knl_Task_LM_switch__C = (((xdc_runtime_Log_Event)21) << 16 | 768)
Definition at line 6148 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_LM_yield__C
const __FAR__ CT__ti_sysbios_knl_Task_LM_yield ti_sysbios_knl_Task_LM_yield__C = (((xdc_runtime_Log_Event)25) << 16 | 768)
Definition at line 6164 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsEnabled ti_sysbios_knl_Task_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6080 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsIncluded ti_sysbios_knl_Task_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6084 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__diagsMask ti_sysbios_knl_Task_Module__diagsMask__C = ((CT__ti_sysbios_knl_Task_Module__diagsMask)0)
Definition at line 6088 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__gateObj__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__gateObj ti_sysbios_knl_Task_Module__gateObj__C = ((CT__ti_sysbios_knl_Task_Module__gateObj)0)
Definition at line 6092 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__gatePrms ti_sysbios_knl_Task_Module__gatePrms__C = ((CT__ti_sysbios_knl_Task_Module__gatePrms)0)
Definition at line 6096 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__id__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__id ti_sysbios_knl_Task_Module__id__C = (xdc_Bits16)0x23
Definition at line 6100 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerDefined ti_sysbios_knl_Task_Module__loggerDefined__C = 0
Definition at line 6104 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn0 ti_sysbios_knl_Task_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn0)0)
Definition at line 6112 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn1 ti_sysbios_knl_Task_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn1)0)
Definition at line 6116 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn2 ti_sysbios_knl_Task_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn2)0)
Definition at line 6120 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn4 ti_sysbios_knl_Task_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn4)0)
Definition at line 6124 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerFxn8 ti_sysbios_knl_Task_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn8)0)
Definition at line 6128 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_knl_Task_Module__loggerObj ti_sysbios_knl_Task_Module__loggerObj__C = ((CT__ti_sysbios_knl_Task_Module__loggerObj)0)
Definition at line 6108 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module__root__V
ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Task_Module__root__V.link,
    &ti_sysbios_knl_Task_Module__root__V.link},
}
Definition at line 5884 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Task_Object__first__S(), and ti_sysbios_knl_Task_Object__next__S().
ti_sysbios_knl_Task_Module__state__V
ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module__state__V
Initial value:
= {
    1,
    (xdc_UInt)0x0,
    0,
    (xdc_UInt)0x1,
    0,
    0,
    ((void*)ti_sysbios_knl_Task_Module_State_0_readyQ__A),
    ((void*)0),
    ((void*)0),
    ((void*)0),
    ((void*)0),
    ((void*)ti_sysbios_knl_Task_Module_State_0_idleTask__A),
    ((void*)0),
    1,
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_inactiveQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_inactiveQ.elem)),
        },
    },
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_terminatedQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_terminatedQ.elem)),
        },
    },
}
Definition at line 1618 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module_State_0_idleTask__A
__T1_ti_sysbios_knl_Task_Module_State__idleTask ti_sysbios_knl_Task_Module_State_0_idleTask__A
Initial value:
= {
    (ti_sysbios_knl_Task_Handle)&ti_sysbios_knl_Task_Object__table__V[0],
}
Definition at line 1615 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module_State_0_readyQ__A
__T1_ti_sysbios_knl_Task_Module_State__readyQ ti_sysbios_knl_Task_Module_State_0_readyQ__A
Definition at line 1612 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module_State_inactiveQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_inactiveQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_inactiveQ)
Definition at line 1967 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Module_State_terminatedQ__O
const __FAR__ xdc_SizeT ti_sysbios_knl_Task_Module_State_terminatedQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_terminatedQ)
Definition at line 1969 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_moduleStateCheckFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFlag ti_sysbios_knl_Task_moduleStateCheckFlag__C = 0
Definition at line 6288 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_moduleStateCheckFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckFxn ti_sysbios_knl_Task_moduleStateCheckFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_moduleStateCheck__I))
Definition at line 6280 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_moduleStateCheckValueFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn ti_sysbios_knl_Task_moduleStateCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getModuleStateCheckValue__I))
Definition at line 6284 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_numConstructedTasks__C
const __FAR__ CT__ti_sysbios_knl_Task_numConstructedTasks ti_sysbios_knl_Task_numConstructedTasks__C = (xdc_UInt)0x0
Definition at line 6304 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_numPriorities__C
const __FAR__ CT__ti_sysbios_knl_Task_numPriorities ti_sysbios_knl_Task_numPriorities__C = (xdc_UInt)0x10
Definition at line 6248 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Object__count__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__count ti_sysbios_knl_Task_Object__count__C = 1
Definition at line 6132 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_knl_Task_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Task_Module__root__V.link,
    sizeof(ti_sysbios_knl_Task___S1) - sizeof(ti_sysbios_knl_Task_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Task_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Task_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Task_Params),
}
Definition at line 5851 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Task_construct(), ti_sysbios_knl_Task_create(), ti_sysbios_knl_Task_destruct(), ti_sysbios_knl_Task_Object__create__S(), and ti_sysbios_knl_Task_Object__delete__S().
ti_sysbios_knl_Task_Object__heap__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__heap ti_sysbios_knl_Task_Object__heap__C = 0
Definition at line 6136 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Object__PARAMS__C
const __FAR__ ti_sysbios_knl_Task_Params ti_sysbios_knl_Task_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Task_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Task_Object__PARAMS__C.__iprms,
    ((xdc_UArg)(0x0)),
    ((xdc_UArg)(0x0)),
    (xdc_Int)0x1,
    ((xdc_Ptr)0),
    (xdc_SizeT)0x0,
    0,
    ((xdc_Ptr)0),
    1,
    (xdc_UInt)0x0,
    1,
    ((xdc_Ptr)0),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5855 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Task_Params__init__S().
ti_sysbios_knl_Task_Object__sizeof__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__sizeof ti_sysbios_knl_Task_Object__sizeof__C = sizeof(ti_sysbios_knl_Task_Object__)
Definition at line 6140 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_Object__table__C
const __FAR__ CT__ti_sysbios_knl_Task_Object__table ti_sysbios_knl_Task_Object__table__C = ti_sysbios_knl_Task_Object__table__V
Definition at line 6144 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_knl_Task_Object__get__S().
ti_sysbios_knl_Task_Object__table__V
ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__table__V
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Object__table__V[0].qElem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Object__table__V[0].qElem)),
        },
        (xdc_Int)0x0,
        (xdc_UInt)0x1,
        ((xdc_Ptr)0),
        ti_sysbios_knl_Task_Mode_INACTIVE,
        ((ti_sysbios_knl_Task_PendElem*)0),
        (xdc_SizeT)0x320,
        ((void*)ti_sysbios_knl_Task_Instance_State_0_stack__A),
        0,
        ((xdc_Void(*)(xdc_UArg,xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Idle_loop__E)),
        ((xdc_UArg)(0x0)),
        ((xdc_UArg)(0x0)),
        ((xdc_Ptr)0),
        ((void*)ti_sysbios_knl_Task_Instance_State_0_hookEnv__A),
        1,
        0,
        (xdc_UInt)0x0,
        (xdc_UInt)0x0,
        1,
        ((xdc_Ptr)0),
        (xdc_UInt32)0x0,
        ((xdc_Ptr)0),
    },
}
Definition at line 1589 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_objectCheckFlag__C
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFlag ti_sysbios_knl_Task_objectCheckFlag__C = 0
Definition at line 6300 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_objectCheckFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckFxn ti_sysbios_knl_Task_objectCheckFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_objectCheck__I))
Definition at line 6292 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_objectCheckValueFxn__C
const __FAR__ CT__ti_sysbios_knl_Task_objectCheckValueFxn ti_sysbios_knl_Task_objectCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getObjectCheckValue__I))
Definition at line 6296 of file dss_mrr_pe674.c.
ti_sysbios_knl_Task_startupHookFunc__C
const __FAR__ CT__ti_sysbios_knl_Task_startupHookFunc ti_sysbios_knl_Task_startupHookFunc__C = ((CT__ti_sysbios_knl_Task_startupHookFunc)0)
Definition at line 6308 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_enableTLSSupport__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_enableTLSSupport ti_sysbios_rts_ti_ThreadLocalStorage_enableTLSSupport__C = 0
Definition at line 6411 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_heapHandle__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_heapHandle ti_sysbios_rts_ti_ThreadLocalStorage_heapHandle__C = 0
Definition at line 6407 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsEnabled ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6339 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsIncluded ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6343 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__diagsMask)0)
Definition at line 6347 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gateObj)0)
Definition at line 6351 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__gatePrms)0)
Definition at line 6355 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__id__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__id ti_sysbios_rts_ti_ThreadLocalStorage_Module__id__C = (xdc_Bits16)0x2a
Definition at line 6359 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerDefined ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerDefined__C = 0
Definition at line 6363 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn0)0)
Definition at line 6371 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn1)0)
Definition at line 6375 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn2)0)
Definition at line 6379 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn4)0)
Definition at line 6383 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8 ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerFxn8)0)
Definition at line 6387 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj__C = ((CT__ti_sysbios_rts_ti_ThreadLocalStorage_Module__loggerObj)0)
Definition at line 6367 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Module__state__V
ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__ ti_sysbios_rts_ti_ThreadLocalStorage_Module__state__V
Initial value:
= {
    ((xdc_Ptr)((void*)"&__TI_TLS_MAIN_THREAD_Base")),
    (xdc_UInt)(-0x0 - 1),
    0,
}
Definition at line 1644 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Object__count__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__count ti_sysbios_rts_ti_ThreadLocalStorage_Object__count__C = 0
Definition at line 6391 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Object__heap__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__heap ti_sysbios_rts_ti_ThreadLocalStorage_Object__heap__C = 0
Definition at line 6395 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Object__sizeof__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__sizeof ti_sysbios_rts_ti_ThreadLocalStorage_Object__sizeof__C = 0
Definition at line 6399 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_Object__table__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_Object__table ti_sysbios_rts_ti_ThreadLocalStorage_Object__table__C = 0
Definition at line 6403 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_TItls_initSectMemory__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_TItls_initSectMemory ti_sysbios_rts_ti_ThreadLocalStorage_TItls_initSectMemory__C = 0
Definition at line 6419 of file dss_mrr_pe674.c.
ti_sysbios_rts_ti_ThreadLocalStorage_TItlsSectMemory__C
const __FAR__ CT__ti_sysbios_rts_ti_ThreadLocalStorage_TItlsSectMemory ti_sysbios_rts_ti_ThreadLocalStorage_TItlsSectMemory__C = 0
Definition at line 6415 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_A_invalidTimer__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_A_invalidTimer ti_sysbios_timers_rti_Timer_A_invalidTimer__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6603 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_anyMask__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_anyMask ti_sysbios_timers_rti_Timer_anyMask__C = (xdc_UInt)0x3
Definition at line 6623 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_continueOnSuspend__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_continueOnSuspend ti_sysbios_timers_rti_Timer_continueOnSuspend__C = 0
Definition at line 6627 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_E_cannotSupport__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_cannotSupport ti_sysbios_timers_rti_Timer_E_cannotSupport__C = (((xdc_runtime_Error_Id)34) << 16 | 0)
Definition at line 6619 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidHwiMask ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C = (((xdc_runtime_Error_Id)33) << 16 | 0)
Definition at line 6615 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_E_invalidTimer__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_invalidTimer ti_sysbios_timers_rti_Timer_E_invalidTimer__C = (((xdc_runtime_Error_Id)31) << 16 | 0)
Definition at line 6607 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_E_notAvailable__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_E_notAvailable ti_sysbios_timers_rti_Timer_E_notAvailable__C = (((xdc_runtime_Error_Id)32) << 16 | 0)
Definition at line 6611 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsEnabled ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6535 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsIncluded ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6539 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__diagsMask ti_sysbios_timers_rti_Timer_Module__diagsMask__C = ((CT__ti_sysbios_timers_rti_Timer_Module__diagsMask)0)
Definition at line 6543 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__gateObj__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gateObj ti_sysbios_timers_rti_Timer_Module__gateObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gateObj)0)
Definition at line 6547 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__gatePrms ti_sysbios_timers_rti_Timer_Module__gatePrms__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gatePrms)0)
Definition at line 6551 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__id__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__id ti_sysbios_timers_rti_Timer_Module__id__C = (xdc_Bits16)0x31
Definition at line 6555 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerDefined ti_sysbios_timers_rti_Timer_Module__loggerDefined__C = 0
Definition at line 6559 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0)0)
Definition at line 6567 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1)0)
Definition at line 6571 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2)0)
Definition at line 6575 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4)0)
Definition at line 6579 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8)0)
Definition at line 6583 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Module__loggerObj ti_sysbios_timers_rti_Timer_Module__loggerObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerObj)0)
Definition at line 6563 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module__root__V
ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__root__V
Initial value:
= {
    {&ti_sysbios_timers_rti_Timer_Module__root__V.link,
    &ti_sysbios_timers_rti_Timer_Module__root__V.link},
}
Definition at line 6455 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_timers_rti_Timer_Object__first__S(), and ti_sysbios_timers_rti_Timer_Object__next__S().
ti_sysbios_timers_rti_Timer_Module__state__V
ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module__state__V
Initial value:
= {
    (xdc_UInt)0x2,
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_device__A),
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A),
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_handles__A),
}
Definition at line 1672 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module_State_0_device__A
__T1_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State_0_device__A
Initial value:
= {
    {
        (xdc_Int)0xe,
        (xdc_Int)0x4b,
        ((xdc_Ptr)((void*)0x2020000)),
    },
    {
        (xdc_Int)0xf,
        (xdc_Int)0x4c,
        ((xdc_Ptr)((void*)0x2020000)),
    },
}
Definition at line 1663 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module_State_0_handles__A
__T1_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State_0_handles__A
Initial value:
= {
    (ti_sysbios_timers_rti_Timer_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0],
    0,
}
Definition at line 1669 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A
__T1_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A
Initial value:
= {
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
}
Definition at line 1666 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_numTimerDevices__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_numTimerDevices ti_sysbios_timers_rti_Timer_numTimerDevices__C = (xdc_Int)0x2
Definition at line 6635 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Object__count__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__count ti_sysbios_timers_rti_Timer_Object__count__C = 1
Definition at line 6587 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Object__DESC__C
const __FAR__ xdc_runtime_Core_ObjDesc ti_sysbios_timers_rti_Timer_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_timers_rti_Timer_Module__root__V.link,
    sizeof(ti_sysbios_timers_rti_Timer___S1) - sizeof(ti_sysbios_timers_rti_Timer_Object2__),
    0,
    0,
    sizeof(ti_sysbios_timers_rti_Timer_Object2__),
    (xdc_CPtr)&ti_sysbios_timers_rti_Timer_Object__PARAMS__C,
    sizeof(ti_sysbios_timers_rti_Timer_Params),
}
Definition at line 6427 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_timers_rti_Timer_construct(), ti_sysbios_timers_rti_Timer_create(), ti_sysbios_timers_rti_Timer_destruct(), ti_sysbios_timers_rti_Timer_Object__create__S(), and ti_sysbios_timers_rti_Timer_Object__delete__S().
ti_sysbios_timers_rti_Timer_Object__heap__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__heap ti_sysbios_timers_rti_Timer_Object__heap__C = 0
Definition at line 6591 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Object__PARAMS__C
const __FAR__ ti_sysbios_timers_rti_Timer_Params ti_sysbios_timers_rti_Timer_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_timers_rti_Timer_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_timers_rti_Timer_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_ITimer_RunMode_CONTINUOUS,
    ti_sysbios_interfaces_ITimer_StartMode_AUTO,
    ((xdc_UArg)0),
    (xdc_UInt32)0x0,
    ti_sysbios_interfaces_ITimer_PeriodType_MICROSECS,
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0x0,
    },
    1,
    ((ti_sysbios_hal_Hwi_Params*)0),
    (xdc_UInt8)0x1,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 6431 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_timers_rti_Timer_Params__init__S().
ti_sysbios_timers_rti_Timer_Object__sizeof__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__sizeof ti_sysbios_timers_rti_Timer_Object__sizeof__C = sizeof(ti_sysbios_timers_rti_Timer_Object__)
Definition at line 6595 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_Object__table__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_Object__table ti_sysbios_timers_rti_Timer_Object__table__C = ti_sysbios_timers_rti_Timer_Object__table__V
Definition at line 6599 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_timers_rti_Timer_Object__get__S().
ti_sysbios_timers_rti_Timer_Object__table__V
ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__table__V
Initial value:
= {
    {
        0,
        1,
        (xdc_Int)0x0,
        ti_sysbios_interfaces_ITimer_RunMode_CONTINUOUS,
        ti_sysbios_interfaces_ITimer_StartMode_AUTO,
        (xdc_UInt)0x1,
        (xdc_UInt)0x3e8,
        ti_sysbios_interfaces_ITimer_PeriodType_MICROSECS,
        (xdc_UInt)0xe,
        ((xdc_UArg)0),
        ((xdc_Void(*)(xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I)),
        {
            (xdc_Bits32)0x0,
            (xdc_Bits32)0x0,
        },
        (ti_sysbios_hal_Hwi_Handle)&ti_sysbios_hal_Hwi_Object__table__V[0],
        1,
    },
}
Definition at line 1652 of file dss_mrr_pe674.c.
ti_sysbios_timers_rti_Timer_startupNeeded__C
const __FAR__ CT__ti_sysbios_timers_rti_Timer_startupNeeded ti_sysbios_timers_rti_Timer_startupNeeded__C = (xdc_UInt)0x1
Definition at line 6631 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_autoAddTasks__C
const __FAR__ CT__ti_sysbios_utils_Load_autoAddTasks ti_sysbios_utils_Load_autoAddTasks__C = 1
Definition at line 6841 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_hwiEnabled__C
const __FAR__ CT__ti_sysbios_utils_Load_hwiEnabled ti_sysbios_utils_Load_hwiEnabled__C = 0
Definition at line 6829 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_LS_cpuLoad__C
const __FAR__ CT__ti_sysbios_utils_Load_LS_cpuLoad ti_sysbios_utils_Load_LS_cpuLoad__C = (((xdc_runtime_Log_Event)31) << 16 | 2048)
Definition at line 6801 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_LS_hwiLoad__C
const __FAR__ CT__ti_sysbios_utils_Load_LS_hwiLoad ti_sysbios_utils_Load_LS_hwiLoad__C = (((xdc_runtime_Log_Event)32) << 16 | 2048)
Definition at line 6805 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_LS_swiLoad__C
const __FAR__ CT__ti_sysbios_utils_Load_LS_swiLoad ti_sysbios_utils_Load_LS_swiLoad__C = (((xdc_runtime_Log_Event)33) << 16 | 2048)
Definition at line 6809 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_LS_taskLoad__C
const __FAR__ CT__ti_sysbios_utils_Load_LS_taskLoad ti_sysbios_utils_Load_LS_taskLoad__C = (((xdc_runtime_Log_Event)34) << 16 | 2048)
Definition at line 6813 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__diagsEnabled__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__diagsEnabled ti_sysbios_utils_Load_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6733 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__diagsIncluded__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__diagsIncluded ti_sysbios_utils_Load_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6737 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__diagsMask__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__diagsMask ti_sysbios_utils_Load_Module__diagsMask__C = ((CT__ti_sysbios_utils_Load_Module__diagsMask)0)
Definition at line 6741 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__gateObj__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__gateObj ti_sysbios_utils_Load_Module__gateObj__C = ((CT__ti_sysbios_utils_Load_Module__gateObj)0)
Definition at line 6745 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__gatePrms__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__gatePrms ti_sysbios_utils_Load_Module__gatePrms__C = ((CT__ti_sysbios_utils_Load_Module__gatePrms)0)
Definition at line 6749 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__id__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__id ti_sysbios_utils_Load_Module__id__C = (xdc_Bits16)0x29
Definition at line 6753 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerDefined__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerDefined ti_sysbios_utils_Load_Module__loggerDefined__C = 0
Definition at line 6757 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerFxn0__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn0 ti_sysbios_utils_Load_Module__loggerFxn0__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn0)0)
Definition at line 6765 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerFxn1__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn1 ti_sysbios_utils_Load_Module__loggerFxn1__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn1)0)
Definition at line 6769 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerFxn2__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn2 ti_sysbios_utils_Load_Module__loggerFxn2__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn2)0)
Definition at line 6773 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerFxn4__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn4 ti_sysbios_utils_Load_Module__loggerFxn4__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn4)0)
Definition at line 6777 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerFxn8__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerFxn8 ti_sysbios_utils_Load_Module__loggerFxn8__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn8)0)
Definition at line 6781 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__loggerObj__C
const __FAR__ CT__ti_sysbios_utils_Load_Module__loggerObj ti_sysbios_utils_Load_Module__loggerObj__C = ((CT__ti_sysbios_utils_Load_Module__loggerObj)0)
Definition at line 6761 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module__state__V
ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module__state__V
Definition at line 1718 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module_State_0_runningTask__A
__T1_ti_sysbios_utils_Load_Module_State__runningTask ti_sysbios_utils_Load_Module_State_0_runningTask__A
Initial value:
= {
    0,
}
Definition at line 1712 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module_State_0_taskEnv__A
__T1_ti_sysbios_utils_Load_Module_State__taskEnv ti_sysbios_utils_Load_Module_State_0_taskEnv__A
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_utils_Load_Module_State_0_taskEnv__A[0].qElem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_utils_Load_Module_State_0_taskEnv__A[0].qElem)),
        },
        (xdc_UInt32)0x0,
        (xdc_UInt32)0x0,
        (xdc_UInt32)0x0,
        (xdc_UInt32)0x0,
        ((xdc_Ptr)0),
    },
}
Definition at line 1715 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module_State_0_taskStartTime__A
__T1_ti_sysbios_utils_Load_Module_State__taskStartTime ti_sysbios_utils_Load_Module_State_0_taskStartTime__A
Initial value:
= {
    (xdc_UInt32)0x0,
}
Definition at line 1709 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Module_State_taskList__O
const __FAR__ xdc_SizeT ti_sysbios_utils_Load_Module_State_taskList__O = offsetof(ti_sysbios_utils_Load_Module_State__,Object_field_taskList)
Definition at line 1977 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Object__count__C
const __FAR__ CT__ti_sysbios_utils_Load_Object__count ti_sysbios_utils_Load_Object__count__C = 0
Definition at line 6785 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Object__heap__C
const __FAR__ CT__ti_sysbios_utils_Load_Object__heap ti_sysbios_utils_Load_Object__heap__C = 0
Definition at line 6789 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Object__sizeof__C
const __FAR__ CT__ti_sysbios_utils_Load_Object__sizeof ti_sysbios_utils_Load_Object__sizeof__C = 0
Definition at line 6793 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_Object__table__C
const __FAR__ CT__ti_sysbios_utils_Load_Object__table ti_sysbios_utils_Load_Object__table__C = 0
Definition at line 6797 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_postUpdate__C
const __FAR__ CT__ti_sysbios_utils_Load_postUpdate ti_sysbios_utils_Load_postUpdate__C = ((CT__ti_sysbios_utils_Load_postUpdate)0)
Definition at line 6817 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_swiEnabled__C
const __FAR__ CT__ti_sysbios_utils_Load_swiEnabled ti_sysbios_utils_Load_swiEnabled__C = 0
Definition at line 6833 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_taskEnabled__C
const __FAR__ CT__ti_sysbios_utils_Load_taskEnabled ti_sysbios_utils_Load_taskEnabled__C = 1
Definition at line 6837 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_updateInIdle__C
const __FAR__ CT__ti_sysbios_utils_Load_updateInIdle ti_sysbios_utils_Load_updateInIdle__C = 0
Definition at line 6821 of file dss_mrr_pe674.c.
ti_sysbios_utils_Load_windowInMs__C
const __FAR__ CT__ti_sysbios_utils_Load_windowInMs ti_sysbios_utils_Load_windowInMs__C = (xdc_UInt)0x1f4
Definition at line 6825 of file dss_mrr_pe674.c.
xdc_runtime_Assert_E_assertFailed__C
const __FAR__ CT__xdc_runtime_Assert_E_assertFailed xdc_runtime_Assert_E_assertFailed__C = (((xdc_runtime_Error_Id)1) << 16 | 0)
Definition at line 6918 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Assert_Module__diagsEnabled xdc_runtime_Assert_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6850 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Assert_Module__diagsIncluded xdc_runtime_Assert_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6854 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Assert_Module__diagsMask xdc_runtime_Assert_Module__diagsMask__C = ((CT__xdc_runtime_Assert_Module__diagsMask)0)
Definition at line 6858 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Assert_Module__gateObj xdc_runtime_Assert_Module__gateObj__C = ((CT__xdc_runtime_Assert_Module__gateObj)0)
Definition at line 6862 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Assert_Module__gatePrms xdc_runtime_Assert_Module__gatePrms__C = ((CT__xdc_runtime_Assert_Module__gatePrms)0)
Definition at line 6866 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__id__C
const __FAR__ CT__xdc_runtime_Assert_Module__id xdc_runtime_Assert_Module__id__C = (xdc_Bits16)0x1
Definition at line 6870 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerDefined xdc_runtime_Assert_Module__loggerDefined__C = 0
Definition at line 6874 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn0 xdc_runtime_Assert_Module__loggerFxn0__C = ((CT__xdc_runtime_Assert_Module__loggerFxn0)0)
Definition at line 6882 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn1 xdc_runtime_Assert_Module__loggerFxn1__C = ((CT__xdc_runtime_Assert_Module__loggerFxn1)0)
Definition at line 6886 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn2 xdc_runtime_Assert_Module__loggerFxn2__C = ((CT__xdc_runtime_Assert_Module__loggerFxn2)0)
Definition at line 6890 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn4 xdc_runtime_Assert_Module__loggerFxn4__C = ((CT__xdc_runtime_Assert_Module__loggerFxn4)0)
Definition at line 6894 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerFxn8 xdc_runtime_Assert_Module__loggerFxn8__C = ((CT__xdc_runtime_Assert_Module__loggerFxn8)0)
Definition at line 6898 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Assert_Module__loggerObj xdc_runtime_Assert_Module__loggerObj__C = ((CT__xdc_runtime_Assert_Module__loggerObj)0)
Definition at line 6878 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Object__count__C
const __FAR__ CT__xdc_runtime_Assert_Object__count xdc_runtime_Assert_Object__count__C = 0
Definition at line 6902 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Object__heap__C
const __FAR__ CT__xdc_runtime_Assert_Object__heap xdc_runtime_Assert_Object__heap__C = 0
Definition at line 6906 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Assert_Object__sizeof xdc_runtime_Assert_Object__sizeof__C = 0
Definition at line 6910 of file dss_mrr_pe674.c.
xdc_runtime_Assert_Object__table__C
const __FAR__ CT__xdc_runtime_Assert_Object__table xdc_runtime_Assert_Object__table__C = 0
Definition at line 6914 of file dss_mrr_pe674.c.
xdc_runtime_Core_A_initializedParams__C
const __FAR__ CT__xdc_runtime_Core_A_initializedParams xdc_runtime_Core_A_initializedParams__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6995 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Core_Module__diagsEnabled xdc_runtime_Core_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6927 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Core_Module__diagsIncluded xdc_runtime_Core_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6931 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Core_Module__diagsMask xdc_runtime_Core_Module__diagsMask__C = ((CT__xdc_runtime_Core_Module__diagsMask)0)
Definition at line 6935 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Core_Module__gateObj xdc_runtime_Core_Module__gateObj__C = ((CT__xdc_runtime_Core_Module__gateObj)0)
Definition at line 6939 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Core_Module__gatePrms xdc_runtime_Core_Module__gatePrms__C = ((CT__xdc_runtime_Core_Module__gatePrms)0)
Definition at line 6943 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__id__C
const __FAR__ CT__xdc_runtime_Core_Module__id xdc_runtime_Core_Module__id__C = (xdc_Bits16)0x2
Definition at line 6947 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerDefined xdc_runtime_Core_Module__loggerDefined__C = 0
Definition at line 6951 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn0 xdc_runtime_Core_Module__loggerFxn0__C = ((CT__xdc_runtime_Core_Module__loggerFxn0)0)
Definition at line 6959 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn1 xdc_runtime_Core_Module__loggerFxn1__C = ((CT__xdc_runtime_Core_Module__loggerFxn1)0)
Definition at line 6963 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn2 xdc_runtime_Core_Module__loggerFxn2__C = ((CT__xdc_runtime_Core_Module__loggerFxn2)0)
Definition at line 6967 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn4 xdc_runtime_Core_Module__loggerFxn4__C = ((CT__xdc_runtime_Core_Module__loggerFxn4)0)
Definition at line 6971 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerFxn8 xdc_runtime_Core_Module__loggerFxn8__C = ((CT__xdc_runtime_Core_Module__loggerFxn8)0)
Definition at line 6975 of file dss_mrr_pe674.c.
xdc_runtime_Core_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Core_Module__loggerObj xdc_runtime_Core_Module__loggerObj__C = ((CT__xdc_runtime_Core_Module__loggerObj)0)
Definition at line 6955 of file dss_mrr_pe674.c.
xdc_runtime_Core_Object__count__C
const __FAR__ CT__xdc_runtime_Core_Object__count xdc_runtime_Core_Object__count__C = 0
Definition at line 6979 of file dss_mrr_pe674.c.
xdc_runtime_Core_Object__heap__C
const __FAR__ CT__xdc_runtime_Core_Object__heap xdc_runtime_Core_Object__heap__C = 0
Definition at line 6983 of file dss_mrr_pe674.c.
xdc_runtime_Core_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Core_Object__sizeof xdc_runtime_Core_Object__sizeof__C = 0
Definition at line 6987 of file dss_mrr_pe674.c.
xdc_runtime_Core_Object__table__C
const __FAR__ CT__xdc_runtime_Core_Object__table xdc_runtime_Core_Object__table__C = 0
Definition at line 6991 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsEnabled xdc_runtime_Defaults_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7004 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsIncluded xdc_runtime_Defaults_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 7008 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Defaults_Module__diagsMask xdc_runtime_Defaults_Module__diagsMask__C = ((CT__xdc_runtime_Defaults_Module__diagsMask)0)
Definition at line 7012 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Defaults_Module__gateObj xdc_runtime_Defaults_Module__gateObj__C = ((CT__xdc_runtime_Defaults_Module__gateObj)0)
Definition at line 7016 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Defaults_Module__gatePrms xdc_runtime_Defaults_Module__gatePrms__C = ((CT__xdc_runtime_Defaults_Module__gatePrms)0)
Definition at line 7020 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__id__C
const __FAR__ CT__xdc_runtime_Defaults_Module__id xdc_runtime_Defaults_Module__id__C = (xdc_Bits16)0x3
Definition at line 7024 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerDefined xdc_runtime_Defaults_Module__loggerDefined__C = 0
Definition at line 7028 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn0 xdc_runtime_Defaults_Module__loggerFxn0__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn0)0)
Definition at line 7036 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn1 xdc_runtime_Defaults_Module__loggerFxn1__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn1)0)
Definition at line 7040 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn2 xdc_runtime_Defaults_Module__loggerFxn2__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn2)0)
Definition at line 7044 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn4 xdc_runtime_Defaults_Module__loggerFxn4__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn4)0)
Definition at line 7048 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerFxn8 xdc_runtime_Defaults_Module__loggerFxn8__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn8)0)
Definition at line 7052 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Defaults_Module__loggerObj xdc_runtime_Defaults_Module__loggerObj__C = ((CT__xdc_runtime_Defaults_Module__loggerObj)0)
Definition at line 7032 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Object__count__C
const __FAR__ CT__xdc_runtime_Defaults_Object__count xdc_runtime_Defaults_Object__count__C = 0
Definition at line 7056 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Object__heap__C
const __FAR__ CT__xdc_runtime_Defaults_Object__heap xdc_runtime_Defaults_Object__heap__C = 0
Definition at line 7060 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Defaults_Object__sizeof xdc_runtime_Defaults_Object__sizeof__C = 0
Definition at line 7064 of file dss_mrr_pe674.c.
xdc_runtime_Defaults_Object__table__C
const __FAR__ CT__xdc_runtime_Defaults_Object__table xdc_runtime_Defaults_Object__table__C = 0
Definition at line 7068 of file dss_mrr_pe674.c.
xdc_runtime_Diags_dictBase__C
const __FAR__ CT__xdc_runtime_Diags_dictBase xdc_runtime_Diags_dictBase__C = ((CT__xdc_runtime_Diags_dictBase)0)
Definition at line 7149 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Diags_Module__diagsEnabled xdc_runtime_Diags_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7077 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Diags_Module__diagsIncluded xdc_runtime_Diags_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7081 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Diags_Module__diagsMask xdc_runtime_Diags_Module__diagsMask__C = ((CT__xdc_runtime_Diags_Module__diagsMask)0)
Definition at line 7085 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Diags_Module__gateObj xdc_runtime_Diags_Module__gateObj__C = ((CT__xdc_runtime_Diags_Module__gateObj)0)
Definition at line 7089 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Diags_Module__gatePrms xdc_runtime_Diags_Module__gatePrms__C = ((CT__xdc_runtime_Diags_Module__gatePrms)0)
Definition at line 7093 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__id__C
const __FAR__ CT__xdc_runtime_Diags_Module__id xdc_runtime_Diags_Module__id__C = (xdc_Bits16)0x4
Definition at line 7097 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerDefined xdc_runtime_Diags_Module__loggerDefined__C = 0
Definition at line 7101 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn0 xdc_runtime_Diags_Module__loggerFxn0__C = ((CT__xdc_runtime_Diags_Module__loggerFxn0)0)
Definition at line 7109 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn1 xdc_runtime_Diags_Module__loggerFxn1__C = ((CT__xdc_runtime_Diags_Module__loggerFxn1)0)
Definition at line 7113 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn2 xdc_runtime_Diags_Module__loggerFxn2__C = ((CT__xdc_runtime_Diags_Module__loggerFxn2)0)
Definition at line 7117 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn4 xdc_runtime_Diags_Module__loggerFxn4__C = ((CT__xdc_runtime_Diags_Module__loggerFxn4)0)
Definition at line 7121 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerFxn8 xdc_runtime_Diags_Module__loggerFxn8__C = ((CT__xdc_runtime_Diags_Module__loggerFxn8)0)
Definition at line 7125 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Diags_Module__loggerObj xdc_runtime_Diags_Module__loggerObj__C = ((CT__xdc_runtime_Diags_Module__loggerObj)0)
Definition at line 7105 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Object__count__C
const __FAR__ CT__xdc_runtime_Diags_Object__count xdc_runtime_Diags_Object__count__C = 0
Definition at line 7129 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Object__heap__C
const __FAR__ CT__xdc_runtime_Diags_Object__heap xdc_runtime_Diags_Object__heap__C = 0
Definition at line 7133 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Diags_Object__sizeof xdc_runtime_Diags_Object__sizeof__C = 0
Definition at line 7137 of file dss_mrr_pe674.c.
xdc_runtime_Diags_Object__table__C
const __FAR__ CT__xdc_runtime_Diags_Object__table xdc_runtime_Diags_Object__table__C = 0
Definition at line 7141 of file dss_mrr_pe674.c.
xdc_runtime_Diags_setMaskEnabled__C
const __FAR__ CT__xdc_runtime_Diags_setMaskEnabled xdc_runtime_Diags_setMaskEnabled__C = 0
Definition at line 7145 of file dss_mrr_pe674.c.
xdc_runtime_Error_E_generic__C
const __FAR__ CT__xdc_runtime_Error_E_generic xdc_runtime_Error_E_generic__C = (((xdc_runtime_Error_Id)2) << 16 | 0)
Definition at line 7245 of file dss_mrr_pe674.c.
xdc_runtime_Error_E_memory__C
const __FAR__ CT__xdc_runtime_Error_E_memory xdc_runtime_Error_E_memory__C = (((xdc_runtime_Error_Id)3) << 16 | 0)
Definition at line 7249 of file dss_mrr_pe674.c.
xdc_runtime_Error_E_msgCode__C
const __FAR__ CT__xdc_runtime_Error_E_msgCode xdc_runtime_Error_E_msgCode__C = (((xdc_runtime_Error_Id)4) << 16 | 0)
Definition at line 7253 of file dss_mrr_pe674.c.
xdc_runtime_Error_IgnoreBlock
xdc_runtime_Error_Block xdc_runtime_Error_IgnoreBlock
Initial value:
= {
    ~0,
    {
        {0, 0}
    },
    0,
    0,
    {
        0,
        0,
        0
    }
}
Definition at line 2034 of file dss_mrr_pe674.c.
xdc_runtime_Error_maxDepth__C
const __FAR__ CT__xdc_runtime_Error_maxDepth xdc_runtime_Error_maxDepth__C = (xdc_UInt16)0x10
Definition at line 7265 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Error_Module__diagsEnabled xdc_runtime_Error_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7173 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Error_Module__diagsIncluded xdc_runtime_Error_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 7177 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Error_Module__diagsMask xdc_runtime_Error_Module__diagsMask__C = ((CT__xdc_runtime_Error_Module__diagsMask)0)
Definition at line 7181 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Error_Module__gateObj xdc_runtime_Error_Module__gateObj__C = ((CT__xdc_runtime_Error_Module__gateObj)0)
Definition at line 7185 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Error_Module__gatePrms xdc_runtime_Error_Module__gatePrms__C = ((CT__xdc_runtime_Error_Module__gatePrms)0)
Definition at line 7189 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__id__C
const __FAR__ CT__xdc_runtime_Error_Module__id xdc_runtime_Error_Module__id__C = (xdc_Bits16)0x5
Definition at line 7193 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerDefined xdc_runtime_Error_Module__loggerDefined__C = 0
Definition at line 7197 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn0 xdc_runtime_Error_Module__loggerFxn0__C = ((CT__xdc_runtime_Error_Module__loggerFxn0)0)
Definition at line 7205 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn1 xdc_runtime_Error_Module__loggerFxn1__C = ((CT__xdc_runtime_Error_Module__loggerFxn1)0)
Definition at line 7209 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn2 xdc_runtime_Error_Module__loggerFxn2__C = ((CT__xdc_runtime_Error_Module__loggerFxn2)0)
Definition at line 7213 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn4 xdc_runtime_Error_Module__loggerFxn4__C = ((CT__xdc_runtime_Error_Module__loggerFxn4)0)
Definition at line 7217 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerFxn8 xdc_runtime_Error_Module__loggerFxn8__C = ((CT__xdc_runtime_Error_Module__loggerFxn8)0)
Definition at line 7221 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Error_Module__loggerObj xdc_runtime_Error_Module__loggerObj__C = ((CT__xdc_runtime_Error_Module__loggerObj)0)
Definition at line 7201 of file dss_mrr_pe674.c.
xdc_runtime_Error_Module__state__V
xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module__state__V
Initial value:
= {
    (xdc_UInt16)0x0,
}
Definition at line 1751 of file dss_mrr_pe674.c.
xdc_runtime_Error_Object__count__C
const __FAR__ CT__xdc_runtime_Error_Object__count xdc_runtime_Error_Object__count__C = 0
Definition at line 7225 of file dss_mrr_pe674.c.
xdc_runtime_Error_Object__heap__C
const __FAR__ CT__xdc_runtime_Error_Object__heap xdc_runtime_Error_Object__heap__C = 0
Definition at line 7229 of file dss_mrr_pe674.c.
xdc_runtime_Error_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Error_Object__sizeof xdc_runtime_Error_Object__sizeof__C = 0
Definition at line 7233 of file dss_mrr_pe674.c.
xdc_runtime_Error_Object__table__C
const __FAR__ CT__xdc_runtime_Error_Object__table xdc_runtime_Error_Object__table__C = 0
Definition at line 7237 of file dss_mrr_pe674.c.
xdc_runtime_Error_policy__C
const __FAR__ CT__xdc_runtime_Error_policy xdc_runtime_Error_policy__C = xdc_runtime_Error_UNWIND
Definition at line 7257 of file dss_mrr_pe674.c.
xdc_runtime_Error_policyFxn__C
const __FAR__ CT__xdc_runtime_Error_policyFxn xdc_runtime_Error_policyFxn__C = ((CT__xdc_runtime_Error_policyFxn)((xdc_Fxn)xdc_runtime_Error_policyDefault__E))
Definition at line 7241 of file dss_mrr_pe674.c.
xdc_runtime_Error_raiseHook__C
const __FAR__ CT__xdc_runtime_Error_raiseHook xdc_runtime_Error_raiseHook__C = ((CT__xdc_runtime_Error_raiseHook)((xdc_Fxn)ti_sysbios_BIOS_errorRaiseHook__I))
Definition at line 7261 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Gate_Module__diagsEnabled xdc_runtime_Gate_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7274 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Gate_Module__diagsIncluded xdc_runtime_Gate_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7278 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Gate_Module__diagsMask xdc_runtime_Gate_Module__diagsMask__C = ((CT__xdc_runtime_Gate_Module__diagsMask)0)
Definition at line 7282 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Gate_Module__gateObj xdc_runtime_Gate_Module__gateObj__C = ((CT__xdc_runtime_Gate_Module__gateObj)0)
Definition at line 7286 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Gate_Module__gatePrms xdc_runtime_Gate_Module__gatePrms__C = ((CT__xdc_runtime_Gate_Module__gatePrms)0)
Definition at line 7290 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__id__C
const __FAR__ CT__xdc_runtime_Gate_Module__id xdc_runtime_Gate_Module__id__C = (xdc_Bits16)0x6
Definition at line 7294 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerDefined xdc_runtime_Gate_Module__loggerDefined__C = 0
Definition at line 7298 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn0 xdc_runtime_Gate_Module__loggerFxn0__C = ((CT__xdc_runtime_Gate_Module__loggerFxn0)0)
Definition at line 7306 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn1 xdc_runtime_Gate_Module__loggerFxn1__C = ((CT__xdc_runtime_Gate_Module__loggerFxn1)0)
Definition at line 7310 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn2 xdc_runtime_Gate_Module__loggerFxn2__C = ((CT__xdc_runtime_Gate_Module__loggerFxn2)0)
Definition at line 7314 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn4 xdc_runtime_Gate_Module__loggerFxn4__C = ((CT__xdc_runtime_Gate_Module__loggerFxn4)0)
Definition at line 7318 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerFxn8 xdc_runtime_Gate_Module__loggerFxn8__C = ((CT__xdc_runtime_Gate_Module__loggerFxn8)0)
Definition at line 7322 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Gate_Module__loggerObj xdc_runtime_Gate_Module__loggerObj__C = ((CT__xdc_runtime_Gate_Module__loggerObj)0)
Definition at line 7302 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Object__count__C
const __FAR__ CT__xdc_runtime_Gate_Object__count xdc_runtime_Gate_Object__count__C = 0
Definition at line 7326 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Object__heap__C
const __FAR__ CT__xdc_runtime_Gate_Object__heap xdc_runtime_Gate_Object__heap__C = 0
Definition at line 7330 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Gate_Object__sizeof xdc_runtime_Gate_Object__sizeof__C = 0
Definition at line 7334 of file dss_mrr_pe674.c.
xdc_runtime_Gate_Object__table__C
const __FAR__ CT__xdc_runtime_Gate_Object__table xdc_runtime_Gate_Object__table__C = 0
Definition at line 7338 of file dss_mrr_pe674.c.
xdc_runtime_IGateProvider_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IGateProvider_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 759 of file dss_mrr_pe674.c.
xdc_runtime_IHeap_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IHeap_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 750 of file dss_mrr_pe674.c.
xdc_runtime_IModule_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_IModule_Interface__BASE__C = {0}
Definition at line 762 of file dss_mrr_pe674.c.
xdc_runtime_ISystemSupport_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ISystemSupport_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 753 of file dss_mrr_pe674.c.
xdc_runtime_ITimestampClient_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ITimestampClient_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 765 of file dss_mrr_pe674.c.
xdc_runtime_ITimestampProvider_Interface__BASE__C
const __FAR__ xdc_runtime_Types_Base xdc_runtime_ITimestampProvider_Interface__BASE__C = {&xdc_runtime_ITimestampClient_Interface__BASE__C}
Definition at line 756 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_construct__C
const __FAR__ CT__xdc_runtime_Log_L_construct xdc_runtime_Log_L_construct__C = (((xdc_runtime_Log_Event)1) << 16 | 4)
Definition at line 7415 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_create__C
const __FAR__ CT__xdc_runtime_Log_L_create xdc_runtime_Log_L_create__C = (((xdc_runtime_Log_Event)2) << 16 | 4)
Definition at line 7419 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_delete__C
const __FAR__ CT__xdc_runtime_Log_L_delete xdc_runtime_Log_L_delete__C = (((xdc_runtime_Log_Event)4) << 16 | 4)
Definition at line 7427 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_destruct__C
const __FAR__ CT__xdc_runtime_Log_L_destruct xdc_runtime_Log_L_destruct__C = (((xdc_runtime_Log_Event)3) << 16 | 4)
Definition at line 7423 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_error__C
const __FAR__ CT__xdc_runtime_Log_L_error xdc_runtime_Log_L_error__C = (((xdc_runtime_Log_Event)5) << 16 | 192)
Definition at line 7431 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_info__C
const __FAR__ CT__xdc_runtime_Log_L_info xdc_runtime_Log_L_info__C = (((xdc_runtime_Log_Event)7) << 16 | 16384)
Definition at line 7439 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_start__C
const __FAR__ CT__xdc_runtime_Log_L_start xdc_runtime_Log_L_start__C = (((xdc_runtime_Log_Event)8) << 16 | 32768)
Definition at line 7443 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_startInstance__C
const __FAR__ CT__xdc_runtime_Log_L_startInstance xdc_runtime_Log_L_startInstance__C = (((xdc_runtime_Log_Event)10) << 16 | 32768)
Definition at line 7451 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_stop__C
const __FAR__ CT__xdc_runtime_Log_L_stop xdc_runtime_Log_L_stop__C = (((xdc_runtime_Log_Event)9) << 16 | 32768)
Definition at line 7447 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_stopInstance__C
const __FAR__ CT__xdc_runtime_Log_L_stopInstance xdc_runtime_Log_L_stopInstance__C = (((xdc_runtime_Log_Event)11) << 16 | 32768)
Definition at line 7455 of file dss_mrr_pe674.c.
xdc_runtime_Log_L_warning__C
const __FAR__ CT__xdc_runtime_Log_L_warning xdc_runtime_Log_L_warning__C = (((xdc_runtime_Log_Event)6) << 16 | 224)
Definition at line 7435 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Log_Module__diagsEnabled xdc_runtime_Log_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7347 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Log_Module__diagsIncluded xdc_runtime_Log_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7351 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Log_Module__diagsMask xdc_runtime_Log_Module__diagsMask__C = ((CT__xdc_runtime_Log_Module__diagsMask)0)
Definition at line 7355 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Log_Module__gateObj xdc_runtime_Log_Module__gateObj__C = ((CT__xdc_runtime_Log_Module__gateObj)0)
Definition at line 7359 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Log_Module__gatePrms xdc_runtime_Log_Module__gatePrms__C = ((CT__xdc_runtime_Log_Module__gatePrms)0)
Definition at line 7363 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__id__C
const __FAR__ CT__xdc_runtime_Log_Module__id xdc_runtime_Log_Module__id__C = (xdc_Bits16)0x7
Definition at line 7367 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerDefined xdc_runtime_Log_Module__loggerDefined__C = 0
Definition at line 7371 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn0 xdc_runtime_Log_Module__loggerFxn0__C = ((CT__xdc_runtime_Log_Module__loggerFxn0)0)
Definition at line 7379 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn1 xdc_runtime_Log_Module__loggerFxn1__C = ((CT__xdc_runtime_Log_Module__loggerFxn1)0)
Definition at line 7383 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn2 xdc_runtime_Log_Module__loggerFxn2__C = ((CT__xdc_runtime_Log_Module__loggerFxn2)0)
Definition at line 7387 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn4 xdc_runtime_Log_Module__loggerFxn4__C = ((CT__xdc_runtime_Log_Module__loggerFxn4)0)
Definition at line 7391 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerFxn8 xdc_runtime_Log_Module__loggerFxn8__C = ((CT__xdc_runtime_Log_Module__loggerFxn8)0)
Definition at line 7395 of file dss_mrr_pe674.c.
xdc_runtime_Log_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Log_Module__loggerObj xdc_runtime_Log_Module__loggerObj__C = ((CT__xdc_runtime_Log_Module__loggerObj)0)
Definition at line 7375 of file dss_mrr_pe674.c.
xdc_runtime_Log_Object__count__C
const __FAR__ CT__xdc_runtime_Log_Object__count xdc_runtime_Log_Object__count__C = 0
Definition at line 7399 of file dss_mrr_pe674.c.
xdc_runtime_Log_Object__heap__C
const __FAR__ CT__xdc_runtime_Log_Object__heap xdc_runtime_Log_Object__heap__C = 0
Definition at line 7403 of file dss_mrr_pe674.c.
xdc_runtime_Log_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Log_Object__sizeof xdc_runtime_Log_Object__sizeof__C = 0
Definition at line 7407 of file dss_mrr_pe674.c.
xdc_runtime_Log_Object__table__C
const __FAR__ CT__xdc_runtime_Log_Object__table xdc_runtime_Log_Object__table__C = 0
Definition at line 7411 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Main_Module__diagsEnabled xdc_runtime_Main_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7464 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Main_Module__diagsIncluded xdc_runtime_Main_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 7468 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Main_Module__diagsMask xdc_runtime_Main_Module__diagsMask__C = ((CT__xdc_runtime_Main_Module__diagsMask)0)
Definition at line 7472 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Main_Module__gateObj xdc_runtime_Main_Module__gateObj__C = ((CT__xdc_runtime_Main_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 7476 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Main_Module__gatePrms xdc_runtime_Main_Module__gatePrms__C = ((CT__xdc_runtime_Main_Module__gatePrms)0)
Definition at line 7480 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__id__C
const __FAR__ CT__xdc_runtime_Main_Module__id xdc_runtime_Main_Module__id__C = (xdc_Bits16)0x8
Definition at line 7484 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerDefined xdc_runtime_Main_Module__loggerDefined__C = 0
Definition at line 7488 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn0 xdc_runtime_Main_Module__loggerFxn0__C = ((CT__xdc_runtime_Main_Module__loggerFxn0)0)
Definition at line 7496 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn1 xdc_runtime_Main_Module__loggerFxn1__C = ((CT__xdc_runtime_Main_Module__loggerFxn1)0)
Definition at line 7500 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn2 xdc_runtime_Main_Module__loggerFxn2__C = ((CT__xdc_runtime_Main_Module__loggerFxn2)0)
Definition at line 7504 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn4 xdc_runtime_Main_Module__loggerFxn4__C = ((CT__xdc_runtime_Main_Module__loggerFxn4)0)
Definition at line 7508 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerFxn8 xdc_runtime_Main_Module__loggerFxn8__C = ((CT__xdc_runtime_Main_Module__loggerFxn8)0)
Definition at line 7512 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Main_Module__loggerObj xdc_runtime_Main_Module__loggerObj__C = ((CT__xdc_runtime_Main_Module__loggerObj)0)
Definition at line 7492 of file dss_mrr_pe674.c.
xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Main_Object__count__C
const __FAR__ CT__xdc_runtime_Main_Object__count xdc_runtime_Main_Object__count__C = 0
Definition at line 7516 of file dss_mrr_pe674.c.
xdc_runtime_Main_Object__heap__C
const __FAR__ CT__xdc_runtime_Main_Object__heap xdc_runtime_Main_Object__heap__C = 0
Definition at line 7520 of file dss_mrr_pe674.c.
xdc_runtime_Main_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Main_Object__sizeof xdc_runtime_Main_Object__sizeof__C = 0
Definition at line 7524 of file dss_mrr_pe674.c.
xdc_runtime_Main_Object__table__C
const __FAR__ CT__xdc_runtime_Main_Object__table xdc_runtime_Main_Object__table__C = 0
Definition at line 7528 of file dss_mrr_pe674.c.
xdc_runtime_Memory_defaultHeapInstance__C
const __FAR__ CT__xdc_runtime_Memory_defaultHeapInstance xdc_runtime_Memory_defaultHeapInstance__C = (xdc_runtime_IHeap_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0]
Definition at line 7625 of file dss_mrr_pe674.c.
xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_Memory_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Memory_Module__diagsEnabled xdc_runtime_Memory_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7557 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Memory_Module__diagsIncluded xdc_runtime_Memory_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7561 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Memory_Module__diagsMask xdc_runtime_Memory_Module__diagsMask__C = ((CT__xdc_runtime_Memory_Module__diagsMask)0)
Definition at line 7565 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Memory_Module__gateObj xdc_runtime_Memory_Module__gateObj__C = ((CT__xdc_runtime_Memory_Module__gateObj)0)
Definition at line 7569 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Memory_Module__gatePrms xdc_runtime_Memory_Module__gatePrms__C = ((CT__xdc_runtime_Memory_Module__gatePrms)0)
Definition at line 7573 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__id__C
const __FAR__ CT__xdc_runtime_Memory_Module__id xdc_runtime_Memory_Module__id__C = (xdc_Bits16)0x9
Definition at line 7577 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerDefined xdc_runtime_Memory_Module__loggerDefined__C = 0
Definition at line 7581 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn0 xdc_runtime_Memory_Module__loggerFxn0__C = ((CT__xdc_runtime_Memory_Module__loggerFxn0)0)
Definition at line 7589 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn1 xdc_runtime_Memory_Module__loggerFxn1__C = ((CT__xdc_runtime_Memory_Module__loggerFxn1)0)
Definition at line 7593 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn2 xdc_runtime_Memory_Module__loggerFxn2__C = ((CT__xdc_runtime_Memory_Module__loggerFxn2)0)
Definition at line 7597 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn4 xdc_runtime_Memory_Module__loggerFxn4__C = ((CT__xdc_runtime_Memory_Module__loggerFxn4)0)
Definition at line 7601 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerFxn8 xdc_runtime_Memory_Module__loggerFxn8__C = ((CT__xdc_runtime_Memory_Module__loggerFxn8)0)
Definition at line 7605 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Memory_Module__loggerObj xdc_runtime_Memory_Module__loggerObj__C = ((CT__xdc_runtime_Memory_Module__loggerObj)0)
Definition at line 7585 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Module__state__V
xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module__state__V
Initial value:
= {
    (xdc_SizeT)0x8,
}
Definition at line 1784 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Object__count__C
const __FAR__ CT__xdc_runtime_Memory_Object__count xdc_runtime_Memory_Object__count__C = 0
Definition at line 7609 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Object__heap__C
const __FAR__ CT__xdc_runtime_Memory_Object__heap xdc_runtime_Memory_Object__heap__C = 0
Definition at line 7613 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Memory_Object__sizeof xdc_runtime_Memory_Object__sizeof__C = 0
Definition at line 7617 of file dss_mrr_pe674.c.
xdc_runtime_Memory_Object__table__C
const __FAR__ CT__xdc_runtime_Memory_Object__table xdc_runtime_Memory_Object__table__C = 0
Definition at line 7621 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Registry_Module__diagsEnabled xdc_runtime_Registry_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7655 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Registry_Module__diagsIncluded xdc_runtime_Registry_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 7659 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Registry_Module__diagsMask xdc_runtime_Registry_Module__diagsMask__C = ((CT__xdc_runtime_Registry_Module__diagsMask)0)
Definition at line 7663 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Registry_Module__gateObj xdc_runtime_Registry_Module__gateObj__C = ((CT__xdc_runtime_Registry_Module__gateObj)0)
Definition at line 7667 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Registry_Module__gatePrms xdc_runtime_Registry_Module__gatePrms__C = ((CT__xdc_runtime_Registry_Module__gatePrms)0)
Definition at line 7671 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__id__C
const __FAR__ CT__xdc_runtime_Registry_Module__id xdc_runtime_Registry_Module__id__C = (xdc_Bits16)0xa
Definition at line 7675 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerDefined xdc_runtime_Registry_Module__loggerDefined__C = 0
Definition at line 7679 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn0 xdc_runtime_Registry_Module__loggerFxn0__C = ((CT__xdc_runtime_Registry_Module__loggerFxn0)0)
Definition at line 7687 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn1 xdc_runtime_Registry_Module__loggerFxn1__C = ((CT__xdc_runtime_Registry_Module__loggerFxn1)0)
Definition at line 7691 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn2 xdc_runtime_Registry_Module__loggerFxn2__C = ((CT__xdc_runtime_Registry_Module__loggerFxn2)0)
Definition at line 7695 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn4 xdc_runtime_Registry_Module__loggerFxn4__C = ((CT__xdc_runtime_Registry_Module__loggerFxn4)0)
Definition at line 7699 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerFxn8 xdc_runtime_Registry_Module__loggerFxn8__C = ((CT__xdc_runtime_Registry_Module__loggerFxn8)0)
Definition at line 7703 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Registry_Module__loggerObj xdc_runtime_Registry_Module__loggerObj__C = ((CT__xdc_runtime_Registry_Module__loggerObj)0)
Definition at line 7683 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Module__state__V
xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module__state__V
Initial value:
= {
    ((xdc_runtime_Types_RegDesc*)0),
    (xdc_Bits16)0x7fff,
}
Definition at line 1803 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Object__count__C
const __FAR__ CT__xdc_runtime_Registry_Object__count xdc_runtime_Registry_Object__count__C = 0
Definition at line 7707 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Object__heap__C
const __FAR__ CT__xdc_runtime_Registry_Object__heap xdc_runtime_Registry_Object__heap__C = 0
Definition at line 7711 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Registry_Object__sizeof xdc_runtime_Registry_Object__sizeof__C = 0
Definition at line 7715 of file dss_mrr_pe674.c.
xdc_runtime_Registry_Object__table__C
const __FAR__ CT__xdc_runtime_Registry_Object__table xdc_runtime_Registry_Object__table__C = 0
Definition at line 7719 of file dss_mrr_pe674.c.
xdc_runtime_Startup_execImpl__C
const __FAR__ CT__xdc_runtime_Startup_execImpl xdc_runtime_Startup_execImpl__C = ((CT__xdc_runtime_Startup_execImpl)((xdc_Fxn)xdc_runtime_Startup_exec__I))
Definition at line 7866 of file dss_mrr_pe674.c.
xdc_runtime_Startup_firstFxns__A
const __T1_xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_heaps_HeapMem_init__I)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_hal_Hwi_initStack)),
}
Definition at line 1824 of file dss_mrr_pe674.c.
xdc_runtime_Startup_firstFxns__C
const __FAR__ CT__xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__C = {2, ((__T1_xdc_runtime_Startup_firstFxns *)xdc_runtime_Startup_firstFxns__A)}
Definition at line 7854 of file dss_mrr_pe674.c.
xdc_runtime_Startup_lastFxns__C
const __FAR__ CT__xdc_runtime_Startup_lastFxns xdc_runtime_Startup_lastFxns__C = {0, 0}
Definition at line 7858 of file dss_mrr_pe674.c.
xdc_runtime_Startup_maxPasses__C
const __FAR__ CT__xdc_runtime_Startup_maxPasses xdc_runtime_Startup_maxPasses__C = (xdc_Int)0x20
Definition at line 7850 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Startup_Module__diagsEnabled xdc_runtime_Startup_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7782 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Startup_Module__diagsIncluded xdc_runtime_Startup_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7786 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Startup_Module__diagsMask xdc_runtime_Startup_Module__diagsMask__C = ((CT__xdc_runtime_Startup_Module__diagsMask)0)
Definition at line 7790 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Startup_Module__gateObj xdc_runtime_Startup_Module__gateObj__C = ((CT__xdc_runtime_Startup_Module__gateObj)0)
Definition at line 7794 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Startup_Module__gatePrms xdc_runtime_Startup_Module__gatePrms__C = ((CT__xdc_runtime_Startup_Module__gatePrms)0)
Definition at line 7798 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__id__C
const __FAR__ CT__xdc_runtime_Startup_Module__id xdc_runtime_Startup_Module__id__C = (xdc_Bits16)0xb
Definition at line 7802 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerDefined xdc_runtime_Startup_Module__loggerDefined__C = 0
Definition at line 7806 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn0 xdc_runtime_Startup_Module__loggerFxn0__C = ((CT__xdc_runtime_Startup_Module__loggerFxn0)0)
Definition at line 7814 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn1 xdc_runtime_Startup_Module__loggerFxn1__C = ((CT__xdc_runtime_Startup_Module__loggerFxn1)0)
Definition at line 7818 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn2 xdc_runtime_Startup_Module__loggerFxn2__C = ((CT__xdc_runtime_Startup_Module__loggerFxn2)0)
Definition at line 7822 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn4 xdc_runtime_Startup_Module__loggerFxn4__C = ((CT__xdc_runtime_Startup_Module__loggerFxn4)0)
Definition at line 7826 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerFxn8 xdc_runtime_Startup_Module__loggerFxn8__C = ((CT__xdc_runtime_Startup_Module__loggerFxn8)0)
Definition at line 7830 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Startup_Module__loggerObj xdc_runtime_Startup_Module__loggerObj__C = ((CT__xdc_runtime_Startup_Module__loggerObj)0)
Definition at line 7810 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Module__state__V
xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module__state__V
Initial value:
= {
    ((xdc_Int*)0),
    0,
    0,
}
Definition at line 1818 of file dss_mrr_pe674.c.
Referenced by ti_sysbios_family_c64p_Cache_Module__startupDone__F(), ti_sysbios_family_c64p_EventCombiner_Module__startupDone__F(), ti_sysbios_family_c64p_Exception_Module__startupDone__F(), ti_sysbios_family_c64p_Hwi_Module__startupDone__F(), ti_sysbios_family_c64p_TimestampProvider_Module__startupDone__F(), ti_sysbios_hal_Hwi_Module__startupDone__F(), ti_sysbios_knl_Clock_Module__startupDone__F(), ti_sysbios_knl_Task_Module__startupDone__F(), ti_sysbios_timers_rti_Timer_Module__startupDone__F(), and xdc_runtime_System_Module__startupDone__F().
xdc_runtime_Startup_Object__count__C
const __FAR__ CT__xdc_runtime_Startup_Object__count xdc_runtime_Startup_Object__count__C = 0
Definition at line 7834 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Object__heap__C
const __FAR__ CT__xdc_runtime_Startup_Object__heap xdc_runtime_Startup_Object__heap__C = 0
Definition at line 7838 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Startup_Object__sizeof xdc_runtime_Startup_Object__sizeof__C = 0
Definition at line 7842 of file dss_mrr_pe674.c.
xdc_runtime_Startup_Object__table__C
const __FAR__ CT__xdc_runtime_Startup_Object__table xdc_runtime_Startup_Object__table__C = 0
Definition at line 7846 of file dss_mrr_pe674.c.
xdc_runtime_Startup_sfxnRts__A
const __T1_xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__A
Initial value:
= {
    1,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
}
Definition at line 1860 of file dss_mrr_pe674.c.
xdc_runtime_Startup_sfxnRts__C
const __FAR__ CT__xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__C = ((CT__xdc_runtime_Startup_sfxnRts)xdc_runtime_Startup_sfxnRts__A)
Definition at line 7874 of file dss_mrr_pe674.c.
xdc_runtime_Startup_sfxnTab__A
const __T1_xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__A
Initial value:
= {
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)xdc_runtime_System_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_c64p_EventCombiner_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_c64p_Exception_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_c64p_Hwi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_c64p_TimestampProvider_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_c64p_Cache_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Clock_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Task_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_hal_Hwi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_timers_rti_Timer_Module_startup__E)),
}
Definition at line 1857 of file dss_mrr_pe674.c.
xdc_runtime_Startup_sfxnTab__C
const __FAR__ CT__xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__C = ((CT__xdc_runtime_Startup_sfxnTab)xdc_runtime_Startup_sfxnTab__A)
Definition at line 7870 of file dss_mrr_pe674.c.
xdc_runtime_Startup_startModsFxn__C
const __FAR__ CT__xdc_runtime_Startup_startModsFxn xdc_runtime_Startup_startModsFxn__C = ((CT__xdc_runtime_Startup_startModsFxn)((xdc_Fxn)xdc_runtime_Startup_startMods__I))
Definition at line 7862 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_Startup_exec__I().
xdc_runtime_SysStd_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsEnabled xdc_runtime_SysStd_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7883 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsIncluded xdc_runtime_SysStd_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7887 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_SysStd_Module__diagsMask xdc_runtime_SysStd_Module__diagsMask__C = ((CT__xdc_runtime_SysStd_Module__diagsMask)0)
Definition at line 7891 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__FXNS__C
const xdc_runtime_SysStd_Fxns__ xdc_runtime_SysStd_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ISystemSupport_Interface__BASE__C,
    &xdc_runtime_SysStd_Module__FXNS__C.__sfxns,
    xdc_runtime_SysStd_abort__E,
    xdc_runtime_SysStd_exit__E,
    xdc_runtime_SysStd_flush__E,
    xdc_runtime_SysStd_putch__E,
    xdc_runtime_SysStd_ready__E,
    {
        NULL,
        NULL,
        NULL,
        0xd,
    }
}
Definition at line 838 of file dss_mrr_pe674.c.
Referenced by xdc_runtime_System_SupportProxy_Proxy__delegate__S().
xdc_runtime_SysStd_Module__gateObj__C
const __FAR__ CT__xdc_runtime_SysStd_Module__gateObj xdc_runtime_SysStd_Module__gateObj__C = ((CT__xdc_runtime_SysStd_Module__gateObj)0)
Definition at line 7895 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_SysStd_Module__gatePrms xdc_runtime_SysStd_Module__gatePrms__C = ((CT__xdc_runtime_SysStd_Module__gatePrms)0)
Definition at line 7899 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__id__C
const __FAR__ CT__xdc_runtime_SysStd_Module__id xdc_runtime_SysStd_Module__id__C = (xdc_Bits16)0xd
Definition at line 7903 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerDefined xdc_runtime_SysStd_Module__loggerDefined__C = 0
Definition at line 7907 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn0 xdc_runtime_SysStd_Module__loggerFxn0__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn0)0)
Definition at line 7915 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn1 xdc_runtime_SysStd_Module__loggerFxn1__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn1)0)
Definition at line 7919 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn2 xdc_runtime_SysStd_Module__loggerFxn2__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn2)0)
Definition at line 7923 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn4 xdc_runtime_SysStd_Module__loggerFxn4__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn4)0)
Definition at line 7927 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerFxn8 xdc_runtime_SysStd_Module__loggerFxn8__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn8)0)
Definition at line 7931 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_SysStd_Module__loggerObj xdc_runtime_SysStd_Module__loggerObj__C = ((CT__xdc_runtime_SysStd_Module__loggerObj)0)
Definition at line 7911 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Object__count__C
const __FAR__ CT__xdc_runtime_SysStd_Object__count xdc_runtime_SysStd_Object__count__C = 0
Definition at line 7935 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Object__heap__C
const __FAR__ CT__xdc_runtime_SysStd_Object__heap xdc_runtime_SysStd_Object__heap__C = 0
Definition at line 7939 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Object__sizeof__C
const __FAR__ CT__xdc_runtime_SysStd_Object__sizeof xdc_runtime_SysStd_Object__sizeof__C = 0
Definition at line 7943 of file dss_mrr_pe674.c.
xdc_runtime_SysStd_Object__table__C
const __FAR__ CT__xdc_runtime_SysStd_Object__table xdc_runtime_SysStd_Object__table__C = 0
Definition at line 7947 of file dss_mrr_pe674.c.
xdc_runtime_System_A_cannotFitIntoArg__C
const __FAR__ CT__xdc_runtime_System_A_cannotFitIntoArg xdc_runtime_System_A_cannotFitIntoArg__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 8040 of file dss_mrr_pe674.c.
xdc_runtime_System_abortFxn__C
const __FAR__ CT__xdc_runtime_System_abortFxn xdc_runtime_System_abortFxn__C = ((CT__xdc_runtime_System_abortFxn)((xdc_Fxn)xdc_runtime_System_abortStd__E))
Definition at line 8048 of file dss_mrr_pe674.c.
xdc_runtime_System_exitFxn__C
const __FAR__ CT__xdc_runtime_System_exitFxn xdc_runtime_System_exitFxn__C = ((CT__xdc_runtime_System_exitFxn)((xdc_Fxn)xdc_runtime_System_exitStd__E))
Definition at line 8052 of file dss_mrr_pe674.c.
xdc_runtime_System_extendFxn__C
const __FAR__ CT__xdc_runtime_System_extendFxn xdc_runtime_System_extendFxn__C = ((CT__xdc_runtime_System_extendFxn)((xdc_Fxn)xdc_runtime_System_printfExtend__I))
Definition at line 8056 of file dss_mrr_pe674.c.
xdc_runtime_System_maxAtexitHandlers__C
const __FAR__ CT__xdc_runtime_System_maxAtexitHandlers xdc_runtime_System_maxAtexitHandlers__C = (xdc_Int)0x0
Definition at line 8044 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_System_Module__diagsEnabled xdc_runtime_System_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7972 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_System_Module__diagsIncluded xdc_runtime_System_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7976 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_System_Module__diagsMask xdc_runtime_System_Module__diagsMask__C = ((CT__xdc_runtime_System_Module__diagsMask)0)
Definition at line 7980 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__gateObj__C
const __FAR__ CT__xdc_runtime_System_Module__gateObj xdc_runtime_System_Module__gateObj__C = ((CT__xdc_runtime_System_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 7984 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_System_Module__gatePrms xdc_runtime_System_Module__gatePrms__C = ((CT__xdc_runtime_System_Module__gatePrms)0)
Definition at line 7988 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__id__C
const __FAR__ CT__xdc_runtime_System_Module__id xdc_runtime_System_Module__id__C = (xdc_Bits16)0xc
Definition at line 7992 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_System_Module__loggerDefined xdc_runtime_System_Module__loggerDefined__C = 0
Definition at line 7996 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn0 xdc_runtime_System_Module__loggerFxn0__C = ((CT__xdc_runtime_System_Module__loggerFxn0)0)
Definition at line 8004 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn1 xdc_runtime_System_Module__loggerFxn1__C = ((CT__xdc_runtime_System_Module__loggerFxn1)0)
Definition at line 8008 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn2 xdc_runtime_System_Module__loggerFxn2__C = ((CT__xdc_runtime_System_Module__loggerFxn2)0)
Definition at line 8012 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn4 xdc_runtime_System_Module__loggerFxn4__C = ((CT__xdc_runtime_System_Module__loggerFxn4)0)
Definition at line 8016 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_System_Module__loggerFxn8 xdc_runtime_System_Module__loggerFxn8__C = ((CT__xdc_runtime_System_Module__loggerFxn8)0)
Definition at line 8020 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_System_Module__loggerObj xdc_runtime_System_Module__loggerObj__C = ((CT__xdc_runtime_System_Module__loggerObj)0)
Definition at line 8000 of file dss_mrr_pe674.c.
xdc_runtime_System_Module__state__V
xdc_runtime_System_Module_State__ xdc_runtime_System_Module__state__V
Initial value:
= {
    ((void*)0),
    (xdc_Int)0x0,
}
Definition at line 1879 of file dss_mrr_pe674.c.
xdc_runtime_System_Module_GateProxy_Module__root__V
xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__root__V
xdc_runtime_System_Object__count__C
const __FAR__ CT__xdc_runtime_System_Object__count xdc_runtime_System_Object__count__C = 0
Definition at line 8024 of file dss_mrr_pe674.c.
xdc_runtime_System_Object__heap__C
const __FAR__ CT__xdc_runtime_System_Object__heap xdc_runtime_System_Object__heap__C = 0
Definition at line 8028 of file dss_mrr_pe674.c.
xdc_runtime_System_Object__sizeof__C
const __FAR__ CT__xdc_runtime_System_Object__sizeof xdc_runtime_System_Object__sizeof__C = 0
Definition at line 8032 of file dss_mrr_pe674.c.
xdc_runtime_System_Object__table__C
const __FAR__ CT__xdc_runtime_System_Object__table xdc_runtime_System_Object__table__C = 0
Definition at line 8036 of file dss_mrr_pe674.c.
xdc_runtime_Text_charCnt__C
const __FAR__ CT__xdc_runtime_Text_charCnt xdc_runtime_Text_charCnt__C = (xdc_Int16)0x1
Definition at line 8198 of file dss_mrr_pe674.c.
xdc_runtime_Text_charTab__A
const __T1_xdc_runtime_Text_charTab xdc_runtime_Text_charTab__A
Initial value:
= {
    (xdc_Char)0x0,
}
Definition at line 1909 of file dss_mrr_pe674.c.
xdc_runtime_Text_charTab__C
const __FAR__ CT__xdc_runtime_Text_charTab xdc_runtime_Text_charTab__C = ((CT__xdc_runtime_Text_charTab)xdc_runtime_Text_charTab__A)
Definition at line 8190 of file dss_mrr_pe674.c.
xdc_runtime_Text_isLoaded__C
const __FAR__ CT__xdc_runtime_Text_isLoaded xdc_runtime_Text_isLoaded__C = 0
Definition at line 8186 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Text_Module__diagsEnabled xdc_runtime_Text_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 8106 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Text_Module__diagsIncluded xdc_runtime_Text_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 8110 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Text_Module__diagsMask xdc_runtime_Text_Module__diagsMask__C = ((CT__xdc_runtime_Text_Module__diagsMask)0)
Definition at line 8114 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Text_Module__gateObj xdc_runtime_Text_Module__gateObj__C = ((CT__xdc_runtime_Text_Module__gateObj)0)
Definition at line 8118 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Text_Module__gatePrms xdc_runtime_Text_Module__gatePrms__C = ((CT__xdc_runtime_Text_Module__gatePrms)0)
Definition at line 8122 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__id__C
const __FAR__ CT__xdc_runtime_Text_Module__id xdc_runtime_Text_Module__id__C = (xdc_Bits16)0xe
Definition at line 8126 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerDefined xdc_runtime_Text_Module__loggerDefined__C = 0
Definition at line 8130 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn0 xdc_runtime_Text_Module__loggerFxn0__C = ((CT__xdc_runtime_Text_Module__loggerFxn0)0)
Definition at line 8138 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn1 xdc_runtime_Text_Module__loggerFxn1__C = ((CT__xdc_runtime_Text_Module__loggerFxn1)0)
Definition at line 8142 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn2 xdc_runtime_Text_Module__loggerFxn2__C = ((CT__xdc_runtime_Text_Module__loggerFxn2)0)
Definition at line 8146 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn4 xdc_runtime_Text_Module__loggerFxn4__C = ((CT__xdc_runtime_Text_Module__loggerFxn4)0)
Definition at line 8150 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerFxn8 xdc_runtime_Text_Module__loggerFxn8__C = ((CT__xdc_runtime_Text_Module__loggerFxn8)0)
Definition at line 8154 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Text_Module__loggerObj xdc_runtime_Text_Module__loggerObj__C = ((CT__xdc_runtime_Text_Module__loggerObj)0)
Definition at line 8134 of file dss_mrr_pe674.c.
xdc_runtime_Text_Module__state__V
xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module__state__V
Initial value:
= {
    ((xdc_CPtr)(&xdc_runtime_Text_charTab__A[0])),
    ((xdc_CPtr)(&xdc_runtime_Text_nodeTab__A[0])),
}
Definition at line 1906 of file dss_mrr_pe674.c.
xdc_runtime_Text_nameEmpty__C
const __FAR__ CT__xdc_runtime_Text_nameEmpty xdc_runtime_Text_nameEmpty__C = "{empty-instance-name}"
Definition at line 8178 of file dss_mrr_pe674.c.
xdc_runtime_Text_nameStatic__C
const __FAR__ CT__xdc_runtime_Text_nameStatic xdc_runtime_Text_nameStatic__C = "{static-instance-name}"
Definition at line 8182 of file dss_mrr_pe674.c.
xdc_runtime_Text_nameUnknown__C
const __FAR__ CT__xdc_runtime_Text_nameUnknown xdc_runtime_Text_nameUnknown__C = "{unknown-instance-name}"
Definition at line 8174 of file dss_mrr_pe674.c.
xdc_runtime_Text_nodeCnt__C
const __FAR__ CT__xdc_runtime_Text_nodeCnt xdc_runtime_Text_nodeCnt__C = (xdc_Int16)0x1
Definition at line 8202 of file dss_mrr_pe674.c.
xdc_runtime_Text_nodeTab__A
const __T1_xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__A
Initial value:
= {
    {
        (xdc_Bits16)0x0,
        (xdc_Bits16)0x0,
    },
}
Definition at line 1912 of file dss_mrr_pe674.c.
xdc_runtime_Text_nodeTab__C
const __FAR__ CT__xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__C = ((CT__xdc_runtime_Text_nodeTab)xdc_runtime_Text_nodeTab__A)
Definition at line 8194 of file dss_mrr_pe674.c.
xdc_runtime_Text_Object__count__C
const __FAR__ CT__xdc_runtime_Text_Object__count xdc_runtime_Text_Object__count__C = 0
Definition at line 8158 of file dss_mrr_pe674.c.
xdc_runtime_Text_Object__heap__C
const __FAR__ CT__xdc_runtime_Text_Object__heap xdc_runtime_Text_Object__heap__C = 0
Definition at line 8162 of file dss_mrr_pe674.c.
xdc_runtime_Text_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Text_Object__sizeof xdc_runtime_Text_Object__sizeof__C = 0
Definition at line 8166 of file dss_mrr_pe674.c.
xdc_runtime_Text_Object__table__C
const __FAR__ CT__xdc_runtime_Text_Object__table xdc_runtime_Text_Object__table__C = 0
Definition at line 8170 of file dss_mrr_pe674.c.
xdc_runtime_Text_registryModsLastId__C
const __FAR__ CT__xdc_runtime_Text_registryModsLastId xdc_runtime_Text_registryModsLastId__C = (xdc_UInt16)0x7fff
Definition at line 8210 of file dss_mrr_pe674.c.
xdc_runtime_Text_unnamedModsLastId__C
const __FAR__ CT__xdc_runtime_Text_unnamedModsLastId xdc_runtime_Text_unnamedModsLastId__C = (xdc_UInt16)0x4000
Definition at line 8206 of file dss_mrr_pe674.c.
xdc_runtime_Text_visitRopeFxn2__C
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn2 xdc_runtime_Text_visitRopeFxn2__C = ((CT__xdc_runtime_Text_visitRopeFxn2)((xdc_Fxn)xdc_runtime_Text_visitRope2__I))
Definition at line 8218 of file dss_mrr_pe674.c.
xdc_runtime_Text_visitRopeFxn__C
const __FAR__ CT__xdc_runtime_Text_visitRopeFxn xdc_runtime_Text_visitRopeFxn__C = ((CT__xdc_runtime_Text_visitRopeFxn)((xdc_Fxn)xdc_runtime_Text_visitRope__I))
Definition at line 8214 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__diagsEnabled xdc_runtime_Timestamp_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 8227 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__diagsIncluded xdc_runtime_Timestamp_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 8231 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__diagsMask xdc_runtime_Timestamp_Module__diagsMask__C = ((CT__xdc_runtime_Timestamp_Module__diagsMask)0)
Definition at line 8235 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__FXNS__C
const xdc_runtime_Timestamp_Fxns__ xdc_runtime_Timestamp_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ITimestampClient_Interface__BASE__C,
    &xdc_runtime_Timestamp_Module__FXNS__C.__sfxns,
    xdc_runtime_Timestamp_get32__E,
    xdc_runtime_Timestamp_get64__E,
    xdc_runtime_Timestamp_getFreq__E,
    {
        NULL,
        NULL,
        NULL,
        0xf,
    }
}
Definition at line 861 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__gateObj__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__gateObj xdc_runtime_Timestamp_Module__gateObj__C = ((CT__xdc_runtime_Timestamp_Module__gateObj)0)
Definition at line 8239 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__gatePrms xdc_runtime_Timestamp_Module__gatePrms__C = ((CT__xdc_runtime_Timestamp_Module__gatePrms)0)
Definition at line 8243 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__id__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__id xdc_runtime_Timestamp_Module__id__C = (xdc_Bits16)0xf
Definition at line 8247 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerDefined xdc_runtime_Timestamp_Module__loggerDefined__C = 0
Definition at line 8251 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn0 xdc_runtime_Timestamp_Module__loggerFxn0__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn0)0)
Definition at line 8259 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn1 xdc_runtime_Timestamp_Module__loggerFxn1__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn1)0)
Definition at line 8263 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn2 xdc_runtime_Timestamp_Module__loggerFxn2__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn2)0)
Definition at line 8267 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn4 xdc_runtime_Timestamp_Module__loggerFxn4__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn4)0)
Definition at line 8271 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerFxn8 xdc_runtime_Timestamp_Module__loggerFxn8__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn8)0)
Definition at line 8275 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_Timestamp_Module__loggerObj xdc_runtime_Timestamp_Module__loggerObj__C = ((CT__xdc_runtime_Timestamp_Module__loggerObj)0)
Definition at line 8255 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Object__count__C
const __FAR__ CT__xdc_runtime_Timestamp_Object__count xdc_runtime_Timestamp_Object__count__C = 0
Definition at line 8279 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Object__heap__C
const __FAR__ CT__xdc_runtime_Timestamp_Object__heap xdc_runtime_Timestamp_Object__heap__C = 0
Definition at line 8283 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Object__sizeof__C
const __FAR__ CT__xdc_runtime_Timestamp_Object__sizeof xdc_runtime_Timestamp_Object__sizeof__C = 0
Definition at line 8287 of file dss_mrr_pe674.c.
xdc_runtime_Timestamp_Object__table__C
const __FAR__ CT__xdc_runtime_Timestamp_Object__table xdc_runtime_Timestamp_Object__table__C = 0
Definition at line 8291 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__diagsEnabled__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__diagsEnabled xdc_runtime_TimestampNull_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 8300 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__diagsIncluded__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__diagsIncluded xdc_runtime_TimestampNull_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 8304 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__diagsMask__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__diagsMask xdc_runtime_TimestampNull_Module__diagsMask__C = ((CT__xdc_runtime_TimestampNull_Module__diagsMask)0)
Definition at line 8308 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__FXNS__C
const xdc_runtime_TimestampNull_Fxns__ xdc_runtime_TimestampNull_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ITimestampProvider_Interface__BASE__C,
    &xdc_runtime_TimestampNull_Module__FXNS__C.__sfxns,
    xdc_runtime_TimestampNull_get32__E,
    xdc_runtime_TimestampNull_get64__E,
    xdc_runtime_TimestampNull_getFreq__E,
    {
        NULL,
        NULL,
        NULL,
        0x10,
    }
}
Definition at line 882 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__gateObj__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__gateObj xdc_runtime_TimestampNull_Module__gateObj__C = ((CT__xdc_runtime_TimestampNull_Module__gateObj)0)
Definition at line 8312 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__gatePrms__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__gatePrms xdc_runtime_TimestampNull_Module__gatePrms__C = ((CT__xdc_runtime_TimestampNull_Module__gatePrms)0)
Definition at line 8316 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__id__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__id xdc_runtime_TimestampNull_Module__id__C = (xdc_Bits16)0x10
Definition at line 8320 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerDefined__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerDefined xdc_runtime_TimestampNull_Module__loggerDefined__C = 0
Definition at line 8324 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerFxn0__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn0 xdc_runtime_TimestampNull_Module__loggerFxn0__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn0)0)
Definition at line 8332 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerFxn1__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn1 xdc_runtime_TimestampNull_Module__loggerFxn1__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn1)0)
Definition at line 8336 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerFxn2__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn2 xdc_runtime_TimestampNull_Module__loggerFxn2__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn2)0)
Definition at line 8340 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerFxn4__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn4 xdc_runtime_TimestampNull_Module__loggerFxn4__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn4)0)
Definition at line 8344 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerFxn8__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerFxn8 xdc_runtime_TimestampNull_Module__loggerFxn8__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn8)0)
Definition at line 8348 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Module__loggerObj__C
const __FAR__ CT__xdc_runtime_TimestampNull_Module__loggerObj xdc_runtime_TimestampNull_Module__loggerObj__C = ((CT__xdc_runtime_TimestampNull_Module__loggerObj)0)
Definition at line 8328 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Object__count__C
const __FAR__ CT__xdc_runtime_TimestampNull_Object__count xdc_runtime_TimestampNull_Object__count__C = 0
Definition at line 8352 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Object__heap__C
const __FAR__ CT__xdc_runtime_TimestampNull_Object__heap xdc_runtime_TimestampNull_Object__heap__C = 0
Definition at line 8356 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Object__sizeof__C
const __FAR__ CT__xdc_runtime_TimestampNull_Object__sizeof xdc_runtime_TimestampNull_Object__sizeof__C = 0
Definition at line 8360 of file dss_mrr_pe674.c.
xdc_runtime_TimestampNull_Object__table__C
const __FAR__ CT__xdc_runtime_TimestampNull_Object__table xdc_runtime_TimestampNull_Object__table__C = 0
Definition at line 8364 of file dss_mrr_pe674.c.