/**
 *  @file    reg_csi2protocolengine.h
 *
 *  @brief
 *    This file gives register definitions of CSI2_PROTOCOL_ENGINE module.
 *
 *  This file is auto-generated on 3/22/2017.
 *
 */

 /*
 *   (C) Copyright 2016, Texas Instruments Incorporated. - TI web address www.ti.com
 *---------------------------------------------------------------------------------------
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *    Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT  OWNER OR CONTRIBUTORS
 *  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *  CONTRACT,  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef REG_CSI2PROTOCOLENGINE_H
#define REG_CSI2PROTOCOLENGINE_H

/****************************************************************************************
 * INCLUDE FILES
 ****************************************************************************************/
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Definition for field REV in Register CSI2_REVISION */
#define CSI2_REVISION_REV_BIT_START                         0U
#define CSI2_REVISION_REV_BIT_END                           7U

/* Definition for field AUTO_IDLE in Register CSI2_SYSCONFIG */
#define CSI2_SYSCONFIG_AUTO_IDLE_BIT_START                  0U
#define CSI2_SYSCONFIG_AUTO_IDLE_BIT_END                    0U

/* Definition for field SOFT_RESET in Register CSI2_SYSCONFIG */
#define CSI2_SYSCONFIG_SOFT_RESET_BIT_START                 1U
#define CSI2_SYSCONFIG_SOFT_RESET_BIT_END                   1U

/* Definition for field SIDLEMODE in Register CSI2_SYSCONFIG */
#define CSI2_SYSCONFIG_SIDLEMODE_BIT_START                  3U
#define CSI2_SYSCONFIG_SIDLEMODE_BIT_END                    4U

/* Definition for field CLOCKACTIVITY in Register CSI2_SYSCONFIG */
#define CSI2_SYSCONFIG_CLOCKACTIVITY_BIT_START              8U
#define CSI2_SYSCONFIG_CLOCKACTIVITY_BIT_END                9U

/* Definition for field ENWAKEUP in Register CSI2_SYSCONFIG */
#define CSI2_SYSCONFIG_ENWAKEUP_BIT_START                   2U
#define CSI2_SYSCONFIG_ENWAKEUP_BIT_END                     2U

/* Definition for field RESET_DONE in Register CSI2_SYSSTATUS */
#define CSI2_SYSSTATUS_RESET_DONE_BIT_START                 0U
#define CSI2_SYSSTATUS_RESET_DONE_BIT_END                   0U

/* Definition for field VIRTUAL_CHANNEL0_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL0_IRQ_BIT_START       0U
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL0_IRQ_BIT_END         0U

/* Definition for field VIRTUAL_CHANNEL1_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL1_IRQ_BIT_START       1U
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL1_IRQ_BIT_END         1U

/* Definition for field VIRTUAL_CHANNEL2_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL2_IRQ_BIT_START       2U
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL2_IRQ_BIT_END         2U

/* Definition for field VIRTUAL_CHANNEL3_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL3_IRQ_BIT_START       3U
#define CSI2_IRQSTATUS_VIRTUAL_CHANNEL3_IRQ_BIT_END         3U

/* Definition for field COMPLEXIO_ERR_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_COMPLEXIO_ERR_IRQ_BIT_START          10U
#define CSI2_IRQSTATUS_COMPLEXIO_ERR_IRQ_BIT_END            10U

/* Definition for field PLL_LOCK_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_PLL_LOCK_IRQ_BIT_START               7U
#define CSI2_IRQSTATUS_PLL_LOCK_IRQ_BIT_END                 7U

/* Definition for field PLL_RECAL_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_PLL_RECAL_IRQ_BIT_START              9U
#define CSI2_IRQSTATUS_PLL_RECAL_IRQ_BIT_END                9U

/* Definition for field PLL_UNLOCK_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_PLL_UNLOCK_IRQ_BIT_START             8U
#define CSI2_IRQSTATUS_PLL_UNLOCK_IRQ_BIT_END               8U

/* Definition for field HS_TX_TO_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_HS_TX_TO_IRQ_BIT_START               14U
#define CSI2_IRQSTATUS_HS_TX_TO_IRQ_BIT_END                 14U

/* Definition for field LP_RX_TO_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_LP_RX_TO_IRQ_BIT_START               15U
#define CSI2_IRQSTATUS_LP_RX_TO_IRQ_BIT_END                 15U

/* Definition for field TE_TRIGGER_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_TE_TRIGGER_IRQ_BIT_START             16U
#define CSI2_IRQSTATUS_TE_TRIGGER_IRQ_BIT_END               16U

/* Definition for field RESYNCHRONIZATION_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_RESYNCHRONIZATION_IRQ_BIT_START      5U
#define CSI2_IRQSTATUS_RESYNCHRONIZATION_IRQ_BIT_END        5U

/* Definition for field WAKEUP_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_WAKEUP_IRQ_BIT_START                 4U
#define CSI2_IRQSTATUS_WAKEUP_IRQ_BIT_END                   4U

/* Definition for field ACK_TRIGGER_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_ACK_TRIGGER_IRQ_BIT_START            17U
#define CSI2_IRQSTATUS_ACK_TRIGGER_IRQ_BIT_END              17U

/* Definition for field SYNC_LOST_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_SYNC_LOST_IRQ_BIT_START              18U
#define CSI2_IRQSTATUS_SYNC_LOST_IRQ_BIT_END                18U

/* Definition for field LDO_POWER_GOOD_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_LDO_POWER_GOOD_IRQ_BIT_START         19U
#define CSI2_IRQSTATUS_LDO_POWER_GOOD_IRQ_BIT_END           19U

/* Definition for field TA_TO_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_TA_TO_IRQ_BIT_START                  20U
#define CSI2_IRQSTATUS_TA_TO_IRQ_BIT_END                    20U

/* Definition for field TE0_LINE_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_TE0_LINE_IRQ_BIT_START               21U
#define CSI2_IRQSTATUS_TE0_LINE_IRQ_BIT_END                 21U

/* Definition for field TE1_LINE_IRQ in Register CSI2_IRQSTATUS */
#define CSI2_IRQSTATUS_TE1_LINE_IRQ_BIT_START               22U
#define CSI2_IRQSTATUS_TE1_LINE_IRQ_BIT_END                 22U

/* Definition for field PLL_LOCK_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_PLL_LOCK_IRQ_EN_BIT_START            7U
#define CSI2_IRQENABLE_PLL_LOCK_IRQ_EN_BIT_END              7U

/* Definition for field PLL_UNLOCK_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_PLL_UNLOCK_IRQ_EN_BIT_START          8U
#define CSI2_IRQENABLE_PLL_UNLOCK_IRQ_EN_BIT_END            8U

/* Definition for field PLL_RECAL_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_PLL_RECAL_IRQ_EN_BIT_START           9U
#define CSI2_IRQENABLE_PLL_RECAL_IRQ_EN_BIT_END             9U

/* Definition for field HS_TX_TO_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_HS_TX_TO_IRQ_EN_BIT_START            14U
#define CSI2_IRQENABLE_HS_TX_TO_IRQ_EN_BIT_END              14U

/* Definition for field LP_RX_TO_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_LP_RX_TO_IRQ_EN_BIT_START            15U
#define CSI2_IRQENABLE_LP_RX_TO_IRQ_EN_BIT_END              15U

/* Definition for field TE_TRIGGER_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_TE_TRIGGER_IRQ_EN_BIT_START          16U
#define CSI2_IRQENABLE_TE_TRIGGER_IRQ_EN_BIT_END            16U

/* Definition for field RESYNCHRONIZATION_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_RESYNCHRONIZATION_IRQ_EN_BIT_START   5U
#define CSI2_IRQENABLE_RESYNCHRONIZATION_IRQ_EN_BIT_END     5U

/* Definition for field WAKEUP_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_WAKEUP_IRQ_EN_BIT_START              4U
#define CSI2_IRQENABLE_WAKEUP_IRQ_EN_BIT_END                4U

/* Definition for field ACK_TRIGGER_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_ACK_TRIGGER_IRQ_EN_BIT_START         17U
#define CSI2_IRQENABLE_ACK_TRIGGER_IRQ_EN_BIT_END           17U

/* Definition for field SYNC_LOST_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_SYNC_LOST_IRQ_EN_BIT_START           18U
#define CSI2_IRQENABLE_SYNC_LOST_IRQ_EN_BIT_END             18U

/* Definition for field LDO_POWER_GOOD_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_LDO_POWER_GOOD_IRQ_EN_BIT_START      19U
#define CSI2_IRQENABLE_LDO_POWER_GOOD_IRQ_EN_BIT_END        19U

/* Definition for field TA_TO_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_TA_TO_IRQ_EN_BIT_START               20U
#define CSI2_IRQENABLE_TA_TO_IRQ_EN_BIT_END                 20U

/* Definition for field TE0_LINE_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_TE0_LINE_IRQ_EN_BIT_START            21U
#define CSI2_IRQENABLE_TE0_LINE_IRQ_EN_BIT_END              21U

/* Definition for field TE1_LINE_IRQ_EN in Register CSI2_IRQENABLE */
#define CSI2_IRQENABLE_TE1_LINE_IRQ_EN_BIT_START            22U
#define CSI2_IRQENABLE_TE1_LINE_IRQ_EN_BIT_END              22U

/* Definition for field IF_EN in Register CSI2_CTRL */
#define CSI2_CTRL_IF_EN_BIT_START                           0U
#define CSI2_CTRL_IF_EN_BIT_END                             0U

/* Definition for field VP_CLK_POL in Register CSI2_CTRL */
#define CSI2_CTRL_VP_CLK_POL_BIT_START                      8U
#define CSI2_CTRL_VP_CLK_POL_BIT_END                        8U

/* Definition for field ECC_RX_EN in Register CSI2_CTRL */
#define CSI2_CTRL_ECC_RX_EN_BIT_START                       2U
#define CSI2_CTRL_ECC_RX_EN_BIT_END                         2U

/* Definition for field VP_HSYNC_POL in Register CSI2_CTRL */
#define CSI2_CTRL_VP_HSYNC_POL_BIT_START                    10U
#define CSI2_CTRL_VP_HSYNC_POL_BIT_END                      10U

/* Definition for field VP_VSYNC_POL in Register CSI2_CTRL */
#define CSI2_CTRL_VP_VSYNC_POL_BIT_START                    11U
#define CSI2_CTRL_VP_VSYNC_POL_BIT_END                      11U

/* Definition for field CS_RX_EN in Register CSI2_CTRL */
#define CSI2_CTRL_CS_RX_EN_BIT_START                        1U
#define CSI2_CTRL_CS_RX_EN_BIT_END                          1U

/* Definition for field VP_DE_POL in Register CSI2_CTRL */
#define CSI2_CTRL_VP_DE_POL_BIT_START                       9U
#define CSI2_CTRL_VP_DE_POL_BIT_END                         9U

/* Definition for field VP_VSYNC_START in Register CSI2_CTRL */
#define CSI2_CTRL_VP_VSYNC_START_BIT_START                  15U
#define CSI2_CTRL_VP_VSYNC_START_BIT_END                    15U

/* Definition for field VP_VSYNC_END in Register CSI2_CTRL */
#define CSI2_CTRL_VP_VSYNC_END_BIT_START                    16U
#define CSI2_CTRL_VP_VSYNC_END_BIT_END                      16U

/* Definition for field VP_HSYNC_START in Register CSI2_CTRL */
#define CSI2_CTRL_VP_HSYNC_START_BIT_START                  17U
#define CSI2_CTRL_VP_HSYNC_START_BIT_END                    17U

/* Definition for field VP_HSYNC_END in Register CSI2_CTRL */
#define CSI2_CTRL_VP_HSYNC_END_BIT_START                    18U
#define CSI2_CTRL_VP_HSYNC_END_BIT_END                      18U

/* Definition for field VP_CLK_RATIO in Register CSI2_CTRL */
#define CSI2_CTRL_VP_CLK_RATIO_BIT_START                    4U
#define CSI2_CTRL_VP_CLK_RATIO_BIT_END                      4U

/* Definition for field EOT_ENABLE in Register CSI2_CTRL */
#define CSI2_CTRL_EOT_ENABLE_BIT_START                      19U
#define CSI2_CTRL_EOT_ENABLE_BIT_END                        19U

/* Definition for field LINE_BUFFER in Register CSI2_CTRL */
#define CSI2_CTRL_LINE_BUFFER_BIT_START                     12U
#define CSI2_CTRL_LINE_BUFFER_BIT_END                       13U

/* Definition for field VP_DATA_BUS_WIDTH in Register CSI2_CTRL */
#define CSI2_CTRL_VP_DATA_BUS_WIDTH_BIT_START               6U
#define CSI2_CTRL_VP_DATA_BUS_WIDTH_BIT_END                 7U

/* Definition for field TX_FIFO_ARBITRATION in Register CSI2_CTRL */
#define CSI2_CTRL_TX_FIFO_ARBITRATION_BIT_START             3U
#define CSI2_CTRL_TX_FIFO_ARBITRATION_BIT_END               3U

/* Definition for field TRIGGER_RESET in Register CSI2_CTRL */
#define CSI2_CTRL_TRIGGER_RESET_BIT_START                   5U
#define CSI2_CTRL_TRIGGER_RESET_BIT_END                     5U

/* Definition for field BLANKING_MODE in Register CSI2_CTRL */
#define CSI2_CTRL_BLANKING_MODE_BIT_START                   20U
#define CSI2_CTRL_BLANKING_MODE_BIT_END                     20U

/* Definition for field TRIGGER_RESET_MODE in Register CSI2_CTRL */
#define CSI2_CTRL_TRIGGER_RESET_MODE_BIT_START              14U
#define CSI2_CTRL_TRIGGER_RESET_MODE_BIT_END                14U

/* Definition for field HFP_BLANKING_MODE in Register CSI2_CTRL */
#define CSI2_CTRL_HFP_BLANKING_MODE_BIT_START               21U
#define CSI2_CTRL_HFP_BLANKING_MODE_BIT_END                 21U

/* Definition for field HBP_BLANKING_MODE in Register CSI2_CTRL */
#define CSI2_CTRL_HBP_BLANKING_MODE_BIT_START               22U
#define CSI2_CTRL_HBP_BLANKING_MODE_BIT_END                 22U

/* Definition for field HSA_BLANKING_MODE in Register CSI2_CTRL */
#define CSI2_CTRL_HSA_BLANKING_MODE_BIT_START               23U
#define CSI2_CTRL_HSA_BLANKING_MODE_BIT_END                 23U

/* Definition for field DISPC_UPDATE_SYNC in Register CSI2_CTRL */
#define CSI2_CTRL_DISPC_UPDATE_SYNC_BIT_START               24U
#define CSI2_CTRL_DISPC_UPDATE_SYNC_BIT_END                 24U

/* Definition for field TX_FIFODEPTH in Register CSI2_GNQ */
#define CSI2_GNQ_TX_FIFODEPTH_BIT_START                     0U
#define CSI2_GNQ_TX_FIFODEPTH_BIT_END                       2U

/* Definition for field RX_FIFODEPTH in Register CSI2_GNQ */
#define CSI2_GNQ_RX_FIFODEPTH_BIT_START                     3U
#define CSI2_GNQ_RX_FIFODEPTH_BIT_END                       5U

/* Definition for field NB_DMA_REQUEST in Register CSI2_GNQ */
#define CSI2_GNQ_NB_DMA_REQUEST_BIT_START                   6U
#define CSI2_GNQ_NB_DMA_REQUEST_BIT_END                     8U

/* Definition for field NB_DATA_LANES in Register CSI2_GNQ */
#define CSI2_GNQ_NB_DATA_LANES_BIT_START                    9U
#define CSI2_GNQ_NB_DATA_LANES_BIT_END                      11U

/* Definition for field VP1_LINE_BUFFER_SIZE in Register CSI2_GNQ */
#define CSI2_GNQ_VP1_LINE_BUFFER_SIZE_BIT_START             12U
#define CSI2_GNQ_VP1_LINE_BUFFER_SIZE_BIT_END               14U

/* Definition for field VP1_NB_LINE_BUFFER in Register CSI2_GNQ */
#define CSI2_GNQ_VP1_NB_LINE_BUFFER_BIT_START               16U
#define CSI2_GNQ_VP1_NB_LINE_BUFFER_BIT_END                 17U

/* Definition for field VP2_LINE_BUFFER_SIZE in Register CSI2_GNQ */
#define CSI2_GNQ_VP2_LINE_BUFFER_SIZE_BIT_START             18U
#define CSI2_GNQ_VP2_LINE_BUFFER_SIZE_BIT_END               20U

/* Definition for field VP2_NB_LINE_BUFFER in Register CSI2_GNQ */
#define CSI2_GNQ_VP2_NB_LINE_BUFFER_BIT_START               22U
#define CSI2_GNQ_VP2_NB_LINE_BUFFER_BIT_END                 23U

/* Definition for field NB_VIDEO_PORTS in Register CSI2_GNQ */
#define CSI2_GNQ_NB_VIDEO_PORTS_BIT_START                   24U
#define CSI2_GNQ_NB_VIDEO_PORTS_BIT_END                     24U

/* Definition for field CLOCK_POSITION in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_CLOCK_POSITION_BIT_START        0U
#define CSI2_COMPLEXIO_CFG1_CLOCK_POSITION_BIT_END          2U

/* Definition for field DATA1_POL in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA1_POL_BIT_START             7U
#define CSI2_COMPLEXIO_CFG1_DATA1_POL_BIT_END               7U

/* Definition for field DATA2_POSITION in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA2_POSITION_BIT_START        8U
#define CSI2_COMPLEXIO_CFG1_DATA2_POSITION_BIT_END          8U

/* Definition for field DATA4_POSITION in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA4_POSITION_BIT_START        16U
#define CSI2_COMPLEXIO_CFG1_DATA4_POSITION_BIT_END          16U

/* Definition for field DATA2_POL in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA2_POL_BIT_START             11U
#define CSI2_COMPLEXIO_CFG1_DATA2_POL_BIT_END               11U

/* Definition for field DATA3_POSITION in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA3_POSITION_BIT_START        12U
#define CSI2_COMPLEXIO_CFG1_DATA3_POSITION_BIT_END          12U

/* Definition for field DATA1_POSITION in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA1_POSITION_BIT_START        4U
#define CSI2_COMPLEXIO_CFG1_DATA1_POSITION_BIT_END          6U

/* Definition for field CLOCK_POL in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_CLOCK_POL_BIT_START             3U
#define CSI2_COMPLEXIO_CFG1_CLOCK_POL_BIT_END               3U

/* Definition for field DATA4_POL in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA4_POL_BIT_START             19U
#define CSI2_COMPLEXIO_CFG1_DATA4_POL_BIT_END               19U

/* Definition for field DATA3_POL in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_DATA3_POL_BIT_START             15U
#define CSI2_COMPLEXIO_CFG1_DATA3_POL_BIT_END               15U

/* Definition for field PWR_CMD in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_PWR_CMD_BIT_START               27U
#define CSI2_COMPLEXIO_CFG1_PWR_CMD_BIT_END                 28U

/* Definition for field PWR_STATUS in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_PWR_STATUS_BIT_START            25U
#define CSI2_COMPLEXIO_CFG1_PWR_STATUS_BIT_END              26U

/* Definition for field GOBIT in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_GOBIT_BIT_START                 30U
#define CSI2_COMPLEXIO_CFG1_GOBIT_BIT_END                   30U

/* Definition for field RESET_DONE in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_RESET_DONE_BIT_START            29U
#define CSI2_COMPLEXIO_CFG1_RESET_DONE_BIT_END              29U

/* Definition for field SHADOWING in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_SHADOWING_BIT_START             31U
#define CSI2_COMPLEXIO_CFG1_SHADOWING_BIT_END               31U

/* Definition for field USE_LDO_EXTERNAL in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_USE_LDO_EXTERNAL_BIT_START      20U
#define CSI2_COMPLEXIO_CFG1_USE_LDO_EXTERNAL_BIT_END        20U

/* Definition for field LDO_POWER_GOOD_STATE in Register CSI2_COMPLEXIO_CFG1 */
#define CSI2_COMPLEXIO_CFG1_LDO_POWER_GOOD_STATE_BIT_START  21U
#define CSI2_COMPLEXIO_CFG1_LDO_POWER_GOOD_STATE_BIT_END    21U

/* Definition for field ERRSYNCESC4_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC4_IRQ_BIT_START  3U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC4_IRQ_BIT_END    3U

/* Definition for field ERRSYNCESC2_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC2_IRQ_BIT_START  1U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC2_IRQ_BIT_END    1U

/* Definition for field ERRSYNCESC5_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC5_IRQ_BIT_START  4U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC5_IRQ_BIT_END    4U

/* Definition for field ERRSYNCESC1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC1_IRQ_BIT_START  0U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC1_IRQ_BIT_END    0U

/* Definition for field ERRSYNCESC3_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC3_IRQ_BIT_START  2U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRSYNCESC3_IRQ_BIT_END    2U

/* Definition for field ERRESC1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC1_IRQ_BIT_START      5U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC1_IRQ_BIT_END        5U

/* Definition for field ERRESC2_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC2_IRQ_BIT_START      6U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC2_IRQ_BIT_END        6U

/* Definition for field ERRESC3_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC3_IRQ_BIT_START      7U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC3_IRQ_BIT_END        7U

/* Definition for field ERRESC4_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC4_IRQ_BIT_START      8U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC4_IRQ_BIT_END        8U

/* Definition for field ERRESC5_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC5_IRQ_BIT_START      9U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRESC5_IRQ_BIT_END        9U

/* Definition for field ERRCONTROL1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL1_IRQ_BIT_START  10U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL1_IRQ_BIT_END    10U

/* Definition for field ERRCONTROL2_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL2_IRQ_BIT_START  11U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL2_IRQ_BIT_END    11U

/* Definition for field ERRCONTROL3_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL3_IRQ_BIT_START  12U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL3_IRQ_BIT_END    12U

/* Definition for field ERRCONTROL4_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL4_IRQ_BIT_START  13U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL4_IRQ_BIT_END    13U

/* Definition for field ERRCONTROL5_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL5_IRQ_BIT_START  14U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTROL5_IRQ_BIT_END    14U

/* Definition for field STATEULPS1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS1_IRQ_BIT_START   15U
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS1_IRQ_BIT_END     15U

/* Definition for field STATEULPS4_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS4_IRQ_BIT_START   18U
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS4_IRQ_BIT_END     18U

/* Definition for field STATEULPS3_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS3_IRQ_BIT_START   17U
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS3_IRQ_BIT_END     17U

/* Definition for field STATEULPS2_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS2_IRQ_BIT_START   16U
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS2_IRQ_BIT_END     16U

/* Definition for field STATEULPS5_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS5_IRQ_BIT_START   19U
#define CSI2_COMPLEXIO_IRQSTATUS_STATEULPS5_IRQ_BIT_END     19U

/* Definition for field ERRCONTENTIONLP0_1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_1_IRQ_BIT_START 20U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_1_IRQ_BIT_END 20U

/* Definition for field ERRCONTENTIONLP1_1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_1_IRQ_BIT_START 21U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_1_IRQ_BIT_END 21U

/* Definition for field ERRCONTENTIONLP0_2_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_2_IRQ_BIT_START 22U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_2_IRQ_BIT_END 22U

/* Definition for field ERRCONTENTIONLP1_2_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_2_IRQ_BIT_START 23U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_2_IRQ_BIT_END 23U

/* Definition for field ERRCONTENTIONLP0_3_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_3_IRQ_BIT_START 24U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_3_IRQ_BIT_END 24U

/* Definition for field ERRCONTENTIONLP1_3_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_3_IRQ_BIT_START 25U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_3_IRQ_BIT_END 25U

/* Definition for field ERRCONTENTIONLP0_4_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_4_IRQ_BIT_START 26U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_4_IRQ_BIT_END 26U

/* Definition for field ERRCONTENTIONLP1_4_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_4_IRQ_BIT_START 27U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_4_IRQ_BIT_END 27U

/* Definition for field ERRCONTENTIONLP0_5_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_5_IRQ_BIT_START 28U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP0_5_IRQ_BIT_END 28U

/* Definition for field ERRCONTENTIONLP1_5_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_5_IRQ_BIT_START 29U
#define CSI2_COMPLEXIO_IRQSTATUS_ERRCONTENTIONLP1_5_IRQ_BIT_END 29U

/* Definition for field ULPSACTIVENOT_ALL0_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ULPSACTIVENOT_ALL0_IRQ_BIT_START 30U
#define CSI2_COMPLEXIO_IRQSTATUS_ULPSACTIVENOT_ALL0_IRQ_BIT_END 30U

/* Definition for field ULPSACTIVENOT_ALL1_IRQ in Register CSI2_COMPLEXIO_IRQSTATUS */
#define CSI2_COMPLEXIO_IRQSTATUS_ULPSACTIVENOT_ALL1_IRQ_BIT_START 31U
#define CSI2_COMPLEXIO_IRQSTATUS_ULPSACTIVENOT_ALL1_IRQ_BIT_END 31U

/* Definition for field ERRESC3_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC3_IRQ_EN_BIT_START   7U
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC3_IRQ_EN_BIT_END     7U

/* Definition for field ERRCONTENTIONLP1_1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_1_IRQ_EN_BIT_START 21U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_1_IRQ_EN_BIT_END 21U

/* Definition for field ERRESC1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC1_IRQ_EN_BIT_START   5U
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC1_IRQ_EN_BIT_END     5U

/* Definition for field ERRSYNCSESC3_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC3_IRQ_EN_BIT_START 2U
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC3_IRQ_EN_BIT_END 2U

/* Definition for field ERRESC4_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC4_IRQ_EN_BIT_START   8U
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC4_IRQ_EN_BIT_END     8U

/* Definition for field ERRCONTROL2_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL2_IRQ_EN_BIT_START 11U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL2_IRQ_EN_BIT_END 11U

/* Definition for field ERRESC5_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC5_IRQ_EN_BIT_START   9U
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC5_IRQ_EN_BIT_END     9U

/* Definition for field ERRCONTROL5_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL5_IRQ_EN_BIT_START 14U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL5_IRQ_EN_BIT_END 14U

/* Definition for field ERRESC2_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC2_IRQ_EN_BIT_START   6U
#define CSI2_COMPLEXIO_IRQENABLE_ERRESC2_IRQ_EN_BIT_END     6U

/* Definition for field ERRSYNCSESC1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC1_IRQ_EN_BIT_START 0U
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC1_IRQ_EN_BIT_END 0U

/* Definition for field ERRSYNCSESC4_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC4_IRQ_EN_BIT_START 3U
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC4_IRQ_EN_BIT_END 3U

/* Definition for field ERRCONTENTIONLP0_1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_1_IRQ_EN_BIT_START 20U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_1_IRQ_EN_BIT_END 20U

/* Definition for field ERRSYNCSESC5_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC5_IRQ_EN_BIT_START 4U
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC5_IRQ_EN_BIT_END 4U

/* Definition for field ERRCONTROL3_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL3_IRQ_EN_BIT_START 12U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL3_IRQ_EN_BIT_END 12U

/* Definition for field ERRCONTROL1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL1_IRQ_EN_BIT_START 10U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL1_IRQ_EN_BIT_END 10U

/* Definition for field ERRCONTROL4_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL4_IRQ_EN_BIT_START 13U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTROL4_IRQ_EN_BIT_END 13U

/* Definition for field ERRSYNCSESC2_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC2_IRQ_EN_BIT_START 1U
#define CSI2_COMPLEXIO_IRQENABLE_ERRSYNCSESC2_IRQ_EN_BIT_END 1U

/* Definition for field STATEULPS1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS1_IRQ_EN_BIT_START 15U
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS1_IRQ_EN_BIT_END  15U

/* Definition for field STATEULPS2_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS2_IRQ_EN_BIT_START 16U
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS2_IRQ_EN_BIT_END  16U

/* Definition for field STATEULPS3_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS3_IRQ_EN_BIT_START 17U
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS3_IRQ_EN_BIT_END  17U

/* Definition for field STATEULPS4_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS4_IRQ_EN_BIT_START 18U
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS4_IRQ_EN_BIT_END  18U

/* Definition for field STATEULPS5_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS5_IRQ_EN_BIT_START 19U
#define CSI2_COMPLEXIO_IRQENABLE_STATEULPS5_IRQ_EN_BIT_END  19U

/* Definition for field ERRCONTENTIONLP1_2_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_2_IRQ_EN_BIT_START 23U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_2_IRQ_EN_BIT_END 23U

/* Definition for field ERRCONTENTIONLP0_2_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_2_IRQ_EN_BIT_START 22U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_2_IRQ_EN_BIT_END 22U

/* Definition for field ERRCONTENTIONLP1_3_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_3_IRQ_EN_BIT_START 25U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_3_IRQ_EN_BIT_END 25U

/* Definition for field ERRCONTENTIONLP0_3_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_3_IRQ_EN_BIT_START 24U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_3_IRQ_EN_BIT_END 24U

/* Definition for field ERRCONTENTIONLP0_4_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_4_IRQ_EN_BIT_START 26U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_4_IRQ_EN_BIT_END 26U

/* Definition for field ERRCONTENTIONLP1_4_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_4_IRQ_EN_BIT_START 27U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_4_IRQ_EN_BIT_END 27U

/* Definition for field ERRCONTENTIONLP0_5_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_5_IRQ_EN_BIT_START 28U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP0_5_IRQ_EN_BIT_END 28U

/* Definition for field ULPSACTIVENOT_ALL0_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ULPSACTIVENOT_ALL0_IRQ_EN_BIT_START 30U
#define CSI2_COMPLEXIO_IRQENABLE_ULPSACTIVENOT_ALL0_IRQ_EN_BIT_END 30U

/* Definition for field ULPSACTIVENOT_ALL1_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ULPSACTIVENOT_ALL1_IRQ_EN_BIT_START 31U
#define CSI2_COMPLEXIO_IRQENABLE_ULPSACTIVENOT_ALL1_IRQ_EN_BIT_END 31U

/* Definition for field ERRCONTENTIONLP1_5_IRQ_EN in Register CSI2_COMPLEXIO_IRQENABLE */
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_5_IRQ_EN_BIT_START 29U
#define CSI2_COMPLEXIO_IRQENABLE_ERRCONTENTIONLP1_5_IRQ_EN_BIT_END 29U

/* Definition for field LP_CLK_NULL_PACKET_ENABLE in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_LP_CLK_NULL_PACKET_ENABLE_BIT_START   15U
#define CSI2_CLK_CTRL_LP_CLK_NULL_PACKET_ENABLE_BIT_END     15U

/* Definition for field LP_CLK_DIVISOR in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_LP_CLK_DIVISOR_BIT_START              0U
#define CSI2_CLK_CTRL_LP_CLK_DIVISOR_BIT_END                12U

/* Definition for field DDR_CLK_ALWAYS_ON in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_DDR_CLK_ALWAYS_ON_BIT_START           13U
#define CSI2_CLK_CTRL_DDR_CLK_ALWAYS_ON_BIT_END             13U

/* Definition for field PLL_PWR_CMD in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_PLL_PWR_CMD_BIT_START                 30U
#define CSI2_CLK_CTRL_PLL_PWR_CMD_BIT_END                   31U

/* Definition for field PLL_PWR_STATUS in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_PLL_PWR_STATUS_BIT_START              28U
#define CSI2_CLK_CTRL_PLL_PWR_STATUS_BIT_END                29U

/* Definition for field CIO_CLK_ICG in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_CIO_CLK_ICG_BIT_START                 14U
#define CSI2_CLK_CTRL_CIO_CLK_ICG_BIT_END                   14U

/* Definition for field LP_CLK_NULL_PACKET_SIZE in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_LP_CLK_NULL_PACKET_SIZE_BIT_START     16U
#define CSI2_CLK_CTRL_LP_CLK_NULL_PACKET_SIZE_BIT_END       17U

/* Definition for field HS_AUTO_STOP_ENABLE in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_HS_AUTO_STOP_ENABLE_BIT_START         18U
#define CSI2_CLK_CTRL_HS_AUTO_STOP_ENABLE_BIT_END           18U

/* Definition for field HS_MANUAL_STOP_CTRL in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_HS_MANUAL_STOP_CTRL_BIT_START         19U
#define CSI2_CLK_CTRL_HS_MANUAL_STOP_CTRL_BIT_END           19U

/* Definition for field LP_CLK_ENABLE in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_LP_CLK_ENABLE_BIT_START               20U
#define CSI2_CLK_CTRL_LP_CLK_ENABLE_BIT_END                 20U

/* Definition for field LP_RX_SYNCHRO_ENABLE in Register CSI2_CLK_CTRL */
#define CSI2_CLK_CTRL_LP_RX_SYNCHRO_ENABLE_BIT_START        21U
#define CSI2_CLK_CTRL_LP_RX_SYNCHRO_ENABLE_BIT_END          21U

/* Definition for field STOP_STATE_COUNTER_IO in Register CSI2_TIMING1 */
#define CSI2_TIMING1_STOP_STATE_COUNTER_IO_BIT_START        0U
#define CSI2_TIMING1_STOP_STATE_COUNTER_IO_BIT_END          12U

/* Definition for field STOP_STATE_X4_IO in Register CSI2_TIMING1 */
#define CSI2_TIMING1_STOP_STATE_X4_IO_BIT_START             13U
#define CSI2_TIMING1_STOP_STATE_X4_IO_BIT_END               13U

/* Definition for field STOP_STATE_X16_IO in Register CSI2_TIMING1 */
#define CSI2_TIMING1_STOP_STATE_X16_IO_BIT_START            14U
#define CSI2_TIMING1_STOP_STATE_X16_IO_BIT_END              14U

/* Definition for field FORCE_TX_STOP_MODE_IO in Register CSI2_TIMING1 */
#define CSI2_TIMING1_FORCE_TX_STOP_MODE_IO_BIT_START        15U
#define CSI2_TIMING1_FORCE_TX_STOP_MODE_IO_BIT_END          15U

/* Definition for field TA_TO in Register CSI2_TIMING1 */
#define CSI2_TIMING1_TA_TO_BIT_START                        31U
#define CSI2_TIMING1_TA_TO_BIT_END                          31U

/* Definition for field TA_TO_X16 in Register CSI2_TIMING1 */
#define CSI2_TIMING1_TA_TO_X16_BIT_START                    30U
#define CSI2_TIMING1_TA_TO_X16_BIT_END                      30U

/* Definition for field TA_TO_X8 in Register CSI2_TIMING1 */
#define CSI2_TIMING1_TA_TO_X8_BIT_START                     29U
#define CSI2_TIMING1_TA_TO_X8_BIT_END                       29U

/* Definition for field TA_TO_COUNTER in Register CSI2_TIMING1 */
#define CSI2_TIMING1_TA_TO_COUNTER_BIT_START                16U
#define CSI2_TIMING1_TA_TO_COUNTER_BIT_END                  28U

/* Definition for field HS_TX_TO_X16 in Register CSI2_TIMING2 */
#define CSI2_TIMING2_HS_TX_TO_X16_BIT_START                 29U
#define CSI2_TIMING2_HS_TX_TO_X16_BIT_END                   29U

/* Definition for field HS_TX_TO in Register CSI2_TIMING2 */
#define CSI2_TIMING2_HS_TX_TO_BIT_START                     31U
#define CSI2_TIMING2_HS_TX_TO_BIT_END                       31U

/* Definition for field HS_TX_TO_COUNTER in Register CSI2_TIMING2 */
#define CSI2_TIMING2_HS_TX_TO_COUNTER_BIT_START             16U
#define CSI2_TIMING2_HS_TX_TO_COUNTER_BIT_END               28U

/* Definition for field HS_TX_TO_X64 in Register CSI2_TIMING2 */
#define CSI2_TIMING2_HS_TX_TO_X64_BIT_START                 30U
#define CSI2_TIMING2_HS_TX_TO_X64_BIT_END                   30U

/* Definition for field LP_RX_TO in Register CSI2_TIMING2 */
#define CSI2_TIMING2_LP_RX_TO_BIT_START                     15U
#define CSI2_TIMING2_LP_RX_TO_BIT_END                       15U

/* Definition for field LP_RX_TO_COUNTER in Register CSI2_TIMING2 */
#define CSI2_TIMING2_LP_RX_TO_COUNTER_BIT_START             0U
#define CSI2_TIMING2_LP_RX_TO_COUNTER_BIT_END               12U

/* Definition for field LP_RX_TO_X16 in Register CSI2_TIMING2 */
#define CSI2_TIMING2_LP_RX_TO_X16_BIT_START                 14U
#define CSI2_TIMING2_LP_RX_TO_X16_BIT_END                   14U

/* Definition for field LP_RX_TO_X4 in Register CSI2_TIMING2 */
#define CSI2_TIMING2_LP_RX_TO_X4_BIT_START                  13U
#define CSI2_TIMING2_LP_RX_TO_X4_BIT_END                    13U

/* Definition for field HBP in Register CSI2_VM_TIMING1 */
#define CSI2_VM_TIMING1_HBP_BIT_START                       0U
#define CSI2_VM_TIMING1_HBP_BIT_END                         11U

/* Definition for field HFP in Register CSI2_VM_TIMING1 */
#define CSI2_VM_TIMING1_HFP_BIT_START                       12U
#define CSI2_VM_TIMING1_HFP_BIT_END                         23U

/* Definition for field HSA in Register CSI2_VM_TIMING1 */
#define CSI2_VM_TIMING1_HSA_BIT_START                       24U
#define CSI2_VM_TIMING1_HSA_BIT_END                         31U

/* Definition for field VBP in Register CSI2_VM_TIMING2 */
#define CSI2_VM_TIMING2_VBP_BIT_START                       0U
#define CSI2_VM_TIMING2_VBP_BIT_END                         7U

/* Definition for field VFP in Register CSI2_VM_TIMING2 */
#define CSI2_VM_TIMING2_VFP_BIT_START                       8U
#define CSI2_VM_TIMING2_VFP_BIT_END                         15U

/* Definition for field VSA in Register CSI2_VM_TIMING2 */
#define CSI2_VM_TIMING2_VSA_BIT_START                       16U
#define CSI2_VM_TIMING2_VSA_BIT_END                         23U

/* Definition for field WINDOW_SYNC in Register CSI2_VM_TIMING2 */
#define CSI2_VM_TIMING2_WINDOW_SYNC_BIT_START               24U
#define CSI2_VM_TIMING2_WINDOW_SYNC_BIT_END                 27U

/* Definition for field VACT in Register CSI2_VM_TIMING3 */
#define CSI2_VM_TIMING3_VACT_BIT_START                      0U
#define CSI2_VM_TIMING3_VACT_BIT_END                        15U

/* Definition for field TL in Register CSI2_VM_TIMING3 */
#define CSI2_VM_TIMING3_TL_BIT_START                        16U
#define CSI2_VM_TIMING3_TL_BIT_END                          31U

/* Definition for field DDR_CLK_POST in Register CSI2_CLK_TIMING */
#define CSI2_CLK_TIMING_DDR_CLK_POST_BIT_START              0U
#define CSI2_CLK_TIMING_DDR_CLK_POST_BIT_END                7U

/* Definition for field DDR_CLK_PRE in Register CSI2_CLK_TIMING */
#define CSI2_CLK_TIMING_DDR_CLK_PRE_BIT_START               8U
#define CSI2_CLK_TIMING_DDR_CLK_PRE_BIT_END                 15U

/* Definition for field VC3_FIFO_SIZE in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC3_FIFO_SIZE_BIT_START        28U
#define CSI2_TX_FIFO_VC_SIZE_VC3_FIFO_SIZE_BIT_END          31U

/* Definition for field VC3_FIFO_ADD in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC3_FIFO_ADD_BIT_START         24U
#define CSI2_TX_FIFO_VC_SIZE_VC3_FIFO_ADD_BIT_END           26U

/* Definition for field VC2_FIFO_SIZE in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC2_FIFO_SIZE_BIT_START        20U
#define CSI2_TX_FIFO_VC_SIZE_VC2_FIFO_SIZE_BIT_END          23U

/* Definition for field VC2_FIFO_ADD in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC2_FIFO_ADD_BIT_START         16U
#define CSI2_TX_FIFO_VC_SIZE_VC2_FIFO_ADD_BIT_END           18U

/* Definition for field VC1_FIFO_SIZE in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC1_FIFO_SIZE_BIT_START        12U
#define CSI2_TX_FIFO_VC_SIZE_VC1_FIFO_SIZE_BIT_END          15U

/* Definition for field VC1_FIFO_ADD in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC1_FIFO_ADD_BIT_START         8U
#define CSI2_TX_FIFO_VC_SIZE_VC1_FIFO_ADD_BIT_END           10U

/* Definition for field VC0_FIFO_SIZE in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC0_FIFO_SIZE_BIT_START        4U
#define CSI2_TX_FIFO_VC_SIZE_VC0_FIFO_SIZE_BIT_END          7U

/* Definition for field VC0_FIFO_ADD in Register CSI2_TX_FIFO_VC_SIZE */
#define CSI2_TX_FIFO_VC_SIZE_VC0_FIFO_ADD_BIT_START         0U
#define CSI2_TX_FIFO_VC_SIZE_VC0_FIFO_ADD_BIT_END           2U

/* Definition for field VC0_FIFO_SIZE in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC0_FIFO_SIZE_BIT_START        4U
#define CSI2_RX_FIFO_VC_SIZE_VC0_FIFO_SIZE_BIT_END          7U

/* Definition for field VC1_FIFO_SIZE in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC1_FIFO_SIZE_BIT_START        12U
#define CSI2_RX_FIFO_VC_SIZE_VC1_FIFO_SIZE_BIT_END          15U

/* Definition for field VC2_FIFO_SIZE in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC2_FIFO_SIZE_BIT_START        20U
#define CSI2_RX_FIFO_VC_SIZE_VC2_FIFO_SIZE_BIT_END          23U

/* Definition for field VC3_FIFO_SIZE in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC3_FIFO_SIZE_BIT_START        28U
#define CSI2_RX_FIFO_VC_SIZE_VC3_FIFO_SIZE_BIT_END          31U

/* Definition for field VC3_FIFO_ADD in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC3_FIFO_ADD_BIT_START         24U
#define CSI2_RX_FIFO_VC_SIZE_VC3_FIFO_ADD_BIT_END           26U

/* Definition for field VC2_FIFO_ADD in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC2_FIFO_ADD_BIT_START         16U
#define CSI2_RX_FIFO_VC_SIZE_VC2_FIFO_ADD_BIT_END           18U

/* Definition for field VC1_FIFO_ADD in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC1_FIFO_ADD_BIT_START         8U
#define CSI2_RX_FIFO_VC_SIZE_VC1_FIFO_ADD_BIT_END           10U

/* Definition for field VC0_FIFO_ADD in Register CSI2_RX_FIFO_VC_SIZE */
#define CSI2_RX_FIFO_VC_SIZE_VC0_FIFO_ADD_BIT_START         0U
#define CSI2_RX_FIFO_VC_SIZE_VC0_FIFO_ADD_BIT_END           2U

/* Definition for field LANE1_ULPS_SIG1 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE1_ULPS_SIG1_BIT_START       0U
#define CSI2_COMPLEXIO_CFG2_LANE1_ULPS_SIG1_BIT_END         0U

/* Definition for field LANE2_ULPS_SIG1 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE2_ULPS_SIG1_BIT_START       1U
#define CSI2_COMPLEXIO_CFG2_LANE2_ULPS_SIG1_BIT_END         1U

/* Definition for field LANE3_ULPS_SIG1 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE3_ULPS_SIG1_BIT_START       2U
#define CSI2_COMPLEXIO_CFG2_LANE3_ULPS_SIG1_BIT_END         2U

/* Definition for field LANE4_ULPS_SIG1 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE4_ULPS_SIG1_BIT_START       3U
#define CSI2_COMPLEXIO_CFG2_LANE4_ULPS_SIG1_BIT_END         3U

/* Definition for field LANE5_ULPS_SIG1 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE5_ULPS_SIG1_BIT_START       4U
#define CSI2_COMPLEXIO_CFG2_LANE5_ULPS_SIG1_BIT_END         4U

/* Definition for field LANE5_ULPS_SIG2 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE5_ULPS_SIG2_BIT_START       9U
#define CSI2_COMPLEXIO_CFG2_LANE5_ULPS_SIG2_BIT_END         9U

/* Definition for field LANE3_ULPS_SIG2 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE3_ULPS_SIG2_BIT_START       7U
#define CSI2_COMPLEXIO_CFG2_LANE3_ULPS_SIG2_BIT_END         7U

/* Definition for field LANE2_ULPS_SIG2 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE2_ULPS_SIG2_BIT_START       6U
#define CSI2_COMPLEXIO_CFG2_LANE2_ULPS_SIG2_BIT_END         6U

/* Definition for field LANE1_ULPS_SIG2 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE1_ULPS_SIG2_BIT_START       5U
#define CSI2_COMPLEXIO_CFG2_LANE1_ULPS_SIG2_BIT_END         5U

/* Definition for field HS_BUSY in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_HS_BUSY_BIT_START               16U
#define CSI2_COMPLEXIO_CFG2_HS_BUSY_BIT_END                 16U

/* Definition for field LP_BUSY in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LP_BUSY_BIT_START               17U
#define CSI2_COMPLEXIO_CFG2_LP_BUSY_BIT_END                 17U

/* Definition for field LANE4_ULPS_SIG2 in Register CSI2_COMPLEXIO_CFG2 */
#define CSI2_COMPLEXIO_CFG2_LANE4_ULPS_SIG2_BIT_START       8U
#define CSI2_COMPLEXIO_CFG2_LANE4_ULPS_SIG2_BIT_END         8U

/* Definition for field VC2_FIFO_FULLNESS in Register CSI2_RX_FIFO_VC_FULLNESS */
#define CSI2_RX_FIFO_VC_FULLNESS_VC2_FIFO_FULLNESS_BIT_START 16U
#define CSI2_RX_FIFO_VC_FULLNESS_VC2_FIFO_FULLNESS_BIT_END  23U

/* Definition for field VC0_FIFO_FULLNESS in Register CSI2_RX_FIFO_VC_FULLNESS */
#define CSI2_RX_FIFO_VC_FULLNESS_VC0_FIFO_FULLNESS_BIT_START 0U
#define CSI2_RX_FIFO_VC_FULLNESS_VC0_FIFO_FULLNESS_BIT_END  7U

/* Definition for field VC3_FIFO_FULLNESS in Register CSI2_RX_FIFO_VC_FULLNESS */
#define CSI2_RX_FIFO_VC_FULLNESS_VC3_FIFO_FULLNESS_BIT_START 24U
#define CSI2_RX_FIFO_VC_FULLNESS_VC3_FIFO_FULLNESS_BIT_END  31U

/* Definition for field VC1_FIFO_FULLNESS in Register CSI2_RX_FIFO_VC_FULLNESS */
#define CSI2_RX_FIFO_VC_FULLNESS_VC1_FIFO_FULLNESS_BIT_START 8U
#define CSI2_RX_FIFO_VC_FULLNESS_VC1_FIFO_FULLNESS_BIT_END  15U

/* Definition for field HFP_HS_INTERLEAVING in Register CSI2_VM_TIMING4 */
#define CSI2_VM_TIMING4_HFP_HS_INTERLEAVING_BIT_START       8U
#define CSI2_VM_TIMING4_HFP_HS_INTERLEAVING_BIT_END         15U

/* Definition for field HBP_HS_INTERLEAVING in Register CSI2_VM_TIMING4 */
#define CSI2_VM_TIMING4_HBP_HS_INTERLEAVING_BIT_START       0U
#define CSI2_VM_TIMING4_HBP_HS_INTERLEAVING_BIT_END         7U

/* Definition for field HSA_HS_INTERLEAVING in Register CSI2_VM_TIMING4 */
#define CSI2_VM_TIMING4_HSA_HS_INTERLEAVING_BIT_START       16U
#define CSI2_VM_TIMING4_HSA_HS_INTERLEAVING_BIT_END         23U

/* Definition for field VC0_FIFO_EMPTINESS in Register CSI2_TX_FIFO_VC_EMPTINESS */
#define CSI2_TX_FIFO_VC_EMPTINESS_VC0_FIFO_EMPTINESS_BIT_START 0U
#define CSI2_TX_FIFO_VC_EMPTINESS_VC0_FIFO_EMPTINESS_BIT_END 7U

/* Definition for field VC2_FIFO_EMPTINESS in Register CSI2_TX_FIFO_VC_EMPTINESS */
#define CSI2_TX_FIFO_VC_EMPTINESS_VC2_FIFO_EMPTINESS_BIT_START 16U
#define CSI2_TX_FIFO_VC_EMPTINESS_VC2_FIFO_EMPTINESS_BIT_END 23U

/* Definition for field VC3_FIFO_EMPTINESS in Register CSI2_TX_FIFO_VC_EMPTINESS */
#define CSI2_TX_FIFO_VC_EMPTINESS_VC3_FIFO_EMPTINESS_BIT_START 24U
#define CSI2_TX_FIFO_VC_EMPTINESS_VC3_FIFO_EMPTINESS_BIT_END 31U

/* Definition for field VC1_FIFO_EMPTINESS in Register CSI2_TX_FIFO_VC_EMPTINESS */
#define CSI2_TX_FIFO_VC_EMPTINESS_VC1_FIFO_EMPTINESS_BIT_START 8U
#define CSI2_TX_FIFO_VC_EMPTINESS_VC1_FIFO_EMPTINESS_BIT_END 15U

/* Definition for field HFP_LP_INTERLEAVING in Register CSI2_VM_TIMING5 */
#define CSI2_VM_TIMING5_HFP_LP_INTERLEAVING_BIT_START       8U
#define CSI2_VM_TIMING5_HFP_LP_INTERLEAVING_BIT_END         15U

/* Definition for field HBP_LP_INTERLEAVING in Register CSI2_VM_TIMING5 */
#define CSI2_VM_TIMING5_HBP_LP_INTERLEAVING_BIT_START       0U
#define CSI2_VM_TIMING5_HBP_LP_INTERLEAVING_BIT_END         7U

/* Definition for field HSA_LP_INTERLEAVING in Register CSI2_VM_TIMING5 */
#define CSI2_VM_TIMING5_HSA_LP_INTERLEAVING_BIT_START       16U
#define CSI2_VM_TIMING5_HSA_LP_INTERLEAVING_BIT_END         23U

/* Definition for field BL_LP_INTERLEAVING in Register CSI2_VM_TIMING6 */
#define CSI2_VM_TIMING6_BL_LP_INTERLEAVING_BIT_START        0U
#define CSI2_VM_TIMING6_BL_LP_INTERLEAVING_BIT_END          15U

/* Definition for field BL_HS_INTERLEAVING in Register CSI2_VM_TIMING6 */
#define CSI2_VM_TIMING6_BL_HS_INTERLEAVING_BIT_START        16U
#define CSI2_VM_TIMING6_BL_HS_INTERLEAVING_BIT_END          31U

/* Definition for field EXIT_HS_MODE_LATENCY in Register CSI2_VM_TIMING7 */
#define CSI2_VM_TIMING7_EXIT_HS_MODE_LATENCY_BIT_START      0U
#define CSI2_VM_TIMING7_EXIT_HS_MODE_LATENCY_BIT_END        15U

/* Definition for field ENTER_HS_MODE_LATENCY in Register CSI2_VM_TIMING7 */
#define CSI2_VM_TIMING7_ENTER_HS_MODE_LATENCY_BIT_START     16U
#define CSI2_VM_TIMING7_ENTER_HS_MODE_LATENCY_BIT_END       31U

/* Definition for field CSI2_STOPCLK_LATENCY in Register CSI2_STOPCLK_TIMING */
#define CSI2_STOPCLK_TIMING_CSI2_STOPCLK_LATENCY_BIT_START  0U
#define CSI2_STOPCLK_TIMING_CSI2_STOPCLK_LATENCY_BIT_END    7U

/* Definition for field VP_CLK_POL in Register CSI2_CTRL2 */
#define CSI2_CTRL2_VP_CLK_POL_BIT_START                     8U
#define CSI2_CTRL2_VP_CLK_POL_BIT_END                       8U

/* Definition for field VP_HSYNC_POL in Register CSI2_CTRL2 */
#define CSI2_CTRL2_VP_HSYNC_POL_BIT_START                   10U
#define CSI2_CTRL2_VP_HSYNC_POL_BIT_END                     10U

/* Definition for field VP_VSYNC_POL in Register CSI2_CTRL2 */
#define CSI2_CTRL2_VP_VSYNC_POL_BIT_START                   11U
#define CSI2_CTRL2_VP_VSYNC_POL_BIT_END                     11U

/* Definition for field VP_DE_POL in Register CSI2_CTRL2 */
#define CSI2_CTRL2_VP_DE_POL_BIT_START                      9U
#define CSI2_CTRL2_VP_DE_POL_BIT_END                        9U

/* Definition for field VP_CLK_RATIO in Register CSI2_CTRL2 */
#define CSI2_CTRL2_VP_CLK_RATIO_BIT_START                   4U
#define CSI2_CTRL2_VP_CLK_RATIO_BIT_END                     4U

/* Definition for field LINE_BUFFER in Register CSI2_CTRL2 */
#define CSI2_CTRL2_LINE_BUFFER_BIT_START                    12U
#define CSI2_CTRL2_LINE_BUFFER_BIT_END                      13U

/* Definition for field VP_DATA_BUS_WIDTH in Register CSI2_CTRL2 */
#define CSI2_CTRL2_VP_DATA_BUS_WIDTH_BIT_START              6U
#define CSI2_CTRL2_VP_DATA_BUS_WIDTH_BIT_END                7U

/* Definition for field HFPX in Register CSI2_VM_TIMING8 */
#define CSI2_VM_TIMING8_HFPX_BIT_START                      0U
#define CSI2_VM_TIMING8_HFPX_BIT_END                        1U

/* Definition for field MIN_HSYNC_PULSE_WIDTH in Register CSI2_TE_HSYNC_WIDTH */
#define CSI2_TE_HSYNC_WIDTH_MIN_HSYNC_PULSE_WIDTH_BIT_START 8U
#define CSI2_TE_HSYNC_WIDTH_MIN_HSYNC_PULSE_WIDTH_BIT_END   19U

/* Definition for field MIN_VSYNC_PULSE_WIDTH in Register CSI2_TE_VSYNC_WIDTH */
#define CSI2_TE_VSYNC_WIDTH_MIN_VSYNC_PULSE_WIDTH_BIT_START 8U
#define CSI2_TE_VSYNC_WIDTH_MIN_VSYNC_PULSE_WIDTH_BIT_END   19U

/* Definition for field LINE_NUMBER in Register CSI2_TE_HSYNC_NUMBER */
#define CSI2_TE_HSYNC_NUMBER_LINE_NUMBER_BIT_START          0U
#define CSI2_TE_HSYNC_NUMBER_LINE_NUMBER_BIT_END            10U

/* Definition for field VC_EN in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_VC_EN_BIT_START                        0U
#define CSI2_VC_CTRL_VC_EN_BIT_END                          0U

/* Definition for field BTA_SHORT_EN in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_BTA_SHORT_EN_BIT_START                 2U
#define CSI2_VC_CTRL_BTA_SHORT_EN_BIT_END                   2U

/* Definition for field CS_TX_EN in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_CS_TX_EN_BIT_START                     7U
#define CSI2_VC_CTRL_CS_TX_EN_BIT_END                       7U

/* Definition for field ECC_TX_EN in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_ECC_TX_EN_BIT_START                    8U
#define CSI2_VC_CTRL_ECC_TX_EN_BIT_END                      8U

/* Definition for field BTA_EN in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_BTA_EN_BIT_START                       6U
#define CSI2_VC_CTRL_BTA_EN_BIT_END                         6U

/* Definition for field SOURCE in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_SOURCE_BIT_START                       1U
#define CSI2_VC_CTRL_SOURCE_BIT_END                         1U

/* Definition for field BTA_LONG_EN in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_BTA_LONG_EN_BIT_START                  3U
#define CSI2_VC_CTRL_BTA_LONG_EN_BIT_END                    3U

/* Definition for field MODE in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_MODE_BIT_START                         4U
#define CSI2_VC_CTRL_MODE_BIT_END                           4U

/* Definition for field DMA_TX_THRESHOLD in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_DMA_TX_THRESHOLD_BIT_START             17U
#define CSI2_VC_CTRL_DMA_TX_THRESHOLD_BIT_END               19U

/* Definition for field RX_FIFO_NOT_EMPTY in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_RX_FIFO_NOT_EMPTY_BIT_START            20U
#define CSI2_VC_CTRL_RX_FIFO_NOT_EMPTY_BIT_END              20U

/* Definition for field MODE_SPEED in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_MODE_SPEED_BIT_START                   9U
#define CSI2_VC_CTRL_MODE_SPEED_BIT_END                     9U

/* Definition for field DMA_TX_REQ_NB in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_DMA_TX_REQ_NB_BIT_START                21U
#define CSI2_VC_CTRL_DMA_TX_REQ_NB_BIT_END                  23U

/* Definition for field TX_FIFO_NOT_EMPTY in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_TX_FIFO_NOT_EMPTY_BIT_START            5U
#define CSI2_VC_CTRL_TX_FIFO_NOT_EMPTY_BIT_END              5U

/* Definition for field DMA_RX_THRESHOLD in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_DMA_RX_THRESHOLD_BIT_START             24U
#define CSI2_VC_CTRL_DMA_RX_THRESHOLD_BIT_END               26U

/* Definition for field DMA_RX_REQ_NB in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_DMA_RX_REQ_NB_BIT_START                27U
#define CSI2_VC_CTRL_DMA_RX_REQ_NB_BIT_END                  29U

/* Definition for field TX_FIFO_FULL in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_TX_FIFO_FULL_BIT_START                 16U
#define CSI2_VC_CTRL_TX_FIFO_FULL_BIT_END                   16U

/* Definition for field VC_BUSY in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_VC_BUSY_BIT_START                      15U
#define CSI2_VC_CTRL_VC_BUSY_BIT_END                        15U

/* Definition for field PP_BUSY in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_PP_BUSY_BIT_START                      14U
#define CSI2_VC_CTRL_PP_BUSY_BIT_END                        14U

/* Definition for field DCS_CMD_ENABLE in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_DCS_CMD_ENABLE_BIT_START               30U
#define CSI2_VC_CTRL_DCS_CMD_ENABLE_BIT_END                 30U

/* Definition for field DCS_CMD_CODE in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_DCS_CMD_CODE_BIT_START                 31U
#define CSI2_VC_CTRL_DCS_CMD_CODE_BIT_END                   31U

/* Definition for field OCP_DATA_BUS_WIDTH in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_OCP_DATA_BUS_WIDTH_BIT_START           10U
#define CSI2_VC_CTRL_OCP_DATA_BUS_WIDTH_BIT_END             11U

/* Definition for field RGB565_ORDER in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_RGB565_ORDER_BIT_START                 12U
#define CSI2_VC_CTRL_RGB565_ORDER_BIT_END                   12U

/* Definition for field VP_SOURCE in Register CSI2_VC_CTRL */
#define CSI2_VC_CTRL_VP_SOURCE_BIT_START                    13U
#define CSI2_VC_CTRL_VP_SOURCE_BIT_END                      13U

/* Definition for field CS_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_CS_IRQ_EN_BIT_START               0U
#define CSI2_VC_IRQENABLE_CS_IRQ_EN_BIT_END                 0U

/* Definition for field ECC_CORRECTION_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_ECC_CORRECTION_IRQ_EN_BIT_START   1U
#define CSI2_VC_IRQENABLE_ECC_CORRECTION_IRQ_EN_BIT_END     1U

/* Definition for field PACKET_SENT_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_PACKET_SENT_IRQ_EN_BIT_START      2U
#define CSI2_VC_IRQENABLE_PACKET_SENT_IRQ_EN_BIT_END        2U

/* Definition for field FIFO_RX_OVF_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_FIFO_RX_OVF_IRQ_EN_BIT_START      4U
#define CSI2_VC_IRQENABLE_FIFO_RX_OVF_IRQ_EN_BIT_END        4U

/* Definition for field FIFO_TX_OVF_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_FIFO_TX_OVF_IRQ_EN_BIT_START      3U
#define CSI2_VC_IRQENABLE_FIFO_TX_OVF_IRQ_EN_BIT_END        3U

/* Definition for field BTA_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_BTA_IRQ_EN_BIT_START              5U
#define CSI2_VC_IRQENABLE_BTA_IRQ_EN_BIT_END                5U

/* Definition for field ECC_NO_CORRECTION_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_ECC_NO_CORRECTION_IRQ_EN_BIT_START 6U
#define CSI2_VC_IRQENABLE_ECC_NO_CORRECTION_IRQ_EN_BIT_END  6U

/* Definition for field FIFO_TX_UDF_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_FIFO_TX_UDF_IRQ_EN_BIT_START      7U
#define CSI2_VC_IRQENABLE_FIFO_TX_UDF_IRQ_EN_BIT_END        7U

/* Definition for field PP_BUSY_CHANGE_IRQ_EN in Register CSI2_VC_IRQENABLE */
#define CSI2_VC_IRQENABLE_PP_BUSY_CHANGE_IRQ_EN_BIT_START   8U
#define CSI2_VC_IRQENABLE_PP_BUSY_CHANGE_IRQ_EN_BIT_END     8U

/* Definition for field CS_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_CS_IRQ_BIT_START                  0U
#define CSI2_VC_IRQSTATUS_CS_IRQ_BIT_END                    0U

/* Definition for field ECC_CORRECTION_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_ECC_CORRECTION_IRQ_BIT_START      1U
#define CSI2_VC_IRQSTATUS_ECC_CORRECTION_IRQ_BIT_END        1U

/* Definition for field PACKET_SENT_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_PACKET_SENT_IRQ_BIT_START         2U
#define CSI2_VC_IRQSTATUS_PACKET_SENT_IRQ_BIT_END           2U

/* Definition for field FIFO_RX_OVF_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_FIFO_RX_OVF_IRQ_BIT_START         4U
#define CSI2_VC_IRQSTATUS_FIFO_RX_OVF_IRQ_BIT_END           4U

/* Definition for field FIFO_TX_OVF_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_FIFO_TX_OVF_IRQ_BIT_START         3U
#define CSI2_VC_IRQSTATUS_FIFO_TX_OVF_IRQ_BIT_END           3U

/* Definition for field BTA_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_BTA_IRQ_BIT_START                 5U
#define CSI2_VC_IRQSTATUS_BTA_IRQ_BIT_END                   5U

/* Definition for field ECC_NO_CORRECTION_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_ECC_NO_CORRECTION_IRQ_BIT_START   6U
#define CSI2_VC_IRQSTATUS_ECC_NO_CORRECTION_IRQ_BIT_END     6U

/* Definition for field FIFO_TX_UDF_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_FIFO_TX_UDF_IRQ_BIT_START         7U
#define CSI2_VC_IRQSTATUS_FIFO_TX_UDF_IRQ_BIT_END           7U

/* Definition for field PP_BUSY_CHANGE_IRQ in Register CSI2_VC_IRQSTATUS */
#define CSI2_VC_IRQSTATUS_PP_BUSY_CHANGE_IRQ_BIT_START      8U
#define CSI2_VC_IRQSTATUS_PP_BUSY_CHANGE_IRQ_BIT_END        8U

/* Definition for field TE_EN in Register CSI2_VC_TE */
#define CSI2_VC_TE_TE_EN_BIT_START                          30U
#define CSI2_VC_TE_TE_EN_BIT_END                            30U

/* Definition for field TE_SIZE in Register CSI2_VC_TE */
#define CSI2_VC_TE_TE_SIZE_BIT_START                        0U
#define CSI2_VC_TE_TE_SIZE_BIT_END                          23U

/* Definition for field TE_START in Register CSI2_VC_TE */
#define CSI2_VC_TE_TE_START_BIT_START                       31U
#define CSI2_VC_TE_TE_START_BIT_END                         31U

/* Definition for field TE_LINE in Register CSI2_VC_TE */
#define CSI2_VC_TE_TE_LINE_BIT_START                        29U
#define CSI2_VC_TE_TE_LINE_BIT_END                          29U

/* Definition for field TE_LINE_NB in Register CSI2_VC_TE */
#define CSI2_VC_TE_TE_LINE_NB_BIT_START                     28U
#define CSI2_VC_TE_TE_LINE_NB_BIT_END                       28U

/* Definition for field HEADER in Register CSI2_VC_LONG_PACKET_HEADER */
#define CSI2_VC_LONG_PACKET_HEADER_HEADER_BIT_START         0U
#define CSI2_VC_LONG_PACKET_HEADER_HEADER_BIT_END           31U

/* Definition for field PAYLOAD in Register CSI2_VC_LONG_PACKET_PAYLOAD */
#define CSI2_VC_LONG_PACKET_PAYLOAD_PAYLOAD_BIT_START       0U
#define CSI2_VC_LONG_PACKET_PAYLOAD_PAYLOAD_BIT_END         31U

/* Definition for field HEADER in Register CSI2_VC_SHORT_PACKET_HEADER */
#define CSI2_VC_SHORT_PACKET_HEADER_HEADER_BIT_START        0U
#define CSI2_VC_SHORT_PACKET_HEADER_HEADER_BIT_END          31U



/**
 * @struct CSI2PROTOCOLENGINERegs_t
 * @brief
 *   Module CSI2_PROTOCOL_ENGINE Register Definition
 * @details
 *   This structure is used to access the CSI2_PROTOCOL_ENGINE module registers.
 */
/**
 * @typedef CSI2PROTOCOLENGINERegs
 * @brief
 *   Module CSI2_PROTOCOL_ENGINE Register Frame type Definition
 * @details
 *   This type is used to access the CSI2_PROTOCOL_ENGINE module registers.
 */
typedef volatile struct CSI2PROTOCOLENGINERegs_t
{
    uint32_t    CSI2_REVISION                      ;        /* Offset = 0x000 */
    uint32_t    RESTRICTED1[3]                     ;        /* Offset = 0x004 */
    uint32_t    CSI2_SYSCONFIG                     ;        /* Offset = 0x010 */
    uint32_t    CSI2_SYSSTATUS                     ;        /* Offset = 0x014 */
    uint32_t    CSI2_IRQSTATUS                     ;        /* Offset = 0x018 */
    uint32_t    CSI2_IRQENABLE                     ;        /* Offset = 0x01c */
    uint32_t    RESTRICTED2[8]                     ;        /* Offset = 0x020 */
    uint32_t    CSI2_CTRL                          ;        /* Offset = 0x040 */
    uint32_t    CSI2_GNQ                           ;        /* Offset = 0x044 */
    uint32_t    CSI2_COMPLEXIO_CFG1                ;        /* Offset = 0x048 */
    uint32_t    CSI2_COMPLEXIO_IRQSTATUS           ;        /* Offset = 0x04c */
    uint32_t    CSI2_COMPLEXIO_IRQENABLE           ;        /* Offset = 0x050 */
    uint32_t    CSI2_CLK_CTRL                      ;        /* Offset = 0x054 */
    uint32_t    CSI2_TIMING1                       ;        /* Offset = 0x058 */
    uint32_t    CSI2_TIMING2                       ;        /* Offset = 0x05c */
    uint32_t    CSI2_VM_TIMING1                    ;        /* Offset = 0x060 */
    uint32_t    CSI2_VM_TIMING2                    ;        /* Offset = 0x064 */
    uint32_t    CSI2_VM_TIMING3                    ;        /* Offset = 0x068 */
    uint32_t    CSI2_CLK_TIMING                    ;        /* Offset = 0x06c */
    uint32_t    CSI2_TX_FIFO_VC_SIZE               ;        /* Offset = 0x070 */
    uint32_t    CSI2_RX_FIFO_VC_SIZE               ;        /* Offset = 0x074 */
    uint32_t    CSI2_COMPLEXIO_CFG2                ;        /* Offset = 0x078 */
    uint32_t    CSI2_RX_FIFO_VC_FULLNESS           ;        /* Offset = 0x07c */
    uint32_t    CSI2_VM_TIMING4                    ;        /* Offset = 0x080 */
    uint32_t    CSI2_TX_FIFO_VC_EMPTINESS          ;        /* Offset = 0x084 */
    uint32_t    CSI2_VM_TIMING5                    ;        /* Offset = 0x088 */
    uint32_t    CSI2_VM_TIMING6                    ;        /* Offset = 0x08c */
    uint32_t    CSI2_VM_TIMING7                    ;        /* Offset = 0x090 */
    uint32_t    CSI2_STOPCLK_TIMING                ;        /* Offset = 0x094 */
    uint32_t    CSI2_CTRL2                         ;        /* Offset = 0x098 */
    uint32_t    CSI2_VM_TIMING8                    ;        /* Offset = 0x09c */
        struct                                              /* AddrOffset = 0x0A0 - 0x0B4 */
        {
            uint32_t    CSI2_TE_HSYNC_WIDTH       ;
            uint32_t    CSI2_TE_VSYNC_WIDTH       ;
            uint32_t    CSI2_TE_HSYNC_NUMBER      ;
        }CSI2TEPARAMS[2];
        uint32_t    PADREGARR0[18]            ;             /* AddrOffset = 0x0B8 - 0x0FC */
        struct                                              /* AddrOffset = 0x100 - 0x17C */
        {
            uint32_t    CSI2_VC_CTRL              ;
            uint32_t    CSI2_VC_TE                ;
            uint32_t    CSI2_VC_LONG_PACKET_HEADER;
            uint32_t    CSI2_VC_LONG_PACKET_PAYLOAD;
            uint32_t    CSI2_VC_SHORT_PACKET_HEADER;
            uint32_t    PADREG11                 ;
            uint32_t    CSI2_VC_IRQSTATUS         ;
            uint32_t    CSI2_VC_IRQENABLE         ;
        }CSI2VCPARAMS[4];
} CSI2PROTOCOLENGINERegs;

#ifdef __cplusplus
}
#endif

#endif /* REG_CSI2PROTOCOLENGINE_H */
/* END OF REG_CSI2PROTOCOLENGINE_H */

