.TH "common Directory Reference" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcfg\&.c\fP"
.br
.ti -1c
.RI "file \fBdetected_obj\&.h\fP"
.br
.ti -1c
.RI "file \fBmmw_messages\&.h\fP"
.br
.RI "This is the main header file for the Millimeter Wave Demo\&. "
.ti -1c
.RI "file \fBmrr_config\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_config_chirp_design_MRR120\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_config_chirp_design_MRR80\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_config_chirp_design_USRR20\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_config_chirp_design_USRR30\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_config_consts\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_defines\&.h\fP"
.br
.ti -1c
.RI "file \fBmrr_output\&.h\fP"
.br
.RI "This is the interface/message header file for the Millimeter Wave Demo\&. "
.in -1c
