.TH "Debug/configPkg/package Directory Reference" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debug/configPkg/package Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcfg\fP"
.br
.ti -1c
.RI "directory \fBrel\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfigPkg\&.java\fP"
.br
.ti -1c
.RI "file \fBpackage\&.defs\&.h\fP"
.br
.ti -1c
.RI "file \fBpackage\&.xdc\&.inc\fP"
.br
.ti -1c
.RI "file \fBpackage_configPkg\&.c\fP"
.br
.in -1c
