.TH "C:/Users/astro/workspace_v9_2/mrr_18xx_dss Directory Reference" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/astro/workspace_v9_2/mrr_18xx_dss Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommon\fP"
.br
.ti -1c
.RI "directory \fBDebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclusteringDBscan\&.c\fP"
.br
.RI "DBscan clustering module\&. "
.ti -1c
.RI "file \fBclusteringDBscan\&.h\fP"
.br
.RI "DBscan clustering module\&. "
.ti -1c
.RI "file \fBdss_config_edma_util\&.c\fP"
.br
.RI "EDMA Configuration Utility API implementation\&. "
.ti -1c
.RI "file \fBdss_config_edma_util\&.h\fP"
.br
.RI "EDMA Configuration Utility API definitions\&. "
.ti -1c
.RI "file \fBdss_data_path\&.c\fP"
.br
.RI "Implements Data path processing functionality\&. "
.ti -1c
.RI "file \fBdss_data_path\&.h\fP"
.br
.RI "This is the data path processing header\&. "
.ti -1c
.RI "file \fBdss_main\&.c\fP"
.br
.ti -1c
.RI "file \fBdss_mrr\&.h\fP"
.br
.RI "This is the main header file for the DSS MRR TI Design\&. "
.ti -1c
.RI "file \fBEKF_XYZ_Consts\&.h\fP"
.br
.RI "Constants for the Extended Kalman Filter\&. "
.ti -1c
.RI "file \fBEKF_XYZ_Interface\&.h\fP"
.br
.RI "Interface the Extended Kalman Filter\&. "
.ti -1c
.RI "file \fBExtended_Kalman_Filter_xyz\&.c\fP"
.br
.RI "Implements an 'Extended Kalman Filter' for radar tracking\&. "
.ti -1c
.RI "file \fBgen_twiddle_fft16x16\&.c\fP"
.br
.ti -1c
.RI "file \fBgen_twiddle_fft32x32\&.c\fP"
.br
.in -1c
