.TH "DSS_TO_MSS_EXCEPTION_IDS" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DSS_TO_MSS_EXCEPTION_IDS \- Exception ID definitions for DSS to MSS urgent exception signalling through software interrupt\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMMWDEMO_DSS2MSS_CHIRP_PROC_DEADLINE_MISS_EXCEPTION\fP   0"
.br
.RI "DSS to MSS chirp processing deadline miss exception ID\&. "
.ti -1c
.RI "#define \fBMMWDEMO_DSS2MSS_FRAME_PROC_DEADLINE_MISS_EXCEPTION\fP   1"
.br
.RI "DSS to MSS frame processing deadline miss exception ID\&. "
.ti -1c
.RI "#define \fBMMWDEMO_DSS2MSS_CHIRP_PROC_DEADLINE_MISS_EXCEPTION\fP   0"
.br
.RI "DSS to MSS chirp processing deadline miss exception ID\&. "
.ti -1c
.RI "#define \fBMMWDEMO_DSS2MSS_FRAME_PROC_DEADLINE_MISS_EXCEPTION\fP   1"
.br
.RI "DSS to MSS frame processing deadline miss exception ID\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception ID definitions for DSS to MSS urgent exception signalling through software interrupt\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define MMWDEMO_DSS2MSS_CHIRP_PROC_DEADLINE_MISS_EXCEPTION   0"

.PP
DSS to MSS chirp processing deadline miss exception ID\&. 
.PP
Definition at line 100 of file mmw_messages\&.h\&.
.SS "#define MMWDEMO_DSS2MSS_CHIRP_PROC_DEADLINE_MISS_EXCEPTION   0"

.PP
DSS to MSS chirp processing deadline miss exception ID\&. 
.PP
Definition at line 100 of file mmw_messages\&.h\&.
.SS "#define MMWDEMO_DSS2MSS_FRAME_PROC_DEADLINE_MISS_EXCEPTION   1"

.PP
DSS to MSS frame processing deadline miss exception ID\&. 
.PP
Definition at line 103 of file mmw_messages\&.h\&.
.SS "#define MMWDEMO_DSS2MSS_FRAME_PROC_DEADLINE_MISS_EXCEPTION   1"

.PP
DSS to MSS frame processing deadline miss exception ID\&. 
.PP
Definition at line 103 of file mmw_messages\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
