.TH "maxVelEnhStruct_t_" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxVelEnhStruct_t_ \- pre-computed parameters of the max-velocity-enhancement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dss_data_path\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBvelResolutionFastChirp\fP"
.br
.ti -1c
.RI "float \fBinvVelResolutionSlowChirp\fP"
.br
.ti -1c
.RI "uint16_t \fBmaxVelAssocThresh\fP"
.br
.ti -1c
.RI "uint16_t \fBpadding\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
pre-computed parameters of the max-velocity-enhancement\&. 
.PP
Definition at line 109 of file dss_data_path\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float maxVelEnhStruct_t_::invVelResolutionSlowChirp"

.PP
Definition at line 112 of file dss_data_path\&.h\&.
.SS "uint16_t maxVelEnhStruct_t_::maxVelAssocThresh"

.PP
Definition at line 113 of file dss_data_path\&.h\&.
.SS "uint16_t maxVelEnhStruct_t_::padding"

.PP
Definition at line 114 of file dss_data_path\&.h\&.
.SS "float maxVelEnhStruct_t_::velResolutionFastChirp"

.PP
Definition at line 111 of file dss_data_path\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
