.TH "MmwDemo_dssAssertInfoMsg_t" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_dssAssertInfoMsg_t \- Message for reporting DSS assertion information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmw_messages\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBfile\fP [\fBMMWDEMO_MAX_FILE_NAME_SIZE\fP]"
.br
.RI "file name "
.ti -1c
.RI "uint32_t \fBline\fP"
.br
.RI "line number "
.in -1c
.SH "Detailed Description"
.PP 
Message for reporting DSS assertion information\&. 

The structure defines the message body for the information on a DSS exception that should be forwarded to the MSS\&. 
.PP
Definition at line 151 of file mmw_messages\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char MmwDemo_dssAssertInfoMsg_t::file"

.PP
file name 
.PP
Definition at line 154 of file mmw_messages\&.h\&.
.SS "uint32_t MmwDemo_dssAssertInfoMsg_t::line"

.PP
line number 
.PP
Definition at line 157 of file mmw_messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
