.TH "MmwDemo_LvdsStreamCfg_t" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_LvdsStreamCfg_t \- LVDS streaming configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrr_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBisHeaderEnabled\fP"
.br
.RI "HSI \fBHeader\fP enabled/disabled flag\&. "
.ti -1c
.RI "uint8_t \fBdataFmt\fP"
.br
.ti -1c
.RI "bool \fBisSwEnabled\fP"
.br
.RI "SW enabled/disabled flag\&. "
.in -1c
.SH "Detailed Description"
.PP 
LVDS streaming configuration\&. 

The structure is used to hold all the relevant configuration for the LVDS streaming\&. 
.PP
Definition at line 275 of file mrr_config\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t MmwDemo_LvdsStreamCfg_t::dataFmt"
HW streaming data format: 0-HW STREAMING DISABLED 1-ADC 2-CP_ADC 3-ADC_CP 4-CP_ADC_CQ 
.PP
Definition at line 290 of file mrr_config\&.h\&.
.SS "bool MmwDemo_LvdsStreamCfg_t::isHeaderEnabled"

.PP
HSI \fBHeader\fP enabled/disabled flag\&. 
.PP
Definition at line 280 of file mrr_config\&.h\&.
.SS "bool MmwDemo_LvdsStreamCfg_t::isSwEnabled"

.PP
SW enabled/disabled flag\&. 
.PP
Definition at line 295 of file mrr_config\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
