.TH "MmwDemo_compRxChannelBiasCfg_t_" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_compRxChannelBiasCfg_t_ \- Range Bias and rx channel gain/phase compensation configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrr_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBrangeBias\fP"
.br
.RI "Compensation for range estimation bias\&. "
.ti -1c
.RI "cmplx16ImRe_t \fBrxChPhaseComp\fP [SYS_COMMON_NUM_TX_ANTENNAS *SYS_COMMON_NUM_RX_CHANNEL]"
.br
.RI "Compensation for Rx channel phase bias in Q15 format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Range Bias and rx channel gain/phase compensation configuration\&. 


.PP
Definition at line 399 of file mrr_config\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float MmwDemo_compRxChannelBiasCfg_t_::rangeBias"

.PP
Compensation for range estimation bias\&. 
.PP
Definition at line 403 of file mrr_config\&.h\&.
.SS "cmplx16ImRe_t MmwDemo_compRxChannelBiasCfg_t_::rxChPhaseComp"

.PP
Compensation for Rx channel phase bias in Q15 format\&. 
.PP
Definition at line 406 of file mrr_config\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
