.TH "MmwDemo_PeakGroupingCfg_t" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_PeakGroupingCfg_t \- Millimeter Wave Demo Peak grouping Configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrr_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBminRangeIndex\fP"
.br
.RI "minimum range index exported "
.ti -1c
.RI "uint16_t \fBmaxRangeIndex\fP"
.br
.RI "maximum range index exported "
.ti -1c
.RI "uint8_t \fBscheme\fP"
.br
.RI "Peak grouping scheme 1-based on neighboring peaks from detection matrix 2-based on on neighboring CFAR detected peaks\&. "
.ti -1c
.RI "uint8_t \fBinRangeDirectionEn\fP"
.br
.RI "Grouping in range direction, 0- disbled, 1-enabled\&. "
.ti -1c
.RI "uint8_t \fBinDopplerDirectionEn\fP"
.br
.RI "Grouping in Doppler direction, 0- disbled, 1-enabled\&. "
.in -1c
.SH "Detailed Description"
.PP 
Millimeter Wave Demo Peak grouping Configuration\&. 

The structure contains the Peak grouping configuration used in data path 
.PP
Definition at line 90 of file mrr_config\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t MmwDemo_PeakGroupingCfg_t::inDopplerDirectionEn"

.PP
Grouping in Doppler direction, 0- disbled, 1-enabled\&. 
.PP
Definition at line 106 of file mrr_config\&.h\&.
.SS "uint8_t MmwDemo_PeakGroupingCfg_t::inRangeDirectionEn"

.PP
Grouping in range direction, 0- disbled, 1-enabled\&. 
.PP
Definition at line 103 of file mrr_config\&.h\&.
.SS "uint16_t MmwDemo_PeakGroupingCfg_t::maxRangeIndex"

.PP
maximum range index exported 
.PP
Definition at line 96 of file mrr_config\&.h\&.
.SS "uint16_t MmwDemo_PeakGroupingCfg_t::minRangeIndex"

.PP
minimum range index exported 
.PP
Definition at line 93 of file mrr_config\&.h\&.
.SS "uint8_t MmwDemo_PeakGroupingCfg_t::scheme"

.PP
Peak grouping scheme 1-based on neighboring peaks from detection matrix 2-based on on neighboring CFAR detected peaks\&. 
.PP
Definition at line 100 of file mrr_config\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
