.TH "MmwDemo_CliCfg_t_" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_CliCfg_t_ \- Millimeter Wave Demo CLI related configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrr_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMmwDemo_ADCBufCfg\fP \fBadcBufCfg\fP"
.br
.RI "ADCBUF Configuration\&. "
.ti -1c
.RI "\fBMmwDemo_GuiMonSel\fP \fBguiMonSel\fP"
.br
.RI "Gui Monitor Selection\&. "
.ti -1c
.RI "\fBMmwDemo_CfarCfg\fP \fBcfarCfgRange\fP"
.br
.RI "CFAR configuration for range\&. "
.ti -1c
.RI "\fBMmwDemo_CfarCfg\fP \fBcfarCfgDoppler\fP"
.br
.RI "CFAR configuration for doppler\&. "
.ti -1c
.RI "\fBMmwDemo_ExtendedMaxVelocityCfg\fP \fBextendedMaxVelocityCfg\fP"
.br
.RI "Velocity disambiguation configuration\&. "
.ti -1c
.RI "\fBMmwDemo_NearFieldCorrectionCfg\fP \fBnearFieldCorrectionCfg\fP"
.br
.RI "Near Field Correction configuration\&. "
.ti -1c
.RI "\fBMmwDemo_PeakGroupingCfg\fP \fBpeakGroupingCfg\fP"
.br
.RI "Peak grouping configuration\&. "
.ti -1c
.RI "\fBMmwDemo_MultiObjBeamFormingCfg\fP \fBmultiObjBeamFormingCfg\fP"
.br
.RI "Multi object beam forming configuration\&. "
.ti -1c
.RI "\fBMmwDemo_CalibDcRangeSigCfg\fP \fBcalibDcRangeSigCfg\fP"
.br
.RI "Calibrate DC (zero) range signature\&. "
.ti -1c
.RI "\fBMmwDemo_ClutterRemovalCfg\fP \fBclutterRemovalCfg\fP"
.br
.RI "Clutter removal configuration\&. "
.ti -1c
.RI "\fBMmwDemo_LvdsStreamCfg\fP \fBlvdsStreamCfg\fP"
.br
.RI "LVDS stream configuration\&. "
.in -1c
.SH "Detailed Description"
.PP 
Millimeter Wave Demo CLI related configuration\&. 
.PP
Definition at line 351 of file mrr_config\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBMmwDemo_ADCBufCfg\fP MmwDemo_CliCfg_t_::adcBufCfg"

.PP
ADCBUF Configuration\&. 
.PP
Definition at line 354 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_CalibDcRangeSigCfg\fP MmwDemo_CliCfg_t_::calibDcRangeSigCfg"

.PP
Calibrate DC (zero) range signature\&. 
.PP
Definition at line 382 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_CfarCfg\fP MmwDemo_CliCfg_t_::cfarCfgDoppler"

.PP
CFAR configuration for doppler\&. 
.PP
Definition at line 366 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_CfarCfg\fP MmwDemo_CliCfg_t_::cfarCfgRange"

.PP
CFAR configuration for range\&. 
.PP
Definition at line 363 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_ClutterRemovalCfg\fP MmwDemo_CliCfg_t_::clutterRemovalCfg"

.PP
Clutter removal configuration\&. 
.PP
Definition at line 385 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_ExtendedMaxVelocityCfg\fP MmwDemo_CliCfg_t_::extendedMaxVelocityCfg"

.PP
Velocity disambiguation configuration\&. 
.PP
Definition at line 369 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_GuiMonSel\fP MmwDemo_CliCfg_t_::guiMonSel"

.PP
Gui Monitor Selection\&. 
.PP
Definition at line 357 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_LvdsStreamCfg\fP MmwDemo_CliCfg_t_::lvdsStreamCfg"

.PP
LVDS stream configuration\&. 
.PP
Definition at line 392 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_MultiObjBeamFormingCfg\fP MmwDemo_CliCfg_t_::multiObjBeamFormingCfg"

.PP
Multi object beam forming configuration\&. 
.PP
Definition at line 379 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_NearFieldCorrectionCfg\fP MmwDemo_CliCfg_t_::nearFieldCorrectionCfg"

.PP
Near Field Correction configuration\&. 
.PP
Definition at line 372 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_PeakGroupingCfg\fP MmwDemo_CliCfg_t_::peakGroupingCfg"

.PP
Peak grouping configuration\&. 
.PP
Definition at line 376 of file mrr_config\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
