.TH "MmwDemo_msgTlv_t" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_msgTlv_t \- TLV part of the message from DSS to MSS on data path detection information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmw_messages\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.RI "Payload type\&. "
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.RI "Length in bytes\&. "
.ti -1c
.RI "uint32_t \fBaddress\fP"
.br
.RI "Address of the payload\&. "
.in -1c
.SH "Detailed Description"
.PP 
TLV part of the message from DSS to MSS on data path detection information\&. 

The structure describes the message item 
.PP
Definition at line 114 of file mmw_messages\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t MmwDemo_msgTlv_t::address"

.PP
Address of the payload\&. 
.PP
Definition at line 123 of file mmw_messages\&.h\&.
.SS "uint32_t MmwDemo_msgTlv_t::length"

.PP
Length in bytes\&. 
.PP
Definition at line 120 of file mmw_messages\&.h\&.
.SS "uint32_t MmwDemo_msgTlv_t::type"

.PP
Payload type\&. 
.PP
Definition at line 117 of file mmw_messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
