.TH "MmwDemo_output_message_dataObjDescr_t" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_output_message_dataObjDescr_t \- Structure holds information about detected objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrr_output\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBnumDetetedObj\fP"
.br
.RI "Number of detected objects\&. "
.ti -1c
.RI "uint16_t \fBxyzQFormat\fP"
.br
.RI "Q format of detected objects x/y/z coordinates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure holds information about detected objects\&. 

This information is sent in front of the array of detected objects 
.PP
Definition at line 165 of file mrr_output\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t MmwDemo_output_message_dataObjDescr_t::numDetetedObj"

.PP
Number of detected objects\&. 
.PP
Definition at line 168 of file mrr_output\&.h\&.
.SS "uint16_t MmwDemo_output_message_dataObjDescr_t::xyzQFormat"

.PP
Q format of detected objects x/y/z coordinates\&. 
.PP
Definition at line 171 of file mrr_output\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
