.TH "MmwDemo_CliCommonCfg_t_" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_CliCommonCfg_t_ \- Millimeter Wave Demo CLI related configuration common across all subframes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrr_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMmwDemo_compRxChannelBiasCfg_t\fP \fBcompRxChanCfg\fP"
.br
.RI "Configuration for compensation for range bias and Rx channel phase offset\&. "
.ti -1c
.RI "\fBMmwDemo_measureRxChannelBiasCfg_t\fP \fBmeasureRxChanCfg\fP"
.br
.RI "Configuration for measurement of range bias and Rx channel phase offset\&. "
.ti -1c
.RI "rlSigImgMonConf_t \fBcqSigImgMonCfg\fP [RL_MAX_PROFILES_CNT]"
.br
.RI "CQ monitor configuration - Signal Image band data\&. "
.ti -1c
.RI "rlRxSatMonConf_t \fBcqSatMonCfg\fP [RL_MAX_PROFILES_CNT]"
.br
.RI "CQ monitor configuration - Signal Image band data\&. "
.ti -1c
.RI "\fBMmwDemo_AnaMonitorCfg\fP \fBanaMonCfg\fP"
.br
.RI "Analog monitor bit mask\&. "
.in -1c
.SH "Detailed Description"
.PP 
Millimeter Wave Demo CLI related configuration common across all subframes\&. 
.PP
Definition at line 434 of file mrr_config\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBMmwDemo_AnaMonitorCfg\fP MmwDemo_CliCommonCfg_t_::anaMonCfg"

.PP
Analog monitor bit mask\&. 
.PP
Definition at line 451 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_compRxChannelBiasCfg_t\fP MmwDemo_CliCommonCfg_t_::compRxChanCfg"

.PP
Configuration for compensation for range bias and Rx channel phase offset\&. 
.PP
Definition at line 438 of file mrr_config\&.h\&.
.SS "rlRxSatMonConf_t MmwDemo_CliCommonCfg_t_::cqSatMonCfg"

.PP
CQ monitor configuration - Signal Image band data\&. 
.PP
Definition at line 448 of file mrr_config\&.h\&.
.SS "rlSigImgMonConf_t MmwDemo_CliCommonCfg_t_::cqSigImgMonCfg"

.PP
CQ monitor configuration - Signal Image band data\&. 
.PP
Definition at line 445 of file mrr_config\&.h\&.
.SS "\fBMmwDemo_measureRxChannelBiasCfg_t\fP MmwDemo_CliCommonCfg_t_::measureRxChanCfg"

.PP
Configuration for measurement of range bias and Rx channel phase offset\&. 
.PP
Definition at line 442 of file mrr_config\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
