.TH "MmwDemo_MSS_STATS_t" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MmwDemo_MSS_STATS_t \- Millimeter Wave Demo statistics\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mss_mrr\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBcliSensorStartEvt\fP"
.br
.ti -1c
.RI "uint8_t \fBcliSensorStopEvt\fP"
.br
.ti -1c
.RI "uint8_t \fBcliFrameStartEvt\fP"
.br
.ti -1c
.RI "uint8_t \fBdatapathConfigEvt\fP"
.br
.ti -1c
.RI "uint8_t \fBdatapathStartEvt\fP"
.br
.ti -1c
.RI "uint8_t \fBdatapathStopEvt\fP"
.br
.ti -1c
.RI "uint32_t \fBnumFailedTimingReports\fP"
.br
.ti -1c
.RI "uint32_t \fBnumCalibrationReports\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Millimeter Wave Demo statistics\&. 

The structure is used to hold the statistics information for the Millimeter Wave demo 
.PP
Definition at line 92 of file mss_mrr\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t MmwDemo_MSS_STATS_t::cliFrameStartEvt"

.PP
Definition at line 96 of file mss_mrr\&.h\&.
.SS "uint8_t MmwDemo_MSS_STATS_t::cliSensorStartEvt"

.PP
Definition at line 94 of file mss_mrr\&.h\&.
.SS "uint8_t MmwDemo_MSS_STATS_t::cliSensorStopEvt"

.PP
Definition at line 95 of file mss_mrr\&.h\&.
.SS "uint8_t MmwDemo_MSS_STATS_t::datapathConfigEvt"

.PP
Definition at line 98 of file mss_mrr\&.h\&.
.SS "uint8_t MmwDemo_MSS_STATS_t::datapathStartEvt"

.PP
Definition at line 99 of file mss_mrr\&.h\&.
.SS "uint8_t MmwDemo_MSS_STATS_t::datapathStopEvt"

.PP
Definition at line 100 of file mss_mrr\&.h\&.
.SS "uint32_t MmwDemo_MSS_STATS_t::numCalibrationReports"

.PP
Definition at line 103 of file mss_mrr\&.h\&.
.SS "uint32_t MmwDemo_MSS_STATS_t::numFailedTimingReports"

.PP
Definition at line 102 of file mss_mrr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
