.TH "C:/Users/astro/workspace_v9_2/mrr_18xx_dss/Debug/configPkg/package/package_configPkg.c" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/astro/workspace_v9_2/mrr_18xx_dss/Debug/configPkg/package/package_configPkg.c
.SH SYNOPSIS
.br
.PP
\fC#include <xdc/std\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__xdc_PKGVERS\fP   null"
.br
.ti -1c
.RI "#define \fB__xdc_PKGNAME\fP   \fBconfigPkg\fP"
.br
.ti -1c
.RI "#define \fB__xdc_PKGPREFIX\fP   configPkg_"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "__FAR__ char \fBconfigPkg__dummy__\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __xdc_PKGNAME   \fBconfigPkg\fP"

.PP
Definition at line 13 of file package_configPkg\&.c\&.
.SS "#define __xdc_PKGPREFIX   configPkg_"

.PP
Definition at line 14 of file package_configPkg\&.c\&.
.SS "#define __xdc_PKGVERS   null"

.PP
Definition at line 12 of file package_configPkg\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "__FAR__ char configPkg__dummy__"

.PP
Definition at line 10 of file package_configPkg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
