.TH "ti_sysbios_timers_rti_Timer_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_timers_rti_Timer_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_UInt \fBavailMask\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_timers_rti_Timer_Module_State__device \fBdevice\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_timers_rti_Timer_Module_State__intFreqs \fBintFreqs\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_timers_rti_Timer_Module_State__handles \fBhandles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1402 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_UInt ti_sysbios_timers_rti_Timer_Module_State__::availMask"

.PP
Definition at line 1403 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State__::device"

.PP
Definition at line 1404 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State__::handles"

.PP
Definition at line 1406 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State__::intFreqs"

.PP
Definition at line 1405 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
