.TH "ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_Ptr \fBcurrentTP\fP"
.br
.ti -1c
.RI "xdc_UInt \fBcontextId\fP"
.br
.ti -1c
.RI "xdc_runtime_IHeap_Handle \fBheapHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1637 of file dss_mrr_pe674\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_UInt ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__::contextId"

.PP
Definition at line 1639 of file dss_mrr_pe674\&.c\&.
.SS "xdc_Ptr ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__::currentTP"

.PP
Definition at line 1638 of file dss_mrr_pe674\&.c\&.
.SS "xdc_runtime_IHeap_Handle ti_sysbios_rts_ti_ThreadLocalStorage_Module_State__::heapHandle"

.PP
Definition at line 1640 of file dss_mrr_pe674\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
