.TH "ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_Char * \fBtaskSP\fP"
.br
.ti -1c
.RI "xdc_Char * \fBisrStack\fP"
.br
.ti -1c
.RI "xdc_Ptr \fBisrStackBase\fP"
.br
.ti -1c
.RI "xdc_Ptr \fBisrStackSize\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__fiqStack \fBfiqStack\fP"
.br
.ti -1c
.RI "xdc_SizeT \fBfiqStackSize\fP"
.br
.ti -1c
.RI "xdc_UInt * \fBvimRam\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__dispatchTable \fBdispatchTable\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__zeroLatencyFIQMask \fBzeroLatencyFIQMask\fP"
.br
.ti -1c
.RI "xdc_UInt \fBspuriousInts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1058 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "__TA_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__dispatchTable ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::dispatchTable"

.PP
Definition at line 1066 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::fiqStack"

.PP
Definition at line 1063 of file mss_mrr_per4f\&.c\&.
.SS "xdc_SizeT ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::fiqStackSize"

.PP
Definition at line 1064 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Char* ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::isrStack"

.PP
Definition at line 1060 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::isrStackBase"

.PP
Definition at line 1061 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::isrStackSize"

.PP
Definition at line 1062 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::spuriousInts"

.PP
Definition at line 1068 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Char* ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::taskSP"

.PP
Definition at line 1059 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt* ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::vimRam"

.PP
Definition at line 1065 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__zeroLatencyFIQMask ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__::zeroLatencyFIQMask"

.PP
Definition at line 1067 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
