.TH "ti_sysbios_heaps_HeapMem_Object__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_heaps_HeapMem_Object__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const ti_sysbios_heaps_HeapMem_Fxns__ * \fB__fxns\fP"
.br
.ti -1c
.RI "xdc_runtime_Memory_Size \fBalign\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_heaps_HeapMem_Instance_State__buf \fBbuf\fP"
.br
.ti -1c
.RI "ti_sysbios_heaps_HeapMem_Header \fBhead\fP"
.br
.ti -1c
.RI "xdc_SizeT \fBminBlockAlign\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 366 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "const ti_sysbios_heaps_HeapMem_Fxns__ * ti_sysbios_heaps_HeapMem_Object__::__fxns"

.PP
Definition at line 367 of file mss_mrr_per4f\&.c\&.
.SS "xdc_runtime_Memory_Size ti_sysbios_heaps_HeapMem_Object__::align"

.PP
Definition at line 368 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Object__::buf"

.PP
Definition at line 369 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_heaps_HeapMem_Header ti_sysbios_heaps_HeapMem_Object__::head"

.PP
Definition at line 370 of file mss_mrr_per4f\&.c\&.
.SS "xdc_SizeT ti_sysbios_heaps_HeapMem_Object__::minBlockAlign"

.PP
Definition at line 371 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
