.TH "ti_sysbios_knl_Swi_Object__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_knl_Swi_Object__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ti_sysbios_knl_Queue_Elem \fBqElem\fP"
.br
.ti -1c
.RI "ti_sysbios_knl_Swi_FuncPtr \fBfxn\fP"
.br
.ti -1c
.RI "xdc_UArg \fBarg0\fP"
.br
.ti -1c
.RI "xdc_UArg \fBarg1\fP"
.br
.ti -1c
.RI "xdc_UInt \fBpriority\fP"
.br
.ti -1c
.RI "xdc_UInt \fBmask\fP"
.br
.ti -1c
.RI "xdc_Bool \fBposted\fP"
.br
.ti -1c
.RI "xdc_UInt \fBinitTrigger\fP"
.br
.ti -1c
.RI "xdc_UInt \fBtrigger\fP"
.br
.ti -1c
.RI "ti_sysbios_knl_Queue_Handle \fBreadyQ\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_knl_Swi_Instance_State__hookEnv \fBhookEnv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 568 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_UArg ti_sysbios_knl_Swi_Object__::arg0"

.PP
Definition at line 571 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UArg ti_sysbios_knl_Swi_Object__::arg1"

.PP
Definition at line 572 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Swi_FuncPtr ti_sysbios_knl_Swi_Object__::fxn"

.PP
Definition at line 570 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_knl_Swi_Instance_State__hookEnv ti_sysbios_knl_Swi_Object__::hookEnv"

.PP
Definition at line 579 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Swi_Object__::initTrigger"

.PP
Definition at line 576 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Swi_Object__::mask"

.PP
Definition at line 574 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Bool ti_sysbios_knl_Swi_Object__::posted"

.PP
Definition at line 575 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Swi_Object__::priority"

.PP
Definition at line 573 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Queue_Elem ti_sysbios_knl_Swi_Object__::qElem"

.PP
Definition at line 569 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Swi_Object__::readyQ"

.PP
Definition at line 578 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Swi_Object__::trigger"

.PP
Definition at line 577 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
