.TH "ti_sysbios_family_c64p_Cache_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_family_c64p_Cache_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile xdc_UInt32 * \fBemifAddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 943 of file dss_mrr_pe674\&.c\&.
.SH "Field Documentation"
.PP 
.SS "volatile xdc_UInt32* ti_sysbios_family_c64p_Cache_Module_State__::emifAddr"

.PP
Definition at line 944 of file dss_mrr_pe674\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
