.TH "ti_sysbios_knl_Swi_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_knl_Swi_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile xdc_Bool \fBlocked\fP"
.br
.ti -1c
.RI "xdc_UInt \fBcurSet\fP"
.br
.ti -1c
.RI "xdc_UInt \fBcurTrigger\fP"
.br
.ti -1c
.RI "ti_sysbios_knl_Swi_Handle \fBcurSwi\fP"
.br
.ti -1c
.RI "ti_sysbios_knl_Queue_Handle \fBcurQ\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_knl_Swi_Module_State__readyQ \fBreadyQ\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_knl_Swi_Module_State__constructedSwis \fBconstructedSwis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1307 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "__TA_ti_sysbios_knl_Swi_Module_State__constructedSwis ti_sysbios_knl_Swi_Module_State__::constructedSwis"

.PP
Definition at line 1314 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Swi_Module_State__::curQ"

.PP
Definition at line 1312 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Swi_Module_State__::curSet"

.PP
Definition at line 1309 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Swi_Handle ti_sysbios_knl_Swi_Module_State__::curSwi"

.PP
Definition at line 1311 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Swi_Module_State__::curTrigger"

.PP
Definition at line 1310 of file mss_mrr_per4f\&.c\&.
.SS "volatile xdc_Bool ti_sysbios_knl_Swi_Module_State__::locked"

.PP
Definition at line 1308 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_knl_Swi_Module_State__readyQ ti_sysbios_knl_Swi_Module_State__::readyQ"

.PP
Definition at line 1313 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
