.TH "ti_sysbios_knl_Clock_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_knl_Clock_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile xdc_UInt32 \fBticks\fP"
.br
.ti -1c
.RI "xdc_UInt \fBswiCount\fP"
.br
.ti -1c
.RI "ti_sysbios_knl_Clock_TimerProxy_Handle \fBtimer\fP"
.br
.ti -1c
.RI "ti_sysbios_knl_Swi_Handle \fBswi\fP"
.br
.ti -1c
.RI "volatile xdc_UInt \fBnumTickSkip\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBnextScheduledTick\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBmaxSkippable\fP"
.br
.ti -1c
.RI "xdc_Bool \fBinWorkFunc\fP"
.br
.ti -1c
.RI "volatile xdc_Bool \fBstartDuringWorkFunc\fP"
.br
.ti -1c
.RI "xdc_Bool \fBticking\fP"
.br
.ti -1c
.RI "\fBti_sysbios_knl_Queue_Object__\fP \fBObject_field_clockQ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1234 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_Bool ti_sysbios_knl_Clock_Module_State__::inWorkFunc"

.PP
Definition at line 1242 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt32 ti_sysbios_knl_Clock_Module_State__::maxSkippable"

.PP
Definition at line 1241 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt32 ti_sysbios_knl_Clock_Module_State__::nextScheduledTick"

.PP
Definition at line 1240 of file mss_mrr_per4f\&.c\&.
.SS "volatile xdc_UInt ti_sysbios_knl_Clock_Module_State__::numTickSkip"

.PP
Definition at line 1239 of file mss_mrr_per4f\&.c\&.
.SS "\fBti_sysbios_knl_Queue_Object__\fP ti_sysbios_knl_Clock_Module_State__::Object_field_clockQ"

.PP
Definition at line 1245 of file mss_mrr_per4f\&.c\&.
.SS "volatile xdc_Bool ti_sysbios_knl_Clock_Module_State__::startDuringWorkFunc"

.PP
Definition at line 1243 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Swi_Handle ti_sysbios_knl_Clock_Module_State__::swi"

.PP
Definition at line 1238 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_knl_Clock_Module_State__::swiCount"

.PP
Definition at line 1236 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Bool ti_sysbios_knl_Clock_Module_State__::ticking"

.PP
Definition at line 1244 of file mss_mrr_per4f\&.c\&.
.SS "volatile xdc_UInt32 ti_sysbios_knl_Clock_Module_State__::ticks"

.PP
Definition at line 1235 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_Module_State__::timer"

.PP
Definition at line 1237 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
