.TH "ti_sysbios_BIOS_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_BIOS_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_runtime_Types_FreqHz \fBcpuFreq\fP"
.br
.ti -1c
.RI "xdc_UInt \fBrtsGateCount\fP"
.br
.ti -1c
.RI "xdc_IArg \fBrtsGateKey\fP"
.br
.ti -1c
.RI "ti_sysbios_BIOS_RtsGateProxy_Handle \fBrtsGate\fP"
.br
.ti -1c
.RI "ti_sysbios_BIOS_ThreadType \fBthreadType\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_BIOS_Module_State__smpThreadType \fBsmpThreadType\fP"
.br
.ti -1c
.RI "volatile ti_sysbios_BIOS_StartFuncPtr \fBstartFunc\fP"
.br
.ti -1c
.RI "volatile ti_sysbios_BIOS_ExitFuncPtr \fBexitFunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 963 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_runtime_Types_FreqHz ti_sysbios_BIOS_Module_State__::cpuFreq"

.PP
Definition at line 964 of file mss_mrr_per4f\&.c\&.
.SS "volatile ti_sysbios_BIOS_ExitFuncPtr ti_sysbios_BIOS_Module_State__::exitFunc"

.PP
Definition at line 971 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_Module_State__::rtsGate"

.PP
Definition at line 967 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_BIOS_Module_State__::rtsGateCount"

.PP
Definition at line 965 of file mss_mrr_per4f\&.c\&.
.SS "xdc_IArg ti_sysbios_BIOS_Module_State__::rtsGateKey"

.PP
Definition at line 966 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_BIOS_Module_State__smpThreadType ti_sysbios_BIOS_Module_State__::smpThreadType"

.PP
Definition at line 969 of file mss_mrr_per4f\&.c\&.
.SS "volatile ti_sysbios_BIOS_StartFuncPtr ti_sysbios_BIOS_Module_State__::startFunc"

.PP
Definition at line 970 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_BIOS_ThreadType ti_sysbios_BIOS_Module_State__::threadType"

.PP
Definition at line 968 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
