.TH "ti_sysbios_timers_rti_Timer_Object__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_timers_rti_Timer_Object__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const ti_sysbios_timers_rti_Timer_Fxns__ * \fB__fxns\fP"
.br
.ti -1c
.RI "xdc_Bool \fBstaticInst\fP"
.br
.ti -1c
.RI "xdc_Int \fBid\fP"
.br
.ti -1c
.RI "ti_sysbios_interfaces_ITimer_RunMode \fBrunMode\fP"
.br
.ti -1c
.RI "ti_sysbios_interfaces_ITimer_StartMode \fBstartMode\fP"
.br
.ti -1c
.RI "xdc_UInt \fBprescale\fP"
.br
.ti -1c
.RI "xdc_UInt \fBperiod\fP"
.br
.ti -1c
.RI "ti_sysbios_interfaces_ITimer_PeriodType \fBperiodType\fP"
.br
.ti -1c
.RI "xdc_UInt \fBintNum\fP"
.br
.ti -1c
.RI "xdc_UArg \fBarg\fP"
.br
.ti -1c
.RI "ti_sysbios_hal_Hwi_FuncPtr \fBtickFxn\fP"
.br
.ti -1c
.RI "xdc_runtime_Types_FreqHz \fBextFreq\fP"
.br
.ti -1c
.RI "ti_sysbios_hal_Hwi_Handle \fBhwi\fP"
.br
.ti -1c
.RI "xdc_Bool \fBcreateHwi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 450 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "const ti_sysbios_timers_rti_Timer_Fxns__ * ti_sysbios_timers_rti_Timer_Object__::__fxns"

.PP
Definition at line 451 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UArg ti_sysbios_timers_rti_Timer_Object__::arg"

.PP
Definition at line 460 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Bool ti_sysbios_timers_rti_Timer_Object__::createHwi"

.PP
Definition at line 464 of file mss_mrr_per4f\&.c\&.
.SS "xdc_runtime_Types_FreqHz ti_sysbios_timers_rti_Timer_Object__::extFreq"

.PP
Definition at line 462 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_hal_Hwi_Handle ti_sysbios_timers_rti_Timer_Object__::hwi"

.PP
Definition at line 463 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Int ti_sysbios_timers_rti_Timer_Object__::id"

.PP
Definition at line 453 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_timers_rti_Timer_Object__::intNum"

.PP
Definition at line 459 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_timers_rti_Timer_Object__::period"

.PP
Definition at line 457 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_interfaces_ITimer_PeriodType ti_sysbios_timers_rti_Timer_Object__::periodType"

.PP
Definition at line 458 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_timers_rti_Timer_Object__::prescale"

.PP
Definition at line 456 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_interfaces_ITimer_RunMode ti_sysbios_timers_rti_Timer_Object__::runMode"

.PP
Definition at line 454 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_interfaces_ITimer_StartMode ti_sysbios_timers_rti_Timer_Object__::startMode"

.PP
Definition at line 455 of file mss_mrr_per4f\&.c\&.
.SS "xdc_Bool ti_sysbios_timers_rti_Timer_Object__::staticInst"

.PP
Definition at line 452 of file mss_mrr_per4f\&.c\&.
.SS "ti_sysbios_hal_Hwi_FuncPtr ti_sysbios_timers_rti_Timer_Object__::tickFxn"

.PP
Definition at line 461 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
