.TH "ti_sysbios_knl_Event_Object__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_knl_Event_Object__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile xdc_UInt \fBpostedEvents\fP"
.br
.ti -1c
.RI "\fBti_sysbios_knl_Queue_Object__\fP \fBObject_field_pendQ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 498 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBti_sysbios_knl_Queue_Object__\fP ti_sysbios_knl_Event_Object__::Object_field_pendQ"

.PP
Definition at line 500 of file mss_mrr_per4f\&.c\&.
.SS "volatile xdc_UInt ti_sysbios_knl_Event_Object__::postedEvents"

.PP
Definition at line 499 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
