.TH "ti_sysbios_heaps_HeapBuf_Object__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_heaps_HeapBuf_Object__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const ti_sysbios_heaps_HeapBuf_Fxns__ * \fB__fxns\fP"
.br
.ti -1c
.RI "xdc_SizeT \fBblockSize\fP"
.br
.ti -1c
.RI "xdc_SizeT \fBalign\fP"
.br
.ti -1c
.RI "xdc_UInt \fBnumBlocks\fP"
.br
.ti -1c
.RI "xdc_runtime_Memory_Size \fBbufSize\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_heaps_HeapBuf_Instance_State__buf \fBbuf\fP"
.br
.ti -1c
.RI "xdc_UInt \fBnumFreeBlocks\fP"
.br
.ti -1c
.RI "xdc_UInt \fBminFreeBlocks\fP"
.br
.ti -1c
.RI "\fBti_sysbios_knl_Queue_Object__\fP \fBObject_field_freeList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 334 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "const ti_sysbios_heaps_HeapBuf_Fxns__* ti_sysbios_heaps_HeapBuf_Object__::__fxns"

.PP
Definition at line 335 of file mss_mrr_per4f\&.c\&.
.SS "xdc_SizeT ti_sysbios_heaps_HeapBuf_Object__::align"

.PP
Definition at line 337 of file mss_mrr_per4f\&.c\&.
.SS "xdc_SizeT ti_sysbios_heaps_HeapBuf_Object__::blockSize"

.PP
Definition at line 336 of file mss_mrr_per4f\&.c\&.
.SS "__TA_ti_sysbios_heaps_HeapBuf_Instance_State__buf ti_sysbios_heaps_HeapBuf_Object__::buf"

.PP
Definition at line 340 of file mss_mrr_per4f\&.c\&.
.SS "xdc_runtime_Memory_Size ti_sysbios_heaps_HeapBuf_Object__::bufSize"

.PP
Definition at line 339 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_heaps_HeapBuf_Object__::minFreeBlocks"

.PP
Definition at line 342 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_heaps_HeapBuf_Object__::numBlocks"

.PP
Definition at line 338 of file mss_mrr_per4f\&.c\&.
.SS "xdc_UInt ti_sysbios_heaps_HeapBuf_Object__::numFreeBlocks"

.PP
Definition at line 341 of file mss_mrr_per4f\&.c\&.
.SS "\fBti_sysbios_knl_Queue_Object__\fP ti_sysbios_heaps_HeapBuf_Object__::Object_field_freeList"

.PP
Definition at line 343 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
