.TH "ti_sysbios_utils_Load_Module_State__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ti_sysbios_utils_Load_Module_State__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_Int \fBtaskHId\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_utils_Load_Module_State__taskStartTime \fBtaskStartTime\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBtimeElapsed\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_utils_Load_Module_State__runningTask \fBrunningTask\fP"
.br
.ti -1c
.RI "xdc_Bool \fBfirstSwitchDone\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBswiStartTime\fP"
.br
.ti -1c
.RI "ti_sysbios_utils_Load_HookContext \fBswiEnv\fP"
.br
.ti -1c
.RI "__TA_ti_sysbios_utils_Load_Module_State__taskEnv \fBtaskEnv\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBswiCnt\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBhwiStartTime\fP"
.br
.ti -1c
.RI "ti_sysbios_utils_Load_HookContext \fBhwiEnv\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBhwiCnt\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBtimeSlotCnt\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBminLoop\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBminIdle\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBt0\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBidleCnt\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBcpuLoad\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBtaskEnvLen\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBtaskNum\fP"
.br
.ti -1c
.RI "xdc_Bool \fBpowerEnabled\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBidleStartTime\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBbusyStartTime\fP"
.br
.ti -1c
.RI "xdc_UInt32 \fBbusyTime\fP"
.br
.ti -1c
.RI "\fBti_sysbios_knl_Queue_Object__\fP \fBObject_field_taskList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1680 of file dss_mrr_pe674\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::busyStartTime"

.PP
Definition at line 1703 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::busyTime"

.PP
Definition at line 1704 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::cpuLoad"

.PP
Definition at line 1698 of file dss_mrr_pe674\&.c\&.
.SS "xdc_Bool ti_sysbios_utils_Load_Module_State__::firstSwitchDone"

.PP
Definition at line 1685 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::hwiCnt"

.PP
Definition at line 1692 of file dss_mrr_pe674\&.c\&.
.SS "ti_sysbios_utils_Load_HookContext ti_sysbios_utils_Load_Module_State__::hwiEnv"

.PP
Definition at line 1691 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::hwiStartTime"

.PP
Definition at line 1690 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::idleCnt"

.PP
Definition at line 1697 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::idleStartTime"

.PP
Definition at line 1702 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::minIdle"

.PP
Definition at line 1695 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::minLoop"

.PP
Definition at line 1694 of file dss_mrr_pe674\&.c\&.
.SS "\fBti_sysbios_knl_Queue_Object__\fP ti_sysbios_utils_Load_Module_State__::Object_field_taskList"

.PP
Definition at line 1705 of file dss_mrr_pe674\&.c\&.
.SS "xdc_Bool ti_sysbios_utils_Load_Module_State__::powerEnabled"

.PP
Definition at line 1701 of file dss_mrr_pe674\&.c\&.
.SS "__TA_ti_sysbios_utils_Load_Module_State__runningTask ti_sysbios_utils_Load_Module_State__::runningTask"

.PP
Definition at line 1684 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::swiCnt"

.PP
Definition at line 1689 of file dss_mrr_pe674\&.c\&.
.SS "ti_sysbios_utils_Load_HookContext ti_sysbios_utils_Load_Module_State__::swiEnv"

.PP
Definition at line 1687 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::swiStartTime"

.PP
Definition at line 1686 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::t0"

.PP
Definition at line 1696 of file dss_mrr_pe674\&.c\&.
.SS "__TA_ti_sysbios_utils_Load_Module_State__taskEnv ti_sysbios_utils_Load_Module_State__::taskEnv"

.PP
Definition at line 1688 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::taskEnvLen"

.PP
Definition at line 1699 of file dss_mrr_pe674\&.c\&.
.SS "xdc_Int ti_sysbios_utils_Load_Module_State__::taskHId"

.PP
Definition at line 1681 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::taskNum"

.PP
Definition at line 1700 of file dss_mrr_pe674\&.c\&.
.SS "__TA_ti_sysbios_utils_Load_Module_State__taskStartTime ti_sysbios_utils_Load_Module_State__::taskStartTime"

.PP
Definition at line 1682 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::timeElapsed"

.PP
Definition at line 1683 of file dss_mrr_pe674\&.c\&.
.SS "xdc_UInt32 ti_sysbios_utils_Load_Module_State__::timeSlotCnt"

.PP
Definition at line 1693 of file dss_mrr_pe674\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
