.TH "trackingInputReport" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trackingInputReport \- Input to tracking from the clustering output\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dss_data_path\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBxSize\fP"
.br
.ti -1c
.RI "int16_t \fBySize\fP"
.br
.ti -1c
.RI "float \fBmeasVec\fP [3]"
.br
.ti -1c
.RI "float \fBmeasCovVec\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Input to tracking from the clustering output\&. 
.PP
Definition at line 358 of file dss_data_path\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float trackingInputReport::measCovVec[3]"
Measurement covariance\&. 
.PP
Definition at line 363 of file dss_data_path\&.h\&.
.SS "float trackingInputReport::measVec[3]"
Measurement input 
.PP
Definition at line 362 of file dss_data_path\&.h\&.
.SS "int16_t trackingInputReport::xSize"
the clustering size on x direction 
.PP
Definition at line 360 of file dss_data_path\&.h\&.
.SS "int16_t trackingInputReport::ySize"
the clustering size on y direction 
.PP
Definition at line 361 of file dss_data_path\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
