.TH "xdc_runtime_System_Module_GateProxy_Module__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xdc_runtime_System_Module_GateProxy_Module__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_runtime_Types_Link \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 774 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_runtime_Types_Link xdc_runtime_System_Module_GateProxy_Module__::link"

.PP
Definition at line 775 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
