.TH "xdc_runtime_Memory_HeapProxy_Object2__" 3 "Wed May 20 2020" "Version 1.0" "mmWaveFMCWRADAR" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xdc_runtime_Memory_HeapProxy_Object2__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xdc_runtime_Types_InstHdr \fBhdr\fP"
.br
.ti -1c
.RI "\fBxdc_runtime_Memory_HeapProxy_Object__\fP \fBobj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 743 of file mss_mrr_per4f\&.c\&.
.SH "Field Documentation"
.PP 
.SS "xdc_runtime_Types_InstHdr xdc_runtime_Memory_HeapProxy_Object2__::hdr"

.PP
Definition at line 744 of file mss_mrr_per4f\&.c\&.
.SS "\fBxdc_runtime_Memory_HeapProxy_Object__\fP xdc_runtime_Memory_HeapProxy_Object2__::obj"

.PP
Definition at line 745 of file mss_mrr_per4f\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mmWaveFMCWRADAR from the source code\&.
